### ISSUE TITLE
Unable to change flagship

### ISSUE THREAD

**Issue by dtdog** [LmeSzinc/AzurLaneAutoScript#1003]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

Flagship change in Gems Farming was stuck since the newest update. It stopped at Formation screen , keep restarting and then stuck again
Sorry for bad English

### Screenshots

![Untitled](https://user-images.githubusercontent.com/80538869/162585333-4c76d5c0-e887-4062-9494-f0989b257f57.jpg)

**Comment by nEEtdo0d** [comment]
I don't use the module myself, so report back if still stuck. Logs and screenshots (either through ALAS or using the emulator) will help isolate where the next problem might be.

**Comment by dtdog** [comment]
> I don't use the module myself, so report back if still stuck. Logs and screenshots (either through ALAS or using the emulator) will help isolate where the next problem might be.

It worked, perfectly fine now. THANK YOU!
