### ISSUE TITLE
cannot import name 'check_model_name' from 'cnocr.cn_ocr'

### ISSUE THREAD

**Issue by lovelessangel** [LmeSzinc/AzurLaneAutoScript#103]
前天（还是哪天）的版本没有问题，今天更新后出现此问题。
![捕获](https://user-images.githubusercontent.com/6416397/87903946-d459a400-ca8f-11ea-8dd0-a4e3b99d4865.PNG)

**Comment by whoamikyo** [comment]
We updated the dependencies, I do not know if you use the alas with alas.bat or do everything manually, I advise to do a new installation from scratch using the easy_install method :

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/Installation_cn.md

**Comment by LmeSzinc** [comment]
最近有一次依赖更新, 建议重新安装Alas. 记得备份配置文件 config/alas.ini, 然后粘贴到新Alas的 config 目录下
以后的依赖更新可以通过 alas.bat 执行了, 不需要手动重装了

**Comment by lovelessangel** [comment]
> We updated the dependencies, I do not know if you use the alas with alas.bat or do everything manually, I advise to do a new installation from scratch using the easy_install method :
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/Installation_cn.md

It works, thx!

**Comment by lovelessangel** [comment]
> 最近有一次依赖更新, 建议重新安装Alas. 记得备份配置文件 config/alas.ini, 然后粘贴到新Alas的 config 目录下
> 以后的依赖更新可以通过 alas.bat 执行了, 不需要手动重装了

感谢，问题已解决。
