### ISSUE TITLE
能否添加一个每天点击几下商店明石的功能

### ISSUE THREAD

**Issue by yxzwym** [LmeSzinc/AzurLaneAutoScript#1034]
### 你的功能请求是否与问题有关？

点明石可以增加好感，增加好感会随机送礼物，这个有时候自己会忘记点，所以希望加上这个功能

### 解决方案

每天点几下明石就行

**Comment by LmeSzinc** [comment]
明石送礼物是怎么送的，我都忘了，是原地弹礼物，还是明天发邮件

**Comment by yxzwym** [comment]
隔天发邮件吧，不是原地弹，我昨天连续收到三封邮件

![1](https://user-images.githubusercontent.com/68624884/163735573-11ed79e8-aeed-4ae4-8bdb-ab0574d81fb6.jpg)

**Comment by yxzwym** [comment]
原来这个礼物只会送一次，我还以为会循环赠送...
