### ISSUE TITLE
识别科研Invalid后，能否delay 5秒钟再识别一次，连续2~3次Invalid再抛弃这个科研

### ISSUE THREAD

**Issue by mofaxiaoyuan** [LmeSzinc/AzurLaneAutoScript#1037]
### 你的功能请求是否与问题有关？

埃吉尔定向恰巧被挡住了，识别出Invalid，然后根据优先级执行了reset
![image](https://user-images.githubusercontent.com/44281183/163774162-d23c6025-9bc2-4f65-b52b-5a785630a2ba.png)

### 解决方案

这里能否delay 5秒钟再识别一次，连续2~3次Invalid再抛弃这个科研

**Comment by mofaxiaoyuan** [comment]
close

**Comment by LmeSzinc** [comment]
怎么就关了

提供一个大月卡横幅弹窗的图片吧，做起来不难，只是优先级不高，有感兴趣的可以直接做，然后PR。
判断横幅是否出现，等待横幅消失，重新识别。

![battle_pass_info](https://user-images.githubusercontent.com/37934724/166054391-62812b4f-923c-4632-84b9-1f95e7a8d599.png)
