### ISSUE TITLE
Non-blocking drop record upload

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1046]
### Is your feature request related to a problem?

Drop screenshots are now uploading to https://azur-stats.lyoko.io/, a poor server using free Cloudflare CDN. Turn it into a non-blocking upload, see code in `module/statistics/azurstats.py`.

**Comment by hgjazhgj** [comment]
Wiki 2.1. Debugging mentions that alas is single-process and single-threaded, do you mind creating a separate thread to upload the image? and ignore the return value of AzurStats._upload but only log it?

**Comment by LmeSzinc** [comment]
> Wiki 2.1. Debugging mentions that alas is single-process and single-threaded, do you mind creating a separate thread to upload the image? and ignore the return value of AzurStats._upload but only log it?

Return value can be discarded

**Comment by LmeSzinc** [comment]
现在有国内代理了，所以这个功能不需要了
