### ISSUE TITLE
"由于目标计算机积极拒绝,无法连接(10061)"该怎么解决?

### ISSUE THREAD

**Issue by yanabcd** [LmeSzinc/AzurLaneAutoScript#106]
我q2278551252,可以的话联系我交个朋友

**Comment by LmeSzinc** [comment]
检查一下, 有没有在把设备设置下的serial, 修改为自己模拟器的serial, 并点击运行来保存.
详见[中文安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/Installation_cn.md) 傻瓜式安装教程的第5步: 检查模拟器连接

另外, 你QQ有验证问题, 加不了.

**Comment by yanabcd** [comment]
e好的谢谢,以前设置时候忘改回来了

**Comment by yanabcd** [comment]
上面我说的是qq

**Comment by yanabcd** [comment]
我下载的是夜神模拟器,按理来说我应该使用你提供的serial,我查了,也就是:127.0.0.1:62001,但是还是报这个错误"由于目标计算机~",我该怎么办,能留下你的联系方式吗

**Comment by LmeSzinc** [comment]
我建了一个QQ群1087735381, 可以在里面找到我

**Comment by LmeSzinc** [comment]
问题已通过私聊解决.

原因排查:
执行 `adb devices`, 得到:
```
adb server version (36) doesn't match this client (41); killing...
* daemon started successfully
List of devices attached
```
说明模拟器在使用低版本的ADB, 而Alas使用的是最新的ADB.
不同版本之间的ADB会互相结束对方, 因此导致无法连接.

解决方法:
按照 [常见问题解答](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/FAQ_en_cn.md) 中的 "为什么我打开另一个模拟器时Alas会断开连接" 小节, 将模拟器中的ADB替换为Alas使用的ADB, 即可解决.
