### ISSUE TITLE
希望在出现 walk_out_of_step 错误时，可以自动退出攻略中的海域

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#1064]
### 你的功能请求是否与问题有关？

长期以来，Alas 在遇到 walk_out_of_step 错误时只会停止全部功能，没有任何恢复机制。在开荒活动海域时，必须人工监控 Alas 的工作状态，这与“把一切都交给 Alas”的理念不符。但 Alas 已经具备一些从海域出击错误中恢复的能力：如果在出击时出现 wait too long 错误，alas会自动重启碧蓝航线客户端。

### 解决方案

出现 walk_out_of_step 错误时，自动退出正在出击的海域，此后可以重新尝试出击，或改为执行调度器中的其他任务。

**Comment by LmeSzinc** [comment]
MapWalkError('walk_out_of_step') 在抛出时，Alas 已经尝试过解决了，解决不了才会最终报错。胡乱重试会带来很多问题，比如用户的舰队步长设置错了会无限进图撤退。

你应该做的：把错误log发出来

**Comment by DebuAqua** [comment]
> MapWalkError('walk_out_of_step') 在抛出时，Alas 已经尝试过解决了，解决不了才会最终报错。胡乱重试会带来很多问题，比如用户的舰队步长设置错了会无限进图撤退。
> 
> 你应该做的：把错误log发出来

既然如此，希望能修改出现抛出 MapWalkError('walk_out_of_step') 时的日志提示，建议用户检查设置或联系作者

**Comment by DebuAqua** [comment]
> MapWalkError('walk_out_of_step') 在抛出时，Alas 已经尝试过解决了，解决不了才会最终报错。胡乱重试会带来很多问题，比如用户的舰队步长设置错了会无限进图撤退。
> 
> 你应该做的：把错误log发出来

录制了本次活动海域开荒中的 walk_out_of_step 异常，已提交至 #1066 。
从视频中可以发现，目前的  walk_out_of_step 解决方法存在问题：二队完全没有移动，Alas 却认为此舰队已经“移动”到超出步长的格子中。
我的建议也包括改为**执行调度器中的其他任务**，这样可以保证用户仍然获得委托、战术学院、科研、后宅等收益，并非所谓“胡乱重试”。
