### ISSUE TITLE
海域开荒中，且BOSS出现在地图边缘时，反复尝试滑动地图（Too many click for a button: MAP_SWIPE_0_-2）

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#1072]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

这次录制了[从进入海域到重启的完整录像](https://www.youtube.com/watch?v=Wu6_5cZzskM)

4:12处，BOSS在海域地图出现。此后，Alas 只在尝试滑动地图，似乎当前地图上方还有人眼无法观察的“神秘区域”，直到抛出 `Too many click for a button: MAP_SWIPE_0_-2   ` 异常。

尝试用 `Map swipe` 和 `MAP_SWIPE` 关键词检查过往 issue ，发现 #857 和 #1055 与此问题高度相同。此问题可能与 PC 配置问题无关。

### 如何复现

活动图关卡名称设置为D1
关闭周回模式、自律寻敌、高效作战书
（但根据 #1055 报告，此问题可能不限于活动图）

### 预期行为

可以正常处理地图边缘的 BOSS ，完成开荒。

### 相关 Logs

```Text
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/8591476/log.txt)
```

### 截图

![2022-04-29_21-49-18-724598](https://user-images.githubusercontent.com/70339606/165963671-281e5f7f-f701-4346-9d26-5bd5ace0f73f.png)

**Comment by orangecathead** [comment]
一样的问题，24年依旧存在

**Comment by wuyns** [comment]
新的活动图T1也出现了同样的问题，在右上角反复滑
