### ISSUE TITLE
手机使用adb修改分辨率为1280*720但是alas获取的分辨率还是[Screen_size] 1440x2560 允许错误

### ISSUE THREAD

**Issue by qq772519864** [LmeSzinc/AzurLaneAutoScript#1089]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

用adb shell wm size 1280x720修改了手机分辨率
报错INFO     16:12:30.335 │ [Screen_size] 1440x2560                                    
INFO     16:12:30.496 │ [Package_name] com.bilibili.azurlane                       
CRITICAL 16:12:30.501 │ Resolution not supported: 1440x2560                        
CRITICAL 16:12:30.503 │ Please set emulator resolution to 1280x720                 
CRITICAL 16:12:30.506 │ Request human takeover   

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
说明你分辨率没有修改成功。Alas 不主动获取屏幕分辨率，以实际收到的截图的宽高为准。

另外，鉴于你使用的是新注册的 github 帐号，这个 issue 将在无活跃 3 天后被关闭。
