### ISSUE TITLE
台服共斗活动选择错误

### ISSUE THREAD

**Issue by NightOwlHaohao** [LmeSzinc/AzurLaneAutoScript#1094]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

台服目前的共斗活动是 复刻特别演习•埃塞克斯级活动专题 

目前Alas会自动选成另一个（手动选择无效），导致卡住

麻烦大佬更改一下，谢谢

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
INFO     17:18:10.647 │ [Screen_size] 1280x720                                     
─────────────────────────────── RAID_20210708_HARD ────────────────────────────────
INFO     17:18:10.738 │ RAID_20210708_HARD                                         
INFO     17:18:10.740 │ Count: 0                                                   
INFO     17:18:10.741 │ <<< UI ENSURE >>>                                          
INFO     17:18:10.742 │ UI get current page                                        
INFO     17:18:10.913 │ Unknown ui page                                            
INFO     17:18:10.920 │ Click (1224,   28) @ GOTO_MAIN                             
INFO     17:18:10.922 │ <<< MINITOUCH INIT >>>                                     
INFO     17:18:10.930 │ [Device Orientation] 0 (Normal)                            
INFO     17:18:10.932 │ Reuse forward: ForwardItem(serial='127.0.0.1:5555',        
         local='tcp:20425', remote='localabstract:minitouch')                      
INFO     17:18:10.936 │ v 1                                                        
INFO     17:18:10.937 │ ^ 2 32767 32767 0                                          
INFO     17:18:10.939 │ $ 5132                                                     
INFO     17:18:10.941 │ minitouch running on port: 20425, pid: 5132                
INFO     17:18:10.943 │ max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
INFO     17:18:11.340 │ Unknown ui page                                            
INFO     17:18:11.493 │ [Package_name] com.hkmanjuu.azurlane.gp.mc                 
INFO     17:18:11.781 │ [UI] page_main                                             
INFO     17:18:11.783 │ Goto page_raid                                             
INFO     17:18:11.784 │ <<< UI GOTO PAGE_RAID >>>                                  
INFO     17:18:11.788 │ Click ( 647,  289) @ MAIN_GOTO_RAID                        
INFO     17:18:56.828 │ Click ( 634,  287) @ MAIN_GOTO_RAID                        
[alas] exited. Reason: Manual stop
```

### 截图

![屏幕截图 2022-05-06 053245](https://user-images.githubusercontent.com/25108395/167029111-6261563d-61f9-4b82-b545-165d73c001a5.png)

**Comment by LmeSzinc** [comment]
#1093

**Comment by NightOwlHaohao** [comment]
大佬，请问目前是半自动模式吗，因为添加进调度器里面能点开活动，但是无法开始，手动点击困难后软件才会进入战斗

RAID_20200624_HARD ────────────────────────────────
INFO     11:55:28.936 │ RAID_20200624_HARD                                         
INFO     11:55:28.938 │ Count: 3                                                   
INFO     11:55:28.939 │ <<< UI ENSURE >>>                                          
INFO     11:55:28.940 │ UI get current page                                        
INFO     11:55:28.948 │ [UI] page_raid                                             
INFO     11:55:28.950 │ Already at page_raid                                       
INFO     11:55:28.952 │ <<< RAID EXECUTE >>>                                       
INFO     11:55:28.954 │ Expect emotion reduce: (2, 0)                              
INFO     11:55:28.966 │ Bind task {'Alas', 'EventGeneral', 'General', 'Raid'}      
INFO     11:55:28.968 │ Save config ./config\alas.json,                            
         Raid.Emotion.Fleet1Value=115,                                             
         Raid.Emotion.Fleet1Record=datetime.datetime(2022, 5, 6, 11, 55, 28),      
         Raid.Emotion.Fleet2Value=119,                                             
         Raid.Emotion.Fleet2Record=datetime.datetime(2022, 5, 6, 11, 55, 28)       
INFO     11:55:28.985 │ [Emotion fleet_1] 115                                      
INFO     11:55:28.987 │ [Emotion fleet_2] 119

**Comment by NightOwlHaohao** [comment]
大佬，请问目前是半自动模式吗，因为添加进调度器里面能点开活动，但是无法开始，logs最后显示心情管理就没反应了

除非手动点击困难后软件才会进入战斗

RAID_20200624_HARD ────────────────────────────────
INFO     11:55:28.936 │ RAID_20200624_HARD                                         
INFO     11:55:28.938 │ Count: 3                                                   
INFO     11:55:28.939 │ <<< UI ENSURE >>>                                          
INFO     11:55:28.940 │ UI get current page                                        
INFO     11:55:28.948 │ [UI] page_raid                                             
INFO     11:55:28.950 │ Already at page_raid                                       
INFO     11:55:28.952 │ <<< RAID EXECUTE >>>                                       
INFO     11:55:28.954 │ Expect emotion reduce: (2, 0)                              
INFO     11:55:28.966 │ Bind task {'Alas', 'EventGeneral', 'General', 'Raid'}      
INFO     11:55:28.968 │ Save config ./config\alas.json,                            
         Raid.Emotion.Fleet1Value=115,                                             
         Raid.Emotion.Fleet1Record=datetime.datetime(2022, 5, 6, 11, 55, 28),      
         Raid.Emotion.Fleet2Value=119,                                             
         Raid.Emotion.Fleet2Record=datetime.datetime(2022, 5, 6, 11, 55, 28)       
INFO     11:55:28.985 │ [Emotion fleet_1] 115                                      
INFO     11:55:28.987 │ [Emotion fleet_2] 119
