### ISSUE TITLE
关于科研使用部件时，是否能筛选所使用部件的种类？

### ISSUE THREAD

**Issue by Lab-Heathcliff** [LmeSzinc/AzurLaneAutoScript#1097]
### 你的功能请求是否与问题有关？

首先在我了解到科研相关的推荐顺序里，完全白嫖的科研收益要低于其它项目的，但像是活动期间大建和购买外观箱会使物资不足，不过这个可通过活动期间临时关闭使用物资来解决，因此日常中也需要使用材料进行科研。不过遗憾的是本人材料数量分布不均，紫鱼雷、舰载机超过1w，但紫通用只有3k出头，并且还有不少通用设备并未强化。在之前的使用中我会让alas接管除了科研以外的操作，由于现在强制开启科研，这个功能对我来说选项还不够精细。

PS：想起来一个不知道是不是bug的事，我是舰队副司令，其它几位管理层全弃坑了，因此需要我来领取每周舰队任务，虽然我点了选择新每周任务那项，但用到现在就帮我没领过，不清楚是不是我设置的问题（
没留意过log，需要的话我可以去翻翻

### 解决方案

如题

### 其他内容

暂无

**Comment by unihugh** [comment]
使用不同部件的科研项目别名是不同的。可以尝试仅做Q-351-MI Q-251-MI Q-051-MI

**Comment by LmeSzinc** [comment]
完全没有必要。

委托项目出现概率：https://azur-stats.lyoko.io/research4-projects
给你算一笔账，已知数据如下
- G 系科研占全部的 16.935%
- G4 占 G 系委托 12.952%
- 消耗通用的科研占 G4 的 20%
- 一次消耗 20 个通用部件

假设你一天做 12 次科研，那么一天消耗的通用部件是全部乘起来等于 1.05 个。才消耗 1.05 个部件，去打两趟图就拿到了，所以这个玩法是有问题的，Alas 完全没有必要支持。

**Comment by Lab-Heathcliff** [comment]
~~emm日常来说我的算法是按碧蓝wiki里的推荐顺序我先排除收益不佳的B、E、T，出现Q系的概率也只稍微高了一点。但活动期间我需要排除所有有物资消耗的D、G，H只算B、C、E、Q、T，这五类大项目占总出率的38.016%，那么Q系占这五类中的44.55%，当然Q-0.5也是要物资的也不算，Q-4约Q出率的12.952%，使用通用T3的占Q-4的20%，所以最后为1.15%。~~

没事了，我这种用法就单种来说用的确实不多，除非只盯着Q系的做，当然了能不能每次都刷到还是问题，刻板坏习惯罢了。当年鱼雷3k通用还经常会用完，到现在鱼雷都1w了通用还是没多少，只能说是真的用得太多了扣科研的也省不出来多少，打扰大佬了。

**Comment by Lab-Heathcliff** [comment]
顺便再问下如果需要帮我自动领大舰队周任务，除了开“收获/大舰队/启用该功能、选择新的每周舰队任务”选项以外还需要再开什么功能吗？我翻了下周一的log，GUILD LOBBY下只找到收取舰队作战奖励相关的记录。

**Comment by LmeSzinc** [comment]
> 顺便再问下如果需要帮我自动领大舰队周任务，除了开“收获/大舰队/启用该功能、选择新的每周舰队任务”选项以外还需要再开什么功能吗？我翻了下周一的log，GUILD LOBBY下只找到收取舰队作战奖励相关的记录。

有问题发log和截图，没有log和截图就当没有问题，另外建议新开issue
