### ISSUE TITLE
委托重复识别

### ISSUE THREAD

**Issue by jichuan-zhang** [LmeSzinc/AzurLaneAutoScript#1101]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

有时候会把同一个委托读取两次， 然后认为已经在做了4个导致有一队空闲

这里log是我自己点完了第四个之后让alas重新读取，结果读取了个5/4

### 如何复现

1. alas委托执行
2. 出现问题

没什么规律，就是有的时候会这样有的时候没事

### 预期行为

修一下，我感觉可能可以通过读取委托界面右上角的队伍数做个校验？

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     22:17:30.591 │ [Screen_size] 1280x720                                     
INFO     22:17:30.648 │ <<< UI ENSURE >>>                                          
INFO     22:17:30.654 │ UI get current page                                        
INFO     22:17:30.678 │ [UI] page_main                                             
INFO     22:17:30.682 │ Goto page_reward                                           
INFO     22:17:30.686 │ <<< UI GOTO PAGE_REWARD >>>                                
INFO     22:17:30.796 │ Click (  24,  172) @ MAIN_GOTO_REWARD                      
INFO     22:17:30.800 │ <<< MINITOUCH INIT >>>                                     
INFO     22:17:30.819 │ [Device Orientation] 0 (Normal)                            
INFO     22:17:30.825 │ Reuse forward: ForwardItem(serial='127.0.0.1:7555',        
         local='tcp:20937', remote='localabstract:minitouch')                      
INFO     22:17:30.832 │ v 1                                                        
INFO     22:17:30.836 │ ^ 10 1280 720 0                                            
INFO     22:17:30.840 │ $ 1483                                                     
INFO     22:17:30.844 │ minitouch running on port: 20937, pid: 1483                
INFO     22:17:30.847 │ max_contact: 10; max_x: 1280; max_y: 720; max_pressure: 0  
INFO     22:17:32.594 │ <<< REWARD RECEIVE >>>                                     
INFO     22:17:32.608 │ Click ( 468,  275) @ REWARD_GOTO_COMMISSION                
═════════════════════════════════ COMMISSION SCAN ═════════════════════════════════
INFO     22:17:34.219 │ COMMISSION SCAN                                            
INFO     22:17:34.226 │ [Commission_switch] daily                                  
INFO     22:17:34.231 │ Click (  63,  270) @ COMMISSION_URGENT                     
INFO     22:17:34.704 │ [Commission_switch] unknown                                
INFO     22:17:35.105 │ [Commission_switch] urgent                                 
─────────────────────────────────── SCAN DAILY ────────────────────────────────────
INFO     22:17:35.115 │ SCAN DAILY                                                 
INFO     22:17:35.120 │ [Commission_switch] urgent                                 
INFO     22:17:35.125 │ Click (  54,  176) @ COMMISSION_DAILY                      
INFO     22:17:35.622 │ [Commission_switch] urgent                                 
INFO     22:17:36.107 │ [Commission_switch] daily                                  
INFO     22:17:36.111 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     22:17:36.116 │ COMMISSION_SCROLL_AREA set to 0.0                          
INFO     22:17:36.120 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     22:17:36.125 │ <<< COMMISSION DETECT >>>                                  
INFO     22:17:36.148 │ Loading OCR model: ./bin/cnocr_models/jp                   
INFO     22:17:36.327 │ [COMMISSION 0.197s] 日常資源開発I                          
INFO     22:17:36.377 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     22:17:36.477 │ [COMMISSION 0.134s] I                                      
INFO     22:17:36.553 │ [DURATION 0.068s] 00:04:33                                 
INFO     22:17:36.562 │ [Commission] 日常資源開発I | Ⅰ (Genre: daily_resource,     
         Status: running, Duration: 0:04:33)                                       
INFO     22:17:36.680 │ [COMMISSION 0.105s] 日常資源開発V                          
INFO     22:17:36.718 │ [COMMISSION 0.030s] V                                      
INFO     22:17:36.800 │ [DURATION 0.072s] 00:27:01                                 
INFO     22:17:36.811 │ [Commission] 日常資源開発V | Ⅴ (Genre: daily_resource,     
         Status: running, Duration: 0:27:01)                                       
INFO     22:17:36.921 │ [COMMISSION 0.097s] 日常資源開発VI                         
INFO     22:17:36.957 │ [COMMISSION 0.026s] I                                      
INFO     22:17:37.025 │ [DURATION 0.060s] 00:31:22                                 
INFO     22:17:37.033 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: running, Duration: 0:31:22)                                       
INFO     22:17:37.158 │ [COMMISSION 0.116s] 上級科学研究                           
INFO     22:17:37.189 │ [COMMISSION 0.023s]                                        
INFO     22:17:37.255 │ [DURATION 0.056s] 10:00:00                                 
INFO     22:17:37.262 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     22:17:37.275 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     22:17:37.287 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     22:17:37.300 │ COMMISSION_SCROLL_AREA set to 1                            
INFO     22:17:37.308 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     22:17:37.320 │ Swipe (1258,  326) -> (1259,  440)                         
INFO     22:17:38.364 │ [COMMISSION_SCROLL_AREA] 0.99 (346.0-252.5)/(599-505)      
INFO     22:17:38.370 │ <<< COMMISSION DETECT >>>                                  
INFO     22:17:38.470 │ [COMMISSION 0.096s] 日常資源開発V                          
INFO     22:17:38.511 │ [COMMISSION 0.031s] V                                      
INFO     22:17:38.584 │ [DURATION 0.065s] 00:26:58                                 
INFO     22:17:38.596 │ [Commission] 日常資源開発V | Ⅴ (Genre: daily_resource,     
         Status: running, Duration: 0:26:58)                                       
INFO     22:17:38.716 │ [COMMISSION 0.110s] 日常資源開発VI                         
INFO     22:17:38.761 │ [COMMISSION 0.036s] VI                                     
INFO     22:17:38.820 │ [DURATION 0.051s] 00:31:19                                 
INFO     22:17:38.831 │ [Commission] 日常資源開発VI | Ⅵ (Genre: daily_resource,    
         Status: running, Duration: 0:31:19)                                       
INFO     22:17:38.961 │ [COMMISSION 0.120s] 上級科学研究                           
INFO     22:17:39.002 │ [COMMISSION 0.031s]                                        
INFO     22:17:39.073 │ [DURATION 0.060s] 10:00:00                                 
INFO     22:17:39.083 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     22:17:39.199 │ [COMMISSION 0.107s] 日常資源開発VI                         
INFO     22:17:39.245 │ [COMMISSION 0.035s] I                                      
INFO     22:17:39.310 │ [DURATION 0.058s] 02:00:00                                 
INFO     22:17:39.324 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: pending, Duration: 2:00:00)                                       
INFO     22:17:39.336 │ [COMMISSION_SCROLL_AREA] 0.99 (346.0-252.5)/(599-505)      
─────────────────────────────────── SCAN URGENT ───────────────────────────────────
INFO     22:17:39.355 │ SCAN URGENT                                                
INFO     22:17:39.363 │ [Commission_switch] daily                                  
INFO     22:17:39.374 │ Click (  52,  269) @ COMMISSION_URGENT                     
INFO     22:17:39.952 │ [Commission_switch] daily                                  
INFO     22:17:40.390 │ [Commission_switch] urgent                                 
INFO     22:17:40.396 │ <<< COMMISSION DETECT >>>                                  
INFO     22:17:40.512 │ [COMMISSION 0.110s] 敵襲1                                  
INFO     22:17:40.545 │ [COMMISSION 0.024s] I                                      
INFO     22:17:40.611 │ [DURATION 0.057s] 01:44:33                                 
INFO     22:17:40.619 │ [Commission] 敵襲1 | Ⅰ (Genre: urgent_cube, Status:        
         running, Duration: 1:44:33)                                               
─────────────────────────────── SHOWING COMMISSION ────────────────────────────────
INFO     22:17:40.631 │ SHOWING COMMISSION                                         
INFO     22:17:40.642 │ Daily commission                                           
INFO     22:17:40.650 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: pending, Duration: 2:00:00)                                       
INFO     22:17:40.659 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     22:17:40.668 │ [Commission] 日常資源開発I | Ⅰ (Genre: daily_resource,     
         Status: running, Duration: 0:04:33)                                       
INFO     22:17:40.679 │ [Commission] 日常資源開発V | Ⅴ (Genre: daily_resource,     
         Status: running, Duration: 0:27:01)                                       
INFO     22:17:40.692 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: running, Duration: 0:31:22)                                       
INFO     22:17:40.700 │ [Commission] 日常資源開発VI | Ⅵ (Genre: daily_resource,    
         Status: running, Duration: 0:31:19)                                       
INFO     22:17:40.707 │ Urgent commission                                          
INFO     22:17:40.714 │ [Commission] 敵襲1 | Ⅰ (Genre: urgent_cube, Status:        
         running, Duration: 1:44:33)                                               
INFO     22:17:40.720 │ [Running] 5/4                                              
═════════════════════════════════ COMMISSION RUN ══════════════════════════════════
INFO     22:17:40.726 │ COMMISSION RUN                                             
INFO     22:17:40.731 │ No commission chose                                        
INFO     22:17:40.735 │ Commission finish: ['2022-05-06 22:22:09', '2022-05-06     
         22:44:37', '2022-05-06 22:48:57', '2022-05-06 22:48:59', '2022-05-07      
         00:02:13']                                                                
INFO     22:17:40.739 │ Delay task `Commission` to 2022-05-06 22:22:09             
         (target=datetime.datetime(2022, 5, 6, 22, 22, 9))                         
INFO     22:17:40.755 │ Bind task {'Commission', 'Alas', 'General'}                
INFO     22:17:40.761 │ Save config ./config\alas.json,                            
         Commission.Scheduler.NextRun=datetime.datetime(2022, 5, 6, 22, 22, 9)     
INFO     22:17:40.775 │ Scheduler: End task `Commission`                           
INFO     22:17:40.780 │ [Server] jp                                                
INFO     22:17:40.800 │ Bind task {'Alas', 'General'}                              
INFO     22:17:40.805 │ No task pending                                            
INFO     22:17:40.809 │ [Task] Commission (Enable, 2022-05-06 22:22:09)            
INFO     22:17:40.814 │ Bind task {'Commission', 'Alas', 'General'}                
INFO     22:17:40.825 │ Wait until 2022-05-06 22:22:09 for task `Commission`       
INFO     22:17:40.830 │ Goto main page during wait                                 
INFO     22:17:43.304 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     22:17:43.344 │ App is already running, goto main page                     
INFO     22:17:43.350 │ <<< UI ENSURE >>>                                          
INFO     22:17:43.354 │ UI get current page                                        
INFO     22:17:43.379 │ [UI] page_commission                                       
INFO     22:17:43.386 │ Goto page_main                                             
INFO     22:17:43.390 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     22:17:43.423 │ Click (1232,   30) @ GOTO_MAIN                             
[alas] exited. Reason: Manual stop
```

### 还有别的吗？

模拟器是mumu，正常运行包括出击时没有卡顿。

**Comment by LmeSzinc** [comment]
是ocr错误，需要问题出现时的，委托列表的截图

**Comment by jichuan-zhang** [comment]
阿这，可是它不算error我怎么找alas看见的截图呢。应该去哪找？

**Comment by LmeSzinc** [comment]
> 阿这，可是它不算error我怎么找alas看见的截图呢。应该去哪找？

手动点模拟器截图，截委托界面的顶部和底部，截图需要是1280x720的

**Comment by jichuan-zhang** [comment]
懂了，下次遇到的时候我截一下，这个bug是偶尔出现的那种我也没办法稳定复现。

**Comment by jichuan-zhang** [comment]
![MuMu20220508232800](https://user-images.githubusercontent.com/91568110/167318386-640c653d-3454-4e2f-9b4d-7f598c0e7d09.png)
![MuMu20220508232805](https://user-images.githubusercontent.com/91568110/167318387-6b78207d-854f-4580-8982-d9ff54e0935d.png)
![MuMu20220508232838](https://user-images.githubusercontent.com/91568110/167318388-f8db4165-79ae-4940-946b-fa3b108d8e58.png)


`
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     23:27:03.709 │ <<< UI ENSURE >>>                                          
INFO     23:27:03.714 │ UI get current page                                        
INFO     23:27:03.733 │ [UI] page_main                                             
INFO     23:27:03.737 │ Goto page_reward                                           
INFO     23:27:03.742 │ <<< UI GOTO PAGE_REWARD >>>                                
INFO     23:27:03.757 │ Click (  21,  161) @ MAIN_GOTO_REWARD                      
INFO     23:27:05.268 │ <<< REWARD RECEIVE >>>                                     
INFO     23:27:05.272 │ Click ( 446,  284) @ REWARD_1                              
INFO     23:27:09.247 │ Click ( 477,  201) @ EXP_INFO_S_REWARD                     
INFO     23:27:10.999 │ Click ( 443,  190) @ EXP_INFO_S_REWARD                     
INFO     23:27:12.116 │ Click ( 450,  205) @ GET_ITEMS_1                           
INFO     23:27:13.344 │ Click ( 447,  282) @ REWARD_GOTO_COMMISSION                
═════════════════════════════════ COMMISSION SCAN ═════════════════════════════════
INFO     23:27:14.602 │ COMMISSION SCAN                                            
INFO     23:27:14.607 │ [Commission_switch] daily                                  
INFO     23:27:14.611 │ Click (  44,  269) @ COMMISSION_URGENT                     
INFO     23:27:15.113 │ [Commission_switch] daily                                  
INFO     23:27:15.463 │ [Commission_switch] urgent                                 
─────────────────────────────────── SCAN DAILY ────────────────────────────────────
INFO     23:27:15.468 │ SCAN DAILY                                                 
INFO     23:27:15.471 │ [Commission_switch] urgent                                 
INFO     23:27:15.474 │ Click (  35,  175) @ COMMISSION_DAILY                      
INFO     23:27:15.898 │ [Commission_switch] urgent                                 
INFO     23:27:16.348 │ [Commission_switch] daily                                  
INFO     23:27:16.352 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     23:27:16.357 │ COMMISSION_SCROLL_AREA set to 0.0                          
INFO     23:27:16.360 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     23:27:16.364 │ <<< COMMISSION DETECT >>>                                  
INFO     23:27:16.383 │ Loading OCR model: ./bin/cnocr_models/jp                   
INFO     23:27:16.526 │ [COMMISSION 0.157s] 中型油田開発I                          
INFO     23:27:16.550 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     23:27:16.634 │ [COMMISSION 0.100s] I                                      
INFO     23:27:16.694 │ [DURATION 0.054s] 03:48:26                                 
INFO     23:27:16.704 │ [Commission] 中型油田開発I | Ⅰ (Genre: extra_oil, Status:  
         running, Duration: 3:48:26)                                               
INFO     23:27:16.801 │ [COMMISSION 0.089s] 中型船団護衛                           
INFO     23:27:16.838 │ [COMMISSION 0.025s]                                        
INFO     23:27:16.890 │ [DURATION 0.045s] 05:51:18                                 
INFO     23:27:16.897 │ [Commission] 中型船団護衛 |  (Genre: extra_book, Status:   
         running, Duration: 5:51:18)                                               
INFO     23:27:16.990 │ [COMMISSION 0.084s] 日常資源開発VI                         
INFO     23:27:17.026 │ [COMMISSION 0.025s] I                                      
INFO     23:27:17.076 │ [DURATION 0.044s] 00:17:45                                 
INFO     23:27:17.082 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: running, Duration: 0:17:45)                                       
INFO     23:27:17.173 │ [COMMISSION 0.083s] 上級科学研究                           
INFO     23:27:17.203 │ [COMMISSION 0.023s]                                        
INFO     23:27:17.261 │ [DURATION 0.051s] 10:00:00                                 
INFO     23:27:17.268 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     23:27:17.276 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     23:27:17.283 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     23:27:17.290 │ COMMISSION_SCROLL_AREA set to 1                            
INFO     23:27:17.295 │ [COMMISSION_SCROLL_AREA] 0.01 (252.5-252.0)/(599-504)      
INFO     23:27:17.305 │ Swipe (1258,  325) -> (1255,  438)                         
INFO     23:27:18.221 │ [COMMISSION_SCROLL_AREA] 0.99 (346.0-252.5)/(599-505)      
INFO     23:27:18.224 │ <<< COMMISSION DETECT >>>                                  
INFO     23:27:18.304 │ [COMMISSION 0.077s] 中型船団護衛                           
INFO     23:27:18.341 │ [COMMISSION 0.027s] I                                      
INFO     23:27:18.398 │ [DURATION 0.051s] 05:51:16                                 
INFO     23:27:18.403 │ [Commission] 中型船団護衛 | Ⅰ (Genre: extra_book, Status:  
         running, Duration: 5:51:16)                                               
INFO     23:27:18.483 │ [COMMISSION 0.073s] 日常資源開発VI                         
INFO     23:27:18.515 │ [COMMISSION 0.025s] VI                                     
INFO     23:27:18.572 │ [DURATION 0.047s] 00:17:43                                 
INFO     23:27:18.583 │ [Commission] 日常資源開発VI | Ⅵ (Genre: daily_resource,    
         Status: running, Duration: 0:17:43)                                       
INFO     23:27:18.666 │ [COMMISSION 0.075s] 上級科学研究                           
INFO     23:27:18.692 │ [COMMISSION 0.021s]                                        
INFO     23:27:18.748 │ [DURATION 0.049s] 10:00:00                                 
INFO     23:27:18.758 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     23:27:18.846 │ [COMMISSION 0.082s] 前線基地防衛巡回                       
INFO     23:27:18.878 │ [COMMISSION 0.024s] I                                      
INFO     23:27:18.923 │ [DURATION 0.037s] 05:20:00                                 
INFO     23:27:18.931 │ [Commission] 前線基地防衛巡回 | Ⅰ (Genre: extra_drill,     
         Status: pending, Duration: 5:20:00)                                       
INFO     23:27:18.937 │ [COMMISSION_SCROLL_AREA] 0.99 (346.0-252.5)/(599-505)      
─────────────────────────────────── SCAN URGENT ───────────────────────────────────
INFO     23:27:18.948 │ SCAN URGENT                                                
INFO     23:27:18.956 │ [Commission_switch] daily                                  
INFO     23:27:18.963 │ Click (  53,  273) @ COMMISSION_URGENT                     
INFO     23:27:19.423 │ [Commission_switch] daily                                  
INFO     23:27:19.802 │ [Commission_switch] urgent                                 
INFO     23:27:19.806 │ <<< COMMISSION DETECT >>>                                  
INFO     23:27:19.877 │ [COMMISSION 0.067s] 離島火力支援                           
INFO     23:27:19.908 │ [COMMISSION 0.021s]                                        
INFO     23:27:19.955 │ [DURATION 0.043s] 01:20:00                                 
INFO     23:27:20.006 │ [EXPIRE 0.045s] 04:58:56                                   
INFO     23:27:20.015 │ [Commission] 離島火力支援 |  (Genre: urgent_part, Status:  
         pending, Duration: 1:20:00, Expire: 4:58:56)                              
─────────────────────────────── SHOWING COMMISSION ────────────────────────────────
INFO     23:27:20.029 │ SHOWING COMMISSION                                         
INFO     23:27:20.036 │ Daily commission                                           
INFO     23:27:20.042 │ [Commission] 前線基地防衛巡回 | Ⅰ (Genre: extra_drill,     
         Status: pending, Duration: 5:20:00)                                       
INFO     23:27:20.050 │ [Commission] 上級科学研究 |  (Genre: major_comm, Status:   
         pending, Duration: 10:00:00)                                              
INFO     23:27:20.056 │ [Commission] 日常資源開発VI | Ⅰ (Genre: daily_resource,    
         Status: running, Duration: 0:17:45)                                       
INFO     23:27:20.062 │ [Commission] 日常資源開発VI | Ⅵ (Genre: daily_resource,    
         Status: running, Duration: 0:17:43)                                       
INFO     23:27:20.072 │ [Commission] 中型船団護衛 |  (Genre: extra_book, Status:   
         running, Duration: 5:51:18)                                               
INFO     23:27:20.077 │ [Commission] 中型油田開発I | Ⅰ (Genre: extra_oil, Status:  
         running, Duration: 3:48:26)                                               
INFO     23:27:20.084 │ Urgent commission                                          
INFO     23:27:20.091 │ [Commission] 離島火力支援 |  (Genre: urgent_part, Status:  
         pending, Duration: 1:20:00, Expire: 4:58:56)                              
INFO     23:27:20.103 │ [Running] 4/4                                              
═════════════════════════════════ COMMISSION RUN ══════════════════════════════════
INFO     23:27:20.112 │ COMMISSION RUN                                             
INFO     23:27:20.116 │ No commission chose                                        
INFO     23:27:20.120 │ Commission finish: ['2022-05-08 23:45:01', '2022-05-08     
         23:45:02', '2022-05-09 03:15:42', '2022-05-09 05:18:34']                  
INFO     23:27:20.125 │ Delay task `Commission` to 2022-05-08 23:45:02             
         (target=datetime.datetime(2022, 5, 8, 23, 45, 2))                         
INFO     23:27:20.140 │ Bind task {'Commission', 'General', 'Alas'}                
INFO     23:27:20.144 │ Save config ./config\alas.json,                            
         Commission.Scheduler.NextRun=datetime.datetime(2022, 5, 8, 23, 45, 2)     
INFO     23:27:20.157 │ Scheduler: End task `Commission`                           
INFO     23:27:20.161 │ [Server] jp                                                
INFO     23:27:20.179 │ Bind task {'General', 'Alas'}                              
INFO     23:27:20.184 │ No task pending                                            
INFO     23:27:20.187 │ [Task] Main (Enable, 2022-05-08 23:36:00)                  
INFO     23:27:20.191 │ Bind task {'General', 'Main', 'Alas'}                      
INFO     23:27:20.202 │ Wait until 2022-05-08 23:36:00 for task `Main`             
INFO     23:27:20.206 │ Goto main page during wait                                 
INFO     23:27:20.592 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     23:27:20.596 │ App is already running, goto main page                     
INFO     23:27:20.599 │ <<< UI ENSURE >>>                                          
INFO     23:27:20.603 │ UI get current page                                        
INFO     23:27:20.619 │ [UI] page_commission                                       
INFO     23:27:20.623 │ Goto page_main                                             
INFO     23:27:20.626 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     23:27:20.658 │ Click (1243,   40) @ GOTO_MAIN                             
`

这种，日常VI被读了两次。好像和VI本身有关系？这次和上面的log都是VI出了问题。
