### ISSUE TITLE
台服META黑海媽卡住+每日共鬥識別錯誤

### ISSUE THREAD

**Issue by flh85799** [LmeSzinc/AzurLaneAutoScript#1111]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

META黑海媽卡住 

每日共鬥識別錯誤
進去共鬥頁面後三種模式識別全為0退出
但場次都還是15/15

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                      OPSIOBSCURE                                                      
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
═══════════════════════════════════════════════════════ OS INIT ═══════════════════════════════════════════════════════
2022-05-09 08:11:47.514 | INFO | OS INIT                                                                               
2022-05-09 08:11:47.530 | INFO | <<< UI ENSURE >>>                                                                     
2022-05-09 08:11:47.533 | INFO | UI get current page                                                                   
2022-05-09 08:11:47.548 | INFO | [UI] page_commission                                                                  
2022-05-09 08:11:47.551 | INFO | Goto page_os                                                                          
2022-05-09 08:11:47.556 | INFO | <<< UI GOTO PAGE_OS >>>                                                               
2022-05-09 08:11:47.571 | INFO | Click (1239,   30) @ GOTO_MAIN                                                        
2022-05-09 08:11:48.920 | INFO | Click (1016,  359) @ MAIN_GOTO_CAMPAIGN                                               
2022-05-09 08:11:50.477 | INFO | Click ( 708,  522) @ CAMPAIGN_MENU_GOTO_OS                                            
2022-05-09 08:11:52.231 | INFO | [MAP_NAME 0.079s] 紐約                                                                
2022-05-09 08:11:52.236 | INFO | Map name processed: 紐約                                                              
2022-05-09 08:11:52.241 | INFO | [Zone] [0|NY City]                                                                    
────────────────────────────────────────────────── AFTER AUTO SEARCH ──────────────────────────────────────────────────
2022-05-09 08:11:52.249 | INFO | AFTER AUTO SEARCH                                                                     
2022-05-09 08:11:52.265 | INFO | [HP]  98%  98%  98%  98%  98%  98%                                                    
2022-05-09 08:11:52.277 | INFO | [Repair icon] [False, False, False, False, False, False]                              
2022-05-09 08:11:52.281 | INFO | No ship found to be below threshold 40%, continue OS exploration                      
2022-05-09 08:11:52.295 | INFO | No EMP debuff on current fleet                                                        
2022-05-09 08:11:52.299 | INFO | Handle after auto search finished, solved=False                                       
2022-05-09 08:11:52.342 | INFO | [ASH_COLLECT_STATUS 0.036s] 100/100                                                   
2022-05-09 08:11:52.348 | INFO | Click ( 675,   36) @ ASH_COLLECT_STATUS                                               
2022-05-09 08:11:53.024 | INFO | Click ( 628,  523) @ ASH_ENTER_CONFIRM                                                
2022-05-09 08:12:53.200 | WARNING | Wait too long                                                                      
2022-05-09 08:12:53.203 | WARNING | Waiting for {'GET_MEOWFFICER_ITEMS_1', 'STORY_LETTER_BLACK',                       
'GET_MEOWFFICER_ITEMS_2', 'GET_ITEMS_1', 'GET_ITEMS_2', 'ASH_START', 'POPUP_CONFIRM', 'IN_MAP', 'STORY_SKIP',          
'GET_MISSION', 'GET_ADAPTABILITY', 'BEACON_REWARD', 'GUILD_POPUP_CONFIRM', 'BEACON_ENTER', 'MAP_ARCHIVES',             
'GET_ITEMS_3', 'ASH_ENTER_CONFIRM', 'OS_GAME_TIPS', 'MAP_WORLD', 'GAME_TIPS'}                                          
2022-05-09 08:12:53.207 | WARNING | Wait too long                                                                      
2022-05-09 08:12:53.210 | WARNING | Saving error: ./log/error/1652055173210
```

### 截图

![2022-05-09_08-12-53-187601](https://user-images.githubusercontent.com/51792581/167393455-02bc53f5-3a44-4ac0-bbe0-261101350ae1.png)

**Comment by flh85799** [comment]
> ### 在提问之前...
> * [x]  我已经搜索了现有的 issues
> * [x]  我在提问题之前至少花费了 5 分钟来思考和准备
> * [x]  我已经阅读了 Wiki 中的 常见问题(FAQ)
> * [x]  我正在使用最新版的 Alas
> 
> ### 描述你的问题
> META黑海媽卡住
> 
> 每日共鬥識別錯誤 進去共鬥頁面後三種模式識別全為0退出 但場次都還是15/15
> 

> ### 相关 Logs
> ```
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
>                                                       OPSIOBSCURE                                                      
> ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
> ═══════════════════════════════════════════════════════ OS INIT ═══════════════════════════════════════════════════════
> 2022-05-09 08:11:47.514 | INFO | OS INIT                                                                               
> 2022-05-09 08:11:47.530 | INFO | <<< UI ENSURE >>>                                                                     
> 2022-05-09 08:11:47.533 | INFO | UI get current page                                                                   
> 2022-05-09 08:11:47.548 | INFO | [UI] page_commission                                                                  
> 2022-05-09 08:11:47.551 | INFO | Goto page_os                                                                          
> 2022-05-09 08:11:47.556 | INFO | <<< UI GOTO PAGE_OS >>>                                                               
> 2022-05-09 08:11:47.571 | INFO | Click (1239,   30) @ GOTO_MAIN                                                        
> 2022-05-09 08:11:48.920 | INFO | Click (1016,  359) @ MAIN_GOTO_CAMPAIGN                                               
> 2022-05-09 08:11:50.477 | INFO | Click ( 708,  522) @ CAMPAIGN_MENU_GOTO_OS                                            
> 2022-05-09 08:11:52.231 | INFO | [MAP_NAME 0.079s] 紐約                                                                
> 2022-05-09 08:11:52.236 | INFO | Map name processed: 紐約                                                              
> 2022-05-09 08:11:52.241 | INFO | [Zone] [0|NY City]                                                                    
> ────────────────────────────────────────────────── AFTER AUTO SEARCH ──────────────────────────────────────────────────
> 2022-05-09 08:11:52.249 | INFO | AFTER AUTO SEARCH                                                                     
> 2022-05-09 08:11:52.265 | INFO | [HP]  98%  98%  98%  98%  98%  98%                                                    
> 2022-05-09 08:11:52.277 | INFO | [Repair icon] [False, False, False, False, False, False]                              
> 2022-05-09 08:11:52.281 | INFO | No ship found to be below threshold 40%, continue OS exploration                      
> 2022-05-09 08:11:52.295 | INFO | No EMP debuff on current fleet                                                        
> 2022-05-09 08:11:52.299 | INFO | Handle after auto search finished, solved=False                                       
> 2022-05-09 08:11:52.342 | INFO | [ASH_COLLECT_STATUS 0.036s] 100/100                                                   
> 2022-05-09 08:11:52.348 | INFO | Click ( 675,   36) @ ASH_COLLECT_STATUS                                               
> 2022-05-09 08:11:53.024 | INFO | Click ( 628,  523) @ ASH_ENTER_CONFIRM                                                
> 2022-05-09 08:12:53.200 | WARNING | Wait too long                                                                      
> 2022-05-09 08:12:53.203 | WARNING | Waiting for {'GET_MEOWFFICER_ITEMS_1', 'STORY_LETTER_BLACK',                       
> 'GET_MEOWFFICER_ITEMS_2', 'GET_ITEMS_1', 'GET_ITEMS_2', 'ASH_START', 'POPUP_CONFIRM', 'IN_MAP', 'STORY_SKIP',          
> 'GET_MISSION', 'GET_ADAPTABILITY', 'BEACON_REWARD', 'GUILD_POPUP_CONFIRM', 'BEACON_ENTER', 'MAP_ARCHIVES',             
> 'GET_ITEMS_3', 'ASH_ENTER_CONFIRM', 'OS_GAME_TIPS', 'MAP_WORLD', 'GAME_TIPS'}                                          
> 2022-05-09 08:12:53.207 | WARNING | Wait too long                                                                      
> 2022-05-09 08:12:53.210 | WARNING | Saving error: ./log/error/1652055173210
> ```
> 
> ### 截图
> ![2022-05-09_08-12-53-187601](https://user-images.githubusercontent.com/51792581/167393455-02bc53f5-3a44-4ac0-bbe0-261101350ae1.png)
>

**Comment by LmeSzinc** [comment]
> 每日共鬥識別錯誤
> 進去共鬥頁面後三種模式識別全為0退出
> 但場次都還是15/15

这部分的log和截图没有提供

**Comment by gl6437531** [comment]
═══════════════════════════════════════════════════════════════════════════════════
                                     RAIDDAILY                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     11:31:22.808 │ [Screen_size] 1280x720                                     
INFO     11:31:22.863 │ <<< UI ENSURE >>>                                          
INFO     11:31:22.866 │ UI get current page                                        
INFO     11:31:22.882 │ [UI] page_main                                             
INFO     11:31:22.884 │ Goto page_raid                                             
INFO     11:31:22.886 │ <<< UI GOTO PAGE_RAID >>>                                  
INFO     11:31:22.958 │ Click ( 637,  288) @ MAIN_GOTO_RAID                        
INFO     11:31:22.960 │ <<< MINITOUCH INIT >>>                                     
INFO     11:31:22.970 │ [Device Orientation] 0 (Normal)                            
INFO     11:31:22.974 │ Reuse forward: ForwardItem(serial='127.0.0.1:62001',       
         local='tcp:20117', remote='localabstract:minitouch')                      
INFO     11:31:22.978 │ v 1                                                        
INFO     11:31:22.980 │ ^ 2 1280 720 0                                             
INFO     11:31:22.982 │ $ 2882                                                     
INFO     11:31:22.984 │ minitouch running on port: 20117, pid: 2882                
INFO     11:31:22.986 │ max_contact: 2; max_x: 1280; max_y: 720; max_pressure: 0   
══════════════════════════════════════ HARD ═══════════════════════════════════════
INFO     11:31:26.447 │ HARD                                                       
INFO     11:31:26.461 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     11:31:26.524 │ [BRISTOL_OCR_REMAIN_HARD 0.075s]                           
WARNING  11:31:26.528 │ Unexpected ocr result:                                     
INFO     11:31:26.530 │ [Hard Remain] 0                                            
INFO     11:31:27.297 │ [BRISTOL_OCR_REMAIN_HARD 0.021s]                           
WARNING  11:31:27.300 │ Unexpected ocr result:                                     
INFO     11:31:27.302 │ [Hard Remain] 0                                            
═════════════════════════════════════ NORMAL ══════════════════════════════════════
INFO     11:31:27.305 │ NORMAL                                                     
INFO     11:31:27.340 │ [BRISTOL_OCR_REMAIN_NORMAL 0.031s]                         
WARNING  11:31:27.343 │ Unexpected ocr result:                                     
INFO     11:31:27.345 │ [Normal Remain] 0                                          
INFO     11:31:28.182 │ [BRISTOL_OCR_REMAIN_NORMAL 0.026s]                         
WARNING  11:31:28.185 │ Unexpected ocr result:                                     
INFO     11:31:28.187 │ [Normal Remain] 0                                          
══════════════════════════════════════ EASY ═══════════════════════════════════════
INFO     11:31:28.190 │ EASY                                                       
INFO     11:31:28.223 │ [BRISTOL_OCR_REMAIN_EASY 0.031s]                           
WARNING  11:31:28.226 │ Unexpected ocr result:                                     
INFO     11:31:28.228 │ [Easy Remain] 0                                            
INFO     11:31:29.029 │ [BRISTOL_OCR_REMAIN_EASY 0.022s]                           
WARNING  11:31:29.032 │ Unexpected ocr result:                                     
INFO     11:31:29.035 │ [Easy Remain] 0                                            
INFO     11:31:29.037 │ Delay task `RaidDaily` to 2022-05-16 00:00:00              
         (server_update='00:00')                                                   
INFO     11:31:29.052 │ Bind task {'General', 'RaidDaily', 'Alas', 'EventGeneral'} 
INFO     11:31:29.055 │ Save config ./config\0主台版(新).json,                     
         RaidDaily.Scheduler.NextRun=datetime.datetime(2022, 5, 16, 0, 0)          
INFO     11:31:29.065 │ Scheduler: End task `RaidDaily`                            
INFO     11:31:29.069 │ [Server] tw                                                
INFO     11:31:29.085 │ Bind task {'General', 'Alas'}                              
INFO     11:31:29.088 │ No task pending                                            
INFO     11:31:29.090 │ [Task] Tactical (Enable, 2022-05-15 11:39:57)              
INFO     11:31:29.093 │ Bind task {'General', 'Alas', 'Tactical'}                  
INFO     11:31:29.099 │ Wait until 2022-05-15 11:39:57 for task `Tactical`         
INFO     11:31:29.103 │ Goto main page during wait                                 
INFO     11:31:29.938 │ [Package_name] com.hkmanjuu.azurlane.gp                    
INFO     11:31:29.941 │ App is already running, goto main page                     
INFO     11:31:29.943 │ <<< UI ENSURE >>>                                          
INFO     11:31:29.945 │ UI get current page                                        
INFO     11:31:29.956 │ [UI] page_raid                                             
INFO     11:31:29.966 │ Goto page_main                                             
INFO     11:31:29.968 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     11:31:29.971 │ Click (1241,   34) @ GOTO_MAIN                             
[https://imgur.com/a/vkffsb4](url)

**Comment by LmeSzinc** [comment]
assets 更新了
另外注意要把 `Alas 设置` - `模拟器设置` - `游戏服务器` 改成 `台服`，不能是 `自动检测`
