### ISSUE TITLE
希望加入切换账号的功能，每个配置文件绑定一个账号

### ISSUE THREAD

**Issue by liusj5257** [LmeSzinc/AzurLaneAutoScript#1115]
### 你的功能请求是否与问题有关？

如题
自动收菜的时候，多余时间可以切换配置方案来服务其他账号

### 解决方案

每个配置方案绑定一个账号，收菜时间让用户手动或自动切换配置方案

**Comment by LmeSzinc** [comment]
不会添加这个功能，因为有这个需求的都不是正常用户。
每个一个帐号需要对应一个独立的alas实例，需要对应一个独立的模拟器实例。
