### ISSUE TITLE
关于科研的设置选项及细分设置

### ISSUE THREAD

**Issue by sleepykittyy** [LmeSzinc/AzurLaneAutoScript#1137]
### 你的功能请求是否与问题有关？

相较于二期科研的双彩船，三期科研的价值较低，不少入坑不久的萌新（比如我）更倾向于在做完4期科研后去补2期的大帝，而目前的倾向选项中缺少相关的选择。
在细分的过滤器设置上，缺少一个设置的说明或者教学，其他的功能都相当的简洁好用，唯有科研设置方面萌新一头雾水

### 解决方案

建议添加对于二期科研的设置选项，并在GitHub中添加一个详细的科研设置教程文件，不甚感激

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn
