### ISSUE TITLE
能否对alas的占用进行优化

### ISSUE THREAD

**Issue by Natsumelike** [LmeSzinc/AzurLaneAutoScript#1140]
### 你的功能请求是否与问题有关？

模拟器+alas占用过高

**Comment by LmeSzinc** [comment]
请描述你的问题。

举例：
我的电脑配置是 I7-8700K CPU，1080TI 显卡，32GB内存3200频率，NVME SSD，我正在使用夜神模拟器64位，版本号XXX，模拟器设置2核心3GB内存60帧，模拟器安装于 NVME SSD 上。在 Alas 运行 XX 任务时，Alas 占用 CPU XX%，占用内存 XX MB。
