### ISSUE TITLE
项目疑似存在漏洞？

### ISSUE THREAD

**Issue by ddaodan** [LmeSzinc/AzurLaneAutoScript#1146]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

star了之后收到一封邮件，提醒我说这个项目存在风险
https://www.oscs1024.com/cd/1527850438970355712?sign=07b32b95

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
这个没有办法了，目前也没有影响就只能不管了，Alas 使用的库都是建项目时的版本，大概 2020 年初，并且现在没有跟进依赖版本的打算。

举个例子就是 numpy==1.16.6 是 cnocr==1.2.2 要求的，cnocr 2.0 之后放弃了 mxnet 转向 pytorch，要更新依赖版本的话，现有 的 3 个自定义 OCR 模型需要重新训练。

**Comment by LmeSzinc** [comment]
www.oscs1024.com 这个网站 google 搜索结果只有 3 页，你应该是没有订阅它的推送的，那么这封邮件的实质还是垃圾推广邮件。
