### ISSUE TITLE
活动图和大世界开荒的调度器优先级问题

### ISSUE THREAD

**Issue by tkosf** [LmeSzinc/AzurLaneAutoScript#1153]
### 你的功能请求是否与问题有关？

当活动图勾上【无视红脸出击】时，会导致短猫相接功能被滞留在后面无法运行。以及大世界每月开荒时，若勾选上【无视时间间隔强制执行】会把许多任务都滞留直到大世界开荒完成。

### 解决方案

希望在这些任务被勾选上特定选项时，如【无视红脸出击】【无视时间间隔强制运行】会自动调整其优先级，以免其他调度器任务被滞留。

### 其他内容

![图片](https://user-images.githubusercontent.com/63329502/170591563-b4f2518f-eaa2-4222-bcb5-a3c8d8dc1fdd.png)

**Comment by LmeSzinc** [comment]
不会这么做，请使用心情控制
粪提建议爬
