### ISSUE TITLE
【潜艇召唤】添加 进图战斗X秒后召唤潜艇

### ISSUE THREAD

**Issue by SF-monkey** [LmeSzinc/AzurLaneAutoScript#1161]
### 你的功能请求是否与问题有关？

目前13-4练船，一般都是BOSS战召唤潜艇出来助攻+吃经验。不过由于氧气不足，战斗后半段会被打死，然后扣心情值。

### 解决方案

添加 进图战斗X秒后召唤潜艇， 这功能可以避免潜艇过早氧气耗尽被打沉，还能对轴击杀人形精英或者BOSS。

**Comment by LmeSzinc** [comment]
#1086
