### ISSUE TITLE
日服委托OCR

### ISSUE THREAD

**Issue by WangRong089** [LmeSzinc/AzurLaneAutoScript#117]
`commission.py`里第285行`if min_distance < 3:`, 改成10可能更好, 3的话会导致所有的genre都是Invalid的(不清楚这是不是local specific的)

还有,日服的活动现在是没有维护了吗? 可以麻烦更新一下7-23的活动, 或者是提供一个example怎么添加新的活动吗? 谢谢!

**Comment by LmeSzinc** [comment]
能贴一些OCR的结果举例吗, 可以在log里找到`[COMMISSION 0.065s] 舰队高阶演习`
commission_name_parse 这个函数是用来纠正OCR错误, 获取委托类型的. 改成10的话可能导致委托分到错误的类别里去

新活动(event_20200723_cn)在dev分支里已经完成了, 但是dev分支本身有一些大改动, 可能会影响正在开墨染活动的EN服, 所以暂时不会merge. 在 [development.md](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/development.md) 里有讲如何适配一张新的地图, 不过现在的地图创建都是自动的了, 见 dev_tools/map_extractor.py , 详细说明在文件的末尾.

**Comment by WangRong089** [comment]
![M1](https://user-images.githubusercontent.com/45116569/88452509-eec9be00-ce91-11ea-8a5e-9c676d1cbf01.png)
我附带打印了一个logger, 里面给出了实际的`min_distance`, 可以看见都比3高但比10低. 如果不修改的话所有的分类都是Invalid的, 顺带我用的是`tesseract 5.0`, 这可能是个OCR的问题导致distance结果不同

**Comment by LmeSzinc** [comment]
你试试把OCR结果里的空格去掉, 再去分类

**Comment by WangRong089** [comment]
补一个`string = re.sub(' ', '', string)` 就没问题了

**Comment by LmeSzinc** [comment]
搞定了
