### ISSUE TITLE
建议降低大世界每月开荒功能的优先级

### ISSUE THREAD

**Issue by scythk** [LmeSzinc/AzurLaneAutoScript#1170]
### 你的功能请求是否与问题有关？

购买战役信息记录仪后每月开荒任务无缝执行导致主线/活动/活动每日被推迟

### 解决方案

建议降低优先级到主线图/活动图任务之后 可以利用回复心情的时间进行开荒
或者增加一个选项 可以交换两边的优先级 满足不同人的需求

**Comment by Harry2020rookie** [comment]
给后来者提个醒，虽然开发者不做这个功能，但我们可以自己去`AzurLaneAutoScript\module\config\config_manual.py`里面修改，把“>OpsiExplore”这一行稍微往下挪到想要的位置就可以了

**Comment by Harry2020rookie** [comment]
小心眼开发者删我评论 只许州官放火不许百姓点灯是吧（乐
