### ISSUE TITLE
Alas交互界面修改配置不触发自动保存

### ISSUE THREAD

**Issue by lbpdfs** [LmeSzinc/AzurLaneAutoScript#1172]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在Alas实例中进行各项配置修改，正常情况下应该是在修改完成后转移输入焦点，即触发保存事件，但本机上经常性出现转移焦点后不进行保存的现象

### 如何复现

目前复现步骤未知，触发原因未知，本身是以管理员权限启动的Alas，会在使用中突发性出现，无论调度器是否启动。出现后重新启动Alas、使用console.bat清理进程再启动Alas、重启电脑均不能有效排除故障，目前仅能确定Alas进行自动更新后该问题有望自动修复，但依然会再次发生

### 预期行为

因加群了解后判断本现象为小概率偶发现象，考虑是否可以为各个配置界面增加一个手动保存按钮，规避这个问题

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/0fa94251c5eb4fe9e6952d0f3755c7003b4f12bd 重构了配置保存，现在问题是否存在？

**Comment by lbpdfs** [comment]
> [0fa9425](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/0fa94251c5eb4fe9e6952d0f3755c7003b4f12bd) 重构了配置保存，现在问题是否存在？

近期使用该问题未重现过，我现在怀疑是我最开始安装出了什么意外，更换盘符重装之后使用正常了
