### ISSUE TITLE
添加永夜幻光的日服支持

### ISSUE THREAD

**Issue by WangRong089** [LmeSzinc/AzurLaneAutoScript#118]
我fork了dev branch, 但是发现新活动只有国服的入口, 可以把commit也在日服做一个支持吗? 谢谢!

**Comment by WangRong089** [comment]
![image](https://user-images.githubusercontent.com/45116569/88455154-a3b9a600-cea5-11ea-8abd-78ae6210d5cd.png)
我尝试把dev下的`asset`, `module`, `compaign` 覆盖我从master里clone下的文件, 然后修改`dictionary.py`里的`event_20200703_cn` 为`event_20200703_jp`, 程序能进入地图并生成地图信息, 但出现上述错误, 请问是哪里修改错误吗?

**Comment by LmeSzinc** [comment]
我在GUI里增加了入口, 顺便改了一下载入翻译字典的方式, 现在可以直接载入其他服务器的地图文件, 不需要复制粘贴了.

你这个问题是因为 dev 分支为了加快识别速度, 会先把图片转成灰度图, 而master分支里的模板文件还是彩色的, 所以在模板匹配的时候出现了报错.

**Comment by LmeSzinc** [comment]
另外不建议直接复制粘贴文件, 最好使用 git

**Comment by WangRong089** [comment]
谢谢, 我这次从`dev`里直接build, 新的入口确实有了, 但`cv2`的问题还在. 我注意到你上次commit 做了一次从`master`到`dev`的merge, 会是这个问题吗?

**Comment by LmeSzinc** [comment]
我忘记把EN和JP的图片也换了, 不好意思. 现在应该可以了

**Comment by WangRong089** [comment]
谢谢! 现在这个版本正常了, 多谢抽时间看这个问题!

这个issue我先open着, 再发现bug我会在这里补充的.

**Comment by WangRong089** [comment]
[Bug] 活动好像忘了加跳过剧情, 否则的话会卡在换舰队的时候(找不到UI)

**Comment by LmeSzinc** [comment]
剧情都是自动跳的, (使用`handle_story_skip`函数), 和是不是活动图没有关系.
我开荒的时候, 确实有注意到部分剧情会卡住, 今天会回看出错的log.

**Comment by WangRong089** [comment]
问一下这个活动的SP 是哪个选项? 我试了SP1,2,3 好像都不行

![image](https://user-images.githubusercontent.com/45116569/88604727-9faaa580-d0aa-11ea-8e25-a2a45b0de254.png)

还有现在的每日困难图还是只有10图吗? 我刷7-2的话会有以下报错

![image](https://user-images.githubusercontent.com/45116569/88604658-7d188c80-d0aa-11ea-9cc5-ac59929dddd6.png)

**Comment by whoamikyo** [comment]
this event has no SP map, i think you're confusing it with SP bonus stage, they're not the same thing.

**Comment by WangRong089** [comment]
Thanks, in that way we are not currently supporting for the SP bonus stage?

**Comment by whoamikyo** [comment]
yeah, without SP bonus support at the moment.

**Comment by LmeSzinc** [comment]
添加了SP图, 同时修改了章节难度的识别方法
能帮我换一下添加一下日服的 `SWITCH_1_HARD, SWITCH_1_NORMAL, SWITCH_2_EX, SWITCH_2_HARD` 四个assets吗, 具体操作在[development.md](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/development.md)里面

**Comment by WangRong089** [comment]
OK, 也push到dev下对吧, 话说我有push的权限吗

**Comment by LmeSzinc** [comment]
PR 就行

**Comment by WangRong089** [comment]
OK了, 不过我只加了assets, 没注册button. 我用的另一个服务器fork clone的, 大陆下载git太慢了...

**Comment by LmeSzinc** [comment]
加一下QQ群吧, 群号在README里面, 在国内讨论要方便些
日服现在还缺一些assets, 运行`button_extract`的时候会有提示, 如果可以的话, 也帮忙添加一下
