### ISSUE TITLE
请教下

### ISSUE THREAD

**Issue by mayu1995-zj** [LmeSzinc/AzurLaneAutoScript#119]
新活动永夜已经添加到活动选项中了吗  我下载当前Code 并未找到新活动

**Comment by LmeSzinc** [comment]
新活动永夜幻光(event_20200723_cn)在dev分支里已经完成
dev分支本身有一些大改动, 可能会影响正在开墨染活动的EN服, 所以暂时不会merge.

**Comment by mayu1995-zj** [comment]
请问下  如何将当前版本更新到分支  我采用傻瓜式安装
