### ISSUE TITLE
alas更新之后有概率被误报病毒

### ISSUE THREAD

**Issue by richardlzs** [LmeSzinc/AzurLaneAutoScript#1191]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在最近一次更新之后，alas被卡巴斯基报毒。
以下复制自卡巴斯基反病毒软件
True;alas.exe;alas.exe;D:\AlasApp_0.3.5\AzurLaneAutoScript\toolkit\WebApp\;PDM:Worm.Win32.BSS.ScreenLock;PDM:Worm.Win32.BSS.ScreenLock;2022/6/7 16:48;已删除

### 如何复现

1.使用alas时报毒

### 还有别的吗？

根据卡巴斯基的日志，被误报和ScreenLock相关，可能需要检查一下是否有强制锁定屏幕的代码

**Comment by LmeSzinc** [comment]
添加白名单就好了
`\toolkit\WebApp\alas.exe` 是 electron 打包出来的，本质是换了图标的 chromium 浏览器

**Comment by richardlzs** [comment]
确实可以在用户处进行白名单处理，但是有空还是应该从代码上解决一下
