### ISSUE TITLE
Add commission preset filters | 增加委托过滤器预设

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1194]
### Describe the solution you'd like

Provides preset filters like research, such as `Gems+Cubes+Oil`, `Gems+Chips+Oil`. Before writing a filter, you need to have a basic knowledge of commission drops, instead of guessing. Contact me to get the commission drop statistics.

像科研一样提供预设的过滤器，例如 `钻石+魔方+石油`，`钻石+心智+石油`。在编写过滤器之前，你需要对委托收益有所了解，而不是靠猜，可以联系我获取委托掉落统计结果。

**Comment by snowly233** [comment]
能否发相关信息过来，让我编写委托过滤器，我实在是看不惯alas给我做那个8小时魔方任务了。。。。。

**Comment by LmeSzinc** [comment]
[委托掉落统计20221002.xlsx](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9895947/20221002.xlsx)

**Comment by snowly233** [comment]
无争议排序（活动和钻石最高排序）
DailyEvent
> Gem-8 > Gem-4 > Gem-2

魔方排列（时均魔方0.15+）
> ExtraCube-0:30 > UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3 > UrgentCube-2:15 > ExtraCube-1:30 > ExtraCube-3
> UrgentCube-6 > UrgentCube-4
后续时均魔方收益远远低于0.15（一半都没有） ，任由其过期

高石油排列（时均油40+）
> DailyResource-2 > DailyResource-1 > Box-6 > DailyChip-2 > Box-3 > Box-1 > DailyChip-1
后续时均石油收益低于40，进入低优先任务排列

高心智排序（时均心智5+）
> DailyChip-2 > DailyChip-1 > NightDrill-2:40 > NightDrill-3:20 > NightDrill-5:20
后续时均心智低于5，进入低优先任务排列

技能书排序（1.2紫书或0.25-0.3金书）
> UrgentBook-2 > UrgentBook-2:30 > UrgentBook-0:30

低优先任务排列(油>心智)
> NightDrill-3:20 > UrgentDrill-2 > UrgentDrill-2:40 > UrgentDrill-4 > UrgentDrill-1:30 > ExtraOil-1 > UrgentDrill-1 > UrgentDrill-1:10 
> NightDrill-2:40 > ExtraOil-1 > ExtraOil-4 > ExtraOil-8 

低优先任务排列(油<心智)
> ExtraDrill-2 > ExtraDrill-5:20 > ExtraDrill-3:20 > ExtraDrill-1 > ExtraDrill-0:20 > ExtraDrill-2:40
> ExtraOil-1 > ExtraOil-4 > ExtraOil-8

过滤器（魔方>石油>心智>教材）
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> ExtraCube-0:30 > UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3 > UrgentCube-2:15 > ExtraCube-1:30 > ExtraCube-3
> UrgentCube-6 > UrgentCube-4
> DailyResource-2 > DailyResource-1 > Box-6 > DailyChip-2 > Box-3 > Box-1 > DailyChip-1
> NightDrill-2:40 > NightDrill-3:20 > NightDrill-5:20
> UrgentDrill-2  > UrgentDrill-4 > UrgentDrill-1:30 > ExtraOil-1 > UrgentDrill-1 > UrgentDrill-1:10 
> UrgentBook-0:30 > UrgentBook-2 > UrgentBook-2:30 
> ExtraOil-4 > ExtraOil-8 > shortest

过滤器（魔方>心智>石油>教材）
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> ExtraCube-0:30 > UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3 > UrgentCube-2:15 > ExtraCube-1:30 > ExtraCube-3
> UrgentCube-6 > UrgentCube-4
> DailyChip-2 > DailyChip-1 > NightDrill-2:40 > NightDrill-3:20 > NightDrill-5:20
> DailyResource-2 > DailyResource-1 > Box-6 > Box-3 > Box-1  
> ExtraDrill-2 > ExtraDrill-5:20 > ExtraDrill-3:20 > ExtraDrill-1 > ExtraDrill-0:20 > ExtraDrill-2:40
> ExtraOil-1 > UrgentBook-0:30 > UrgentBook-2 > UrgentBook-2:30 > ExtraOil-4 > ExtraOil-8 > shortest

过滤器（心智>石油>魔方>教材）
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> DailyChip-2 > DailyChip-1 > NightDrill-2:40 > NightDrill-3:20 > NightDrill-5:20
> DailyResource-2 > DailyResource-1 > Box-6  > Box-3 > Box-1 
> ExtraCube-0:30 > UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3 > UrgentCube-2:15 > ExtraCube-1:30 > ExtraCube-3
> UrgentCube-6 > UrgentCube-4
> UrgentDrill-2 > UrgentDrill-2:40 > UrgentDrill-4 > UrgentDrill-1:30 > ExtraOil-1 > UrgentDrill-1 > UrgentDrill-1:10 
> ExtraOil-1 > UrgentBook-0:30 > UrgentBook-2 > UrgentBook-2:30 > ExtraOil-4 > ExtraOil-8 > shortest

过滤器（心智>魔方>石油>教材）
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> DailyChip-2 > DailyChip-1 > NightDrill-2:40 > NightDrill-3:20 > NightDrill-5:20
> ExtraCube-0:30 > UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3 > UrgentCube-2:15 > ExtraCube-1:30 > ExtraCube-3
> UrgentCube-6 > UrgentCube-4
> DailyResource-2 > DailyResource-1 > Box-6  > Box-3 > Box-1 
> ExtraDrill-2 > ExtraDrill-5:20 > ExtraDrill-3:20 > ExtraDrill-1 > ExtraDrill-0:20 > ExtraDrill-2:40
> ExtraOil-1 > UrgentBook-0:30 > UrgentBook-2 > UrgentBook-2:30 > ExtraOil-4 > ExtraOil-8 > shortest

我根据委托时均收益写出了上述4种最常用的过滤器以及对应高收益委托排序，暂未测试，有问题的话跟我说一下我看看怎么改

**Comment by snowly233** [comment]
有相当一部分的>符号被吃掉了，我这里发一个txt版本吧
[委托排列.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9896347/default.txt)

**Comment by LmeSzinc** [comment]
1. 同类委托划分标准不明。`魔方排列（时均魔方0.15+）` 这里的 0.15 是如何确定的？
2. 不同委托之间组合的顺序不明。现在似乎只是 `魔方1 > 魔方2 > 魔方3 > 心智1 > 心智2 > 心智3`，举个夸张的例子就是如果 魔方3 是0.15/h，心智1是100心智/h，那排序可能是 `魔方1 > 魔方2 > 心智1 > 心智2 > 魔方3 > 心智3`，也就是发生了穿插，那这个穿插的标准是什么？

还是要靠计算啊，需要一个通用的委托收益评价体系。

另外过滤器可以放在 markdown 语法的代码框里：
```
1  > 2 > 3
> 4 > 5 > 6
```

**Comment by snowly233** [comment]
确实没有考虑到穿插问题，但是石油与魔方和心智确实是兼顾的，我去计算一下委托评分，`1>2>3
>4>5>6`

**Comment by snowly233** [comment]
极高价值的委托都已修改在最前列，后续委托价值相差不大已经不同产出的暂分类排列，另dailyresource委托有概率出魔方但是期望仅有0.03因此直接将其算做较高价值的石油委托会比较好

**Comment by SaiCateDoan** [comment]
@snowly233 
我现在正在做这个委托过滤器预设，你的委托过滤器是怎么确定权重的，
一个非常夸张的做法是用魔方=2000物资，心智=159物资，石油=7.54物资，统一转换成物资之后再加用户权重，
我觉得这样生硬的转换是愚蠢的，无法体现需求的价值，但是没有等价物又容易出现lme提到的问题，
我想知道你是怎么解决这个问题的

**Comment by SaiCateDoan** [comment]
或许转换成物资之后把用户权重拉到5:1或者更高可以解决问题

**Comment by snowly233** [comment]
> @snowly233 我现在正在做这个委托过滤器预设，你的委托过滤器是怎么确定权重的， 一个非常夸张的做法是用魔方=2000物资，心智=159物资，石油=7.54物资，统一转换成物资之后再加用户权重， 我觉得这样生硬的转换是愚蠢的，无法体现需求的价值，但是没有等价物又容易出现lme提到的问题， 我想知道你是怎么解决这个问题的

石油较高类别，心智类别，根据用户自身的需求划分权重，因为实际上魔方心智石油的较高档次差距都不大，具体可看我的TXT的时均收益，心智委托和魔方委托的高价值委托更是少而又少

**Comment by snowly233** [comment]
> 或许转换成物资之后把用户权重拉到5:1或者更高可以解决问题

高价值魔方任务（时均非常高）总计9个（除去不稳定的高价值每日委托，但本身高价值每日委托优先级较高，故可忽略不计）
高价值心智任务总计5个，其中2个是高价值每日心智委托，其余为夜间钻头委托
而较高石油价值委托除去高价值每日委托只有紧急科技箱委托
因此，用户权重定好之后可直接进行排列，或许你可以从低价值委托排列中继续进行委托确定权重
