### ISSUE TITLE
’help wanted‘ 求助，在按照教程安装完毕之后启动没有反应

### ISSUE THREAD

**Issue by 201816070304** [LmeSzinc/AzurLaneAutoScript#12]
安装依赖成功
![image](https://user-images.githubusercontent.com/44728386/83380043-8f11e200-a40f-11ea-86fa-8034b0890194.png)

**Comment by whoamikyo** [comment]
I don't see any error in image.

**Comment by 201816070304** [comment]
adb也配置好了
![image](https://user-images.githubusercontent.com/44728386/83380107-aea90a80-a40f-11ea-8cca-06e02fa2bde1.png)
adb.exe覆盖完毕
安装 uiautomator2
![image](https://user-images.githubusercontent.com/44728386/83380227-0182c200-a410-11ea-9671-9cd8fca5112e.png)
但是点击没有反应
![image](https://user-images.githubusercontent.com/44728386/83380305-32fb8d80-a410-11ea-9bce-9b43d1caa8e2.png)

**Comment by 201816070304** [comment]
问题就是无法启动，点击alas_cn.pyw之后没有任何反应

**Comment by whoamikyo** [comment]
edit the file alas.bat, change `alas_en.pyw ` for alas_cn.py`, save and double click on alas.bat.

**Comment by 201816070304** [comment]
有一个命令行窗口一闪而过，然后还是没有反应

**Comment by whoamikyo** [comment]
if you type `alas_cn.py` was wrong, miss type, its `alas_cn.pyw`

**Comment by 201816070304** [comment]
我把`alas_cn.py`改成了`alas_cn.pyw`，这次命令行窗口上有错误信息了，我试着截图了
![image](https://user-images.githubusercontent.com/44728386/83381001-0ba5c000-a412-11ea-8719-efa6c6404feb.png)

**Comment by whoamikyo** [comment]
Type `python` on cmd and print here the output

**Comment by 201816070304** [comment]
![image](https://user-images.githubusercontent.com/44728386/83381130-617a6800-a412-11ea-82cf-3b6ee76c1ca1.png)

**Comment by whoamikyo** [comment]
uninstall that python version and install 3.7.6 or follow that guide to use a virtual environment  https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc%2FQuick_guide.md

**Comment by 201816070304** [comment]
好的，我去试试

**Comment by 201816070304** [comment]
非常感谢，虽然直接双击’alas_cn.py‘还是无法启动，但是在使用虚拟环境之后用命令行成功启动了，再次感谢你耐心的解答！

**Comment by LmeSzinc** [comment]
直接双击pyw文件会使用系统默认的python, 你可以创建一个快捷方式并把它修改为虚拟环境中的python, 以后双击快捷方式就可以运行了

**Comment by 201816070304** [comment]
额，在网上找了找没有发现具体教程，怎么样把它修改为虚拟环境中的python呢

**Comment by LmeSzinc** [comment]
对alas.pyw创建快捷方式, 右键快捷方式, 属性, 修改里面的"目标"
比如: `E:\xxxx\envs\AzurLane\pythonw.exe "E:\xxxx\AzurLaneAutoScript\alas.pyw"`

**Comment by LmeSzinc** [comment]
如果在使用中遇到问题的话, 可以来 https://discord.gg/vCFxDen

**Comment by 201816070304** [comment]
嗯，多谢解答，感觉学到了新姿势！
