### ISSUE TITLE
自动获取维护更新时间并延迟任务

### ISSUE THREAD

**Issue by Horizon101011** [LmeSzinc/AzurLaneAutoScript#1205]
### 你的功能请求是否与问题有关？

在假定维护不延期的前提下，通过读取官网公告来自动将维护期间的任务推迟到维护结束，从而免去手动重启alas

### 解决方案

初步设想是类似于Updater一样做一个检查器，从各服务器官网上爬取信息后比对时间
对于国服，可供抓取的url是https://api.biligame.com/news/list.action?gameExtensionId=103&positionId=2
一个简单的demo可以是
```
import os
import json
import re
url = '"https://api.biligame.com/news/list.action?gameExtensionId=103&positionId=2"'
with os.popen(f'curl {url}') as f:
    response = f.read()
j = json.loads(response)
content = j['data'][1]['content']
m=re.search(r'[0-9]{1,2}月[0-9]{1,2}日[0-9]{1,2}:[0-9]{1,2}~[0-9]{1,2}:[0-9]{1,2}',j['data'][1]['content'])
time = m.group(0)  # '6月9日9:00~15:00'
```
对于日服，可供抓取的url是https://www.azurlane.jp/news.html?c=4
对于台服，可供抓取的url是https://open.azurlane.tw/web-api/pass/game/news/list?type=notice&websiteId=1
以上均需要获取最新公告的地址再作跳转，但是都可以用正则解决，问题不大
对于美服，暂时找不到能用的地址，https://azurlane.yo-star.com/news/ 这边给的是图片，需要进一步探索

### 其他内容

如果这个功能有必要我会抽时间来实现

**Comment by LmeSzinc** [comment]
不要抓公告，抓游戏里面登录界面的服务器状态。每次启动客户端之前请求这个URL，分几种情况，服务器维护和网络连接断开。循环请求这个URL，直到服务器上线或者网络链接恢复了，再继续启动客户端。

**Comment by KenkoC** [comment]
**同求**
