### ISSUE TITLE
强化功能不完善

### ISSUE THREAD

**Issue by modeilan** [LmeSzinc/AzurLaneAutoScript#1208]
### 你的功能请求是否与问题有关？

强化时排序前面几个都是航母，每次都没出几个航母的白船，强化几次没白船就会退出，久而久之的就会在退役界面卡住，希望大佬能再优化下，后面还有很多其他类型的船可以强化

### 解决方案

多写几个强化循环，或者分类型进行强化

**Comment by Horizon101011** [comment]
![image](https://user-images.githubusercontent.com/43370844/173013102-ca1575d6-1048-4f84-9b34-523d60af59e8.png)
你说的功能都在这里
增大强化数量以尝试更多的强化次数
使用过滤字符串指定不同的舰种

退役设置请按如下设置
![image](https://user-images.githubusercontent.com/43370844/173013602-c4e1c4e9-b0ba-4934-9277-2266af7876db.png)

在正确设置的前提下不可能出现在退役卡住的情况
唯一的解释是你的第三优先级设置了无
如果不希望白船被退役，正确的做法是通过设置合适的强化数量或者指定舰种来消耗他们，而不是不让退役
