### ISSUE TITLE
如何更新分支

### ISSUE THREAD

**Issue by mayu1995-zj** [LmeSzinc/AzurLaneAutoScript#121]
请问下 如何将当前版本更新到分支 我采用傻瓜式安装

**Comment by LmeSzinc** [comment]
你可以在更新界面中选择 whoamikyo 的 nightly 分支, 这个分支有和 dev 分支同步

**Comment by xiaodingxe** [comment]
dalao如何使用dev分支，刚刚使用这个软件小白有点懵。
