### ISSUE TITLE
战术学院 技能书的选择策略未成功生效

### ISSUE THREAD

**Issue by Mirageorwhatever** [LmeSzinc/AzurLaneAutoScript#1213]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

战术学院项目中的溢出经验控制选项并未成功生效，当角色技能经验快满时，alas并不会选择较低等级的技能书，而是使用更高级的同色技能书

在描述现象之前，我想说明一下我对这个选项的预期，如果与制作组对这个功能的预期有偏差，请无视我这条反馈。
我认为，这个功能是一个消耗更多时间为代价，来节约技能书资源的方式，所以此时的最佳策略是，在不溢出经验的前提下，优先使用不会溢出的经验书来填满空缺，最后使用T1书进行补全。（因为T1书只有150点经验值，在有溢出的情况下，最多也是100点，在其他经验书允许溢出的经验值也为100点的情况下，这是完全可以接受的）

如下方例子中，皇家方舟的经验值为5300，距离满级5800差500点经验值，如果控制选项生效，那么alas应选择450经验的T2技能书，最后使用150点的经验书进行补全，溢出经验为100点。

我明白程序中带有溢出经验控制，可以自己将T1的溢出值设置为100，但alas在这个场景下的选择是使用T3经验书，溢出经验值为800，远远超出了预期，可见，溢出经验控制功能并没有生效。
此外，还有一例相似的情况，但我找不到那时候的日志了，那一例中，alas同样在经验溢出的情况下，选用了T4经验书，而本次由于我没有同色的T4书了，所以不能确定具体现象是使用了更高级技能书还是选用最高级技能书

这个可能是选择策略代码中的bug，也可能是溢出经验控制数值设置不正确导致了这个bug（我的设置是保持默认 由上往下依次为100 100 100 50，如果是这导致的bug，我觉得可以将T1的数值也设置为100）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![Screenshot_20220611-184840](https://user-images.githubusercontent.com/84392723/173185001-71a71bc9-2dec-4064-b598-0254c9dfdfba.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/8883704/log.txt)

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/badb3c77583a8ef49ae06fd924d53d1d4bea9e48
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/1a0dd81adfd4af2aa88d76ee340d215b1d15814d
