### ISSUE TITLE
有关-每日收获-其他商店-功勋商店 能否手动关掉的提议

### ISSUE THREAD

**Issue by Dq8515** [LmeSzinc/AzurLaneAutoScript#1214]
### 你的功能请求是否与问题有关？

按默认兑换，功勋一般不够换商店，而且功勋商店现在应该是一月刷新一次，手动购买也不费多少时间。

### 解决方案

增添一个能手动开关功勋商店的功能

**Comment by LmeSzinc** [comment]
留一个空格就可以了

建议还是多打图，正常使用alas每天打图的话勋章是溢出的。现在很多每周一次每月一次的功能都在计划中了，为的是完全托管
