### ISSUE TITLE
需要对CPU占用进行优化

### ISSUE THREAD

**Issue by binglingyao** [LmeSzinc/AzurLaneAutoScript#1216]
### 你的功能请求是否与问题有关？

用了很久了,今日偶然发现CPU占用奇高无比,突然惊觉.

随着alas的不断更新,仅使用alas与4个模拟器的情况下**CPU占用率从20%到峰值67% 左右 到如今30%到峰值100%(长时间)**

(目前我使用的CPU为 i9-11900)
这是一个不太妙的占用提升也是一个不太妙的信号
随着alas的不断更新,可能出现更多的不知道使用到何处的CPU资源会更多
所以,可能需要作者对一些代码进行一些优化了.

### 解决方案

优化它

### 其他内容

暂无

**Comment by LmeSzinc** [comment]
这个问题与 Alas 无关，每个 Alas 实例的 cpu 占用应该是 <1% 的（进行 OCR 时除外），占用 cpu 的是模拟器。
可以进行的尝试：
- 每个模拟器分配 2 核心 2GB 内存
- 使用 ADB_nc 截图和 minitouch 点击，ascreencap 更快但会占用更多 cpu，*_nc 方法调用更快
- 保持 Alas 默认的截图间隔 0.3s 和战斗截图间隔 1.0s
- 清除游戏客户端的数据，不要下载额外语言包，Live2d 资源包等
- 在模拟器的多开管理器中，清理实例的储存
