### ISSUE TITLE
netcat connection refused

### ISSUE THREAD

**Issue by n0k0m3** [LmeSzinc/AzurLaneAutoScript#1236]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

Got `nc: connect: Connection refused` when trying to use/benchmark adb_nc on AVD Android 11

### To Reproduce

0. Setup AVD with Android 11, 1280x720
1. Go to benchmark
2. Choose all but hermit
3. Hit "Go"

### Expected behavior

Benchmark successfully run with adb_nc and related tasks

### Relevant log output

```Text
INFO     03:53:27.974 │ BENCHMARK TEST                                                                                          
INFO     03:53:27.975 │ Testing function: screenshot_adb_nc                                                                     
INFO     03:53:27.977 │ Connecting to local emulator, using host 127.0.1.1                                                      
INFO     03:53:27.978 │ Reverse server listening on 127.0.1.1:20154, client can send data to 127.0.1.1:20154                    
WARNING  03:53:32.986 │ b'nc: connect: Connection refused\n'                                                                    
ERROR    03:53:32.989 │ AdbTimeout: reverse server accept timeout                                                               
INFO     03:53:35.994 │ <<< DETECT DEVICE >>>                                                                                   
INFO     03:53:35.996 │ Here are the available devices, copy to Alas.Emulator.Serial to use it or set                           
         Alas.Emulator.Serial="auto"                                                                                            
INFO     03:53:35.999 │ emulator-5554                                                                                           
INFO     03:53:36.001 │ Connecting to local emulator, using host 127.0.1.1                                                      
INFO     03:53:36.003 │ Reverse server listening on 127.0.1.1:20233, client can send data to 127.0.1.1:20233                    
WARNING  03:53:41.013 │ b'nc: connect: Connection refused\n'                                                                    
ERROR    03:53:41.015 │ AdbTimeout: reverse server accept timeout
```

### Anything else?

Using Android Emulator from Android SDK, Android 11 (API 30)

**Comment by LmeSzinc** [comment]
Not familiar with AVD, but from [what I have searched](https://stackoverflow.com/questions/5806220/how-to-connect-to-my-http-localhost-web-server-from-android-emulator), AVD can access host via `10.0.2.2`. Try to access `http://10.0.2.2:22267` in emulator browser, see if there's Alas's web interface. Netcat can send screenshots there if it works, but we still need a way to distinguish AVD since both AVD and LDPlayer use emulator-555X.

**Comment by LmeSzinc** [comment]
This may help
https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/blob/88ca9bd8008aca6df1ae33bca27da807830b1d96/automator/control/adb/info.py#L59-L74

**Comment by n0k0m3** [comment]
Yep `10.0.2.2:22267` works nicely.

From my research `getprop ro.product.board` returns
- `goldfish_*` for `avd` (which makes sense for this [line](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper/blob/88ca9bd8008aca6df1ae33bca27da807830b1d96/automator/control/adb/info.py#L65))
- `LDPlayer` or `Play1` for `LDPlayer`

So can we implement what AAH did for ALAS?

**Comment by LmeSzinc** [comment]
check `getprop ro.product.board` should be enough

**Comment by hgjazhgj** [comment]
> ...(which makes sense for this [line]  
> ________________________________ ^  `ArknightsAutoHelper` bomb julie...  

In my avd(Pixel XL, Android 7.1 Nougat, API level 25), `ro.product.board` has an empty value:
```
[ro.product.board]: []
```
Full output [here](https://www.luogu.com.cn/paste/dn46kre8)  
Is there something wrong?

**Comment by hgjazhgj** [comment]
Android 11 avd printed as expected
```
[ro.product.board]: [goldfish_x86]
```
Testing on other API levels...

**Comment by n0k0m3** [comment]
That field doesn't exists on 11
However, funny enough we can use `ro.hardware.audio.primary`
