### ISSUE TITLE
怎么使用dev 分支

### ISSUE THREAD

**Issue by xiaodingxe** [LmeSzinc/AzurLaneAutoScript#125]
小白刚刚使用这个软件，如何使用cn的dev分支弄了半天没弄明白。

**Comment by LmeSzinc** [comment]
如果你使用的是傻瓜式安装包, 按照 [中文安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/Installation_cn.md) 里的 傻瓜式更新教程 进行操作, 选择:
`3) https://github.com/whoamikyo/AzurLaneAutoScript (nightly build, dont use)`

**Comment by xiaodingxe** [comment]
好的，谢谢！

**Comment by xiaodingxe** [comment]
dalao，我想问一下目标计算机积极拒绝该怎么弄。

**Comment by LmeSzinc** [comment]
看看 #106 是不是你的遇到问题

**Comment by xiaodingxe** [comment]
是的。

**Comment by xiaodingxe** [comment]
啊，还是有点看不明白。。。

**Comment by xiaodingxe** [comment]
请问可以加一下你的那个qq群联系一下你么，实在有点看不明白。

**Comment by LmeSzinc** [comment]
欢迎啊, 国服开发群来的
