### ISSUE TITLE
我更改了您所说的使用门槛但还是无法打开alas而且还是出现重新检查deploy文件的提示

### ISSUE THREAD

**Issue by SilenceWank** [LmeSzinc/AzurLaneAutoScript#1256]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我每次打开alas都按照说明将Repository: 'https://gitee.com/LmeSzinc/AzurLaneAutoScript'更改成PypiMirror: 'https://pypi.tuna.tsinghua.edu.cn/simple' 但是还是有概率出现无法打开的问题，且当我打开失败后，已修改的deploy文件又变回Repository: 'https://gitee.com/LmeSzinc/AzurLaneAutoScript' 之前我都是重启电脑或者多次打开alas才能有几率成功启动alas，这问题能折磨我一天，今天我无数次修改了deploy文件还是打不开。我真的已经阅读了说明书，我也改了好几遍文件。可是确实是不能解决我的问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
你可能改错文件了，需要更改的是 `config/deploy.yaml`，不是 `config/deploy.templete.yaml`

**Comment by SilenceWank** [comment]
链接：https://pan.baidu.com/s/1X2idMhXUhO6ZWdMnu4mTIQ 
提取码：zusm
我把我使用的录屏文件传到百度云了
我挺不理解的，我真的是按照说明书弄的 可能是我看不懂或者是我哪儿做错了 那不会不懂的人就要被嘲讽吗？我在群里问，没人解答，只有冷嘲热讽问我为什么不看说明书。我说我看了我也改了，可是问题还会发生。我是不是哪儿做错了改错了，因为我一点不懂程序相关知识、也没人回答我。我今天去你们群里那个脚本视频下面找人问，回头还被别人挂在群里骂是不给傻瓜安装就不会玩的，只能说确实是我不配用了，

**Comment by SilenceWank** [comment]
> 你可能改错文件了，需要更改的是 `config/deploy.yaml`，不是 `config/deploy.templete.yaml`，前面的是用户配置文件，后面的是配置文件模板，模板会随Alas更新。

我改的就是`config/deploy.yaml`，改的不是templete 我发了度盘视频

**Comment by SilenceWank** [comment]
![3UL~AHA~J6P%RX P(C7` 97](https://user-images.githubusercontent.com/108127479/175523719-161c2e06-b6d2-4c29-9db1-b31ada31de50.png)

**Comment by LmeSzinc** [comment]
改错地方了，有两个需要更改的地方 `Repository` 和 `PypiMirror`，需要修改它们分别对应的地方，但是你把 `PypiMirror` 改到了 `Repository` 上，配置文件错误会自动还原

**Comment by SilenceWank** [comment]
你说的那个文件应该是只在我成功打开alas一次之后才会生成吧，我把过去用的卸载了重新安装。也没有你说的那个文件了

**Comment by SilenceWank** [comment]
> 
解决问题了 是我没有理解使用门槛 感谢您拨冗帮助

**Comment by SilenceWank** [comment]
> 改错地方了，有两个需要更改的地方 `Repository` 和 `PypiMirror`，需要修改它们分别对应的地方，但是你把 `PypiMirror` 改到了 `Repository` 上，配置文件错误会自动还原

再次为我不懂而浪费您的时间感到抱歉

**Comment by SilenceWank** [comment]
> 改错地方了，有两个需要更改的地方 `Repository` 和 `PypiMirror`，需要修改它们分别对应的地方，但是你把 `PypiMirror` 改到了 `Repository` 上，配置文件错误会自动还原

我之前的错误改法是概率能打开alas，之前在群里问我的改法对不对，有个人跟我说就那么改。然后我误打误撞进去了。才一直对我的错误改法深信不疑。
