### ISSUE TITLE
 主线 - 困难12-4 开荒 有BUG ... boss 都没出来  切换二队 一直走来走去 .....

### ISSUE THREAD

**Issue by zeroxsama** [LmeSzinc/AzurLaneAutoScript#1263]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

 主线 - 困难12-4 开荒 有BUG ... boss 都没出来  切换二队 一直走来走去 .....
关闭辅助后   手动切换道中队  打了战斗一次  然后BOSS 出来了  
不太清楚  这个是根据每张地图的 战斗次数  来判断boss出来没出来 
还是根据 图片识别来判断的
如果是地图 战斗次数的话  困难12-4 加1应该就好了

### 如何复现

设置好 主线 困难 12-4 开荒

### 预期行为

能正确的打boss

**Comment by LmeSzinc** [comment]
#885
