### ISSUE TITLE
永夜幻光D2六战问题

### ISSUE THREAD

**Issue by nh632343** [LmeSzinc/AzurLaneAutoScript#127]
D2是6战出BOSS，现在是1队会打6战
请问能不能设置成空弹就不打，由2队再打一战？
还有可以设置优先选择1星敌人吗？

**Comment by LmeSzinc** [comment]
这个要自己写地图逻辑, 可以看一下https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/development, 或者模仿已有的地图
现在D2的逻辑是
```
class Campaign(CampaignBase):
    MAP = MAP

    def battle_0(self):
        if self.clear_siren():
            return True
        if self.clear_enemy(scale=(2,), genre=['light', 'main', 'enemy', 'carrier']):
            return True
        if self.clear_enemy(genre=['light', 'main', 'enemy']):
            return True

        return self.battle_default()

    def battle_5(self):
        if self.clear_enemy(scale=(1,)):
            return True
        if self.clear_enemy(scale=(2,), genre=['light', 'main', 'enemy', 'carrier']):
            return True
        if self.clear_enemy(genre=['light', 'main', 'enemy']):
            return True

        return self.battle_default()

    def battle_6(self):
        return self.fleet_boss.clear_boss()
```
翻译:
第一战到第五战, 精英 > 二星侦查 > 二星主力 > 二星未知 > 二星航空 > 侦查 > 主力 > 航空 > 默认权重
第六战, 一星 > 二星侦查 > 二星主力 > 二星未知 > 二星航空 > 侦查 > 主力 > 航空 > 默认权重
第七战, BOSS队打BOSS

**Comment by nh632343** [comment]
我在d2.py增加了log输出，但是重新启动也没看到有输出
感觉我的改动无效
大佬看看是为什么

    def battle_0(self):
        
        print("enter battle 0")
        logger.info("enter battle 0")
        if self.clear_siren():
            return True
        if self.clear_enemy(scale=(2,), genre=['light', 'main', 'enemy', 'carrier']):
            return True
        if self.clear_enemy(genre=['light', 'main', 'enemy']):
            return True

        return self.battle_default()

**Comment by LmeSzinc** [comment]
开荒完了吗
开荒的时候会使用别的逻辑, 到安全海域之后才会使用自定义逻辑

**Comment by nh632343** [comment]
哦，我的是绿海还没三星，我再试一下

**Comment by nh632343** [comment]
大佬，还有个问题，自定义逻辑这里怎样判断舰队的血量情况？
能判断吗

**Comment by whoamikyo** [comment]
battle logic has no control over HP, however the GUI has a few options.

**Comment by nh632343** [comment]
OK, Thanks
