### ISSUE TITLE
需要对新的共斗活动进行适配

### ISSUE THREAD

**Issue by Marius-Streicher** [LmeSzinc/AzurLaneAutoScript#1270]
### 你的功能请求是否与问题有关？

需要作者大佬对新活动进行适配

**Comment by Arcelibs** [comment]
![image](https://user-images.githubusercontent.com/49543451/176722711-5e84f8b7-6c22-4101-a4a0-61d648a1c28c.png)

更新適配之後的活動會卡在介面上

**Comment by appleapple802** [comment]
#1271  後已可使用alas共鬥模塊 感謝您
