### ISSUE TITLE
[日服]新活动共斗出现了一些问题

### ISSUE THREAD

**Issue by binglingyao** [LmeSzinc/AzurLaneAutoScript#1274]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动后会卡在
![image](https://user-images.githubusercontent.com/60381869/176722924-2ed8ecb1-0fa2-4d19-b628-c4637d7d045b.png)
这个界面,直到等待时间过长停止调度
实测手动选取难度也不会进去,似乎是卡在识别上了
这个问题在<共斗活动每日>与<共斗活动>中均出现
实测国服中没有这个问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       RAID                                        
═══════════════════════════════════════════════════════════════════════════════════
─────────────────────────────── RAID_20220630_HARD ────────────────────────────────
INFO     23:45:00.964 │ RAID_20220630_HARD                                         
INFO     23:45:00.966 │ Count: 0                                                   
INFO     23:45:00.967 │ <<< UI ENSURE >>>                                          
INFO     23:45:00.969 │ UI get current page                                        
INFO     23:45:00.977 │ [UI] page_daily                                            
INFO     23:45:00.980 │ Goto page_raid                                             
INFO     23:45:00.982 │ <<< UI GOTO PAGE_RAID >>>                                  
INFO     23:45:00.985 │ Page switch: page_daily -> page_main                       
INFO     23:45:00.987 │ Click (1238,   26) @ GOTO_MAIN                             
INFO     23:45:02.081 │ Page switch: page_main -> page_raid                        
INFO     23:45:02.083 │ Click ( 621,  276) @ MAIN_GOTO_RAID                        
INFO     23:46:28.265 │ Page switch: page_main -> page_raid                        
INFO     23:46:28.266 │ Click ( 627,  283) @ MAIN_GOTO_RAID                        
INFO     23:47:22.310 │ Click ( 268,   36) @ MAP_PREPARATION_CANCEL                
WARNING  23:50:22.614 │ Wait too long                                              
WARNING  23:50:22.615 │ Waiting for {'BUILD_CHECK', 'COMMISSION_CHECK', 'WITHDRAW',
         'WAR_ARCHIVES_CHECK', 'MAIN_GOTO_CAMPAIGN', 'DORM_INFO', 'GET_SHIP',      
         'FLEET_PREPARATION', 'MEOWFFICER_INFO', 'MUNITIONS_CHECK', 'RAID_CHECK',  
         'RESHMENU_CHECK', 'DAILY_CHECK', 'DORM_CHECK', 'SHIPYARD_CHECK',          
         'POPUP_CANCEL', 'RESEARCH_CHECK', 'GET_MISSION', 'FLEET_CHECK',           
         'GUILD_CHECK', 'AUTO_SEARCH_MENU_EXIT', 'EVENT_CHECK',                    
         'RESET_TICKET_POPUP', 'MONTHLY_PASS_NOTICE', 'STORY_SKIP',                
         'ACADEMY_CHECK', 'EXERCISE_CHECK', 'STORY_LETTER_BLACK', 'REWARD_CHECK',  
         'RESET_FLEET_PREPARATION', 'SHOP_CHECK', 'META_CHECK', 'GET_ITEMS_1',     
         'MISSION_CHECK', 'CAMPAIGN_MENU_CHECK', 'PLAYER_CHECK',                   
         'BATTLE_PASS_NOTICE', 'RAID_FLEET_PREPARATION', 'MAP_PREPARATION',        
         'SUPPLY_PACK_CHECK', 'LOGIN_ANNOUNCE', 'DORMMENU_CHECK', 'GAME_TIPS',     
         'SP_CHECK', 'MEOWFFICER_CHECK', 'DORM_FEED_CANCEL', 'CAMPAIGN_CHECK',     
         'GUILD_POPUP_CONFIRM', 'BATTLE_PASS_CHECK', 'OS_CHECK',                   
         'LOGIN_RETURN_SIGN', 'DORM_TROPHY_CONFIRM', 'LOGIN_CHECK',                
         'EVENT_LIST_CHECK', 'EXCHANGE_CHECK', 'TACTICAL_CHECK'}                   
WARNING  23:50:22.621 │ Wait too long                                              
WARNING  23:50:22.623 │ Game stuck, com.YoStarJP.AzurLane will be restarted in 10  
         seconds                                                                   
WARNING  23:50:22.625 │ If you are playing by hand, please stop Alas               
INFO     23:50:22.627 │ Task call: Restart                                         
INFO     23:50:22.637 │ Bind task {'Alas', 'EventGeneral', 'Raid', 'General'}      
INFO     23:50:22.639 │ Save config ./config\日服.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2022, 6, 30, 23, 50, 22),     
         Restart.Scheduler.Enable=True                                             
INFO     23:50:32.646 │ Scheduler: End task `Raid`                                 
INFO     23:50:32.647 │ [日服] exited. Reason: Finish
```

### 截图

![image](https://user-images.githubusercontent.com/60381869/176723790-570b0115-32df-4568-b7d8-7fb959c95705.png)

**Comment by ccodykid** [comment]
Same issue on EU server

**Comment by mikage3miya** [comment]
日服，会进行到H15/15 N9/15时卡住
手动打一把N变成8/15后可以继续，之后7/15又会卡住疑似OCR相关出了问题

> ════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                   RAIDDAILY                                                    
════════════════════════════════════════════════════════════════════════════════════════════════════════════════
INFO     09:32:10.624 │ <<< UI ENSURE >>>                                                                       
INFO     09:32:10.626 │ UI get current page                                                                     
INFO     09:32:10.640 │ [UI] page_main                                                                          
INFO     09:32:10.643 │ Goto page_raid                                                                          
INFO     09:32:10.645 │ <<< UI GOTO PAGE_RAID >>>                                                               
INFO     09:32:10.696 │ Page switch: page_main -> page_raid                                                     
INFO     09:32:10.699 │ Click ( 631,  284) @ MAIN_GOTO_RAID                                                     
INFO     09:32:11.387 │ Page arrive: page_raid                                                                  
═════════════════════════════════════════════════════ HARD ═════════════════════════════════════════════════════
INFO     09:32:11.391 │ HARD                                                                                    
INFO     09:32:11.410 │ Loading OCR model: ./bin/cnocr_models/cnocr                                             
INFO     09:32:11.470 │ [IRIS_OCR_REMAIN_HARD 0.076s] 1                                                         
WARNING  09:32:11.473 │ Unexpected ocr result: 1                                                                
INFO     09:32:11.476 │ [Hard Remain] 0                                                                         
INFO     09:32:11.748 │ [IRIS_OCR_REMAIN_HARD 0.044s] 1515                                                      
WARNING  09:32:11.750 │ Unexpected ocr result: 1515                                                             
INFO     09:32:11.752 │ [Hard Remain] 0                                                                         
INFO     09:32:12.013 │ [IRIS_OCR_REMAIN_HARD 0.021s] 1515                                                      
WARNING  09:32:12.015 │ Unexpected ocr result: 1515                                                             
INFO     09:32:12.017 │ [Hard Remain] 0                                                                         
════════════════════════════════════════════════════ NORMAL ════════════════════════════════════════════════════
INFO     09:32:12.020 │ NORMAL                                                                                  
INFO     09:32:12.042 │ [IRIS_OCR_REMAIN_NORMAL 0.019s] 915                                                     
WARNING  09:32:12.043 │ Unexpected ocr result: 915                                                              
INFO     09:32:12.045 │ [Normal Remain] 0                                                                       
INFO     09:32:12.337 │ [IRIS_OCR_REMAIN_NORMAL 0.023s] 915                                                     
WARNING  09:32:12.340 │ Unexpected ocr result: 915                                                              
INFO     09:32:12.342 │ [Normal Remain] 0                                                                       
INFO     09:32:12.613 │ [IRIS_OCR_REMAIN_NORMAL 0.024s] 915                                                     
WARNING  09:32:12.616 │ Unexpected ocr result: 915                                                              
INFO     09:32:12.618 │ [Normal Remain] 0                                                                       
INFO     09:32:12.620 │ Delay task `RaidDaily` to 2022-07-02 00:00:00 (server_update='00:00')                   
INFO     09:32:12.633 │ Bind task {'Alas', 'General', 'RaidDaily', 'EventGeneral'}                              
INFO     09:32:12.636 │ Save config ./config\alas.json, RaidDaily.Scheduler.NextRun=datetime.datetime(2022, 7,  
         2, 0, 0)                                                                                               
INFO     09:32:12.647 │ Scheduler: End task `RaidDaily`                                                         
INFO     09:32:12.650 │ [Server] jp                                                                             
INFO     09:32:12.668 │ Bind task {'General', 'Alas'}                                                           
INFO     09:32:12.671 │ No task pending
