### ISSUE TITLE
希望每日余烬信标增加一拳走人模式

### ISSUE THREAD

**Issue by mikage3miya** [LmeSzinc/AzurLaneAutoScript#1284]
### 你的功能请求是否与问题有关？

现有的大世界通用设置中，打余烬信标一项只有一直打直到打完的设计
在无法一刀斩杀的情况下会产生额外的燃油消耗

### 解决方案

希望增加一个新的可选模式
在该模式下仅由自身的舰队进行一次无燃料消耗的攻击，之后不再继续攻击
转为每隔30分钟检查是否完成击杀，若未击杀则再次扩散至全员，重复检查-扩散循环直至击杀

### 其他内容

没错我就是个打META全求人的弱鸡啦

**Comment by LmeSzinc** [comment]
这个可以有

**Comment by yeyyt** [comment]
支持，对于我这种一拳六万都要看海妈脸色的人来说很需要

**Comment by LmeSzinc** [comment]
#1574
