### ISSUE TITLE
能否通过自行修改的方式，让alas支持更高分辨率

### ISSUE THREAD

**Issue by Francaise0923** [LmeSzinc/AzurLaneAutoScript#1303]
### 你的功能请求是否与问题有关？

显示器是4K屏幕，用720P太模糊了,N卡的整数缩放也不是很有效。

**Comment by LmeSzinc** [comment]
不可以。建议将模拟器和alas最小化到托盘区，然后正常地学习和工作。

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/1.-Start
> 使用 1280x720 分辨率的原因是：
> 
> - 720p 在图像清晰度和截图耗时之间有较好的平衡，480p 下海图识别正确率明显下降，1080p 截图耗时几乎翻倍
> - 异型屏没有统一的标准，适配非 16:9 分辨率带来的维护成本和获得的收益不符

**Comment by LmeSzinc** [comment]
模拟器本身是可以拉伸和缩放的全屏的，并且不会影响alas，群里有些第一次使用模拟器不知道，这里说一下
