### ISSUE TITLE
希望支持1920x1080分辨率（adb screencap）

### ISSUE THREAD

**Issue by defencer** [LmeSzinc/AzurLaneAutoScript#1316]
### 你的功能请求是否与问题有关？

用手机做测试，一台无法root的荣耀8，原生分辨率1920x1080，
使用（adb shell wm size 720x1280 ）
         （adb shell wm density 320）
后重启手机，这时候系统显示的是720x1280,使用系统自带截图软件是720x1280.但是手动测试adb screencap截图还是1920x1080，所以无法启动脚本。

### 解决方案

在使用wm size和wm density后，经过手动测试，发现adb shell input tap的输入坐标在屏幕上是正常的，所以我认为完全可以把1080x1920的adb截图等比缩放到720x1280,再对接脚本，应该就能用了。

另一台设备小米6，获取root权限，修改分辨率和adb截图正常。

**Comment by 18870** [comment]
#1303

**Comment by LmeSzinc** [comment]
是 `wm size` 的问题，群里的聊天记录给你参考一下

![ref1](https://user-images.githubusercontent.com/37934724/178111754-5cdd6c81-a93e-4cdc-a48f-6a3728c19868.png)
![ref2](https://user-images.githubusercontent.com/37934724/178111759-79c096c1-332f-4aa6-a29c-e3f67b695141.png)

**Comment by pein0saga** [comment]
有能力的话可以自己fork一个自己做，牺牲速度运行在高性能的机器上（随着硬件进步，未来可期）。毕竟碧蓝航线60FPS的动态大海和弹幕太耗性能了。

**Comment by 13167755816** [comment]
老哥，我也有一台root的小米6，但是用wm size和wm density后还是不行，和你荣耀的表现一样，你是拿啥改的小米6分辨率？

> ### 你的功能请求是否与问题有关？
> 用手机做测试，一台无法root的荣耀8，原生分辨率1920x1080， 使用（adb shell wm size 720x1280 ） （adb shell wm density 320） 后重启手机，这时候系统显示的是720x1280,使用系统自带截图软件是720x1280.但是手动测试adb screencap截图还是1920x1080，所以无法启动脚本。
> 
> ### 解决方案
> 在使用wm size和wm density后，经过手动测试，发现adb shell input tap的输入坐标在屏幕上是正常的，所以我认为完全可以把1080x1920的adb截图等比缩放到720x1280,再对接脚本，应该就能用了。
> 
> 另一台设备小米6，获取root权限，修改分辨率和adb截图正常。
> 
> ### 其他内容
> _No response_

老哥，我也有一台root的小米6，但是用wm size和wm density后还是不行，和你荣耀的表现一样，你是拿啥改的小米6分辨率？

**Comment by defencer** [comment]
> 老哥，我也有一台root的小米6，但是用wm size和wm density后还是不行，和你荣耀的表现一样，你是拿啥改的小米6分辨率？
> 
> > ### 你的功能请求是否与问题有关？
> > 用手机做测试，一台无法root的荣耀8，原生分辨率1920x1080， 使用（adb shell wm size 720x1280 ） （adb shell wm density 320） 后重启手机，这时候系统显示的是720x1280,使用系统自带截图软件是720x1280.但是手动测试adb screencap截图还是1920x1080，所以无法启动脚本。
> > ### 解决方案
> > 在使用wm size和wm density后，经过手动测试，发现adb shell input tap的输入坐标在屏幕上是正常的，所以我认为完全可以把1080x1920的adb截图等比缩放到720x1280,再对接脚本，应该就能用了。
> > 另一台设备小米6，获取root权限，修改分辨率和adb截图正常。
> > ### 其他内容
> > _No response_
> 
> 老哥，我也有一台root的小米6，但是用wm size和wm density后还是不行，和你荣耀的表现一样，你是拿啥改的小米6分辨率？

我是开发版系统，用wm size是可以实现的，miui10 9.9.3

**Comment by nixin92** [comment]
![11129092-33b2b3d84d8e509f](https://github.com/user-attachments/assets/9e95ce96-f129-4c53-b0bb-1713903329ab)
要打开usb调试（安全设置）

**Comment by tencentbook** [comment]
改分辨率要搭配scrcpy才有用，我用adb改了后alas不能识别，用scrcpy连接后就能正常识别了
