### ISSUE TITLE
希望 每日收获-其他商店 下的每个商店都有独立开关

### ISSUE THREAD

**Issue by MJSummer** [LmeSzinc/AzurLaneAutoScript#1321]
![image](https://user-images.githubusercontent.com/73144479/178635230-41d22cc4-e1ea-4a5f-9131-c6c7b207fe96.png)
例如在这个地方提供一个开启舰队商店购买与否的复选框，后面其他商店以此类推

**Comment by SaiCateDoan** [comment]
如果输入一个空格即为不购买，留空则恢复默认值
留空为不购买在现在的alas上没法简单实现，并且因为需求太小，暂时没有相关计划
