### ISSUE TITLE
活动图设置无法保存

### ISSUE THREAD

**Issue by 757957414** [LmeSzinc/AzurLaneAutoScript#1328]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

因为本次复刻的活动和以前的一样，所以打算直接设置活动图（活动图-2）刷图，但是发现无论如何切换【活动名称】都会自动切换回去

也许是因为【自动切换为最新的活动】的问题？

### 如何复现

前往 【活动】-》【活动图-2】-【修改活动名称为：蝶海梦花】-》【弹出保存成功】-》【总览】-》【启动】-》
抛出异常：
WARNING  21:47:13.202 │ Map file not found: campaign.event_20201012_cn.ht5         
WARNING  21:47:13.205 │ Existing files: ['sp1', 'sp2', 'sp3']                      
CRITICAL 21:47:13.208 │ Possible reason #1: This event (event_20201012_cn) does not
         have ht5       
-》【查看配置】-》【活动名称自动变更为：复刻划破海空之翼】

### 截图

![image](https://user-images.githubusercontent.com/23210825/178999801-0d72bb63-8a3e-44d5-874e-2c1c5f3909bf.png)
![image](https://user-images.githubusercontent.com/23210825/178999874-f0f18c5a-5cb3-48c5-8923-c9524756506e.png)
![image](https://user-images.githubusercontent.com/23210825/178999931-09e9ff6d-f29d-4e9c-b604-47ad03955bb1.png)

**Comment by 757957414** [comment]
我试着手动修改配置文件，发现居然无效= =
![image](https://user-images.githubusercontent.com/23210825/179004274-c9f6b9dd-718e-4b07-95f6-dffb16fc7329.png)
![image](https://user-images.githubusercontent.com/23210825/179004363-88d65dc1-4a61-4801-82f2-6c5bee3610d7.png)

**Comment by 757957414** [comment]
> ![](https://user-images.githubusercontent.com/22175295/179005852-934fd300-89b8-4788-aba0-f2f1e8298f58.png) ![](https://user-images.githubusercontent.com/22175295/179006494-d8541d07-0ed8-4087-9004-e444e28e66a3.jpg)



> ![](https://user-images.githubusercontent.com/22175295/179005852-934fd300-89b8-4788-aba0-f2f1e8298f58.png) ![](https://user-images.githubusercontent.com/22175295/179006494-d8541d07-0ed8-4087-9004-e444e28e66a3.jpg)
我知道现在还没出，我是想看看之前的能不能用，因为按照官方说法是没变的，也就是说这个选择是无效的是么？

**Comment by SuLiu99** [comment]
我也遇到了同一个问题 但是吧以前的碟海梦花的活动文件复制到event_20201012_cn下 是可以正常使用的

**Comment by xzjjasper** [comment]
手动修改可以参考[https://github.com/LmeSzinc/AzurLaneAutoScript/pull/1323](url)

**Comment by 757957414** [comment]
> 1323

你这个地址点开是没有的

**Comment by LmeSzinc** [comment]
#1332
