### ISSUE TITLE
未来是否会考虑加入AI自律功能躲子弹/撞船

### ISSUE THREAD

**Issue by SaferSky** [LmeSzinc/AzurLaneAutoScript#134]
这个只是个设想哈哈，用AI控制来代替官方的自律。。如果能做一个躲子弹和敌船的自律功能就好了。 
这功能主要是用来给等级装备不够自律，但手操能过的船练级用。说白了就是想省点油。。
另外例如7-2，单后排时，有时候还需要结合血量，前排主动去脸接自爆船帮低等级后排扛伤害。。

当然这些要求有点过分哈哈，也就说说而已，能做出来那就牛逼上天了。大佬别当真。

**Comment by LmeSzinc** [comment]
这个太难了, 只能YY一下.

不过, 已经有一个低级的手操功能, 叫"中路站桩", 会在开场5秒后把船移到中间, 并自动放空袭和鱼雷.
这次永夜幻光D1, 后排单零破祥凤自律有时会暴毙, 改用中路站桩之后, 不漏过一艘潜艇, 零破祥凤直接带双液压
