### ISSUE TITLE
[收菜] 数据收集(打主线)类研发 筛选逻辑 ；后宅收金币/爱心

### ISSUE THREAD

**Issue by SaferSky** [LmeSzinc/AzurLaneAutoScript#135]
目前从wiki的列表上看，所有的数据收集类都是4小时，但是有蓝紫金3类，其中金色性价比最高。
目前的filter只能用B4，如何才能只选金色的打主线类研发呢？

另外就是后宅收金币/爱心，这个未来会加入吗？

**Comment by LmeSzinc** [comment]
B系 和 E系科研都是默认丢弃, 写死在代码里的. 有考虑过放开 E-6
丢弃数据收集 (B series) 和 部件分解 (E-2) 的考虑是:
- 无法保证完成科研要求, 可能会出现挂了一天, 但是前置条件未完成的情况.
- B系科研收益低, 根据统计, 金色B系科研 相当于 12小时白嫖 (C-12), 还会消耗大量石油.

后宅喂食, 点爱心这个, 未来会有的.

**Comment by SaferSky** [comment]
谢谢回答！
