### ISSUE TITLE
增加每日主线困难图出击次数选择

### ISSUE THREAD

**Issue by xzjjasper** [LmeSzinc/AzurLaneAutoScript#1351]
### 你的功能请求是否与问题有关？

希望可以为每日任务 > 困难图 增加次数选择功能。目前我的解决办法是每日添加限制次数为1的出击，但队列优先度低且需要每日更改出击次数并加入队列。

**Comment by LmeSzinc** [comment]
不会添加这个功能，我不认为每天只打一次困难图会带来什么收益
