### ISSUE TITLE
请求添加道中全清功能

### ISSUE THREAD

**Issue by xzw2935** [LmeSzinc/AzurLaneAutoScript#1367]
### 你的功能请求是否与问题有关？

12-4练级，就是贪那10点石油的入场费

**Comment by bookbug666** [comment]
出擊的行為不就是在耗油了嗎?你想省油為什麼不減少出擊呢?
何況出BOSS之後還清道中敵人的話:

1. 你是空彈進行所有戰鬥(練級的隊伍要能承受空彈Debuff的影響)
2. 戰鬥的額外獎勵(結算下面那個2K多的物資)並不會多給，單從綜合產出是不值得的

而且吧 如果單論道中的**單場經驗獲得/鎖油油耗**，你應該要選擇11-1的
建議先思考自己的issue是不是真的能幫助自己，還是其實你看似想改善收益但其實在別的地方虧了

**Comment by bookbug666** [comment]
參考一下海事局的 [出击常去关卡收益分析](https://wiki.biligame.com/blhx/%E5%87%BA%E5%87%BB%E5%B8%B8%E5%8E%BB%E5%85%B3%E5%8D%A1%E6%94%B6%E7%9B%8A%E5%88%86%E6%9E%90) 吧

**Comment by ZSJsts** [comment]
> 出擊的行為不就是在耗油了嗎?你想省油為什麼不減少出擊呢? 何況出BOSS之後還清道中敵人的話:
> 
> 1. 你是空彈進行所有戰鬥(練級的隊伍要能承受空彈Debuff的影響)
> 2. 戰鬥的額外獎勵(結算下面那個2K多的物資)並不會多給，單從綜合產出是不值得的
> 
> 而且吧 如果單論道中的**單場經驗獲得/鎖油油耗**，你應該要選擇11-1的 建議先思考自己的issue是不是真的能幫助自己，還是其實你看似想改善收益但其實在別的地方虧了

您好我是刷好感的.
由于伏击的出现次数调整,不再像以前那样无限刷伏击.
导致现在刷好感度不得不去寻找道中最多的场景手动清光.
这个时候道中全清的意义就出现了.如果1次出击后能打10轮.那么比大5轮效率要高一倍.因为每次进入地图扣一次心情.道中战斗次数不影响心情扣除.
