### ISSUE TITLE
日服触发自动重启游戏后停在开始界面

### ISSUE THREAD

**Issue by railzy** [LmeSzinc/AzurLaneAutoScript#137]
自动重启游戏后进入到开始界面后就停住没有自动点击了，似乎是没有识别到已进入开始界面？
请问哪张图片是对应检查开始界面的，我再替换下试试
> 2020-08-04 11:51:06.372 | INFO | In stage.
> 2020-08-04 11:51:07.580 | INFO | <<< CAMPAIGN END >>>
> 2020-08-04 11:51:07.581 | INFO | [Emotion_bug] 108/100
> 2020-08-04 11:51:07.581 | INFO | <<< TRIGGERED RESTART AVOID EMOTION BUG >>>
> 2020-08-04 11:51:07.581 | INFO | <<< APP RESTART >>>
> 2020-08-04 11:51:07.581 | INFO | App stop: com.YoStarJP.AzurLane
> 2020-08-04 11:51:08.306 | INFO | App start: com.YoStarJP.AzurLane
> 2020-08-04 11:51:09.098 | INFO | <<< APP LOGIN >>>
> 2020-08-04 11:52:02.212 | WARNING | Wait too long
> 2020-08-04 11:52:02.212 | WARNING | Waiting for {'GET_ITEMS_2', 'LOGIN_ANNOUNCE', 'CAMPAIGN_CHECK', 'GET_ITEMS_1', 'EXERCISE_CHECK', 'LOGIN_CONFIRM', 'LOGIN_GAME_UPDATE', 'MAIN_GOTO_CAMPAIGN', 'GOTO_MAIN', 'EVENT_LIST_CHECK', 'SWITCH_2_HARD', 'FLEET_CHECK', 'INFO_BAR_2', 'LOGIN_RETURN_SIGN', 'SWITCH_2_EX', 'GET_MISSION', 'EVENT_CHECK', 'POPUP_CANCEL', 'INFO_BAR_1', 'SWITCH_1_NORMAL', 'DAILY_CHECK', 'INFO_BAR_3', 'GET_SHIP'}
> 2020-08-04 11:52:02.212 | WARNING | Wait too long
> 2020-08-04 11:52:02.213 | INFO | Saving error: ./log/error/1596513122213
> 2020-08-04 11:52:16.606 | WARNING | com.YoStarJP.AzurLane will be restart in 10 seconds
> 2020-08-04 11:52:16.606 | WARNING | If you are playing by hand, please stop Alas
> 2020-08-04 11:52:26.607 | INFO | <<< APP RESTART >>>
> 2020-08-04 11:52:26.607 | INFO | App stop: com.YoStarJP.AzurLane
> 2020-08-04 11:52:27.162 | INFO | App start: com.YoStarJP.AzurLane
> 2020-08-04 11:52:27.869 | INFO | <<< APP LOGIN >>>
> 2020-08-04 11:53:37.965 | WARNING | Wait too long
> 2020-08-04 11:53:37.965 | WARNING | Waiting for {'GET_ITEMS_2', 'POPUP_CANCEL', 'INFO_BAR_1', 'LOGIN_ANNOUNCE', 'LOGIN_CONFIRM', 'LOGIN_GAME_UPDATE', 'GET_MISSION', 'GOTO_MAIN', 'LOGIN_RETURN_SIGN', 'INFO_BAR_3', 'MAIN_GOTO_CAMPAIGN', 'EVENT_LIST_CHECK', 'GET_ITEMS_1', 'GET_SHIP', 'INFO_BAR_2'}
> Traceback (most recent call last):
>   File "C:\fakepath\AzurLaneAutoScript\alas.py", line 27, in run
>     self.__getattribute__(command.lower())()
>   File "C:\fakepath\AzurLaneAutoScript\alas.py", line 141, in event
>     az.run(self.config.CAMPAIGN_EVENT, folder=self.config.EVENT_NAME)
>   File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 139, in run
>     if self.handle_app_restart():
>   File "C:\fakepath\AzurLaneAutoScript\module\campaign\run.py", line 124, in handle_app_restart
>     self.app_restart()
>   File "C:\fakepath\AzurLaneAutoScript\module\handler\login.py", line 61, in app_restart
>     self.handle_app_login()
>   File "C:\fakepath\AzurLaneAutoScript\module\handler\login.py", line 19, in handle_app_login
>     self.device.screenshot()
>   File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 48, in screenshot
>     self.stuck_record_check()
>   File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 113, in stuck_record_check
>     raise GameStuckError(f'Wait too long')
> module.exception.GameStuckError: Wait too long
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\fakepath\AzurLaneAutoScript\alas_jp_cn.pyw", line 8, in <module>
>     main()
>   File "C:\fakepath\AzurLaneAutoScript\toolkit\lib\site-packages\gooey\python_bindings\gooey_decorator.py", line 130, in <lambda>
>     return lambda *args, **kwargs: func(*args, **kwargs)
>   File "C:\fakepath\AzurLaneAutoScript\module\config\argparser.py", line 402, in main
>     alas.run(command=command)
>   File "C:\fakepath\AzurLaneAutoScript\alas.py", line 39, in run
>     az.handle_game_stuck()
>   File "C:\fakepath\AzurLaneAutoScript\module\handler\login.py", line 97, in handle_game_stuck
>     self.app_restart()
>   File "C:\fakepath\AzurLaneAutoScript\module\handler\login.py", line 61, in app_restart
>     self.handle_app_login()
>   File "C:\fakepath\AzurLaneAutoScript\module\handler\login.py", line 19, in handle_app_login
>     self.device.screenshot()
>   File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 48, in screenshot
>     self.stuck_record_check()
>   File "C:\fakepath\AzurLaneAutoScript\module\device\device.py", line 113, in stuck_record_check
>     raise GameStuckError(f'Wait too long')
> module.exception.GameStuckError: Wait too long

**Comment by whoamikyo** [comment]
Try replace LOGIN_CONFIRM and LOGIN_CHECK.

**Comment by whoamikyo** [comment]
Maybe you need replace more assets, it seems that many assets in the Japanese version have not been added.
