### ISSUE TITLE
[收菜-战术学院] 同类型技能树不足时 增加停止继续选项

### ISSUE THREAD

**Issue by SaferSky** [LmeSzinc/AzurLaneAutoScript#138]
在战术学院里面，如果同类型的技能书全用完了，例如红书，能否添加一个停止学习的选项？
目前的逻辑是如果同类型的书没了，就会消耗同等级的其他书继续。
但在很多时候其实3类技能书，尤其是最高级的，都非常缺。如果直接吃其他类型，损失的经验实在太多。

**Comment by LmeSzinc** [comment]
已添加
