### ISSUE TITLE
能否添加手动关闭自动科研的功能

### ISSUE THREAD

**Issue by boxingboxingbo** [LmeSzinc/AzurLaneAutoScript#1389]
### 你的功能请求是否与问题有关？

有了科研队列之后，自动科研的需求已经没那么高了。

### 解决方案

添加按钮关闭自动科研功能

**Comment by SaarChaffee** [comment]
> 

请问你想关科研的原因是什么？
<hr/>
以下是我个人对于ALAS全自动科研的看法：

窑子有了科研队列之后，alas真正做到了无缝科研（以前旧版本还得等几秒认点进去科研项目），而且alas能很快帮我判断这一轮需要选什么，并且内置了对24h科研来说收益最大化的选项，一切交给alas，不需要在意科研完成了没有。当然了如果要自己调一下项目的优先度，那alas还有[自定义过滤器](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn)，可以让alas按照你的想法去做科研。

**Comment by boxingboxingbo** [comment]
> 

感谢回复。

我想关闭自动科研的原因有这么几个：
1. 我对自己编写的自定义过滤器是否完备没有信心，但是以往没有科研队列的时候，全程手操也无法实现，有了队列之后感觉自己手操更放心一些。
2. 更加想自己确认科研任务的完成，知道有没有彩装备图纸，或者彩船图纸，虽然这没有什么实际意义，不过感觉会更有满足感一些......
3. 考虑到这个功能的实现（增加关闭按钮）在技术上或许非常简单，比较好实现，也是希望增加这个简单功能的一个原因。

**Comment by yzanhua** [comment]
我也希望加入手动关闭自动科研的功能。

有时ALAS的逻辑不是很方便：
当科研队列里还有科研，且科研资源（魔方/资金等）不足时:
1. 有时我会希望等待前面的科研完成，期间我把资源刷足
2. 有时我会选择把能做的先加入队列，完全交给ALAS
选项2 似乎是ALAS的默认选择，但有时我会在1和2之间左右横跳。（类似问题已经有朋友提交了pull request）

增加这个功能（增加关闭按钮）后，如果玩家遇到预料之外的问题可以选择先关闭自动科研，然后到这边提交issue/pull request，以此最大化自由度。

**Comment by moshan1997** [comment]
貌似仓库作者不打算给你关闭的自由，之前的issue就被删了。
并且其他人所做的fork也不允许发出来，不然也删你评论。
同时在[pr#1360]藏恶意代码(https://github.com/LmeSzinc/AzurLaneAutoScript/pull/1360/commits/620e6510bc738b9cb30351b610e8dd2358a493fb) 中的 [connection_attr.py#L44~L61](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/620e6510bc738b9cb30351b610e8dd2358a493fb/module/device/connection_attr.py#L44)，如果修改过锁定的数量你adb就会被加个换行符，连不上。
我不打算对此做过多主观评判，但还是提醒开源作者注意自己的声誉。

**Comment by moshan1997** [comment]
如果你有需要可以从这两个大佬的fork中选一个换了，https://github.com/buding983/AzurLaneAutoScript/issues/1，https://github.com/foxwhite25/AzurLaneAutoScriptThatWorks，只是解除了锁定和恶意代码。

**Comment by SaiCateDoan** [comment]
怎么又是这个问题...

这里是原因：在Alas更新调度器后，绝大部分用户没法很快理解Alas的调度器系统，把Alas当成传统脚本使用，这使得alas完全无法发挥其独特的优势。lme希望通过强制运行所有用户都需要的任务这种方式，让用户能够快速接受调度器的运作方式。

但是在发布后讨论的过程中遇到了一些异常的反对意见，在询问和调查后发现来源于工作室和代练。虽然作为一个开源脚本，alas不会拒绝也不能拒绝任何用户，但是任何使用alas的人也应当遵守alas的规则，使用alas进行代练还不开科研多少有点过分，因此alas开发组拒绝了他们的issue。

然后就过分了，经常有人来alas的issue下面发同样的内容，基本换汤不换药，有时候还跑到别的issue下面污染讨论，被block了就换小号，一个字都不带变的，丝毫不掩饰自己的恶意。在沟通无效和拉黑大战之后，alas禁止了一段时间这个话题的讨论，但是还是没法完全解决问题，事实上这个issue里就有个刚刚被删comment的小号。当然根据开源协议，alas允许任何有能力的用户修改代码并取消强制科研，但是同样alas不欢迎任何来主仓库跳脸的坏孩子。

PS：alas之前还遭遇过违反开源协议倒卖脚本的情况，因此加入了一些防止恶意修改的代码

**Comment by SaiCateDoan** [comment]
> 我也希望加入手动关闭自动科研的功能。
> 
> 有时ALAS的逻辑不是很方便： 当科研队列里还有科研，且科研资源（魔方/资金等）不足时:
> 
> 1. 有时我会希望等待前面的科研完成，期间我把资源刷足
> 2. 有时我会选择把能做的先加入队列，完全交给ALAS
> 
> 选项2 似乎是ALAS的默认选择，但有时我会在1和2之间左右横跳。（类似问题已经有朋友提交了pull request）
> 
> 增加这个功能（增加关闭按钮）后，如果玩家遇到预料之外的问题可以选择先关闭自动科研，然后到这边提交issue/pull request，以此最大化自由度。

刚好你说的pr就是我在做，还没写完
做好之后会有一个选项，让用户在1和2之间进行选择，默认是1（不会导致科研停转，事实上科研停转导致的亏损远比一个高收益科研来的大），如果用户感觉自己会长期处在资源不足且不能长时间运行alas的情况，可以选择2，这样alas会尽量填满科研队列，如果关闭alas也不会导致科研停转

**Comment by yzanhua** [comment]
> 怎么又是这个问题...
> ...
> 经常有人来alas的issue下面发同样的内容
（正常）用户没法知道类似issue被问了多少遍，毕竟won't fix issue, readme, wiki 目前都找不到说明。 

原来是有打击号贩子这方面的考虑，👍

> 刚好你说的pr就是我在做，还没写完
👍👍

**Comment by burner114514** [comment]
> 但是在发布后讨论的过程中遇到了一些异常的反对意见，在询问和调查后发现来源于工作室和代练。虽然作为一个开源脚本，alas不会拒绝也不能拒绝任何用户，但是任何使用alas的人也应当遵守alas的规则，使用alas进行代练还不开科研多少有点过分，因此alas开发组拒绝了他们的issue。

不过很多不是代练的也遇到了一些问题想要暂时关闭项目，相关issues如下，但这些问题到最后都没有修复就打上user error wont fix，也不解释就把issue关了，很难不让人联想你们是不是要去恰米了。能不能说是代练之前先解决一些正常玩家会有的问题。。。

https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1363
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1279
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1076

**Comment by buzhidaoshuoshenmehao** [comment]
> 怎么又是这个问题...
> 
> 这里是原因：在Alas更新调度器后，绝大部分用户没法很快理解Alas的调度器系统，把Alas当成传统脚本使用，这使得alas完全无法发挥其独特的优势。lme希望通过强制运行所有用户都需要的任务这种方式，让用户能够快速接受调度器的运作方式。
> 
> 但是在发布后讨论的过程中遇到了一些异常的反对意见，在询问和调查后发现来源于工作室和代练。虽然作为一个开源脚本，alas不会拒绝也不能拒绝任何用户，但是任何使用alas的人也应当遵守alas的规则，使用alas进行代练还不开科研多少有点过分，因此alas开发组拒绝了他们的issue。
> 
> 然后就过分了，经常有人来alas的issue下面发同样的内容，基本换汤不换药，有时候还跑到别的issue下面污染讨论，被block了就换小号，一个字都不带变的，丝毫不掩饰自己的恶意。在沟通无效和拉黑大战之后，alas禁止了一段时间这个话题的讨论，但是还是没法完全解决问题，事实上这个issue里就有个刚刚被删comment的小号。当然根据开源协议，alas允许任何有能力的用户修改代码并取消强制科研，但是同样alas不欢迎任何来主仓库跳脸的坏孩子。
> 
> PS：alas之前还遭遇过违反开源协议倒卖脚本的情况，因此加入了一些防止恶意修改的代码

我自己做科研会获得快乐 所以是倾向于自己手动做的 即便是优化到下面的选项1、2能够完全符合我的科研选择逻辑的时候
对我而言 Alas是帮我做不快乐的部分 留下快乐的部分给我自己做的系统
仅仅只是表达自己的想法 没有别的意思


顺便我想问问关于夜间委托 会比较不容易添加吗 比如说到了晚上一定的时间 优先选夜间魔方＞油＞快速建造
我发现晚上都是优先跑6小时快速建造 
还是说不需要添加 只要我自己设置好过滤器就可以了？


题外话：
我不懂写代码 也不知道表达想法要去哪里 只能顺着alas摸到这里来
我不知道还有这种 代练撕逼的事情 

昨天第一次注册了账号并发表和这个一样的想法  估计是被秒删了 我以为是没发出来 又发了一遍
再来就发现这条建议 我搞不懂这个网站是怎么用的 我以为是对我的想法优化后发表的 
今天看完发现无法评论 但又好像可以发表意见 搞了半天没搞懂 
最后感觉是被当小号禁言了 又注册了第二个账号来评论 

如果大佬们觉得有一些功能已经不需要再商讨了 这个网站有没有办法挂一下公告之类的 告诉新人怎么回事 不要重复发帖踩雷

**Comment by bookbug666** [comment]
如果你是要暫時關閉，為什麼不Fork一個自己的專案然後參考Wiki的說明進行GUI選項的修改呢(也許Lme不會希望我說明怎麼操作所以我不明說，刪掉我這個comment也無所謂)

我先假設上面沒有惡意的友善詢問者們都不是代練工作室，如果今天如五期科研新增科研隊列造成alas的科研無法正常運作，那麼確實暫時性的關閉比關閉整個alas更好

真的迫切希望alas有你想要的功能的話，你可以自己弄一個(存在local或是哪天這個需求又出現了你可以pull request)，順便還能參與alas的開發，我相信研發組不會討厭新人加入開發的

**Comment by Ringo3939** [comment]
其实出现这个问题的一个因素可能在于官方提供队列与5期科研的性能、厨力因素跟alas现有功能之间的矛盾导致最近反馈得比较多；两彩+哈尔滨有较高强度与厨力加成（比如我），我可能倾向于疯狂切方块强刷这些角色的蓝图，对于其他的可能就无所谓，而目前alas是没有指定角色优先的功能的；同时自定义顺序可能依然有一些使用门槛。
另外，我记得以前是有开关的，不知道在哪个版本更新后专门锁定了这个开关，，

**Comment by tihSdoolB** [comment]
我也建议能手动关闭自动科研，纵使咸鱼如我也会有资源紧缺的时候，或者说对选择科研的优先级会随着科研进度、游戏版本、活动皮肤、资源情况发生剧烈变化，经常调过滤器顺序在我看来是非常笨拙的方法，官方的科研队列其实弱化了玩家对自动科研的需求

**Comment by bookbug666** [comment]
![image](https://user-images.githubusercontent.com/29662367/180993984-3470eb44-21cf-4a58-9c4e-92f503739b14.png)
如果有存物資需求關閉物資使用不是就能達成了?

甚至你就所有都不使用(如圖介面)，實質上不就關閉了嗎

角色優先很簡單啊，自定義過濾器直接把角色名字對應的縮寫代號寫進去就好
並不需要經常對整個過濾器調整，你只需要關閉物資/方塊使用，Alas就會跳過那些使用物資/方塊的科研任務並從剩下的白嫖科研或是消耗部件/裝備箱(前提是你的自訂過濾器沒有將那些刪除)

**Comment by tihSdoolB** [comment]
> ![image](https://user-images.githubusercontent.com/29662367/180993984-3470eb44-21cf-4a58-9c4e-92f503739b14.png) 如果有存物資需求關閉物資使用不是就能達成了?
> 
> 甚至你就所有都不使用(如圖介面)，實質上不就關閉了嗎
> 
> 角色優先很簡單啊，自定義過濾器直接把角色名字對應的縮寫代號寫進去就好 並不需要經常對整個過濾器調整，你只需要關閉物資/方塊使用，Alas就會跳過那些使用物資/方塊的科研任務並從剩下的白嫖科研或是消耗部件/裝備箱(前提是你的自訂過濾器沒有將那些刪除)

感谢回复。但是还是关掉比较简单。
![图片](https://user-images.githubusercontent.com/47805988/181004567-050c9d47-0102-40dd-ab20-33a731430115.png)
