### ISSUE TITLE
[7-2三战捡垃圾] 请求增加 低血量更换道中2队

### ISSUE THREAD

**Issue by SaferSky** [LmeSzinc/AzurLaneAutoScript#139]
7-2捡垃圾顺便练级的时候，单前排单后排，会出现前排或后排血量告急的情况。
这时候一般我会换道中二队打剩下的几局，血量告急的队去踩A3。如果依旧打不过那就撤退。

这时候有可能出现C3, B4, C5全被堵死两队无法替换的情况。
如果这样我会赌一把，让二队直接打C3, B4, C5其中一个，残血队踩F1, G2, G3其中一个。
3战完如果问号在A2但是同时A3也刷新敌人，就放弃A2问号。（也可以加个功能，打4战取问号，虽然性价比低）

不知道未来能否考虑增加这个功能。

另外我觉得还可以加几个7-2之外也能用的功能：
* 回避3星舰队，除非挡路必须打
* 原本血量健康但是前排/后排旗舰突然血量爆减（例如点燃/疯狂撞船），血量达到阈值就退出重打，重打次数超过n次依旧打不过就停止。

**Comment by LmeSzinc** [comment]
需要复杂战斗逻辑的, 可以自己编写 campaign/campaign_main/campaign_7_2_mystery_farming.py, 血量也可以通过 `self.hp` 获取.
战斗中检测血量, 这个暂时做不了.

稍微讲一些题外话:
1. 一般 7-2 练单前排都会带女将或者夕张, 然后错开主炮和鱼雷的CD, 能清除量产和自爆, 也不会降低太多经验-油耗比.
2. 国服百级零破黑暗界加唐斯卡辛都可以7-2三战, 随便拉两个百级满破去7-2打三战不会有问题, 你等级/装备可能有很大问题.
