### ISSUE TITLE
无缝练猫，卡在了点击喂养上

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#1395]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

第一次使用  无缝练猫  功能，其实也不太有信心自己是否正确使用
现在是卡在了点击喂养键上
![L$514 P5D9}LHNQ~2FNQH}F](https://user-images.githubusercontent.com/49509508/180339104-51be8c03-0025-4282-838d-5936addfb399.png)

以下是我的配置项
![5$%2F1FTUF 3P0U5MROK$XI](https://user-images.githubusercontent.com/49509508/180339130-3a005ef4-39f5-4413-98cc-9855e3f23df5.png)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

[1658451253203.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9163643/1658451253203.zip)

**Comment by LmeSzinc** [comment]
检查一下你要用的猫都锁定了吗，舰队里配置的猫都锁定了吗，没锁定的猫还会出现在喂猫的界面但是选不了，Alas就一直尝试选它直到超出次数

**Comment by julystone** [comment]
是我搞错了。。。
