### ISSUE TITLE
希望添加活动图结束后自动关闭活动相关任务的功能

### ISSUE THREAD

**Issue by jingfengsama** [LmeSzinc/AzurLaneAutoScript#1396]
### 你的功能请求是否与问题有关？

昨天活动结束，关闭活动相关任务时候忘记关闭活动CD图，结果导致每次运行了 更高优先级的任务就停了，没注意log就继续开，过一会儿接着自动关闭。所以希望能在活动结束后自动关闭活动相关任务

### 解决方案

希望添加活动图结束后，自动关闭活动相关任务的功能
由项目人工添加时间可能难，可以通过进入出击界面之后看活动图是否开放来判定活动是否结束.

**Comment by bookbug666** [comment]
雖然不是提供方法，但我想問你是否有想過想要怎麼實現
判定是否有活動的方法很多，而且可能存在疊活動的情況
![image](https://user-images.githubusercontent.com/29662367/180363204-c5547e39-bd52-445a-b008-52e7fa060467.png)
![image](https://user-images.githubusercontent.com/29662367/180363236-ee627063-0d0c-4057-a36c-48d19b8915b1.png)
![image](https://user-images.githubusercontent.com/29662367/180363275-d08fc95e-1f72-4682-908f-e1419d1ceeff.png)

要讓每次不管是大活小活共鬥都能共用的module，如果我判定一個能適用全部嗎

活動的結束也有特定日期換日跟持續到維護前的情況，你希望Alas怎麼操作呢

#1379 我也跟你有類似想法，所以我也在思考怎麼讓Alas實現這個功能
只是我的方法是透過公告預判然後填入數值

如果你有不錯的思路我可以試著改看看，但也許得等到真的有活動才知道他是不是正常運行

**Comment by bookbug666** [comment]
補充一個，判定活動還有主頁面自動變換的Banner，但掃描那個大概不太穩定
應該不是一個好方法

**Comment by karegyudon** [comment]
这个功能不是已经现成有的么？每次开活动的时候设置一下就好了啊。

![Snipaste_2022-07-22_16-13-43](https://user-images.githubusercontent.com/22168767/180395086-16fdab94-c41f-4c71-8cc7-79bed974569c.png)

**Comment by LmeSzinc** [comment]
可以检查 `活动筹备中` 这几个字，如果出现，就关闭所有活动相关的任务

![image](https://user-images.githubusercontent.com/37934724/180631902-d5ad7e35-d860-40f0-97dc-fbfcfb495923.png)

**Comment by jingfengsama** [comment]
> 可以检查 `活动筹备中` 这几个字，如果出现，就关闭所有活动相关的任务
> 
> ![image](https://user-images.githubusercontent.com/37934724/180631902-d5ad7e35-d860-40f0-97dc-fbfcfb495923.png)
s是的我的想法就是这个。

**Comment by bookbug666** [comment]
> 可以检查 `活动筹备中` 这几个字，如果出现，就关闭所有活动相关的任务
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/37934724/180631902-d5ad7e35-d860-40f0-97dc-fbfcfb495923.png)
> 
> 

是說如果要實現這個，應該要各服務器截圖一個asset還是可以使用OCR呢

**Comment by LmeSzinc** [comment]
> 是說如果要實現這個，應該要各服務器截圖一個asset還是可以使用OCR呢

固定的内容都用assets

**Comment by bookbug666** [comment]
本來想趁彩船活動結束來做......結果無縫接輕量化復刻，那只好問些事前作業了
##
![image](https://user-images.githubusercontent.com/29662367/210742479-8d18bb3b-a6ec-4cf5-9037-a04f4b208917.png)

1. 現在ui切換不一定會經過上面這個畫面，如主線task就會從
![image](https://user-images.githubusercontent.com/29662367/210742725-be066a0f-602f-4a9d-bc04-ddde62ef0b57.png)
需要修改原本的ui_goto_event嗎?如果直接拆成campaign_menu再goto_event有間隔夠alas偵測嗎
2. 假設我偵測畫面上出現no_event就stop_task並disable_task，這個判定放在哪裡比較合適
3. 這個功能會取代原本的日期觸發，還是共存?

![image](https://user-images.githubusercontent.com/29662367/210744489-397f7c61-12b8-4182-b33c-a09821e8ea9d.png)
~~反正7天後才能做assets，不急~~

**Comment by LmeSzinc** [comment]
@bookbug666 
1. 可以分开两步
2. 放ui_goto_event里
3. 共存，没活动禁用任务不需要有开关
