### ISSUE TITLE
[asking a question]请问默认的科研过滤器的参数是怎么样的

### ISSUE THREAD

**Issue by jingfengsama** [LmeSzinc/AzurLaneAutoScript#1397]
自己编写了一个适合自己的自定义科研过滤器（4期彩图为主），现在5期出了，加上4期彩图即将完成，想改变为天雷策列再补充最后的彩图。想参考一下预优化科研过滤器的参数，请问如何获得呢

**Comment by bookbug666** [comment]
.\module\research\preset.py
裡面有

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/module/research/preset.py

See also #872

**Comment by jingfengsama** [comment]
> .\module\research\preset.py 裡面有

感谢

**Comment by jingfengsama** [comment]
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/module/research/preset.py
> 
> See also #872

感谢
