### ISSUE TITLE
能否让编队之间互换刷图

### ISSUE THREAD

**Issue by semz666** [LmeSzinc/AzurLaneAutoScript#1405]
### 你的功能请求是否与问题有关？

用两支编队交替刷图可以最大效率的利用后宅回复心情来保持高效的经验获取，因此想问一下能否实现。

**Comment by 18870** [comment]
#576 #614 

出击中有主线图-123，你可以配置同一张图使用不同的队伍

**Comment by semz666** [comment]
> #576 #614
> 
> 出击中有主线图-123，你可以配置同一张图使用不同的队伍

哦，谢谢回复，主线图确实可以通过这种方式来进行切换，但如果是档案作战只有一个的情况下，就做不到自动切换，只能手动进行切换了
