### ISSUE TITLE
推迟继续选择科研到服务器刷新时间

### ISSUE THREAD

**Issue by jichuan-zhang** [LmeSzinc/AzurLaneAutoScript#1406]
### 你的功能请求是否与问题有关？

举个例子，现在科研队列里是4个切魔方，现在可选的科研项目是五个12小时，举例服务器第二天刷新还有3小时。

这个时候合理的做法显然是等到第二天点刷新，而不是选个12小时加进科研队列。

### 解决方案

添加一个可选功能：如果已有的项目总时间可以到达第二天，然后科研选项是五个优先级在reset后面的，则停止添加项目到科研队列直到刷新。

如果能再加一个可以自定义允许科研空闲的时间就更好了。没算过，但俺寻思空闲一个小时然后开切也比直接整个八小时白嫖效率要高吧。

### 其他内容

背景：一个不注意科研队列里多了俩八小时，人麻了

**Comment by bookbug666** [comment]
你是不是誤會了Alas如何運作科研，在沒有科研隊列以前的Alas只要使用自定義的過濾器組合就不會加入12小時科研
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn

Wiki裡有對科研過濾器如何填寫的說明，你會被添加12小時科研應該是因為你reset後面還有加入shortest，因為我用Alas很久也沒見過我截圖紀錄裡有出現過Alas幫我選擇我期待以外的科研，真的出現完全沒有我要的情況Alas也幫我推遲到了伺服器換日

**Comment by jichuan-zhang** [comment]
哦哦是shortest的问题是吧，我去调调过滤器，谢谢
