### ISSUE TITLE
为什么我点开alas.exe后会显示FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by 1594235487** [LmeSzinc/AzurLaneAutoScript#1407]
为什么我点开alas.exe后会显示FileNotFoundError: [WinError 2] 系统找不到指定的文件。
![图片](https://user-images.githubusercontent.com/106726922/180608428-0e94019d-9376-496b-88e6-5ea5ede18aa8.png)
![图片](https://user-images.githubusercontent.com/106726922/180608452-89329bee-1e16-4de4-91f3-701bd9e090bc.png)
![图片](https://user-images.githubusercontent.com/106726922/180608458-8b4f10b2-1a70-481b-ae95-d0685d95732d.png)

**Comment by 1594235487** [comment]
我的配置文件都是按照安装教程来的

**Comment by SaiCateDoan** [comment]
怎么会有人电脑里没有taskkill的啊？
你需要手动修复电脑中不存在taskkill.exe的问题

**Comment by lzy0702** [comment]
请清除引起taskkill.exe被删除的原因（一般是某些拙劣的病毒）
然后以管理员权限运行
`sfc /scannow`
以修复缺失的系统文件

**Comment by SaiCateDoan** [comment]
在数个月后，我们终于发现了这个问题的本质
请检查你的环境变量中的comspec，它的值通常应该是C:\WINDOWS\system32\cmd.exe，它会被作为alas调用命令行的基础
如果它的值被某些软件篡改成一个不合法的shell，则会出现上面的问题（已知mysql可能导致这个问题）
