### ISSUE TITLE
Alas能否通过命令行不显示图形界面直接控制吗？

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#1414]
### 你的功能请求是否与问题有关？

我目前是在Windows的计划任务程序里设置了启动alas与模拟器的计划任务，因此想了解一下，alas可以在updater运行完成后或是在完全未启动时，用命令行（powershell或CMD）控制它依照config内的json文件执行任务吗？

**Comment by hgjazhgj** [comment]
直接运行alas.py就相当于你在webui中配置名为`alas`的标签中按下了启动按钮  

alas.py中的AzurLaneAutoScript类是alas的本体,其构造方法接受一个可选参数以指定配置文件名  
以下内容可以直接丢进计划任务里,假设你要使用的配置文件名为`qwerty`  
```
操作: 启动程序
程序或脚本: cmd
添加参数: /C "echo __import__('alas').AzurLaneAutoScript('qwerty').loop() | python"
起始位置: 你的alas.py所在目录
```

**Comment by HS7097** [comment]
嗯...我不太明白问题出在哪了，我是这么设置的，如果删掉起始于后面的alas.py，他不会报错 。
如果添加上去，那日志会报两条错误，分别为：任务计划程序无法为用户启动“\Emulator_Alas_run”任务。其他数据: 错误值: 2147942667。；务计划程序无法启动任务“\Emulator_Alas_run”的实例“{e448afb5-bc61-4bc9-8fee-b9d11e90b337}”中的操作“%windir%\system32\cmd.exe”。其他数据: 错误值: 2147942667。
但是无论他会不会报错，设置完成后手动执行没有任何反应。
下面是我导出的计划任务设置，修改成TXT格式
[Emulator_Alas_run.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9186223/Emulator_Alas_run.txt)

**Comment by HS7097** [comment]
> 直接运行alas.py就相当于你在webui中配置名为`alas`的标签中按下了启动按钮
> 
> alas.py中的AzurLaneAutoScript类是alas的本体,其构造方法接受一个可选参数以指定配置文件名 以下内容可以直接丢进计划任务里,假设你要使用的配置文件名为`qwerty.json`
> 
> ```
> 操作: 启动程序
> 程序或脚本: cmd
> 添加参数: /C "echo __import__('alas').AzurLaneAutoScript('qwerty').loop() | python"
> 起始于: 你的alas.py所在目录
> ```

**Comment by HS7097** [comment]
> 直接运行alas.py就相当于你在webui中配置名为`alas`的标签中按下了启动按钮
> 
> alas.py中的AzurLaneAutoScript类是alas的本体,其构造方法接受一个可选参数以指定配置文件名 以下内容可以直接丢进计划任务里,假设你要使用的配置文件名为`qwerty.json`
> 
> ```
> 操作: 启动程序
> 程序或脚本: cmd
> 添加参数: /C "echo __import__('alas').AzurLaneAutoScript('qwerty').loop() | python"
> 起始于: 你的alas.py所在目录
> ```

嗯...我不太明白问题出在哪了，我是这么设置的，如果删掉起始于后面的alas.py，他不会报错 。
如果添加上去，那日志会报两条错误，分别为：任务计划程序无法为用户启动“\Emulator_Alas_run”任务。其他数据: 错误值: 2147942667。；务计划程序无法启动任务“\Emulator_Alas_run”的实例“{e448afb5-bc61-4bc9-8fee-b9d11e90b337}”中的操作“%windir%\system32\cmd.exe”。其他数据: 错误值: 2147942667。
但是无论他会不会报错，设置完成后手动执行没有任何反应。
下面是我导出的计划任务设置，修改成TXT格式
[Emulator_Alas_run.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9186236/Emulator_Alas_run.txt)

**Comment by 18870** [comment]
[778cd44](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/778cd44b3d4260578f473bc7cd9ba587c024e19e) 添加了命令行参数 `--run`
使用 `python gui.py --run alas alas2 alas3 ...` 可以自动启动对应的配置文件名

**Comment by bookbug666** [comment]
如果你是要完全交給Alas控制中途不進行任何停止及修改設定
只要在config資料夾創建一個名為reloadalas的檔案，內容填寫為你的設定json名
每次啟動時讓bat生成或是複製然後執行alas.py(如果你不需要gui)或是gui.py(網頁gui)

或是你反悔了想要DesktopApp就讓bat執行alas.exe

**Comment by HS7097** [comment]
> 如果你是要完全交給Alas控制中途不進行任何停止及修改設定 只要在config資料夾創建一個名為reloadalas的檔案，內容填寫為你的設定json名 每次啟動時讓bat生成或是複製然後執行alas.py(如果你不需要gui)或是gui.py(網頁gui)
> 
> 或是你反悔了想要DesktopApp就讓bat執行alas.exe

**Comment by HS7097** [comment]
> /C "echo __import__('alas').AzurLaneAutoScript('qwerty').loop() | python"

嗯...再请教一下，这个东西该怎么做才能让它自动运行呀，我得到console.bat手动输入才有效果

**Comment by bookbug666** [comment]
@HS7097 我給你參考我的吧
```
@rem
@echo off
echo alas > W:\AzurLaneAutoScript\config\reloadalas
start /d "C:\Program Files\BlueStacks_nxt" HD-Player.exe --instance Nougat64

set "_root=%~dp0"
set "_root=%_root:~0,-1%"
cd "%_root%"

set "_pyBin=%_root%\toolkit"
set "_GitBin=%_root%\toolkit\Git\mingw64\bin"
set "_adbBin=%_root%\toolkit\Lib\site-packages\adbutils\binaries"
set "PATH=%_root%\toolkit\alias;%_root%\toolkit\command;%_pyBin%;%_pyBin%\Scripts;%_GitBin%;%_adbBin%;%PATH%"

timeout /t 8 >nul
start /d "W:\AzurLaneAutoScript" Alas.exe
```
其中目錄要自己更動，由於你不需要GUI(假設你也不需要把Bluestacks於bat中啟動)所以可以更簡單，變成
```
@rem
@echo off
echo alas > W:\AzurLaneAutoScript\config\reloadalas

set "_root=%~dp0"
set "_root=%_root:~0,-1%"
cd "%_root%"

set "_pyBin=%_root%\toolkit"
set "_GitBin=%_root%\toolkit\Git\mingw64\bin"
set "_adbBin=%_root%\toolkit\Lib\site-packages\adbutils\binaries"
set "PATH=%_root%\toolkit\alias;%_root%\toolkit\command;%_pyBin%;%_pyBin%\Scripts;%_GitBin%;%_adbBin%;%PATH%"

python alas.py
```

**Comment by bookbug666** [comment]
或是你有自己的python就可以省略set PATH那些，直接指定到目錄的alas.py

**Comment by HS7097** [comment]
> 或是你有自己的python就可以省略set PATH那些，直接指定到目錄的alas.py 此處是使用Alas安裝包帶的Python

非常感谢，已经配置好了
