### ISSUE TITLE
今日台服開服後發現科研會卡住

### ISSUE THREAD

**Issue by tenchi6707** [LmeSzinc/AzurLaneAutoScript#1432]
### 你的功能请求是否与问题有关？

目前自動科研是強制開啟的，能否設個開關來選擇是否開啟自動科研
因今日台服開服後發現科研會卡住，謝謝

────────────────────────────── RECEIVE 6TH RESEARCH ───────────────────────────────
INFO     18:10:11.755 │ RECEIVE 6TH RESEARCH                                       
INFO     18:10:11.760 │ No research has finished                                   
INFO     18:10:11.768 │ Research status: ['detail', 'detail', 'waiting', 'detail', 
         'detail']                                                                 
INFO     18:10:11.774 │ Research queue: ['empty', 'waiting', 'waiting', 'waiting', 
         'waiting']                                                                
INFO     18:10:11.777 │ [Research queue slot] 1                                    
INFO     18:10:11.781 │ <<< RESEARCH PROJECT START >>>                             
INFO     18:10:11.784 │ Research project: 2                                        
INFO     18:10:11.787 │ Research project: 2                                        
INFO     18:10:11.789 │ Project offset: 0, project 2 is at 2                       
INFO     18:10:11.793 │ Click ( 569,  222) @ ENTRANCE_3                            
INFO     18:10:14.900 │ <<< RESEARCH QUEUE ADD >>>                                 
INFO     18:10:14.908 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:14.921 │ Click ( 625,  586) @ RESEARCH_QUEUE_ADD                    
INFO     18:10:15.466 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:15.906 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:16.351 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:16.774 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:17.230 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:17.638 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:18.038 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:18.464 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:18.897 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:19.317 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:19.740 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:20.164 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:20.169 │ Click ( 566,  594) @ RESEARCH_QUEUE_ADD                    
INFO     18:10:20.652 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:21.091 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:21.624 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:22.033 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:22.479 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:22.901 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:23.339 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:23.797 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:24.212 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:24.709 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:25.132 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:25.641 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:25.645 │ Click ( 600,  592) @ RESEARCH_QUEUE_ADD                    
INFO     18:10:26.167 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:26.592 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:27.006 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:27.444 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:27.869 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:28.284 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']                                                     
INFO     18:10:28.681 │ Research status: ['unknown', 'unknown', 'unknown',         
         'unknown', 'unknown']

**Comment by LmeSzinc** [comment]
#1416 

有问题请上报问题
