### ISSUE TITLE
alas一直显示更新中，不能取消，使得不能启动调度器

### ISSUE THREAD

**Issue by yamabukiyui** [LmeSzinc/AzurLaneAutoScript#1433]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

见标题。取消更新为不可点击状态

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/88662338/181504576-89bb6fe7-e6f7-4dfe-8220-5e3798308f80.png)

**Comment by 18870** [comment]
发一下log文件夹下的 `2022-07-28_gui.txt`
