### ISSUE TITLE
针对 Hyper-V 电脑的解决方案：可选使用逍遥模拟器 8，可将 Readme 更新。

### ISSUE THREAD

**Issue by soloopooo** [LmeSzinc/AzurLaneAutoScript#1444]
### 你的功能请求是否与问题有关？

在 `Hyper-V` 环境下，目前支持运行的模拟器和虚机有 WSA，MumuX，逍遥模拟器 8（Android7.1以上），蓝叠 4-HV 和 5-HV 。经过本人测试，逍遥模拟器 8 现在对于 `Windows 11 Insider Preview` 的支持最佳。MumuX 会导致 Windows 出现 BSOD (2022/07/28反馈，客服说明该问题已知，正在修复)。WSA 的性能与稳定性稍显逊色，且需要将游戏持续在后台运行，操控略显麻烦。蓝叠 4-HyperV 和蓝叠 5-HyperV 版性能较弱，且蓝叠的 VDisk 对于机械硬盘来说性能极差。

并且，Readme 中的

> 在逍遥模拟器下使用需要将控制方式设置为 uiautomator2

经过我多次测试，现在已经不正确了。

现在，针对逍遥模拟器，最快的点击与截图方案分别为 minitouch (约0.5s/t) 和ADB (约0.8-1.8s/c)。

`uiautomator2` 的性能远不及 `minitouch`。

截图绝对不可以选择 `adb_nc`，速度慢到 13-14s/c。

### 解决方案

作者可以选择直接关闭此 Issue。此 Issue 仅为使用报告与优化建议。

### 其他内容

时效性：此 Issue 提出时间为 2022年7月29日。此时的 Windows 11 Insider Preview 版本为 25163。

逍遥模拟器在运行碧蓝航线时，可能会产生卡顿，尤其是针对 L2D 资源。针对这种现象，打开设置中的 ASTC 缓存即可解决。

正常运行的运行截图：
![image](https://user-images.githubusercontent.com/36123081/181669603-333e023f-1762-42f5-8b73-3b7405681137.png)

**Comment by 18870** [comment]
逍遥模拟器不用minitouch是因为它不能缩放。你可以用minitouch运行一次后宅试试能不能正确缩放

**Comment by freesrz93** [comment]
现在后宅不用缩放了吧

**Comment by LmeSzinc** [comment]
我这边使用逍遥模拟器非 hyperv 版的情况是，如果逍遥模拟器运行时间过长，minitouch会失效，具体的表现是连接有响应但是实际没有点击。alas重新连接minitouch，在通过 `http://127.0.0.1:7912/remote` 访问atx也是只有图片，点击不生效，需要 `python -m uiautomator2 init` 重新安装才能恢复。所以我在 readme 里推荐选 uiautomator2

对于正常的游戏玩家，我是非常建议关闭wsa和关闭hyper V的，绝大多数用户不会需要用到的，这样你就可以用回普通的模拟器了，现在的模拟器比wsa成熟太多。

**Comment by soloopooo** [comment]
@LmeSzinc 目前微软针对于默认的 Windows11 安装用户都是开启内存完整性验证的。很难保证以后微软会不会把 Based on Hyper-V 的功能默认在新电脑上开启，谁也不好说，毕竟微软做出的傻事大家都知道。本 issue 可作为相关问题参考供后人查阅使用。

@18870 我暂时无法测试，现在后宅进入默认为全部画面显示，Alas也没有尝试进行缩放行为。

**Comment by soloopooo** [comment]
2022/07/31测试补充：逍遥模拟器 8 HV 版，性能最优为如下设置， Benchmark 如图。

如果运行在 OpenGL 模式下，且未开启显存优化（未知该选项是否会影响），ADB_nc 截图速度会慢到 13s 一张。

![image](https://user-images.githubusercontent.com/36123081/182011260-4ce2c8c6-040a-4c7c-9118-dddc0a8d964b.png)

![image](https://user-images.githubusercontent.com/36123081/182011309-f2e0b97c-cb5e-4397-abbf-5ff78afcb9b9.png)
