### ISSUE TITLE
"雄鹰的叙事诗"活动图B1找不到

### ISSUE THREAD

**Issue by futureprecd** [LmeSzinc/AzurLaneAutoScript#1450]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

活动图ABCD已经全部手动清理完，3星都达成了，想低耗队刷B1，结果出现如下错误提示：
WARNING  16:20:00.859 │ Map file not found: campaign.event_20220728_cn.b1          
WARNING  16:20:00.863 │ Existing files: ['a1', 'a2', 'a3', 'c1', 'c2', 'c3']       
CRITICAL 16:20:00.866 │ Possible reason #1: This event (event_20220728_cn) does not
         have b1                                                                   
CRITICAL 16:20:00.869 │ Possible reason #2: You are using an old Alas, please check
         for update, or make map files yourself using dev_tools/map_extractor.py   
CRITICAL 16:20:00.872 │ Request human takeover    
显示是没有B以及D的图的，感觉可能是新活动在ALAS上出现了bug？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
WARNING  16:20:00.859 │ Map file not found: campaign.event_20220728_cn.b1          
WARNING  16:20:00.863 │ Existing files: ['a1', 'a2', 'a3', 'c1', 'c2', 'c3']       
CRITICAL 16:20:00.866 │ Possible reason #1: This event (event_20220728_cn) does not
         have b1                                                                   
CRITICAL 16:20:00.869 │ Possible reason #2: You are using an old Alas, please check
         for update, or make map files yourself using dev_tools/map_extractor.py   
CRITICAL 16:20:00.872 │ Request human takeover
```

### 截图

这是我的活动图设置
![image](https://user-images.githubusercontent.com/38852593/181717564-a3695644-ac78-40a3-a76d-db36a8ca79c0.png)
![image](https://user-images.githubusercontent.com/38852593/181717624-3d1db809-aca8-4abb-b5db-08665e829148.png)
![image](https://user-images.githubusercontent.com/38852593/181717675-4c9098ef-c909-4aef-b098-8ebaf5c431d2.png)
![image](https://user-images.githubusercontent.com/38852593/181717713-48660aba-1969-4949-9e8d-186a868024df.png)

**Comment by bookbug666** [comment]
#1445 #1449 
Search before asking
