### ISSUE TITLE
CN服大世界OCR辨認報錯

### ISSUE THREAD

**Issue by leo706966** [LmeSzinc/AzurLaneAutoScript#1465]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

短貓相接時UnicodeEncodeError會直接中斷ALAS的運行

### 如何复现

陆间海A-安全海域
直布罗特

目前遇到以上兩個海域 會出現UnicodeEncodeError直接中斷運行

### 预期行为

能否處理這個意外讓ALAS跳過短貓相接而正常運行

### 截图

![2022-07-31_14-22-54-555651](https://user-images.githubusercontent.com/15162112/182015537-02b7b659-5d0c-4c74-85dd-21a63258d9aa.png)
![2022-07-31_14-25-03-695516](https://user-images.githubusercontent.com/15162112/182015573-6e8d33fd-7e87-466c-8808-0077395cd5e8.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9228251/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9228253/log.txt)

**Comment by 18870** [comment]
重启更新一下依赖

#1464 #1463

**Comment by leo706966** [comment]
好的
