### ISSUE TITLE
Alas 自动拖动游戏内滚动条出现错误

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#1470]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

目前我在两处遇到了这个bug，模拟器使用的是蓝叠4，手动操作时没感觉到卡顿 
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9230134/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9230135/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9230137/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9230138/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9230141/log.txt)
/9230140/log.txt)
![2022-07-31_09-20-57-923208](https://user-images.githubusercontent.com/103177863/182053866-2d7b18e3-e9f0-45f8-b2e3-689dde20eb89.png)

![2022-08-01_05-56-35-755631](https://user-images.githubusercontent.com/103177863/182053861-e1480e9d-9be6-464e-8fde-8ea7e403686c.png)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
检查一下：
- 模拟器设置里有没有设置为60帧
- 游戏设置里有没有设置60帧
- 实际游戏运行有没有到60帧

碧蓝航线它很魔法，它的实际滑动距离和帧数挂钩，如果帧数不够的话，很容易出现滑动滑不动的情况。
