### ISSUE TITLE
能否添加关机的任务需求

### ISSUE THREAD

**Issue by zhangyg0123456** [LmeSzinc/AzurLaneAutoScript#1474]
### 你的功能请求是否与问题有关？

我平时不需要7*24小时挂机，每天只用上线两次，只想在上班前用电脑打完每日任务就自动关机。

### 解决方案

添加关机的队列需求

**Comment by bookbug666** [comment]
雖然我想開發組應該是做得到，但如果你要定期關機不是用電腦的工作排程就好了嗎
設定好時間直接加一個shutdown.exe -s -t 0就能做到了不是嗎

**Comment by bookbug666** [comment]
而且你似乎並沒有描述清楚你希望的解決方案，你是希望設定若清空任務+到達特定時間=關機嗎
你的"只用上線兩次"讓人不知道你的需求到底是多少次

**Comment by zhangyg0123456** [comment]
> 而且你似乎並沒有描述清楚你希望的解決方案，你是希望設定若清空任務+到達特定時間=關機嗎 你的"只用上線兩次"讓人不知道你的需求到底是多少次

抱歉，是我没说清楚。
我的想法是在"队列中"的最后添加一个关机的任务。
实际的效果就是把设定好的每日任务做完后(队列中无任务)关机，如果进行每日任务的时间过长，有些定时任务时间到了要插队的话，也是插在关机任务的前面。（相当于关机任务置底）
关机任务可以设定一个定时选项，来添加进定时任务。
关机任务只能手动添加进"队列中"。
关机任务成功运行一次后，若要再次使用，仍需手动添加进"队列中"。
若进行关机任务，添加一个60s的倒计时，并弹窗提醒。弹窗中要有可以取消关机指令的按钮。


前面提到的"上线两次"是我的个人游戏习惯，与提出的需求无关。

**Comment by bookbug666** [comment]
照你的運作邏輯，使用任務添加的方式的話，那麼他可能會出現以下情況
設定午夜12:30關機>時間到12:28觸發大世界拓荒+餘燼信標跟剩餘一大堆任務>超過12:30還沒有關機

那麼你是希望他一直推遲直到清空任務嗎?但是如果你12:40完成清空任務而12:41有一個委託就要完成了，你要讓Alas等到接完委託才關機嗎?還是因為"觸發條件清空+時間"所以不管委託執行關機呢?

Alas設計用意是不停機的持續執行，如果你真要讓他關機我更傾向於從系統端下手
![image](https://user-images.githubusercontent.com/29662367/182433858-c570fc58-92f7-463d-81b0-5b3065ec1f74.png)
![image](https://user-images.githubusercontent.com/29662367/182434016-411b7ce2-93b3-4333-bbc0-affef5a1bbc7.png)
![image](https://user-images.githubusercontent.com/29662367/182434196-17abecde-c298-4edd-9a99-431a583756de.png)
![image](https://user-images.githubusercontent.com/29662367/182434319-dba5d18d-b40b-467e-891d-3465b65d1754.png)
![image](https://user-images.githubusercontent.com/29662367/182434490-98607d8e-e810-4830-bf4b-27babc92aa8a.png)

因為Alas並沒有鎖定螢幕開啟所以這是可行的，另外如果你要取消關機就打開cmd輸入shutdown /a然後Enter就行
Alas社群中也少有人提到關於定期關機的事情，因為你隨時都能停止關閉去睡覺，開機了點開始一樣能把你睡前沒做的事情做了，~~除非伺服器換日~~

在你的要求中有提到關機的倒計時，也許你沒有注意到這已經與遊戲運作無關了，它完全不是非得由Python(我們的Alas)執行的
相反它是一個WinOS系統端的行為，因此從系統端來做執行規劃顯然更直接簡單

真要從Alas那邊新增 ，應該是可以做到的(加一行os.system"shutdown -s -t 0")，但就是繞一大圈讓Python執行系統指令，我不確定這是不是就是你要的

**Comment by bookbug666** [comment]
至於shutdown是WinOS裏的關機指令，百度下應該就能知道怎麼用了

**Comment by zhangyg0123456** [comment]
我的本意确实是当定时关机任务达到时间但任务序列为空，关机任务就一直推遲到清空任務，当"觸發條件清空+時間已过"然后不管委託直接執行關機。
在开新图的时候要开荒的话，一天所花的时间就会与平时不一样，那么关机的定时就要手动调整并且定时时间难以预估。

按照您的推荐，我确实可以估算任务序列清空一次的使用时间，然后在系统端任务计划设定更长一些的定时时间去关机，若要打新图的话，倒是可以定时更长的时间进行关机，并且没想到本软件可以隨時停止關閉去睡覺，開機了點開始一樣能把之前沒做的事情做了，这基本上是解决了我的需求。
