### ISSUE TITLE
大艦隊作戰派遣

### ISSUE THREAD

**Issue by mm770912** [LmeSzinc/AzurLaneAutoScript#1476]
### 你的功能请求是否与问题有关？

關於作戰自動派遣的部分
偵測時間可否縮短
因爲好像沒有派遣隊伍的話拿不到獎勵的樣子

### 解决方案

偵測時間可否縮短

**Comment by LmeSzinc** [comment]
不需要。大舰队派遣在每天服务器时间 6/12/18/21 时刷新，大舰队作战在每天 0 时刷新，Alas 的大舰队任务在每天的 0/6/12/18/21 时运行，是刚刚好的，增加运行不会多派遣一次
