### ISSUE TITLE
请求修改AidLux目录的requirements.txt的Numpy版本

### ISSUE THREAD

**Issue by VirtualTowel** [LmeSzinc/AzurLaneAutoScript#1477]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我按照群里的教程进行了AidLux上Alas的安装，安装完成后，尝试启动：
![image](https://user-images.githubusercontent.com/42640608/182374175-1272c01f-f9e0-4c6a-9095-3ec27c4c01f6.png)

gui.py显示START后直接闪退，尝试启动alas.py：
![image](https://user-images.githubusercontent.com/42640608/182374330-fc111787-339e-42dc-b4d5-7b0618bc74fd.png)
显示Illegal instruction。

经尝试，发现是numpy版本问题。./deploy/AidLux/0.92/requirements.txt文件内的numpy并没有指定版本，而最新版的numpy似乎已经不支持alas的代码了。我将numpy版本更换为主目录requirements.txt内指定的1.16.6后，问题得以解决。

**Comment by LmeSzinc** [comment]
当时测试的结果是，如果在 requirements.txt 写 numpy==1.16.6 的话，Pip 会有依赖冲突，所以我把版本要求去掉了

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/aa348b855a14e86f2cd0c39beaf43c14d57a774e/deploy/AidLux/requirements_generator.py#L56-L59

真机上安装 Alas 的这个教程因为 vmos 长时间运行会闪退卡死，目前还没有办法解决，已经被放弃了，现在是在云手机上装 Alas 了

**Comment by VirtualTowel** [comment]
> 当时测试的结果是，如果在 requirements.txt 写 numpy==1.16.6 的话，Pip 会有依赖冲突，所以我把版本要求去掉了
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/aa348b855a14e86f2cd0c39beaf43c14d57a774e/deploy/AidLux/requirements_generator.py#L56-L59
> 
> 真机上安装 Alas 的这个教程因为 vmos 长时间运行会闪退卡死，目前还没有办法解决，已经被放弃了，现在是在云手机上装 Alas 了

原来如此。可以问一下vmos闪退卡死后，alas的错误报告是什么吗？
我以前一直是用云服务器+本地vmos，这几天运行比较长时间了以后，都会遇到“由于目标计算机积极拒绝，无法连接。 (10061)”，我一直以为是家里的网络问题，难道这个问题是vmos卡退了嘛

> 当时测试的结果是，如果在 requirements.txt 写 numpy==1.16.6 的话，Pip 会有依赖冲突，所以我把版本要求去掉了
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/aa348b855a14e86f2cd0c39beaf43c14d57a774e/deploy/AidLux/requirements_generator.py#L56-L59
> 
> 真机上安装 Alas 的这个教程因为 vmos 长时间运行会闪退卡死，目前还没有办法解决，已经被放弃了，现在是在云手机上装 Alas 了

我原来是云服务器Alas+ 本地frp+vmos，但是Alas似乎对网络波动的耐受度较低，这几天都遇到了

> 当时测试的结果是，如果在 requirements.txt 写 numpy==1.16.6 的话，Pip 会有依赖冲突，所以我把版本要求去掉了
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/aa348b855a14e86f2cd0c39beaf43c14d57a774e/deploy/AidLux/requirements_generator.py#L56-L59
> 
> 真机上安装 Alas 的这个教程因为 vmos 长时间运行会闪退卡死，目前还没有办法解决，已经被放弃了，现在是在云手机上装 Alas 了

我本来是云服务器+本地vmos的组合，遇到的更多的不是vmos卡死而是网络波动造成的错误，这几天凌晨都报了“由于目标计算机积极拒绝，无法连接。 (10061)”这个错误，而游戏还在结算界面，说明vmos并没有闪退。如果可以的话我是想继续用云服务器组合的，不知道lme有没有意向优化一下Alas的网络波动耐受度（）

**Comment by LmeSzinc** [comment]
> 遇到的更多的不是vmos卡死而是网络波动造成的错误，这几天凌晨都报了“由于目标计算机积极拒绝，无法连接。 (10061)”这个错误

这个其实就是卡了，vmos到adb服务的连接断开了，模拟器挂了或者连接一个错误的地址也可以获得相同的错误。我是建议去买 chinac.com 的云手机，买38一个月的，它家云手机提供公网adb连接，把地址填进alas里就可以了，运行体验会比你现在好很多截图能进0.3s，你现在本地手机没有公网ip，还要做内网穿透截图速度肯定很慢。

未来alas会直接运行在云手机上，获取本地的截图，截图也不会受网络影响了

**Comment by VirtualTowel** [comment]
原来是这样，感谢解答~

**Comment by VirtualTowel** [comment]
增加一个解决方案：在环境变量内添加export OPENBLAS_CORETYPE=ARMV8

**Comment by VirtualTowel** [comment]
还有一个在调用“工具”内部分功能的时候遇到的错误：
`OSError: /usr/lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block`
可以通过在环境变量内添加以下内容解决：
`export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1:$LD_PRELOAD`
