### ISSUE TITLE
请问大世界通用设置里面，在地图里面遇到商人时，能否在商店过滤器加入一个购买效能样本的选项

### ISSUE THREAD

**Issue by futureprecd** [LmeSzinc/AzurLaneAutoScript#1480]
### 你的功能请求是否与问题有关？

如题，昨晚用Alas挂机大世界每月开荒，开荒完毕后发现攻击适应性只有170点，然后去打月度boss着实有点难，三个属性的值分别是170,190,190，我记得之前每月手动开荒完毕后，在商人那里购买的各种效能样本加上压制地图后获得的三属性加成，基本上三个的平均值能到200，但是目前自动开荒的结果着实有点低(这还是在每个月月初兑换商店里面的那些总共60加成的效能样本已经全部买了并且使用了之后的结果)，感觉会不会是由于地图里碰到商人后没有购买效能样本的缘故？因为我看见大世界通用设置里面的商店过滤器好像只有行动力和紫币选项

### 其他内容

![image](https://user-images.githubusercontent.com/38852593/182553802-32b7e3c1-4a18-4348-9988-849202b32474.png)
rutio如题， 我不太清楚代码里面是不是设置了效能样本相关的变量代码，所以不知道这里怎样把效能样本加上，关键字也不太了解

**Comment by LmeSzinc** [comment]
可以填写的物品在 `assets/shop/os` 文件夹里，不过明石商店的过滤器一般不用改，再等几天适应性就够打月度boss了
