### ISSUE TITLE
GUI界面部分显示问题

### ISSUE THREAD

**Issue by KylezXing** [LmeSzinc/AzurLaneAutoScript#1482]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

1、每一个下拉选项框、选择框、填空框下都会显示格式错误
2、选项框会把所有可选选项在下面列出，导致整个界面十分冗长。（这个问题是在最近一次更新后出现的，更新之前只有问题1存在）
上述问题都没有影响正常使用，但使用体验有点糟糕。在其他电脑上安装是正常的，已经尝试过重装没能解决，希望大佬支个招，非常感谢！

### 截图

主界面
![image](https://user-images.githubusercontent.com/110474093/182838957-5b40985b-42de-4a52-9870-ded2da087a56.png)
以出击界面为例
![image](https://user-images.githubusercontent.com/110474093/182839140-039cd133-3548-4bbf-87a4-ca21a30a3a0e.png)
![image](https://user-images.githubusercontent.com/110474093/182839197-0f5374fd-28cf-43d2-8ca1-6fc21a102f30.png)

**Comment by KylezXing** [comment]
控制台和网络图片如下
![image](https://user-images.githubusercontent.com/110474093/182839887-aa262de6-3131-454f-868c-57763f3cde54.png)
![image](https://user-images.githubusercontent.com/110474093/182839991-40bf636f-9719-4215-b871-fa93acd31a3e.png)

**Comment by 18870** [comment]
1. 勾上Disable Cache 并刷新
2. 如果不能解决，在 deploy.yaml 中将 CDN 设为 True

**Comment by KylezXing** [comment]
> 1. 勾上Disable Cache 并刷新
> 2. 如果不能解决，在 deploy.yaml 中将 CDN 设为 True

问题已解决，非常感谢
