### ISSUE TITLE
自動拆箱子

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1502]
### 你的功能请求是否与问题有关？

碧航至今沒有科技箱販賣的功能，而至今仍有人為物資所苦，而拆箱子這件事能增加物資獲取但極度精污

### 解决方案

希望能增加自動拆藍白箱的功能，甚至有保留特定藍裝(有些裝備是特定強裝的研發前置)或是紫裝金裝(三式彈、金吊臂)

如果透過掃描星數可能會遇到唯一裝備的問題，不知道怎麼解決，希望能有人提出不錯的方案

**Comment by SaiCateDoan** [comment]
你要是想做这个，可以顺便把E系科研支持做了，加油

**Comment by bookbug666** [comment]
> 你要是想做这个，可以顺便把E系科研支持做了，加油

我是很想自己加上去，奈何我是邊學Python邊熟悉Alas代碼邊寫/修改功能的，UI捲動/切換還有處理例外什麼的還要參考一下別的module
只是看到群裡有人在建議區提到他有5萬個箱子多到想讓Alas自動拆箱就發出來了，目前的我還沒能力獨立編寫新功能

**Comment by LmeSzinc** [comment]
#183 曾经有人尝试过，但是核心问题没有解决，就是如何区分出需要被拆解的装备。当时是两个方法，这两个都不理想。
- 识别NEW，但如果你已经有了这个装备，那么会继续堆叠，不会有new。
- 按强化等级倒序，但不能区分出有用的+0装备

如果是只开白箱子的话，那把白色装备全部分解，我觉得是没有问题的，但是如果要开蓝色和紫色箱子的话，这个就必须要做区分的。
