### ISSUE TITLE
大舰队购买舰队补给的识别问题

### ISSUE THREAD

**Issue by XokoukioX** [LmeSzinc/AzurLaneAutoScript#1505]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当舰队物资不够买补给时,脚本会重复尝试购买,最后重启APP

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

INFO     11:01:58.161 │ GUILD LOGISTICS     
INFO     11:01:58.164 │ GUILD_SIDE_NAVBAR   
         set to right=3 bottom=3            
INFO     11:01:58.169 │ Nav item active: 0  
         from range (0, 5)                  
INFO     11:01:58.173 │ Click (  52,  451) @
         GUILD_SIDE_NAVBAR_0_3              
INFO     11:01:59.055 │ Nav item active: 3  
         from range (0, 5)                  
INFO     11:01:59.616 │ <<< GUILD LOGISTICS 
         >>>                                
INFO     11:01:59.619 │ [Guild              
         master/official] False             
INFO     11:01:59.623 │ Guild supply button 
         active                             
INFO     11:01:59.627 │ Click (1129,  645) @
         GUILD_SUPPLY                       
INFO     11:02:00.186 │ Guild supply button 
         active                             
INFO     11:02:00.455 │ Click ( 790,  517) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:01.278 │ Guild supply button 
         active                             
INFO     11:02:01.281 │ Click (1111,  635) @
         GUILD_SUPPLY                       
INFO     11:02:01.822 │ Guild supply button 
         active                             
INFO     11:02:02.702 │ Click ( 778,  515) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:03.509 │ Guild supply button 
         active                             
INFO     11:02:03.512 │ Click (1153,  642) @
         GUILD_SUPPLY                       
INFO     11:02:04.035 │ Guild supply button 
         active                             
INFO     11:02:04.910 │ Click ( 770,  515) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:05.717 │ Guild supply button 
         active                             
INFO     11:02:05.721 │ Click (1205,  626) @
         GUILD_SUPPLY                       
INFO     11:02:06.243 │ Guild supply button 
         active                             
INFO     11:02:07.110 │ Click ( 774,  506) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:07.916 │ Guild supply button 
         active                             
INFO     11:02:07.919 │ Click (1124,  626) @
         GUILD_SUPPLY                       
INFO     11:02:08.452 │ Guild supply button 
         active                             
INFO     11:02:09.309 │ Click ( 790,  514) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:10.120 │ Guild supply button 
         active                             
INFO     11:02:10.122 │ Click (1134,  646) @
         GUILD_SUPPLY                       
INFO     11:02:10.669 │ Guild supply button 
         active                             
INFO     11:02:11.540 │ Click ( 794,  516) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:12.357 │ Guild supply button 
         active                             
INFO     11:02:12.360 │ Click (1166,  636) @
         GUILD_SUPPLY                       
INFO     11:02:12.875 │ Guild supply button 
         active                             
INFO     11:02:13.750 │ Click ( 792,  524) @
         POPUP_CONFIRM_GUILD_LOGISTICS      
INFO     11:02:14.644 │ Guild supply button 
         active                             
WARNING  11:02:14.646 │ Too many click      
         between 2 buttons:                 
         POPUP_CONFIRM_GUILD_LOGISTICS,     
         GUILD_SUPPLY                       
WARNING  11:02:14.650 │ History click:      
         ['GUILD_SUPPLY',                   
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY',                    
         'POPUP_CONFIRM_GUILD_LOGISTICS',   
         'GUILD_SUPPLY']                    
ERROR    11:02:14.653 │                     
         GameTooManyClickError: Too many    
         click between 2 buttons:           
         POPUP_CONFIRM_GUILD_LOGISTICS,     
         GUILD_SUPPLY                       
WARNING  11:02:14.657 │ Saving error:       
         ./log/error/1660014134657          
WARNING  11:02:14.878 │ Game stuck,         
         com.bilibili.azurlane will be      
         restarted in 10 seconds            
WARNING  11:02:14.881 │ If you are playing  
         by hand, please stop Alas          
INFO     11:02:14.883 │ Task call: Restart  
INFO     11:02:14.899 │ Bind task {'Guild', 
         'Alas', 'General'}                 
INFO     11:02:14.904 │ Save config         
         ./config\alas.json, Restart.Schedul
         er.NextRun=datetime.datetime(2022, 
         8, 9, 11, 2, 14),                  
         Restart.Scheduler.Enable=True      
INFO     11:02:24.918 │ Scheduler: End task 
         `Guild`                            
INFO     11:02:24.933 │ [Server] cn         
INFO     11:02:24.975 │ Bind task           
         {'General', 'Alas'}                
INFO     11:02:24.979 │ Pending tasks:      
         ['Restart', 'Guild', 'SupplyPack', 
         'Reward', 'MetaReward',            
         'ShopFrequent', 'ShopOnce',        
         'Shipyard', 'DataKey', 'Daily',    
         'OpsiAshAssist', 'Event',          
         'GemsFarming']                     
INFO     11:02:24.984 │ [Task] Restart      
         (Enable, 2022-08-09 11:02:14)      
INFO     11:02:24.988 │ Bind task           
         {'Restart', 'General', 'Alas'}     
INFO     11:02:24.995 │ Scheduler: Start    
         task `Restart`                     
════════════════════════════════════════════
                  RESTART                   
════════════════════════════════════════════
INFO     11:02:25.595 │ <<< APP RESTART >>> 
INFO     11:02:25.598 │ App stop:           
         com.bilibili.azurlane

**Comment by LmeSzinc** [comment]
```
WARNING 11:02:14.657 │ Saving error: ./log/error/1660014134657
```
找到这个文件夹，用压缩包打包发出来

**Comment by XokoukioX** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在作业，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
