### ISSUE TITLE
能自由设置重启的开关功能

### ISSUE THREAD

**Issue by Testplayers** [LmeSzinc/AzurLaneAutoScript#1516]
### 你的功能请求是否与问题有关？

重启的开关功能影响很大

### 解决方案

能自由设置重启的开关功能

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/discussions/1437#discussioncomment-3280922

**Comment by LmeSzinc** [comment]
你没有提供具体原因，那按以往经验，不想要关游戏的都是使用了GG （gameguardian），或者GG二次封装，开外挂的，我的建议是放弃使用GG，用这个 https://androidrepublic.org/threads/azur-lane-en-cn-jp-kr-tw-v6-1-2-mega-mod.128986/ ，游戏重启后外挂依然生效
