### ISSUE TITLE
可不可以运行Alas后自动运行脚本

### ISSUE THREAD

**Issue by ErosionSpark** [LmeSzinc/AzurLaneAutoScript#1528]
### 你的功能请求是否与问题有关？

本意是想着用定时开关机，配合自动启动模拟器的，但是启动了Alas好像不会自动运行😭

**Comment by bookbug666** [comment]
#1414

**Comment by ErosionSpark** [comment]
太感谢了

**Comment by ErosionSpark** [comment]
我还是想请问一下，打开了alas.py之后没反应，已经安装了python3.10

**Comment by bookbug666** [comment]
你是怎麼運行的，bat生成reloadalas後啟動alas.exe就能自動啟動了

**Comment by bookbug666** [comment]
如果你是使用預設第一個alas那你運行alas.py就會開始跑，而且你顯然沒有看安裝說明https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en
不是說要用Python3.7.6嗎

**Comment by ErosionSpark** [comment]
> 你是怎麼運行的，bat生成reloadalas後啟動alas.exe就能自動啟動了

解决了，只是不太明白为什么关掉alas后reloadalas会被删除，就设置成只读了，感谢大佬解答

**Comment by bookbug666** [comment]
呃，不行
你得讓bat每次都寫入，read-only會讓更新出現問題

**Comment by bookbug666** [comment]
> > 你是怎麼運行的，bat生成reloadalas後啟動alas.exe就能自動啟動了
> 
> 解决了，只是不太明白为什么关掉alas后reloadalas会被删除，就设置成只读了，感谢大佬解答

.\module\webui\process_manager.py裡面有提到，這算是借用了更新的機制去做到自動啟動
read-only會讓後面os.remove出現問題

**Comment by ErosionSpark** [comment]
> 呃，不行 你得讓bat每次都寫入，read-only會讓更新出現問題

好吧😥
