### ISSUE TITLE
余烬信标复刻META需求(档案信标记录)

### ISSUE THREAD

**Issue by binglingyao** [LmeSzinc/AzurLaneAutoScript#1532]
### 你的功能请求是否与问题有关？

META船复刻可以打了,每天和正常余烬信标一样200点,可以储存1500点
然后发现alas没更新此功能,需求个此功能

### 解决方案

判断是否够100档案信标记录仪
如果足够执行
打一次复刻余烬信标
判断是否成功击破
如果未成功击破则点击自动作战,15分钟之后回来领取奖励
如果成功击破则直接点击领取奖励
重复以上操作

**Comment by LmeSzinc** [comment]
与 #1375 重复

**Comment by LmeSzinc** [comment]
#1574
