### ISSUE TITLE
重启设置卡死问题

### ISSUE THREAD

**Issue by PredictableX** [LmeSzinc/AzurLaneAutoScript#1533]
### 你的功能请求是否与问题有关？

脚本里面有个重启设置让游戏重启，但是我重启之后经常在选择服务器的那个界面跑黄鸡，然后游戏就卡死在那里了。
脚本右边一直在显示“Click ( 512,  366) @ LOGIN_CHECK  ”循环。

### 解决方案

检测到一定数量的Click ( 512,  366) @ LOGIN_CHECK 之后进行强制重启游戏。

**Comment by LmeSzinc** [comment]
需要提供完整的log，alas启动游戏有3次重试，全部失败才会停止
