### ISSUE TITLE
撈船滿破後停止刷圖

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1544]
### 你的功能请求是否与问题有关？

現行Alas有新船停止，然而活動打撈船或是主線打撈到第一艘之後就沒法觸發這個停止了
想說能不能讓Alas掃描讓玩家省點布里，不然短期想增加金紫布里的獲取幾乎是不可能的

### 解决方案

篩選船塢裡面特定船隻的數量，增加一個特定數量後停止

### 其他内容

如果不可行我就關了，就問問這能不能做到

**Comment by LmeSzinc** [comment]
目前没有好的识别方案
