### ISSUE TITLE
活动图关卡刷满100%之后不能反复刷此关卡

### ISSUE THREAD

**Issue by ImMappyJ** [LmeSzinc/AzurLaneAutoScript#1545]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

拿这一次远会点作战举个例子，100%通关+3星+安全海域了SP4后，仍然启用活动图这个脚本，模拟器会先打开SP4这个关卡，然后过一会会返回主界面，同时在Alas里会取消启用活动图脚本

### 如何复现

1. 前往 '活动图'
2. 点击 '启用'
3. 待模拟器打开SP4关卡后自动关闭
4. 出现问题

### 预期行为

能持续自律寻敌作战

**Comment by LmeSzinc** [comment]
我猜你在停止条件处设置了 `100%通关+3星+安全海域` 停止，现在达到了 `100%通关+3星+安全海域` ，SP4是最后一关不能往后推图，所以alas停止了
你需要把 `达成关卡成就后停止` 设置为 `否`

**Comment by ImMappyJ** [comment]
WOW谢谢
