### ISSUE TITLE
日服出击界面舰队职能设置阶段错误

### ISSUE THREAD

**Issue by xuewuji** [LmeSzinc/AzurLaneAutoScript#1551]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

“自动设定”按钮在(1206,285)坐标附近，但是alas试图点击(1205,400)位置，导致无法进入关卡。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by 18870** [comment]
#1043
