### ISSUE TITLE
希望有可以将两个项目穿插进行的解决方案

### ISSUE THREAD

**Issue by MJSummer** [LmeSzinc/AzurLaneAutoScript#1558]
### 你的功能请求是否与问题有关？

例如我有1队低耗 2队监工 和3队东煌
我希望1+2打五次sp3，然后2+3打五次sp4，来回穿插进行

### 解决方案

将调度器增设相关功能
如果有可以实现类似功能的其他方法也可以先用上

**Comment by bookbug666** [comment]
已經有活動1跟活動2了呀，你活動1設1+2打SP3;活動2設2+3打SP4不就實現了嗎
反正你監工不存在心情不一致的問題
