### ISSUE TITLE
捞到新船以后保存截图

### ISSUE THREAD

**Issue by LascinaryZX** [LmeSzinc/AzurLaneAutoScript#1559]
### 你的功能请求是否与问题有关？

alas现有的出击设置中已有捞到新船停止，那么能否添加一个捞到新船以后自动截图的开关？保存路径支不支持自定义无所谓，模拟器截图文件夹路径或者alas根目录的screenshots文件夹都行。

### 解决方案

在出击设置中添加一个捞到新船以后自动截图的选项

**Comment by MJSummer** [comment]
支持（doge

**Comment by LmeSzinc** [comment]
Alas设置 - 掉落记录 - 战斗掉落截图，设置为 `保存`
关卡设置 - 使用自律寻敌，设置为 `关`
