### ISSUE TITLE
出擊加入每日最少次數

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1565]
### 你的功能请求是否与问题有关？

現有的出擊只要填入次數就好，但想要更精準的控制
如果能讓每日至少執行某個出擊任務X次就能更平均石油的消耗
而且也能讓科研或是其他資源消耗更能避免短時間特定的不足

### 解决方案

在出擊任務(除每日活動雙倍三倍那些可以不用)上次數停止下面加上每日最少次數，只有在停止次數為0的時候才啟用這個
這樣我不只可以讓每天固定打X次活動，非活動期間我也可以設定一天至少打多少場就能確保我有足夠的物資跑科研，油不夠一樣會由Alas觸發停止

完成每日最低出擊，延遲至下次伺服器刷新換日

**Comment by LmeSzinc** [comment]
这个应该在 #1509 里添加，并且逻辑应当是当物资低于X时运行，以达到自动控制的目的，而不是去手动计算

**Comment by bookbug666** [comment]
主要是我想要平均一天打活動的比例，算好這次活動需要打500場才能畢業的話
我會希望讓一天能最少打40場，剩下的都交給石油控制，那這場數應該是手動的吧......至少我是這樣想的

我也會希望我一天進帳假設3600油，非活動期間也至少打N場，有個最保底的出擊量

**Comment by bookbug666** [comment]
希望的是像每日Hard3場那樣，但能自定義出擊量

**Comment by bookbug666** [comment]
重新思考了一下，這個量是跟每日石油獲取有衝突的(手動計算是否有超過一天大約3500上下的石油)
如果弄不好會有一天沒打完的情況，與我希望的/Alas實際運作不符，所以我Close了
