### ISSUE TITLE
慢的电脑无法登陆进游戏 能否把这个点击次数上限后自动重启功能关闭？ 或者截图间隔延长到1秒？

### ISSUE THREAD

**Issue by JinAquila** [LmeSzinc/AzurLaneAutoScript#1566]
### 你的功能请求是否与问题有关？

截图间隔现在强制在0.3秒，本来每次游戏被重启慢的电脑进都要花很长时间，上次更新后就多了个点击次数上限后自动重启，导致慢的电脑根本进不去游戏界面就被重启三次然后alas报错停止。
能否把这个点击次数上限后自动重启功能关闭？
或者截图间隔延长到1秒？
谢谢

### 解决方案

能否把这个点击次数上限后自动重启功能关闭？
或者截图间隔延长到1秒？
谢谢

**Comment by JinAquila** [comment]
![Uploading E6AFF979-57F7-422E-A033-BCEC72104349.jpeg…]()

**Comment by LmeSzinc** [comment]
需要提供完整log和游戏截图
鉴于你正在使用新的 github 帐号，这个 issue 将在无活跃的 3 天后被关闭

**Comment by JinAquila** [comment]
![01B72667-0821-4110-B868-A1A285C36BD6](https://user-images.githubusercontent.com/111650440/187054366-76423780-1f1d-456f-a506-0916c56e9395.jpeg)
log是这样的，这样的错误不会存在error文件夹里
截图就是登陆界面

**Comment by JinAquila** [comment]
![393D0CA7-0C97-44AF-85EC-A5B23AF437DC](https://user-images.githubusercontent.com/111650440/187057200-3cd417c5-75e0-4290-a47d-2bfd87a4a9d3.jpeg)
就在这里登陆花的时间很长，以前等等就进去了，就上回更新了个新功能点点点上限了就要重启，这辈子进不去游戏主界面。
求求出个一个开关能不能不要强制重启，我等还不行吗。
