### ISSUE TITLE
ubuntu手动安装问题

### ISSUE THREAD

**Issue by zhiye1235** [LmeSzinc/AzurLaneAutoScript#1568]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

在使用云服务器ubuntu系统手动安装alas，完成前面的步骤到了最后一步运行alas出现了问题，大佬能帮忙看看吗？，谢谢。

### To Reproduce

1. 看教程手动安装alas
2. 完成前面步骤
3. 到了最后一步运行alas出现错误

### Expected behavior

成功在云服务器上运行alas

### Relevant log output

```Text
(alas) ubuntu@VM-4-6-ubuntu:~/AzurLaneAutoScript$ python gui.py
Traceback (most recent call last):
  File "gui.py", line 4, in <module>
    from module.webui.setting import State
  File "/home/ubuntu/AzurLaneAutoScript/module/webui/__init__.py", line 2, in <module>
    from module.logger import logger  # Change folder
  File "/home/ubuntu/AzurLaneAutoScript/module/logger.py", line 7, in <module>
    from rich.console import Console, ConsoleOptions, ConsoleRenderable, NewLine
ModuleNotFoundError: No module named 'rich
```

### Screenshots

![屏幕截图 2022-08-27 215735](https://user-images.githubusercontent.com/103776784/187033803-b351de6a-de95-450b-bf1c-637ad6294fae.jpg)

**Comment by LmeSzinc** [comment]
依赖未安装完全，需要安装 requirements-in.txt 中的依赖
