### ISSUE TITLE
PermissionError Encountered When Applying Docker Deployment

### ISSUE THREAD

**Issue by jellllly420** [LmeSzinc/AzurLaneAutoScript#1569]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [x] I am using the latest version of Alas

### Describe the bug

- **Versoin:** ``Master`` branch from [the gitee repository](https://gitee.com/lmeszinc/AzurLaneAutoScript)
- **Platform:** Ubuntu 22.04LTS
- **Docker Version:** 20.10.17

#### Description
I followed [this artical](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en_docker) to deploy Alas on my server. Right after the building procedure, ``os.mkdir()`` triggered an PermissionError as the log below shows.

I'm new to docker and container so I'm not sure what exactly caused this problem. I thought it might be related to the user ``abc`` in ``deploy/docker/Dockerfile`` and its privileges.

Thanks to anyone who is willing to help.

### To Reproduce

Follow [this artical](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en_docker) to deploy Alas on a server running Ubuntu 22.04LTS.

### Expected behavior

I expected it to show the IP address to access the GUI in my web browser just like [this artical](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en_docker) said.

### Relevant log output

```Text
ubuntu:~/AzurLaneAutoScript$ docker compose up
[+] Running 1/0
 ⠿ Container alas  Created                                                               0.0s
Attaching to alas
alas  | * daemon not running; starting now at tcp:5037
alas  | * daemon started successfully
alas  | Traceback (most recent call last):
alas  |   File "/app/AzurLaneAutoScript/module/logger.py", line 193, in set_file_logger
alas  |     file = open(log_file, mode='a', encoding='utf-8')
alas  | FileNotFoundError: [Errno 2] No such file or directory: './log/2022-08-27_gui.txt'
alas  | 
alas  | During handling of the above exception, another exception occurred:
alas  | 
alas  | Traceback (most recent call last):
alas  |   File "/app/AzurLaneAutoScript/gui.py", line 4, in <module>
alas  |     from module.webui.setting import State
alas  |   File "/app/AzurLaneAutoScript/module/webui/__init__.py", line 2, in <module>
alas  |     from module.logger import logger  # Change folder
alas  |   File "/app/AzurLaneAutoScript/module/logger.py", line 355, in <module>
alas  |     logger.set_file_logger()
alas  |   File "/app/AzurLaneAutoScript/module/logger.py", line 195, in set_file_logger
alas  |     os.mkdir('./log')
alas  | PermissionError: [Errno 13] Permission denied: './log'
alas exited with code 1
```

**Comment by jellllly420** [comment]
@viperML or @n0k0m3 Could you please have a look into this issue? Thank you.

**Comment by n0k0m3** [comment]
Can you paste the output of `ls -la`?

**Comment by jellllly420** [comment]
Sorry for the delay. Here is the `ls -la` output:
<details>
<summary>output</summary>

```
ubuntu:~/AzurLaneAutoScript$ ls -la
total 156
drwxrwxr-x 13 jelly jelly  4096 Aug 28 01:40 .
drwxrwxr-x  3 jelly jelly  4096 Aug 28 01:04 ..
-rw-rw-r--  1 jelly jelly 19553 Aug 28 01:40 alas.py
drwxrwxr-x 13 jelly jelly  4096 Aug 28 01:40 assets
drwxrwxr-x  5 jelly jelly  4096 Aug 28 01:40 bin
drwxrwxr-x 71 jelly jelly  4096 Aug 28 01:40 campaign
drwxrwxr-x  2 jelly jelly  4096 Aug 28 01:40 config
drwxrwxr-x  5 jelly jelly  4096 Aug 28 01:40 deploy
drwxrwxr-x  3 jelly jelly  4096 Aug 28 01:40 dev_tools
drwxrwxr-x  3 jelly jelly  4096 Aug 28 01:40 doc
-rw-rw-r--  1 jelly jelly   316 Aug 28 01:40 docker-compose.yml
drwxrwxr-x  8 jelly jelly  4096 Aug 28 01:40 .git
-rw-rw-r--  1 jelly jelly   248 Aug 28 01:40 .gitattributes
drwxrwxr-x  4 jelly jelly  4096 Aug 28 01:40 .github
-rw-rw-r--  1 jelly jelly  3897 Aug 28 01:40 .gitignore
-rw-rw-r--  1 jelly jelly  2184 Aug 28 01:40 gui.py
-rw-rw-r--  1 jelly jelly 35149 Aug 28 01:40 LICENSE
drwxrwxr-x 43 jelly jelly  4096 Aug 28 01:40 module
-rw-rw-r--  1 jelly jelly  6356 Aug 28 01:40 README_en.md
-rw-rw-r--  1 jelly jelly 10618 Aug 28 01:40 README.md
-rw-rw-r--  1 jelly jelly   359 Aug 28 01:40 requirements-in.txt
-rw-rw-r--  1 jelly jelly  4526 Aug 28 01:40 requirements.txt
drwxrwxr-x  8 jelly jelly  4096 Aug 28 01:40 webapp
```

</details>

Also, I tried to modify the `deploy/docker/Dockerfile` to let the docker run without creating a new user `abc` and added Alas as a globally safe directory for Git. I knew this in conflict with Git‘s security policy but it finally worked at least. [Here](https://github.com/jellllly420/AzurLaneAutoScript/blob/master/deploy/docker/Dockerfile) is the code.

> Can you paste the output of `ls -la`?

**Comment by n0k0m3** [comment]
Not really a fan of using bypassing git safe directory. Creating new user `abc` is to resolve the problem without modifying git security flags, but I assume that your UID and GID of `jelly` are different from UID/GID 1000/1000.

Let me check if the docker deployment can be used with podman instead as podman UID mapping is more sane

**Comment by n0k0m3** [comment]
Also regarding 39b1899cddaec9d41fca32a451c46e02babeb0bd, can you create a new Dockerfile deployment for CN instead as `pip install -i` argument will be indexed first during requirements installation and it will be slow for people outside of CN

Meanwhile the proper way to solve this is `userns-remap` (https://docs.docker.com/engine/security/userns-remap/), but it will f* up any docker containers you already having.

So again, the good solution here is to figure out podman

**Comment by jellllly420** [comment]
You are right about the UID/GID. However, I don't think it makes sense that I must get specific UID/GID to use Alas.
 
39b1899 is just my try for test and all the modifications of mirrors can be ignored. 

I'm a real noob to containers and I'm still confused with their file systems. So I'm afraid I can't offer you any help on the remap of user namespace or the migration to Podman, at least not recently. 

Hope you can solve this problem. Thank you very much for your help.

**Comment by n0k0m3** [comment]
Got podman and podman compose working and it seems that they map uid and gid to running user immediately. With this I don't need to create a user any more (more or less I wanted a secure setup so root in container mapping to root host is nono).

Will make a PR for this soon and edit the wiki
