### ISSUE TITLE
一括退役經常無法按  導致ALAS卡住

### ISSUE THREAD

**Issue by kakeru168** [LmeSzinc/AzurLaneAutoScript#1575]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

一括退役經常無法按  導致ALAS卡住

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
需要完整log和截图，并描述你的问题。

举例：我正在使用XX模拟器玩碧蓝航线X服，遇到了一键退役无法点击的问题，
[游戏截图一张]
```
一大串log
```
我进行的尝试
我尝试手动点击一键退役的按钮（能/不能）成功选择，我尝试点击返回按钮再进入（能/不能）成功选择，我尝试重启游戏（能/不能）成功选择

**Comment by kakeru168** [comment]
![image](https://user-images.githubusercontent.com/106340846/187475349-0edabc37-e179-496e-8c21-530a4ce3ba8a.png)
──────────────────────────────────── BATTLE_2 ─────────────────────────────────────
INFO     23:15:42.380 │ BATTLE_2                                                   
INFO     23:15:42.382 │ Auto search moving                                         
INFO     23:15:42.384 │ Fleet: 1, fleet_current_index: 1                           
INFO     23:15:42.412 │ [OCR_OIL 0.024s] 3695                                      
INFO     23:15:44.881 │ Skip map cat attack                                        
INFO     23:15:44.884 │ Click (1229,  665) @ MAP_CAT_ATTACK                        
INFO     23:15:46.078 │ Click ( 426,  510) @ RETIRE_APPEAR_1                       
INFO     23:15:46.695 │ <<< RETIREMENT >>>                                         
INFO     23:15:46.697 │ Using one click retirement.                                
INFO     23:15:46.699 │ [Favourite_filter] off                                     
INFO     23:15:46.713 │ Click ( 746,  667) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:48.894 │ Click ( 725,  669) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:51.016 │ Click ( 692,  665) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:53.115 │ Click ( 735,  662) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:55.211 │ Click ( 713,  668) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:57.336 │ Click ( 695,  662) @ ONE_CLICK_RETIREMENT                  
INFO     23:15:59.438 │ Click ( 740,  674) @ ONE_CLICK_RETIREMENT                  
INFO     23:16:01.556 │ Click ( 763,  673) @ ONE_CLICK_RETIREMENT                  
INFO     23:16:03.645 │ Click ( 694,  667) @ ONE_CLICK_RETIREMENT                  
INFO     23:16:05.761 │ Click ( 738,  677) @ ONE_CLICK_RETIREMENT                  
[alas] exited. Reason: Manual stop
我尝试手动点击一键退役的按钮 （不能） 成功选择，我尝试点击返回按钮再进入（能）成功选择，我尝试重启游戏（能）成功选择

**Comment by Guosh2020** [comment]
我国服蓝叠模拟器遇到了同样的问题

**Comment by Guosh2020** [comment]
![Screenshot_2022 08 31_18 16 09 204](https://user-images.githubusercontent.com/111166987/187656137-59b6de0f-0fe9-43e4-b5ba-8e82672aa088.png)

──────────────────────────────────── BATTLE_5 ─────────────────────────────────────
INFO     17:51:45.867 │ BATTLE_5                                                   
INFO     17:51:45.874 │ Auto search moving                                         
INFO     17:51:45.883 │ Fleet: 1, fleet_current_index: 1                           
INFO     17:51:45.967 │ [OCR_OIL 0.076s] 1323                                      
INFO     17:51:50.973 │ Fleet: 2, fleet_current_index: 2                           
INFO     17:51:55.809 │ Click ( 435,  519) @ RETIRE_APPEAR_1                       
INFO     17:51:57.723 │ <<< RETIREMENT >>>                                         
INFO     17:51:57.730 │ Using one click retirement.                                
INFO     17:51:57.738 │ [Favourite_filter] off                                     
INFO     17:51:57.772 │ Click ( 719,  688) @ ONE_CLICK_RETIREMENT                  
INFO     17:51:59.975 │ Click ( 759,  665) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:02.099 │ Click ( 733,  660) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:04.223 │ Click ( 728,  676) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:06.432 │ Click ( 725,  656) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:08.581 │ Click ( 701,  653) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:10.686 │ Click ( 719,  662) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:12.729 │ Click ( 740,  685) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:14.793 │ Click ( 724,  655) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:16.814 │ Click ( 755,  665) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:19.437 │ Click ( 746,  664) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:21.546 │ Click ( 723,  689) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:23.569 │ Click ( 722,  671) @ ONE_CLICK_RETIREMENT                  
INFO     17:52:25.743 │ Click ( 705,  663) @ ONE_CLICK_RETIREMENT                  
WARNING  17:52:27.770 │ Too many click for a button: ONE_CLICK_RETIREMENT          
WARNING  17:52:27.775 │ History click: ['ONE_CLICK_RETIREMENT',                    
         'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT',   
         'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT',   
         'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT',   
         'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT',   
         'ONE_CLICK_RETIREMENT', 'ONE_CLICK_RETIREMENT']                           
ERROR    17:52:27.784 │ GameTooManyClickError: Too many click for a button:        
         ONE_CLICK_RETIREMENT                                                      
WARNING  17:52:27.796 │ Saving error: ./log/error/1661939547796                    
WARNING  17:52:28.261 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  17:52:28.267 │ If you are playing by hand, please stop Alas               
INFO     17:52:28.272 │ Task call: Restart                                         
INFO     17:52:28.301 │ Bind task {'Alas', 'General', 'Event', 'EventGeneral'}     
INFO     17:52:28.306 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2022, 8, 31, 17, 52, 28),     
         Restart.Scheduler.Enable=True                                             
INFO     17:52:38.323 │ Scheduler: End task `Event`                                
INFO     17:52:38.327 │ [alas] exited. Reason: Finish

**Comment by modeilan** [comment]
国服夜神现在也有同样的问题了，第一次进入退役界面一键退役无法点击，需要退出去重新进入才行
