### ISSUE TITLE
錯誤通知功能是否正常？

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1600]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

照著程式內的教學，配置了discord webhook及telegram bot並手動製造error，但都沒有發送訊息

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

通知玩家

**Comment by 18870** [comment]
![image](https://user-images.githubusercontent.com/22175295/188573686-421c247a-f356-4681-a619-3e2e8366f4cf.png)
![image](https://user-images.githubusercontent.com/22175295/188574923-4a7b92fe-327e-4b8c-a562-7d83ed3a4ee8.png)

**Comment by bookbug666** [comment]
那就奇怪了......我檢查一下檔案有沒有問題好了
~~沒理由只有我不能用吧~~

**Comment by bookbug666** [comment]
確認格式是對的了但沒有出現push notify

**Comment by 18870** [comment]
设备连接失败并不会推送
https://github.com/LmeSzinc/AzurLaneAutoScript/discussions/1611#discussioncomment-3587405

**Comment by bookbug666** [comment]
原來是這樣，剛剛整個清除重啟再貼回去突然正常運作了
