### ISSUE TITLE
Assets update for OneHitMod and Dossier Beacon

### ISSUE THREAD

**Issue by zhou525** [LmeSzinc/AzurLaneAutoScript#1606]
### Is your feature request related to a problem?

#1574 

### Additional context

Four assets need to be added:

DOSSIER_LIST.png
META_AUTO_CONFIRM.png
META_INNER_PAGE_DAMAGE.png
META_INNER_PAGE_NOT_DAMAGE.png

The following assets need to be checked for compatibility with own server:

META_BEACON_DATA.png
META_BEACON_FLAG.png
META_DOSSIER_DATA.png
META_DOSSIER_FLAG.png
META_DAMAGE.png

**Comment by mm770912** [comment]
![image](https://user-images.githubusercontent.com/14796986/190204250-a7b1f66e-bcf8-461c-af34-e29e22436973.png)

請問更新之後的這個功能是這樣打勾就好嗎

**Comment by LmeSzinc** [comment]
台服目前未开放往期信标系统，还不需要适配，所以 issue 先关掉，见 #1640
