### ISSUE TITLE
在安装时出现ModuleNotFoundError: No module named 'progress.bar'

### ISSUE THREAD

**Issue by Nieianyue** [LmeSzinc/AzurLaneAutoScript#1608]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在安装时出现
File "C:\Users\RyuZU\Desktop\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\init.py", line 12, in <module>
    import progress.bar
ModuleNotFoundError: No module named 'progress.bar'
我尝试在console.bat中安装了progress
pip install progress
依然出现这个问题。

### 如何复现

1. 前往 'Alas.exe'
4. 出现问题

### 预期行为

能够正常安装

### 截图

![图片](https://user-images.githubusercontent.com/13326189/188784046-da129858-ca81-4b37-8928-cdd31e312b4c.png)

**Comment by LmeSzinc** [comment]
在 console.bat 中执行：
```
pip uninstall -y progress
pip install --no-cache-dir progress
```
然后重新打开 Alas.exe

**Comment by Nieianyue** [comment]
感谢，已解决！
