### ISSUE TITLE
每执行完一次战斗就会报错,系统找不到指定的路径

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [LmeSzinc/AzurLaneAutoScript#161]
自动开始进入战斗后，会在第一个结算界面卡住
> 2020-08-15 15:48:04.464 | ERROR | [WinError 3] 系统找不到指定的路径。: '/campaign_4_2\\status'
> Traceback (most recent call last):
>   File "E:\tools\AzurLaneAutoScript\alas.py", line 27, in run
>     self.__getattribute__(command.lower())()
>   File "E:\tools\AzurLaneAutoScript\alas.py", line 141, in event
>     az.run(self.config.CAMPAIGN_EVENT, folder=self.config.EVENT_NAME)
>   File "E:\tools\AzurLaneAutoScript\module\campaign\run.py", line 173, in run
>     self.campaign.run()
>   File "E:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 123, in run
>     self.execute_a_battle()
>   File "E:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 93, in execute_a_battle
>     result = self.battle_function()
>   File "E:\tools\AzurLaneAutoScript\module\base\decorator.py", line 62, in wrapper
>     return record['func'](self, *args, **kwargs)
>   File "E:\tools\AzurLaneAutoScript\module\campaign\campaign_base.py", line 61, in battle_function
>     if self.clear_siren():
>   File "E:\tools\AzurLaneAutoScript\module\map\map.py", line 400, in clear_siren
>     self.clear_chosen_enemy(grids[0], expected='siren')
>   File "E:\tools\AzurLaneAutoScript\module\map\map.py", line 19, in clear_chosen_enemy
>     self.goto(grid, expected=expected)
>   File "E:\tools\AzurLaneAutoScript\module\map\fleet.py", line 304, in goto
>     self._goto(node, expected=expected if node == nodes[-1] else '')
>   File "E:\tools\AzurLaneAutoScript\module\map\fleet.py", line 225, in _goto
>     self.combat(expected_end=self._expected_combat_end(expected), fleet_index=self.fleet_current_index)
>   File "E:\tools\AzurLaneAutoScript\module\combat\combat.py", line 377, in combat
>     auto=auto_mode, call_submarine_at_boss=call_submarine_at_boss, save_get_items=save_get_items)
>   File "E:\tools\AzurLaneAutoScript\module\combat\combat.py", line 224, in combat_execute
>     if self.handle_battle_status(save_get_items=save_get_items) or self.handle_get_items(save_get_items=save_get_items):
>   File "E:\tools\AzurLaneAutoScript\module\combat\combat.py", line 238, in handle_battle_status
>     if self.appear_then_click(BATTLE_STATUS_S, screenshot=save_get_items, genre='status', interval=self.battle_status_click_interval):
>   File "E:\tools\AzurLaneAutoScript\module\base\base.py", line 61, in appear_then_click
>     self.device.save_screenshot(genre=genre)
>   File "E:\tools\AzurLaneAutoScript\module\device\screenshot.py", line 144, in save_screenshot
>     os.mkdir(folder)
> FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '/campaign_4_2\\status'
> 2020-08-15 15:48:04.467 | INFO | Saving error: ./log/error/1597477684467
>

**Comment by LmeSzinc** [comment]
把掉落记录关了, 或者指定存放的文件夹

**Comment by Tsurumaki-Kokoro** [comment]
感谢，已解决
