### ISSUE TITLE
传统退役是否可以选择不退役布里

### ISSUE THREAD

**Issue by AzusaYukina** [LmeSzinc/AzurLaneAutoScript#1614]
### 你的功能请求是否与问题有关？

一键退役在启动游戏第一次使用时无法点击，在服务器配置下经常导致Alas报错退出，故切换至传统退役。但传统退役选择退役紫船后，紫布里也被一并退役。

### 解决方案

在退役模式选择传统退役时，添加选项使得Alas不退役布里
进一步，是否可以添加选项过滤特定舰娘使其不被退役

### 其他内容

无

**Comment by LmeSzinc** [comment]
> 一键退役在启动游戏第一次使用时无法点击

这个问题应该在 #1575 中已经修复，如果你存在问题贴出 log 和截图

**Comment by AzusaYukina** [comment]
嗯，我再测试一下一键退役是否可用，半个月前因为上面提到的游戏本体问题就换成传统退役了，后来没有更改过
（不过仍然希望如果有可能的话给传统退役增加一些过滤选项）
