### ISSUE TITLE
扫描紧急委托时有概率忽略掉第一个

### ISSUE THREAD

**Issue by VirtualTowel** [LmeSzinc/AzurLaneAutoScript#1622]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

这个问题主要是在Aidlux+Vmos方案下使用aScreenCap截图方式遇到的，猜测是因为游戏反应较慢以及aScreenCap在手机上截图速度相对较快（0.2s），在第一个紧急委托被遮挡时就截了图。
在云服务器+星界链方案同样遇到了这个问题，但是概率相对较小，主要也是在使用速度较快的截图方式时出现概率较高。

目前只在紧急委托页面没有scroll bar的时候遇到了这个问题。

### 预期行为

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/72c9cb1937cae203b2b197c50d93d5928816c74a/module/commission/commission.py#L74
尝试把commission_detect函数的skip_first_screenshot参数改成false，使其在第一次扫描委托之前重新截图，问题似乎被解决，经过多次重试没有复现。此更改似乎并没有造成过多的性能浪费，所以我想是否可以直接弃用这个skip_first_screenshot参数？

### 截图

尝试在点击紧急委托时录像并在紧急委托出现的一瞬间截图：
![QQ图片20220910173828](https://user-images.githubusercontent.com/42640608/189477804-2a3ce140-6934-4d81-940e-bad31e3a31d0.png)

猜测_commission_ensure_mode函数也许把这个情况当成正常的了，于是截取了此时的图像

**Comment by LmeSzinc** [comment]
已经有这个的处理。切换委托列表的时候有一个动画，委托卡片从屏幕上方滑出
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/72c9cb1937cae203b2b197c50d93d5928816c74a/module/commission/commission.py#L179-L193

可以尝试在 `if not COMMISSION_SCROLL.appear(main=self) or COMMISSION_SCROLL.cal_position(main=self) < 0.05:` 里添加 `or COMMISSION_SCROLL.length / COMMISSION_SCROLL.total > 0.98`

**Comment by VirtualTowel** [comment]
> 已经有这个的处理。切换委托列表的时候有一个动画，委托卡片从屏幕上方滑出
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/72c9cb1937cae203b2b197c50d93d5928816c74a/module/commission/commission.py#L179-L193
> 
> 可以尝试在 `if not COMMISSION_SCROLL.appear(main=self) or COMMISSION_SCROLL.cal_position(main=self) < 0.05:` 里添加 `or COMMISSION_SCROLL.length / COMMISSION_SCROLL.total > 0.98`

我按照这样修改了，并没有解决，可能并不一定是滚动条的问题，因为后面两三帧是这种情况：
![QQ图片20220910213312](https://user-images.githubusercontent.com/42640608/189485805-87d46a35-993a-40bd-b74b-ba9ebc31c257.png)
没有滚动条，且还是看不见委托名称。
目前没有过多时间研究_commission_ensure_mode这个函数……找到两个相对来说简单的解决方法

1、上文说的弃用skip_first_screenshot参数

2、
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/72c9cb1937cae203b2b197c50d93d5928816c74a/module/commission/commission.py#L259-L263
在261和262行中间添加一行`self.device.screenshot()`，使其在扫描紧急委托列表之前额外截图一次，测试可行。

第二个方案的性能损失似乎更小，是否可以这样更改呢？

**Comment by LmeSzinc** [comment]
你也提到是后面两三针都是这个情况，那么这两种方法显然都不能解决问题，因为他们只能解决一帧的问题。

**Comment by VirtualTowel** [comment]
#1626
