### ISSUE TITLE
DLL load failed: %1 不是有效的 Win32 应用程序。

### ISSUE THREAD

**Issue by Testplayers** [LmeSzinc/AzurLaneAutoScript#1623]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

DLL load failed: %1 不是有效的 Win32 应用程序。

### 如何复现

ERROR    17:57:11.141 │ ImportError: DLL load failed: %1 不是有效的 Win32          
         应用程序。                                                                
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\webui\process_manager.py:132 in           │
         │ run_process                                                            │
         │                                                                        │
         │   130 │   │   │   │   if e is not None:                                │
         │   131 │   │   │   │   │   AzurLaneAutoScript.stop_event = e            │
         │ ❱ 132 │   │   │   │   AzurLaneAutoScript(config_name=config_name).loop │
         │   133 │   │   │   elif func == "Daemon":                               │
         │   134 │   │   │   │   from module.daemon.daemon import AzurLaneDaemon  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ AzurLaneAutoScript = <class 'alas.AzurLaneAutoScript'>             │ │
         │ │     AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'> │ │
         │ │        config_name = 'alas'                                        │ │
         │ │                  e = ImportError('DLL load failed: %1 不是有效的   │ │
         │ │                      Win32 应用程序。')                            │ │
         │ │               func = 'Alas'                                        │ │
         │ │                  q = <AutoProxy[Queue] object, typeid 'Queue' at   │ │
         │ │                      0xfbe8e390c8>                                 │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\AzurLaneAutoScript\alas.py:470 in loop                              │
         │                                                                        │
         │   468 │   │   │   │   self.config.task_call('Restart')                 │
         │   469 │   │   │   # Get task                                           │
         │ ❱ 470 │   │   │   task = self.get_next_task()                          │
         │   471 │   │   │   # Init device and change server                      │
         │   472 │   │   │   _ = self.device                                      │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ failure_record = {}                                                │ │
         │ │       is_first = True                                              │ │
         │ │           self = <alas.AzurLaneAutoScript object at                │ │
         │ │                  0x000000FBE86FCA88>                               │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\alas.py:409 in get_next_task                     │
         │                                                                        │
         │   407 │   │   │   from module.base.resource import release_resources   │
         │   408 │   │   │   if self.config.task.command != 'Alas':               │
         │ ❱ 409 │   │   │   │   release_resources(next_task=task.command)        │
         │   410 │   │   │                                                        │
         │   411 │   │   │   if task.next_run > datetime.now():                   │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ release_resources = <function release_resources at                 │ │
         │ │                     0x000000FBE9889168>                            │ │
         │ │              self = <alas.AzurLaneAutoScript object at             │ │
         │ │                     0x000000FBE86FCA88>                            │ │
         │ │              task = Restart (Enable, 2020-01-01 00:00:00)          │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\base\resource.py:108 in release_resources │
         │                                                                        │
         │   106 │   if not State.deploy_config.UseOcrServer:                     │
         │   107 │   │   # Release only when using per-instance OCR               │
         │ ❱ 108 │   │   from module.ocr.ocr import OCR_MODEL                     │
         │   109 │   │   if 'Opsi' in next_task or 'commission' in next_task:     │
         │   110 │   │   │   # OCR models will be used soon, don't release        │
         │                                                                        │
         │ ╭───────────────────── locals ─────────────────────╮                   │
         │ │ next_task = 'Restart'                            │                   │
         │ │     State = <class 'module.webui.setting.State'> │                   │
         │ ╰──────────────────────────────────────────────────╯                   │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\ocr\ocr.py:6 in <module>                  │
         │                                                                        │
         │     4 from typing import TYPE_CHECKING                                 │
         │     5                                                                  │
         │ ❱   6 from module.base.button import Button                            │
         │     7 from module.base.utils import *                                  │
         │     8 from module.logger import logger                                 │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │  __builtins__ = {                                                  │ │
         │ │                 │   '__name__': 'builtins',                        │ │
         │ │                 │   '__doc__': 'Built-in functions, exceptions,    │ │
         │ │                 and other objects.\n\nNoteworthy: None is the      │ │
         │ │                 `nil'+46,                                          │ │
         │ │                 │   '__package__': '',                             │ │
         │ │                 │   '__loader__': <class                           │ │
         │ │                 '_frozen_importlib.BuiltinImporter'>,              │ │
         │ │                 │   '__spec__': ModuleSpec(name='builtins',        │ │
         │ │                 loader=<class                                      │ │
         │ │                 '_frozen_importlib.BuiltinImporter'>),             │ │
         │ │                 │   '__build_class__': <built-in function          │ │
         │ │                 __build_class__>,                                  │ │
         │ │                 │   '__import__': <built-in function __import__>,  │ │
         │ │                 │   'abs': <built-in function abs>,                │ │
         │ │                 │   'all': <built-in function all>,                │ │
         │ │                 │   'any': <built-in function any>,                │ │
         │ │                 │   ... +143                                       │ │
         │ │                 }                                                  │ │
         │ │    __cached__ = 'D:\\AzurLaneAutoScript\\module\\ocr\\__pycache__… │ │
         │ │       __doc__ = None                                               │ │
         │ │      __file__ = 'D:\\AzurLaneAutoScript\\module\\ocr\\ocr.py'      │ │
         │ │    __loader__ = <_frozen_importlib_external.SourceFileLoader       │ │
         │ │                 object at 0x000000FBEA329748>                      │ │
         │ │      __name__ = 'module.ocr.ocr'                                   │ │
         │ │   __package__ = 'module.ocr'                                       │ │
         │ │      __spec__ = ModuleSpec(name='module.ocr.ocr',                  │ │
         │ │                 loader=<_frozen_importlib_external.SourceFileLoad… │ │
         │ │                 object at 0x000000FBEA329748>,                     │ │
         │ │                 origin='D:\\AzurLaneAutoScript\\module\\ocr\\ocr.… │ │
         │ │            re = <module 're' from                                  │ │
         │ │                 'D:\\AzurLaneAutoScript\\toolkit\\lib\\re.py'>     │ │
         │ │          time = <module 'time' (built-in)>                         │ │
         │ │     timedelta = <class 'datetime.timedelta'>                       │ │
         │ │ TYPE_CHECKING = False                                              │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\base\button.py:9 in <module>              │
         │                                                                        │
         │     7 from module.base.decorator import cached_property                │
         │     8 from module.base.resource import Resource                        │
         │ ❱   9 from module.base.utils import *                                  │
         │    10 from module.config.server import VALID_SERVER                    │
         │    11                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │    __builtins__ = {                                                │ │
         │ │                   │   '__name__': 'builtins',                      │ │
         │ │                   │   '__doc__': 'Built-in functions, exceptions,  │ │
         │ │                   and other objects.\n\nNoteworthy: None is the    │ │
         │ │                   `nil'+46,                                        │ │
         │ │                   │   '__package__': '',                           │ │
         │ │                   │   '__loader__': <class                         │ │
         │ │                   '_frozen_importlib.BuiltinImporter'>,            │ │
         │ │                   │   '__spec__': ModuleSpec(name='builtins',      │ │
         │ │                   loader=<class                                    │ │
         │ │                   '_frozen_importlib.BuiltinImporter'>),           │ │
         │ │                   │   '__build_class__': <built-in function        │ │
         │ │                   __build_class__>,                                │ │
         │ │                   │   '__import__': <built-in function             │ │
         │ │                   __import__>,                                     │ │
         │ │                   │   'abs': <built-in function abs>,              │ │
         │ │                   │   'all': <built-in function all>,              │ │
         │ │                   │   'any': <built-in function any>,              │ │
         │ │                   │   ... +143                                     │ │
         │ │                   }                                                │ │
         │ │      __cached__ = 'D:\\AzurLaneAutoScript\\module\\base\\__pycach… │ │
         │ │         __doc__ = None                                             │ │
         │ │        __file__ = 'D:\\AzurLaneAutoScript\\module\\base\\button.p… │ │
         │ │      __loader__ = <_frozen_importlib_external.SourceFileLoader     │ │
         │ │                   object at 0x000000FBEA40A608>                    │ │
         │ │        __name__ = 'module.base.button'                             │ │
         │ │     __package__ = 'module.base'                                    │ │
         │ │        __spec__ = ModuleSpec(name='module.base.button',            │ │
         │ │                   loader=<_frozen_importlib_external.SourceFileLo… │ │
         │ │                   object at 0x000000FBEA40A608>,                   │ │
         │ │                   origin='D:\\AzurLaneAutoScript\\module\\base\\b… │ │
         │ │ cached_property = <class 'module.base.decorator.cached_property'>  │ │
         │ │       ImageDraw = <module 'PIL.ImageDraw' from                     │ │
         │ │                   'D:\\AzurLaneAutoScript\\toolkit\\lib\\site-pac… │ │
         │ │         imageio = <module 'imageio' from                           │ │
         │ │                   'D:\\AzurLaneAutoScript\\toolkit\\lib\\site-pac… │ │
         │ │              os = <module 'os' from                                │ │
         │ │                   'D:\\AzurLaneAutoScript\\toolkit\\lib\\os.py'>   │ │
         │ │        Resource = <class 'module.base.resource.Resource'>          │ │
         │ │       traceback = <module 'traceback' from                         │ │
         │ │                   'D:\\AzurLaneAutoScript\\toolkit\\lib\\tracebac… │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\base\utils.py:1 in <module>               │
         │                                                                        │
         │ ❱   1 import cv2                                                       │
         │     2 import numpy as np                                               │
         │     3 from PIL import Image                                            │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __builtins__ = {                                                   │ │
         │ │                │   '__name__': 'builtins',                         │ │
         │ │                │   '__doc__': 'Built-in functions, exceptions, and │ │
         │ │                other objects.\n\nNoteworthy: None is the `nil'+46, │ │
         │ │                │   '__package__': '',                              │ │
         │ │                │   '__loader__': <class                            │ │
         │ │                '_frozen_importlib.BuiltinImporter'>,               │ │
         │ │                │   '__spec__': ModuleSpec(name='builtins',         │ │
         │ │                loader=<class                                       │ │
         │ │                '_frozen_importlib.BuiltinImporter'>),              │ │
         │ │                │   '__build_class__': <built-in function           │ │
         │ │                __build_class__>,                                   │ │
         │ │                │   '__import__': <built-in function __import__>,   │ │
         │ │                │   'abs': <built-in function abs>,                 │ │
         │ │                │   'all': <built-in function all>,                 │ │
         │ │                │   'any': <built-in function any>,                 │ │
         │ │                │   ... +143                                        │ │
         │ │                }                                                   │ │
         │ │   __cached__ = 'D:\\AzurLaneAutoScript\\module\\base\\__pycache__… │ │
         │ │      __doc__ = None                                                │ │
         │ │     __file__ = 'D:\\AzurLaneAutoScript\\module\\base\\utils.py'    │ │
         │ │   __loader__ = <_frozen_importlib_external.SourceFileLoader object │ │
         │ │                at 0x000000FBECCC6FC8>                              │ │
         │ │     __name__ = 'module.base.utils'                                 │ │
         │ │  __package__ = 'module.base'                                       │ │
         │ │     __spec__ = ModuleSpec(name='module.base.utils',                │ │
         │ │                loader=<_frozen_importlib_external.SourceFileLoader │ │
         │ │                object at 0x000000FBECCC6FC8>,                      │ │
         │ │                origin='D:\\AzurLaneAutoScript\\module\\base\\util… │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\cv2\__init__.py:5 in   │
         │ <module>                                                               │
         │                                                                        │
         │    3 import sys                                                        │
         │    4                                                                   │
         │ ❱  5 from .cv2 import *                                                │
         │    6 from .data import *                                               │
         │    7                                                                   │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __builtins__ = {                                                   │ │
         │ │                │   '__name__': 'builtins',                         │ │
         │ │                │   '__doc__': 'Built-in functions, exceptions, and │ │
         │ │                other objects.\n\nNoteworthy: None is the `nil'+46, │ │
         │ │                │   '__package__': '',                              │ │
         │ │                │   '__loader__': <class                            │ │
         │ │                '_frozen_importlib.BuiltinImporter'>,               │ │
         │ │                │   '__spec__': ModuleSpec(name='builtins',         │ │
         │ │                loader=<class                                       │ │
         │ │                '_frozen_importlib.BuiltinImporter'>),              │ │
         │ │                │   '__build_class__': <built-in function           │ │
         │ │                __build_class__>,                                   │ │
         │ │                │   '__import__': <built-in function __import__>,   │ │
         │ │                │   'abs': <built-in function abs>,                 │ │
         │ │                │   'all': <built-in function all>,                 │ │
         │ │                │   'any': <built-in function any>,                 │ │
         │ │                │   ... +143                                        │ │
         │ │                }                                                   │ │
         │ │   __cached__ = 'D:\\AzurLaneAutoScript\\toolkit\\lib\\site-packag… │ │
         │ │      __doc__ = None                                                │ │
         │ │     __file__ = 'D:\\AzurLaneAutoScript\\toolkit\\lib\\site-packag… │ │
         │ │   __loader__ = <_frozen_importlib_external.SourceFileLoader object │ │
         │ │                at 0x000000FBECCEE0C8>                              │ │
         │ │     __name__ = 'cv2'                                               │ │
         │ │  __package__ = 'cv2'                                               │ │
         │ │     __path__ = [                                                   │ │
         │ │                │                                                   │ │
         │ │                'D:\\AzurLaneAutoScript\\toolkit\\lib\\site-packag… │ │
         │ │                ]                                                   │ │
         │ │     __spec__ = ModuleSpec(name='cv2',                              │ │
         │ │                loader=<_frozen_importlib_external.SourceFileLoader │ │
         │ │                object at 0x000000FBECCEE0C8>,                      │ │
         │ │                origin='D:\\AzurLaneAutoScript\\toolkit\\lib\\site… │ │
         │ │                submodule_search_locations=['D:\\AzurLaneAutoScrip… │ │
         │ │    importlib = <module 'importlib' from                            │ │
         │ │                'D:\\AzurLaneAutoScript\\toolkit\\lib\\importlib\\… │ │
         │ │           os = <module 'os' from                                   │ │
         │ │                'D:\\AzurLaneAutoScript\\toolkit\\lib\\os.py'>      │ │
         │ │          sys = <module 'sys' (built-in)>                           │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         ImportError: DLL load failed: %1 不是有效的 Win32 应用程序。

**Comment by LmeSzinc** [comment]
检查你电脑是不是 64 位的，Alas 只能在 64 位系统上运行

**Comment by Testplayers** [comment]
> 

服务器是X64 的winserver2012

**Comment by LmeSzinc** [comment]
#1142
