### ISSUE TITLE
科研队列实装后，科研项目是否考虑将强制打开变为可选打开？

### ISSUE THREAD

**Issue by SpringLantern** [LmeSzinc/AzurLaneAutoScript#1627]
### 你的功能请求是否与问题有关？

五期科研实装后，科研队列显著解决了减少了玩家们在科研中破坏的作息。
每个人的科研计划都不同，各自经历的阶段由于强制打开导致要频繁修改过滤器，是否有考虑过将科研项目的强制打开变为可选打开呢？

**Comment by LmeSzinc** [comment]
#1418
