### ISSUE TITLE
显示更新失败

### ISSUE THREAD

**Issue by chuanhezi** [LmeSzinc/AzurLaneAutoScript#1628]
启动后需要长时间加载，之后显示更新失败。重新启动无效
![1G5P$E 7MJU4@XISKY4TY}6](https://user-images.githubusercontent.com/108390112/189562404-0a2cb7cb-47d1-466d-985b-0f66515fe807.png)

**Comment by LmeSzinc** [comment]
阅读 [中文安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn)

**Comment by chuanhezi** [comment]
所以我需要在每次更新之后去修改吗。我在之前已经用了半年，最近才出现的这个问题

**Comment by LmeSzinc** [comment]
可能你一直都没有改过，靠好运气连的 github。按照安装教程把两个地址改一下就好了

**Comment by chuanhezi** [comment]
哦好
