### ISSUE TITLE
增加 MuMu 模拟器 App 多开的支持

### ISSUE THREAD

**Issue by Irido-nyto** [LmeSzinc/AzurLaneAutoScript#1635]
### 你的功能请求是否与问题有关？

MuMu 模拟器如果使用模拟器多开，多个 adb 会同时监听 7555 端口，导致 alas 无法正常工作。

### 解决方案

使用 MuMu 的 App 多开应该可以解决这个问题。根据 [MuMu 开发者手册](https://mumu.163.com/help/func/20190129/30131_797867.html) 的描述，在 2.2.2x86/x64 版本前的 App 多开是使用不同的包后缀名区分多开的 App，2.2.2x86/x64 版本后的 MuMu 模拟器是通过 UserId 来区分多开的 App。

按照 [这份文档](https://note.youdao.com/ynoteshare1/index.html?id=8bb0f335e90f16c37d66e84ac7d8bcb1&type=note) 的方案，应该可以为 adb 增加一个 `--user` 参数来操控不同的多开 App，实现对 MuMu 模拟器 App 多开。

**Comment by LmeSzinc** [comment]
MuMu 不支持多开，要多开不用 MuMu。这样说的不仅是 Alas，另外两家大的开源二次元手游脚本 [MaaAssistantArknights](https://github.com/MaaAssistantArknights/MaaAssistantArknights) 和 [ArknightsAutoHelper](https://github.com/ArknightsAutoHelper/ArknightsAutoHelper) 也是这样的，~他们甚至对 MuMu 没什么好感~

**Comment by Irido-nyto** [comment]
好的吧，那我考虑换个模拟器
