### ISSUE TITLE
最近突然更新失败

### ISSUE THREAD

**Issue by lllLllori** [LmeSzinc/AzurLaneAutoScript#1644]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

之前一直用的很好，突然有一次就打不开了，然后也按照安装教程做了还是不行

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![M 3 B
RUS%$8UVK{2QT}K](https://user-images.githubusercontent.com/101250945/190388697-99a3f508-05f9-4eba-97be-80dab900d4e9.png)

**Comment by lllLllori** [comment]
我用安装教程提供的那个gitee地址也是连接不上

**Comment by LmeSzinc** [comment]
检查你电脑上的代理软件，例如 uu 加速器，原神私服等，Alas 需要获取更新，但是被重定向到了 localhost:8080

**Comment by lllLllori** [comment]
> 检查你电脑上的代理软件，例如 uu 加速器，原神私服等，Alas 需要获取更新，但是被重定向到了 localhost:8080

请问我该如何检查呢 我现在把他们都卸载了还是不行 这个8080端口号怎么改回去呢？

**Comment by lllLllori** [comment]
我用Git更改了端口 已经解决问题了 感谢
