### ISSUE TITLE
Assets update for rapid training in tactical class

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1648]
### Is your feature request related to a problem?

Update assets `RAPID_TRAINING`, it must be one on the leftmost slot.

![image](https://user-images.githubusercontent.com/37934724/190478662-f4c7bacb-0676-453e-9ecd-7b85a44db757.png)

**Comment by appleapple802** [comment]
台服長一樣
![Screenshot_20220917-210532](https://user-images.githubusercontent.com/48844954/190862415-da558cea-135d-4fca-88ce-7164fabe3223.png)
