### ISSUE TITLE
不使用物资的科研循环卡死

### ISSUE THREAD

**Issue by n12z** [LmeSzinc/AzurLaneAutoScript#1661]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

科研里面设定不使用物资，当不能刷新且没有不使用物资的项目时，会无限循环科研队列和科研选项界面，程序进入死循环。这时只能手动选择一个消耗物资的项目，alas才能继续工作。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
> 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
