### ISSUE TITLE
希望加个失败时另一队打完或者撤退重打功能

### ISSUE THREAD

**Issue by SZCDSB** [LmeSzinc/AzurLaneAutoScript#1663]
### 你的功能请求是否与问题有关？

一旦作战失败整个脚本就会停下

### 解决方案

加个失败后换另一队打或者是撤退重打,实在不行就重开app去掉战斗任务继续做别的事

**Comment by LmeSzinc** [comment]
> 一旦作战失败整个脚本就会停下

不会。战斗有 3 分钟的超时，战斗超时会重启游戏，连续出错 3 次才会停下。如果连续出错 3 次的话通常是你队伍强度不足
