### ISSUE TITLE
Add WarArchive Crescendo of Polaris | 新增作戰檔案 激奏的Polaris

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1671]
### Is your feature request related to a problem?

https://azurlane.koumakan.jp/wiki/Crescendo_of_Polaris
https://wiki.biligame.com/blhx/%E4%BD%9C%E6%88%98%E6%A1%A3%E6%A1%88%E6%BF%80%E5%A5%8F%E7%9A%84Polaris%E5%85%B3%E5%8D%A1%E4%BF%A1%E6%81%AF
Please :)
關卡上好一段時間了，唯一可以刷外觀的作戰檔案的說......

### Describe the solution you'd like

SP1-5 fully support
就SP1到5，再次感謝

**Comment by LmeSzinc** [comment]
这个活动早于 2020.02 也就是我开始写 Alas 的时间，所以需要以全新地图的形式适配，不像其他档案有现成的地图文件只需要添加入口

**Comment by LmeSzinc** [comment]
#1729
