### ISSUE TITLE
活动图出击中，选择不自律寻敌而让alas寻敌，有概率出现寻敌错误

### ISSUE THREAD

**Issue by lbpdfs** [LmeSzinc/AzurLaneAutoScript#1674]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

具体表现为，地图更新完毕后，alas反复拖动镜头识别海图，但并不能选定敌舰目标，多次重复后判断出错退出海域，并停止该出击任务。

### 如何复现

目前出现情况为2次，没有总结出具体经验，只知道是在本次活动图出击过程中突然产生的。重启alas可修复该问题

### 预期行为

不再出现此异常问题，或提供缓解此问题出现可能的方案

### 相关 Logs

```Text
见下文附件
```

### 截图

无

### 还有别的吗？

[活动图，非自律寻敌模式，敌人识别错误.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9615731/default.zip)
此为今天发生于C2海域的log，最终我手动终止了该过程
[9.16 a1 两次.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9615768/9.16.a1.zip)
此为9.16于活动图a1海域出现，并进行了第二次尝试得到相同结果，没有人工打断。之后重启alas，该问题并未即时重现。

**Comment by lbpdfs** [comment]
新出现的问题，这回并没有滑动屏幕浏览海域，进入关卡，切换队伍后就反复刷下图log
![0099](https://user-images.githubusercontent.com/49297944/191573184-8260b117-3c16-4bd6-bbfe-a7d97eabc2dd.png)

**Comment by lbpdfs** [comment]
[1663847647367.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9625393/1663847647367.zip)
[1663845106464.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/9625395/1663845106464.zip)
又出现了，短时间2次，这是海图识别出问题了吗

**Comment by LmeSzinc** [comment]
群里已回复是真机运行但未开启 `去除图片色彩抖动`
