### ISSUE TITLE
2020.09 Plans

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#168]
Since most plans in 2020.06 have been finished, here list the plans of Alas in 2020.09.
If you have feature requests or have objections on some plans, you can comment here. Also, PRs are welcomed, if you finished one of this.
2020.06的大部分计划已经完成, 这里列出2020.09的开发计划.
如果你希望添加新的功能或者对一些计划有异议, 可以在下方评论. 同时, 如果你完成了其中的某项功能, 欢迎PR.

> **Note**
> Please avoid using logic like `sleep(2) > click(A) > sleep(2) > click(B)`, which makes bot slow and unreliable.
> Use logic like `wait_until_appear_than_click(A) > wait_until_appear_than_click(B)` instead. This makes bot run as fast as possible on good pc, and still reliable on slow pc.

## 2020.09 Plans

- [ ] **Daily shopping** Buy items in General Shop, Merit Shop, Build Exchange.
  - Support filter string like the one in research. For exmple:
    In general shop `Cube > AttackBookT3 > SupportBookT3 > OffenceBookT3 > 30000`.
    In merit shop `Cube > BulinGold > 15000 > BoxT4`
    In build exchange `Food20000 > Food10000 > Food > AttackBookT3 > SupportBookT3 > OffenceBookT3 > Research2DR > Research2PRY`
  - Allow digit filter, like `15000`, to preserve 15000 coins. If coins lower than 15000, stop buying.
  - Handle shop switcher position. If there's an on-going event, general shop switch will be in a different position. Provide a public method to switch.
  - Record last execute time in alas.ini, skip if already executed before next shop refresh.
  - Add this to reward and disabled by default.

- [x] **SOS maps**
  - Add maps from 3-5 to 10-5.
  - Boss spawn point in some maps are static, use map logics like `fleet_2_push_forward` and `clear_roadblocks` to avoid boss fleet get stuck by mob enemies
  - Able to use differnet fleets in differnet maps. For example, mob_fleet=3 and boss_fleet=4 in 3-5 to 8-5, mob_fleet=5 and boss_fleet=4 in 9-5 and 10-5.
  - Able to ignore spesfic maps, some people may not do 9-5 and 10-5 because high oil comsumption.
  - Run option: `once_per_day`, `wait_until_8_signals`
  - Standalone function to run SOS, and option to run SOS in daily.

- [x] **Dorm**
  - Zoom-out dorm and pick up loves and coins. This may only be able done by minitouch, because both adb and uiautomator2 don't support miltiple touches.
  - Standalone interval to check dorm, because it don't need to ckeck frequently.
  - Fill the foods, call OCR to detect.
  - Don't use template matching to detect which food is available, because the naval curry change from time to time. Unavailable food items have a white overlay, make good use of that.

- [ ] **Doc and wiki update**
  - Installation guide for ADT-V4.bat
  - Battle logic document. Including map info, camera control, fleet control, map logic.
  - Alas develop document. Including object detection, UI control, etc

- [ ] **Single fleet support**

  - Add setting `boss_fleet_switch`, options: `use_map_file_logic`, `use_one_fleet`, `switch_after_boss_appear`, `switch_after_5_battle`, `switch_after_6_battle`
  - Delete setting `FLEET_BOSS`.
  - Less effect existing map files as possible, so modify method `fleet_x` and `fleet_2_xxx` series method. They should do nothing if BOSS_FLEET_SWITCH != use_map_file_logic. Do fleet switching in a higher level method: module/campaign/campaign_base.py execute_a_battle.

- [ ] **Delete spare fleet** These settings are not functonal currently, and I no longer think this feature neccessary. Sheduling will be added in the future, which can do this.
  - Delete settings in GUI, config, ini, etc.

- [x] **~~HOMO_STORAGE for every maps~~** Cancelled
HOMO_STORAGE is a value that record the perspective on map. In current version, HOMO_STORAGE is calculated after the first time you enter a map. Calculation may get errors if too few grid lines. Hardcode this value in map config can avoid this.

  - Add HOMO_STORAGE config to all map files.
  - Add a dev_tool to auto update HOMO_STORAGE. Perspective on map may be changed sometimes because anti-bot purpose. Add an auto tool to receive map names we want to update, than enter map > update camera > update HOMO_STORAGE in map file > retreat > enter next map.

- [ ] **Rework find_current_fleet** find_current_fleet in module/map/fleet.py looks terrible after months of development. It sometimes unable to find both 2 fleets because the ammo icon is covered by another fleet, even it have fleet prediction logic and fall back method: find_fleets.

  - Predict missing fleets. use grid_coverd and SP (fleet spawn point).
  - If failed, find fleets in SP, predict missing again.
  - If failed, switch fleets to find fleets. because camera will focus to a fleet after fleet switching.
  - Sync attribute `fleet_x_location` in Fleet and attribute `is_fleet` in GridInfo objects in map.

- [ ] **Fix clear_potential_boss if MB (may_boss) blocked by mob enemies**

  - Brute clear roadblocks if MB blocked by mob enemies. This is a rare issue, need long time testing.
- [ ] **Delete clear_grids_for_faster** An logic only used in 7-2, can be done in other ways.

- [ ] **Try [Mumu Nebula](http://mumu.163.com/20200515/25905_880846.html)** Nebula is a new version of MumuPlayer still under testing. Some people said it's fast on slow pc. 

  - Try if it's fast. You need some tricks to install Azur Lane in Nebula, because it haven't support Azur Lane officially.
  - Find how to connect Nebula with ADB. `adb connect 127.0.0.1:7555` not working. Also not listed in `adb devices`.

**Comment by SaferSky** [comment]
12图超时练级考虑吗？

**Comment by LmeSzinc** [comment]
Cancel plan: HOMO_STORAGE for every maps
Recently found that, JP has different map size, so it's better to calculate perspective data in real time, instead of hardcoding it.
![CN_JP_72_diff](https://user-images.githubusercontent.com/37934724/93769167-05e81a80-fc4d-11ea-95b5-d6818e9f0436.png)

Known mechanism in JP, which is different to other servers:
1. After fleet switching, camera focus to another fleet, while in JP is about 0.75 grid higher than grid center ( #75 , 5bed370443c3f2857d9c0d0ce990d3270120ab35 )
2. In research page, it shows the name code of research projects, while in JP, it shows the name of research genre ( #174 )
3. JP has different map size.

**Comment by mickeystone** [comment]
hi, bro,

**Comment by mickeystone** [comment]
`Find how to connect Nebula with ADB. adb connect 127.0.0.1:7555 not working. Also not listed in adb devices.`

hi, bro, do you find any way to connect connect Nebula with ADB ?

**Comment by LmeSzinc** [comment]
> `Find how to connect Nebula with ADB. adb connect 127.0.0.1:7555 not working. Also not listed in adb devices.`
> 
> hi, bro, do you find any way to connect connect Nebula with ADB ?

No, mumu nebula doesn't have ADB. It has no difference to other emulators but requires our extra work, so there's no reason to spend time on it anymore
