### ISSUE TITLE
Receive Merit Rewards in Mail | 领取功勋奖励邮件

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1684]
### Is your feature request related to a problem?

如果一直用Alas打演习的话，那每个演习周期经常是有五星上将的，但是这些演习等级奖励是送到邮箱的，导致邮箱里全是垃圾邮件。希望增加功能每天领取这些演习奖励，只检测第一页的前三个就足够了。
If you keep ALAS doing exercises, you'll probably get Fleet Admiral at the end of each exercise season. However ranking rewards are send to mail resulting in spam in mail system. Hope to add feature to claim these ranking rewards everyday, scaning the first 3 mails at the first page woule be enough.

**Comment by nEEtdo0d** [comment]
A feature I hadn't realized would be good, guess I'm so use to doing this manually. I can undertake this if you don't mind, will refrain in relying on `confirm_timer`

Preferable check into dev, bugfix, or submit as a new branch PR?

**Comment by LmeSzinc** [comment]
> A feature I hadn't realized would be good, guess I'm so use to doing this manually. I can undertake this if you don't mind. Will refrain in relying on `confirm_timer`
> 
> Preferable check into dev, bugfix, or submit as a new branch PR? I would imagine not a few line changes.

On new branch first, merge into `dev` then.

**Comment by nEEtdo0d** [comment]
Close issue, merged to dev via #1719
