### ISSUE TITLE
每日委托倾向修改

### ISSUE THREAD

**Issue by snowly233** [LmeSzinc/AzurLaneAutoScript#1686]
### 你的功能请求是否与问题有关？

每日委托默认是优先级是长时间优先，比如钻石最高优先级，后续便是各种各样的物资杂乱排序
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> NightDrill-8 > NightDrill-7 > NightDrill-6
> ExtraDrill-0:20 > ExtraDrill-1 > ExtraDrill-2 > ExtraDrill-2:40 > ExtraDrill-3:20 > ExtraDrill-5:20
> Box-1 > Box-3 > Box-6
> DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3
> Major
> DailyChip > DailyResource
> UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
> Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
> NightOil > NightCube
> shortest

### 解决方案

刷紧急委托的缺魔方的老咸鱼们是不缺物资教材和盒子这种东西的，也就是说物资委托倾向是最低最低的，我们的期望大约是钻石＞魔方＞石油＞其他，而紧急委托是很容易刷出来的，也需要短时长高收益委托，即使在-刷紧急委托-防止紧急委托数量过多 选项勾上后，委托的排列优先级依旧无修改，因此希望在每日委托一栏将各项资源倾向可以修改，亦或是将短时长高收益的各项物资优先级修改教程写下

**Comment by snowly233** [comment]
尝试自己编写委托过滤器，但由于不清楚委托收益权重以及紧急委托时效性，本人编写的Gems+Cube+Oils（钻石+魔方+石油）委托过滤十分简陋，希望作者大大提供帮助

以下为我自行修改结果：将高于6小时的长时间夜间委托优先度调至极低，将钻头5:20提供心智的委托优先度调低，其余石油尽可能多的委托优先级摆在前面，但个人并不清楚所有委托的代号，因此并没有增加或删减
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3
> ExtraDrill-0:20 > ExtraDrill-1 > ExtraDrill-2 > ExtraDrill-2:40 > ExtraDrill-3:20 
> Box-6 > Box-3 > Box-1
> Major
> DailyChip > DailyResource
> Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
> NightOil > NightCube > shortest
> UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
> ExtraDrill-5:20 > NightDrill-8 > NightDrill-7 > NightDrill-6

**Comment by LmeSzinc** [comment]
过滤器文档在这里：https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn#%E5%A7%94%E6%89%98%E8%BF%87%E6%BB%A4%E5%99%A8

如果你是 7x24 刷委托的话就这么写，再配合 “防止委托数量过多” 的选项
```
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3
> Box-6 > Box-3 > Box-1
> DailyChip > DailyResource
> Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
> shortest
```
