### ISSUE TITLE
大世界的體力購買可以加一個次數的限制嗎

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1696]
### 你的功能请求是否与问题有关？

#1673 
跟主線不同限制實在是感覺不出到底買掉多少油

### 解决方案

像主線打圖一樣多個次數限制

**Comment by SaiCateDoan** [comment]
个人感觉挺有价值的，而且应该不难做，
但是我开的坑已经够多了，给你点个赞好了
