### ISSUE TITLE
大世界深渊海域和隐秘海域在月初开荒完成前先关闭

### ISSUE THREAD

**Issue by junbluedd** [LmeSzinc/AzurLaneAutoScript#1700]
### 你的功能请求是否与问题有关？

大世界深渊海域和隐秘海域按照上个月的配置在月初是默认运行的，但是在没开荒完成的情况下（没用5000石油）一来就打深渊海域不一定能打过，我手动设置了下一次任务运行时间延后几天可是不生效，还是会按照alas自己的时间照常运行 

### 解决方案

大世界深渊海域和隐秘海域设置成延后几天运行或者等月初开荒完成再运行

### 其他内容

无

**Comment by LmeSzinc** [comment]
已经是这样的了，你需要打开 `每月开荒` 的任务，开荒完了也不需要关闭
