### ISSUE TITLE
大世界每月开荒bug循环

### ISSUE THREAD

**Issue by yx134** [LmeSzinc/AzurLaneAutoScript#1701]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

大世界每月开荒不点击塞壬资源导致无法全海域压制，有些海域显示周边海域未压制，从而导致一直在地图上循环。塞壬资源如截图所示

### 截图

[https://img1.imgtp.com/2022/10/02/1mPQ0ZMP.png](url)

**Comment by LmeSzinc** [comment]
需要修改游戏内的设置：
<html>
<body>


大型作战设置 - 自律时自动提交道具 | 开
-- | --



</body>
</html>

完整游戏设置见 README
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">主界面 =&gt; 右下角：设置 =&gt; 左侧边栏：选项</p>

设置名称 | 值
-- | --
帧数设置 | 60帧
大型作战设置 - 减少TB引导 | 开
大型作战设置 - 自律时自动提交道具 | 开
大型作战设置 - 安全海域默认开启自律 | 关
剧情自动播放 | 开启
剧情自动播放速度调整 | 特快


</body>
</html>
