### ISSUE TITLE
傻瓜式安装法alas.bat选择手动设置serial却无法正确连接雷电模拟器4.0

### ISSUE THREAD

**Issue by NeuWings** [LmeSzinc/AzurLaneAutoScript#171]
运行环境雷电模拟器4.0.34出现,不过之前4.0.23时候也遇到了这个问题.
选择手动设置后设置Serial为emulator-5554,无法正确识别与连接.
情况见图,因为是配置页面就出现了,似乎并没有找到logs.
已更换雷电ADB为toolkit附带的ADB文件,GUI中设置界面正常,连接性测试大部分时候稳定,但时常出现USB连接相关错误.
![GUI设备设置](https://user-images.githubusercontent.com/26756868/91795735-06465480-ec51-11ea-9f77-ef4a58436c56.PNG)

![Bat设置截图](https://user-images.githubusercontent.com/26756868/91795561-8fa95700-ec50-11ea-99e8-867976866abd.PNG)

我觉得应该是个人问题?但是不知道如何解决,希望能寻求帮助.

**Comment by LmeSzinc** [comment]
打错字了, 是 `emulator-5554`

**Comment by LmeSzinc** [comment]
顺便讲一下雷电模拟器的反人类ADB连接:
1. 如果ADB服务未启动, 此时启动雷电模拟器, 雷电模拟器启动时启动了ADB服务, 那么serial是 `emulator-5554`
2. 如果ADB服务已经启动, 此时启动雷电模拟器, 雷电模拟器启动时自动连接ADB服务, 那么serial是 `127.0.0.1:5555`

**Comment by NeuWings** [comment]
啊这 丢人了,下次注意...
顺便这个连接方式也太反人类了...我再试试...
感谢帮助指正.
