### ISSUE TITLE
卡启动器，报错UnicodeDecodeError

### ISSUE THREAD

**Issue by 31415926loli** [LmeSzinc/AzurLaneAutoScript#1728]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

不知道出了什么问题，某次重启脚本后就无限卡启动器了，重启电脑无效。重装脚本第一次安装完毕后可以进脚本界面，重启脚本后继续卡启动器报错。

### 如何复现

不知道如何复现，也不知道是不是个例。

### 预期行为

能正常进脚本就行。

### 相关 Logs

```Text
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 606: illegal multibyte sequence
```

### 截图

![QQ截图20221015032114](https://user-images.githubusercontent.com/58452868/195926625-d6575d10-a4d9-42df-b9e0-04d828ce0eaa.jpg)

### 还有别的吗？

win11 22h2

**Comment by SaiCateDoan** [comment]
最好提供一下你使用的模拟器的名称

**Comment by SaiCateDoan** [comment]
所以我尝试修了一下，你现在可以正常使用了吗

**Comment by 31415926loli** [comment]
> 所以我尝试修了一下，你现在可以正常使用了吗

谢谢，已经ok了，辛苦了
