### ISSUE TITLE
主线图出击停止条件增加“物资超过X后停止”或“物资超过存储上限后停止”

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#1741]
### 你的功能请求是否与问题有关？

（可能是XY问题，见谅）
每周一购买免费礼包+领取每周任务后的4000+（2900）油被Alas连续地来打主线图了，导致物资溢出超过存储上限大约一半多；
我不想浪费小卖部的产出（这6900油本来可以被我用来缺物资的时候刷），但我也不希望每周手动修改主线图“石油低于X后停止“的值。

### 解决方案

主线图出击停止条件增加“物资超过X后停止”或“物资超过存储上限后停止”的项；主线图出击前检查物资量，大于指定值时（或大于存储上限时）推迟任务。

### 其他内容

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/45f14210830787151120af13f51580f5c155c139/module/campaign/run.py#L118-L143

我看了 #1509 的内容；但我感觉利用活动图物资下限设置达不到我的需求（毕竟要求是反的）

另外，此处的X（或物资最大值）与活动图物资下限不匹配时如何处理我还没想好……

**Comment by bookbug666** [comment]
#1509 其實初版是用你想要的邏輯建置的，就是物資達到X停止，~~但當時否決了~~
小賣部我只能說放長遠一點的話，達到60萬以前溢出的浪費可忽略
因為爆油假設你打13-4/14-4你倍率是7.多倍到8倍的，如果真有需要我可以重提PR

**Comment by bookbug666** [comment]
如果你要的是全時的物資控制，那抱歉現在的平衡器只能管活動圖的
而且最大值跟最小同時存在會變得有些奇怪，~~何況這有點重複勞動了~~

建議稍微計算下自己怎麼玩遊戲，以及到底希望Alas怎麼面對你的issue
不然 #1509 的XY問題可能又要再來一遍

**Comment by guoh064** [comment]
好吧，我计算了一下，确实物资想用总有办法可以消耗。
