### ISSUE TITLE
Mac 安装报错

### ISSUE THREAD

**Issue by lslvxy** [LmeSzinc/AzurLaneAutoScript#1750]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

conda 和python环境已经安装好了

执行pip install -r requirements.txt 报错如下

ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.0rc1 Requires-Python >=3.8; 1.22.0rc2 Requires-Python >=3.8; 1.22.0rc3 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 3.6.0 Requires-Python >=3.8; 3.6.0rc1 Requires-Python >=3.8; 3.6.0rc2 Requires-Python >=3.8; 3.6.1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: none)
ERROR: No matching distribution found for pywin32==301

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by lslvxy** [comment]
> 

也尝试过了，也是报错的

**Comment by lslvxy** [comment]
昨天Anaconda3自动升级了导致环境的问题，我把他又降级了，用requirements-in.txt 安装成功了，

**Comment by LmeSzinc** [comment]
requirements.txt 是给 windows 下安装用的，Alas 使用的库都很旧了，所以需要在里面固定所有库的版本号，里面有 windows only 的库。其他系统需要使用 requirements-in.txt，当然，mac 和 linux 更建议 docker 安装就是了。
