### ISSUE TITLE
[台服]如何轉活動圖

### ISSUE THREAD

**Issue by Evanto1258** [LmeSzinc/AzurLaneAutoScript#1753]
昨天剛開復刻活動圖 但發現不能手動選擇相對應的活動圖。是需要等更新嗎?
![image](https://user-images.githubusercontent.com/61620346/197117997-d951713e-2f22-4e3d-b6f0-47db41110fea.png)

**Comment by appleapple802** [comment]
#1754

**Comment by appleapple802** [comment]
#1758
