### ISSUE TITLE
更新失败然后打不开了

### ISSUE THREAD

**Issue by nxz999** [LmeSzinc/AzurLaneAutoScript#1756]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

昨天前天正常使用，今天更新后突然卡住打不开了。已检查了config/deploy没有错误，但是还是打不开。
重新下载新版仍然打不开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![TC04TIB6LGO~@LS%A964OF0](https://user-images.githubusercontent.com/102858704/197159334-235febbc-52cd-4fbc-b83d-9820b0119a81.png)

**Comment by NaNaisNaNa** [comment]
gitee的alas的界面打不开了

**Comment by Steven-Zhl** [comment]
对，之前修改的gitee仓库的链接无法从外部直接打开，但是从gitee作者界面是可以正常点开的....可以先换回GitHub

**Comment by LmeSzinc** [comment]
#1755
