### ISSUE TITLE
无法检测蓝叠模拟器ADB

### ISSUE THREAD

**Issue by Lunareo** [LmeSzinc/AzurLaneAutoScript#1763]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

先前一直使用夜神模拟器运行并多开，Alas一切正常。但是增加蓝叠模拟器后Alas似乎无法检测蓝叠的屏幕尺寸，既不报错也无其他作为；对Alas和蓝叠分别进行重启后，现在的问题变成了Alas无法检测到蓝叠模拟器

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

1.蓝叠模拟器ADB已开启
2.Alas正常连接到蓝叠模拟器

### 相关 Logs

```Text
INFO     11:05:18.434 │ <<< DETECT DEVICE >>>                                      
INFO     11:05:18.437 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     11:05:18.441 │ 127.0.0.1:52026  //此为夜神模拟器                                          
INFO     11:05:18.445 │ Connecting to local emulator, using host 192.168.56.1      
ERROR    11:05:18.450 │ AdbError: device 'emulator-5554' not found
```

### 截图

![Snipaste_2022-10-22_11-30-09](https://user-images.githubusercontent.com/52236921/197317350-96df302d-5acd-451a-9166-b7ef7563f07a.png)

### 还有别的吗？

使用模拟器:
1.夜神模拟器Android 7(64bit)(正常)
2.蓝叠模拟器Android 9(64bit)(疑似检测不到窗口尺寸或检测不到ADB)
3.全手动填写模拟器Serial

**Comment by LmeSzinc** [comment]
> AdbError: device 'emulator-5554' not found

在 serial 处填写蓝叠模拟器显示的 `127.0.0.1:5555`，而不是 `emulator-5554`
