### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by yanguyue** [LmeSzinc/AzurLaneAutoScript#1764]
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/LmeSzinc/AzurLaneAutoScript
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default

Last command: "C:/Users/alise/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
error_code: 128
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe

**Comment by Horizon101011** [comment]
#1755
