### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by linsnowmm** [LmeSzinc/AzurLaneAutoScript#1770]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

更新后无法打开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![1](https://user-images.githubusercontent.com/97744559/197429634-5af2aca5-c402-43af-81d5-51e8b1eabcd7.png)
![2](https://user-images.githubusercontent.com/97744559/197429710-4624add2-c229-4d1e-96fb-2499bb15a732.png)

**Comment by linsnowmm** [comment]
config\deploy.yaml中
 AutoUpdate: true改为false后
可以正常打开
但在应用内一直弹出更新提示，且无法更新

**Comment by LmeSzinc** [comment]
#1755
