### ISSUE TITLE
打不开alas，#1755#1756类似问题看过，修改无用

### ISSUE THREAD

**Issue by myyauean** [LmeSzinc/AzurLaneAutoScript#1773]
### 你的功能请求是否与问题有关？

打不开，error 128

### 解决方案

我修改过https://gitee.com/lmeszinc/azur-lane-auto-script-mirror

### 其他内容

![image](https://user-images.githubusercontent.com/87347694/197491821-505da33d-85b4-4e64-9345-95dc8f886260.png)

**Comment by myyauean** [comment]
"D:\AlasApp_0.3.7\AzurLaneAutoScript
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/AlasApp_0.3.7/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
==================== SET GIT REPOSITORY ====================
"D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: Enumerating objects: 45914, done.
remote: Counting objects: 100% (45914/45914), done.
remote: Compressing objects: 100% (11488/11488), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Rest of the configs are the same as default

Last command: "D:/AlasApp_0.3.7/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
error_code: 128
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe

**Comment by Creator-Wating** [comment]
我也有这样的报错，让我修改默认git路径，修改无用

**Comment by lulvyun** [comment]
config/deploy.yaml里修改这两处
Repository: 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror'
PypiMirror: 'https://pypi.tuna.tsinghua.edu.cn/simple'
