### ISSUE TITLE
关于 template.match 的问题

### ISSUE THREAD

**Issue by RuaBQ** [LmeSzinc/AzurLaneAutoScript#178]
我在写一个拆箱子的功能，在使用的时候遇到了一些问题。
我直接使用asserts/stats_basic 下的BoxT4.png 拷贝至 asserts/template 下并重命名为 TEMPLATE_BOX_T4 作为 Template ，但是 TEMPLATE_BOX_T4.match() 返回的结果却很糟糕。我调高 similarity 会使箱子不能正确识别出来， 调低后会导致很多别的东西也被认为是箱子
我已经正确划分了格子，可以保证每个传入的 area 都恰好是一个物品所占的空间（大小为 120*120 ）。

我想问一下 template  的正确使用方法是什么？我是不是应该吧箱子中间的 T3 作为识别的模板？
附上我的使用代码
```python
def Predict_Box_T3(self, area):
    image = self.relative_crop(area=area)
    return TEMPLATE_BOX_T4.match(image, similarity=0.27)

for i in self.grid:
    if self.Predict_Box_T3(i):
    Image.fromarray(self.relative_crop(area=i)).show()

```

**Comment by LmeSzinc** [comment]
1. 缩放 assets 图片，assets/stats_basic 下的图片是在掉落界面截取的，仓库界面的图片可能大小不一样。
2. 使用图片的部分作为模板，而不是整张去匹配。因为会有 NEW 和物品数量的干扰。现有的掉落统计 module/statistics/item.py 就是这样的。

**Comment by LmeSzinc** [comment]
`relative_crop` 是在有一点透视的海域地图中使用的，在游戏界面内不需要使用 (如果这个函数是现有的，不是你实现的话)
如果想要裁切特定区域的图片可以使用 `self.device.image.crop(area)`

**Comment by RuaBQ** [comment]
> 1. 缩放 assets 图片，assets/stats_basic 下的图片是在掉落界面截取的，仓库界面的图片可能大小不一样。
> 2. 使用图片的部分作为模板，而不是整张去匹配。因为会有 NEW 和物品数量的干扰。现有的掉落统计 module/statistics/item.py 就是这样的。

感谢。我通过截取箱子中间 “TX” 部分解决了识别问题
