### ISSUE TITLE
夜神模拟器不能正常的使用出击和共斗

### ISSUE THREAD

**Issue by zzlinbai** [LmeSzinc/AzurLaneAutoScript#1783]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

不能正常的使用出击和共斗

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

正常出击

### 截图

![Snipaste_2022-10-27_22-59-10](https://user-images.githubusercontent.com/116387135/198326540-d25dc455-a62a-45e9-ba79-810284575847.png)

**Comment by LmeSzinc** [comment]
共斗活动未更新，需要等待更新

**Comment by LmeSzinc** [comment]
#1784 ，更新了
