### ISSUE TITLE
共鬥的挑戰券UI變更有影響到Alas嗎

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1788]
### 你的功能请求是否与问题有关？

本次共鬥有修改特別挑戰券的剩餘並且多了一個勾選，但Alas更新的時候已經手動打完了
而朋友說alas沒幫他用券，我沒法復現所以來問其他社群用戶

**Comment by LmeSzinc** [comment]
现在挑战券不是弹窗，改成战斗准备界面打勾了，还没有做适配
