### ISSUE TITLE
是否可以在共斗任务中增加确认潜艇出击的选项

### ISSUE THREAD

**Issue by timedosentlie** [LmeSzinc/AzurLaneAutoScript#1794]
### 你的功能请求是否与问题有关？

现在的共斗活动在不使用潜艇的情况下油耗非常大，但是如果默认出击设置中没有勾选“潜艇自动出战”的话共斗任务将因为作战时间过长而失败

### 解决方案

在编队页面确认潜艇自动出击按钮的状态，在其状态不符合脚本设置时自动点击修正

**Comment by LmeSzinc** [comment]
共斗活动一般不上潜艇。另外呼叫潜艇也是要耗油的，导致收益降低，还没见到有哪个攻略是叫潜艇的。
