### ISSUE TITLE
一进入8-5潜艇图就报错 国服 蓝叠模拟器

### ISSUE THREAD

**Issue by Guosh2020** [LmeSzinc/AzurLaneAutoScript#1809]
**在提问之前...**

- [x]  我已经搜索了现有的 issues
- [x]  我在提问题之前至少花费了 5 分钟来思考和准备
- [x]  我已经阅读了 Wiki 中的 常见问题(FAQ)
- [x]  我正在使用最新版的 Alas

**描述你的问题**
ALAS运行到潜艇图时，一进图就卡住

**如何复现**
1将潜艇图添加入队列中
2启动Alas
3进图后卡死

**预期行为**
无

**相关 Logs**
─────────────────────────────────────── 8-5 ───────────────────────────────────────
INFO     09:53:09.463 │ 8-5                                                        
INFO     09:53:09.472 │ Expect emotion reduce: (10, 0)                             
INFO     09:53:09.526 │ Bind task {'Alas', 'Sos', 'General'}                       
INFO     09:53:09.538 │ Save config ./config\alas.json,                            
         Sos.Emotion.Fleet1Value=119,                                              
         Sos.Emotion.Fleet1Record=datetime.datetime(2022, 11, 3, 9, 53, 9),        
         Sos.Emotion.Fleet2Value=119,                                              
         Sos.Emotion.Fleet2Record=datetime.datetime(2022, 11, 3, 9, 53, 9)         
INFO     09:53:09.573 │ [Emotion fleet_1] 119                                      
INFO     09:53:09.579 │ [Emotion fleet_2] 119                                      
INFO     09:53:09.585 │ <<< ENTER MAP >>>                                          
INFO     09:53:09.665 │ Click ( 889,  339) @ 8-5                                   
INFO     09:53:10.778 │ [Map_clear_percentage] 0.0                                 
INFO     09:53:11.252 │ [Map_clear_percentage] 0.0                                 
INFO     09:53:11.761 │ [Map_clear_percentage] 0.0                                 
INFO     09:53:11.765 │ [MAP_CLEAR_ALL_THIS_TIME] 0                                
INFO     09:53:11.769 │ [Map_info] 0%,                                             
INFO     09:53:11.772 │ [StopCondition_MapAchievement] non_stop                    
INFO     09:53:11.799 │ No auto search option.                                     
INFO     09:53:11.804 │ Click (1008,  508) @ MAP_PREPARATION                       
INFO     09:53:12.907 │ Using fleet: [3, 4, 0]                                     
INFO     09:53:12.912 │ [Light_orange_line] 0                                      
INFO     09:53:12.917 │ Click (1139,  471) @ SUBMARINE_CLEAR                       
INFO     09:53:13.902 │ Click (1161,  329) @ FLEET_2_CLEAR                         
INFO     09:53:14.922 │ Click (1063,  212) @ FLEET_1_CHOOSE                        
INFO     09:53:15.932 │ Current selected: [3]                                      
INFO     09:53:15.936 │ Click (1074,  206) @ FLEET_1_CHOOSE                        
INFO     09:53:16.862 │ Click (1079,  325) @ FLEET_2_CHOOSE                        
INFO     09:53:17.804 │ Current selected: [3]                                      
INFO     09:53:17.807 │ Click (1135,  513) @ FLEET_2_BAR_INDEX_4                   
INFO     09:53:18.677 │ Click (1048,  614) @ FLEET_PREPARATION                     
INFO     09:53:24.293 │ Enemy searching appeared.                                  
INFO     09:53:24.993 │ No fleet lock option.                                      
INFO     09:53:24.997 │ <<< MAP INIT >>>                                           
INFO     09:53:25.002 │ Load map_data, has_loop=False, use_loop=False              
INFO     09:53:25.007 │ Load spawn_data, has_loop=False, use_loop=False            
INFO     09:53:25.011 │ grid_connection: wall=False, portal=False                  
INFO     09:53:25.018 │ Load mechanism, land_base=False, maze=False,               
         fortress=False, bouncing_enemy=False                                      
INFO     09:53:25.842 │           vanish_point: (  641, -1581)                     
INFO     09:53:25.846 │          distant_point: (-2089, -1581)                     
INFO     09:53:25.915 │ 0.262s      Horizontal: 7 (7 inner, 1 edge)                
INFO     09:53:25.921 │ Edges: /_\    Vertical: 9 (17 inner, 4 edge)               
INFO     09:53:25.927 │ [homo_storage] ((8, 6), [(240.861, 118.024), (1143.845,    
         118.024), (109.332, 676.129), (1308.887, 676.129)])                       
INFO     09:53:26.104 │            tile_center: 0.942 (good match)                 
INFO     09:53:26.151 │ 0.217s      edge_lines: 2 hori, 7 vert                     
INFO     09:53:26.157 │ Edges: /_\   homo_loca: ( 33, 132)                         
INFO     09:53:26.173 │            center_loca: (3, 3)                             
INFO     09:53:26.177 │       camera_corrected: A1 -> D5                           
INFO     09:53:26.183 │                 Camera: D5                                 
INFO     09:53:26.305 │ 0.116s         predict: 46                                 
INFO     09:53:26.309 │ -- -- -- -- -- -- -- --                                    
INFO     09:53:26.312 │ -- 3L -- -- Fl -- -- --                                    
INFO     09:53:26.315 │ -- -- -- -- -- -- -- --                                    
INFO     09:53:26.320 │ -- -- -- -- -- -- 2L --                                    
INFO     09:53:26.324 │ 3L -- -- -- FL 2L -- --                                    
INFO     09:53:26.328 │ .. -- -- -- -- -- -- ..                                    
INFO     09:53:26.331 │ Fleet set to 1                                             
INFO     09:53:26.355 │ Fleet: 1, fleet_current_index: 1                           
INFO     09:53:26.362 │ [Map_buff] double_line                                     
INFO     09:53:26.366 │ Skip strategy bar check.                                   
ERROR    09:53:26.376 │ ValueError: operands could not be broadcast together with  
         shapes (3,) (2,)                                                          
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ E:\AzurLaneAutoScript\alas.py:63 in run                                │
         │                                                                        │
         │    61 │   │   try:                                                     │
         │    62 │   │   │   self.device.screenshot()                             │
         │ ❱  63 │   │   │   self.__getattribute__(command)()                     │
         │    64 │   │   │   return True                                          │
         │    65 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ command = 'sos'                                                    │ │
         │ │       e = ValueError('operands could not be broadcast together     │ │
         │ │           with shapes (3,) (2,) ')                                 │ │
         │ │    self = <alas.AzurLaneAutoScript object at 0x000001F58D580908>   │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ E:\AzurLaneAutoScript\alas.py:252 in sos                               │
         │                                                                        │
         │   250 │   def sos(self):                                               │
         │   251 │   │   from module.sos.sos import CampaignSos                   │
         │ ❱ 252 │   │   CampaignSos(config=self.config, device=self.device).run( │
         │   253 │                                                                │
         │   254 │   def war_archives(self):                                      │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ CampaignSos = <class 'module.sos.sos.CampaignSos'>                 │ │
         │ │        self = <alas.AzurLaneAutoScript object at                   │ │
         │ │               0x000001F58D580908>                                  │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\sos\sos.py:208 in run                     │
         │                                                                        │
         │   206 │   │   │   │   name = f'campaign_{self.config.Sos_Chapter}_5'   │
         │   207 │   │   │   │   self.config.override(Campaign_Name=name)         │
         │ ❱ 208 │   │   │   │   super().run(name, folder=folder, mode=mode, tota │
         │   209 │   │   │   │   if self.run_count > 0:                           │
         │   210 │   │   │   │   │   continue                                     │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.sos.sos.CampaignSos'>                   │ │
         │ │    folder = 'campaign_sos'                                         │ │
         │ │      mode = 'normal'                                               │ │
         │ │      name = 'campaign_8_5'                                         │ │
         │ │    remain = 2                                                      │ │
         │ │      self = <module.sos.sos.CampaignSos object at                  │ │
         │ │             0x000001F59F95E688>                                    │ │
         │ │     total = 1                                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\campaign\run.py:250 in run                │
         │                                                                        │
         │   248 │   │   │   # Run                                                │
         │   249 │   │   │   try:                                                 │
         │ ❱ 250 │   │   │   │   self.campaign.run()                              │
         │   251 │   │   │   except ScriptEnd as e:                               │
         │   252 │   │   │   │   logger.hr('Script end')                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ folder = 'campaign_sos'                                            │ │
         │ │   mode = 'normal'                                                  │ │
         │ │   name = 'campaign_8_5'                                            │ │
         │ │   self = <module.sos.sos.CampaignSos object at 0x000001F59F95E688> │ │
         │ │  total = 1                                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\campaign\campaign_base.py:130 in run      │
         │                                                                        │
         │   128 │   │   if not self.map_is_auto_search:                          │
         │   129 │   │   │   self.handle_map_fleet_lock()                         │
         │ ❱ 130 │   │   │   self.map_init(self.MAP)                              │
         │   131 │   │   else:                                                    │
         │   132 │   │   │   self.map = self.MAP                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_sos.campaign_8_5.Campaign object at      │ │
         │ │        0x000001F5BFC5E5C8>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\map\fleet.py:811 in map_init              │
         │                                                                        │
         │    809 │   │   logger.hr('Map init')                                   │
         │    810 │   │   self.map_data_init(map_)                                │
         │ ❱  811 │   │   self.map_control_init()                                 │
         │    812 │                                                               │
         │    813 │   def map_data_init(self, map_):                              │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                  │ │
         │ │        0x000001F5BFA89348>                                         │ │
         │ │ self = <campaign.campaign_sos.campaign_8_5.Campaign object at      │ │
         │ │        0x000001F5BFC5E5C8>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\map\fleet.py:857 in map_control_init      │
         │                                                                        │
         │    855 │   │   self.handle_strategy(index=self.fleet_show_index)       │
         │    856 │   │   self.hp_reset()                                         │
         │ ❱  857 │   │   self.hp_get()                                           │
         │    858 │   │   self.lv_reset()                                         │
         │    859 │   │   self.lv_get()                                           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_sos.campaign_8_5.Campaign object at      │ │
         │ │        0x000001F5BFC5E5C8>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ E:\AzurLaneAutoScript\module\combat\hp_balancer.py:90 in hp_get        │
         │                                                                        │
         │    88 │   │   hp = [self._calculate_hp(button.area) for button in self │
         │    89 │   │   weight = to_list(self.config.HpControl_HpBalanceWeight)  │
         │ ❱  90 │   │   scout = np.array(hp[3:]) * np.array(weight) / np.max(wei │
         │    91 │   │                                                            │
         │    92 │   │   self.hp = hp[:3] + scout.tolist()                        │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │     hp = [                                                         │ │
         │ │          │   0.9848484848484849,                                   │ │
         │ │          │   0.0,                                                  │ │
         │ │          │   0.0,                                                  │ │
         │ │          │   0.9848484848484849,                                   │ │
         │ │          │   0.9848484848484849,                                   │ │
         │ │          │   0.0                                                   │ │
         │ │          ]                                                         │ │
         │ │   self = <campaign.campaign_sos.campaign_8_5.Campaign object at    │ │
         │ │          0x000001F5BFC5E5C8>                                       │ │
         │ │ weight = [1000, 800]                                               │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         ValueError: operands could not be broadcast together with shapes (3,) (2,)
WARNING  09:53:27.933 │ Saving error: ./log/error/1667440407933                    
INFO     09:53:28.344 │ No provider specified, skip sending    
                    
**截图**
![Screenshot_2022 11 03_10 17 43 953](https://user-images.githubusercontent.com/111166987/199636135-b126592a-aa80-46fc-8d3d-6728c9ec83db.png)

**还有别的吗？**
No response

**Comment by Guosh2020** [comment]
话说这个提问的模板在哪找啊？我从别人的帖子里把格式复制过来的，还不会调字体...

**Comment by LmeSzinc** [comment]
![image](https://user-images.githubusercontent.com/37934724/199648330-22c0cd94-2995-4b36-8736-8c57ba54466d.png)
![image](https://user-images.githubusercontent.com/37934724/199648404-033c044a-ee59-4c6a-8909-bcebfb3c82ca.png)

**Comment by Guosh2020** [comment]
> ![image](https://user-images.githubusercontent.com/37934724/199648330-22c0cd94-2995-4b36-8736-8c57ba54466d.png) ![image](https://user-images.githubusercontent.com/37934724/199648404-033c044a-ee59-4c6a-8909-bcebfb3c82ca.png)

好吧，我早上点进去怎么没有这个上报BUG界面...
那我需要重新再提交一遍问题吗？我这个问题应该怎么解决？

**Comment by LmeSzinc** [comment]
```
weight = [1000, 800]
```
血量控制 - 先锋血量权重需要有三个值。或者关闭血量平衡

**Comment by Guosh2020** [comment]
解决了，感谢！
