### ISSUE TITLE
关于有动画需要延迟一段时间才能判断图像的问题

### ISSUE THREAD

**Issue by RuaBQ** [LmeSzinc/AzurLaneAutoScript#181]
我正在写拆箱子的功能。
在点击拆箱子会返回两种结果：1是正常分解，此时因为有一个一个装备弹出来的动画，一般会停顿一段时间才可以判断。2时装备仓库满了，会专门弹出一个对话框。
我想问一下这种情况该如何判断呢。
~~最后球球进群~~

**Comment by LmeSzinc** [comment]
可以同时判断 popup_confirm 和 popup_cancel
所有申请我都点同意了，没收到你的加群申请
