### ISSUE TITLE
如何添加活动图

### ISSUE THREAD

**Issue by xzjjasper** [LmeSzinc/AzurLaneAutoScript#1814]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

尝试添加台服复刻活动，修改 /campaign/Readme.md 后，在alas根目录下打开 adb 输入`python -m dev_tools.event_extract` 提示 No module named dev_tools.event_extract。请问如何进行后续操作？

**Comment by LmeSzinc** [comment]
看一下开发文档
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/5.2.-Create-globe-Map
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/6.1.-GUI-Option
