### ISSUE TITLE
无法启动alas，一直卡在git init 和set git

### ISSUE THREAD

**Issue by zhenghuafeng1** [LmeSzinc/AzurLaneAutoScript#1818]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![image](https://user-images.githubusercontent.com/51359277/199856745-6af8ba2b-25cd-45ea-8f31-ca02e838514c.png)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
你进入了命令行的快速编辑模式，需要按 `ENTER` 继续执行
![image](https://user-images.githubusercontent.com/37934724/199866192-f24d27c4-f7d9-495f-98a2-159751d95e3f.png)
