### ISSUE TITLE
启动Alas时会导致已在运行的其他无关安卓模拟器卡死

### ISSUE THREAD

**Issue by Mo-Yuxi** [LmeSzinc/AzurLaneAutoScript#1836]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

本机现状：
已安装蓝mumu模拟器，内装有碧蓝航线，作为alas的目标控制模拟器
电脑上还安装有一个蓝叠国际版，内装有明日方舟
问题如标题

### 如何复现

当先启动蓝叠国际版并运行游戏后，双击alas.exe初始化时，出现问题。
问题现象为100%出现的蓝叠模拟器出现完全卡死、画面定格、无法继续正常运行，仅有关闭蓝叠模拟器重新启动后蓝叠模拟器才恢复正常

### 预期行为

alas内部已经设定正确并且两款模拟器的adb端口不同，按道理说并不会冲突

### 相关 Logs

```Text
Null
```

### 截图

Null

### 还有别的吗？

作为非受控目标的蓝叠模拟器内也存在一个ATX应用图标，已尝试在蓝叠模拟器内卸载，并未解决问题

**Comment by LmeSzinc** [comment]
更改蓝叠模拟器中的 `图形渲染器` 和 `界面渲染器` 选项，排列组合找出能用的组合

![2022-11-09_22-12-18_N1QsKqXq0z_1020_1022](https://user-images.githubusercontent.com/37934724/200853037-f24ccb55-9490-41aa-a350-1aa3801afcdd.png)

**Comment by Mo-Yuxi** [comment]
切换到兼容+DX模式之后问题解决，感谢
