### ISSUE TITLE
紧急委托任务可能会无法正常切换前排角色

### ISSUE THREAD

**Issue by YuetKany** [LmeSzinc/AzurLaneAutoScript#1838]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

进行“刷紧急委托”的任务时，在当前舰队心情归零后，有相当概率无法正常切换前排
由log以及截图中可以见到，进行切换时，有两名满足条件的舰娘（即满级0破 心情处于10-150之间 白鹰驱逐）
![筛选可突破白鹰白皮驱逐](https://user-images.githubusercontent.com/95143326/200928712-89cf95d9-9527-4614-bdc1-6ff085d31b34.jpg)
但最后日志中仍给出了更换前排失败的错误（Change vanguard ship failed, no DD in common rarity.    ）

之前使用该功能时并未出现相似问题

### 如何复现

1.进行“刷紧急委托”直至当前舰队心情耗尽
2. 控制满足条件的角色只含有已誓约角色 即有几率复现

### 预期行为

正常做出切换的行为
初步分析为无法正常识别已经誓约的角色的稀有度 而将其稀有度置为_”unknown“_，从而导致无法正确切换
![可能出现未正确识别错误的相关log](https://user-images.githubusercontent.com/95143326/200931118-1826310e-0d30-4daf-9426-680204e6b838.jpg)

另 对于部分较为简单的低耗可选择图，是否可以考虑解除部分筛选限制，或将限制条件变为手动可控；而非简单粗暴地限制为**满级白鹰**驱逐
在部分情况下需要使用皇家或其他阵营的驱逐 或 **暂时**并未满级的驱逐进行练级或刷取经验

### 相关 Logs

```Text
INFO     03:46:41.495 │ Setting DOCK options, sort='level', index='dd',            
         faction='eagle', rarity='common', extra='can_limit_break'                 
INFO     03:46:41.498 │ Click ( 854,  159) @ FILTER_INDEX_3_0                      
INFO     03:46:41.551 │ Click ( 507,  275) @ FILTER_FACTION_1_0                    
INFO     03:46:41.604 │ Click ( 508,  419) @ FILTER_RARITY_1_0                     
INFO     03:46:41.658 │ Click ( 970,  487) @ FILTER_EXTRA_4_0                      
INFO     03:46:41.827 │ Setting DOCK options, sort='level', index='dd',            
         faction='eagle', rarity='common', extra='can_limit_break'                 
INFO     03:46:42.076 │ <<< UI CLICK >>>                                           
INFO     03:46:42.078 │ Click ( 841,  625) @ DOCK_FILTER_CONFIRM                   
INFO     03:46:43.694 │ [Favourite_filter] off                                     
INFO     03:46:43.696 │ <<< FINDING VANGUARD >>>                                   
INFO     03:46:43.697 │ Limitaions set to {'level': (100, 100), 'emotion': (10,    
         150), 'rarity': 'common', 'fleet': 0, 'status': 'free'}                   
INFO     03:46:43.846 │ [DOCK_LEVEL_OCR 0.147s] [0, 82, 40, 41, 41, 41, 41, 70,    
         100, 100, 0, 0, 0, 0]                                                     
WARNING  03:46:43.937 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  03:46:43.940 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  03:46:43.942 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  03:46:43.944 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  03:46:43.945 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
INFO     03:46:43.947 │ [DOCK_EMOTION_OCR 0.100s] [0, 0, 150, 150, 150, 150, 150,  
         30, 119, 119, 0, 0, 0, 0]                                                 
INFO     03:46:43.992 │ Ship(rarity='unknown', level=0, emotion=0, fleet=0,        
         status='free', button=CARD_0_0)                                           
INFO     03:46:43.994 │ Ship(rarity='common', level=82, emotion=0, fleet=6,        
         status='free', button=CARD_1_0)                                           
INFO     03:46:43.996 │ Ship(rarity='common', level=40, emotion=150, fleet=0,      
         status='commission', button=CARD_2_0)                                     
INFO     03:46:43.999 │ Ship(rarity='common', level=41, emotion=150, fleet=0,      
         status='free', button=CARD_3_0)                                           
INFO     03:46:44.000 │ Ship(rarity='common', level=41, emotion=150, fleet=0,      
         status='free', button=CARD_4_0)                                           
INFO     03:46:44.003 │ Ship(rarity='common', level=41, emotion=150, fleet=0,      
         status='free', button=CARD_5_0)                                           
INFO     03:46:44.004 │ Ship(rarity='common', level=41, emotion=150, fleet=0,      
         status='free', button=CARD_6_0)                                           
INFO     03:46:44.007 │ Ship(rarity='common', level=70, emotion=30, fleet=0,       
         status='free', button=CARD_0_1)                                           
INFO     03:46:44.008 │ Ship(rarity='unknown', level=100, emotion=119, fleet=0,    
         status='free', button=CARD_1_1)                                           
INFO     03:46:44.010 │ Ship(rarity='unknown', level=100, emotion=119, fleet=0,    
         status='free', button=CARD_2_1)                                           
INFO     03:46:44.012 │ Ship(rarity='unknown', level=0, emotion=0, fleet=0,        
         status='free', button=CARD_3_1)                                           
INFO     03:46:44.015 │ Ship(rarity='unknown', level=0, emotion=0, fleet=0,        
         status='free', button=CARD_4_1)                                           
INFO     03:46:44.017 │ Ship(rarity='unknown', level=0, emotion=0, fleet=0,        
         status='free', button=CARD_5_1)                                           
INFO     03:46:44.019 │ Ship(rarity='unknown', level=0, emotion=0, fleet=0,        
         status='free', button=CARD_6_1)                                           
INFO     03:46:44.021 │ Change vanguard ship failed, no DD in common rarity.
```

**Comment by LmeSzinc** [comment]
已在 #1842 中修复

**Comment by YuetKany** [comment]
不进行稀有度识别虽不会出现unknown无法识别的情况 但是会因为被置None而导致依然无法成功识别

log如下：
INFO     22:39:08.582 │ [DOCK_EMOTION_OCR 0.091s] [0, 119, 0, 110, 150, 150, 150,  
         150, 150, 119, 0, 0, 0, 0]                                                
INFO     22:39:08.624 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_0_0)                                           
INFO     22:39:08.625 │ Ship(rarity=None, level=82, emotion=119, fleet=4,          
         status='free', button=CARD_1_0)                                           
**INFO     22:39:08.628 │ Ship(rarity=None, level=100, emotion=0, fleet=6,           
         status='free', button=CARD_2_0)                                           
INFO     22:39:08.630 │ Ship(rarity=None, level=100, emotion=110, fleet=5,         
         status='free', button=CARD_3_0)**                                           
INFO     22:39:08.633 │ Ship(rarity=None, level=41, emotion=150, fleet=0,          
         status='free', button=CARD_4_0)                                           
INFO     22:39:08.634 │ Ship(rarity=None, level=41, emotion=150, fleet=0,          
         status='free', button=CARD_5_0)                                           
INFO     22:39:08.636 │ Ship(rarity=None, level=41, emotion=150, fleet=0,          
         status='free', button=CARD_6_0)                                           
INFO     22:39:08.638 │ Ship(rarity=None, level=41, emotion=150, fleet=0,          
         status='free', button=CARD_0_1)                                           
INFO     22:39:08.641 │ Ship(rarity=None, level=41, emotion=150, fleet=0,          
         status='free', button=CARD_1_1)                                           
INFO     22:39:08.644 │ Ship(rarity=None, level=70, emotion=119, fleet=0,          
         status='free', button=CARD_2_1)                                           
INFO     22:39:08.646 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_3_1)                                           
INFO     22:39:08.647 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_4_1)                                           
INFO     22:39:08.649 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_5_1)                                           
INFO     22:39:08.650 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_6_1)                                           
INFO     22:39:08.652 │ Limitaions set to {'level': (100, 100), 'emotion': (10,    
         150), 'rarity': 'any', 'fleet': 0, 'status': 'free'}                      
INFO     22:39:08.790 │ [DOCK_LEVEL_OCR 0.136s] [0, 82, 100, 100, 41, 41, 41, 41,  
         41, 70, 0, 0, 0, 0]                                                       
WARNING  22:39:08.866 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  22:39:08.868 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  22:39:08.870 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  22:39:08.872 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
WARNING  22:39:08.874 │ OCR DOCK_EMOTION_OCR: Result "" is revised to "0"          
INFO     22:39:08.876 │ [DOCK_EMOTION_OCR 0.084s] [0, 119, 0, 110, 150, 150, 150,  
         150, 150, 119, 0, 0, 0, 0]                                                
**INFO     22:39:08.912 │ Change vanguard ship failed, no DD in common rarity.**       
INFO     22:39:08.914 │ <<< UI CLICK >>>                                           
INFO     22:39:08.917 │ Click (1136,   33) @ DOCK_FILTER                           
INFO     22:39:09.708 │ Setting DOCK options,                                      
INFO     22:39:09.711 │ Click ( 405,  152) @ FILTER_INDEX_0_0                      
INFO     22:39:09.764 │ Click ( 303,  295) @ FILTER_FACTION_0_0                    
INFO     22:39:09.818 │ Click ( 353,  424) @ FILTER_RARITY_0_0                     
INFO     22:39:09.870 │ Click ( 335,  487) @ FILTER_EXTRA_0_0                      
INFO     22:39:10.080 │ Setting DOCK options,                                      
INFO     22:39:10.316 │ Setting DOCK options, sort='level', index='all',           
         faction='all', rarity='all', extra='no_limit'
