### ISSUE TITLE
活动图功能无法选择活动名称为其他活动

### ISSUE THREAD

**Issue by Mo-Yuxi** [LmeSzinc/AzurLaneAutoScript#1841]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在活动-活动图-关卡设置-活动名称处的下拉菜单中无法选择其他活动

### 如何复现

1. 前往 '活动-活动图-关卡设置-活动名称'
2. 滑动到 下拉菜单
3. 问题出现——无法选择其他活动

### 预期行为

当前正是负象限活动复刻，试图选择使用先前负象限活动的活动关卡数据进行运行，但是无法选择这个活动，或者说整个下拉菜单均无法选择任何选项除了“紫绛槿岚”

### 相关 Logs

```Text
Null
```

### 截图

Null

### 还有别的吗？

Null

**Comment by snowly233** [comment]
等更新就行了

**Comment by LmeSzinc** [comment]
#1844
