### ISSUE TITLE
希望增加识别不同颜色的实验品募集

### ISSUE THREAD

**Issue by 10101abc** [LmeSzinc/AzurLaneAutoScript#1852]
### 你的功能请求是否与问题有关？

相同时长的实验品募集有不同的颜色，而在选择过滤时应该进行区分，目前的科研任务没有相关功能
![image](https://user-images.githubusercontent.com/31378390/201365224-407e389b-86b2-4312-a2b3-09be7dda84f1.png)

### 解决方案

在识别时对其进行区分，如项目代码、项目颜色。

### 其他内容

相关链接：碧蓝航线wiki，https://wiki.biligame.com/blhx/%E5%86%9B%E9%83%A8%E7%A0%94%E7%A9%B6%E5%AE%A4

**Comment by LmeSzinc** [comment]
你可以通过 `S5-E-315` 和 `S5-E-031` 进行选择

**Comment by 10101abc** [comment]
懂了😂
