### ISSUE TITLE
als取消数据收集科研，然后进行推图。但是这与我的初衷不符

### ISSUE THREAD

**Issue by Csgus** [LmeSzinc/AzurLaneAutoScript#1855]

**Comment by Horizon101011** [comment]
B系列科研会被alas主动取消，原因是：

1. 不能保证研究条件被完成
2. 基于1，没有完成前置无法加入队列，可能会出现阻塞导致后续无法进行
3. B系列的收益较低

如果你**手动选择**了B类科研，请**自行完成**前置并等待队列有空时**手动加入**。
