### ISSUE TITLE
关于默认委托模板的问题

### ISSUE THREAD

**Issue by VirtualTowel** [LmeSzinc/AzurLaneAutoScript#1861]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

这是默认委托模板：
```
DailyEvent
> Gem-8 > Gem-4 > Gem-2
> NightDrill-8 > NightDrill-7 > NightDrill-6
> ExtraDrill-0:20 > ExtraDrill-1 > ExtraDrill-2 > ExtraDrill-2:40 > ExtraDrill-3:20 > ExtraDrill-5:20
> Box-6 > Box-3 > Box-1
> DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3
> Major
> DailyChip > DailyResource
> UrgentBook-2:30 > UrgentBook-2 > UrgentBook-1:20 > UrgentBook-1:40
> Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00
> NightOil > NightCube
> shortest
```

其中：
`> DailyCube-0:30 > UrgentCube-1:30 > DailyCube-1:30 > UrgentCube-1:45 > UrgentCube-2:15 > UrgentCube-3`
一行中的DailyCube似乎并不存在，应该改成ExtraCube。

`> Daily-0:20 > Daily-0:30 > Daily-1:00 > Daily-1:30 > Daily-2:00`
这一行的所有项目都被上面的`> DailyChip > DailyResource`所覆盖，似乎应该将这行的Daily全部改成Extra？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by SaiCateDoan** [comment]
正确的，我还以为只有我知道默认委托过滤器全是问题
目前默认委托过滤器已经修改好，多种默认过滤器的框架也搭好了，但是委托收益模拟还没完成
看到这个issue我决定先把默认委托过滤器pr了

**Comment by SaiCateDoan** [comment]
有兴趣的话来写委托收益模拟啊

**Comment by VirtualTowel** [comment]
> 有兴趣的话来写委托收益模拟啊

okok，最近备考，考完有时间看看٩( 'ω' )و

**Comment by LmeSzinc** [comment]
#1194
