### ISSUE TITLE
在M1 Mac上运行无任何反应

### ISSUE THREAD

**Issue by vecStardo** [LmeSzinc/AzurLaneAutoScript#1873]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在部署之后点击调度器启动之后无任何反应，日志显示INFO     2022-11-15 19:55:59.623 │ End of log queue handler loop 

- 系统：MacOS 13.0(M1 Pro)
- 模拟器：android Emulator api28(android 9)
- python环境3.7.6

deploy.yaml内git路径、python路径、adb路径均已修改
在部署文件中提到的需要修改的connection.py文件内容第一处在connection-attar.py内找到并修改，第二处未找到。
依赖已更新，无不良报错，pip无更新提示
adb devices运行结果为 emulator-5554	device

在性能测试页面点击运行无任何反应，控制台日志输出为INFO     2022-11-15 19:55:59.623 │ End of log queue handler loop 。alas网页控制台无输出。左上角状态全程显示为闲置
在主页面点击运行日志输出在下文相关logs内贴出，左上角状态变化为发生错误

### 如何复现

1. 前往 '性能评估'或‘总览’
2. 点击 '运行'
4. 出现问题

### 相关 Logs

```Text
══════════════════════════════════════════
                  START                   
══════════════════════════════════════════
INFO     20:08:50.451 │ Start scheduler   
         loop: alas                       
INFO     20:08:50.456 │ [Server] cn       
INFO     20:08:50.471 │ Bind task {'Alas',
         'General'}                       
INFO     20:08:51.117 │ Server            
         "阿留申群岛" is available.       
INFO     20:08:51.121 │ Pending tasks:    
         ['Restart', 'Commission',        
         'Tactical', 'Research',          
         'Exercise', 'Dorm', 'Meowfficer',
         'Guild', 'Reward', 'Freebies',   
         'OpsiExplore', 'OpsiAshBeacon',  
         'OpsiDaily', 'OpsiAbyssal',      
         'OpsiStronghold', 'OpsiObscure', 
         'Daily', 'Hard', 'OpsiAshAssist',
         'EventSp', 'EventC', 'EventD',   
         'MaritimeEscort',                
         'OpsiMeowfficerFarming']         
INFO     20:08:51.125 │ [Task] Restart    
         (Enable, 2020-01-01 00:00:00)    
INFO     20:08:51.127 │ Bind task {'Alas',
         'Restart', 'General'}
```

**Comment by LmeSzinc** [comment]
需要提供当天的完整的 alas.txt 和 gui.txt

**Comment by LmeSzinc** [comment]
如果你是 arm 架构的 cpu，看群友的博客文章11111111111 https://www.binss.me/blog/run-azurlaneautoscript-on-arm64/

**Comment by vecStardo** [comment]
> 如果你是 arm 架构的 cpu，看群友的博客文章 https://www.binss.me/blog/run-azurlaneautoscript-on-arm64/

感谢，以按照该博客完成部署。
对后人进行一些查漏补缺

- 在创建android模拟器的时候默认的模拟器配置没有1280x720的需要选择new hardware porfile 填写分辨率之后在supported device states 中取消对portrait的勾选，否则即使手动横屏，alas进行点击的位置仍然是错误的。
- 如果挂在docker Mac的Library/目录是不能给docker访问的，fileshare了也不行。
- docker应用程序内的启动的容器内命令行无法启动这位群友配置的conda虚拟环境，需要自己从命令行链接进入容器

**Comment by Ding-Kyoma** [comment]
下面是我在arm mac python原生运行alas的方法

- 在mac上的docker部署alas十分的占用内存（4GB）。而在arm mac环境下仅占用200MB，并且cpu占用更低（<5%）
- conda环境`environment.yml`贴在下面，
    - 先安装`miniforge`(conda) 在mac上
    - `conda env create -f environment.yml` 创建相同的环境
    - `conda activate alas`激活环境，`cd`到alas项目后，`python gui.py`
    注：Python的版本为3.8.18 （conda不提供更加早的arm mac python版本了）。用anaconda channel安装arm mxnet=1.5.1 （不用自己编译了:)。已逐个解决包冲突问题，并测试了能正常稳定的运行
   
- 模拟器截图、控制都选ADB即可，省心。将`config/deploy.yaml`与`deploy/config.py`文件中git路径改成`/usr/bin/git`即可正常更新alas
- 模拟器Android Studio填`127.0.0.1:5555`即可

``` yaml
name: alas
channels:
  - anaconda
  - conda-forge
dependencies:
  - _mutex_mxnet=0.0.50=openblas
  - blas=1.0=openblas
  - brotli-python=1.0.9=py38hc377ac9_7
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.11.17=hf0a4a13_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2023.11.17=py38hca03da5_0
  - cffi=1.16.0=py38h80987f9_0
  - cryptography=41.0.3=py38hd4332d6_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - eigen=3.3.7=h525c30c_1
  - expat=2.5.0=h313beb8_0
  - fontconfig=2.14.1=h6b8db82_1
  - freetype=2.12.1=h1192e45_0
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h80987f9_3
  - glib=2.69.1=h514c7bf_2
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - icu=68.1=hc377ac9_0
  - jpeg=9e=h80987f9_1
  - krb5=1.20.1=hf3e1bf2_1
  - lerc=3.0=hc377ac9_0
  - libblas=3.9.0=20_osxarm64_openblas
  - libcblas=3.9.0=20_osxarm64_openblas
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=7.88.1=h3e2b118_2
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.8=h1a28f6b_5
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libiconv=1.16=h1a28f6b_2
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm14=14.0.6=h7ec7a93_3
  - libmxnet=1.5.1=openblas_h34268ac_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.39=h80987f9_0
  - libpq=12.15=h02f6b3c_1
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.10.0=h02f6b3c_2
  - libtiff=4.4.0=h2fd578a_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - libxml2=2.9.14=h8c5e841_0
  - libxslt=1.1.35=h9833966_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.6=hcd81f8e_0
  - lz4-c=1.9.4=h313beb8_0
  - mxnet=1.5.1=hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - ncurses=6.4=h463b476_2
  - opencv=4.6.0=py38h8794c10_2
  - openssl=3.2.0=h0d3ecfb_1
  - pcre=8.45=hc377ac9_0
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.40.0=h1a28f6b_0
  - py-mxnet=1.5.1=py38h3f2eb1c_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.18=h2469fbe_1_cpython
  - python_abi=3.8=4_cp38
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtwebkit=5.212=h0f11f3c_4
  - readline=8.2=h92ec313_1
  - requests=2.31.0=py38hca03da5_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.13=h5083fa2_1
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.2=h8574219_0
  - pip:
      - adbutils==0.11.0
      - aiofiles==23.2.1
      - alas-webapp==0.3.7.0
      - annotated-types==0.6.0
      - anyio==3.7.1
      - apkutils2==1.0.0
      - asgiref==3.7.2
      - async-generator==1.10
      - av==10.0.0
      - cached-property==1.5.2
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - cigam==0.0.3
      - click==8.1.7
      - cnocr==1.2.3
      - colorama==0.4.6
      - commonmark==0.9.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - exceptiongroup==1.2.0
      - filelock==3.13.1
      - fonttools==4.47.0
      - future==0.18.3
      - gevent==23.9.1
      - gluoncv==0.6.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httptools==0.6.1
      - idna==3.6
      - imageio==2.27.0
      - importlib-resources==6.1.1
      - inflection==0.5.1
      - jellyfish==0.11.2
      - kiwisolver==1.4.5
      - logzero==1.7.0
      - lxml==5.0.0
      - lz4==4.3.2
      - matplotlib==3.7.4
      - msgpack==1.0.7
      - numpy==1.24.4
      - onepush==1.3.0
      - opencv-python==4.9.0.80
      - packaging==20.9
      - pillow==10.1.0
      - portalocker==2.8.2
      - prettytable==2.2.1
      - progress==1.6
      - psutil==5.9.3
      - py==1.11.0
      - pycryptodome==3.19.1
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pyelftools==0.30
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pypresence==4.2.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-graphviz==0.8.4
      - pywebio==1.6.2
      - pyyaml==6.0.1
      - pyzmq==22.3.0
      - retry==0.9.2
      - retrying==1.3.4
      - rich==11.2.0
      - scipy==1.10.1
      - six==1.16.0
      - sniffio==1.3.0
      - starlette==0.14.2
      - tornado==6.4
      - tqdm==4.66.1
      - typing-extensions==4.9.0
      - ua-parser==0.18.0
      - uiautomator2==2.16.17
      - uiautomator2cache==0.3.0.1
      - urllib3==2.1.0
      - user-agents==2.2.0
      - uvicorn==0.17.6
      - uvloop==0.19.0
      - v==1
      - watchgod==0.8.2
      - wcwidth==0.2.12
      - websockets==12.0
      - whichcraft==0.6.1
      - wrapt==1.13.1
      - xmltodict==0.13.0
      - zerorpc==0.6.3
      - zipp==3.17.0
      - zope-event==5.0
      - zope-interface==6.1
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/alas
```

**Comment by whitebluepants** [comment]
> 下面是我在arm mac python原生运行alas的方法
> 
> * 在mac上的docker部署alas十分的占用内存，需要4GB左右。而在arm mac环境下仅占用200MB，并且cpu占用更低（<5%）
> * conda环境`environment.yml`贴在下面，
>   
>   * 先安装`miniforge`(conda) 在mac上
>   * `conda env create -f environment.yml` 创建相同的环境
>   * `conda activate alas`激活环境，`cd`到alas项目后，`python gui.py`
>     注：Python的版本为3.8.18 （conda不提供更加早的arm mac python版本了）。用anaconda channel安装arm mxnet=1.5.1 （不用自己编译了:)。已逐个解决包冲突问题，并测试了能正常稳定的运行
> * 模拟器截图、控制都选ADB即可，省心。将`config/deploy.yaml`与`deploy/config.py`文件中git路径改成`/usr/bin/git`即可正常更新alas
> * 模拟器Android Studio填`127.0.0.1:5555`即可
> 
> ```yaml
> name: alas
> channels:
>   - anaconda
>   - conda-forge
> dependencies:
>   - _mutex_mxnet=0.0.50=openblas
>   - blas=1.0=openblas
>   - brotli-python=1.0.9=py38hc377ac9_7
>   - bzip2=1.0.8=h93a5062_5
>   - c-ares=1.19.1=h80987f9_0
>   - ca-certificates=2023.11.17=hf0a4a13_0
>   - cairo=1.16.0=h302bd0f_5
>   - certifi=2023.11.17=py38hca03da5_0
>   - cffi=1.16.0=py38h80987f9_0
>   - cryptography=41.0.3=py38hd4332d6_0
>   - cyrus-sasl=2.1.28=h9131b1a_1
>   - eigen=3.3.7=h525c30c_1
>   - expat=2.5.0=h313beb8_0
>   - fontconfig=2.14.1=h6b8db82_1
>   - freetype=2.12.1=h1192e45_0
>   - gettext=0.21.0=h826f4ad_0
>   - giflib=5.2.1=h80987f9_3
>   - glib=2.69.1=h514c7bf_2
>   - graphite2=1.3.14=hc377ac9_1
>   - gst-plugins-base=1.14.1=h313beb8_1
>   - gstreamer=1.14.1=h80987f9_1
>   - harfbuzz=4.3.0=he9eebac_1
>   - hdf5=1.12.1=h05c076b_3
>   - icu=68.1=hc377ac9_0
>   - jpeg=9e=h80987f9_1
>   - krb5=1.20.1=hf3e1bf2_1
>   - lerc=3.0=hc377ac9_0
>   - libblas=3.9.0=20_osxarm64_openblas
>   - libcblas=3.9.0=20_osxarm64_openblas
>   - libclang=14.0.6=default_h1b80db6_1
>   - libclang13=14.0.6=default_h24352ff_1
>   - libcurl=7.88.1=h3e2b118_2
>   - libcxx=16.0.6=h4653b0c_0
>   - libdeflate=1.8=h1a28f6b_5
>   - libedit=3.1.20221030=h80987f9_0
>   - libev=4.33=h1a28f6b_1
>   - libffi=3.4.2=h3422bc3_5
>   - libgfortran=5.0.0=13_2_0_hd922786_1
>   - libgfortran5=13.2.0=hf226fd6_1
>   - libiconv=1.16=h1a28f6b_2
>   - liblapack=3.9.0=20_osxarm64_openblas
>   - libllvm14=14.0.6=h7ec7a93_3
>   - libmxnet=1.5.1=openblas_h34268ac_0
>   - libnghttp2=1.57.0=h62f6fdd_0
>   - libopenblas=0.3.25=openmp_h6c19121_0
>   - libpng=1.6.39=h80987f9_0
>   - libpq=12.15=h02f6b3c_1
>   - libsqlite=3.44.2=h091b4b1_0
>   - libssh2=1.10.0=h02f6b3c_2
>   - libtiff=4.4.0=h2fd578a_2
>   - libwebp=1.2.4=ha3663a8_1
>   - libwebp-base=1.2.4=h80987f9_1
>   - libxml2=2.9.14=h8c5e841_0
>   - libxslt=1.1.35=h9833966_0
>   - libzlib=1.2.13=h53f4e23_5
>   - llvm-openmp=17.0.6=hcd81f8e_0
>   - lz4-c=1.9.4=h313beb8_0
>   - mxnet=1.5.1=hca03da5_0
>   - mysql=5.7.24=ha71a6ea_2
>   - ncurses=6.4=h463b476_2
>   - opencv=4.6.0=py38h8794c10_2
>   - openssl=3.2.0=h0d3ecfb_1
>   - pcre=8.45=hc377ac9_0
>   - pip=23.3.2=pyhd8ed1ab_0
>   - pixman=0.40.0=h1a28f6b_0
>   - py-mxnet=1.5.1=py38h3f2eb1c_0
>   - pycparser=2.21=pyhd3eb1b0_0
>   - pyopenssl=23.2.0=py38hca03da5_0
>   - pysocks=1.7.1=py38hca03da5_0
>   - python=3.8.18=h2469fbe_1_cpython
>   - python_abi=3.8=4_cp38
>   - qt-main=5.15.2=h9b4df51_9
>   - qt-webengine=5.15.9=h2903aaf_7
>   - qtwebkit=5.212=h0f11f3c_4
>   - readline=8.2=h92ec313_1
>   - requests=2.31.0=py38hca03da5_0
>   - setuptools=68.2.2=pyhd8ed1ab_0
>   - sqlite=3.41.2=h80987f9_0
>   - tk=8.6.13=h5083fa2_1
>   - wheel=0.42.0=pyhd8ed1ab_0
>   - xz=5.2.6=h57fd34a_0
>   - zlib=1.2.13=h53f4e23_5
>   - zstd=1.5.2=h8574219_0
>   - pip:
>       - adbutils==0.11.0
>       - aiofiles==23.2.1
>       - alas-webapp==0.3.7.0
>       - annotated-types==0.6.0
>       - anyio==3.7.1
>       - apkutils2==1.0.0
>       - asgiref==3.7.2
>       - async-generator==1.10
>       - av==10.0.0
>       - cached-property==1.5.2
>       - chardet==5.2.0
>       - charset-normalizer==3.3.2
>       - cigam==0.0.3
>       - click==8.1.7
>       - cnocr==1.2.3
>       - colorama==0.4.6
>       - commonmark==0.9.1
>       - contourpy==1.1.1
>       - cycler==0.12.1
>       - decorator==5.1.1
>       - deprecated==1.2.14
>       - deprecation==2.1.0
>       - exceptiongroup==1.2.0
>       - filelock==3.13.1
>       - fonttools==4.47.0
>       - future==0.18.3
>       - gevent==23.9.1
>       - gluoncv==0.6.0
>       - greenlet==3.0.3
>       - h11==0.14.0
>       - httptools==0.6.1
>       - idna==3.6
>       - imageio==2.27.0
>       - importlib-resources==6.1.1
>       - inflection==0.5.1
>       - jellyfish==0.11.2
>       - kiwisolver==1.4.5
>       - logzero==1.7.0
>       - lxml==5.0.0
>       - lz4==4.3.2
>       - matplotlib==3.7.4
>       - msgpack==1.0.7
>       - numpy==1.24.4
>       - onepush==1.3.0
>       - opencv-python==4.9.0.80
>       - packaging==20.9
>       - pillow==10.1.0
>       - portalocker==2.8.2
>       - prettytable==2.2.1
>       - progress==1.6
>       - psutil==5.9.3
>       - py==1.11.0
>       - pycryptodome==3.19.1
>       - pydantic==2.5.3
>       - pydantic-core==2.14.6
>       - pyelftools==0.30
>       - pygments==2.17.2
>       - pyparsing==3.1.1
>       - pypresence==4.2.1
>       - python-dateutil==2.8.2
>       - python-dotenv==1.0.0
>       - python-graphviz==0.8.4
>       - pywebio==1.6.2
>       - pyyaml==6.0.1
>       - pyzmq==22.3.0
>       - retry==0.9.2
>       - retrying==1.3.4
>       - rich==11.2.0
>       - scipy==1.10.1
>       - six==1.16.0
>       - sniffio==1.3.0
>       - starlette==0.14.2
>       - tornado==6.4
>       - tqdm==4.66.1
>       - typing-extensions==4.9.0
>       - ua-parser==0.18.0
>       - uiautomator2==2.16.17
>       - uiautomator2cache==0.3.0.1
>       - urllib3==2.1.0
>       - user-agents==2.2.0
>       - uvicorn==0.17.6
>       - uvloop==0.19.0
>       - v==1
>       - watchgod==0.8.2
>       - wcwidth==0.2.12
>       - websockets==12.0
>       - whichcraft==0.6.1
>       - wrapt==1.13.1
>       - xmltodict==0.13.0
>       - zerorpc==0.6.3
>       - zipp==3.17.0
>       - zope-event==5.0
>       - zope-interface==6.1
> prefix: /opt/homebrew/Caskroom/miniforge/base/envs/alas
> ```

想请教下，为什么我直接使用这个配置去创建环境会失败呢。 提示
ERROR: Could not find a version that satisfies the requirement python-graphviz==0.8.4 (from versions: none)
ERROR: No matching distribution found for python-graphviz==0.8.4

这里说python版本要3.8.18，应该说的是配置里的python版本，跟系统安装的有关吗（系统上的3.10）
❯ conda --version
conda 24.1.2

**Comment by whitebluepants** [comment]
@Ding-Kyoma 大佬，想再请教下环境搭建的细节。会不会还需要什么依赖、版本的限制？
我想着先注释掉graphviz，把其他安装完再单独弄这个
结果发现其他依赖也有安装问题

**Comment by Ding-Kyoma** [comment]
@whitebluepants 
刚刚更新了environment.yml，之前的好像有问题。安装好后alas env 后再用conda装下lxml（见步骤）。
环境搭建只要安装miniforge就可以了，依赖都在environment.yml里。
我现在已经不用arm mac跑alas了，更新后的environment.yml现在可以跑gui了，但运行起来是否还有问题我现在不清楚。

**Comment by SakuraToErii** [comment]
> 下面是我在arm mac python原生运行alas的方法 (内存、cpu占用更少)
> 
> * 创建conda环境文件`environment-arm-mac.yml`贴在下面，
>   
>   * 先安装 [`miniforge`](https://github.com/conda-forge/miniforge) 或者`conda`在mac上
>   * `conda env create -f environment-arm-mac.yml` 创建相同的环境
>   * `conda activate alas`激活环境，`cd`到alas项目后，`python gui.py`
>     注：Python的版本为3.8.18 （conda不提供更加早的arm mac python版本了）。conda 有编译好的原生arm mxnet=1.5.1 可以使用。已逐个解决包冲突问题，并测试了能正常稳定的运行 :)
> * 模拟器截图、控制都选ADB即可，省心。将`config/deploy.yaml`与`deploy/config.py`文件中git路径改成`/usr/bin/git`即可正常更新alas
> * 模拟器可以使用mumu pro，体验非常好
> 

大佬，你的 mumu 版本是多少，我的 mumu 只要python -m uiautomator2 init 过，装了小黄车 atx 以后就启动不了了

**Comment by Ding-Kyoma** [comment]
> > 下面是我在arm mac python原生运行alas的方法 (内存、cpu占用更少)
> > 
> > * 创建conda环境文件`environment-arm-mac.yml`贴在下面，
> >   
> >   * 先安装 [`miniforge`](https://github.com/conda-forge/miniforge) 或者`conda`在mac上
> >   * `conda env create -f environment-arm-mac.yml` 创建相同的环境
> >   * `conda activate alas`激活环境，`cd`到alas项目后，`python gui.py`
> >     注：Python的版本为3.8.18 （conda不提供更加早的arm mac python版本了）。conda 有编译好的原生arm mxnet=1.5.1 可以使用。已逐个解决包冲突问题，并测试了能正常稳定的运行 :)
> > * 模拟器截图、控制都选ADB即可，省心。将`config/deploy.yaml`与`deploy/config.py`文件中git路径改成`/usr/bin/git`即可正常更新alas
> > * 模拟器可以使用mumu pro，体验非常好
> 
> 大佬，你的 mumu 版本是多少，我的 mumu 只要python -m uiautomator2 init 过，装了小黄车 atx 以后就启动不了了

v1.4.11

**Comment by SakuraToErii** [comment]
> > > 下面是我在arm mac python原生运行alas的方法 (内存、cpu占用更少)
> > > 
> > > * 创建conda环境文件`environment-arm-mac.yml`贴在下面，
> > >   
> > >   * 先安装 [`miniforge`](https://github.com/conda-forge/miniforge) 或者`conda`在mac上
> > >   * `conda env create -f environment-arm-mac.yml` 创建相同的环境
> > >   * `conda activate alas`激活环境，`cd`到alas项目后，`python gui.py`
> > >     注：Python的版本为3.8.18 （conda不提供更加早的arm mac python版本了）。conda 有编译好的原生arm mxnet=1.5.1 可以使用。已逐个解决包冲突问题，并测试了能正常稳定的运行 :)
> > > * 模拟器截图、控制都选ADB即可，省心。将`config/deploy.yaml`与`deploy/config.py`文件中git路径改成`/usr/bin/git`即可正常更新alas
> > > * 模拟器可以使用mumu pro，体验非常好
> > 
> > 
> > 大佬，你的 mumu 版本是多少，我的 mumu 只要python -m uiautomator2 init 过，装了小黄车 atx 以后就启动不了了
> 
> v1.4.11

我的也是 1.4.11，好奇怪啊。每次只要python -m uiautomator2 init 过，装了小黄车以后就启动不了了，除非新建一个容器，我能够确认是这个问题，做了对比实验。请问您方便“传递”一下您的安装包吗，仅供学习（滑稽），我想试试看可以吗？

**Comment by swordfeng** [comment]
M-series的朋友们，试试我的傻瓜包吧：https://github.com/swordfeng/alas-launcher

**Comment by SakuraToErii** [comment]
> M-series的朋友们，试试我的傻瓜包吧：https://github.com/swordfeng/alas-launcher

好的好的，谢谢佬，我后面用蓝叠跑起来了，能正常使用。现在试试你的
