### ISSUE TITLE
潛艇功能優化BOSS出擊

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1883]
### 你的功能请求是否与问题有关？

現行沒法同時使用狩獵跟BOSS出擊，但事實上如果隊伍中有U522/達芬奇的話是會出現次數尚有但ALAS不在BOSS戰召喚的情況
(事實上要是你有U556專武跟另一個道具把支援範圍等級拉滿也能做到)

### 解决方案

能否偵測BOSS戰是否可點擊召喚，就可以讓狩獵+支援同時存在了
畢竟非全自動的狀態下，BOSS戰ALAS是可以點擊潛艇的

**Comment by LmeSzinc** [comment]
可以尝试添加 `狩猎+boss战召唤` 的选项

**Comment by bookbug666** [comment]
可是我沒看懂怎麼實現，本來想仿造僅boss出擊
但我在combat/submarine.py只看到不出擊跟僅狩獵
