### ISSUE TITLE
经常报错无法继续进行

### ISSUE THREAD

**Issue by 203216705** [LmeSzinc/AzurLaneAutoScript#1887]
每天晚上12点，无法重启，然后就报错

**Comment by LmeSzinc** [comment]
> 如何上报bug How to Report Bugs
> 
> 在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。
> 

> 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
