### ISSUE TITLE
Bug（fork bomb）

### ISSUE THREAD

**Issue by Buenty** [LmeSzinc/AzurLaneAutoScript#1888]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [ ] 我正在使用最新版的 Alas

### 描述你的问题

![20221121165249](https://user-images.githubusercontent.com/93589744/203006792-dfb1c918-80bf-4f6c-9c19-e2409058f547.png)
1.运行Alas.exe,弹出如上图片。
2.发现BUG（fork bomb）
3.在网上查阅资料，发现fork bomb可能是病毒，于是通过联想电脑管家查杀，然而没有显示异常。
![20221121165831](https://user-images.githubusercontent.com/93589744/203008042-b36db646-15f6-44f9-8e2b-c361bbc4d976.png)
4.开始懵逼
5.纯小白希望大佬别嫌我菜

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LostMyMind** [comment]
你重新下个包试试？我咋感觉你这是缺文件了

**Comment by SaiCateDoan** [comment]
网上遇到这个问题的人非常少，但是他们都通过重新安装git解决了
对alas来说，我的建议是重新下载最新的alas，
[https://github.com/LmeSzinc/AzurLaneAutoScript/releases/download/v2022.10.24/AlasApp_0.3.8_cn.7z](url)
然后看看还会不会发生这个问题

**Comment by SaiCateDoan** [comment]
补充：我注意到你使用了自己的git而非alas内置的，你也可以尝试使用alas内置的git，或者检查你自己的git是否存在问题

**Comment by Buenty** [comment]
> 补充：我注意到你使用了自己的git而非alas内置的，你也可以尝试使用alas内置的git，或者检查你自己的git是否存在问题

谢谢，通过alas内置的git已经可以重新使用
