### ISSUE TITLE
无法打开alas

### ISSUE THREAD

**Issue by yibanluguodebaipiaoguai** [LmeSzinc/AzurLaneAutoScript#1898]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在之前的一次意外关机后alas就一直无法打开，在尝试重装之后只有第一次可以使用，之后依旧无法打开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![Alas Updater 2022_11_24 17_39_06](https://user-images.githubusercontent.com/111331381/203750032-04a96d72-3f06-4ca4-9913-8fdf9a16c7fc.png)
![Alas Updater 2022_11_24 17_38_56](https://user-images.githubusercontent.com/111331381/203750068-2d4750de-bb20-4333-84a6-2ea4e7badd46.png)

**Comment by LmeSzinc** [comment]
在 `C:\Users\{你的用户名}\AppData\Local\Temp` 下搜索 `dicts.dat` ，把搜索到的全部删掉，然后应该就好了
我的这个文件是在 `C:\Users\LmeSzinc\AppData\Local\Temp\gen_py\3.7\dicts.dat`
