### ISSUE TITLE
活动图运行过程会违背设置的周回模式、自律寻敌等强行切成手动

### ISSUE THREAD

**Issue by PkuRinko** [LmeSzinc/AzurLaneAutoScript#1903]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

本次更新后运行活动图会违背设置的周回模式、自律寻敌强行切成手动，同时设置好的1队道中会变成1队全清。观察运行过程和日志发现，这个问题产生的原因是在设置好周回模式、自律寻敌的前提下，进入关卡时程序仍然将自律寻敌的选项取消。同时切换队伍时程序会先点击清除2队再选择设置好的队伍，这样会导致队伍职能被重置为1队全清2队待机。个人认为开发者可能是为了手动捡素材而强制手动寻敌，但本次活动自律模式会自动捡素材。烦请开发者将这一问题修正。

另外还发现本次更新后设置好每一战召唤潜艇后进入关卡程序不会召唤潜艇，这一问题暂时没有找到原因，烦请开发者留意

### 如何复现

1. 设置好活动图周回模式、自律寻敌
2. 点击启动

**Comment by PkuRinko** [comment]
补充：在按照以上设置以周回模式进入关卡后，程序仍然按照设置的非周回模式步长移动舰队

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/efb13b3106e62e10397f8fe0d2f5cea323922699
TH图没有关卡进度没有三星，需要用脏代码绕过现有的地图状态检查
一般地图里自律寻敌需要周回模式，周回模式需要100%通关
