### ISSUE TITLE
活动图的任务数量有点少

### ISSUE THREAD

**Issue by PkuRinko** [LmeSzinc/AzurLaneAutoScript#1907]
### 你的功能请求是否与问题有关？

活动图除了每日关卡之外只有两个任务循环，类似当期的活动有5个关卡要周回的就不够了，能不能多增加几个循环窗口？

**Comment by mm770912** [comment]
其實你就設定五次就好了

**Comment by bookbug666** [comment]
> 其實你就設定五次就好了

其實問題不在那，如果你設定ABCD都是TH1-5那一天就是TH1-5各打4次而已
而任務貌似要求你要打10次來著

複製貼上5次沒有達到這個目標
