### ISSUE TITLE
请求添加一个心情控制相关的模块

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#1912]
### 你的功能请求是否与问题有关？

当检测到多个任务中均存在相同编号的舰队，则所有任务同步修改该编号舰队的心情值

我不太清楚Alas是否存在这样的模块，所以就先提一个issues，谢谢大佬

**Comment by snowly233** [comment]
同时2个任务存在相同编号的舰队心情判断会出大问题，没多久就报错了。。。我觉得可以修一下

**Comment by LmeSzinc** [comment]
多任务之间不可以共享同一角色
