### ISSUE TITLE
莱莎活动采集图设置自律无效

### ISSUE THREAD

**Issue by EnormousLegendaryFish** [LmeSzinc/AzurLaneAutoScript#1916]
在Alas里设置已开启自律，但是每次进图都把自律关闭。虽然还是不需要自己手动操作，但是效率很慢

**Comment by LmeSzinc** [comment]
请使用模板发起 issue
![image](https://user-images.githubusercontent.com/37934724/204106351-579ef649-4499-4c67-bcb8-821682e459c3.png)
