### ISSUE TITLE
登录时可能因为网络情况不佳造成卡住不运行

### ISSUE THREAD

**Issue by kotoricon** [LmeSzinc/AzurLaneAutoScript#1917]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

外服登录时可能会因为卡连接或者连接不上服务器时卡住不动多重复几次后就把脚本自动停止了，而且脚本也不会自动重启

### 截图

每次出现这个框的时候必定停止脚本不会自动重启，仅能手动登录进游戏重新开始脚本解决
![Screenshot_20221127-205213](https://user-images.githubusercontent.com/8659834/204140569-65c3e5ed-ced9-4900-b909-f3b9b0b44a4e.png)

**Comment by LmeSzinc** [comment]
需要提供log

**Comment by kotoricon** [comment]
INFO     12:07:10.183 │ Delay task `Commission` to 2022-11-28 12:09:40             
         (target=datetime.datetime(2022, 11, 28, 12, 9, 40))                       
INFO     12:07:10.206 │ Bind task {'Commission', 'Alas', 'General'}                
INFO     12:07:10.209 │ Save config ./config\alas.json,                            
         Commission.Scheduler.NextRun=datetime.datetime(2022, 11, 28, 12, 9, 40)   
INFO     12:07:10.269 │ Daily commission: 1, filtered_urgent: 0                    
INFO     12:07:10.273 │ Scheduler: End task `Commission`                           
INFO     12:07:10.276 │ [Server] jp                                                
INFO     12:07:10.301 │ Bind task {'Alas', 'General'}                              
INFO     12:07:10.306 │ No task pending                                            
INFO     12:07:10.308 │ [Task] Commission (Enable, 2022-11-28 12:09:40)            
INFO     12:07:10.311 │ Bind task {'Commission', 'Alas', 'General'}                
INFO     12:07:10.326 │ Wait until 2022-11-28 12:09:40 for task `Commission`       
INFO     12:07:10.329 │ Goto main page during wait                                 
INFO     12:07:10.558 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     12:07:10.562 │ App is already running, goto main page                     
INFO     12:07:10.565 │ <<< UI ENSURE >>>                                          
INFO     12:07:10.568 │ UI get current page                                        
INFO     12:07:10.586 │ [UI] page_commission                                       
INFO     12:07:10.589 │ Goto page_main                                             
INFO     12:07:10.593 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     12:07:10.611 │ Page switch: page_commission -> page_main                  
INFO     12:07:10.614 │ Click (1241,   38) @ GOTO_MAIN                             
INFO     12:07:11.171 │ Page arrive: page_main                                     
INFO     12:09:41.199 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     12:09:41.378 │ <<< UI ENSURE >>>                                          
INFO     12:09:41.381 │ UI get current page                                        
INFO     12:09:41.724 │ Unknown ui page                                            
INFO     12:09:41.795 │ Get urgent commission                                      
INFO     12:09:41.798 │ Click ( 666,  513) @ GET_MISSION                           
INFO     12:09:42.084 │ Unknown ui page                                            
INFO     12:09:42.326 │ Click ( 496,  339) @ LOGIN_CHECK                           
INFO     12:09:42.589 │ Unknown ui page                                            
INFO     12:09:42.661 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     12:09:42.681 │ [Device Orientation] 0 (Normal)                            
INFO     12:09:42.930 │ Unknown ui page                                            
INFO     12:09:43.242 │ Unknown ui page                                            
INFO     12:09:43.527 │ Unknown ui page                                            
INFO     12:09:43.851 │ Unknown ui page                                            
INFO     12:09:44.182 │ Unknown ui page                                            
INFO     12:09:44.504 │ Unknown ui page                                            
INFO     12:09:44.766 │ Unknown ui page

![explorer_rP6irNETSN](https://user-images.githubusercontent.com/8659834/204192366-7af2b239-7432-4fc4-a802-2dfe571c1447.png)

**Comment by LmeSzinc** [comment]
这应该是你的加速器不稳定，一个登录信息无效，一个HostNotFound

**Comment by kotoricon** [comment]
我知道加速器可能有点问题，这还有另外一种版本的错误我已经不知道到底是哪里的锅了

INFO     01:52:56.863 │ Scheduler: End task `Tactical`                             
INFO     01:52:56.867 │ [Server] jp                                                
INFO     01:52:56.891 │ Bind task {'General', 'Alas'}                              
INFO     01:52:56.894 │ No task pending                                            
INFO     01:52:56.897 │ [Task] Commission (Enable, 2022-11-29 02:05:33)            
INFO     01:52:56.899 │ Bind task {'General', 'Alas', 'Commission'}                
INFO     01:52:56.910 │ Wait until 2022-11-29 02:05:33 for task `Commission`       
INFO     01:52:56.914 │ Goto main page during wait                                 
INFO     01:52:57.111 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     01:52:57.114 │ App is already running, goto main page                     
INFO     01:52:57.116 │ <<< UI ENSURE >>>                                          
INFO     01:52:57.119 │ UI get current page                                        
INFO     01:52:57.132 │ [UI] page_reward                                           
INFO     01:52:57.135 │ Goto page_main                                             
INFO     01:52:57.138 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     01:52:57.162 │ Page switch: page_reward -> page_main                      
INFO     01:52:57.165 │ Click (1063,  625) @ REWARD_GOTO_MAIN                      
INFO     01:52:57.420 │ Page arrive: page_main                                     
INFO     02:05:37.500 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     02:05:37.679 │ <<< UI ENSURE >>>                                          
INFO     02:05:37.682 │ UI get current page                                        
INFO     02:05:38.044 │ Unknown ui page                                            
INFO     02:05:38.154 │ Click (1024,  670) @ GET_SHIP                              
INFO     02:05:38.436 │ Unknown ui page                                            
INFO     02:05:38.686 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     02:05:38.707 │ [Device Orientation] 0 (Normal)                            
INFO     02:05:38.932 │ Unknown ui page                                            
INFO     02:05:39.216 │ Unknown ui page                                            
INFO     02:05:39.566 │ Unknown ui page                                            
INFO     02:05:39.816 │ Unknown ui page                                            
INFO     02:05:40.118 │ Unknown ui page                                            
INFO     02:05:40.424 │ Unknown ui page                                            
INFO     02:05:40.745 │ Unknown ui page                                            
INFO     02:05:41.033 │ Unknown ui page                                            
INFO     02:05:41.326 │ Unknown ui page                                            
INFO     02:05:41.610 │ Unknown ui page                                            
INFO     02:05:41.926 │ Unknown ui page                                            
INFO     02:05:42.234 │ Unknown ui page                                            
INFO     02:05:42.530 │ Unknown ui page                                            
INFO     02:05:42.828 │ Unknown ui page                                            
INFO     02:05:43.137 │ Unknown ui page                                            
WARNING  02:05:43.391 │ Unknown ui page                                            
INFO     02:05:43.395 │ [EMULATOR__SCREENSHOT_METHOD] aScreenCap_nc                
INFO     02:05:43.399 │ [EMULATOR__CONTROL_METHOD] minitouch                       
INFO     02:05:43.402 │ [SERVER] jp                                                
WARNING  02:05:43.405 │ Starting from current page is not supported                
WARNING  02:05:43.408 │ Supported page: ['page_unknown', 'page_main', 'page_fleet',
         'page_guild', 'page_mission', 'page_event_list', 'page_campaign_menu',    
         'page_campaign', 'page_exercise', 'page_daily', 'page_event', 'page_sp',  
         'page_raid', 'page_archives', 'page_reward', 'page_commission',           
         'page_tactical', 'page_battle_pass', 'page_reshmenu', 'page_research',    
         'page_shipyard', 'page_meta', 'page_dormmenu', 'page_dorm',               
         'page_meowfficer', 'page_academy', 'page_shop', 'page_storage',           
         'page_munitions', 'page_supply_pack', 'page_build', 'page_os']            
WARNING  02:05:43.414 │ Supported page: Any page with a "HOME" button on the       
         upper-right                                                               
CRITICAL 02:05:43.417 │ Please switch to a supported page before starting Alas     
INFO     02:05:43.420 │ Game server may be under maintenance or network may be     
         broken, check server status now                                           
INFO     02:05:44.587 │ Server "スイートバン" is available.                        
CRITICAL 02:05:44.590 │ Game page unknown                                          
WARNING  02:05:44.593 │ Saving error: ./log/error/1669658744593                    
INFO     02:05:44.876 │ No provider specified, skip sending 
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10106408/log.txt)

**Comment by LmeSzinc** [comment]
需要上传 `./log/error/1669658744593`

**Comment by kotoricon** [comment]
传了啊。。你看最后那个log.txt

**Comment by LmeSzinc** [comment]
这个文件夹应该包含 `log.txt` 和一张截图
