### ISSUE TITLE
更簡單的任務自添加

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#1922]
### 你的功能请求是否与问题有关？

看了下之前 #1665 有人覺得出擊任務太少，而添加任務涉及的東西有點多
相對的添加設定檔卻幾乎是一鍵複製template

### 解决方案

如果是一模一樣的任務，比方說多一個活動圖3，有可能透過新增一個小檔案讓alas在重啟時讀取並生成新的GUI_set嗎
當前添加一個Event3幾乎是要開IDE搜索全部的Usage再手動檢查

~~就問問能不能而已，不行我就closed了~~

**Comment by LmeSzinc** [comment]
不支持
