### ISSUE TITLE
无法正常调用MAA，OSError: exception: access violation reading 0x0000000000000018

### ISSUE THREAD

**Issue by yokinanya** [LmeSzinc/AzurLaneAutoScript#1937]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

上游issues：MaaAssistantArknights/MaaAssistantArknights#2976
MAA更新到v4.8.0-alpha.1，Alas无法正常调用MAA

### 相关 Logs

[2022-12-02_maa.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10137831/2022-12-02_maa.txt)

**Comment by SaiCateDoan** [comment]
花了很长时间让我能够调试这个bug，
又花了很长时间跟maa的开发者交流沟通，
还是完全无法理解这个bug，
我感觉这个bug已经超越了c++甚至汇编的范畴，
存在一些系统或者硬件上的问题，
已知使用更高版本的python可以解决，但是alas不能升，
我已经调试这个bug到麻木了

好消息是lme没有触发这个bug
坏消息是我不知道为什么

贴一点调试过程中的截图，如果有路过的大佬可以顺便看一眼

![3RSEWD6F}S8N3`MLKF39(RI](https://user-images.githubusercontent.com/48789988/205315742-a7c42462-f60c-4a7d-9e73-75f6317766aa.png)

![)MIUZ`F`90~TYWTTF`~SXW](https://user-images.githubusercontent.com/48789988/205315927-cdca9afa-6047-4d88-97d4-8022c1d16f9d.png)

**Comment by GengGode** [comment]
要不要发个完整的程序包

**Comment by SaiCateDoan** [comment]
喜报：问题解决了

问题原因：
python 3.7的bug导致dll文件会优先从系统加载而不是本文件夹加载，
导致maa错误的加载了来自system32的旧版本onnxruntime.dll，而不是maa文件夹里的新版本onnxruntime.dll
然后maa调用的onnx和fastdeploy都没有在报错的第一时间停止运行，只是输出一个提示，
导致后续出现了看起来非常莫名其妙的错误

临时解决方案：
使用maa文件夹里的新版本onnxruntime.dll替换掉C:\Windows\System32里的旧版本onnxruntime.dll（需要手动调整权限）

后续的解决方案可能需要跟maa那边讨论过才行
为了这个bug我已经高强度工作快12小时了
感谢maa开发者跟alas开发者在我调试过程中提供的各种知识援助，如果没有他们，我一个星期都不一定能搞懂

**Comment by SaiCateDoan** [comment]
由于错误提示是在加载dll的时候就出现的，
所以跟真正出错的位置差了十万八千里，
导致调试过程中走了很多弯路

![CLZY)UCBRN5_XO7H10Z8UVM](https://user-images.githubusercontent.com/48789988/205422016-09515b5f-5c65-4ffc-ae0f-c842405269d6.png)

**Comment by Shawnsdaddy** [comment]
> 喜报：问题解决了
> 
> 问题原因： python 3.7的bug导致dll文件会优先从系统加载而不是本文件夹加载， 导致maa错误的加载了来自system32的旧版本onnxruntime.dll，而不是maa文件夹里的新版本onnxruntime.dll 然后maa调用的onnx和fastdeploy都没有在报错的第一时间停止运行，只是输出一个提示， 导致后续出现了看起来非常莫名其妙的错误
> 
> 临时解决方案： 使用maa文件夹里的新版本onnxruntime.dll替换掉C:\Windows\System32里的旧版本onnxruntime.dll（需要手动调整权限）
> 
> 后续的解决方案可能需要跟maa那边讨论过才行 为了这个bug我已经高强度工作快12小时了 感谢maa开发者跟alas开发者在我调试过程中提供的各种知识援助，如果没有他们，我一个星期都不一定能搞懂

手动调整权限太硬核了
