### ISSUE TITLE
无法正常调用MAA

### ISSUE THREAD

**Issue by yokinanya** [LmeSzinc/AzurLaneAutoScript#1938]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

上游issues：MaaAssistantArknights/MaaAssistantArknights#2976
MAA更新到v4.8.0-alpha.1，Alas无法正常调用MAA

### 相关 Logs

```Text
[2022-12-02_maa.txt](https://github.com/MaaAssistantArknights/MaaAssistantArknights/files/10137831/2022-12-02_maa.txt)
```

**Comment by 18870** [comment]
#1937

**Comment by yokinanya** [comment]
网络问题导致重复开了issue，抱歉
