### ISSUE TITLE
在西北航道A清图后被机关卡死，自律寻敌无法搜索到敌人，脚本读图后直接回港再次重复开荒。

### ISSUE THREAD

**Issue by TRNCL** [LmeSzinc/AzurLaneAutoScript#1942]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在西北航道A清图后被机关卡死，自律寻敌无法搜索到敌人，脚本读图后直接回港再次重复开荒。
忘了截Log。。。

### 如何复现

不清楚大型作战是否每个人都一样。
1. 进入大型作战
2. 进入西北航道A

### 截图

![屏幕截图 2022-12-04 025550](https://user-images.githubusercontent.com/94829054/205457878-95a9a210-3f44-4572-b264-9cb8b80d5ac1.png)
![屏幕截图 2022-12-04 025622](https://user-images.githubusercontent.com/94829054/205457880-2c270c39-762f-45e7-b198-d763b6b8d01e.png)

**Comment by LmeSzinc** [comment]
这个是游戏自身的 bug 了，特殊事件刚好刷到了当前舰队的脚下，导致无法移动。你需要换队手动清理海域，还是解决不了的话需要联系客服解决
