### ISSUE TITLE
Assets update for OpSi voucher shop | 大世界兑换商店的assets更新

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1947]
### 你的功能请求是否与问题有关？

1. 更新 `EXCHANGE_ENTER`
2. 检查 `VoucherShop.shop_grid`

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/919a154c310091365fab9c6bea5c70226039188a/module/shop/shop_voucher.py#L93-L105

3. 移除 `OSCampaignRun.opsi_voucher()` 中的服务器检查

**Comment by appleapple802** [comment]
#1982
