### ISSUE TITLE
Assets update for strategic search | 计划作战的assets更新

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#1948]
### Is your feature request related to a problem?

1. Update assets from https://github.com/LmeSzinc/AzurLaneAutoScript/blob/dev/module/os_handler/strategic.py
2. Remove server checker in `OSCampaignRun.opsi_hazard1_leveling()`

**Comment by appleapple802** [comment]
#1981
