### ISSUE TITLE
issues: The connection was not successful on SERIAL: emulator-5554

### ISSUE THREAD

**Issue by CoffeeMantou** [LmeSzinc/AzurLaneAutoScript#195]
I first run alas.bat and set SERIAL: emulator-5554 (I use the LDplayer).
See error "The connection was not successful on SERIAL: emulator-5554"

**Comment by whoamikyo** [comment]
did you already read the FAQ ? 

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn

**Comment by CoffeeMantou** [comment]
> did you already read the FAQ ?
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn

I have read the  FAQ, but I think only the last question may be similar to my situation. I have replaced the ade.exe, but still can't connect emulator.

**Comment by whoamikyo** [comment]
LDplayer needs additional procedures like start pc > open console.bat in ALAS PATH > adb devices > run alas.bat > set SERIAL in alas.bat 127.0.0.1:5555 > start ldplayer > start GUI > profit

if you open LDplayer before starting an adb server LDplayer starts its own adb server, creating that serial emulator-5554, so you need to start an external adb server before opening this crap, or just use another emulator, no point to use LDplayer.

**Comment by CoffeeMantou** [comment]
> LDplayer needs additional procedures like start pc > open console.bat in ALAS PATH > adb devices > run alas.bat > set SERIAL in alas.bat 127.0.0.1:5555 > start ldplayer > start GUI > profit
> 
> if you open LDplayer before starting an adb server LDplayer starts its own adb server, creating that serial emulator-5554, so you need to start an external adb server before opening this crap, or just use another emulator, no point to use LDplayer.

Thank you! I will try another emulator.
