### ISSUE TITLE
作战档案 红染的参访者 A3 概率出错

### ISSUE THREAD

**Issue by Mirageorwhatever** [LmeSzinc/AzurLaneAutoScript#1955]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

A3进图概率在
if self.fleet_2_push_forward():
            return True
报错，日志见1

我个人尝试写了段答辩代码，删除了push_forward()，通过RoadGrids指定了需要清除的网格点，代码见a3_temp，这段代码成功运行了几次，但是偶尔会在C2打完后报错，日志见2。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2022-12-07_11-40-46-098339](https://user-images.githubusercontent.com/84392723/206125227-b3e6fa43-c9f1-457f-86a7-603b61cceb2b.png)
原代码报错截图
[1.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10174026/1.txt)
原代码报错日志
![2022-12-07_16-03-21-894071](https://user-images.githubusercontent.com/84392723/206125345-d2d67514-28f6-4bad-9848-2cf92f3f19df.png)
答辩代码报错截图
[a3_temp.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10174033/a3_temp.txt)
修改后的代码
[2.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10174048/2.txt)
修改后的代码报错日志

**Comment by LmeSzinc** [comment]
现在的地图buff越来越多了，把当前舰队的绿箭头挡住了，覆写 `predict_current_fleet` 方法调低阈值。现在的作战档案地图文件是自动生成的，确实是会有很多问题，如果你优化完了可以提交 PR
```python
from module.map_detection.grid import Grid
from module.template.assets import TEMPLATE_FLEET_CURRENT
class EventGrid(Grid):
    def predict_current_fleet(self):
        count = self.relative_hsv_count(area=(-0.5, -3.5, 0.5, -2.5), h=(141 - 3, 141 + 10), shape=(50, 50))
        if count < 200:
            return False

        # image = self.relative_crop((-0.5, -3.5, 0.5, -2.5), shape=(60, 60))
        # image = color_similarity_2d(image, color=(24, 255, 107))
        # if not TEMPLATE_FLEET_CURRENT.match(image, similarity=0.75):
        #     return False

        return True

class Campaign(CampaignBase):
    grid_class = EventGrid
    ...
```

**Comment by LmeSzinc** [comment]
这个也改一下，这个位置能看到两个舰队的出生点
```python
MAP.camera_data_spawn_point = ['C1']
```
