### ISSUE TITLE
請問這是什麼

### ISSUE THREAD

**Issue by Arrest3579** [LmeSzinc/AzurLaneAutoScript#1963]
### 你的功能请求是否与问题有关？

請問這是什麼
![image](https://user-images.githubusercontent.com/14796986/206442775-8ca533f3-47e8-4ae5-ab6c-43ad4cd00d84.png)
![image](https://user-images.githubusercontent.com/14796986/206442813-85a78357-c72f-48c9-90b0-39fa0b5dd63f.png)

**Comment by bookbug666** [comment]
呃，他對應的是你遊戲內的白票商店呀
`Logger`對應任意紀錄儀
`LoggerAbyssal`是強敵
`LoggerObscure`是寶箱地圖
`HECombatPlan`是作戰指令書(俗稱2X書)
其他就是技能書跟物資，建議下次有新功能可以先從help裡面的描述找遊戲裡對應的東西
不然wiki沒有維護那麼頻繁跟快速

**Comment by bookbug666** [comment]
![image](https://user-images.githubusercontent.com/29662367/206444875-ceb97291-66d3-4d0a-b288-68e3f864fc06.png)
如圖，wiki雖然沒有完整更新但至少help有人寫這是個"什麼功能"

**Comment by bookbug666** [comment]
另外，台服似乎沒有更新assets，可能需要有人幫忙pr不然你還是會報錯

**Comment by mm770912** [comment]
> 另外，台服似乎沒有更新assets，可能需要有人幫忙pr不然你還是會報錯

我是日服
主要我不會用GITHUB 
不然我也很想幫忙

我是想問說
這個更新有針對那三個新道具嗎

**Comment by bookbug666** [comment]
~~抱歉先入為主以為是台服了~~
![image](https://user-images.githubusercontent.com/29662367/206445969-31288420-097e-4e8d-902d-ea6fa1ccf537.png)
你是問這三個嗎

**Comment by mm770912** [comment]
> ~抱歉先入為主以為是台服了~ ![image](https://user-images.githubusercontent.com/29662367/206445969-31288420-097e-4e8d-902d-ea6fa1ccf537.png) 你是問這三個嗎

對的 我本來以為是這三個 畢竟其他白票其實剛重置不久我就自己手動買完了
因為我想玩到最後大家白票應該都是過剩了

**Comment by bookbug666** [comment]
第一個是消寶箱圖偵查謎霧(相當於直接清霧，所以你的偵查會停用)
Alas有一個大世界共用的計時器，也許會有人修正相關的module讓運作更簡單

第二第三是一次性的檔案地圖

**Comment by mm770912** [comment]
> 第一個是消寶箱圖偵查謎霧(相當於直接清霧，所以你的偵查會停用) Alas有一個大世界共用的計時器，也許會有人修正相關的module讓運作更簡單
> 
> 第二第三是一次性的檔案地圖

功能我知道啦哈哈哈
第一個道具應該是可以讓短貓跟每月開荒優化的更好
現在就不知道是不是每個月都要買
剛剛沒仔細看說明就用下去了

**Comment by bookbug666** [comment]
開發中與否不知道 ~~今天才剛加入，你幾小時就來問~~
對Alas用戶來說這個幾乎等於沒差，因為本來alas就會幫你算間隔(而且原本也就是27分鐘)
![image](https://user-images.githubusercontent.com/29662367/206449718-656bd3cb-cef3-4183-b50b-6ba27637a128.png)
~~我是有看我能不能幫忙，奈何我座標給alas清光光了~~

也許你可以等幾天看看

**Comment by Arrest3579** [comment]
好 感謝您
我也都已經打光了....

**Comment by snowly233** [comment]
我已更新wiki，这两个分别是海域坐标记录仪和塞壬坐标记录仪，档案坐标记录仪应该还没实装

**Comment by yhzdOuO** [comment]
> 我已更新wiki，这两个分别是海域坐标记录仪和塞壬坐标记录仪，档案坐标记录仪应该还没实装

wiki上疑似有误（https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/reward_shop_filter_string），描述与对应的内容反了，LoggerAbyssal 应该是塞壬坐标记录仪，LoggerObscure 应该是海域坐标记录仪。我今天尝试了一下，只写了LoggerObscure，alas把所有的海域坐标记录仪买了，因此怀疑wiki上描述有误，上面的回复也佐证了我这个猜测，请您验证一下。
