### ISSUE TITLE
在BOSS战中延迟召唤潜艇

### ISSUE THREAD

**Issue by Anselyuki** [LmeSzinc/AzurLaneAutoScript#1964]
### 你的功能请求是否与问题有关？

在诸如14-4此类长时间BOSS战中，潜艇可以作为输出BOSS的重要输出来源，目前的潜艇召唤方式为进入战斗即召唤潜艇

### 解决方案

是否可以增加延迟一定秒数对潜艇进行召唤，数值手动输入，可以使舰队更好地适配高难图的boss环节

**Comment by LmeSzinc** [comment]
#1086
