### ISSUE TITLE
Unable to retire and change flagship

### ISSUE THREAD

**Issue by dtdog** [LmeSzinc/AzurLaneAutoScript#1967]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

Unable to retire and unable to change flagship in commission farming
When going to map selection with dock's full, it got stuck at retire screen
Same goes for flagship change, when flagship lv32 and alas went to fleet formation to change but also got stuck there and do nothing

The bugs only happen after the newest AL patch 

### Screenshots

![Untitled](https://user-images.githubusercontent.com/80538869/206679148-2f379a2d-b31a-49c2-b478-62bb414ddaf3.jpg)
![Untitled01](https://user-images.githubusercontent.com/80538869/206679158-e61d82d4-eabd-4310-8689-01c32fcfd98a.jpg)

**Comment by LmeSzinc** [comment]
Send raw screnshots from emulator

**Comment by dtdog** [comment]
> Send raw screnshots from emulator

![MuMu20221209194922](https://user-images.githubusercontent.com/80538869/206706283-5b4205ab-d17d-429b-9f52-b52e1690c502.png)
You mean this? anything else i can do?

**Comment by LmeSzinc** [comment]
Yep, it's enough for assets update

**Comment by dtdog** [comment]
Retire is working fine now
But still unable to change flagship
![2022-12-10_02-25-23-245236](https://user-images.githubusercontent.com/80538869/206785296-dda624de-7798-4c3b-8790-c34387da38cb.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10197748/log.txt)

**Comment by dtdog** [comment]
Update: Flagship change is working fine now
Thanks to all your hard-working!
