### ISSUE TITLE
WSA改变分辨率后显示问题

### ISSUE THREAD

**Issue by rabbithzy** [LmeSzinc/AzurLaneAutoScript#1970]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

尝试将alas运行在WSA的碧蓝航线上，然后出现了以下情况
![图片](https://user-images.githubusercontent.com/96123202/206710902-2f0f2c1a-b25d-496c-a53f-72d1bddf067d.png)
浏览Issue #669 后，重启WSA，adb调试输入adb shell wm size 1280x720，出现相同情况，感觉像是WSA的问题
目前使用的WSA 版本为2210.40000.7.0

### 相关 Logs

```Text
log报错game page unknown
```

### 截图

log中的截图
![2022-12-09_21-08-40-501471](https://user-images.githubusercontent.com/96123202/206712400-d730b009-c488-4401-88c6-d81024f74e29.png)

### 还有别的吗？

大概率WSA的问题，提交一下看看能不能有什么解决方案

**Comment by LmeSzinc** [comment]
#1795

**Comment by rabbithzy** [comment]
刚刚看到，所以close issue，正在打算尝试一下（虽然python学的堪忧）

**Comment by rabbithzy** [comment]
尝试后还是不行，那是不是可以换个开发方向，比如不用改变分辨率，这个建议很早就想提了

**Comment by LmeSzinc** [comment]
真要建议的话，对于正常游戏玩家我是建议卸载wsa，关闭hyperv，~~wsa对比模拟器没有优势还一堆bug不修~~

**Comment by rabbithzy** [comment]
比如不同分辨率截图后都缩放至1280*720处理，如果这样影响性能和响应速度的话，是不是可以将点击位置的坐标缩放一下，毕竟2k的屏幕不用来好好欣赏一下立绘可惜了(写这条时刚看到回复，确实没错)
ps:作为一个连python代码都写不明白的人不是很清楚这里面的工作量，对于无私维护这样一个开源项目的人还是非常佩服的，不希望自己的一个建议给开发者带来大量的工作

**Comment by chrony2333** [comment]
修改桌面屏幕分辨率为1280x720，后以全屏幕显示
