### ISSUE TITLE
加入困难副本周期功能，每日自动完成三次

### ISSUE THREAD

**Issue by KiminoKaslana** [LmeSzinc/AzurLaneAutoScript#1985]
### 你的功能请求是否与问题有关？

当前打困难副本功能融合在主线图内，不会识别剩余次数且当设置的次数限制达到，功能会关闭。

### 解决方案

希望alas能够识别每日困难副本的剩余次数并且自动刷满

**Comment by bookbug666** [comment]
![image](https://user-images.githubusercontent.com/29662367/206893819-218aa3aa-d239-4024-a998-33f4146ee13f.png)
已經有的，在這
