### ISSUE TITLE
侵蚀1总是出错

### ISSUE THREAD

**Issue by tanshengzero** [LmeSzinc/AzurLaneAutoScript#1995]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

好像不能准确识别自动确保的滚动条
![image](https://user-images.githubusercontent.com/112092328/207031531-d8def69c-b795-4ea4-8da8-b2a52422561a.png)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
OPSIHAZARD1LEVELING                                
═══════════════════════════════════════════════════════════════════════════════════
INFO     19:12:24.283 │ [Screen_size] 1280x720                                     
INFO     19:12:24.434 │ Bind task {'Alas', 'General', 'OpsiGeneral',               
         'OpsiHazard1Leveling'}                                                    
INFO     19:12:24.437 │ Save config ./config\alas.json,                            
         OpsiMeowfficerFarming.Scheduler.Enable=True                               
═════════════════════════════════════ OS INIT ═════════════════════════════════════
INFO     19:12:24.456 │ OS INIT                                                    
INFO     19:12:24.475 │ Already in os map                                          
INFO     19:12:24.477 │ <<< ZONE INIT >>>                                          
INFO     19:12:24.486 │ Get zone name                                              
INFO     19:12:24.617 │ Loading OCR model: ./bin/cnocr_models/jp                   
INFO     19:12:24.713 │ [MAP_NAME 0.149s] 西大陸棚D安全海域                        
INFO     19:12:24.715 │ Map name processed: 西大陸棚D                              
INFO     19:12:24.719 │ [Zone] [44|West Continental Shelf D]                       
──────────────────────────────── AFTER AUTO SEARCH ────────────────────────────────
INFO     19:12:24.722 │ AFTER AUTO SEARCH                                          
INFO     19:12:24.743 │ No EMP debuff on current fleet                             
INFO     19:12:24.750 │ [HP]  98%  98%  98%  98%  98%  98%                         
INFO     19:12:24.757 │ [Repair icon] [False, False, False, False, False, False]   
INFO     19:12:24.761 │ No ship found to be below threshold 40%, continue OS       
         exploration                                                               
INFO     19:12:24.764 │ Handle after auto search finished, solved=False            
INFO     19:12:24.767 │ Current fleet is not afflicted with the low resolve debuff 
INFO     19:12:24.771 │ In zone 22, 44, 154, skip running first auto search        
INFO     19:12:24.774 │ Ash beacon status: gray                                    
INFO     19:12:24.792 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     19:12:24.851 │ [ASH_COLLECT_STATUS 0.075s] 0/200                          
INFO     19:12:24.877 │ [ASH_DAILY_STATUS 0.023s] 200/200                          
INFO     19:12:24.879 │ Ash beacon fully collected today                           
══════════════════════════════ OS HAZARD 1 LEVELING ═══════════════════════════════
INFO     19:12:24.883 │ OS HAZARD 1 LEVELING                                       
INFO     19:12:24.884 │ [OS_ACTION_POINT_PRESERVE] 200                             
INFO     19:12:24.910 │ [SHOP_YELLOW_COINS 0.024s] 237476                          
INFO     19:12:24.965 │ [MAP_NAME 0.051s] 西大陸棚D安全海域                        
INFO     19:12:24.968 │ Map name processed: 西大陸棚D                              
INFO     19:12:24.970 │ [Zone] [44|West Continental Shelf D]                       
INFO     19:12:24.973 │ <<< UI CLICK >>>                                           
INFO     19:12:27.390 │ Click ( 907,   35) @ ACTION_POINT_REMAIN_OS                
INFO     19:12:27.392 │ <<< MINITOUCH INIT >>>                                     
INFO     19:12:27.401 │ [Device Orientation] 0 (Normal)                            
INFO     19:12:27.404 │ Reuse forward: ForwardItem(serial='127.0.0.1:2253',        
         local='tcp:20256', remote='localabstract:minitouch')                      
INFO     19:12:27.408 │ v 1                                                        
INFO     19:12:27.410 │ ^ 2 32767 32767 0                                          
INFO     19:12:27.412 │ $ 4455                                                     
INFO     19:12:27.413 │ minitouch running on port: 20256, pid: 4455                
INFO     19:12:27.415 │ max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
INFO     19:12:30.574 │ [Amount_ocr 0.055s] [9653, 67, 1, 0]                       
INFO     19:12:30.600 │ [ACTION_POINT_REMAIN 0.024s] 171                           
INFO     19:12:30.602 │ Action points: 171(1561), oil: 9653                        
INFO     19:12:30.604 │ Having enough action points                                
INFO     19:12:30.606 │ <<< UI CLICK >>>                                           
INFO     19:12:30.618 │ Click ( 416,  548) @ ACTION_POINT_CANCEL                   
════════════════════════ OS HAZARD 1 LEVELING, ZONE_ID=44 ═════════════════════════
INFO     19:12:31.481 │ OS HAZARD 1 LEVELING, ZONE_ID=44                           
INFO     19:12:31.483 │ <<< FLEET SET TO 4 >>>                                     
INFO     19:12:31.515 │ It is fleet 4 already                                      
─────────────────────────────── RUN STRATEGY SEARCH ───────────────────────────────
INFO     19:12:31.518 │ RUN STRATEGY SEARCH                                        
INFO     19:12:31.520 │ <<< STRATEGIC SEARCH START >>>                             
INFO     19:12:31.521 │ Strategic search enter                                     
INFO     19:12:33.709 │ Click (1245,  601) @ STRATEGIC_SEARCH_MAP_OPTION_OFF       
INFO     19:12:35.993 │ Click (1210,  597) @ STRATEGIC_SEARCH_MAP_OPTION_OFF       
INFO     19:12:36.687 │ Strategic search set option                                
INFO     19:12:36.690 │ [zone_mode] repeat                                         
INFO     19:12:36.691 │ [encounter_merchant] stop                                  
INFO     19:12:36.693 │ STRATEGIC_SEARCH_SCROLL_AREA set to 0.5                    
INFO     19:12:36.696 │ [STRATEGIC_SEARCH_SCROLL_AREA] 0.00 (33.5-34.0)/(193-68)   
INFO     19:12:36.698 │ Swipe ( 910,  304) -> ( 910,  375)                         
INFO     19:12:39.300 │ [STRATEGIC_SEARCH_SCROLL_AREA] 0.00 (nan-0.0)/(193-0)      
WARNING  19:12:39.302 │ Scroll disappeared, assume scroll set
```

**Comment by tanshengzero** [comment]
[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10237614/error.zip)

**Comment by ybyzz** [comment]
经过观察好像是点击计划任务的时候连续多次点击造成对话框消失

**Comment by LmeSzinc** [comment]
> [error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10237614/error.zip)

<html>
<body>
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">修改游戏设置</h2><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">对照这个表格修改游戏内的设置，<del style="box-sizing: border-box;">正常玩过游戏的都这么设置</del>。</p><blockquote style="box-sizing: border-box; margin: 0px 0px 16px; padding: 0px 1em; color: var(--color-fg-muted); border-left: 0.25em solid var(--color-border-default); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px;">对着改的意思是，这是统一的标准，照着给定的内容执行，不要问为什么，不允许有不一样的。</p></blockquote><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">主界面 =&gt; 右下角：设置 =&gt; 左侧边栏：选项</p>

设置名称 | 值
-- | --
帧数设置 | 60帧
大型作战设置 - 减少TB引导 | 开
大型作战设置 - 自律时自动提交道具 | 开
大型作战设置 - 安全海域默认开启自律 | 关
剧情自动播放 | 开启
剧情自动播放速度调整 | 特快


</body>
</html>
