### ISSUE TITLE
使用途中启动过其他模拟器大概率会出现“远程主机强迫关闭了一个现有的连接”

### ISSUE THREAD

**Issue by kotoricon** [LmeSzinc/AzurLaneAutoScript#1997]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

目前平时使用都在用夜神，但是如果中途启动过其他模拟器（如雷电/bs等）大概率会一直提示“远程主机强迫关闭了一个现有的连接”无法使用。只能通过重复重新手动启动或者直接重启电脑才能解决。

手动设置端口修改比如修改auto为指定ip端口无效

### 如何复现

1. 开启挂游戏的模拟器后启动其他品牌的模拟器玩其他游戏或者做其他的事
2. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     01:51:11.342 │ Start scheduler loop: alas                                 
INFO     01:51:11.374 │ [Server] cn                                                
INFO     01:51:11.404 │ Bind task {'General', 'Alas'}                              
INFO     01:51:12.764 │ Server "スイートバン" is available.                        
INFO     01:51:12.768 │ Pending tasks: ['Research', 'Meowfficer']                  
INFO     01:51:12.771 │ [Task] Research (Enable, 2022-12-13 01:47:45)              
INFO     01:51:12.774 │ Bind task {'Research', 'General', 'Alas'}                  
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     01:51:21.214 │ DEVICE                                                     
INFO     01:51:21.217 │ [AdbBinary]                                                
         F:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     01:51:21.223 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     01:51:21.226 │ <<< DETECT DEVICE >>>                                      
INFO     01:51:21.229 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     01:51:25.444 │ No available devices                                       
INFO     01:51:25.454 │ connected to 127.0.0.1:62001                               
INFO     01:51:25.457 │ [AdbDevice] AdbDevice(serial=127.0.0.1:62001)              
INFO     01:51:25.459 │ [PackageName] com.YoStarJP.AzurLane                        
INFO     01:51:25.462 │ [Server] jp                                                
INFO     01:51:25.465 │ Screenshot interval set to 0.3s                            
INFO     01:51:25.469 │ Scheduler: Start task `Research`                           
═══════════════════════════════════════════════════════════════════════════════════
                                     RESEARCH                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     01:51:25.475 │ Connecting to local emulator, using host 192.168.50.7      
INFO     01:51:25.479 │ Reverse server listening on 192.168.50.7:20805, client can 
         send data to 192.168.50.7:20805                                           
ERROR    01:51:28.024 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     01:51:35.226 │ Restart adb                                                
INFO     01:51:35.230 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    01:51:35.246 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     01:51:42.451 │ Restart adb                                                
INFO     01:51:42.456 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    01:51:42.462 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     01:51:49.667 │ Restart adb                                                
INFO     01:51:49.672 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    01:51:49.680 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     01:51:56.888 │ Restart adb                                                
INFO     01:51:56.893 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    01:51:56.899 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
CRITICAL 01:51:56.903 │ Retry screenshot_ascreencap_nc() failed                    
CRITICAL 01:51:56.905 │ Request human takeover                                     
INFO     01:51:56.907 │ No provider specified, skip sending                        
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     01:56:26.431 │ Start scheduler loop: alas                                 
INFO     01:56:26.437 │ [Server] cn                                                
INFO     01:56:26.466 │ Bind task {'Alas', 'General'}                              
INFO     01:56:27.734 │ Server "スイートバン" is available.                        
INFO     01:56:27.738 │ Pending tasks: ['Research', 'Meowfficer']                  
INFO     01:56:27.741 │ [Task] Research (Enable, 2022-12-13 01:47:45)              
INFO     01:56:27.744 │ Bind task {'Alas', 'Research', 'General'}                  
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     01:56:30.132 │ DEVICE                                                     
INFO     01:56:30.136 │ [AdbBinary]                                                
         F:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     01:56:30.142 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     01:56:30.146 │ <<< DETECT DEVICE >>>                                      
INFO     01:56:30.149 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     01:56:34.364 │ No available devices                                       
INFO     01:56:34.373 │ connected to 127.0.0.1:62001                               
INFO     01:56:34.376 │ [AdbDevice] AdbDevice(serial=127.0.0.1:62001)              
INFO     01:56:34.380 │ [PackageName] com.YoStarJP.AzurLane                        
INFO     01:56:34.382 │ [Server] jp                                                
INFO     01:56:34.385 │ Screenshot interval set to 0.3s                            
INFO     01:56:34.388 │ Scheduler: Start task `Research`
```

**Comment by SaiCateDoan** [comment]
有可能是因为不同模拟器的adb版本不一致导致的，alas会尝试用自己的adb替换所有模拟器的adb，但是不一定能成功，你可以尝试手动替换

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#adb-server-version-36-doesnt-match-this-client-41-killing

**Comment by kotoricon** [comment]
效果不大，依然继续出 举例刚才的记录

═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     11:35:02.069 │ Start scheduler loop: alas                                 
INFO     11:35:02.084 │ [Server] cn                                                
INFO     11:35:02.109 │ Bind task {'General', 'Alas'}                              
INFO     11:35:03.061 │ Server "スイートバン" is available.                        
INFO     11:35:03.066 │ Pending tasks: ['Commission', 'Tactical', 'Research',      
         'Dorm', 'Guild', 'Reward']                                                
INFO     11:35:03.070 │ [Task] Commission (Enable, 2022-12-20 04:08:06)            
INFO     11:35:03.074 │ Bind task {'General', 'Alas', 'Commission'}                
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     11:35:11.024 │ DEVICE                                                     
INFO     11:35:11.028 │ [AdbBinary]                                                
         F:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     11:35:11.034 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     11:35:11.036 │ <<< DETECT DEVICE >>>                                      
INFO     11:35:11.039 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     11:35:11.044 │ 127.0.0.1:62001                                            
INFO     11:35:11.051 │ already connected to 127.0.0.1:62001                       
INFO     11:35:11.055 │ [AdbDevice] AdbDevice(serial=127.0.0.1:62001)              
INFO     11:35:11.059 │ [PackageName] com.YoStarJP.AzurLane                        
INFO     11:35:11.062 │ [Server] jp                                                
INFO     11:35:11.065 │ Screenshot interval set to 0.3s                            
INFO     11:35:11.068 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     11:35:11.076 │ Connecting to local emulator, using host 192.168.50.7      
INFO     11:35:11.079 │ Reverse server listening on 192.168.50.7:20886, client can 
         send data to 192.168.50.7:20886                                           
ERROR    11:35:13.383 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     11:35:20.996 │ Restart adb                                                
INFO     11:35:21.002 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    11:35:21.006 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
[alas] exited. Reason: Manual stop

═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     11:35:25.671 │ Start scheduler loop: alas                                 
INFO     11:35:25.676 │ [Server] cn                                                
INFO     11:35:25.702 │ Bind task {'Alas', 'General'}                              
INFO     11:35:26.517 │ Server "スイートバン" is available.                        
INFO     11:35:26.522 │ Pending tasks: ['Commission', 'Tactical', 'Research',      
         'Dorm', 'Guild', 'Reward']                                                
INFO     11:35:26.525 │ [Task] Commission (Enable, 2022-12-20 04:08:06)            
INFO     11:35:26.528 │ Bind task {'Commission', 'Alas', 'General'}                
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     11:35:28.770 │ DEVICE                                                     
INFO     11:35:28.774 │ [AdbBinary]                                                
         F:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     11:35:28.780 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     11:35:28.783 │ <<< DETECT DEVICE >>>                                      
INFO     11:35:28.787 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     11:35:33.000 │ No available devices                                       
INFO     11:35:33.011 │ connected to 127.0.0.1:62001                               
INFO     11:35:33.014 │ [AdbDevice] AdbDevice(serial=127.0.0.1:62001)              
INFO     11:35:33.017 │ [PackageName] com.YoStarJP.AzurLane                        
INFO     11:35:33.020 │ [Server] jp                                                
INFO     11:35:33.023 │ Screenshot interval set to 0.3s                            
INFO     11:35:33.026 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     11:35:33.033 │ Connecting to local emulator, using host 192.168.50.7      
INFO     11:35:33.036 │ Reverse server listening on 192.168.50.7:20314, client can 
         send data to 192.168.50.7:20314                                           
ERROR    11:35:35.106 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     11:35:42.316 │ Restart adb                                                
INFO     11:35:42.320 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    11:35:42.325 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     11:35:49.533 │ Restart adb                                                
INFO     11:35:49.537 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    11:35:49.542 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     11:35:56.783 │ Restart adb                                                
INFO     11:35:56.790 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    11:35:56.797 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
INFO     11:36:04.000 │ Restart adb                                                
INFO     11:36:04.005 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
ERROR    11:36:04.011 │ ConnectionResetError: [WinError 10054]                     
         远程主机强迫关闭了一个现有的连接。                                        
CRITICAL 11:36:04.015 │ Retry screenshot_ascreencap_nc() failed                    
CRITICAL 11:36:04.017 │ Request human takeover                                     
INFO     11:36:04.020 │ No provider specified, skip sending

**Comment by LmeSzinc** [comment]
文档只是以夜神作为例子，你需要替换 **所有模拟器** 的 **所有ADB**，还需要替换一些其他软件自带的ADB，保证电脑上的所有ADB都是相同版本

**Comment by kotoricon** [comment]
都替换过了，有时候甚至是刚开机什么都没运行过只开它一个模拟器也会出错，不信晚上有空了我给你录视频看看

**Comment by kotoricon** [comment]
https://drive.google.com/file/d/1JjOLMawQt2YrTx-C1GQNbMLbKm8DieJ1/view?usp=sharing

一直忘了这个了，刚开机就5037

**Comment by bookbug666** [comment]
![image](https://user-images.githubusercontent.com/29662367/209474861-c6f8b870-e461-4dff-ac39-b67ca5da80b3.png)
其實不開別的模擬器，光是使用`服務器刷新時重啟`就有機會遇到，你可以點`Force restart`試試(至少比重啟電腦快些
