### ISSUE TITLE
Incorrect versions in requirements.txt

### ISSUE THREAD

**Issue by whoamikyo** [LmeSzinc/AzurLaneAutoScript#2]
Hi, I downloaded your script to test and saw that the versions of the dependencies that you specified in the requirements.txt file are not correct, could you put the compatible versions?

Also, any chance to support other languages? I could help with the assets of the English version.

![](https://i.imgur.com/5T71PTA.png)

**Comment by LmeSzinc** [comment]
I have changed the versions, and tested on a new conda environment (python3.7) with no errors.

I also make some changes and it is possible to support other language now.
See [development.md](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/development.md#%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81%E5%85%B6%E4%BB%96%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AF%AD%E8%A8%80-how-to-support-other-serverlanguage) for details.

**Comment by whoamikyo** [comment]
thanks, appreciate.
