### ISSUE TITLE
遊戲重啟過程中失敗Couldn't get focused app

### ISSUE THREAD

**Issue by ddmugicha** [LmeSzinc/AzurLaneAutoScript#2009]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

遊戲重啟過程中失敗Couldn't get focused app

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

[Log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10252038/Log.txt)

**Comment by LmeSzinc** [comment]
游戏在 3 分钟内未能启动，且无法获取当前应用的信息，可能是模拟器崩溃了，重启模拟器就好
