### ISSUE TITLE
14图弹药bug

### ISSUE THREAD

**Issue by goat0001** [LmeSzinc/AzurLaneAutoScript#2026]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

14图的照明弹捡起后卡在弹药介绍界面

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2022-12-23_12-26-53-141452](https://user-images.githubusercontent.com/108048191/209271269-48e2e6a5-1c1f-494f-8373-081022d86455.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10292074/log.txt)

**Comment by LmeSzinc** [comment]
#1954
