### ISSUE TITLE
请求在心情计算中加入温泉的心情回复

### ISSUE THREAD

**Issue by 2508194792** [LmeSzinc/AzurLaneAutoScript#2029]
### 你的功能请求是否与问题有关？

在新活动中有一个温泉功能，可以回复舰娘心情，且可与后宅叠加

### 解决方案

不知道可不可以在”活动图“的心情计算那一栏加一个”后宅二层+温泉“的选项？

### 其他内容

![碧蓝航线脚本反馈](https://user-images.githubusercontent.com/71597704/209282136-db0d3856-9a4a-40eb-bf87-6c4f08b5b951.png)

**Comment by bookbug666** [comment]
剛剛擺放交叉看了下，溫泉相當於+10的每小時回復，也許你可以先用'**全員已婚**'假裝一下
另外溫泉看起來不是常駐，不確定會不會增加維護成本/會不會做

**Comment by 2508194792** [comment]
好的好的，非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月23日(周五) 下午2:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 请求在心情计算中加入温泉的心情回复 (Issue #2029)




 
剛剛擺放交叉看了下，溫泉相當於+10的每小時回復，也許你可以先用'全員已婚'假裝一下
 另外溫泉看起來不是常駐，不確定會不會增加維護成本/會不會做

**Comment by Arrest3579** [comment]
我覺得也不用吧 你的油有那麼多嗎
