### ISSUE TITLE
MUMU模拟器多开ADB端口问题解决

### ISSUE THREAD

**Issue by qingxuehu** [LmeSzinc/AzurLaneAutoScript#2038]
### Is your feature request related to a problem?

MuMu模拟器多开时ADB端口只能控制第一个模拟器的问题有解决办法

### Describe the solution you'd like

MuMu是基于vbox魔改来的，有人发现了解决办法
本人转载了该文章，源网页已无法打开
https://www.bilibili.com/read/cv20710232

命令是这样子的

"C:\Program Files\NemuVbox\Hypervisor\NemuManage.exe" modifyvm "虚拟机对应的名字" --natpf1 "myadb,tcp,,自定义的端口号,,5555"

主要修改几个引号里面的内容，

第一个NemuManage的路径基本都固定，一般都不需要改。

第二个引号是虚拟机对应的名字，在

MuMu安装目录\emulator\nemu\vms\

里面查看，每个窗口对应一个文件夹，就是文件夹的名字。

第三个就是自定义的端口号了，自己随便取，不要跟已经有的冲突就可以。每个窗口一个。

示例：

"C:\Program Files\NemuVbox\Hypervisor\NemuManage.exe" modifyvm "60.6.29.002-nemu-default-x64-release" --natpf1 "myadb,tcp,,8555,,5555"

在虚拟机关闭的情况下用cmd执行就可以了。

执行完，开启这个虚拟机，就可以用adb通过自定义的端口连接到了。

MuMu初始的那个窗口不需要改，还是7555，自己新建的，以上面我的示例从8555开始，逐个+1

这样就可以实现了MUMU模拟器多开同时用adb控制的功能。

本人使用时注意到 如果还是无法连接要用mumu模拟器的多开器一键全部关闭，再一键全部启动，才能实现 多模拟器下ADB端口正确

### Additional context

![image](https://user-images.githubusercontent.com/47526418/209425035-6b05fc21-df1c-4279-84bc-78aee6fe8e94.png)
![image](https://user-images.githubusercontent.com/47526418/209425083-cf311ad4-a7fe-4077-8fed-63477cb3f8a2.png)

**Comment by LmeSzinc** [comment]
我注意到模拟器下有vbox配置文件，mumu x 的在 ：（nemu-12.0-x64-default是模拟器实例名称）
```
MuMu9\emulator\nemu9\vms\nemu-12.0-x64-default\nemu-12.0-x64-default.nemu
```
在夜神逍遥里 Alas 是通过ADB_PORT的转发设置查询模拟器 serial 的，mumu的配置文件也有这句
```xml
<Forwarding name="ADB_PORT" proto="1" hostip="127.0.0.1" hostport="7555" guestport="5555"/>
```
我想了解的是:
1. 直接修改vbox配置文件，能实现mumu开在不同端口上吗
2. 直接修改vbox配置文件与用命令新增转发一样吗
3. 可以提供一个简单的脚本给mumu自动安排多开端口吗，按 7555 7556 7557 递增

**Comment by qingxuehu** [comment]
vbox配置文件 我也尝试过修改，但是，不论修改成什么端口，最后开启时都会被重置成7555

**Comment by SaiCateDoan** [comment]
我尝试在mumu x上进行这样的修改，但是失败了
"C:\Program Files\Nemu6Vbox\Hypervisor\Muvm6Manage.exe" modifyvm "nemu-vm-base_1" --natpf1 "myadb,tcp,,8555,,5555"
这是我尝试使用的命令
修改之后单独打开其中一个模拟器端口会变回7555，一键多开会导致模拟器卡60%

**Comment by qingxuehu** [comment]
本方法仅在mumu模拟器 安卓6 上测试过，本人不是该方法发现者，且目前无法联系上原作者，我也不懂模拟器设置，下面说出我使用期间遇到的问题和解决方法
1、单独启动其中一个模拟器无法应用多开的端口，使用mumu多开器勾上全部模拟器一键多开
2、1方法某模拟器端口还是无法连接时，使用mumu多开器勾上全部一键关闭后，再次一键多开，如还还有问题请重新输入命令设置adb端口
3、一键多开时出现卡加载界面，白屏等，请在任务管理器里关闭所有的mumu相关程序，本人一般直接重启
本人不是专业人士，望各位大佬补充更正

**Comment by segfault-bilibili** [comment]
我之前是在这里找到的方法：
https://jiezhe.net/post/91.html

但是MuMu（安卓6）更新了几个版本之后貌似就如楼上所说会自动重置端口号回7555。

**Comment by segfault-bilibili** [comment]
刚刚通过hex patch `VboxManager.dll`的方法使其跳过`resetMachine`，这样就可以防止`myadb`被重置清除掉：
```
正在比较文件 VboxManager-orig.dll 和 VboxManager.dll
00037586: 75 EB
```

`75 08 48 8B CB E8 92 8F FC FF E8 2C 96 FC FF` => `EB 08 48 8B CB E8 92 8F FC FF E8 2C 96 FC FF`

文件路径是`[MuMu安装目录]\emulator\nemu\EmulatorShell\VboxManager.dll`

相关log（`[MuMu安装目录]\emulator\nemu\EmulatorShell\vmsdk\NemuPlayer.exe_vm_nemu_nemu-vm-base_1.log`）：
```
[2,023-01-21:16:25:04:300][INFO] (VboxManager::VmCommandManager::cleanEmptyMediums) <3928> # end
[2,023-01-21:16:25:04:300][INFO] (VboxManager::VmCommandManager::detachMachineAllDisks) <3977> # end
[2,023-01-21:16:25:16:718][INFO] (VboxManager::VmCommandManager::resetMachine) <4304> # start
[2,023-01-21:16:25:16:719][INFO] (VboxManager::VBox::findMachine) <338> # nemu-vm-base_1
[2,023-01-21:16:25:16:719][INFO] (VboxManager::VBox::machineGetState) <488> # 7
[2,023-01-21:16:25:16:721][INFO] (VboxManager::VBox::machineGetState) <504> # return state = 1
……
[2,023-01-21:16:25:16:836][INFO] (VboxManager::VmCommandManager::cleanEmptyMediums) <3928> # end
[2,023-01-21:16:25:16:836][INFO] (VboxManager::VmCommandManager::resetMachine) <4356> # end
[2,023-01-21:16:25:16:836][INFO] (VboxManager::VBox::findMachine) <338> # nemu-vm-base_1
[2,023-01-21:16:25:16:836][INFO] (VboxManager::VBox::machineGetState) <488> # 12
[2,023-01-21:16:25:16:836][INFO] (VboxManager::VBox::machineGetState) <504> # return state = 1
```

**Comment by qingxuehu** [comment]
可以的话能否提供一个操作方法或者是脚本 来使用

**Comment by segfault-bilibili** [comment]
找个十六进制编辑器搜索替换即可

**Comment by segfault-bilibili** [comment]
（另外我只是观察到它不会重置机器了，不知道有没有别的什么未知副作用，慎用）

**Comment by segfault-bilibili** [comment]
啊原来可以直接上传

[VboxManager-noreset.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10471862/VboxManager-noreset.zip)

不过不知道MuMu版本和你们是否一致，我现在是2.7.16.0 x64

**Comment by aqudgv** [comment]
> 啊原来可以直接上传
> 
> [VboxManager-noreset.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10471862/VboxManager-noreset.zip)
> 
> 不过不知道MuMu版本和你们是否一致，我现在是2.7.16.0 x64

膜拜大神！！！

顺便问一下 resetMachine => eesetMachine 为啥程序不报错？

**Comment by LmeSzinc** [comment]
测试中的 MuMu 12 支持多开了，不是 mumu6 和 mumu X 的残废多开，每个模拟器实例的 adb 连接地址在 `菜单` - `问题诊断` 里面可以看到。以上内容都没有意义了，因此关闭 issue。
https://adl.netease.com/d/g/a11/c/mumu12_t

**Comment by fengliCN** [comment]
查看MuMu模拟器12的adb连接端口
https://mumu.163.com/help/20230214/35047_1073151.html
