### ISSUE TITLE
使用了狩猎及boss战但是在boss战不召唤潜艇

### ISSUE THREAD

**Issue by 24k12315** [LmeSzinc/AzurLaneAutoScript#2039]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用了狩猎及boss战但是在boss战不召唤潜艇

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![12CB4C0DA69FBC17F6D28162D86956DD](https://user-images.githubusercontent.com/118600831/209425963-456d7767-ec4c-4791-baf8-5e876a8300cc.jpg)
![I~Y5QEQYH{8DAUC7LNA0UBH](https://user-images.githubusercontent.com/118600831/209425968-c6854920-a815-42dc-b76a-59234c1918f3.png)
![${K(30VYLE%)}C8FNRCJ KT](https://user-images.githubusercontent.com/118600831/209425990-b33602c9-b368-448f-8888-b38426c9a50d.png)

**Comment by LmeSzinc** [comment]
潜艇设置仅在 `自律寻敌` 关闭时生效
