### ISSUE TITLE
MAA启动后报错 TouchModeNotAvailable

### ISSUE THREAD

**Issue by wosiwq** [LmeSzinc/AzurLaneAutoScript#2044]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

MAA启动后报错 TouchModeNotAvailable

### 如何复现

1.使用全新windows server 2016
2.安装运行依赖ndp48-x86-x64-allos-enu VC_redist.x64
3.启动alas 创建maa
4.点击启动，即可触发
使用的是阿里云的服务器，手机用的是星界链的云手机

### 相关 Logs

```Text
INFO     20:07:08.761 │ SHOW DEPLOY CONFIG                                                                                      
INFO     20:07:08.772 │ Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror                                     
INFO     20:07:08.780 │ PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple                                                    
INFO     20:07:08.780 │ Language: zh-CN                                                                                         
INFO     20:07:08.811 │ Rest of the configs are the same as default                                                             
INFO     20:07:12.593 │ [Message.ConnectionInfo] 103.36.***.**:301 UuidGot                                                     
INFO     20:07:12.655 │ [Message.ConnectionInfo] 103.36.***.**:301 ResolutionGot                                               
INFO     20:07:12.686 │ [Message.ConnectionInfo] 103.36.***.**:301 Connected                                                   
INFO     20:07:16.098 │ [Message.ConnectionInfo] 103.36.***.**:301 TouchModeNotAvailable                                       
CRITICAL 20:07:16.503 │ Request human takeover                                                                                  
INFO     20:07:17.311 │ No provider specified, skip sending                                  
```
```


### 截图

_No response_

### 还有别的吗？

_No response_

**Comment by wosiwq** [comment]
通过把[asst_backup](../tree/master/submodule/AlasMaaBridge/module/handler/asst_backup.py)更新到[MAA最新版](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/Python/asst.py)，并修改[handler](../tree/master/submodule/AlasMaaBridge/module/handler/handler.py)中的connect方法，在[194行](../tree/master/submodule/AlasMaaBridge/module/handler/handler.py#L194)后添加语句 `self.asst.set_instance_option(InstanceOptionType.touch_type, 'adb')` (此处引入依赖以导入InstanceOptionType，语句为`from submodule.AlasMaaBridge.module.handler.asst_backup import InstanceOptionType`) 后成功解决问题，希望在config中添加相应的配置进行选择，以修改此处硬编码的 `'adb'` 
关于[set_instance_option](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/master/src/MaaCore/Assistant.cpp#L62)可以在此处找到源方法
@SaiCateDoan

**Comment by SaiCateDoan** [comment]
在做了在做了

**Comment by wosiwq** [comment]
> 在做了在做了

在commit 1dc28e253d50b1e1544857ac4e3cd7e4fcfa694e 之后 已经确认功能可用，BUG已经修复，就是在maa.py的第88行 `logger.critical('使用了不支持自动下干员的触控方案')` 此处有typo，应为 `'使用了不支持暂停下干员的触控方案'`
