### ISSUE TITLE
不知道這個新道具購買的功能是否已經加進去了

### ISSUE THREAD

**Issue by Arrest3579** [LmeSzinc/AzurLaneAutoScript#2056]
### 你的功能请求是否与问题有关？

如圖
記得沒錯好像是12月新物品
不知道是否已加入排程更新

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/reward_shop_filter_string
英文不好看不出來是哪個

### 其他内容

![Uploading image.png…]()

**Comment by Arrest3579** [comment]
![image](https://user-images.githubusercontent.com/14796986/210149707-f97b54f7-fe82-4bc4-acba-d3c2add8ba6c.png)

**Comment by LmeSzinc** [comment]
有 Alas 的话，那个隐秘海域道具就不需要买了，Alas 会等空域搜索 CD 的，在等 CD 期间其他任务会穿插进行。
