### ISSUE TITLE
无法使用。提示 Timeout while connecting to server checker API. 

### ISSUE THREAD

**Issue by XuyuEre** [LmeSzinc/AzurLaneAutoScript#2058]
在办公室开alas无法使用，但是回家后可以使用，尝试过重启和更换成手机热点依然存在。检查过adb是开启的。

> log：
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     10:21:40.364 │ Start scheduler loop: alas                                 
INFO     10:21:40.370 │ [Server] cn                                                
INFO     10:21:40.394 │ Bind task {'Alas', 'General'}                              
ERROR    10:21:40.477 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    10:21:40.481 │ Timeout while connecting to server checker API.            
INFO     10:21:40.669 │ Trigger fast retry.                                        
INFO     10:21:40.671 │ Retry 1 times ...                                          
ERROR    10:21:40.731 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    10:21:40.735 │ Timeout while connecting to server checker API.            
INFO     10:21:40.738 │ Retry 2 times ...                                          
ERROR    10:21:40.812 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    10:21:40.817 │ Timeout while connecting to server checker API.            
INFO     10:21:40.819 │ Retry 3 times ...                                          
ERROR    10:21:40.884 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    10:21:40.890 │ Timeout while connecting to server checker API.            
ERROR    10:21:40.894 │ Cannot connect to API. Please check you network or disable 
         server checker.                                                           
INFO     10:21:40.900 │ Server checker will retry after 120s                       
[alas] exited. Reason: Manual stop

**Comment by Horizon101011** [comment]
需要检查一下防火墙或者杀软之类的相关配置，ConnectionAbortedError出现的时间太快了，通常都是这一类问题主动切断连接引起的

**Comment by XuyuEre** [comment]
主要是我也没更改防火墙和杀软的配置。难道是vpn引起的吗，但是同一个vpn软件 我回家后就能正常使用alas了，就很奇怪

**Comment by XuyuEre** [comment]
- 
        
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     21:37:43.015 │ Start scheduler loop: alas                                 
INFO     21:37:43.028 │ [Server] cn                                                
INFO     21:37:43.057 │ Bind task {'General', 'Alas'}                              
INFO     21:37:43.258 │ Server "十字路口行动" is available.                        
INFO     21:37:43.265 │ Pending tasks: ['Restart', 'Commission', 'Tactical',       
         'Research', 'Exercise', 'Dorm', 'Meowfficer', 'Guild', 'Reward',          
         'ShopFrequent', 'ShopOnce', 'Freebies', 'OpsiExplore', 'OpsiAshBeacon',   
         'OpsiDaily', 'OpsiShop', 'OpsiAbyssal', 'OpsiStronghold', 'OpsiObscure',  
         'Daily', 'Hard', 'OpsiAshAssist', 'Event']                                
INFO     21:37:43.273 │ [Task] Restart (Enable, 2023-01-01 00:00:00)               
INFO     21:37:43.276 │ Bind task {'General', 'Alas', 'Restart'}                   
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     21:37:45.904 │ DEVICE                                                     
INFO     21:37:45.908 │ [AdbBinary]                                                
         D:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     21:37:45.914 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     21:37:45.919 │ <<< DETECT DEVICE >>>                                      
INFO     21:37:45.924 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     21:37:45.928 │ emulator-5554                                              
INFO     21:37:45.931 │ emulator-5556                                              
INFO     21:37:45.933 │ emulator-5558                                              
INFO     21:37:45.937 │ [AdbDevice] AdbDevice(serial=emulator-5554)                
INFO     21:37:45.942 │ [PackageName] com.bilibili.azurlane                        
INFO     21:37:45.944 │ [Server] cn                                                
INFO     21:37:45.946 │ Screenshot interval set to 0.3s                            
INFO     21:37:45.951 │ Skip task `Restart` at scheduler start                     
INFO     21:37:45.955 │ Delay task `Restart` to 2023-01-02 00:00:00                
         (server_update='00:00')                                                   
INFO     21:37:45.976 │ Bind task {'General', 'Alas', 'Restart'}                   
INFO     21:37:45.979 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2023, 1, 2, 0, 0)             
INFO     21:37:45.990 │ [Server] cn                                                
INFO     21:37:46.016 │ Bind task {'General', 'Alas'}                              
INFO     21:37:46.023 │ Pending tasks: ['Commission', 'Tactical', 'Research',      
         'Exercise', 'Dorm', 'Meowfficer', 'Guild', 'Reward', 'ShopFrequent',      
         'ShopOnce', 'Freebies', 'OpsiExplore', 'OpsiAshBeacon', 'OpsiDaily',      
         'OpsiShop', 'OpsiAbyssal', 'OpsiStronghold', 'OpsiObscure', 'Daily',      
         'Hard', 'OpsiAshAssist', 'Event']                                         
INFO     21:37:46.027 │ [Task] Commission (Enable, 2022-12-31 23:58:11)            
INFO     21:37:46.029 │ Bind task {'General', 'Alas', 'Commission'}                
INFO     21:37:46.037 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     21:37:46.044 │ Connecting to local emulator, using host 192.168.0.105     
INFO     21:37:46.070 │ Reverse server listening on 192.168.0.105:20454, client can
         send data to 192.168.0.105:20454                                          
INFO     21:37:46.102 │ [nc command] ['busybox', 'nc']                             
INFO     21:37:46.329 │ [Screen_size] 1280x720                                     
INFO     21:37:46.443 │ <<< UI ENSURE >>>                                          
INFO     21:37:46.448 │ UI get current page                                        
INFO     21:37:46.761 │ Unknown ui page

**Comment by XuyuEre** [comment]
现在就是一切正常ORZ

**Comment by XuyuEre** [comment]
我初步怀疑是联通网络的锅，只要我使用办公室网络（联通）和我自己手机的联通卡热点，且同时打开alas设置里头“游戏内服务器”选择，就会卡我所说的error，只要换成电信卡热点 或者关闭“游戏内服务器”选择，就能正常使用了。。ORZ
        
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     09:38:29.869 │ Start scheduler loop: alas                                 
INFO     09:38:29.873 │ [Server] cn                                                
INFO     09:38:29.893 │ Bind task {'General', 'Alas'}                              
ERROR    09:38:30.044 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    09:38:30.049 │ Timeout while connecting to server checker API.            
INFO     09:38:30.330 │ [network_available] True                                   
INFO     09:38:30.334 │ Trigger fast retry.                                        
INFO     09:38:30.337 │ Retry 1 times ...                                          
ERROR    09:38:30.480 │ ConnectionError: ('Connection aborted.',                   
         ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', 
         None, 10053, None))                                                       
ERROR    09:38:30.484 │ Timeout while connecting to server checker API.            
INFO     09:38:30.487 │ Retry 2 times ...                                          
INFO     09:38:30.764 │ Server "十字路口行动" is available.                        
INFO     09:38:30.768 │ Retry 3 times ...                                          
INFO     09:38:30.882 │ Server "十字路口行动" is available.                        
INFO     09:38:30.888 │ Pending tasks: ['Restart', 'Commission', 'Tactical',       
         'Research', 'Exercise', 'Dorm', 'Meowfficer', 'Guild', 'Reward',          
         'ShopFrequent', 'ShopOnce', 'Freebies', 'OpsiExplore', 'OpsiAshBeacon',   
         'OpsiDaily', 'OpsiShop', 'OpsiAbyssal', 'OpsiStronghold', 'OpsiObscure',  
         'Daily', 'Hard', 'OpsiAshAssist', 'Event2']                               
INFO     09:38:30.896 │ [Task] Restart (Enable, 2023-01-02 00:00:00)               
INFO     09:38:30.900 │ Bind task {'General', 'Restart', 'Alas'}                   
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     09:38:32.907 │ DEVICE                                                     
INFO     09:38:32.911 │ [AdbBinary]                                                
         D:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     09:38:32.917 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     09:38:32.920 │ <<< DETECT DEVICE >>>                                      
INFO     09:38:32.923 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     09:38:32.927 │ emulator-5554                                              
INFO     09:38:32.931 │ emulator-5556                                              
INFO     09:38:32.934 │ emulator-5558                                              
INFO     09:38:32.936 │ [AdbDevice] AdbDevice(serial=emulator-5554)                
INFO     09:38:32.939 │ [PackageName] com.bilibili.azurlane

**Comment by sue950** [comment]
太感谢了，终于找到bug所在的地方了

**Comment by Buyu-hash** [comment]
同样是联通，也遇到了这个问题，目前已解决，感谢
