### ISSUE TITLE
alas嫌委托界面的滑动条长了一点点，反复拖动后抛出GameTooManyClickError

### ISSUE THREAD

**Issue by ec7529a2** [LmeSzinc/AzurLaneAutoScript#2059]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

扫描委托时alas认为滑动条没到底，于是反复将其向下拖动，但其实滑动条已经到底了，所以拖不动，然后因为一直尝试拖动滑动条，抛出GameTooManyClickError

### 如何复现

1. 运行委托任务，alas扫描委托
2. alas认为滑动条没到底，尝试把它拖到底，但实际已经到底了，所以拖不动
3. alas反复尝试拖动滑动条
4. GameTooManyClickError

### 预期行为

应该能正确识别滑动条已经到底了，或在认为它几乎到底且能正确扫描到委托时忽略那一点点差别

### 截图

[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10328230/error.zip)

### 还有别的吗？

可以通过在委托区域手动向上拖动来让右侧滑动条缩短一点，然后alas就能识别委托了，这一点挺让人无语的
另外，这个是最近出现的新问题，以前没有，我的error文件夹里的第一个关于这个错误的报告时间是1671797054697

**Comment by LmeSzinc** [comment]
ATX 的悬浮窗挡住了滚动条，我把 u2 里的开启悬浮窗的代码 patch 掉了，重启模拟器应该就没有这个悬浮窗了。

![image](https://user-images.githubusercontent.com/37934724/210166409-65847088-6003-4311-8f3a-b5529619cebe.png)

**Comment by ec7529a2** [comment]
已更新，ATX悬浮窗没了，alas能正确识别滚动条了，close
