### ISSUE TITLE
添加类似于任务优先级的功能

### ISSUE THREAD

**Issue by zxc7895531** [LmeSzinc/AzurLaneAutoScript#2078]
### 你的功能请求是否与问题有关？

活动时刷每日AB图很明显是要比活动时刷普通图重要的，但是我的ALAS会优先启动普通图再启动每日AB图，这样导致如果我不手动设置油量下限的话有大概率会错过每日的AB图，造成活动代币亏损

### 解决方案

在需要队伍出击的任务里添加一个优先级，如果两个任务都满足条件的话优先执行优先级别高的任务

**Comment by LmeSzinc** [comment]
每日活动ABCD图的任务，作为每日类任务，优先级是默认高于活动图和主线图的，如果你没有改过Alas代码的话应该不存在这个问题。默认任务优先级是 收菜类（委托科研）> 每日收菜类（商店抽卡） > 大世界类 > 每日出击类（潜艇图活动每日） > 活动 > 主线 > 浪费时间类（刷委托侵蚀一）
