### ISSUE TITLE
活动图无法选择活动.

### ISSUE THREAD

**Issue by superwdy** [LmeSzinc/AzurLaneAutoScript#2080]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

无法选择活动.

### 如何复现

1. 前往 '活动'-> 活动图
2. 点击 '活动名称' 的 dropdown list.
3. 点选任意活动
4. 出现问题

### 预期行为

活动名称全部grey out.无法选择.

所有活动task 均无法选择活动.

### 截图

![image](https://user-images.githubusercontent.com/7831954/210726187-2fd5f929-92e4-44ee-bff3-d132d46a4444.png)

**Comment by ec7529a2** [comment]
如果你是想让alas帮你打作战档案，请使用每日任务-作战档案。
![alas 每日任务-作战档案](https://user-images.githubusercontent.com/113332436/210734326-52a39fb7-e592-4b57-8edb-01bdaa55338a.png)

**Comment by WenFengx1** [comment]
I have the same problem too; As the new event is open, but I can't play it by this tool because I can't choose the map in Event

**Comment by WolfCanglong** [comment]
写死的 没法选 等更新
不过明明是旧活动为啥不做成可以选的，好像手动改了参数也会被同步回去

**Comment by LmeSzinc** [comment]
活动图需要等待更新
