### ISSUE TITLE
运行一段时间后，alas大量截图导致模拟器卡顿死机

### ISSUE THREAD

**Issue by KiminoKaslana** [LmeSzinc/AzurLaneAutoScript#2093]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

alas会在某次点击（click）后持续进行截图，而没有进一步反应，**期间不会尝试重新点击**，手动点击后恢复正常。这种异常导致模拟器卡顿，甚至死机，alas也会报错而停止。这种bug在运行一段时间后出现，alas会在长时间尝试后尝试重启游戏，但不能解决问题。在运行每月开荒和非周回模式推图时，更容易出现问题。

### 如何复现

使用alas进行未通关地图推图，直到模拟器出现掉帧。此时应当没有新的日志产生。

### 相关 Logs

```Text
INFO     15:31:38.639 │ Using fleet: [3, 2, 0]                                     
INFO     15:31:38.640 │ [Light_orange_line] 4                                      
INFO     15:31:38.641 │ Hard Campaign. No fleet preparation                        
INFO     15:31:38.643 │ Click (1106,  610) @ FLEET_PREPARATION                     
WARNING  15:32:38.826 │ Wait too long                                              
WARNING  15:32:38.828 │ Waiting for {'AUTO_SEARCH_MENU_CONTINUE',                  
         'RETIRE_APPEAR_1', 'MAP_PREPARATION', 'AUTO_SEARCH_MENU_EXIT',            
         'EVENT_CHECK', 'VOTE_CANCEL', 'SP_CHECK', 'GET_MISSION',                  
         'GUILD_POPUP_CONFIRM', 'GAME_TIPS', 'IN_MAP', 'CAMPAIGN_CHECK',           
         'FLEET_PREPARATION', 'STORY_SKIP', 'BOOK_POPUP_CHECK',                    
         'STORY_LETTER_BLACK', 'IN_RETIREMENT_CHECK'}
```

**Comment by LmeSzinc** [comment]
需要上传由 Alas 保存的错误log和截图，在 /log/error 目录下

**Comment by KiminoKaslana** [comment]
截图全黑，完整log如下
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10380462/log.txt)
但报错时发现模拟器和adb服务是正在运行的

**Comment by KiminoKaslana** [comment]
> 需要上传由 Alas 保存的错误log和截图，在 /log/error 目录下

截图全黑，完整log如下
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10380462/log.txt)
但报错时发现模拟器和adb服务是正在运行的

**Comment by KiminoKaslana** [comment]
提供一些个人的推测供参考：测试后发现，一开始使用的ADB_nc方案在运行一段时间后截图返回的始终为黑图，最慢的ADB方案目前在长时间运行的情况下返回正常。初步怀疑是nc本身缺陷。

**Comment by LostMyMind** [comment]
我之前遇到过模拟器卡死导致截图是黑色的情况，会不会也是这样？

**Comment by LostMyMind** [comment]
我之前遇到过模拟器卡死导致截图是黑色的情况，你会不会也是这样？是因为卡死黑屏导致不断截图，而不是不断截图导致卡死。

**Comment by KiminoKaslana** [comment]
> 我之前遇到过模拟器卡死导致截图是黑色的情况，你会不会也是这样？是因为卡死黑屏导致不断截图，而不是不断截图导致卡死。

测试过，应该不是。报错期间模拟器因为截图掉帧，但是仍然在运行。停止alas后运行也很正常。
