### ISSUE TITLE
功能请求：希望修改强制开启任务的尝试次数或者最大运行时间

### ISSUE THREAD

**Issue by Liudegloire** [LmeSzinc/AzurLaneAutoScript#2104]
### 你的功能请求是否与问题有关？

石油溢出时委托任务会重复尝试获取奖励，无法获取奖励将会一直卡在这里，尝试通过修改配置文件template.json中关于委托的部分，重启时又会自动改回未修改的状态

### 解决方案

想知道是否可以通过修改配置文件来让跳过这个阶段

### 其他内容

![image](https://user-images.githubusercontent.com/39121540/211717170-b2556e14-b0b8-4fc6-be9b-d074ce9d76d4.png)
![image](https://user-images.githubusercontent.com/39121540/211717198-f9bd1da3-7bb1-493b-a207-197125dde766.png)

**Comment by LmeSzinc** [comment]
去后宅买 2000 油咖喱
