### ISSUE TITLE
B系列科研

### ISSUE THREAD

**Issue by cyx2499** [LmeSzinc/AzurLaneAutoScript#2107]
B系列科研会被alas主动取消，原因是：

1. 不能保证研究条件被完成
2. 基于1，没有完成前置无法加入队列，可能会出现阻塞导致后续无法进行
3. B系列的收益较低

如果你**手动选择**了B类科研，请**自行完成**前置并等待队列有空时**手动加入**。

_Originally posted by @Horizon101011 in https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1855#issuecomment-1312493714_
在我本就有刷图需求的情况下，做B系列相当于不需要除了时间以外的任何成本，11图以上的B系列我觉得收益还是可观的。在alas的活动图设置中有防止物资过少的“任务平衡设置”，可以呼叫提前设置好的主线图，是否可以仿照这个让科研在选择11图以上的B系列时呼叫主线图完成任务呢？

**Comment by LmeSzinc** [comment]
原因你也列举出来了，增加工作量却不带来收益的功能是不会被开发的。

[azur-stats.lyoko.io](https://azur-stats.lyoko.io/) 每年接收上百万掉落上传，只有五十来的 B 系样本，海事局人工统计还需要特意安排人做 B 系才有样本，说 B 系列的收益较低都是高情商了，这玩意就是没人做的狗屎。
