### ISSUE TITLE
请求添加Hermit开启无障碍模式的横屏识别

### ISSUE THREAD

**Issue by eTATr** [LmeSzinc/AzurLaneAutoScript#2113]
### 你的功能请求是否与问题有关？

用VMOS只有竖屏才能自动开启和识别Hermit的无障碍模式，横屏就会报错。但在平放手机的情况下，我的VMOS在alas打开碧蓝航线后再去开启Hermit会自动是横屏模式，导致报错。

### 解决方案

希望横屏也可以开启和识别Hermit的无障碍模式，或者在选择Hermot模式时能单独设置是否检查Hermit的无障碍模式
临时解决办法：①竖放手机；或②手动打开Hermit的无障碍（或者用无障碍-Daemon等软件锁定无障碍权限），然后存一份AzurLaneAutoScript\module\device\method下删掉#ENABLE ACCESSIBILITY SERVICE的内容（现在是123 124行）的hermit.py，并每次打开alas后都要覆盖一下hermit.py或打开再删一次。

### 其他内容

INFO     15:49:35.767 │ <<< APP RESTART >>>                                        
INFO     15:49:35.769 │ App stop: com.bilibili.blhx.mi                             
INFO     15:49:36.790 │ App start: com.bilibili.blhx.mi                            
INFO     15:49:38.020 │ <<< APP LOGIN >>>                                          
INFO     15:49:38.120 │ [Device Orientation] 1 (HOME key on the right)             
INFO     15:49:38.733 │ [Screen_size] 1280x720                                     
INFO     15:49:43.542 │ [Device Orientation] 1 (HOME key on the right)             
INFO     15:49:48.743 │ [Device Orientation] 1 (HOME key on the right)             
INFO     15:49:53.899 │ [Device Orientation] 1 (HOME key on the right)             
INFO     15:49:56.205 │ Click ( 495,  371) @ LOGIN_CHECK                           
INFO     15:49:56.209 │ Create forward: ForwardItem(serial='192.168.68.123:5668',  
         local='tcp:20256', remote='tcp:9999')                                     
ERROR    15:49:56.293 │ HermitError: {'code': -1, 'msg': 'error'}                  
INFO     15:49:56.299 │ disconnected 192.168.68.123:5668                           
INFO     15:49:56.312 │ connected to 192.168.68.123:5668                           
INFO     15:49:56.316 │ <<< DETECT DEVICE >>>                                      
INFO     15:49:56.321 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     15:49:56.326 │ 192.168.68.123:5668                                        
INFO     15:49:56.330 │ <<< HERMIT INIT >>>                                        
INFO     15:49:57.286 │ Try to start hermit                                        
INFO     15:49:58.905 │ Success to start hermit                                    
INFO     15:49:58.908 │ <<< ENABLE ACCESSIBILITY SERVICE >>>                       
CRITICAL 15:50:22.055 │ Unable to turn on accessibility service for Hermit         
CRITICAL 15:50:22.057 │                                                            
                                                                                   
         Please do this manually:                                                  
         1. Find "Hermit" in accessibility setting and click it                    
         2. Turn it ON and click OK                                                
         3. Switch back to AzurLane                                                
                                                                                   
CRITICAL 15:50:22.063 │ Retry click_hermit() failed                                
CRITICAL 15:50:22.065 │ Request human takeover                                     
INFO     15:50:22.211 │ Push notify success                

![QQ图片20230113161944](https://user-images.githubusercontent.com/83582854/212272183-a7af5716-9e25-4f66-8d35-9cd05047826c.jpg)
![QQ图片20230113161949](https://user-images.githubusercontent.com/83582854/212272211-2f7b9757-c5c8-46c0-a075-5d5b8a874093.jpg)

**Comment by LmeSzinc** [comment]
把这些奇奇怪怪的东西删掉，找不到 Hermit 的元素
```python
            if appear_then_click('//*[@text="Hermit" and @resource-id="android:id/title"]'):
                continue
```

![image](https://user-images.githubusercontent.com/37934724/212331646-7f4cbb9e-9801-4b16-94ce-70727a114e95.png)

**Comment by eTATr** [comment]
> 把这些奇奇怪怪的东西删掉，找不到 Hermit 的元素
> 
> ```python
>             if appear_then_click('//*[@text="Hermit" and @resource-id="android:id/title"]'):
>                 continue
> ```
> 
> ![image](https://user-images.githubusercontent.com/37934724/212331646-7f4cbb9e-9801-4b16-94ce-70727a114e95.png)

可以了，删了几个再把DPI改成了240露出Hermit就好了，感谢
