### ISSUE TITLE
现在短猫里的”保留 X 点行动力“设置在开启侵蚀1练级后强制为1000了

### ISSUE THREAD

**Issue by LostMyMind** [LmeSzinc/AzurLaneAutoScript#2117]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我现在行动力2500点，短猫里保留 X 点行动力设置的是3000，开启了侵蚀1练级。
但是最近某次更新后，在开启侵蚀1练级的情况下，保留X点行动力的设置似乎强制变成了1000，只要高于1000，哪怕自己设置的是3000，也会自动短猫而不是侵蚀1练级
```
INFO     14:41:33.944 │ Action points: 79(2569), oil: 12329                                                                     
INFO     14:41:33.949 │ Having enough action points         
```

### 预期行为

已有低于自己在短猫设置里的行动力，则开始侵蚀1练级，而不是写死1000点

### 相关 Logs

```Text
════════════════════════════════════════════ OS MEOWFFICER FARMING, HAZARD_LEVEL=5 ═════════════════════════════════════════════
INFO     14:41:33.195 │ OS MEOWFFICER FARMING, HAZARD_LEVEL=5                                                                   
INFO     14:41:33.198 │ [OpsiNextReset] 2023-02-01 00:00:00                                                                     
INFO     14:41:33.202 │ [ResetRemain] 17                                                                                        
INFO     14:41:33.206 │ Not close to OpSi reset                                                                                 
INFO     14:41:33.210 │ [OpsiNextReset] 2023-02-01 00:00:00                                                                     
INFO     14:41:33.214 │ [OpsiExplore] (False, datetime.datetime(2020, 1, 1, 0, 0))                                              
INFO     14:41:33.219 │ Not in OpsiExplore, able to do OpsiDaily                                                                
INFO     14:41:33.223 │ [OS_ACTION_POINT_PRESERVE] 2000                                                                         
INFO     14:41:33.244 │ Click ( 897,   36) @ ACTION_POINT_REMAIN_OS                                                             
INFO     14:41:33.890 │ [Amount_ocr 0.122s] [12329, 57, 17, 5]                                                                  
INFO     14:41:33.938 │ [ACTION_POINT_REMAIN 0.043s] 79                                                                         
INFO     14:41:33.944 │ Action points: 79(2569), oil: 12329                                                                     
INFO     14:41:33.949 │ Having enough action points                                                                             
INFO     14:41:33.954 │ <<< UI CLICK >>>
```

**Comment by LmeSzinc** [comment]
和 #2092 一样，你需要理解 ① 侵蚀一消耗黄币，获取经验和行动力 ② 侵蚀五消耗行动力，返回部分黄币，获取金菜和经验，这样一个玩法循环，循环的最终结果是消耗黄币，获取金菜和经验。Alas 会自动保持这两个任务的动态平衡，只做①不做②是不行的。

**Comment by qingtonshidai** [comment]
我也是遇到上面的问题，就是常遇到行动力不足的问题，我其实更侧重刷世界1，因为会出红尖尖委托，所以设置保留10000行动力，目的是为了一直刷世界1，等黄币不够或月底再刷短猫，现在凌晨0点就会刷短猫，早上起来一看，只有400左右的行动力了，现在我没行动力了。这种强制刷短猫的感觉很难受，希望可以优化一下。

**Comment by LmeSzinc** [comment]
@qingtonshidai 我上面已经表达清楚了，请不要让我再重复一遍

**Comment by LmeSzinc** [comment]
[侵蚀1攻略先行版.docx](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10417921/1.docx)

**Comment by qingtonshidai** [comment]
我理解您的“留1000行动力和100000黄币，防止因为运气差耗尽行动力和买不起港口商店。”设计，但问题是每次它强制刷短猫就会导致我行动力不足，而黄票20w+，然后几天后才有足够的行动力能一晚上刷世界1。
而问题就出在它会不顾我预设的保留10000行动力，去刷短猫，导致行动力不足。
您对世界1和短猫的理解我能接受，但我想应该还是有一些像我一样主要注重刷红尖尖委托而不是短猫收益的玩家，我想优先的是行动力，而不是黄票。
仅代表个人观点，希望能保证更多的行动力。而不是强制1000。

**Comment by qingtonshidai** [comment]
-
![Screenshot_20230114-231610](https://user-images.githubusercontent.com/107467978/212479188-fa146663-d8cc-4711-9b89-b614a838a7ad.png)
![Screenshot_20230114-231613](https://user-images.githubusercontent.com/107467978/212479190-218b5e57-0348-41ee-b6ee-617d75cdeda2.png)
这就是我最终被强制运行短猫的结果

**Comment by LmeSzinc** [comment]
刷委托应该使用 `刷紧急委托` 任务，为什么不在侵蚀一刷委托？因为打得太慢（指出击数/小时），更不要说2-4还有BOSS点，委托掉率是小怪的3倍多。配合 `防止紧急委托数量过多` 的设置，可以与侵蚀一同时运行，作为游戏后期的挂机内容。话题已经偏了，这些内容与这个issue无关。

**Comment by qingtonshidai** [comment]
好的，您是对的，不打扰您了

**Comment by SaiCateDoan** [comment]
首先，强制的部分是2000而不是1000，正常情况下2000行动力还会刷空的情况非常罕见
然后，侵蚀1需要短猫提供的黄币维持，如果短猫行动力设的太高会因为黄币不足导致侵蚀1提前停止
最后，这个月的侵蚀1产出我体感很有问题，现在我正在寻找原因并尝试修复 #2120 
如果下个月还是数据异常就要怀疑官方暗改了侵蚀1的收益，需要重新进行数据统计

**Comment by LostMyMind** [comment]
> 首先，强制的部分是2000而不是1000，正常情况下2000行动力还会刷空的情况非常罕见 然后，侵蚀1需要短猫提供的黄币维持，如果短猫行动力设的太高会因为黄币不足导致侵蚀1提前停止 最后，这个月的侵蚀1产出我体感很有问题，现在我正在寻找原因并尝试修复 #2120 如果下个月还是数据异常就要怀疑官方暗改了侵蚀1的收益，需要重新进行数据统计

那这个说明要不要改一下“行动力低于 X 后停止，自动打开行动力箱子，X 包含箱子中的行动力，建议保留1000行动力给侵蚀1练级
这个值将在大世界重置前3天自动减少至200点，如果启用侵蚀1练级则改为1000点，并在最后一天自动减少至0点”
这个地方说侵蚀1是1000点

**Comment by SaiCateDoan** [comment]
> > 首先，强制的部分是2000而不是1000，正常情况下2000行动力还会刷空的情况非常罕见 然后，侵蚀1需要短猫提供的黄币维持，如果短猫行动力设的太高会因为黄币不足导致侵蚀1提前停止 最后，这个月的侵蚀1产出我体感很有问题，现在我正在寻找原因并尝试修复 #2120 如果下个月还是数据异常就要怀疑官方暗改了侵蚀1的收益，需要重新进行数据统计
> 
> 那这个说明要不要改一下“行动力低于 X 后停止，自动打开行动力箱子，X 包含箱子中的行动力，建议保留1000行动力给侵蚀1练级 这个值将在大世界重置前3天自动减少至200点，如果启用侵蚀1练级则改为1000点，并在最后一天自动减少至0点” 这个地方说侵蚀1是1000点

1000是下限，2000是上限，如果低于1000也会强制改成1000，2000是后面加的，没写进说明里

**Comment by SaiCateDoan** [comment]
#2170
