### ISSUE TITLE
MAA插件的战斗排班功能

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2125]
### 解决方案

合并清理智与刷材料，统一为战斗；
内置时间表；
允许ALAS控制MAA根据用户的设置每日自动更新用户已设置的每日目标；
比如周一打什么本，打多少，周二打什么本打多少，每日凌晨4：00自动替换为当日目标，其中，3：50停止执行任何已设置的消耗理智的任务
否则设置到未开放的本又会报错

**Comment by SaiCateDoan** [comment]
这是一个很好的想法，但是我没有精力做，希望有人帮忙实现

**Comment by LmeSzinc** [comment]
![image](https://user-images.githubusercontent.com/37934724/213135416-c5c3decf-b8e2-4cd1-a853-5269473fae8a.png)
