### ISSUE TITLE
无法刷取傀影肉鸽等级，出现重复操作，进入肉鸽后会直接进入水月肉鸽，然后退出

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2126]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

[asst.log](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10423716/asst.log)
从今日15:44开始往前，好长一段时间都是这样

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/103177863/212628501-e66deaeb-3f7c-453d-a0c7-9bc163444e76.png)
![image](https://user-images.githubusercontent.com/103177863/212628641-b3295f48-4bf4-4fc6-9d43-04dda91d9459.png)

### 还有别的吗？

同时还有
![image](https://user-images.githubusercontent.com/103177863/212596346-79276230-104c-4e61-a7d7-348d7270b6f9.png)
![image](https://user-images.githubusercontent.com/103177863/212596474-e6ce9b9e-7b39-43dd-b47c-0d61513519d2.png)
以及重复出现的配置文件

**Comment by SaiCateDoan** [comment]
TouchModeNotAvailable是设备不支持minitouch，如果是偶然发生，有可能是抽风导致的误报
无法刷傀影肉鸽是因为我漏了一条提示，需在集成战略界面手动将对应主题添加到终端

**Comment by ChthoIly** [comment]
Alas还能刷方舟？

**Comment by HS7097** [comment]
> TouchModeNotAvailable是设备不支持minitouch，如果是偶然发生，有可能是抽风导致的误报 无法刷傀影肉鸽是因为我漏了一条提示，需在集成战略界面手动将对应主题添加到终端

好的，已经解决了
