### ISSUE TITLE
希望Alas可以增加MAA配置文件的启动自运行支持

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2133]
### 你的功能请求是否与问题有关？

我不太清楚这是否是bug或是配置错误qwq
启动后所有配置文档都自动运行alas本体相关的功能，
并未正确按照配置文档运行MAA插件相关的功能
希望大佬们可以看一下

### 其他内容

![image](https://user-images.githubusercontent.com/103177863/212811668-85656019-0025-4f26-b5c5-d32d08200086.png)
![image](https://user-images.githubusercontent.com/103177863/212811703-b1c3aceb-23f8-4c8f-8dfe-bbdb1b34af81.png)
![image](https://user-images.githubusercontent.com/103177863/212811757-1750690c-5d7d-4110-b784-88c374905d01.png)
![image](https://user-images.githubusercontent.com/103177863/212811794-1fc9a792-c4a3-4492-b8d2-7b2e0e253988.png)
============================
Run: maa3 , maa2 , maa1 , alas

**Comment by SaiCateDoan** [comment]
#2135 在修了
另外这个bug可能导致出现maa1.maa.json和maa1.json同时存在并导致更加复杂的问题
请手动删除maa1.json

**Comment by HS7097** [comment]
> #2135 在修了 另外这个bug可能导致出现maa1.maa.json和maa1.json同时存在并导致更加复杂的问题 请手动删除maa1.json

那是否可以将Alas的json与MAA的json统一为Alas格式的json？
仅在文件内容中标注出需要用的模块，未标注的默认使用Alas模块qwq
~~不过应该非常麻烦~~
