### ISSUE TITLE
不到一定等级没解锁指挥喵栏主线出击会被卡住

### ISSUE THREAD

**Issue by senarenako** [LmeSzinc/AzurLaneAutoScript#2145]
### 你的功能请求是否与问题有关？

出击的时候右边等级不够的话只有编队职能。所以会点到下面空白然后无限卡死

### 解决方案

希望能在舰队职能选择上设置一个不设置。
这样就不会卡死到那里。
虽说购买直升70级可以解决问题。
但可以的话希望能让功能更完善。

**Comment by LmeSzinc** [comment]
Alas 不支持低等级帐号的运行
