### ISSUE TITLE
开发船坞彩船和金船免费图纸都买

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#2149]
### 你的功能请求是否与问题有关？

摘自[1月18日9:00港区改建公告](https://wiki.biligame.com/blhx/2023%E5%B9%B41%E6%9C%8818%E6%97%A59:00%E6%B8%AF%E5%8C%BA%E6%94%B9%E5%BB%BA)：

> 科研三期【最高方案】方案舰及科研二期【决战方案】方案舰当没有足够蓝图进行养成时，可以通过物资进行养成；
> ※暂不可使用物资购买科研三期【决战方案】方案舰的蓝图；
> ※免费和折扣次数为所有开启了此功能的方案舰共享，每日4点重置；
> ※【决战方案】方案舰和【最高方案】方案舰的免费和折扣次数将**独立计算**，所需物资数量不同；

目前alas的开发船坞功能一天只能买一艘船的图纸，希望能处理同时买金船和彩船的情况。

**Comment by szjawo** [comment]
同求此功能，现在彩船也可以用金币买图纸了，而且每天的折扣图纸是跟金船分开算的。开发船坞可以增加一个对彩船图纸的购买项目，或者简单点直接加一个船，让用户自己设置
