### ISSUE TITLE
大世界行動點異常消耗

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#2151]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我的設定預留1200點但起床只剩120點了，因為功能也算是成功運行所以沒有log
有什麼我可以提供的我會再上傳

### 如何复现

運行侵蝕1/短貓

### 预期行为

少於1200就停止

### 截图

![image](https://user-images.githubusercontent.com/29662367/213368612-74d75d6c-da81-4295-b3b7-1c8d0a137583.png)

**Comment by bookbug666** [comment]
[2023-01-19_alas2.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10453992/2023-01-19_alas2.txt)
試著清空日期逼他重新辨識，但這次是正常的
~~算是偶發嗎~~

**Comment by LostMyMind** [comment]
这个的意思应该是指短猫到1200点行动力之后开启侵蚀1练级，所以估计是你行动力被短猫到1200后侵蚀1一直练级耗到了120

**Comment by bookbug666** [comment]
> 这个的意思应该是指短猫到1200点行动力之后开启侵蚀1练级，所以估计是你行动力被短猫到1200后侵蚀1一直练级耗到了120

如果是那樣還好辦，~~問題原本就不是那樣運作的~~，我實際運行也證明了實際並不是那樣運作
![image](https://user-images.githubusercontent.com/29662367/213487633-7fa003b0-445d-411c-9825-b1347c13e390.png)
我的短貓改回1000停止了，他運行的log是這樣
[2023-01-19_alas3.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10458259/2023-01-19_alas3.txt)
除了這幾天的更新，我就只有更新了mumu本身並且換了截圖方法到ADB，僅此

**Comment by bookbug666** [comment]
#2170
