### ISSUE TITLE
当金币不足以购买预设的每日科研图纸时程序异常

### ISSUE THREAD

**Issue by Mo-Yuxi** [LmeSzinc/AzurLaneAutoScript#2158]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当金币量不足以购买预设数量的一/二期科研图纸时，程序会反复点击直到报错

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
需要提供log和截图

**Comment by Mo-Yuxi** [comment]
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10527010/log.txt)
![2023-01-27_14-51-23-503397](https://user-images.githubusercontent.com/80117830/215262106-af86b1f2-e575-4a1b-b64c-fcae000153d3.png)
错误日志及对应截图上传

**Comment by Mo-Yuxi** [comment]
alas上相关参数为：购买数量6

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2177#issuecomment-1408299698
