### ISSUE TITLE
无法启动alas

### ISSUE THREAD

**Issue by SaigyoujiYukon** [LmeSzinc/AzurLaneAutoScript#216]
无法启动alas，显示命令语法不正确

**Comment by SaigyoujiYukon** [comment]
![Uploading image.png…]()

**Comment by LmeSzinc** [comment]
请提供详细信息

**Comment by SaigyoujiYukon** [comment]
![20201003232204](https://user-images.githubusercontent.com/40208202/94995235-94ef1e00-05cf-11eb-9470-587e4eaf4e50.png)
无了，也不知道咋获取更多信息

**Comment by whoamikyo** [comment]
Try not use powershell, open console.bat on alas root path, then type alas.bat and press enter.
