### ISSUE TITLE
关于侵蚀1的两个疑问

### ISSUE THREAD

**Issue by icateav** [LmeSzinc/AzurLaneAutoScript#2168]
侵蚀1的随机商店只买体力不买紫币是设定如此还是我不小心改了设置导致的？如果希望它买紫币要如何设置？
然后为什么我开侵蚀1以后一路刷到体力箱子就只剩5个20了（不是说体力消耗略等于支出吗）都没体力打隐秘和深渊了

**Comment by LostMyMind** [comment]
就是设定，没法设置，除非硬改代码
运气在平均值的情况下是回体与消耗差不多，但是也有越打越多和越打越少的情况，比如你就是第二种（

**Comment by SaiCateDoan** [comment]
#2170
