### ISSUE TITLE
在获得新船 new 的时候使用onepush通道通知一条信息

### ISSUE THREAD

**Issue by wosiwq** [LmeSzinc/AzurLaneAutoScript#2174]
### 你的功能请求是否与问题有关？

希望在获得新船的时候可以收到推送

### 解决方案

在获得新船的时候触发一次onepush通道的推送

**Comment by LmeSzinc** [comment]
目前新船的识别是颜色识别，可能有随机图像命中这个颜色区间，非常多的模块也在复用 handle_get_ship 方法，增加推送会导致 spam

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/cdff9f61fc96ca7cd10659176d36088a4e26da44/module/combat/combat.py#L365-L381

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/cdff9f61fc96ca7cd10659176d36088a4e26da44/module/combat/combat.py#L431-L435

**Comment by wosiwq** [comment]
如果是真的获取到新船，会有一个确认锁定的弹窗，是否考虑在识别到确认锁定后再发送以此来规避spam呢
