### ISSUE TITLE
希望优化【开发船坞】中购买图纸功能的逻辑

### ISSUE THREAD

**Issue by TarringFox** [LmeSzinc/AzurLaneAutoScript#2177]
### 你的功能请求是否与问题有关？

现在游戏内开发船坞中新增加了“决战方案”（DR）的物资追赶功能，追赶这类舰船时，物资的消耗也会显著提高，且此类型舰船的养成周期更长
如果玩家的物资不足时，alas进行开发船坞的任务时会卡住，不再进行之后的任务
因此希望能优化目前的“开发船坞”功能的逻辑

### 解决方案

在“开发船坞”功能中增加类似于“科研”功能里的“资源不足时延迟科研”选项，将运行开发船坞的任务延后数十分钟或数个小时
预期行为：【在数次点击后，识别到追赶次数与预期不符，将“开发船坞”任务延后数十分钟或数个小时】

或者

在“开发船坞”功能增加类似于“演习”功能中的“今日已刷新对手X次”功能，在物资暂时不足时，alas能够先购买一部分图纸，并记录下已经购买的次数，之后数十分钟或十个小时后再次运行补足剩下的部分，并且于每日刷新折扣次数时将已购买次数清零
【记录下当前的使用的追赶数目，点击确认以当前可用的追赶次数进行物资追赶，并记录目前已经购买的次数，同时将“开发船坞”任务延后数十分钟后或数个小时，再次运行任务时购买剩下的部分，如果依然卡住可以累加计算今日已购买数量，直到已购买数满足设置条件，已购买次数在每日的4点之后重置为0】

我认为两个方案均有现成且已实现的功能可供参考，可行性很高

**Comment by wosiwq** [comment]
#2149

**Comment by wosiwq** [comment]
#2158

**Comment by LmeSzinc** [comment]
> 如果玩家的物资不足时，alas进行开发船坞的任务时会卡住，不再进行之后的任务

这是因为金彩图纸价格不一样，alas按金图纸的价格去预估，但买的是彩图纸。现在单独增加了彩图纸的购买就没有问题了
