### ISSUE TITLE
侵蚀一增加消耗/产出行动力统计

### ISSUE THREAD

**Issue by icateav** [LmeSzinc/AzurLaneAutoScript#2181]
### 你的功能请求是否与问题有关？

我光知道我打侵蚀一亏了体力，但具体亏了多少我也不清楚，希望能做一个功能记录体力消耗和产出，弄清楚每次（每个月）到底亏多少

### 解决方案

任务开始时把读取到的当前行动力（总行动力）记录下来展示，根据结束时剩余的行动力对比计算消耗的行动力，或者根据战斗次数计算行动力消耗（以免任务被手动中断导致计算失败，不过被其他任务中断的话战斗会暂停，log里的战斗次数也会重新统计，战斗次数好像会+1？）

购买时记录购买的体力箱子，计算产出行动力

**Comment by LmeSzinc** [comment]
#2178
