### ISSUE TITLE
演习赛季结束前清空剩余演习次数

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#2184]
### 你的功能请求是否与问题有关？

目前Alas的演习中若设置了保留X次演习次数，那么ocr到剩余X/10时就会停止；
当X为1～5时，alas会在赛季剩余6小时（最后一次刷新）后打演习到剩X次，这造成了90*x功勋值的浪费。当X大于5时，这会在每次演习次数刷新时造成浪费。

（可能涉及游戏玩法讨论，下略）

### 解决方案

增加对赛季剩余时间的ocr，并在赛季结束前清空演习次数（类似大世界剩余2天后会强制覆盖行动力保留量的操作）

### 其他内容

如下图，右上角的“演習期間”。
<img width="640" alt="cp-ph15an0dbzr654 (2)" src="https://user-images.githubusercontent.com/50830808/215318034-7d7c00b8-8c29-4beb-813a-a9a5489329e7.png">

**Comment by LmeSzinc** [comment]
#953 曾经有过演习憋分的 PR，但是后来摆了

**Comment by guoh064** [comment]
这个写的全面点就是自定义憋分（定义冲榜时间），但是卡点冲榜不太稳定（容易打输），应该推荐手打；但如果每次都是刷新之后就打的话是可以考虑alas接管策略的；
写的懒一点可以只写在第二周周日18点刷新后把冗余次数打完，其余时候该留就留，该浪费就浪费……
当然真正的懒人（我）在的服务器是可以每个赛季保留0次让alas摆烂上五星上将的；
但是不留次数也是因为发现留次数会亏最后那五次；最近买布里花了不少功勋所以还是抠点吧；
我也在实验如果alas保留五次能到什么水平，如果不行的话就考虑0次摆烂+关掉这个issue了。
