### ISSUE TITLE
能添加对BlueStacks5的Hyper-V Pie64版的支持么

### ISSUE THREAD

**Issue by WolfCanglong** [LmeSzinc/AzurLaneAutoScript#2188]
### 你的功能请求是否与问题有关？

最新BlueStacks 5的Hyper-V版支持Pie64了，个人感觉比Nougat64快（起码重启时候登录帐号不用卡半天）
不过ALAS好像不能支持Pie64的？模拟器Serial写bluestacks5-hyperv还是对Nougat64操作的 还是说有特殊写法？

### 解决方案

![image](https://user-images.githubusercontent.com/40590525/215643653-0ccc246b-081b-464e-8efc-6dcc03b90e59.png)
应该就是bluestacks.conf这里识别改一下吧？希望能加个支持Pie64的模拟器Serial写法

**Comment by LmeSzinc** [comment]
Nougat64 和 Pie64 的实例序号是分别自增还是共用一个自增序号？两种实例都新建 3 个，生成的配置文件发来看看

**Comment by WolfCanglong** [comment]
> 

[bluestacks.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10552509/bluestacks.zip)
看起来是共用的 不过第一个引擎都是没有序号的

**Comment by WolfCanglong** [comment]
试了下多开的可以用了
不过还有个小瑕疵，就是如果同时存在Nougat64 Pie64，写bluestacks5-hyperv只会读Nougat64的，要么多开要么只能把其中一个的全删掉（删掉第一个所有那个版本的多开都会消失）影响不大就是了，不过说明里最好写下不然碰到的可能会摸不着头脑
