### ISSUE TITLE
在电脑意外断开网络后，停止运行

### ISSUE THREAD

**Issue by BSJJC** [LmeSzinc/AzurLaneAutoScript#2189]
### 解决方案

在断开网络连接、并尝试重连一定次数后，停止尝试

### 其他内容

![MuMu20230131133508](https://user-images.githubusercontent.com/95690003/215675539-fe26eff2-a5eb-43cd-aa55-9597f6ac25b0.png)
![屏幕截图 2023-01-31 133534](https://user-images.githubusercontent.com/95690003/215675549-6c867928-8811-4277-9ac2-62f65129651c.png)

**Comment by LmeSzinc** [comment]
Alas 能在 电脑无网络连接 或者 游戏服务器维护 的时候保持等待，并在 电脑网络连接恢复 或者 游戏服务器维护结束 的时候，自动登录游戏并恢复运行。因此在无网络的情况下继续保持运行是正常的。
