### ISSUE TITLE
强化指挥猫不会过滤掉已满级的指挥猫

### ISSUE THREAD

**Issue by KbClownxxx** [LmeSzinc/AzurLaneAutoScript#2211]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

强化指挥猫不会过滤掉已满级的指挥猫，会一直重复选择指挥猫，强化的步骤

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![QQ截图20230204172218](https://user-images.githubusercontent.com/56860845/216759549-97b46899-625c-4549-b745-f00e04212acb.png)

**Comment by LmeSzinc** [comment]
需要提供游戏内的截图

**Comment by KbClownxxx** [comment]
![image](https://user-images.githubusercontent.com/56860845/216763396-53451a7a-deeb-42b4-9305-286e2bbb37ab.png)

**Comment by KbClownxxx** [comment]
手动取消后也不会顺位到下一个指挥猫

**Comment by KbClownxxx** [comment]
只能自己发现了再改
