### ISSUE TITLE
MAA插件运行速度不佳

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2213]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

以前MAA插件的任务很少因此感觉并不是特别明显
我没有用过MAA本体，因此并不能判断是否符合预期QwQ
对整体的使用并无特别明显的影响

### 如何复现

开始运行MAA插件后，有些任务在调度器中显示正在运行，但实际上没有响应
卡顿时间从窗口中的日志上来看有最长的有2.30min
多开模拟器后更加明显
已尝试的解决办法有为每个模拟器与配置文件分配不同的MAA路径

### 预期行为

立即执行任务（生稀盐酸影响/相关除外）

### 截图

https://drive.google.com/file/d/1F_u90XyscFTFAC8CkIsVojljmPXFH63z/view?usp=share_link

### 还有别的吗？

模拟器：蓝叠 Pie 64bit 
Windows Server 2022
9700KF 32G RX590

**Comment by SaiCateDoan** [comment]
由于我没有使用过MAA进行多开，只是从MAA开发那边得知可以多开
因此这个issue可能开在MAA那边更好
好像也有其他人反馈python多开MAA时出现问题的

**Comment by SaiCateDoan** [comment]
提供一下log，包括maa安装文件夹里的maa log

**Comment by HS7097** [comment]
> 提供一下log，包括maa安装文件夹里的maa log

[日志文件.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10610993/default.zip)
今日18时左右MAA插件还出现了一个导致停止运行的错误，因不在未及时查看，所以并不知道是如何造成的
还请帮忙看一下QwQ

**Comment by SaiCateDoan** [comment]
注意到maa1跟maa2都出现了无法截图的情况，你可以拿这两个log去MAA那边开一个issue

**Comment by Shawnsdaddy** [comment]
> > 注意到maa1跟maa2都出现了无法截图的情况，你可以拿这两个log去MAA那边开一个issue
> 
> 好的，谢谢大佬

我的好像是点击失效？？

@HS7097 ,,, 我通过在python 中maa任务结束以后把maa instance 设置成None，，解决了这个问题。。
如果MAA没时间的话ALAS可以尝试一下我这个办法。。

https://github.com/Shawnsdaddy/arknights-mower/blob/4.8.0/arknights_mower/solvers/base_schedule.py#L1623
