### ISSUE TITLE
大世界商店

### ISSUE THREAD

**Issue by shenqimolisha** [LmeSzinc/AzurLaneAutoScript#2217]
如题，我眼睁睁看着它拿紫币买了东西。黄币的东西它是一点不碰啊，紫币不多，买买就没了。黄币还有20w。可你却不买一个2w的20紫币，我不是很理解AI，它就用黄币买了行动力和坐标，兑换紫币它是一点不兑换啊。储物仓里的普通海域坐标它也不刷，那它买了干嘛啊...

**Comment by LmeSzinc** [comment]
如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
