### ISSUE TITLE
无法识别石油

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2223]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

13/4战斗中会出现无法识别石油的日志

并不确定其他地图是否会复现

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
──────────────────────── BATTLE_6 ─────────────────────────
INFO     14:08:54.844 │ BATTLE_6                           
INFO     14:08:54.845 │ Auto search moving                 
INFO     14:08:54.849 │ Fleet: 2, fleet_current_index: 1   
WARNING  14:08:54.876 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:54.878 │ [OCR_OIL 0.027s] 0                 
WARNING  14:08:54.880 │ Oil not found                      
WARNING  14:08:55.195 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:55.198 │ [OCR_OIL 0.025s] 0                 
WARNING  14:08:55.201 │ Oil not found                      
WARNING  14:08:55.476 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:55.478 │ [OCR_OIL 0.020s] 0                 
WARNING  14:08:55.480 │ Oil not found                      
WARNING  14:08:55.782 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:55.784 │ [OCR_OIL 0.019s] 0                 
WARNING  14:08:55.786 │ Oil not found                      
WARNING  14:08:56.085 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:56.087 │ [OCR_OIL 0.018s] 0                 
WARNING  14:08:56.089 │ Oil not found                      
WARNING  14:08:56.407 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:56.409 │ [OCR_OIL 0.020s] 0                 
WARNING  14:08:56.411 │ Oil not found                      
WARNING  14:08:56.684 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:56.686 │ [OCR_OIL 0.018s] 0                 
WARNING  14:08:56.688 │ Oil not found                      
WARNING  14:08:56.985 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:56.987 │ [OCR_OIL 0.018s] 0                 
WARNING  14:08:56.989 │ Oil not found                      
WARNING  14:08:57.278 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:57.280 │ [OCR_OIL 0.020s] 0                 
WARNING  14:08:57.282 │ Oil not found                      
WARNING  14:08:57.591 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:57.592 │ [OCR_OIL 0.021s] 0                 
WARNING  14:08:57.594 │ Oil not found                      
WARNING  14:08:57.896 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:57.898 │ [OCR_OIL 0.020s] 0                 
WARNING  14:08:57.900 │ Oil not found                      
WARNING  14:08:58.205 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:58.207 │ [OCR_OIL 0.019s] 0                 
WARNING  14:08:58.208 │ Oil not found                      
WARNING  14:08:58.482 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:58.484 │ [OCR_OIL 0.017s] 0                 
WARNING  14:08:58.486 │ Oil not found                      
WARNING  14:08:58.796 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:58.798 │ [OCR_OIL 0.021s] 0                 
WARNING  14:08:58.799 │ Oil not found                      
WARNING  14:08:59.088 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:59.091 │ [OCR_OIL 0.022s] 0                 
WARNING  14:08:59.093 │ Oil not found                      
WARNING  14:08:59.404 │ OCR OCR_OIL: Result "" is revised  
         to "0"                                            
INFO     14:08:59.406 │ [OCR_OIL 0.023s] 0                 
WARNING  14:08:59.408 │ Oil not found                      
INFO     14:08:59.735 │ [Loading] 6%                       
INFO     14:08:59.738 │ Auto search combat loading         
INFO     14:08:59.739 │ Screenshot interval set to 1.0s    
INFO     14:09:06.706 │ Auto Search combat execute         
INFO     14:09:06.708 │ <<< EMOTION REDUCE >>>             
INFO     14:09:06.720 │ Bind task {'Alas', 'Main',         
         'General'}                                        
INFO     14:09:06.722 │ Save config ./config\alas.json,    
         Main.Emotion.Fleet1Value=119,                     
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 
         2, 9, 14, 9, 6), Main.Emotion.Fleet2Value=132,    
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 
         2, 9, 14, 9, 6)                                   
INFO     14:09:06.732 │ [Emotion fleet_1] 119              
INFO     14:09:06.734 │ [Emotion fleet_2] 132              
INFO     14:09:12.697 │ Combat auto check timer reached
```

### 截图

![image](https://user-images.githubusercontent.com/103177863/217732031-962dbb80-4f3c-4665-8803-e9dad3ff2706.png)
![image](https://user-images.githubusercontent.com/103177863/217732399-50981be7-5d65-4d38-a5bc-25b36837eb2c.png)
![Screenshot_2023 02 09_14 11 56 000](https://user-images.githubusercontent.com/103177863/217738291-16a1dcc2-8bb7-4ebe-a994-91efbce5cebc.png)

[2023-02-09_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10694238/2023-02-09_alas.txt)

[2023-02-09_gui.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10694247/2023-02-09_gui.txt)

**Comment by Altria17388** [comment]
12-4亲测也有无法识别石油的bug，同模拟器Pie64版本

**Comment by lilacmist** [comment]
我也是，好像是上面那个黑条挡住了

**Comment by ZeroBloodedge** [comment]
同，我也是，更新以后出的问题

**Comment by bookbug666** [comment]
@HS7097 可以發一張主畫面的截圖嗎

看起來戰鬥中的半透明蓋到石油/物資/鑽石那邊了，因為之前進戰鬥那一塊是沒有被淡化的

**Comment by HS7097** [comment]
> @HS7097 可以發一張主畫面的截圖嗎
> 
> 看起來戰鬥中的半透明蓋到石油/物資/鑽石那邊了，因為之前進戰鬥那一塊是沒有被淡化的

![Screenshot_2023 02 09_15 35 08 767](https://user-images.githubusercontent.com/103177863/217747168-6f5b555d-b751-4b34-823d-6b35459f3c06.png)
这个可以吗qwq

**Comment by bookbug666** [comment]
> > @HS7097 可以發一張主畫面的截圖嗎
> > 看起來戰鬥中的半透明蓋到石油/物資/鑽石那邊了，因為之前進戰鬥那一塊是沒有被淡化的
> 
> ![Screenshot_2023 02 09_15 35 08 767](https://user-images.githubusercontent.com/103177863/217747168-6f5b555d-b751-4b34-823d-6b35459f3c06.png) 这个可以吗qwq

![image](https://user-images.githubusercontent.com/29662367/217748234-d6fa2604-8846-4dce-8e33-24141ef2f741.png)
上半是你戰鬥中，下半是你非戰鬥頁面的的，圖標跟字都有明顯淡化(也許是太淡OCR看不出是多少)
看了下日服歷史截圖也沒有出現這種情況，可以多回報一下還有哪些地方無法識別(畢竟也不知道是CN專屬還是黃雞又攪了UI)

**Comment by HS7097** [comment]
> > > @HS7097 可以發一張主畫面的截圖嗎
> > > 看起來戰鬥中的半透明蓋到石油/物資/鑽石那邊了，因為之前進戰鬥那一塊是沒有被淡化的
> > 
> > 
> > ![Screenshot_2023 02 09_15 35 08 767](https://user-images.githubusercontent.com/103177863/217747168-6f5b555d-b751-4b34-823d-6b35459f3c06.png) 这个可以吗qwq
> 
> ![image](https://user-images.githubusercontent.com/29662367/217748234-d6fa2604-8846-4dce-8e33-24141ef2f741.png) 上半是你戰鬥中，下半是你非戰鬥頁面的的，圖標跟字都有明顯淡化(也許是太淡OCR看不出是多少) 看了下日服歷史截圖也沒有出現這種情況，可以多回報一下還有哪些地方無法識別(畢竟也不知道是CN專屬還是黃雞又攪了UI)

停止主线图以及刷委托任务等消耗石油的任务后，Alas托管正常，出现错误提示错误应该只有石油识别错误

**Comment by HS7097** [comment]
既然日服没改的话，大概就是个bug，反脚本机制也没有这么搞的吧qwq？

**Comment by bookbug666** [comment]
> 既然日服没改的话，大概就是个bug，反脚本机制也没有这么搞的吧qwq？

喔不是，日版還在維修所以才希望多給點資訊(不然我就只有這張圖)

**Comment by bookbug666** [comment]
![MuMu20230209160457](https://user-images.githubusercontent.com/29662367/217752984-c8cbf9d9-ad73-401c-b75a-39889422d51e.png)
日板也被淡化，看來是黃雞攪了UI(而且商店.大廳都沒變，只有進戰鬥那一層半透明才會蓋上去)

**Comment by HS7097** [comment]
> ![MuMu20230209160457](https://user-images.githubusercontent.com/29662367/217752984-c8cbf9d9-ad73-401c-b75a-39889422d51e.png) 日板也被淡化，看來是黃雞攪了UI(而且商店.大廳都沒變，只有進戰鬥那一層半透明才會蓋上去)

好家伙，还基本只有石油 那里被挡了

**Comment by MengNianxiaoyao** [comment]
物资也识别不了，尝试修复过，还是无法识别

**Comment by MengNianxiaoyao** [comment]
> 物资也识别不了，尝试修复过，还是无法识别

也许需要重新训练OCR模型

**Comment by SaiCateDoan** [comment]
好，是时候顺便把ocr模型换了（不是
正常的处理办法可能是做点图像预处理，让数字清晰到ocr能识别的程度

**Comment by jszhtian** [comment]
cv.threshold二值化试试。
反正ocr的时候只要数字。再不行的话。crap到只有数字再二值化。

**Comment by minatoAI** [comment]
我这边看起来变回去了，不是之前那种半透明了
![image](https://user-images.githubusercontent.com/121915052/217999339-300bcb73-34e5-4f41-b010-beca5cfee61c.png)

![image](https://user-images.githubusercontent.com/121915052/217999413-2b8777af-28d6-4244-ab1c-a6028ab7740a.png)

**Comment by minatoAI** [comment]
> 我这边看起来变回去了，不是之前那种半透明了 ![image](https://user-images.githubusercontent.com/121915052/217999339-300bcb73-34e5-4f41-b010-beca5cfee61c.png)
> 
> ![image](https://user-images.githubusercontent.com/121915052/217999413-2b8777af-28d6-4244-ab1c-a6028ab7740a.png)

根据官方动态，应该是游戏bug，已经修复了
<https://b23.tv/mHT1gaF>
