### ISSUE TITLE
每次自动进行委托完成和委托选择的时候出现异常停止

### ISSUE THREAD

**Issue by SnowParaselene** [LmeSzinc/AzurLaneAutoScript#2226]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

每次自动进行委托完成和委托选择的时候出现异常停止

### 如何复现

看log重复时像是在识别委托内容时拉动滑动条失败

### 预期行为

解决问题

### 相关 Logs

```Text
最近发生的几个log打包成zip里了
```

### 截图

![2023-02-10_06-02-51-098386](https://user-images.githubusercontent.com/120864040/217976374-9aea4650-ed43-442d-983a-03eac262a9f2.png)
![2023-02-10_06-05-11-691829](https://user-images.githubusercontent.com/120864040/217976381-26bfd10f-4d93-4d19-b2b4-a267070d9c8f.png)
![2023-02-10_06-06-57-160498](https://user-images.githubusercontent.com/120864040/217976393-c157b616-b6ad-4f3e-a615-2118cbcf9eff.png)

### 还有别的吗？

[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10702870/error.zip)

**Comment by LmeSzinc** [comment]
#1470
