### ISSUE TITLE
侵蚀1练级点击返回主页界面不动

### ISSUE THREAD

**Issue by shenqimolisha** [LmeSzinc/AzurLaneAutoScript#2233]
如题，最近一次更新alas后，侵蚀1练级没法用了，修改时间马上运行也没用。。。只会返回主界面，不知道作者是不是也有这个问题

**Comment by LmeSzinc** [comment]
如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。


上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。

**Comment by shenqimolisha** [comment]
![mmexport1676189871218.png](https://user-images.githubusercontent.com/93420332/218300374-e83f6e5b-2a42-4dcb-b181-ea1ba1605f9f.png)没有error报错，没有理解这个是怎么回事，体力箱子还有，就是不自动侵蚀1练级了

**Comment by TinyTitanPro** [comment]
默认情况下行动力总数超过3000或者白币低于10w会自动停止侵蚀1，可以通过修改相关代码解除这些限制

**Comment by shenqimolisha** [comment]
这样啊。那我只有手动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月13日(周一) 上午9:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 侵蚀1练级点击返回主页界面不动 (Issue #2233)




 
默认情况下行动力总数超过3000或者白币低于10w会自动停止侵蚀1，可以通过修改相关代码解除这些限制

**Comment by LmeSzinc** [comment]
如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。**若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。**

**若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。**
**若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。**
**若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。**
**若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。**

**Comment by LmeSzinc** [comment]
#2170 

未提供 log 的 issue 将在 7 天后被关闭，继续虚空讨论也会导致 issue 被关闭。

**Comment by LostMyMind** [comment]
一些手动代码
AzurLaneAutoScript\module\os\operation_siren.py第380行            `self.config.cross_set(keys='OpsiMeowfficerFarming.Scheduler.Enable', value=True)`
True改成False可以禁止自动启动短猫，**但是最近好像失效了**，而且这样搞会导致黄币急速减少。
D:\arura\AzurLaneAutoScript\module\config\config_manual.py第305行，100000就是要保留黄币的数量，但是**只建议月末用**，要不然商店买不完会很蛋疼。

**Comment by LostMyMind** [comment]
一些手动代码
AzurLaneAutoScript\module\os\operation_siren.py第380行 self.config.cross_set(keys='OpsiMeowfficerFarming.Scheduler.Enable', value=True)
True改成False可以禁止自动启动短猫，但是最近好像失效了，而且这样搞会导致黄币急速减少。
AzurLaneAutoScript\module\config\config_manual.py第305行，100000就是要保留黄币的数量，但是只建议月末用，要不然商店买不完会很蛋疼。
