### ISSUE TITLE
能不能在通用商店功能中加个勋章商店的开关

### ISSUE THREAD

**Issue by HuangTianMatt** [LmeSzinc/AzurLaneAutoScript#2234]
### 你的功能请求是否与问题有关？

仓鼠喜欢屯一点到下个月毕竟不是每个月都要抽卡，勋章可能只够兑换性价比高的那些

### 解决方案

加个开关

**Comment by LmeSzinc** [comment]
你可以使用商店过滤器
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/reward_shop_filter_string

![image](https://user-images.githubusercontent.com/37934724/218353952-177f88d3-86cb-4add-ace6-00a07d8ac787.png)
