### ISSUE TITLE
更均勻的同類型任務調度

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#2235]
### 你的功能请求是否与问题有关？

當啟用主線圖123的時候，如果是相同石油限制(假設現在有4000石油，限制為3000)流程會變成

1. 主線圖1執行，23等待直到1打到石油限制或是心情(但心情很難)
2. 主線圖2執行幾次，觸發石油限制停止，3幾乎不執行
3. 石油回復，執行主線1

如果是設定級距(3000,2800,2600)，會變成主線1進入休息後持續被2搶石油，除非委託/獎勵收取讓石油存量再次超過主線1的限制，不然就會變成大多2少數1跟3
##
當前的任務優先度又是絕對排序，沒有那種執行比例的設定，不是很確定在邏輯甚至編寫上能否實現

### 解决方案

有沒有什麼將123綁定成一組平等執行的方法，像是之前萊莎連動那樣平均分配給相同類型的任務

**Comment by LmeSzinc** [comment]
从设计的角度来说，这三个任务不是平级的。它们叫主线图1/2/3，通常情况下会认为第一任务会优先于第三任务执行。
