### ISSUE TITLE
艦隊獎勵未收取作戰報酬

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#2236]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![image](https://user-images.githubusercontent.com/29662367/218369457-b74dd223-64fd-49d8-8406-169ae75321a8.png)
如題，我有開啟收取獎勵

但作戰獎勵不知道是本來就沒做還是bug，沒有收取，清空後也沒有領取
![MuMu20230213120940](https://user-images.githubusercontent.com/29662367/218369517-c2625335-8798-4db0-84c5-f3ca673faaac.png)
![MuMu20230213120949](https://user-images.githubusercontent.com/29662367/218369524-63f2f88b-ddc3-4bab-a766-f28a5c69234f.png)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

alas幫用戶領取作戰獎勵

**Comment by bookbug666** [comment]
[2023-02-13_alas_.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10722503/2023-02-13_alas_.txt)
嘗試清空時間後的log

**Comment by LmeSzinc** [comment]
一键领取的按钮稍微有点色差，拉高阈值应该就好了
