### ISSUE TITLE
Wiki 中过滤器部分没有强化过滤器的说明

### ISSUE THREAD

**Issue by Orange-Summer** [LmeSzinc/AzurLaneAutoScript#2239]
### 你的功能请求是否与问题有关？

如题

**Comment by bookbug666** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn#%E5%BC%BA%E5%8C%96%E8%88%B0%E8%88%B9%E8%BF%87%E6%BB%A4%E5%99%A8

其實就是常用的海軍艦種代號，幫你打了一份上去 ~~湊合著看吧~~

**Comment by Orange-Summer** [comment]
感谢大佬
