### ISSUE TITLE
auto检测不到模拟器

### ISSUE THREAD

**Issue by shenqimolisha** [LmeSzinc/AzurLaneAutoScript#2243]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如图，今早更新后，刚刚维护好进去，就成这样了，一直显示检测不到模拟器。照着log里面改成同样的也显示检测不到

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/93420332/219292518-2bb7cd5e-8e2b-45db-8823-5a64dc9b18fd.png)

**Comment by LmeSzinc** [comment]
需要提供模拟器类型和模拟器版本号，以及尝试重启模拟器

**Comment by shenqimolisha** [comment]
已经没事了，我绿化了下模拟器，卸载了alas重装了下，就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] auto检测不到模拟器 (Issue #2243)




 
需要提供模拟器类型和模拟器版本号，以及尝试重启模拟器
