### ISSUE TITLE
webui内文件无法访问

### ISSUE THREAD

**Issue by alonexin1** [LmeSzinc/AzurLaneAutoScript#2248]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

下载Visual Studio Code和python3.10后，晚上启动模拟器显示系统无法访问此文件，新下载alas后还是同样的问题

### Screenshots

![IQ%$(NYM7M RUDUI}3 NDTD](https://user-images.githubusercontent.com/102207420/219376068-c2f5359e-c2ab-43f3-8578-3a5a34afe6e4.png)

**Comment by LmeSzinc** [comment]
需要提供完整log

**Comment by alonexin1** [comment]
辛苦您，我个人猜测可能是vsc改变了文件的读取方式导致的。
![TN17{(@ ~MI2XR~}`STQVTD](https://user-images.githubusercontent.com/102207420/219436710-dd10503a-c11f-419f-a27f-232fb6c9b870.png)

**Comment by LmeSzinc** [comment]
看看 #497

**Comment by alonexin1** [comment]
我在看完#497后，解决方法都用了，而且我顺便把python3.10也删了，vsc也删了，并且重新下载了alas，还是出现了上述问题

**Comment by alonexin1** [comment]
感谢Lem哥的回答，我发现问题所在了，是我在安装python3.10后，在环境变量中配置python导致的，删除python环境变量后就可以正常运行了，您辛苦，再次感谢您的回复。
