### ISSUE TITLE
深度回音進入關卡後卡住

### ISSUE THREAD

**Issue by Evanto1258** [LmeSzinc/AzurLaneAutoScript#2253]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [x] I am using the latest version of Alas

### Describe the bug

進圖之後會定位不到地圖

### Screenshots

![2023-02-17_22-42-51-436545](https://user-images.githubusercontent.com/61620346/219687842-5713f7f1-1b98-49e4-8a1e-d7330ee37e32.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10768122/log.txt)

**Comment by Evanto1258** [comment]
LOG太多字不給直接貼上,我就直接上傳TXT檔

**Comment by LmeSzinc** [comment]
另外你的电脑很慢，建议运行 工具 - 性能测试，选择最快的截图方案
```
2023-02-17 22:42:19.941 | INFO | Click ( 374,  525) @ d2                                                               
2023-02-17 22:42:20.786 | INFO | [Map_clear_percentage] 0.0                                                            
2023-02-17 22:42:20.867 | INFO | [Map_clear_percentage] 0.0                                                            
2023-02-17 22:42:21.444 | INFO | [Map_clear_percentage] 0.0
```

**Comment by Evanto1258** [comment]
═════════════════════════════════════ BENCHMARK RESULTS ═════════════════════════════════════
INFO     02:47:43.255 │ BENCHMARK RESULTS                                                    
                           ┏━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━┓                           
                           ┃ Screenshot    ┃ Time   ┃ Speed      ┃                           
                           ┡━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━┩                           
                           │ ADB           │ 0.222s │ Fast       │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ ADB_nc        │ 0.135s │ Very Fast  │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ uiautomator2  │ 0.374s │ Medium     │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ aScreenCap    │ 0.107s │ Very Fast  │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ aScreenCap_nc │ 0.092s │ Ultra Fast │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ DroidCast     │ 0.182s │ Very Fast  │                           
                           ├───────────────┼────────┼────────────┤                           
                           │ DroidCast_raw │ 0.063s │ Ultra Fast │                           
                           └───────────────┴────────┴────────────┘                           
INFO     02:47:43.259 │ Recommend screenshot method: DroidCast_raw (0.063s)                  
                             ┏━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┓                              
                             ┃ Control      ┃ Time   ┃ Speed  ┃                              
                             ┡━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━┩                              
                             │ ADB          │ 0.170s │ Medium │                              
                             ├──────────────┼────────┼────────┤                              
                             │ uiautomator2 │ 0.149s │ Medium │                              
                             ├──────────────┼────────┼────────┤                              
                             │ minitouch    │ 0.050s │ Fast   │                              
                             └──────────────┴────────┴────────┘                              
INFO     02:47:43.261 │ Recommend control method: minitouch (0.050s)                         
INFO     02:47:43.262 │ [alas] exited. Reason: Finish

**Comment by LmeSzinc** [comment]
嗯，选 `DroidCast_raw` 截图和 `minitouch` 点击 就可以了
