### ISSUE TITLE
识别后宅家具弹窗

### ISSUE THREAD

**Issue by Lazy-Beee** [LmeSzinc/AzurLaneAutoScript#2262]
### 你的功能请求是否与问题有关？

因为后宅放置了较多纪念章，alas进入后宅收集家具币时，有概率点击到家具，然后因为无法识别UI而停止运行。这个问题可以通过移除后宅中特殊家具解决，但恳请大佬添加识别这类弹窗的功能。

### 解决方案

添加一个功能，识别后宅家具弹窗，并点击确定消除弹窗

### 其他内容

[Error Log](https://github.com/LmeSzinc/AzurLaneAutoScript/files/10789518/log.txt)

![2023-02-20_23-12-55-946206](https://user-images.githubusercontent.com/85976834/220246520-b8d59df6-d82c-4170-ab11-ea15c3b09a43.png)

**Comment by bookbug666** [comment]
這個都是哪些物品會出現啊?

**Comment by Lazy-Beee** [comment]
> 這個都是哪些物品會出現啊?

所有活动纪念家具

**Comment by Lazy-Beee** [comment]
经测试已经可以关闭家具弹窗，非常感谢
