### ISSUE TITLE
能否恢复余烬信标仅出击档案信标的功能？

### ISSUE THREAD

**Issue by PkuRinko** [LmeSzinc/AzurLaneAutoScript#2268]
### 你的功能请求是否与问题有关？

似乎几天前的更新去除了单独出击档案信标不出击当期信标的功能。能否将之恢复？

**Comment by LmeSzinc** [comment]
这样做会导致一个严重的任务调度 BUG。因为在当前游戏机制下，当期 META 和往期 META 是不能并存的，也就是说在玩家开启了一个 META 作战的情况下（无论它是当前还是往期），如果玩家想开另一个 META 作战（无论它是当前还是往期），那么玩家必须完成上一个 META 作战才能开启下一个。

那么 BUG 就来了，如果玩家已经开启了一个当期 META 并且只打往期，Alas 发现信标数据满了调起 META 任务，META 任务发现是当期 META 于是跳过，回来又发现信标数据满了，这样就无限循环了。一直没发现这个 BUG 是因为很少有人去关掉那个开关，毕竟有 一刀即走 的功能，打一下也不会造成资源损失。
