### ISSUE TITLE
出于改版后刷好感度的需要.请求"道中全清"功能

### ISSUE THREAD

**Issue by ZSJsts** [LmeSzinc/AzurLaneAutoScript#2274]
由于伏击出现次数被固定.1-1无限横跳刷好感的玩法没有了.
退而求其次只能尽可能去找道中最多的场景.并且在清完道中全部后再打BOSS.
这样可以在扣除1次心情后尽可能的增加多的好感.
虽然效率肯定不如以前1-1.但作为妥协方案也是可行的.....

否则目前没有其他更好的快速刷好感度的办法了.因为心情限制,本身就要在扣相同心情的前提下打尽可能多的道中

**Comment by bookbug666** [comment]
你有一個誤區:心情是沒有"扣除上限"的
每一次進場就是心情-2(無論輸贏，非共鬥沈船的該船再扣10)，增加道中全清長期只是省入場的10油
(何況出怪量依然有限制，例如9-1道中最多8戰+1戰BOSS=9戰

你的好感增長速度依然受限於后宅的回復速度，以及你打圖的速度 ~~至於陰間沈船超時法不再此討論~~
如果你是考慮"好感增加的速度"，那麼增加道中全清並沒有幫助到你，只能省點油

**Comment by ZSJsts** [comment]
> 

唔唔 感谢
