### ISSUE TITLE
Event farming should default to lower level map if no higher is availble, stops the farm instead

### ISSUE THREAD

**Issue by Oplikk** [LmeSzinc/AzurLaneAutoScript#2291]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

                          On  latest build (update to 10:00 CET)
                          
                          When A2 not found should default to A1 again

                          
                          
                          
                                      EVENTA                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     10:50:13.847 │ [Stage] ['a1', 'a2', 'a3', 'b1', 'b2', 'b3', 'c1', 'c2',   
         'c3', 'd1', 'd2', 'd3', 'sp', 'unknown']                                  
INFO     10:50:13.850 │ [StageFilter] A1 > A2 > A3                                 
INFO     10:50:13.852 │ [Filter sort] a1 > a2 > a3                                 
INFO     10:50:13.855 │ LastStage a1, recorded at 2023-02-26 10:50:12              
INFO     10:50:13.857 │ [Filter sort] a2 > a3                                      
═══════════════════════════════════════ A2 ════════════════════════════════════════
INFO     10:50:13.880 │ A2                                                         
INFO     10:50:13.883 │ Count: 0                                                   
INFO     10:50:13.899 │ UI get current page                                        
INFO     10:50:13.912 │ [UI] page_event                                            
INFO     10:50:13.915 │ Already at page_event                                      
INFO     10:50:13.938 │ [Mode_switch_2] ex                                         
INFO     10:50:13.959 │ [Mode_switch_1] hard                                       
INFO     10:50:13.960 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:14.031 │ [campaign 0.019s] A1                                       
INFO     10:50:14.033 │ [Chapter] a                                                
INFO     10:50:14.035 │ [Stage] a1                                                 
INFO     10:50:14.037 │ [Index] 1                                                  
WARNING  10:50:14.039 │ Stage not found: a2                                        
INFO     10:50:14.471 │ UI get current page                                        
INFO     10:50:14.486 │ [UI] page_event                                            
INFO     10:50:14.489 │ Already at page_event                                      
INFO     10:50:14.492 │ [Mode_switch_2] ex                                         
INFO     10:50:14.495 │ [Mode_switch_1] hard                                       
INFO     10:50:14.497 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:14.557 │ [campaign 0.012s] A1                                       
INFO     10:50:14.559 │ [Chapter] a                                                
INFO     10:50:14.560 │ [Stage] a1                                                 
INFO     10:50:14.562 │ [Index] 1                                                  
WARNING  10:50:14.565 │ Stage not found: a2                                        
INFO     10:50:15.017 │ UI get current page                                        
INFO     10:50:15.033 │ [UI] page_event                                            
INFO     10:50:15.035 │ Already at page_event                                      
INFO     10:50:15.039 │ [Mode_switch_2] ex                                         
INFO     10:50:15.044 │ [Mode_switch_1] hard                                       
INFO     10:50:15.045 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:15.102 │ [campaign 0.010s] A1                                       
INFO     10:50:15.105 │ [Chapter] a                                                
INFO     10:50:15.107 │ [Stage] a1                                                 
INFO     10:50:15.109 │ [Index] 1                                                  
WARNING  10:50:15.111 │ Stage not found: a2                                        
INFO     10:50:15.254 │ UI get current page                                        
INFO     10:50:15.270 │ [UI] page_event                                            
INFO     10:50:15.272 │ Already at page_event                                      
INFO     10:50:15.276 │ [Mode_switch_2] ex                                         
INFO     10:50:15.279 │ [Mode_switch_1] hard                                       
INFO     10:50:15.281 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:15.347 │ [campaign 0.012s] A1                                       
INFO     10:50:15.349 │ [Chapter] a                                                
INFO     10:50:15.351 │ [Stage] a1                                                 
INFO     10:50:15.353 │ [Index] 1                                                  
WARNING  10:50:15.355 │ Stage not found: a2                                        
INFO     10:50:15.544 │ UI get current page                                        
INFO     10:50:15.559 │ [UI] page_event                                            
INFO     10:50:15.560 │ Already at page_event                                      
INFO     10:50:15.566 │ [Mode_switch_2] ex                                         
INFO     10:50:15.569 │ [Mode_switch_1] hard                                       
INFO     10:50:15.571 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:15.634 │ [campaign 0.011s] A1                                       
INFO     10:50:15.636 │ [Chapter] a                                                
INFO     10:50:15.638 │ [Stage] a1                                                 
INFO     10:50:15.640 │ [Index] 1                                                  
WARNING  10:50:15.642 │ Stage not found: a2                                        
INFO     10:50:16.135 │ UI get current page                                        
INFO     10:50:16.146 │ [UI] page_event                                            
INFO     10:50:16.148 │ Already at page_event                                      
INFO     10:50:16.154 │ [Mode_switch_2] ex                                         
INFO     10:50:16.157 │ [Mode_switch_1] hard                                       
INFO     10:50:16.159 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:16.224 │ [campaign 0.013s] A1                                       
INFO     10:50:16.225 │ [Chapter] a                                                
INFO     10:50:16.227 │ [Stage] a1                                                 
INFO     10:50:16.229 │ [Index] 1                                                  
WARNING  10:50:16.231 │ Stage not found: a2                                        
INFO     10:50:16.350 │ UI get current page                                        
INFO     10:50:16.363 │ [UI] page_event                                            
INFO     10:50:16.365 │ Already at page_event                                      
INFO     10:50:16.372 │ [Mode_switch_2] ex                                         
INFO     10:50:16.375 │ [Mode_switch_1] hard                                       
INFO     10:50:16.377 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:16.443 │ [campaign 0.014s] A1                                       
INFO     10:50:16.445 │ [Chapter] a                                                
INFO     10:50:16.448 │ [Stage] a1                                                 
INFO     10:50:16.449 │ [Index] 1                                                  
WARNING  10:50:16.451 │ Stage not found: a2                                        
INFO     10:50:16.657 │ UI get current page                                        
INFO     10:50:16.668 │ [UI] page_event                                            
INFO     10:50:16.670 │ Already at page_event                                      
INFO     10:50:16.675 │ [Mode_switch_2] ex                                         
INFO     10:50:16.678 │ [Mode_switch_1] hard                                       
INFO     10:50:16.679 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:16.754 │ [campaign 0.018s] A1                                       
INFO     10:50:16.757 │ [Chapter] a                                                
INFO     10:50:16.759 │ [Stage] a1                                                 
INFO     10:50:16.762 │ [Index] 1                                                  
WARNING  10:50:16.764 │ Stage not found: a2                                        
INFO     10:50:16.960 │ UI get current page                                        
INFO     10:50:16.976 │ [UI] page_event                                            
INFO     10:50:16.978 │ Already at page_event                                      
INFO     10:50:16.984 │ [Mode_switch_2] ex                                         
INFO     10:50:16.989 │ [Mode_switch_1] hard                                       
INFO     10:50:16.992 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:17.064 │ [campaign 0.012s] A1                                       
INFO     10:50:17.067 │ [Chapter] a                                                
INFO     10:50:17.070 │ [Stage] a1                                                 
INFO     10:50:17.072 │ [Index] 1                                                  
WARNING  10:50:17.074 │ Stage not found: a2                                        
INFO     10:50:17.277 │ UI get current page                                        
INFO     10:50:17.296 │ [UI] page_event                                            
INFO     10:50:17.298 │ Already at page_event                                      
INFO     10:50:17.306 │ [Mode_switch_2] ex                                         
INFO     10:50:17.310 │ [Mode_switch_1] hard                                       
INFO     10:50:17.312 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:17.388 │ [campaign 0.012s] A1                                       
INFO     10:50:17.391 │ [Chapter] a                                                
INFO     10:50:17.393 │ [Stage] a1                                                 
INFO     10:50:17.394 │ [Index] 1                                                  
WARNING  10:50:17.396 │ Stage not found: a2                                        
INFO     10:50:17.562 │ UI get current page                                        
INFO     10:50:17.577 │ [UI] page_event                                            
INFO     10:50:17.578 │ Already at page_event                                      
INFO     10:50:17.583 │ [Mode_switch_2] ex                                         
INFO     10:50:17.587 │ [Mode_switch_1] hard                                       
INFO     10:50:17.589 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:17.652 │ [campaign 0.010s] A1                                       
INFO     10:50:17.656 │ [Chapter] a                                                
INFO     10:50:17.657 │ [Stage] a1                                                 
INFO     10:50:17.659 │ [Index] 1                                                  
WARNING  10:50:17.661 │ Stage not found: a2                                        
INFO     10:50:17.869 │ UI get current page                                        
INFO     10:50:17.885 │ [UI] page_event                                            
INFO     10:50:17.888 │ Already at page_event                                      
INFO     10:50:17.893 │ [Mode_switch_2] ex                                         
INFO     10:50:17.896 │ [Mode_switch_1] hard                                       
INFO     10:50:17.898 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:17.962 │ [campaign 0.011s] A1                                       
INFO     10:50:17.964 │ [Chapter] a                                                
INFO     10:50:17.967 │ [Stage] a1                                                 
INFO     10:50:17.970 │ [Index] 1                                                  
WARNING  10:50:17.972 │ Stage not found: a2                                        
INFO     10:50:18.167 │ UI get current page                                        
INFO     10:50:18.180 │ [UI] page_event                                            
INFO     10:50:18.182 │ Already at page_event                                      
INFO     10:50:18.188 │ [Mode_switch_2] ex                                         
INFO     10:50:18.193 │ [Mode_switch_1] hard                                       
INFO     10:50:18.194 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:18.259 │ [campaign 0.012s] A1                                       
INFO     10:50:18.261 │ [Chapter] a                                                
INFO     10:50:18.263 │ [Stage] a1                                                 
INFO     10:50:18.265 │ [Index] 1                                                  
WARNING  10:50:18.267 │ Stage not found: a2                                        
INFO     10:50:18.776 │ UI get current page                                        
INFO     10:50:18.788 │ [UI] page_event                                            
INFO     10:50:18.790 │ Already at page_event                                      
INFO     10:50:18.794 │ [Mode_switch_2] ex                                         
INFO     10:50:18.797 │ [Mode_switch_1] hard                                       
INFO     10:50:18.800 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:18.862 │ [campaign 0.013s] A1                                       
INFO     10:50:18.864 │ [Chapter] a                                                
INFO     10:50:18.867 │ [Stage] a1                                                 
INFO     10:50:18.869 │ [Index] 1                                                  
WARNING  10:50:18.872 │ Stage not found: a2                                        
INFO     10:50:19.278 │ UI get current page                                        
INFO     10:50:19.294 │ [UI] page_event                                            
INFO     10:50:19.296 │ Already at page_event                                      
INFO     10:50:19.300 │ [Mode_switch_2] ex                                         
INFO     10:50:19.304 │ [Mode_switch_1] hard                                       
INFO     10:50:19.306 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:19.367 │ [campaign 0.010s] A1                                       
INFO     10:50:19.369 │ [Chapter] a                                                
INFO     10:50:19.371 │ [Stage] a1                                                 
INFO     10:50:19.373 │ [Index] 1                                                  
WARNING  10:50:19.375 │ Stage not found: a2                                        
INFO     10:50:19.800 │ UI get current page                                        
INFO     10:50:19.817 │ [UI] page_event                                            
INFO     10:50:19.819 │ Already at page_event                                      
INFO     10:50:19.824 │ [Mode_switch_2] ex                                         
INFO     10:50:19.827 │ [Mode_switch_1] hard                                       
INFO     10:50:19.829 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:19.892 │ [campaign 0.011s] A1                                       
INFO     10:50:19.894 │ [Chapter] a                                                
INFO     10:50:19.896 │ [Stage] a1                                                 
INFO     10:50:19.898 │ [Index] 1                                                  
WARNING  10:50:19.900 │ Stage not found: a2                                        
INFO     10:50:20.019 │ UI get current page                                        
INFO     10:50:20.034 │ [UI] page_event                                            
INFO     10:50:20.036 │ Already at page_event                                      
INFO     10:50:20.042 │ [Mode_switch_2] ex                                         
INFO     10:50:20.045 │ [Mode_switch_1] hard                                       
INFO     10:50:20.047 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:20.131 │ [campaign 0.020s] A1                                       
INFO     10:50:20.134 │ [Chapter] a                                                
INFO     10:50:20.135 │ [Stage] a1                                                 
INFO     10:50:20.139 │ [Index] 1                                                  
WARNING  10:50:20.142 │ Stage not found: a2                                        
INFO     10:50:20.336 │ UI get current page                                        
INFO     10:50:20.354 │ [UI] page_event                                            
INFO     10:50:20.358 │ Already at page_event                                      
INFO     10:50:20.362 │ [Mode_switch_2] ex                                         
INFO     10:50:20.366 │ [Mode_switch_1] hard                                       
INFO     10:50:20.368 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:20.436 │ [campaign 0.011s] A1                                       
INFO     10:50:20.439 │ [Chapter] a                                                
INFO     10:50:20.440 │ [Stage] a1                                                 
INFO     10:50:20.442 │ [Index] 1                                                  
WARNING  10:50:20.444 │ Stage not found: a2                                        
INFO     10:50:20.920 │ UI get current page                                        
INFO     10:50:20.934 │ [UI] page_event                                            
INFO     10:50:20.937 │ Already at page_event                                      
INFO     10:50:20.942 │ [Mode_switch_2] ex                                         
INFO     10:50:20.944 │ [Mode_switch_1] hard                                       
INFO     10:50:20.946 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:21.008 │ [campaign 0.013s] A1                                       
INFO     10:50:21.011 │ [Chapter] a                                                
INFO     10:50:21.013 │ [Stage] a1                                                 
INFO     10:50:21.015 │ [Index] 1                                                  
WARNING  10:50:21.016 │ Stage not found: a2                                        
INFO     10:50:21.140 │ UI get current page                                        
INFO     10:50:21.159 │ [UI] page_event                                            
INFO     10:50:21.161 │ Already at page_event                                      
INFO     10:50:21.167 │ [Mode_switch_2] ex                                         
INFO     10:50:21.170 │ [Mode_switch_1] hard                                       
INFO     10:50:21.172 │ <<< UI ENSURE INDEX >>>                                    
INFO     10:50:21.245 │ [campaign 0.013s] A1                                       
INFO     10:50:21.246 │ [Chapter] a                                                
INFO     10:50:21.249 │ [Stage] a1                                                 
INFO     10:50:21.251 │ [Index] 1                                                  
WARNING  10:50:21.253 │ Stage not found: a2                                        
WARNING  10:50:21.442 │ Campaign name error                                        
ERROR    10:50:21.445 │ ScriptEnd: Campaign name error                             
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:\XXXX\AzurLaneAutoScript\alas.py:63 in run    │
         │                                                                        │
         │    61 │   │   try:                                                     │
         │    62 │   │   │   self.device.screenshot()                             │
         │ ❱  63 │   │   │   self.__getattribute__(command)()                     │
         │    64 │   │   │   return True                                          │
         │    65 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭───────────────────────────── locals ─────────────────────────────╮   │
         │ │ command = 'event_a'                                              │   │
         │ │       e = ScriptEnd('Campaign name error')                       │   │
         │ │    self = <alas.AzurLaneAutoScript object at 0x000002351BAFF948> │   │
         │ ╰──────────────────────────────────────────────────────────────────╯   │
         │ C:\XXXX\AzurLaneAutoScript\alas.py:253 in       │
         │ event_a                                                                │
         │                                                                        │
         │   251 │   def event_a(self):                                           │
         │   252 │   │   from module.event.campaign_abcd import CampaignABCD      │
         │ ❱ 253 │   │   CampaignABCD(config=self.config, device=self.device).run │
         │   254 │                                                                │
         │   255 │   def event_b(self):                                           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ CampaignABCD = <class 'module.event.campaign_abcd.CampaignABCD'>   │ │
         │ │         self = <alas.AzurLaneAutoScript object at                  │ │
         │ │                0x000002351BAFF948>                                 │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\XXXX\AzurLaneAutoScript\module\event\campaig │
         │ n_abcd.py:44 in run                                                    │
         │                                                                        │
         │   42 │   │   │   stage = str(stage)                                    │
         │   43 │   │   │   try:                                                  │
         │ ❱ 44 │   │   │   │   super().run(name=stage, folder=self.config.Campai │
         │   45 │   │   │   except TaskEnd:                                       │
         │   46 │   │   │   │   # Catch task switch                               │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.event.campaign_abcd.CampaignABCD'>      │ │
         │ │      args = ()                                                     │ │
         │ │    kwargs = {}                                                     │ │
         │ │      last = 'a1'                                                   │ │
         │ │      self = <module.event.campaign_abcd.CampaignABCD object at     │ │
         │ │             0x000002354AF76B88>                                    │ │
         │ │     stage = 'a2'                                                   │ │
         │ │    stages = ['a2', 'a3']                                           │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:XXXX\AzurLaneAutoScript\module\campaign\run. │
         │ py:285 in run                                                          │
         │                                                                        │
         │   283 │   │   │   │   │   self.campaign.ensure_campaign_ui(name=self.s │
         │   284 │   │   │   else:                                                │
         │ ❱ 285 │   │   │   │   self.campaign.ensure_campaign_ui(name=self.stage │
         │   286 │   │   │   self.handle_commission_notice()                      │
         │   287                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ folder = 'event_20230223_cn'                                       │ │
         │ │   mode = 'normal'                                                  │ │
         │ │   name = 'a2'                                                      │ │
         │ │   self = <module.event.campaign_abcd.CampaignABCD object at        │ │
         │ │          0x000002354AF76B88>                                       │ │
         │ │  total = 1                                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:XXXX\AzurLaneAutoScript\module\campaign\camp │
         │ aign_ui.py:145 in ensure_campaign_ui                                   │
         │                                                                        │
         │   143 │   │                                                            │
         │   144 │   │   logger.warning('Campaign name error')                    │
         │ ❱ 145 │   │   raise ScriptEnd('Campaign name error')                   │
         │   146 │                                                                │
         │   147 │   def commission_notice_show_at_campaign(self):                │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ mode = 'normal'                                                    │ │
         │ │    n = 19                                                          │ │
         │ │ name = 'a2'                                                        │ │
         │ │ self = <campaign.event_20230223_cn.a2.Campaign object at           │ │
         │ │        0x000002353A684688>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         ScriptEnd: Campaign name error                                            
WARNING  10:50:21.706 │ Saving error: ./log/error/1677405021705                    
INFO     10:50:22.176 │ No provider specified, skip sending    

### 如何复现

event A farm

**Comment by LmeSzinc** [comment]
Task `Event Daily A` is for the 3x PT bonus everyday. Task `Event` should be used if you haven't unlock all the stages.

**Comment by Oplikk** [comment]
Okay sorry man, did not figure that one out. Thanks!
