### ISSUE TITLE
Out of step

### ISSUE THREAD

**Issue by Oplikk** [LmeSzinc/AzurLaneAutoScript#2293]
No idea what caused this, was not looking when this happened
![image](https://user-images.githubusercontent.com/67639836/221407024-0a269b05-153b-482c-a41c-7f62d068c7b9.png)

──────────────────────────────────── BATTLE_0 ─────────────────────────────────────
INFO     11:47:12.248 │ BATTLE_0                                                   
INFO     11:47:12.249 │ Using function: battle_0                                   
INFO     11:47:12.251 │ <<< CLEAR SIREN >>>                                        
INFO     11:47:12.254 │ sort=('weight', 'cost_2')                                  
INFO     11:47:12.256 │ Grids: [C3]                                                
INFO     11:47:12.257 │ targetEnemyScale:default_mode                              
INFO     11:47:12.258 │ Clear enemy: C3                                            
INFO     11:47:12.260 │ [Fleet_1: A3] Fleet_2: A5                                  
INFO     11:47:12.280 │ Bind task {'EventGeneral', 'Event', 'Alas', 'General',     
         'TaskBalancer'}                                                           
INFO     11:47:12.282 │ Save config ./config\alas.json,                            
         Event.Emotion.Fleet1Value=91,                                             
         Event.Emotion.Fleet1Record=datetime.datetime(2023, 2, 26, 11, 47, 12),    
         Event.Emotion.Fleet2Value=119,                                            
         Event.Emotion.Fleet2Record=datetime.datetime(2023, 2, 26, 11, 47, 12)     
INFO     11:47:12.295 │ [Emotion fleet_1] 91                                       
INFO     11:47:12.296 │ [Emotion fleet_2] 119                                      
INFO     11:47:12.298 │ Full path: [A3, B3, C3]                                    
INFO     11:47:12.301 │ Path: [C3]                                                 
INFO     11:47:12.303 │ Fleet set to 1                                             
INFO     11:47:12.316 │ Fleet: 1, fleet_current_index: 1                           
INFO     11:47:12.317 │ In sight: C3                                               
INFO     11:47:12.320 │ Focus to: D3                                               
INFO     11:47:12.322 │ Map swipe: (0, -2)                                         
INFO     11:47:12.327 │ Swipe ( 637,  194) -> ( 649,  467)                         
INFO     11:47:13.424 │            tile_center: 0.922 (good match)                 
INFO     11:47:13.435 │ 0.078s      edge_lines: 0 hori, 1 vert                     
INFO     11:47:13.438 │ Edges: /     homo_loca: ( 30,  46)                         
INFO     11:47:13.445 │            center_loca: (3, 3)                             
INFO     11:47:13.484 │ Map swipe predict: None (0.037s, no match)                 
INFO     11:47:13.488 │                 Camera: D3                                 
INFO     11:47:13.490 │                 Camera: D3                                 
INFO     11:47:13.643 │ 0.152s         predict: 48                                 
INFO     11:47:13.645 │ -- -- -- -- -- -- -- -- --                                 
INFO     11:47:13.647 │ -- -- -- -- -- -- -- -- ..                                 
INFO     11:47:13.649 │ -- -- 2E -- -- -- -- -- ..                                 
INFO     11:47:13.651 │ Fl -- LE -- -- -- -- -- ..                                 
INFO     11:47:13.654 │ -- -- -- -- -- -- -- 1M ..                                 
INFO     11:47:13.655 │ FL -- -- -- -- -- -- .. ..                                 
INFO     11:47:13.657 │ Map swipe: (0, 0)                                          
INFO     11:47:13.658 │ Re-focus to grid center.                                   
INFO     11:47:13.660 │ Map swipe: (0, 0)                                          
INFO     11:47:13.662 │ Global C3 (camera=D3) -> Local C4 (center=D4)              
INFO     11:47:13.665 │ Click ( 519,  363) @ C4                                    
WARNING  11:47:14.427 │ Map walk out of step.                                      
WARNING  11:47:17.352 │ Map walk error.                                            
INFO     11:47:17.502 │ 0.148s         predict: 48                                 
INFO     11:47:17.504 │ -- -- -- -- -- -- -- -- --                                 
INFO     11:47:17.506 │ -- -- -- -- -- -- -- -- ..                                 
INFO     11:47:17.507 │ -- -- 2E -- -- -- -- -- ..                                 
INFO     11:47:17.510 │ Fl -- -- -- -- -- -- -- ..                                 
INFO     11:47:17.511 │ -- -- -- -- -- -- -- 1M ..                                 
INFO     11:47:17.512 │ FL -- -- -- -- -- -- .. ..                                 
INFO     11:47:17.513 │ Ensure edge in sight.                                      
INFO     11:47:17.515 │ Map swipe: (0, 2)                                          
INFO     11:47:17.520 │ Swipe ( 631,  526) -> ( 633,  270)                         
INFO     11:47:18.303 │            tile_center: 0.922 (good match)                 
INFO     11:47:18.321 │ 0.088s      edge_lines: 1 hori, 1 vert                     
INFO     11:47:18.322 │ Edges: /_    homo_loca: ( 31,  75)                         
INFO     11:47:18.330 │            center_loca: (3, 3)                             
INFO     11:47:18.365 │ Map swipe predict: (0, 2) (0.034s, current fleet match)    
INFO     11:47:18.368 │                 Camera: D5                                 
INFO     11:47:18.370 │                 Camera: D5                                 
INFO     11:47:18.514 │ 0.143s         predict: 48                                 
INFO     11:47:18.517 │ -- -- 2E -- -- -- -- -- --                                 
INFO     11:47:18.519 │ -- -- LE -- -- -- -- -- ..                                 
INFO     11:47:18.520 │ -- -- -- -- -- -- -- 1M ..                                 
INFO     11:47:18.522 │ FL -- -- -- -- -- -- -- ..                                 
INFO     11:47:18.524 │ -- -- -- -- -- -- -- -- ..                                 
INFO     11:47:18.525 │ -- -- -- -- -- -- -- .. ..                                 
INFO     11:47:18.527 │ Map swipe: (0, 0)                                          
INFO     11:47:18.528 │ Full path: [A3, B3, C3]                                    
INFO     11:47:18.530 │ Path: [B3, C3]                                             
INFO     11:47:18.532 │ Fleet set to 1                                             
INFO     11:47:18.543 │ Fleet: 1, fleet_current_index: 1                           
INFO     11:47:18.545 │ In sight: B3                                               
INFO     11:47:18.546 │ Focus to: D3                                               
INFO     11:47:18.548 │ Map swipe: (0, -2)                                         
INFO     11:47:18.553 │ Swipe ( 634,  197) -> ( 635,  457)                         
INFO     11:47:19.354 │            tile_center: 0.922 (good match)                 
INFO     11:47:19.367 │ 0.088s      edge_lines: 0 hori, 1 vert                     
INFO     11:47:19.370 │ Edges: /     homo_loca: ( 32,  50)                         
INFO     11:47:19.378 │            center_loca: (3, 3)                             
INFO     11:47:19.417 │ Map swipe predict: (0, -2) (0.036s, current fleet match)   
INFO     11:47:19.420 │                 Camera: D3                                 
INFO     11:47:19.422 │                 Camera: D3                                 
INFO     11:47:19.584 │ 0.161s         predict: 48                                 
INFO     11:47:19.587 │ -- -- -- -- -- -- -- -- --                                 
INFO     11:47:19.588 │ -- -- -- -- -- -- -- -- ..                                 
INFO     11:47:19.590 │ -- -- 2E -- -- -- -- -- ..                                 
INFO     11:47:19.591 │ Fl -- LE -- -- -- -- -- ..                                 
INFO     11:47:19.592 │ -- -- -- -- -- -- -- 1M ..                                 
INFO     11:47:19.594 │ FL -- -- -- -- -- -- .. ..                                 
INFO     11:47:19.595 │ Map swipe: (0, 0)                                          
INFO     11:47:19.597 │ Global B3 (camera=D3) -> Local B4 (center=D4)              
INFO     11:47:19.601 │ Click ( 372,  374) @ B4                                    
WARNING  11:47:21.082 │ Map walk out of step.                                      
ERROR    11:47:23.232 │ MapWalkError: walk_out_of_step                             
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\map\fleet.py: │
         │ 491 in goto                                                            │
         │                                                                        │
         │    489 │   │   │   │   │   │   self._goto(grids[0], expected='')       │
         │    490 │   │   │   │   try:                                            │
         │ ❱  491 │   │   │   │   │   self._goto(node, expected=expected if node  │
         │    492 │   │   │   │   except MapWalkError:                            │
         │    493 │   │   │   │   │   logger.warning('Map walk error.')           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ expected = 'combat_siren'                                          │ │
         │ │ location = (2, 2)                                                  │ │
         │ │     node = (2, 2)                                                  │ │
         │ │    node_ = (1, 2)                                                  │ │
         │ │    nodes = [(2, 2)]                                                │ │
         │ │   nodes_ = [(1, 2), (2, 2)]                                        │ │
         │ │ optimize = True                                                    │ │
         │ │     self = <campaign.event_20230223_cn.a2.Campaign object at       │ │
         │ │            0x0000014CED52BB48>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ C:X\AzurLaneAutoScript\module\map\fleet.py: │
         │ 373 in _goto                                                           │
         │                                                                        │
         │    371 │   │   │   │                                                   │
         │    372 │   │   │   │   if self.handle_walk_out_of_step():              │
         │ ❱  373 │   │   │   │   │   raise MapWalkError('walk_out_of_step')      │
         │    374 │   │   │   │                                                   │
         │    375 │   │   │   │   # Arrive                                        │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │          ambushed_retry = Timer(limit=0.0/0.5, count=2/2)          │ │
         │ │          arrive_checker = False                                    │ │
         │ │          arrive_predict = ''                                       │ │
         │ │            arrive_timer = Timer(limit=0.0/0.5, count=2/2)          │ │
         │ │ arrive_unexpected_timer = Timer(limit=0.0/1.5, count=6/6)          │ │
         │ │                 arrived = False                                    │ │
         │ │                expected = 'combat_siren'                           │ │
         │ │                   extra = 0                                        │ │
         │ │                    grid = C4                                       │ │
         │ │               is_portal = False                                    │ │
         │ │                location = (2, 2)                                   │ │
         │ │      may_submarine_icon = False                                    │ │
         │ │                 mystery = False                                    │ │
         │ │                  result = 'nothing'                                │ │
         │ │          result_mystery = ''                                       │ │
         │ │                    self = <campaign.event_20230223_cn.a2.Campaign  │ │
         │ │                           object at 0x0000014CED52BB48>            │ │
         │ │            walk_timeout = Timer(limit=9.519/20, count=2/0)         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         MapWalkError: walk_out_of_step                                            
                                                                                   
         During handling of the above exception, another exception occurred:       
                                                                                   
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:X\AzurLaneAutoScript\alas.py:63 in run    │
         │                                                                        │
         │    61 │   │   try:                                                     │
         │    62 │   │   │   self.device.screenshot()                             │
         │ ❱  63 │   │   │   self.__getattribute__(command)()                     │
         │    64 │   │   │   return True                                          │
         │    65 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭───────────────────────────── locals ─────────────────────────────╮   │
         │ │ command = 'event'                                                │   │
         │ │       e = MapWalkError('walk_out_of_step')                       │   │
         │ │    self = <alas.AzurLaneAutoScript object at 0x0000014CBE702048> │   │
         │ ╰──────────────────────────────────────────────────────────────────╯   │
         │ C:X\AzurLaneAutoScript\alas.py:349 in event │
         │                                                                        │
         │   347 │   │   from module.campaign.run import CampaignRun              │
         │   348 │   │   CampaignRun(config=self.config, device=self.device).run( │
         │ ❱ 349 │   │   │   name=self.config.Campaign_Name, folder=self.config.C │
         │       mode=self.config.Campaign_Mode)                                  │
         │   350 │                                                                │
         │   351 │   def event2(self):                                            │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ CampaignRun = <class 'module.campaign.run.CampaignRun'>            │ │
         │ │        self = <alas.AzurLaneAutoScript object at                   │ │
         │ │               0x0000014CBE702048>                                  │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\campaign\run. │
         │ py:294 in run                                                          │
         │                                                                        │
         │   292 │   │   │   # Run                                                │
         │   293 │   │   │   try:                                                 │
         │ ❱ 294 │   │   │   │   self.campaign.run()                              │
         │   295 │   │   │   except ScriptEnd as e:                               │
         │   296 │   │   │   │   logger.hr('Script end')                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ folder = 'event_20230223_cn'                                       │ │
         │ │   mode = 'normal'                                                  │ │
         │ │   name = 'a2'                                                      │ │
         │ │   self = <module.campaign.run.CampaignRun object at                │ │
         │ │          0x0000014CED31E188>                                       │ │
         │ │  total = 0                                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\campaign\camp │
         │ aign_base.py:141 in run                                                │
         │                                                                        │
         │   139 │   │   │   try:                                                 │
         │   140 │   │   │   │   if not self.map_is_auto_search:                  │
         │ ❱ 141 │   │   │   │   │   self.execute_a_battle()                      │
         │   142 │   │   │   │   else:                                            │
         │   143 │   │   │   │   │   self.auto_search_execute_a_battle()          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │    _ = 0                                                           │ │
         │ │ self = <campaign.event_20230223_cn.a2.Campaign object at           │ │
         │ │        0x0000014CED52BB48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\campaign\camp │
         │ aign_base.py:100 in execute_a_battle                                   │
         │                                                                        │
         │    98 │   │   for _ in range(10):                                      │
         │    99 │   │   │   try:                                                 │
         │ ❱ 100 │   │   │   │   result = self.battle_function()                  │
         │   101 │   │   │   │   break                                            │
         │   102 │   │   │   except MapEnemyMoved:                                │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │      _ = 0                                                         │ │
         │ │   prev = 0                                                         │ │
         │ │ result = False                                                     │ │
         │ │   self = <campaign.event_20230223_cn.a2.Campaign object at         │ │
         │ │          0x0000014CED52BB48>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\base\decorato │
         │ r.py:70 in wrapper                                                     │
         │                                                                        │
         │    68 │   │   │   │   │   │   continue                                 │
         │    69 │   │   │   │   │                                                │
         │ ❱  70 │   │   │   │   │   return record['func'](self, *args, **kwargs) │
         │    71 │   │   │   │                                                    │
         │    72 │   │   │   │   logger.warning(f'No option fits for {name}, usin │
         │       func.')                                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │   args = ()                                                        │ │
         │ │    cls = <class 'module.base.decorator.Config'>                    │ │
         │ │   flag = [True, True]                                              │ │
         │ │   func = <function CampaignBase.battle_function at                 │ │
         │ │          0x0000014CEE0425E8>                                       │ │
         │ │ kwargs = {}                                                        │ │
         │ │ logger = <Logger alas (INFO)>                                      │ │
         │ │   name = 'battle_function'                                         │ │
         │ │ record = {                                                         │ │
         │ │          │   'options': {                                          │ │
         │ │          │   │   'MAP_CLEAR_ALL_THIS_TIME': False,                 │ │
         │ │          │   │   'POOR_MAP_DATA': False                            │ │
         │ │          │   },                                                    │ │
         │ │          │   'func': <function CampaignBase.battle_function at     │ │
         │ │          0x0000014CEE0425E8>                                       │ │
         │ │          }                                                         │ │
         │ │   self = <campaign.event_20230223_cn.a2.Campaign object at         │ │
         │ │          0x0000014CED52BB48>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\campaign\camp │
         │ aign_base.py:90 in battle_function                                     │
         │                                                                        │
         │    88 │   │   func = self.__getattribute__(func)                       │
         │    89 │   │                                                            │
         │ ❱  90 │   │   result = func()                                          │
         │    91 │   │                                                            │
         │    92 │   │   return result                                            │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ extra_battle = 0                                                   │ │
         │ │         func = <bound method Campaign.battle_0 of                  │ │
         │ │                <campaign.event_20230223_cn.a2.Campaign object at   │ │
         │ │                0x0000014CED52BB48>>                                │ │
         │ │         self = <campaign.event_20230223_cn.a2.Campaign object at   │ │
         │ │                0x0000014CED52BB48>                                 │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\campaign\event_20230 │
         │ 223_cn\a2.py:67 in battle_0                                            │
         │                                                                        │
         │   65 │                                                                 │
         │   66 │   def battle_0(self):                                           │
         │ ❱ 67 │   │   if self.clear_siren():                                    │
         │   68 │   │   │   return True                                           │
         │   69 │   │   if self.clear_filter_enemy(self.ENEMY_FILTER, preserve=0) │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.event_20230223_cn.a2.Campaign object at           │ │
         │ │        0x0000014CED52BB48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\map\map.py:46 │
         │ 5 in clear_siren                                                       │
         │                                                                        │
         │   463 │   │   │   else:                                                │
         │   464 │   │   │   │   expected = 'siren'                               │
         │ ❱ 465 │   │   │   self.clear_chosen_enemy(grids[0], expected=expected) │
         │   466 │   │   │   return True                                          │
         │   467                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ expected = 'siren'                                                 │ │
         │ │    grids = <module.map.map_grids.SelectedGrids object at           │ │
         │ │            0x0000014CEDBB0688>                                     │ │
         │ │   kwargs = {'sort': ('weight', 'cost_2')}                          │ │
         │ │     self = <campaign.event_20230223_cn.a2.Campaign object at       │ │
         │ │            0x0000014CED52BB48>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\map\map.py:27 │
         │ in clear_chosen_enemy                                                  │
         │                                                                        │
         │    25 │   │   if self.emotion.is_calculate and self.config.Campaign_Us │
         │    26 │   │   │   self.emotion.wait(fleet_index=self.fleet_current_ind │
         │ ❱  27 │   │   self.goto(grid, expected=expected)                       │
         │    28 │   │                                                            │
         │    29 │   │   self.full_scan()                                         │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ expected = 'combat_siren'                                          │ │
         │ │     grid = C3                                                      │ │
         │ │     self = <campaign.event_20230223_cn.a2.Campaign object at       │ │
         │ │            0x0000014CED52BB48>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:\X\AzurLaneAutoScript\module\map\fleet.py: │
         │ 498 in goto                                                            │
         │                                                                        │
         │    496 │   │   │   │   │   nodes_ = self.map.find_path(node, step=1)   │
         │    497 │   │   │   │   │   for node_ in nodes_:                        │
         │ ❱  498 │   │   │   │   │   │   self._goto(node_, expected=expected if  │
         │        '')                                                             │
         │    499 │   │   else:                                                   │
         │    500 │   │   │   self._goto(location, expected=expected)             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ expected = 'combat_siren'                                          │ │
         │ │ location = (2, 2)                                                  │ │
         │ │     node = (2, 2)                                                  │ │
         │ │    node_ = (1, 2)                                                  │ │
         │ │    nodes = [(2, 2)]                                                │ │
         │ │   nodes_ = [(1, 2), (2, 2)]                                        │ │
         │ │ optimize = True                                                    │ │
         │ │     self = <campaign.event_20230223_cn.a2.Campaign object at       │ │
         │ │            0x0000014CED52BB48>                                     │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ C:X\AzurLaneAutoScript\module\map\fleet.py: │
         │ 373 in _goto                                                           │
         │                                                                        │
         │    371 │   │   │   │                                                   │
         │    372 │   │   │   │   if self.handle_walk_out_of_step():              │
         │ ❱  373 │   │   │   │   │   raise MapWalkError('walk_out_of_step')      │
         │    374 │   │   │   │                                                   │
         │    375 │   │   │   │   # Arrive                                        │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │          ambushed_retry = Timer(limit=0.0/0.5, count=2/2)          │ │
         │ │          arrive_checker = False                                    │ │
         │ │          arrive_predict = ''                                       │ │
         │ │            arrive_timer = Timer(limit=0.0/0.5, count=2/2)          │ │
         │ │ arrive_unexpected_timer = Timer(limit=0.0/1.5, count=6/6)          │ │
         │ │                 arrived = False                                    │ │
         │ │                expected = 'combat_siren'                           │ │
         │ │                   extra = 0                                        │ │
         │ │                    grid = B4                                       │ │
         │ │               is_portal = False                                    │ │
         │ │                location = (1, 2)                                   │ │
         │ │      may_submarine_icon = False                                    │ │
         │ │                 mystery = False                                    │ │
         │ │                  result = 'nothing'                                │ │
         │ │          result_mystery = ''                                       │ │
         │ │                    self = <campaign.event_20230223_cn.a2.Campaign  │ │
         │ │                           object at 0x0000014CED52BB48>            │ │
         │ │            walk_timeout = Timer(limit=3.583/20, count=2/0)         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         MapWalkError: walk_out_of_step                                            
WARNING  11:47:24.051 │ Saving error: ./log/error/1677408444051                    
INFO     11:47:24.501 │ No provider specified, skip sending

**Comment by LmeSzinc** [comment]
Your fleet can only go 2 grids each turn, set `Fleet 1 Step Number` to `2`. Placing DDs in fleet can increase the walk distance.

**Comment by Oplikk** [comment]
Thanks, did not notice that I switched the fleets.
