### ISSUE TITLE
希望能在限定池时自动每日三抽，其他时间每日一抽轻型池

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [LmeSzinc/AzurLaneAutoScript#2303]
### 解决方案

在抽卡界面自动识别限定池，并且在设置页面增加相关的设置选项

**Comment by guoh064** [comment]
目前的每日抽卡任务是设置在服务器0点的时候，在活动当天的0点并没有实装限定池，那么当天这个任务是做还是不做呢？是否要推迟到活动开始？以及各个服务器更新时间不同（国服是服务器9点，日服是服务器13点）
如果限定池毕业了，那么仍然能识别到限定池资源，这个时候每日是抽三抽还是单抽呢？如果到最后一天还没毕业，是不是还得抽卡？
以上涉及的我觉得更多是游戏策略而非机械重复劳动。
感觉有这么多问题，我个人的处理方法是在活动前一天关掉每日抽卡，等毕业了之后再开启每日抽卡，感觉比自动化方便；

另外，如果限定池抽卡都自动了，那玩这个游戏的意义是什么呢……

**Comment by 0O0o0oOoO00** [comment]
> 目前的每日抽卡任务是设置在服务器0点的时候，在活动当天的0点并没有实装限定池，那么当天这个任务是做还是不做呢？是否要推迟到活动开始？以及各个服务器更新时间不同（国服是服务器9点，日服是服务器13点） 如果限定池毕业了，那么仍然能识别到限定池资源，这个时候每日是抽三抽还是单抽呢？如果到最后一天还没毕业，是不是还得抽卡？ 以上涉及的我觉得更多是游戏策略而非机械重复劳动。 感觉有这么多问题，我个人的处理方法是在活动前一天关掉每日抽卡，等毕业了之后再开启每日抽卡，感觉比自动化方便；
> 
> 另外，如果限定池抽卡都自动了，那玩这个游戏的意义是什么呢……

alas是为 7x24 运行的场景而设计的，那理应考虑到抽卡相关的问题，而非人为频繁地根据卡池去调整抽卡设置
关于你提到抽卡时间的问题，可以在卡池开启当天延迟抽卡，比如号主当天一天都没有抽卡则自动在这一天快结束的时候三抽或者抽指定数量。
关于卡池毕业后是否继续抽和直到到最后一天还没毕业是否继续抽或者干脆梭哈或者再抽指定数量的卡，都可以放到设置中，这个只针对限定池

**Comment by bookbug666** [comment]
Alas目前已經有檢測不到活動池的時候，切換回輕型池的設計了，你只要在活動開始的時候切換到活動池並把數量調整為3就好

至於畢業了自動切池，或是滿突就不造這種目前沒有好的方法實現，還請理解Alas是有其局限性的

**Comment by LmeSzinc** [comment]
嗯，你选择抽活动池，那在没有活动池的时候，Alas会自动回退到轻型池，因此你可以一直选着 `活动池` 而不受游戏活动排期的影响。
