### ISSUE TITLE
希望大世界开荒能增加一个休眠间隔

### ISSUE THREAD

**Issue by Moonlight3399** [LmeSzinc/AzurLaneAutoScript#2307]
### 你的功能请求是否与问题有关？

月初开荒的时候，如果已购买5000油道具，一次性开荒可能会消耗很长时间。
期间其他同样处于0点刷新的任务都会一直处于队列状态，比如每日任务，困难图等
如果开荒在一天内没有消耗完当前行动力，这些任务一直不会进入执行阶段
可能就拖到了第二天浪费了次数

### 解决方案

大世界开荒功能执行2-3小时后进行一个短暂的休眠期，30分钟-1小时
以供队列内其他任务执行

**Comment by guoh064** [comment]
“大世界开荒完全可以由alas执行，不需要买5000油，会以27分钟为间隔依次压制每个海域”

**Comment by LmeSzinc** [comment]
嗯，如果你希望有间隔地运行就不买5000油道具，如果你需要马上嘎嘎打完就买。
