### ISSUE TITLE
紧急委托换船时必定会卸下装备

### ISSUE THREAD

**Issue by Zuosizhu** [LmeSzinc/AzurLaneAutoScript#2311]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/8cc2f57d701f341f21a03c07aa0692c44a1c0ae9/module/campaign/gems_farming.py#L104-L121
更换舰船时肯定会卸下装备，但不一定会装备上装备

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

正确处理装备

### 截图

![~RGWMLDJW{)48WFT` V{2`L](https://user-images.githubusercontent.com/60862861/222075622-114d24f4-b262-41d2-9552-bd3de1cab941.png)

**Comment by Zuosizhu** [comment]
或许旗舰是故意的，但是前锋不能出这个问题啊（捂脸）

**Comment by pein0saga** [comment]
> 旗舰是故意的

旗舰必须故意换，否则自动退役会把装备拆了。
