### ISSUE TITLE
紧急委托为啥变的旗舰看心情了

### ISSUE THREAD

**Issue by lu28826167** [LmeSzinc/AzurLaneAutoScript#2316]
### 你的功能请求是否与问题有关？

我感觉很不合理啊 最后不都要退役 为啥要改成心情红就换呢。。。。

**Comment by ec7529a2** [comment]
主要原因：开发者个人反对红脸出击
次要原因：刷委托时alas不计算心情值，而是看到红脸弹窗就去换船，后排红脸时继续出击就没法知道前排是否红脸
（但是换船时能看到心情值且alas会识别心情值，所以是可以计算的）

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2322#issuecomment-1482330524
