### ISSUE TITLE
希望刷委托功能将更换舰船与计算心情改成可选项

### ISSUE THREAD

**Issue by minatoAI** [LmeSzinc/AzurLaneAutoScript#2322]
### 你的功能请求是否与问题有关？

刷委托功能更新后，没有了心情计算，并且会更换低等级的主力
- 而一般没有那么多可供更换的主力，节约升级增加的一点油耗不如简化操作，只用固定的那几个船

> 考虑到刷委托的效率需要，个人会弄三个编队六个船放到后宅回复心情，开启心情计算并轮流出击

### 解决方案

希望能够把计算心情与更换舰船做成可选项

- 如果可以的话，在别的出击（如主线图2，主线图3）设置里增加“防止委托数量过多”的选项

**Comment by LmeSzinc** [comment]
`刷紧急委托` 的任务的特性就是将后排更换为低级白皮轻航以节省 1 油，如果不换的话这个任务就和 `主线图` 一样，没有存在的意义。
