### ISSUE TITLE
每日任务中其他商店的功能细化

### ISSUE THREAD

**Issue by ElephantWorld** [LmeSzinc/AzurLaneAutoScript#2324]
### 你的功能请求是否与问题有关？

问题:
有一部分舰娘添加到了军需商店,这部分舰娘在军需商店中随机刷新,如果缺少舰娘需要每天上线查看刷新.(蓝鳃鱼等了2个月才刷到).

### 解决方案

能否设置军需商店自动购买 new 船的功能,
或者自定义购买指定舰娘(以防不小心退役,需要重新购买).

**Comment by LmeSzinc** [comment]
在过滤器内填入船的英文名就可以了，比如蓝鳃鱼是 Bluegill，具体船的名称参考 assets/shop/merit 目录下的图片。
