### ISSUE TITLE
MAA插件活动关卡的导航问题

### ISSUE THREAD

**Issue by yokinanya** [LmeSzinc/AzurLaneAutoScript#2338]
### 你的功能请求是否与问题有关？

上游issue：https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/3916
活动【落叶逐火】的导航功能并没有内置到MAA中，需要UI自行下载

**Comment by SaiCateDoan** [comment]
#2341
已经修了，我本地测试没问题
