### ISSUE TITLE
MAA插件的基建换班无法执行

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2346]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

运行后提示心情设置错误
我使用的是默认设置

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/103177863/223998793-d4285918-30e1-4b86-8af8-9ba8afe10015.png)
![image](https://user-images.githubusercontent.com/103177863/223998840-9497b98d-247d-42a9-91e4-3b9c97dd849e.png)

**Comment by SaiCateDoan** [comment]
#2345
