### ISSUE TITLE
请问侧边栏怎么删除？

### ISSUE THREAD

**Issue by XuhaiOuroboros** [LmeSzinc/AzurLaneAutoScript#2361]
多余的侧边栏请问怎么删除，不小心多点了几个。

**Comment by LmeSzinc** [comment]
在config文件夹下删除对应名称的配置，然后 CTRL+R 刷新 Alas。

![image](https://user-images.githubusercontent.com/37934724/224785382-b7b67f44-5ae7-4794-a5bd-9e0afbc1fc23.png)
