### ISSUE TITLE
大世界商店的商店不购买紫币

### ISSUE THREAD

**Issue by q9722088** [LmeSzinc/AzurLaneAutoScript#2364]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我确认我开启了大世界商店购买全部的选项,但是我在偶尔登录游戏时会发现大世界商贷能没有清空,而且剩下的都是紫币.
有两种猜测:
1. 当时白币数量不够,无法购买全部(但是四个商店都只剩下紫币没有购买,感觉不是这个原因)
2. 紫币默认为不会购买

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

清空大世界商店

**Comment by D9Lose** [comment]
先看一眼侵蚀1和短猫的逻辑再讲这个......
如果真的有也是先把log摆出来
不要搞猜谜式交流

**Comment by SaiCateDoan** [comment]
#2374 
 
> 如果你曾经使用过侵蚀一练级的任务，就会发现在侵蚀一任务启用的情况下，Alas 既不会买港口商店里的紫币，也不会买明石商店里的紫币。
