### ISSUE TITLE
建议长时间无任务时自动设置成30帧降低占用

### ISSUE THREAD

**Issue by JYL32tgr** [LmeSzinc/AzurLaneAutoScript#2371]
### 你的功能请求是否与问题有关？

比如，每日做完，就剩收委托这种间隔长的任务时，长时间挂在后台60帧并没有太大的意义。或许可以由alas自动设置成30帧挂机，要用的时候再恢复？

**Comment by LmeSzinc** [comment]
Alas设置 - 优化设置 - 当任务队列清空后 - 关闭游戏

![image](https://user-images.githubusercontent.com/37934724/225811649-8be7d8b9-109c-4bfc-ade2-21a1891c1bf1.png)

**Comment by JYL32tgr** [comment]
感谢回复！
