### ISSUE TITLE
大世界“侵蚀一练级”以及“回港修理”逻辑改进

### ISSUE THREAD

**Issue by shawnyuan-cn** [LmeSzinc/AzurLaneAutoScript#2374]
### 你的功能请求是否与问题有关？

目前状态是，进入侵蚀一地图后，会自动放弃本次关卡，用官方的计划作战实现自律，而这放弃的一次如果刷出明石商店便会使行动力收益下降。

### 解决方案

希望能够改进“侵蚀一练级”逻辑，**第一次进入地图会开始自律，待检测到本次自律结束会开始检测探索地图资源（明石商店、装置），再进行计划作战自律**。

**Comment by shawnyuan-cn** [comment]
补充：

1. 当练度不足在连续作战侵蚀一触发探索地图资源（明石商店、装置）停止之后，此时若血量低于一定比例，触发了大世界通用设置中**回港修理，便会反复触发**上述“进入侵蚀一地图后，自动放弃本次关卡，用计划作战实现自律”造成收益进一步下降。
2. 当练度不足在连续作战侵蚀一**次数过多**，未能触发探索地图资源（明石商店、装置）而停止，前排或旗舰沉没会触发战斗失败而报错。希望回港修理增加**战斗后血量检测**的逻辑，修理后再返回自律（未探索完的地图再次进入是不消耗行动力的）。

以下单讨论回港修理的优化：

1. 毕竟不是每个队伍都携带了奶妈，回港修理增加**战斗后血量检测**的逻辑也同样可以优化大世界其他功能，如每日任务（任务刷在高侵蚀等级区域）、红漩涡（塞壬要塞），但黄宝箱（隐秘海域）等退出后不能再次进入的区域不应触发回港修理。
2. 另外舰船血量不足时，除了回港修理也可以**优先使用背包中的维修箱**（每月回收、数量众多且**不消耗白票**），这点还可以实现黄宝箱（隐秘海域）等退出后不能再次进入的区域的维修需求。

**Comment by shawnyuan-cn** [comment]
另外明石商店紫币白票兑换比为80:1，港口商店中兑换比为100:1。

希望增加：
1. **开放“侵蚀一练级”中明石商店紫币兑换**的选项。
2. **关闭港口商店兑换紫币**的选项。

**Comment by LmeSzinc** [comment]
> 目前状态是，进入侵蚀一地图后，会自动放弃本次关卡，用官方的计划作战实现自律，而这放弃的一次如果刷出明石商店便会使行动力收益下降。

#2367

**Comment by LmeSzinc** [comment]
> 毕竟不是每个队伍都携带了奶妈，回港修理增加战斗后血量检测的逻辑也同样可以优化大世界其他功能，如每日任务（任务刷在高侵蚀等级区域）、红漩涡（塞壬要塞），但黄宝箱（隐秘海域）等退出后不能再次进入的区域不应触发回港修理。

事实是几乎所有人的道中队伍都携带了奶妈，现在预装填奶角色太多，不说限定的英仙座，还有常驻的独角兽改。任何软件都无法满足所有人的需求，Alas 是为大部分人的需求和主流游戏玩法设计的。为什么维修箱的功能一直没做，因为需求太少。

> 另外明石商店白票紫币兑换比为80:1，港口商店中兑换比为100:1。
> 希望增加：
> 
> 开放“侵蚀一练级”中明石商店紫币兑换的选项。
> 关闭港口商店兑换紫币的选项。
> 由于港口商店兑换比低，因此在港口商店用30000白票兑换300紫币对于刷侵蚀一来说是完全的负收益。

我已经在怀疑你是否使用过 Alas，从你目前的话语来看，我认为你完全没有使用过，并且还是带着偏见来的。如果你曾经打开过 Alas，就会知道 `大世界通用设置` - `商店过滤器` 能设置明石商店的购买，如果你曾经使用过侵蚀一练级的任务，就会发现在侵蚀一任务启用的情况下，Alas 既不会买港口商店里的紫币，也不会买明石商店里的紫币。

侵蚀一是通过大量消耗黄币来换取收益的，运行 24 小时大约消耗 10w 黄币，因此需要节省黄币。在每月使用 Alas 全勤大世界的情况下紫币是完全溢出的，不需要额外购买，白票也是溢出的，不需要额外贪。因此在运行侵蚀一的情况下需要通过以下方式维持黄币：
1. 将多余的行动力用于短猫，获取黄币
2. 禁止购买明石商店里的紫币
3. 禁止购买港口商店里的紫币

**Comment by shawnyuan-cn** [comment]
> 我已经在怀疑你是否使用过 Alas，从你目前的话语来看，我认为你完全没有使用过，并且还是带着偏见来的。

@LmeSzinc 
首先简单回应一下，你可以认为我对于软件使用摸索的不够清晰透彻，但不能片面的认为我怀着偏见来提出意见。
我确实是碧蓝三个月的萌新，但使用 Alas 也至少有了两个月的时间，之前接触过明日方舟的 maa 并在长期使用，Alas 中的任务选项确实很多，我摸索的还不够透彻，这点需要向大大道歉。
我个人很感谢大大在内的 Alas 开发者们，毕竟无偿给我们有需求的玩家带来了便利，非常感谢。

> `大世界通用设置` - `商店过滤器` 能设置明石商店的购买，如果你曾经使用过侵蚀一练级的任务，就会发现在侵蚀一任务启用的情况下，Alas 既不会买港口商店里的紫币，也不会买明石商店里的紫币。

这一点就要说明一下我对于 Alas 的使用习惯了：
1. 个人的 `侵蚀一练级` 任务并不是常驻开启的，一般有选择的手动开启（肝科研经验、练舰船等级时），在不需要时我会手动关闭任务以退出游戏降低CPU占用而非无休止的刷侵蚀一。
2. 与之相对 `大世界商店` 任务常驻开启。
**因为个人使用原因才造成了在经常使用“侵蚀一练级”的情况下港口商店兑换了紫币，因此我还是提议在“侵蚀一练级”任务关闭时也可以有选择的关闭港口商店黄币兑换紫币（单独排除或添加过滤器）**。

> 另外明石商店白票紫币兑换比为 80:1，港口商店中兑换比为 100:1 。

关于我所提议的有个收益比的最后一点，我描述的可能有些不太准确。
1. 每月结算时紫币白票转换比为 1:1 、黄币白票转换比为 100:1 ；
2. 港口商店中黄币紫币兑换比为 100:1 ；
3. 明石商店中黄币紫币兑换比为 80:1 ；
综合以上因素我才提议 可以`开放“侵蚀一练级”中明石商店紫币兑换` 用以提高月末结算转换白票的效率。

最后重申关于以上所有的这些只是针对对于我个人使用情况的一些反馈，表达的也只是我个人的一些改进期望，大大的时间当然是有限的，我的有些期望无法实现也是理所应当，请允许我再次表达我的感谢。

**Comment by haoyu-sunshine** [comment]
侵蚀1练级不是月末，短猫保留 X 点行动力设置一个比较大的数字，仍然会跳去短猫相接，不知道是自身使用的问题还是什么情况
