### ISSUE TITLE
新增等級須認知覺醒時停止

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#2375]
### 你的功能请求是否与问题有关？

現在已經有等級低於X的船，到達X級時停止
但似乎沒有一個偵測可覺醒時停止的功能，如
- 99-100
- 104-105
- 109-110
- 114-115
- 119-120
- 124-125

黃雞至今都沒有把心智的獲取加大，沒買心智根本沒法突船
想著至少我能先把經驗堆起來，卡等了就換一艘，哪天有活動或是送了一堆心智覺醒後又可以讓alas幫我看什麼時候滿了

### 解决方案

100級之後每一等的級距足夠大，應該不會出現70級以前那種有可能一次升兩等的
所以應該監測現在等級跟最接近的覺醒等級就好

也不用多艘船，有`任一艘船觸發上限`就停

**Comment by guoh064** [comment]
感觉也有必要做一个达到条件后onepush推送的功能（适用于打捞出新船、活动图满pt等等）

**Comment by bookbug666** [comment]
> 感觉也有必要做一个达到条件后onepush推送的功能（适用于打捞出新船、活动图满pt等等）

你的訴求更像是`觸發任一停止條件`時`推送onepush`，跟什麼時候onepush比較有關而不是停止條件

另外出新船以前有人提過，但好像有重複觸發的問題，這部分我不太懂，你可以看看 #1894 #2174 
~~建議開新的issue，或是問當初引入onepush的人~~(應該是18870吧，我自己對串onepush那邊比較不懂)

**Comment by LmeSzinc** [comment]
可以直接填入，达到 115 级后停止这样，但是不能判断是不是卡认知觉醒了，因为 Alas 是在地图里获取角色等级的。

**Comment by bookbug666** [comment]
情景是這樣的，今天道中6船等級若為(120,120,119,104,105,109)
假設如果我填入了110，那麼119變成120的船或是104到105的船不會觸發這個

沒有辦法有一個判斷式，當
LV_OLD=5N-1, N>=20, N為整數
LV_NEW=5N

數學上我知曉怎麼判斷，但我不確定在python能不能做到/怎麼做到
手動填入相當於人工去確認當前等級，而如果要做到`達到認知覺醒門檻後停止`相當於我要把6船快到門檻的都看一遍，然後看最接近門檻的那一個，然後再填入等級，有些麻煩了，我認為應該**有機會**讓Alas代勞這個作業

~~當然如果很麻煩或是無法實現也不強求，大不了統一120才停~~

**Comment by guoh064** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/aca6bc3dc0568b37d650ceaba0a93ca73032f195/module/combat/level.py#L73-L91
看上去现在的做法主要是`after >= limit > before > 0`这个条件，
主要是这里面混含了紧急委托35级退役的判断，
不然直接改成`after / 5 >= 20 && after % 5 == 0`好了……

**Comment by ec7529a2** [comment]
还可以通过扫描战斗结束后显示的经验获取量实现“积累的经验足够升级到120级时停止”。因为即使不认知觉醒也可以存经验，有些玩家可能希望一次存够升到120的经验，这样就可以在获得心智后直接觉醒到120，不用再放进编队继续练。
另外也可以有“需要认知觉醒时自动觉醒”，因为有些玩家可能有很多心智，且不想手动觉醒。（比如刚开始用alas的咸鱼）
可以通过编队界面进入舰船详情界面来进行认知觉醒，不用去船坞里找。
