### ISSUE TITLE
执行每日任务时出现错误

### ISSUE THREAD

**Issue by windskyxb** [LmeSzinc/AzurLaneAutoScript#2378]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在更新了限时兵装挑战后，哪怕设置不打限时兵装本，都会出现错误

### 如何复现

启用每日任务这个功能
启动调度器
执行每日任务时出现错误

### 相关 Logs

```Text
https://wwee.lanzouy.com/iX4Dj0qhxxmh
```

### 截图

![image](https://user-images.githubusercontent.com/60282327/226155039-5666c228-a540-42ad-bb5a-fdfacef9c006.png)
![image](https://user-images.githubusercontent.com/60282327/226155049-4412a384-20b0-494c-920d-fdbff6715c7c.png)

**Comment by Mirageorwhatever** [comment]
今天出了另一个错误 我的商队护航只开了第二个的扫荡功能 设置也是第二个 但今天alas会直接点第一个。可能是由于今天限时兵装本结束的日子 而限时兵装本和商队护航序号一致，所以就按把商队护航当限时兵装本打了

**Comment by Rikkalxn** [comment]
我也遇到了同样的错误，我没有勾选执行破交作战，但是他总是执行每日任务的时候去自己点破交作战，然后打不过，然后就报错寄了

**Comment by LmeSzinc** [comment]
b90ed0c43a4fd7b1f58c6465ba2f1c06555c1b65
