### ISSUE TITLE
重启游戏后可能跳转到主页面

### ISSUE THREAD

**Issue by SheerYin** [LmeSzinc/AzurLaneAutoScript#2380]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

之前没这个问题，然后夜神模拟器前几天有更新，我更新后就出这个毛病了

### 如何复现

1. 等待0点，重启
2. 不知道什么原因1小时甚至更久会触发，然后在模拟器主页面。打开 近期任务 碧蓝航线是黑屏状态，点开会进行启动游戏，或者无法启动跳转到模拟器主页面
3. 我起床时才发现，重启模拟器可修复，一天内不会触发，直到0点以后

### 相关 Logs

```Text
https://pastebin.com/CyFdStMY 密码 9RYaVQWaG3
```

### 截图

![2023-03-19_01-21-31-813530](https://user-images.githubusercontent.com/83099762/226199738-a4e5e7f6-55ad-4a1f-b27c-4bb03eb2c8ea.png)

### 还有别的吗？

我尝试使用 adb shell am force-stop com.bilibili.azurlane 清除后台程序，发现还是在后台黑屏状态。不知道和这个错误有无关系
[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11012018/error.zip)
国际版夜神
![image](https://user-images.githubusercontent.com/83099762/226200555-1ac257e2-e509-457b-90a5-84171ae27813.png)

**Comment by SaiCateDoan** [comment]
你关掉了Alas的异常处理？
本来Alas应该能自动处理游戏闪退的情况，但是如果你主动关掉那就另说了
或者你可以尝试更换模拟器，使用MuMu X之类的
