### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by xiaowuAAA** [LmeSzinc/AzurLaneAutoScript#2382]
更新完bios之后打开软件突然就变成这样了，尝试重新下载软件，安装完后自动打开是正常的，但是关闭后就打不开了
也是跟这个报错一样
![KI$K03PWO19C}W4T G%` 2](https://user-images.githubusercontent.com/61065165/226425961-406fa84a-ef5e-45f8-a05e-e20ef4623c0a.png)

**Comment by LmeSzinc** [comment]
文件损坏了，把 `C:\Users\LmeSzinc\AppData\Local\Temp\gen_py\3.7\dicts.dat` 删掉就好了，`LmeSzinc` 替换成你电脑的用户名。

**Comment by xiaowuAAA** [comment]
> 文件损坏了，把`C:\Users\LmeSzinc\AppData\Local\Temp\gen_py\3.7\dicts.dat`删掉就好了，`LmeSzinc`替换成你电脑的用户名。
解决了，感谢
