### ISSUE TITLE
修改module/config/argument/args.json的参数会导致ABD无法连接.

### ISSUE THREAD

**Issue by ZSJsts** [LmeSzinc/AzurLaneAutoScript#2393]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![image](https://user-images.githubusercontent.com/33511529/227429633-b8554af0-4e7c-4d9d-9821-99022049a52b.png)

备注:
我的蓝叠(BlueStack5)没有多开.我不太清楚端口不是5555的原因(每次重启蓝叠都会更换端口).有一次我因为DOCKER不得不更新WSL2然后重新关闭Hyper2后蓝叠端口就开始变化了.
但依然不影响使用.只是我需要每次开启ALAS和蓝叠时重新输入一次端口.

但是在昨天晚上我删除了整个Alas并重新安装Alas,我重新填写配置文件后就再也无法连接.

总之就是,我重装了Alas(Alas整个文件夹删除)重新下载启动,重新填写ADB端口和服务器信息等配置后alas无法连接ADB.
期间蓝叠本身没有任何变动

备注:为什么我的端口不是默认的5555:
我的蓝叠(BlueStack5)没有多开.我其实也不太清楚端口不是5555的原因(每次重启蓝叠都会更换端口).几个月前我因为DOCKER兼容性问题不得不重装了一次WSL2然后蓝叠端口就开始不正常了.但依然不影响使用.只是我需要每次开启ALAS和蓝叠时重新输入一次端口.

我有一个刷机时用的ADB,我把ALAS的adb关掉后用这个ADB尝试连接蓝叠.是正常的.
如图
![image](https://user-images.githubusercontent.com/33511529/227429145-6e20c862-79c3-4ae0-8636-d70dccd564c1.png)

我猜测可能不是Alas的问题.
但是从正常到出现问题前后唯一的变动只有删除并重装ALAS.所以我无法找出问题所在.HELP ME :/

(在问题发生后我重装了一次Bluestacks,情况没有发生变化...)

**Comment by ZSJsts** [comment]
问题解决了
ALAS似乎存在一些奇怪的残留和读取.
我把KeepLocalChanges改回默认后,将被我改过的文件复制出了一份并重命名.
重启Alas后Python开始报错并提示文件尝试读取到了被我重命名的备份文件(重新拉取git得到的默认文件被无视了).
我关闭ADB和python后台删除整个ALAS重装,问题依旧.
最后清理临时文件后再次重装,依然会弹出先前出现的报错窗口.但点击后消失然后一切恢复正常.
ADB端口也能正常连接了.

**Comment by LmeSzinc** [comment]
> 最后清理临时文件后再次重装,依然会弹出先前出现的报错窗口.但点击后消失然后一切恢复正常.

什么报错窗口

**Comment by ZSJsts** [comment]
> > 最后清理临时文件后再次重装,依然会弹出先前出现的报错窗口.但点击后消失然后一切恢复正常.
> 
> 什么报错窗口

额.忘记截了.就是ALAS启动后跟随弹出的PY报错窗口(UI和ALAS相同).

上面的错误信息是PY发生了某种读取错误然后返回了最近的几次调用.

我当时粗略看了看那些错误信息.

在这之前
我修改了KeepLocalChanges后又修改了module\config.py,
我想重置回原样,然后我就把KeepLocalChanges改回来然后把config.py复制出一份"config修改备份.py"
重启ALAS后config.py被覆盖(我打开看了).

然后就发生了这些报错.
因为报错信息很长,我看到上面的一些错误都是正常的ALAS原本的PY代码.
但我往下翻了翻.发现报错涉及到了"config修改备份.py"这种文件...



我记得重装ALAS的时候我是把后台ABD和python都关闭的了(按说如果不关闭,删除文件的时候会提示占用的)
但这个问题看起来好像是Python并没有随着ALAS重装而重置数据...

前面无法连接到ABD端口可能也是这个原因.

**Comment by ZSJsts** [comment]
> > 最后清理临时文件后再次重装,依然会弹出先前出现的报错窗口.但点击后消失然后一切恢复正常.
> 
> 什么报错窗口

═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     15:38:58.568 │ Start scheduler loop: alas                                 
INFO     15:38:58.570 │ [Server] cn                                                
INFO     15:38:58.580 │ Bind task {'Alas', 'General'}                              
INFO     15:38:58.703 │ Server "オデッサ" is available.                            
INFO     15:38:58.705 │ Pending tasks: ['Commission', 'Tactical', 'Dorm',          
         'Meowfficer', 'Guild', 'Reward', 'Freebies']                              
INFO     15:38:58.706 │ [Task] Commission (Enable, 2020-01-01 00:00:00)            
INFO     15:38:58.706 │ Bind task {'Alas', 'Commission', 'General'}                
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     15:38:59.527 │ DEVICE                                                     
INFO     15:38:59.528 │ [AdbBinary] D:\app\AzurLaneBot\AzurLaneAutoScript\toolkit\L
         ib\site-packages\adbutils\binaries\adb.exe                                
INFO     15:38:59.530 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     15:38:59.531 │ <<< DETECT DEVICE >>>                                      
INFO     15:38:59.532 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     15:38:59.533 │ No available devices                                       
INFO     15:38:59.538 │ cannot resolve host '127.0.0.1' and port 52515: No such    
         host is known. (11001)                                                    
INFO     15:38:59.540 │ cannot resolve host '127.0.0.1' and port 52515: No such    
         host is known. (11001)                                                    
INFO     15:38:59.541 │ cannot resolve host '127.0.0.1' and port 52515: No such    
         host is known. (11001)                                                    
WARNING  15:38:59.542 │ Failed to connect 127.0.0.1:52515 after 3 trial, assume    
         connected                                                                 
INFO     15:38:59.543 │ <<< DETECT DEVICE >>>                                      
INFO     15:38:59.544 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     15:38:59.545 │ No available devices                                       
INFO     15:38:59.545 │ [AdbDevice] AdbDevice(serial=127.0.0.1:52515)              
INFO     15:38:59.546 │ [PackageName] com.YoStarJP.AzurLane                        
INFO     15:38:59.547 │ [Server] jp                                                
INFO     15:38:59.547 │ Screenshot interval set to 0.3s                            
INFO     15:38:59.548 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     15:38:59.551 │ Create forward: ForwardItem(serial='\x08127.0.0.1:52515',  
         local='tcp:20390', remote='tcp:53516')                                    
ERROR    15:38:59.552 │ AdbError:                                                  
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\module\device\method\droidcast.p │
         │ y:35 in retry_wrapper                                                  │
         │                                                                        │
         │    33 │   │   │   │   │   retry_sleep(_)                               │
         │    34 │   │   │   │   │   init()                                       │
         │ ❱  35 │   │   │   │   return func(self, *args, **kwargs)               │
         │    36 │   │   │   # Can't handle                                       │
         │    37 │   │   │   except RequestHumanTakeover:                         │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │      _ = 0                                                         │ │
         │ │   args = ()                                                        │ │
         │ │      e = AdbError('')                                              │ │
         │ │   func = <function DroidCast.screenshot_droidcast_raw at           │ │
         │ │          0x0000018A9370AEE8>                                       │ │
         │ │   init = None                                                      │ │
         │ │ kwargs = {}                                                        │ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x0000018A39D5EA48>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\module\device\method\droidcast.p │
         │ y:200 in screenshot_droidcast_raw                                      │
         │                                                                        │
         │   198 │   def screenshot_droidcast_raw(self):                          │
         │   199 │   │   self.config.DROIDCAST_VERSION = 'DroidCast_raw'          │
         │ ❱ 200 │   │   image = self.droidcast_session.get(self.droidcast_url(), │
         │   201 │   │   # DroidCast_raw returns a RGB565 bitmap                  │
         │   202                                                                  │
         │                                                                        │
         │ ╭───────────────────────────── locals ──────────────────────────────╮  │
         │ │ self = <module.device.device.Device object at 0x0000018A39D5EA48> │  │
         │ ╰───────────────────────────────────────────────────────────────────╯  │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\module\base\decorator.py:97 in   │
         │ __get__                                                                │
         │                                                                        │
         │    95 │   │   │   return self                                          │
         │    96 │   │                                                            │
         │ ❱  97 │   │   value = obj.__dict__[self.func.__name__] = self.func(obj │
         │    98 │   │   return value                                             │
         │    99                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │  cls = <class 'module.device.device.Device'>                       │ │
         │ │  obj = <module.device.device.Device object at 0x0000018A39D5EA48>  │ │
         │ │ self = <module.base.decorator.cached_property object at            │ │
         │ │        0x0000018A93708448>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\module\device\method\droidcast.p │
         │ y:103 in droidcast_session                                             │
         │                                                                        │
         │   101 │   │   session = requests.Session()                             │
         │   102 │   │   session.trust_env = False  # Ignore proxy                │
         │ ❱ 103 │   │   self._droidcast_port = self.adb_forward('tcp:53516')     │
         │   104 │   │   return session                                           │
         │   105                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │    self = <module.device.device.Device object at                   │ │
         │ │           0x0000018A39D5EA48>                                      │ │
         │ │ session = <requests.sessions.Session object at 0x0000018A3B02FA08> │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\module\device\connection.py:422  │
         │ in adb_forward                                                         │
         │                                                                        │
         │   420 │   │   │   forward = ForwardItem(self.serial, f'tcp:{port}', re │
         │   421 │   │   │   logger.info(f'Create forward: {forward}')            │
         │ ❱ 422 │   │   │   self.adb.forward(forward.local, forward.remote)      │
         │   423 │   │   │   return port                                          │
         │   424                                                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ forward = ForwardItem(serial='\x08127.0.0.1:52515',                │ │
         │ │           local='tcp:20390', remote='tcp:53516')                   │ │
         │ │    port = 20390                                                    │ │
         │ │  remote = 'tcp:53516'                                              │ │
         │ │    self = <module.device.device.Device object at                   │ │
         │ │           0x0000018A39D5EA48>                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\toolkit\lib\site-packages\adbuti │
         │ ls\__init__.py:591 in forward                                          │
         │                                                                        │
         │   589 │                                                                │
         │   590 │   def forward(self, local: str, remote: str):                  │
         │ ❱ 591 │   │   return self._client.forward(self._serial, local, remote) │
         │   592 │                                                                │
         │   593 │   def forward_port(self, remote: Union[int, str]) -> int:      │
         │                                                                        │
         │ ╭────────────────── locals ──────────────────╮                         │
         │ │  local = 'tcp:20390'                       │                         │
         │ │ remote = 'tcp:53516'                       │                         │
         │ │   self = AdbDevice(serial=127.0.0.1:52515) │                         │
         │ ╰────────────────────────────────────────────╯                         │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\toolkit\lib\site-packages\adbuti │
         │ ls\__init__.py:406 in forward                                          │
         │                                                                        │
         │   404 │   │   │   cmds.append(local + ";" + remote)                    │
         │   405 │   │   │   c.send_command(":".join(cmds))                       │
         │ ❱ 406 │   │   │   c.check_okay()                                       │
         │   407 │                                                                │
         │   408 │   def reverse(self, serial, remote, local, norebind=False):    │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │        c = <adbutils._AdbStreamConnection object at                │ │
         │ │            0x0000018A93456D88>                                     │ │
         │ │     cmds = [                                                       │ │
         │ │            │   'host-serial',                                      │ │
         │ │            │   '\x08127.0.0.1:52515',                              │ │
         │ │            │   'forward',                                          │ │
         │ │            │   'tcp:20390;tcp:53516'                               │ │
         │ │            ]                                                       │ │
         │ │    local = 'tcp:20390'                                             │ │
         │ │ norebind = False                                                   │ │
         │ │   remote = 'tcp:53516'                                             │ │
         │ │     self = <adbutils.AdbClient object at 0x0000018A9330C0C8>       │ │
         │ │   serial = '\x08127.0.0.1:52515'                                   │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\app\AzurLaneBot\AzurLaneAutoScript\toolkit\lib\site-packages\adbuti │
         │ ls\__init__.py:168 in check_okay                                       │
         │                                                                        │
         │   166 │   │   data = self.read_string(4)                               │
         │   167 │   │   if data == _FAIL:                                        │
         │ ❱ 168 │   │   │   raise AdbError(self.read_string_block())             │
         │   169 │   │   elif data == _OKAY:                                      │
         │   170 │   │   │   return                                               │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ data = 'FAIL'                                                      │ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x0000018A93456D88>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         AdbError                                                                  
CRITICAL 15:38:59.734 │ Possible reason #1: If you are using BlueStacks or LD      
         player or WSA, please enable ADB in the settings of your emulator         
CRITICAL 15:38:59.736 │ Possible reason #2: Emulator died, please restart emulator 
CRITICAL 15:38:59.736 │ Possible reason #3: Serial incorrect, no such device exists
         or emulator is not running                                                
CRITICAL 15:38:59.737 │ Retry screenshot_droidcast_raw() failed                    
CRITICAL 15:38:59.738 │ Request human takeover                                     
INFO     15:38:59.739 │ No provider specified, skip sending                        


我重新单独尝试了我的每一个步骤.发现问题在于只要我修改了module/config/argument/args.json就会导致ABD无法连接.
并出现上述错误.
但为什么脚本的参数改变会影响ABD?

**Comment by LmeSzinc** [comment]
#1418

这里不欢迎关委托科研的代练仔。
