### ISSUE TITLE
新活心情计算问题

### ISSUE THREAD

**Issue by Isharmla** [LmeSzinc/AzurLaneAutoScript#2396]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

刷TC3前将3队心情同时控制在150，同时都没有放在后宅，设置多队出击，刷前手动输入了alas心情值150，停止活动图后心情显示79，游戏内3队实际心情均为134

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Mo-Yuxi** [comment]
刚刚盯着日志看了一下  应该是 多队出击 的情况下各自队伍的心情计算是独立的，而alas以“进一次战斗扣2点心情”的逻辑进行的心情计算，所以出现了心情计算问题，期待修复

**Comment by LmeSzinc** [comment]
#2399
