### ISSUE TITLE
油的识别好像有时候会出问题

### ISSUE THREAD

**Issue by WolfCanglong** [LmeSzinc/AzurLaneAutoScript#2397]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

以前倒是没遇到，今天刷了一天的新活动，后面老莫名停止 一开始还以为是心情问题，看了LOG发现他频繁识别油为153，其实应该是153XX但是当时没想到是这个问题没注意看确切的油数，不过最后一次正确的应该是15375，见log，应该是17:01:33开始出现了几次
[2023-03-24_alas.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11060446/2023-03-24_alas.zip)
另外还有个报错我发现他里面油也识别错了,1545，一起传上来看看
[1679634308510.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11060460/1679634308510.zip)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by SaiCateDoan** [comment]
想主动复现的时候复现不出来，但是问题仍然存在

**Comment by WolfCanglong** [comment]
更新完到现在暂时没再碰到

**Comment by WolfCanglong** [comment]
这个问题应该还是存在 今天又遇到了几次
4000多的油识别成400多
[2023-03-28_alas.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11101468/2023-03-28_alas.zip)

**Comment by WolfCanglong** [comment]
说下我的环境看看有没有参考意义
蓝叠国际版Hyper-v，24小时挂机，发现卡的话手动重启模拟器
最近就是3队无限刷3图，一队后宅1层，打个几次后宅2层2队手动轮换，刚发那时候应该是打5次换一波，后面包括今天是打7次换，发现问题就是上去发现ALAS还有剩余次数但是不打了，我设置了心情是后宅2层不可能因为心情停的，翻LOG就发现原因是油限制停的，基本都是识别错误后面少了几位导致的。没记错的话中间几天应该确实没遇到

**Comment by zydhhh** [comment]
我也遇到这个问题了
INFO     21:54:51.110 │ <<< UI GOTO PAGE_COALITION >>>                             
INFO     21:54:51.114 │ Page switch: page_campaign_menu -> page_coalition          
INFO     21:54:51.115 │ Click ( 857,  275) @ CAMPAIGN_MENU_GOTO_EVENT              
INFO     21:54:51.730 │ Page arrive: page_coalition                                
INFO     21:54:51.732 │ [CoalitionMode] story                                      
INFO     21:54:51.748 │ [OCR_OIL 0.015s] 864                                       
INFO     21:54:51.749 │ <<< TRIGGERED STOP CONDITION: OIL LIMIT >>>                
INFO     21:54:51.750 │ Delay task `Coalition` to 2023-03-30 00:37:07 (minute=(120,240))                                                                     
INFO     21:54:51.760 │ Bind task {'Coalition', 'General', 'Alas', 'TaskBalancer', 'EventGeneral'}                                                           
INFO     21:54:51.761 │ Save config ./config\alas.json,Coalition.Scheduler.NextRun=datetime.datetime(2023, 3, 30, 0, 37, 7)      
INFO     21:54:51.769 │ Scheduler: End task `Coalition`   
![image](https://user-images.githubusercontent.com/25688118/228566198-17fac24c-08ac-4a34-88d1-aa59bde9f12a.png)
油剩余8646，ocr识别为864，少了最后一位
模拟器是蓝叠5
