### ISSUE TITLE
64位模拟器部分界面卡住无法继续

### ISSUE THREAD

**Issue by sayakii** [LmeSzinc/AzurLaneAutoScript#240]
每日任务困难演习：卡在演习次数为0
触发概率：100%
截图方案：uiautomator2（aScreenCap无法启动）
模拟器：MEmu Play
系统版本：7.1 (64bit)

演习次数打完后停住不动，手动点击<返回>后脚本可以继续执行
不知道是x64点击得太快（**比x86要快几倍**?），还是图片识别上有问题

以前还遇到过的卡在退役界面的情况
但因为我现在用这个工具只是拿来做下日常就下线了，没法触发需要退役的情况，不知道修复了没有

![Screenshot_1604995548](https://user-images.githubusercontent.com/74230987/98646651-9fd76400-236e-11eb-875c-1037cbc06918.png)

**Comment by LmeSzinc** [comment]
发 log 和截图

**Comment by sayakii** [comment]
卡在红框位置，手动点击返回后会继续
![Screenshot](https://user-images.githubusercontent.com/74230987/98650824-61dd3e80-2374-11eb-9522-55187d997b7a.png)

**Comment by LmeSzinc** [comment]
等1分钟, 卡一分钟之后会报错, 把自动保存 log 和截图发一下

**Comment by sayakii** [comment]
因为之前错误截图文件一大堆，我就把记录关了的，现在我打开了等演习恢复或者明天我再提交吧

**Comment by sayakii** [comment]
修改配置文件可以重现BUG
演示：
![demo](https://user-images.githubusercontent.com/74230987/98676233-4a16b200-2396-11eb-8cdf-b593d8fe48c4.gif)

日志：
![Screenshot](https://user-images.githubusercontent.com/74230987/98676177-3bc89600-2396-11eb-9358-c11524f5ccdf.png)

简单测试了一下，该问题**只会发生在从<演习>转到<日常>任务的时候**才会卡住
如果日常任务已有记录应该跳过时会正常回到主页面并不会卡

保存的错误截图为60张演习界面截图，没看出实际意义，已经删除

**Comment by LmeSzinc** [comment]
> 保存的错误截图为60张演习界面截图，没看出实际意义，已经删除
我只是想看一下错误截图里演习界面截图, 一张就够了, 看看和正常的有什么不同

**Comment by sayakii** [comment]
截图我挨个看过，每张都是正常的，跟普通截图没有任何区别，问题肯定不在这上面
我觉得最好的是你自己试一试看，问题可以重现，跟电脑没有关系的
Android 7.1 64位系统（我用的是逍遥海外版，国内版本内核也是一样的）

我用64位主要是它性能实在是太强了，比x86快的不是一点半点，丝般顺滑😁😁😁

**Comment by LmeSzinc** [comment]
那你发一张嘛, 我看看截图是不是压缩过

**Comment by sayakii** [comment]
好吧，我去恢复一下

**Comment by sayakii** [comment]
~~截图Discord发了~~

**Comment by LmeSzinc** [comment]
![edpsCXgWwW_635_475](https://user-images.githubusercontent.com/37934724/98684360-08d7cf80-23a1-11eb-9056-2bb6c2ec3807.png)

看了一下是压缩过, uiautomator2 会把 64 位模拟器识别为安卓真机, 调用 minicap 截图
你把截图方式改为 ADB 就好了

**Comment by whoamikyo** [comment]
> ![edpsCXgWwW_635_475](https://user-images.githubusercontent.com/37934724/98684360-08d7cf80-23a1-11eb-9056-2bb6c2ec3807.png)
> 
> 看了一下是压缩过, uiautomator2 会把 64 位模拟器识别为安卓真机, 调用 minicap 截图
> 你把截图方式改为 ADB 就好了

ALAS Easy Install package don't include minicap btw, i removed.
