### ISSUE TITLE
gitee镜像消失

### ISSUE THREAD

**Issue by Book-fall2wish** [LmeSzinc/AzurLaneAutoScript#2412]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

remote: [session-784338ad] The Repository has been blocked. see: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
fatal: unable to access 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror/': The requested URL returned error: 403
[ failure ], error_code: 128

https://gitee.com/lmeszinc/
用户已被屏蔽
重新改为github后可以正常启动

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Shawn88-ops** [comment]
一样的问题，请问现在还有其它网站吗

**Comment by Shawn88-ops** [comment]
![image](https://user-images.githubusercontent.com/57652481/228180031-ed22f374-8007-4567-a48c-5e18f3f56341.png)
改为github后仍报错QAQ

**Comment by teriri0328** [comment]
> ![图像](https://user-images.githubusercontent.com/57652481/228180031-ed22f374-8007-4567-a48c-5e18f3f56341.png)改为github后仍报错QAQ

重启一下应该就好了，你试试？

**Comment by Shawn88-ops** [comment]
已解决，别搭梯子开alas！！虽然只有梯子才能上github就是了

**Comment by xfcx123** [comment]
更新一下ALAS的文件就行

**Comment by Chassk** [comment]
很淦，我的换成github源也是报错128，只能直接跳过更新了

**Comment by Nagami-Suzuka** [comment]
在项目主人更新之前，将deploy.yaml中的链接改为'[https://github.com/LmeSzinc/AzurLaneAutoScript'，然后关闭所有代理软件（包括修改host的软件）后重启Alas。来自中国的访问，可能由于网络环境异常出现不稳定。](https://github.com/LmeSzinc/AzurLaneAutoScript'%EF%BC%8C%E7%84%B6%E5%90%8E%E5%85%B3%E9%97%AD%E6%89%80%E6%9C%89%E4%BB%A3%E7%90%86%E8%BD%AF%E4%BB%B6%EF%BC%88%E5%8C%85%E6%8B%AC%E4%BF%AE%E6%94%B9host%E7%9A%84%E8%BD%AF%E4%BB%B6%EF%BC%89%E5%90%8E%E9%87%8D%E5%90%AFAlas%E3%80%82%E6%9D%A5%E8%87%AA%E4%B8%AD%E5%9B%BD%E7%9A%84%E8%AE%BF%E9%97%AE%EF%BC%8C%E5%8F%AF%E8%83%BD%E7%94%B1%E4%BA%8E%E7%BD%91%E7%BB%9C%E7%8E%AF%E5%A2%83%E5%BC%82%E5%B8%B8%E5%87%BA%E7%8E%B0%E4%B8%8D%E7%A8%B3%E5%AE%9A%E3%80%82)

マスターがプロジェクトをアップデータするまでに、しばらくファイルdeploy.yaml中のリンクを'[https://github.com/LmeSzinc/AzurLaneAutoScrip'tに書き換えてください。また、すべでのVPNソフト（hostをコントロールするソフトも含め）を閉じてからAlasを再起動してください。中国からのアクセスは、ネットの環境によって不安定になる可能性があります。](https://github.com/LmeSzinc/AzurLaneAutoScrip't%E3%81%AB%E6%9B%B8%E3%81%8D%E6%8F%9B%E3%81%88%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82%E3%81%BE%E3%81%9F%E3%80%81%E3%81%99%E3%81%B9%E3%81%A7%E3%81%AEVPN%E3%82%BD%E3%83%95%E3%83%88%EF%BC%88host%E3%82%92%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B%E3%82%BD%E3%83%95%E3%83%88%E3%82%82%E5%90%AB%E3%82%81%EF%BC%89%E3%82%92%E9%96%89%E3%81%98%E3%81%A6%E3%81%8B%E3%82%89Alas%E3%82%92%E5%86%8D%E8%B5%B7%E5%8B%95%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82%E4%B8%AD%E5%9B%BD%E3%81%8B%E3%82%89%E3%81%AE%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%81%AF%E3%80%81%E3%83%8D%E3%83%83%E3%83%88%E3%81%AE%E7%92%B0%E5%A2%83%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6%E4%B8%8D%E5%AE%89%E5%AE%9A%E3%81%AB%E3%81%AA%E3%82%8B%E5%8F%AF%E8%83%BD%E6%80%A7%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82)

**Comment by Nagami-Suzuka** [comment]
在项目主人更新之前，将deploy.yaml中的链接改为(https://github.com/LmeSzinc/AzurLaneAutoScript)，然后关闭所有代理软件（包括修改host的软件）后重启Alas。来自中国的访问，可能由于网络环境异常出现不稳定。

マスターがプロジェクトをアップデータするまでに、しばらくファイルdeploy.yaml中のリンクを(https://github.com/LmeSzinc/AzurLaneAutoScrip)tに書き換えてください。また、すべでのVPNソフト（hostをコントロールするソフトも含め）を閉じてからAlasを再起動してください。中国からのアクセスは、ネットの環境によって不安定になる可能性があります。

**Comment by Nagami-Suzuka** [comment]
在项目主人更新之前，将deploy.yaml中的链接改为<https://github.com/LmeSzinc/AzurLaneAutoScript>，然后关闭所有代理软件（包括修改host的软件）后重启Alas。来自中国的访问，可能由于网络环境异常出现不稳定。

マスターがプロジェクトをアップデータするまでに、しばらくファイルdeploy.yaml中のリンクを<https://github.com/LmeSzinc/AzurLaneAutoScript>に書き換えてください。また、すべでのVPNソフト（hostをコントロールするソフトも含め）を閉じてからAlasを再起動してください。中国からのアクセスは、ネットの環境によって不安定になる可能性があります。

**Comment by LYSSION** [comment]
可以修改至https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/releases/tag/v2023.03.28
Alas发布新版本了，下载 AlasApp_0.4.0_cn.7z 重新安装 Alas。 
右键点击压缩包，解压到当前文件夹，把旧的config文件夹复制到新Alas去，最后双击打开 Alas.exe

**Comment by ykypz** [comment]
把config/deploy.yaml中的Repository改为Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git即可

**Comment by Crashine** [comment]
我一样的报错，改成https://github.com/LmeSzinc/AzurLaneAutoScript可以访问
