### ISSUE TITLE
镜像消失后清洁安装无法打开 V0.4.1

### ISSUE THREAD

**Issue by binglingyao** [LmeSzinc/AzurLaneAutoScript#2414]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

执行清洁安装后,无论是使用fullcn还是full包都无法打开
报错内容几乎一致寻求帮助

### 截图

![QQ图片20230329045909](https://user-images.githubusercontent.com/60381869/228365440-678d2843-27ce-4e35-a837-07865beedb0e.png)

**Comment by binglingyao** [comment]
![image](https://user-images.githubusercontent.com/60381869/228369382-aaaeb0dc-d7a9-4c19-99a9-13b766d1cc49.png)

**Comment by 1059870594** [comment]
我今天也打不开了。但是我去config/deploy.yaml重新修改了一下repo和pymi的参数就没问题了..

**Comment by kotoricon** [comment]
修改了也没用 一直报错128
![20230329080055](https://user-images.githubusercontent.com/8659834/228392956-c346f3f8-da24-4282-bb59-9979178fe205.png)

**Comment by suilbx** [comment]
![6(Q~%94VXL2M3_9GN9X0QBA](https://user-images.githubusercontent.com/87057023/228393313-36354d41-c5b4-4ca5-9f17-4e3ea5583358.png)
我修改了能修的，还是没用

**Comment by ianlee0800** [comment]
> 我今天也打不开了。但是我去config/deploy.yaml重新修改了一下repo和pymi的参数就没问题了..

@1059870594 可以問一下參數是修改成什麼嗎?

**Comment by 1059870594** [comment]
@ianlee0800 你看一下之前的issue吧。我在国外，repo和pymi不知道怎么被设置成国内的了，改成国外的就没问题了。

**Comment by lazyyumin** [comment]
看了一下文档，config/deploy.yaml下的Repository源从https://github.com/LmeSzinc/AzurLaneAutoScript改成了https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git，手动改一下就能更新了

**Comment by kotoricon** [comment]
没用的，继续128

**Comment by bimyoukyori** [comment]
管理员运行就可以，不知道什么原因。

**Comment by kotoricon** [comment]
> 管理员运行就可以，不知道什么原因。

试了一下，确实这样可行

**Comment by binglingyao** [comment]
我已经解决问题
解决方案: 强行为Alas挂梯到HK,使用github源,不要使用国内镜像

ps: 挂梯到USA和JPN并不能解决问题,就很奇怪
