### ISSUE TITLE
无法在包含空格的路径中执行此脚本自带的 .bat 文件

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#242]
PS D:\Portable Program\AzurLaneAutoScript> .\Alas-Deploy-Tool-V4.bat
系统找不到指定的路径。
此时不应有 Program\AzurLaneAutoScript\config\deploy.ini。
PS D:\Portable Program\AzurLaneAutoScript> .\alas.bat
系统找不到指定的路径。
此时不应有 Program\AzurLaneAutoScript\config\deploy.ini。

**Comment by whoamikyo** [comment]
this is not a issue, it is a technical limitation, run in a folder with no spaces in PATH.

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Troubleshooting
