### ISSUE TITLE
启动反和谐后出现错误

### ISSUE THREAD

**Issue by wEuphorIA** [LmeSzinc/AzurLaneAutoScript#2426]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动反和谐后出现错误

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

ERROR    19:53:40.025 │ ExecutionError:                                                      
         ╭─────────────────────── Traceback (most recent call last) ────────────────────────╮
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\module\webui\process_manager.py:161 in run_process    │
         │                                                                                  │
         │   159 │   │   │   │   from module.daemon.uncensored import AzurLaneUncensored    │
         │   160 │   │   │   │                                                              │
         │ ❱ 161 │   │   │   │   AzurLaneUncensored(config=config_name, task="AzurLaneUncen │
         │   162 │   │   │   elif func == "Benchmark":                                      │
         │   163 │   │   │   │   from module.daemon.benchmark import Benchmark              │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │                  _ = ['--port', '22267']                                     │ │
         │ │               args = Namespace(electron=True)                                │ │
         │ │     AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'>           │ │
         │ │ AzurLaneUncensored = <class 'module.daemon.uncensored.AzurLaneUncensored'>   │ │
         │ │        config_name = 'alas'                                                  │ │
         │ │       console_hdlr = <RichHandler (NOTSET)>                                  │ │
         │ │                  e = ExecutionError()                                        │ │
         │ │               func = 'AzurLaneUncensored'                                    │ │
         │ │             parser = ArgumentParser(prog='gui.py', usage=None,               │ │
         │ │                      description=None, formatter_class=<class                │ │
         │ │                      'argparse.HelpFormatter'>, conflict_handler='error',    │ │
         │ │                      add_help=True)                                          │ │
         │ │                  q = <AutoProxy[Queue] object, typeid 'Queue' at             │ │
         │ │                      0x20a66e6fbc8>                                          │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │ E:\alas\AzurLaneAutoScript\module\daemon\uncensored.py:34 in run                 │
         │                                                                                  │
         │   32 │   │   │   branch='master',                                                │
         │   33 │   │   │   proxy=manager.config['GitProxy'],                               │
         │ ❱ 34 │   │   │   keep_changes=False                                              │
         │   35 │   │   )                                                                   │
         │   36                                                                             │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │  folder = './toolkit/AzurLaneUncensored'                                     │ │
         │ │ manager = <deploy.git.GitManager object at 0x0000020A463CA0C8>               │ │
         │ │    prev = 'E:\\alas\\AzurLaneAutoScript'                                     │ │
         │ │    repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'                    │ │
         │ │    self = <module.daemon.uncensored.AzurLaneUncensored object at             │ │
         │ │           0x0000020A66E8B448>                                                │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\deploy\git.py:50 in git_repository_init               │
         │                                                                                  │
         │   48 │   │                                                                       │
         │   49 │   │   logger.hr('Fetch Repository Branch', 1)                             │
         │ ❱ 50 │   │   self.execute(f'"{self.git}" fetch {source} {branch}')               │
         │   51 │   │                                                                       │
         │   52 │   │   logger.hr('Pull Repository Branch', 1)                              │
         │                                                                                  │
         │ ╭────────────────────────────── locals ───────────────────────────────╮          │
         │ │       branch = 'master'                                             │          │
         │ │ keep_changes = False                                                │          │
         │ │        proxy = None                                                 │          │
         │ │         repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'      │          │
         │ │         self = <deploy.git.GitManager object at 0x0000020A463CA0C8> │          │
         │ │       source = 'origin'                                             │          │
         │ │   ssl_verify = True                                                 │          │
         │ ╰─────────────────────────────────────────────────────────────────────╯          │
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\deploy\config.py:151 in execute                       │
         │                                                                                  │
         │   149 │   │   │   │   logger.info(f"[ failure ], error_code: {error_code}")      │
         │   150 │   │   │   │   self.show_error(command)                                   │
         │ ❱ 151 │   │   │   │   raise ExecutionError                                       │
         │   152 │   │   else:                                                              │
         │   153 │   │   │   logger.info(f"[ success ]")                                    │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │ allow_failure = False                                                        │ │
         │ │       command = '"E:/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.ex… │ │
         │ │                 fetch origin master'                                         │ │
         │ │    error_code = 128                                                          │ │
         │ │        output = True                                                         │ │
         │ │          self = <deploy.git.GitManager object at 0x0000020A463CA0C8>         │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         ╰──────────────────────────────────────────────────────────────────────────────────╯
         ExecutionError                                                                      

### 相关 Logs

```Text
ERROR    19:53:40.025 │ ExecutionError:                                                      
         ╭─────────────────────── Traceback (most recent call last) ────────────────────────╮
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\module\webui\process_manager.py:161 in run_process    │
         │                                                                                  │
         │   159 │   │   │   │   from module.daemon.uncensored import AzurLaneUncensored    │
         │   160 │   │   │   │                                                              │
         │ ❱ 161 │   │   │   │   AzurLaneUncensored(config=config_name, task="AzurLaneUncen │
         │   162 │   │   │   elif func == "Benchmark":                                      │
         │   163 │   │   │   │   from module.daemon.benchmark import Benchmark              │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │                  _ = ['--port', '22267']                                     │ │
         │ │               args = Namespace(electron=True)                                │ │
         │ │     AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'>           │ │
         │ │ AzurLaneUncensored = <class 'module.daemon.uncensored.AzurLaneUncensored'>   │ │
         │ │        config_name = 'alas'                                                  │ │
         │ │       console_hdlr = <RichHandler (NOTSET)>                                  │ │
         │ │                  e = ExecutionError()                                        │ │
         │ │               func = 'AzurLaneUncensored'                                    │ │
         │ │             parser = ArgumentParser(prog='gui.py', usage=None,               │ │
         │ │                      description=None, formatter_class=<class                │ │
         │ │                      'argparse.HelpFormatter'>, conflict_handler='error',    │ │
         │ │                      add_help=True)                                          │ │
         │ │                  q = <AutoProxy[Queue] object, typeid 'Queue' at             │ │
         │ │                      0x20a66e6fbc8>                                          │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │ E:\alas\AzurLaneAutoScript\module\daemon\uncensored.py:34 in run                 │
         │                                                                                  │
         │   32 │   │   │   branch='master',                                                │
         │   33 │   │   │   proxy=manager.config['GitProxy'],                               │
         │ ❱ 34 │   │   │   keep_changes=False                                              │
         │   35 │   │   )                                                                   │
         │   36                                                                             │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │  folder = './toolkit/AzurLaneUncensored'                                     │ │
         │ │ manager = <deploy.git.GitManager object at 0x0000020A463CA0C8>               │ │
         │ │    prev = 'E:\\alas\\AzurLaneAutoScript'                                     │ │
         │ │    repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'                    │ │
         │ │    self = <module.daemon.uncensored.AzurLaneUncensored object at             │ │
         │ │           0x0000020A66E8B448>                                                │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\deploy\git.py:50 in git_repository_init               │
         │                                                                                  │
         │   48 │   │                                                                       │
         │   49 │   │   logger.hr('Fetch Repository Branch', 1)                             │
         │ ❱ 50 │   │   self.execute(f'"{self.git}" fetch {source} {branch}')               │
         │   51 │   │                                                                       │
         │   52 │   │   logger.hr('Pull Repository Branch', 1)                              │
         │                                                                                  │
         │ ╭────────────────────────────── locals ───────────────────────────────╮          │
         │ │       branch = 'master'                                             │          │
         │ │ keep_changes = False                                                │          │
         │ │        proxy = None                                                 │          │
         │ │         repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'      │          │
         │ │         self = <deploy.git.GitManager object at 0x0000020A463CA0C8> │          │
         │ │       source = 'origin'                                             │          │
         │ │   ssl_verify = True                                                 │          │
         │ ╰─────────────────────────────────────────────────────────────────────╯          │
         │                                                                                  │
         │ E:\alas\AzurLaneAutoScript\deploy\config.py:151 in execute                       │
         │                                                                                  │
         │   149 │   │   │   │   logger.info(f"[ failure ], error_code: {error_code}")      │
         │   150 │   │   │   │   self.show_error(command)                                   │
         │ ❱ 151 │   │   │   │   raise ExecutionError                                       │
         │   152 │   │   else:                                                              │
         │   153 │   │   │   logger.info(f"[ success ]")                                    │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │ allow_failure = False                                                        │ │
         │ │       command = '"E:/alas/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.ex… │ │
         │ │                 fetch origin master'                                         │ │
         │ │    error_code = 128                                                          │ │
         │ │        output = True                                                         │ │
         │ │          self = <deploy.git.GitManager object at 0x0000020A463CA0C8>         │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         ╰──────────────────────────────────────────────────────────────────────────────────╯
         ExecutionError
```

**Comment by SaarChaffee** [comment]
反和谐仓库地址先暂时填下面两个中的随便一个，下载速度不能保证很快
`https://e.coding.net/llop18870/alas/AzurLaneUncensored.git`
`https://git.saarcenter.com/LmeSzinc/AzurLaneUncensored.git`

**Comment by wEuphorIA** [comment]
谢谢

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/bd83b765cec55542089e57e7e17c45315ac449ea 已经更换反和谐仓库，启动反和谐会自动修改。
