### ISSUE TITLE
无法正常启动Alas界面

### ISSUE THREAD

**Issue by futureprecd** [LmeSzinc/AzurLaneAutoScript#2432]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

应该是在更新游戏后，我点了一下反和谐，然后Alas就出现错误了，然后我关闭Alas，重新启动，现在Alas直接无法正常启动了

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
"C:\Users\HsiJia\Desktop\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in C:/Users/HsiJia/Desktop/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: [session-26457caa] The Repository has been blocked. see: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
fatal: unable to access 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror/': The requested URL returned error: 403
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default

Last command: "C:/Users/HsiJia/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help
```

**Comment by Jzzzzth** [comment]
"C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"C:/Users/Tianhao/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: [session-a34f7682] The Repository has been blocked. see: https://gitee.com/lmeszinc/azur-lane-auto-script-mirrorfatal: unable to access 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror/': The requested URL returned error: 403
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Theme: dark
Rest of the configs are the same as default

Last command: "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help

**Comment by HS7097** [comment]
反和谐失败
═════════════════════════════════════════════════════════════════════════════════════════════
                                        UPDATE FAILED                                        
═════════════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════ SHOW DEPLOY CONFIG ═════════════════════════════════════
INFO     16:20:14.016 │ SHOW DEPLOY CONFIG                                                   
INFO     16:20:14.017 │ Repository:                                                          
         https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git                          
INFO     16:20:14.017 │ GitExecutable: F:\AlasApp_0.3.7\toolkit\Git\mingw64\bin\git.exe      
INFO     16:20:14.018 │ KeepLocalChanges: True                                               
INFO     16:20:14.019 │ PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple                 
INFO     16:20:14.020 │ AdbExecutable:                                                       
         F:\AlasApp_0.3.7\toolkit\Lib\site-packages\adbutils\binaries\adb.exe                
INFO     16:20:14.021 │ Language: zh-CN                                                      
INFO     16:20:14.022 │ Theme: dark                                                          
INFO     16:20:14.022 │ Run: maa2 , maa1 , alas                                              
INFO     16:20:14.023 │ Rest of the configs are the same as default                          
INFO     16:20:14.024 │                                                                      
INFO     16:20:14.025 │ Last command: "F:/AlasApp_0.3.7/toolkit/Git/mingw64/bin/git.exe"     
         fetch origin master                                                                 
INFO     16:20:14.026 │ Please check your deploy settings in config/deploy.yaml and re-open  
         Alas.exe                                                                            
INFO     16:20:14.026 │ Take the screenshot of entire window if you need help                
ERROR    16:20:14.027 │ ExecutionError:                                                      
         ╭─────────────────────── Traceback (most recent call last) ────────────────────────╮
         │                                                                                  │
         │ F:\AlasApp_0.3.7\module\webui\process_manager.py:161 in run_process              │
         │                                                                                  │
         │   159 │   │   │   │   from module.daemon.uncensored import AzurLaneUncensored    │
         │   160 │   │   │   │                                                              │
         │ ❱ 161 │   │   │   │   AzurLaneUncensored(config=config_name, task="AzurLaneUncen │
         │   162 │   │   │   elif func == "Benchmark":                                      │
         │   163 │   │   │   │   from module.daemon.benchmark import Benchmark              │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │                  _ = ['--port', '22267']                                     │ │
         │ │               args = Namespace(electron=True)                                │ │
         │ │     AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'>           │ │
         │ │ AzurLaneUncensored = <class 'module.daemon.uncensored.AzurLaneUncensored'>   │ │
         │ │        config_name = 'alas'                                                  │ │
         │ │       console_hdlr = <RichHandler (NOTSET)>                                  │ │
         │ │                  e = ExecutionError()                                        │ │
         │ │               func = 'AzurLaneUncensored'                                    │ │
         │ │             parser = ArgumentParser(prog='gui.py', usage=None,               │ │
         │ │                      description=None, formatter_class=<class                │ │
         │ │                      'argparse.HelpFormatter'>, conflict_handler='error',    │ │
         │ │                      add_help=True)                                          │ │
         │ │                  q = <AutoProxy[Queue] object, typeid 'Queue' at             │ │
         │ │                      0x240efa7d9c8>                                          │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │ F:\AlasApp_0.3.7\module\daemon\uncensored.py:34 in run                           │
         │                                                                                  │
         │   32 │   │   │   branch='master',                                                │
         │   33 │   │   │   proxy=manager.config['GitProxy'],                               │
         │ ❱ 34 │   │   │   keep_changes=False                                              │
         │   35 │   │   )                                                                   │
         │   36                                                                             │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │  folder = './toolkit/AzurLaneUncensored'                                     │ │
         │ │ manager = <deploy.git.GitManager object at 0x000002409EE77408>               │ │
         │ │    prev = 'F:\\AlasApp_0.3.7'                                                │ │
         │ │    repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'                    │ │
         │ │    self = <module.daemon.uncensored.AzurLaneUncensored object at             │ │
         │ │           0x00000240EEACDF48>                                                │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         │                                                                                  │
         │ F:\AlasApp_0.3.7\deploy\git.py:50 in git_repository_init                         │
         │                                                                                  │
         │   48 │   │                                                                       │
         │   49 │   │   logger.hr('Fetch Repository Branch', 1)                             │
         │ ❱ 50 │   │   self.execute(f'"{self.git}" fetch {source} {branch}')               │
         │   51 │   │                                                                       │
         │   52 │   │   logger.hr('Pull Repository Branch', 1)                              │
         │                                                                                  │
         │ ╭────────────────────────────── locals ───────────────────────────────╮          │
         │ │       branch = 'master'                                             │          │
         │ │ keep_changes = False                                                │          │
         │ │        proxy = None                                                 │          │
         │ │         repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'      │          │
         │ │         self = <deploy.git.GitManager object at 0x000002409EE77408> │          │
         │ │       source = 'origin'                                             │          │
         │ │   ssl_verify = True                                                 │          │
         │ ╰─────────────────────────────────────────────────────────────────────╯          │
         │                                                                                  │
         │ F:\AlasApp_0.3.7\deploy\config.py:151 in execute                                 │
         │                                                                                  │
         │   149 │   │   │   │   logger.info(f"[ failure ], error_code: {error_code}")      │
         │   150 │   │   │   │   self.show_error(command)                                   │
         │ ❱ 151 │   │   │   │   raise ExecutionError                                       │
         │   152 │   │   else:                                                              │
         │   153 │   │   │   logger.info(f"[ success ]")                                    │
         │                                                                                  │
         │ ╭─────────────────────────────────── locals ───────────────────────────────────╮ │
         │ │ allow_failure = False                                                        │ │
         │ │       command = '"F:/AlasApp_0.3.7/toolkit/Git/mingw64/bin/git.exe" fetch    │ │
         │ │                 origin master'                                               │ │
         │ │    error_code = 128                                                          │ │
         │ │        output = True                                                         │ │
         │ │          self = <deploy.git.GitManager object at 0x000002409EE77408>         │ │
         │ ╰──────────────────────────────────────────────────────────────────────────────╯ │
         ╰──────────────────────────────────────────────────────────────────────────────────╯
         ExecutionError

**Comment by illyaaaa** [comment]
@futureprecd @Jzzzzth 
> fatal: unable to access 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror/

https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2412#issuecomment-1486576012

@HS7097 
> folder = './toolkit/AzurLaneUncensored' │ │
│ │ manager = <deploy.git.GitManager object at 0x000002409EE77408> │ │
│ │ prev = 'F:\AlasApp_0.3.7' │ │
│ │ repo = 'https://gitee.com/LmeSzinc/AzurLaneUncensored' │ │

https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2426#issuecomment-1490483334

**Comment by BuchuanZhao** [comment]
阅读安装文档，打开config/deploy.yaml，按照如下修改即可：
Repository: 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git'

**Comment by BuchuanZhao** [comment]
> "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy [ allowed failure ], error_code: 5 "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true [ success ] ==================== SET GIT REPOSITORY ==================== "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://gitee.com/lmeszinc/azur-lane-auto-script-mirror [ success ] ==================== FETCH REPOSITORY BRANCH ==================== "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master remote: [session-a34f7682] The Repository has been blocked. see: https://gitee.com/lmeszinc/azur-lane-auto-script-mirrorfatal: unable to access 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror/': The requested URL returned error: 403 [ failure ], error_code: 128 +-----------------------------------------------------+ | UPDATE FAILED | +-----------------------------------------------------+ ==================== SHOW DEPLOY CONFIG ==================== Repository: https://gitee.com/lmeszinc/azur-lane-auto-script-mirror PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple Language: zh-CN Theme: dark Rest of the configs are the same as default
> 
> Last command: "C:/Users/XX/Desktop/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master Please check your deploy settings in config/deploy.yaml and re-open Alas.exe Take the screenshot of entire window if you need help

阅读安装文档，打开config/deploy.yaml，按照如下修改即可：
Repository: 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git'

**Comment by jack-chenkerui** [comment]
@illyaaaa 大佬你好，您发的链接已经失效，能不能再发一个。我也遇到了该问题，我是三天前使用的反和谐，但是前两天可以正常使用，今天不能启动。

**Comment by CKR530** [comment]
已解决，不好意思大佬，翻了其他回答找到解决方法：找到console.bat 输入 python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git 回车
