### ISSUE TITLE
minitouch download失败

### ISSUE THREAD

**Issue by gimfia** [LmeSzinc/AzurLaneAutoScript#2445]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

minitouch download失败

### 如何复现

启动alas.exe

### 预期行为

正常启动

### 相关 Logs

```Text
[D 230402 11:01:30 init:62] Download https://github.com/openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/x86_64/bin/minitouch
[W 230402 11:01:51 api:40] HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /openatx/stf-binaries/raw/0.3.0/node_modules/@devicefarmer/minitouch-prebuilt/prebuilt/x86_64/bin/minitouch (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000295989EB288>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')), retrying in 0 seconds...
```

### 截图

![image](https://user-images.githubusercontent.com/54408388/229328878-09ac1dfb-25ca-4267-a7e0-bdf48500a08f.png)
![image](https://user-images.githubusercontent.com/54408388/229328888-4b79babe-798b-40b4-a203-a4c30250f2dd.png)

**Comment by LmeSzinc** [comment]
[cache.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11134646/cache.zip)

将这个文件解压到 `C:\Users\LmeSzinc\.uiautomator2\cache`，`LmeSzinc` 替换成你电脑的用户名，像这样：

![image](https://user-images.githubusercontent.com/37934724/229410102-e463f6c0-b3cc-4874-bc7f-971502afccbd.png)

**Comment by fengliCN** [comment]
路过，很好的建议，一下子就流畅了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/releases/tag/v2023.04.19
