### ISSUE TITLE
【偶发】大世界隐秘海域，进入后有个领航员提示，没有跳过，最后超时wait too long

### ISSUE THREAD

**Issue by cloudchina** [LmeSzinc/AzurLaneAutoScript#2449]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

RT，大世界开荒完成了，现在就是进入某些隐秘海域时，有领航员提示，没有点击跳过，然后空域搜索，就一直等待，最后超时，日志记录wait too long

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

> ═════════════════════════════ OS CLEAR OBSCURE ══════════════════════════════
INFO     21:49:49.265 │ OS CLEAR OBSCURE                                     
INFO     21:49:49.266 │ <<< OS GET NEXT OBSCURE >>>                          
INFO     21:49:49.267 │ Storage enter                                        
INFO     21:49:49.276 │ Click ( 850,  671) @ STORAGE_ENTER                   
INFO     21:49:50.376 │ <<< STORAGE CHECKOUT ITEM OBSCURE >>>                
INFO     21:49:50.420 │ [Storage_OBSCURE] 1                                  
INFO     21:49:50.423 │ Click ( 202,  164) @ TEMPLATE_STORAGE_OBSCURE        
INFO     21:49:50.998 │ Click ( 579,  510) @ STORAGE_COORDINATE_CHECKOUT     
INFO     21:49:54.032 │ Already selected at OBSCURE                          
INFO     21:49:54.051 │ Click ( 474,  286) @ ZONE_ENTRANCE                   
INFO     21:49:54.755 │ [Amount_ocr 0.114s] [1343, 30, 0, 0]                 
INFO     21:49:54.810 │ [ACTION_POINT_REMAIN 0.051s] 2                       
INFO     21:49:54.814 │ Action points: 2(602), oil: 1343                     
INFO     21:49:54.819 │ Click ( 830,  568) @ ACTION_POINT_USE                
INFO     21:49:55.511 │ [Amount_ocr 0.115s] [1343, 29, 0, 0]                 
INFO     21:49:55.557 │ [ACTION_POINT_REMAIN 0.043s] 22                      
INFO     21:49:55.560 │ Action points: 22(602), oil: 1343                    
INFO     21:49:55.568 │ Click ( 781,  564) @ ACTION_POINT_USE                
INFO     21:49:56.223 │ [Amount_ocr 0.108s] [1343, 28, 0, 0]                 
INFO     21:49:56.275 │ [ACTION_POINT_REMAIN 0.048s] 42                      
INFO     21:49:56.278 │ Action points: 42(602), oil: 1343                    
INFO     21:49:56.281 │ Having enough action points                          
INFO     21:49:56.284 │ <<< UI CLICK >>>                                     
INFO     21:49:56.308 │ Click ( 430,  548) @ ACTION_POINT_CANCEL             
INFO     21:49:57.178 │ Click ( 487,  286) @ ZONE_ENTRANCE                   
INFO     21:49:58.937 │ <<< ZONE INIT >>>                                    
INFO     21:49:58.940 │ Get zone name                                        
INFO     21:49:59.050 │ [MAP_NAME 0.091s] NA海域深处H-隐秘海域               
INFO     21:49:59.054 │ Map name processed: NA海域深处H                      
INFO     21:49:59.057 │ [Zone] [159|NA Ocean Depths H]                       
INFO     21:49:59.060 │ <<< FLEET SET TO 1 >>>                               
INFO     21:49:59.094 │ It is fleet 1 already                                
INFO     21:49:59.097 │ <<< ORDER_SCAN >>>                                   
INFO     21:49:59.101 │ Order enter                                          
INFO     21:49:59.123 │ Click (1025,  178) @ ORDER_ENTER                     
WARNING  21:50:59.258 │ Wait too long                                        
WARNING  21:50:59.259 │ Waiting for {'ORDER_CHECK', 'MAP_GOTO_GLOBE_FOG',    
         'AUTO_SEARCH_REWARD', 'IN_MAP', 'ORDER_ENTER'}                      
INFO     21:50:59.291 │ [Package_name] com.bilibili.azurlane                 
ERROR    21:50:59.292 │ GameStuckError: Wait too long                        
WARNING  21:50:59.293 │ Saving error: ./log/error/1680529859293              
WARNING  21:50:59.601 │ Game stuck, com.bilibili.azurlane will be restarted  
         in 10 seconds                                                       
WARNING  21:50:59.603 │ If you are playing by hand, please stop Alas         
INFO     21:50:59.604 │ Task call: Restart                                   
INFO     21:50:59.622 │ Bind task {'General', 'Alas', 'OpsiObscure',         
         'OpsiGeneral'}                                                      
INFO     21:50:59.624 │ Save config ./config\alas.json,                      
         Restart.Scheduler.NextRun=datetime.datetime(2023, 4, 3, 21, 50, 59),
         Restart.Scheduler.Enable=True                                       
INFO     21:51:09.634 │ Scheduler: End task `OpsiObscure`                    
CRITICAL 21:51:09.635 │ Task `OpsiObscure` failed 3 or more times.           
CRITICAL 21:51:09.637 │ Possible reason #1: You haven't used it correctly.   
         Please read the help text of the options.                           
CRITICAL 21:51:09.639 │ Possible reason #2: There is a problem with this     
         task. Please contact developers or try to fix it yourself.          
CRITICAL 21:51:09.640 │ Request human takeover                               
INFO     21:51:09.641 │ No provider specified, skip sending                  
═════════════════════════════════════════════════════════════════════════════
                                    START                                    
═════════════════════════════════════════════════════════════════════════════
INFO     21:54:36.897 │ Start scheduler loop: alas                           
INFO     21:54:36.900 │ [Server] cn                                          
INFO     21:54:36.933 │ Bind task {'Alas', 'General'}                        
INFO     21:54:37.065 │ Server "秋季旅行" is available.                      
INFO     21:54:37.070 │ Pending tasks: ['Restart', 'OpsiObscure']            
INFO     21:54:37.072 │ [Task] Restart (Enable, 2023-04-03 21:50:59)         
INFO     21:54:37.075 │ Bind task {'Restart', 'Alas', 'General'}   

_No response_

### 截图

![image](https://user-images.githubusercontent.com/96337073/229531038-d9db0989-0af4-4dc1-9c0f-3ed8593cb357.png)

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
![image](https://user-images.githubusercontent.com/37934724/229538259-806fa19b-2b46-476c-9f3c-f40e7a70a397.png)

**Comment by cloudchina** [comment]
我后续再观察试一下，主要是这个也是偶发情况，开荒完成后接近20个隐秘海域，卡了三次

**Comment by LmeSzinc** [comment]
你需要回答是否按照要求修改了游戏设置，这个通常是 TB 引导没关
