### ISSUE TITLE
退役模式选择强化，会出现不强化直接点击返回键后反复点击同一点

### ISSUE THREAD

**Issue by NAnaLko** [LmeSzinc/AzurLaneAutoScript#2453]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我搜索了现有的issues但是没有发现有人和我有同样的问题，所以尝试了一下是不是偶发的bug，但是重启了alas问题还是存在。
请问是设置错了吗还是有别的问题。辛苦啦

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
────────────────────────────────────── 12-4 ───────────────────────────────────────
INFO     15:14:18.920 │ 12-4                                                       
INFO     15:14:18.921 │ Expect emotion reduce: (12, 2)                             
INFO     15:14:18.932 │ Bind task {'General', 'Alas', 'Main2'}                     
INFO     15:14:18.933 │ Save config ./config\alas.json,                            
         Main2.Emotion.Fleet1Value=103,                                            
         Main2.Emotion.Fleet1Record=datetime.datetime(2023, 4, 4, 15, 14, 18),     
         Main2.Emotion.Fleet2Value=119,                                            
         Main2.Emotion.Fleet2Record=datetime.datetime(2023, 4, 4, 15, 14, 18)      
INFO     15:14:18.940 │ [Emotion fleet_1] 103                                      
INFO     15:14:18.942 │ [Emotion fleet_2] 119                                      
INFO     15:14:18.942 │ <<< ENTER MAP >>>                                          
INFO     15:14:18.969 │ Click ( 908,  553) @ 12-4                                  
INFO     15:14:19.385 │ [Map_clear_percentage] 0.18895348837209303                 
INFO     15:14:19.730 │ [Map_clear_percentage] 0.8255813953488372                  
INFO     15:14:20.029 │ [Map_clear_percentage] 0.997093023255814                   
INFO     15:14:20.031 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     15:14:20.032 │ [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 
         3_stars, threat_safe, clear_mode                                          
INFO     15:14:20.033 │ [StopCondition_MapAchievement] non_stop                    
INFO     15:14:20.034 │ [Fast_Forward] off                                         
INFO     15:14:20.046 │ No auto search option.                                     
INFO     15:14:20.047 │ Click ( 929,  526) @ MAP_PREPARATION                       
INFO     15:14:20.286 │ Click ( 848,  504) @ RETIRE_APPEAR_3                       
INFO     15:14:22.264 │ <<< ENHANCEMENT BY TYPE >>>                                
INFO     15:14:22.266 │ [Enhance Order] [None]                                     
INFO     15:14:22.267 │ Favourite=False, Ship Type=None                            
INFO     15:14:22.267 │ <<< UI CLICK >>>                                           
INFO     15:14:22.276 │ Click (1135,   31) @ DOCK_FILTER                           
INFO     15:14:22.918 │ Setting DOCK options,                                      
INFO     15:14:22.926 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/enhanceable                                                         
INFO     15:14:22.934 │ Click ( 321,  495) @ FILTER_EXTRA_0_0                      
INFO     15:14:23.172 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     15:14:23.180 │ Setting DOCK options, sort='level', index='all',           
         faction='all', rarity='all', extra='enhanceable'                          
INFO     15:14:23.188 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     15:14:23.195 │ Click ( 726,  490) @ FILTER_EXTRA_3_0                      
INFO     15:14:23.506 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/enhanceable                                                         
INFO     15:14:23.513 │ <<< UI CLICK >>>                                           
INFO     15:14:23.516 │ Click ( 789,  640) @ DOCK_FILTER_CONFIRM                   
INFO     15:14:25.078 │ equip_enter DOCK_CHECK -> BACK_ARROW                       
INFO     15:14:25.079 │ Click (  61,   53) @ BACK_ARROW                            
INFO     15:14:25.314 │ Click ( 179,  172) @ CARD_0_0                              
INFO     15:14:35.386 │ Click ( 171,  212) @ CARD_0_0                              
INFO     15:14:45.503 │ Click ( 163,  125) @ CARD_0_0                              
INFO     15:14:55.748 │ Click ( 184,  211) @ CARD_0_0                              
INFO     15:15:06.048 │ Click ( 128,  173) @ CARD_0_0                              
INFO     15:15:16.286 │ Click ( 170,  155) @ CARD_0_0                              
INFO     15:15:26.467 │ Click ( 187,  127) @ CARD_0_0
```

**Comment by zeroxsama** [comment]
一样遇到了  设备是 星界链  其他设备不清楚
观察了下  他在切换完 强化分类  船的载入有明显卡顿
不清楚是不是这个卡顿 导致的  希望早点得到修复

**Comment by HS7097** [comment]
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                     MAIN                                                      
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════ CAMPAIGN_7_2 ═════════════════════════════════════════════════
INFO     19:28:27.381 │ CAMPAIGN_7_2                                                                           
INFO     19:28:27.382 │ Count: 0                                                                               
INFO     19:28:27.392 │ <<< UI ENSURE >>>                                                                      
INFO     19:28:27.394 │ UI get current page                                                                    
INFO     19:28:27.400 │ [UI] page_main                                                                         
INFO     19:28:27.401 │ Goto page_campaign                                                                     
INFO     19:28:27.403 │ <<< UI GOTO PAGE_CAMPAIGN >>>                                                          
INFO     19:28:27.509 │ Page switch: page_main -> page_campaign_menu                                           
INFO     19:28:27.511 │ Click (1110,  371) @ MAIN_GOTO_CAMPAIGN                                                
INFO     19:28:28.017 │ Page switch: page_campaign_menu -> page_campaign                                       
INFO     19:28:28.019 │ Click ( 328,  356) @ CAMPAIGN_MENU_GOTO_CAMPAIGN                                       
INFO     19:28:28.311 │ Page arrive: page_campaign                                                             
INFO     19:28:28.339 │ [Mode_switch_1] hard                                                                   
INFO     19:28:28.341 │ <<< UI ENSURE INDEX >>>                                                                
INFO     19:28:28.375 │ No stage found.                                                                        
INFO     19:28:28.637 │ No stage found.                                                                        
INFO     19:28:28.938 │ No stage found.                                                                        
INFO     19:28:29.280 │ Loading OCR model: ./bin/cnocr_models/azur_lane                                        
INFO     19:28:29.379 │ [campaign 0.133s] ['7-2', '7-1', '7-3']                                                
INFO     19:28:29.381 │ [Chapter] 7                                                                            
INFO     19:28:29.382 │ [Stage] 7-2, 7-1, 7-3                                                                  
INFO     19:28:29.383 │ [Index] 7                                                                              
INFO     19:28:29.429 │ [OCR_OIL 0.035s] 24533                                                                 
───────────────────────────────────────────────────── 7-2 ─────────────────────────────────────────────────────
INFO     19:28:29.431 │ 7-2                                                                                    
INFO     19:28:29.433 │ Expect emotion reduce: (10, 2)                                                         
INFO     19:28:29.446 │ Bind task {'General', 'Alas', 'Main'}                                                  
INFO     19:28:29.447 │ Save config ./config\AlasR.json, Main.Emotion.Fleet1Value=150,                         
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 4, 4, 19, 28, 29), Main.Emotion.Fleet2Value=119,    
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 4, 4, 19, 28, 29)                                   
INFO     19:28:29.454 │ [Emotion fleet_1] 150                                                                  
INFO     19:28:29.455 │ [Emotion fleet_2] 119                                                                  
INFO     19:28:29.456 │ <<< ENTER MAP >>>                                                                      
INFO     19:28:29.485 │ Click ( 440,  219) @ 7-2                                                               
INFO     19:28:29.918 │ [Map_clear_percentage] 0.125                                                           
INFO     19:28:30.209 │ [Map_clear_percentage] 0.7296511627906976                                              
INFO     19:28:30.577 │ [Map_clear_percentage] 0.997093023255814                                               
INFO     19:28:30.580 │ [MAP_CLEAR_ALL_THIS_TIME] False                                                        
INFO     19:28:30.581 │ [Map_info] 99%, star_1, star_2, 100_percent_clear, threat_safe, clear_mode             
INFO     19:28:30.582 │ [StopCondition_MapAchievement] non_stop                                                
INFO     19:28:30.584 │ [Fast_Forward] on                                                                      
INFO     19:28:30.596 │ [Auto_Search] off                                                                      
INFO     19:28:30.598 │ Click ( 894,  533) @ MAP_PREPARATION                                                   
INFO     19:28:30.818 │ Click ( 844,  514) @ RETIRE_APPEAR_3                                                   
INFO     19:28:32.672 │ <<< ENHANCEMENT BY TYPE >>>                                                            
INFO     19:28:32.673 │ [Enhance Order] [None]                                                                 
INFO     19:28:32.674 │ Favourite=True, Ship Type=None                                                         
INFO     19:28:32.677 │ [Favourite_filter] off                                                                 
INFO     19:28:32.677 │ Click ( 706,   23) @ COMMON_SHIP_FILTER_DISABLE                                        
INFO     19:28:32.972 │ [Favourite_filter] unknown                                                             
INFO     19:28:33.283 │ [Favourite_filter] on                                                                  
INFO     19:28:34.466 │ <<< UI CLICK >>>                                                                       
INFO     19:28:34.479 │ Click (1152,   19) @ DOCK_FILTER                                                       
INFO     19:28:35.055 │ Setting DOCK options,                                                                  
INFO     19:28:35.064 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable               
INFO     19:28:35.071 │ Click ( 310,  479) @ FILTER_EXTRA_0_0                                                  
INFO     19:28:35.340 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit                  
INFO     19:28:35.348 │ Setting DOCK options, sort='level', index='all', faction='all', rarity='all',          
         extra='enhanceable'                                                                                   
INFO     19:28:35.357 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit                  
INFO     19:28:35.365 │ Click ( 743,  480) @ FILTER_EXTRA_3_0                                                  
INFO     19:28:35.662 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable               
INFO     19:28:35.670 │ <<< UI CLICK >>>                                                                       
INFO     19:28:35.673 │ Click ( 774,  645) @ DOCK_FILTER_CONFIRM                                               
INFO     19:28:37.285 │ equip_enter DOCK_CHECK -> BACK_ARROW                                                   
INFO     19:28:37.287 │ Click (  50,   48) @ BACK_ARROW                                                        
INFO     19:28:37.565 │ Click ( 189,  187) @ CARD_0_0                                                          
INFO     19:28:47.784 │ Click ( 187,  178) @ CARD_0_0                                                          
INFO     19:28:58.012 │ Click ( 161,  137) @ CARD_0_0                                                          
INFO     19:29:08.232 │ Click ( 178,  161) @ CARD_0_0                                                          
=================================
7-2若船坞已满，进入战斗后会提示强化，但Alas并不会选择强化而是返回地图

**Comment by HS7097** [comment]
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                     MAIN                                                      
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════ CAMPAIGN_7_2 ═════════════════════════════════════════════════
INFO     19:28:27.381 │ CAMPAIGN_7_2                                                                           
INFO     19:28:27.382 │ Count: 0                                                                               
INFO     19:28:27.392 │ <<< UI ENSURE >>>                                                                      
INFO     19:28:27.394 │ UI get current page                                                                    
INFO     19:28:27.400 │ [UI] page_main                                                                         
INFO     19:28:27.401 │ Goto page_campaign                                                                     
INFO     19:28:27.403 │ <<< UI GOTO PAGE_CAMPAIGN >>>                                                          
INFO     19:28:27.509 │ Page switch: page_main -> page_campaign_menu                                           
INFO     19:28:27.511 │ Click (1110,  371) @ MAIN_GOTO_CAMPAIGN                                                
INFO     19:28:28.017 │ Page switch: page_campaign_menu -> page_campaign                                       
INFO     19:28:28.019 │ Click ( 328,  356) @ CAMPAIGN_MENU_GOTO_CAMPAIGN                                       
INFO     19:28:28.311 │ Page arrive: page_campaign                                                             
INFO     19:28:28.339 │ [Mode_switch_1] hard                                                                   
INFO     19:28:28.341 │ <<< UI ENSURE INDEX >>>                                                                
INFO     19:28:28.375 │ No stage found.                                                                        
INFO     19:28:28.637 │ No stage found.                                                                        
INFO     19:28:28.938 │ No stage found.                                                                        
INFO     19:28:29.280 │ Loading OCR model: ./bin/cnocr_models/azur_lane                                        
INFO     19:28:29.379 │ [campaign 0.133s] ['7-2', '7-1', '7-3']                                                
INFO     19:28:29.381 │ [Chapter] 7                                                                            
INFO     19:28:29.382 │ [Stage] 7-2, 7-1, 7-3                                                                  
INFO     19:28:29.383 │ [Index] 7                                                                              
INFO     19:28:29.429 │ [OCR_OIL 0.035s] 24533                                                                 
───────────────────────────────────────────────────── 7-2 ─────────────────────────────────────────────────────
INFO     19:28:29.431 │ 7-2                                                                                    
INFO     19:28:29.433 │ Expect emotion reduce: (10, 2)                                                         
INFO     19:28:29.446 │ Bind task {'General', 'Alas', 'Main'}                                                  
INFO     19:28:29.447 │ Save config ./config\AlasR.json, Main.Emotion.Fleet1Value=150,                         
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 4, 4, 19, 28, 29), Main.Emotion.Fleet2Value=119,    
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 4, 4, 19, 28, 29)                                   
INFO     19:28:29.454 │ [Emotion fleet_1] 150                                                                  
INFO     19:28:29.455 │ [Emotion fleet_2] 119                                                                  
INFO     19:28:29.456 │ <<< ENTER MAP >>>                                                                      
INFO     19:28:29.485 │ Click ( 440,  219) @ 7-2                                                               
INFO     19:28:29.918 │ [Map_clear_percentage] 0.125                                                           
INFO     19:28:30.209 │ [Map_clear_percentage] 0.7296511627906976                                              
INFO     19:28:30.577 │ [Map_clear_percentage] 0.997093023255814                                               
INFO     19:28:30.580 │ [MAP_CLEAR_ALL_THIS_TIME] False                                                        
INFO     19:28:30.581 │ [Map_info] 99%, star_1, star_2, 100_percent_clear, threat_safe, clear_mode             
INFO     19:28:30.582 │ [StopCondition_MapAchievement] non_stop                                                
INFO     19:28:30.584 │ [Fast_Forward] on                                                                      
INFO     19:28:30.596 │ [Auto_Search] off                                                                      
INFO     19:28:30.598 │ Click ( 894,  533) @ MAP_PREPARATION                                                   
INFO     19:28:30.818 │ Click ( 844,  514) @ RETIRE_APPEAR_3                                                   
INFO     19:28:32.672 │ <<< ENHANCEMENT BY TYPE >>>                                                            
INFO     19:28:32.673 │ [Enhance Order] [None]                                                                 
INFO     19:28:32.674 │ Favourite=True, Ship Type=None                                                         
INFO     19:28:32.677 │ [Favourite_filter] off                                                                 
INFO     19:28:32.677 │ Click ( 706,   23) @ COMMON_SHIP_FILTER_DISABLE                                        
INFO     19:28:32.972 │ [Favourite_filter] unknown                                                             
INFO     19:28:33.283 │ [Favourite_filter] on                                                                  
INFO     19:28:34.466 │ <<< UI CLICK >>>                                                                       
INFO     19:28:34.479 │ Click (1152,   19) @ DOCK_FILTER                                                       
INFO     19:28:35.055 │ Setting DOCK options,                                                                  
INFO     19:28:35.064 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable               
INFO     19:28:35.071 │ Click ( 310,  479) @ FILTER_EXTRA_0_0                                                  
INFO     19:28:35.340 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit                  
INFO     19:28:35.348 │ Setting DOCK options, sort='level', index='all', faction='all', rarity='all',          
         extra='enhanceable'                                                                                   
INFO     19:28:35.357 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit                  
INFO     19:28:35.365 │ Click ( 743,  480) @ FILTER_EXTRA_3_0                                                  
INFO     19:28:35.662 │ [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable               
INFO     19:28:35.670 │ <<< UI CLICK >>>                                                                       
INFO     19:28:35.673 │ Click ( 774,  645) @ DOCK_FILTER_CONFIRM                                               
INFO     19:28:37.285 │ equip_enter DOCK_CHECK -> BACK_ARROW                                                   
INFO     19:28:37.287 │ Click (  50,   48) @ BACK_ARROW                                                        
INFO     19:28:37.565 │ Click ( 189,  187) @ CARD_0_0                                                          
INFO     19:28:47.784 │ Click ( 187,  178) @ CARD_0_0                                                          
INFO     19:28:58.012 │ Click ( 161,  137) @ CARD_0_0                                                          
INFO     19:29:08.232 │ Click ( 178,  161) @ CARD_0_0                                                          
------------
7-2也遇到了

**Comment by subB1ss** [comment]
同样遇到了
INFO     20:11:57.023 │ <<< ENTER MAP >>>                                          
INFO     20:11:57.053 │ Click ( 872,  474) @ 11-4                                  
INFO     20:11:57.929 │ [Map_clear_percentage] 0.4331395348837209                  
INFO     20:11:58.280 │ [Map_clear_percentage] 0.997093023255814                   
INFO     20:11:58.282 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     20:11:58.283 │ [Map_info] 99%, star_1, star_2, 100_percent_clear,         
         threat_safe, clear_mode                                                   
INFO     20:11:58.283 │ [StopCondition_MapAchievement] non_stop                    
INFO     20:11:58.284 │ [Fast_Forward] on                                          
INFO     20:11:58.291 │ [Auto_Search] on                                           
INFO     20:11:58.292 │ Click ( 985,  518) @ MAP_PREPARATION                       
INFO     20:11:58.858 │ Click ( 854,  514) @ RETIRE_APPEAR_3                       
INFO     20:12:01.265 │ <<< ENHANCEMENT BY TYPE >>>                                
INFO     20:12:01.267 │ [Enhance Order] [None]                                     
INFO     20:12:01.267 │ Favourite=False, Ship Type=None                            
INFO     20:12:01.268 │ <<< UI CLICK >>>                                           
INFO     20:12:01.276 │ Click (1143,   28) @ DOCK_FILTER                           
INFO     20:12:01.822 │ Setting DOCK options,                                      
INFO     20:12:01.828 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     20:12:01.834 │ Setting DOCK options, sort='level', index='all',           
         faction='all', rarity='all', extra='enhanceable'                          
INFO     20:12:01.839 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     20:12:01.845 │ Click ( 707,  484) @ FILTER_EXTRA_3_0                      
INFO     20:12:02.153 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/enhanceable                                                         
INFO     20:12:02.159 │ <<< UI CLICK >>>                                           
INFO     20:12:02.161 │ Click ( 794,  621) @ DOCK_FILTER_CONFIRM                   
INFO     20:12:04.286 │ equip_enter DOCK_CHECK -> BACK_ARROW                       
INFO     20:12:04.287 │ Click (  60,   57) @ BACK_ARROW                            
INFO     20:12:04.555 │ Click ( 182,  216) @ CARD_0_0                              
INFO     20:12:14.799 │ Click ( 157,  164) @ CARD_0_0                              
INFO     20:12:24.904 │ Click ( 129,  189) @ CARD_0_0                              
INFO     20:12:34.963 │ Click ( 178,  176) @ CARD_0_0                              
INFO     20:12:45.147 │ Click ( 173,  158) @ CARD_0_0                              
INFO     20:12:55.301 │ Click ( 144,  179) @ CARD_0_0                              
INFO     20:13:05.539 │ Click ( 125,  167) @ CARD_0_0                              
INFO     20:13:15.782 │ Click ( 147,  163) @ CARD_0_0                              
INFO     20:13:26.015 │ Click ( 164,  221) @ CARD_0_0                              
INFO     20:13:36.310 │ Click ( 147,  140) @ CARD_0_0                              
INFO     20:13:46.533 │ Click ( 185,  146) @ CARD_0_0                              
INFO     20:13:56.650 │ Click ( 142,  142) @ CARD_0_0                              
INFO     20:14:06.898 │ Click ( 200,  185) @ CARD_0_0                              
INFO     20:14:17.294 │ Click ( 160,  194) @ CARD_0_0

**Comment by cswhrdf** [comment]
遇到相同问题后想用半自动点击完成强化操作，但是半自动点击也没有进行强化操作
>2023-04-04 21:17:21.792 | INFO | v 1
2023-04-04 21:17:21.795 | INFO | ^ 10 720 1280 0
2023-04-04 21:17:21.798 | INFO | $ 3431
2023-04-04 21:17:21.800 | INFO | minitouch running on port: 20357, pid: 3431
2023-04-04 21:17:21.802 | INFO | max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0
2023-04-04 21:17:24.175 | INFO | Setting DOCK options,
2023-04-04 21:17:24.185 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable
2023-04-04 21:17:24.195 | INFO | Click ( 256,  492) @ FILTER_EXTRA_0_0
2023-04-04 21:17:24.985 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable
2023-04-04 21:17:25.693 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit
2023-04-04 21:17:25.704 | INFO | Setting DOCK options, sort='level', index='all', faction='all', rarity='all',
extra='enhanceable'
2023-04-04 21:17:25.714 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit
2023-04-04 21:17:25.725 | INFO | Click ( 715,  502) @ FILTER_EXTRA_3_0
2023-04-04 21:17:26.503 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/no_limit
2023-04-04 21:17:27.249 | INFO | [DOCK] sort/level, index/all, faction/all, rarity/all, extra/enhanceable
2023-04-04 21:17:27.260 | INFO | <<< UI CLICK >>>
2023-04-04 21:17:27.265 | INFO | Click ( 846,  654) @ DOCK_FILTER_CONFIRM
2023-04-04 21:17:32.583 | INFO | equip_enter DOCK_CHECK -> BACK_ARROW
2023-04-04 21:17:32.587 | INFO | Click (  68,   40) @ BACK_ARROW
2023-04-04 21:17:34.330 | INFO | Click ( 177,  136) @ CARD_0_0
2023-04-04 21:17:43.735 | INFO | equip_enter DOCK_CHECK -> BACK_ARROW
2023-04-04 21:17:43.738 | INFO | Click (  59,   65) @ BACK_ARROW
2023-04-04 21:17:45.577 | INFO | Click ( 185,  153) @ CARD_0_0

**Comment by nxz999** [comment]
同样遇到了

**Comment by wEuphorIA** [comment]
同样遇到了。我也遇到了这个问题

**Comment by zeroxsama** [comment]
![image](https://user-images.githubusercontent.com/55774216/230532181-d98dd0be-1b1f-4bc0-a118-593286b7df79.png)
刷紧急委托 满船了触发强化  会强化临时 航母

**Comment by LmeSzinc** [comment]
@zeroxsama 不要在无关的issue下回复
