### ISSUE TITLE
出击寻敌能否增加舰种判断

### ISSUE THREAD

**Issue by kkkkirsi** [LmeSzinc/AzurLaneAutoScript#2463]
### 你的功能请求是否与问题有关？

想在7-2顺便捞点紫通用. 7图的侦查是不掉通用的, 请问能否增加一个优先打主力的功能 谢谢了

**Comment by LmeSzinc** [comment]
可以修改地图文件来实现，不过2023年了早已经没人打 7-2 了，所以。。。
