### ISSUE TITLE
能否增加一个道中全清的功能

### ISSUE THREAD

**Issue by CNLSL** [LmeSzinc/AzurLaneAutoScript#2465]
### 解决方案

希望能够给所有出击功能增加一个清除道中所有敌舰的选项和是否击杀boss的选项

**Comment by LmeSzinc** [comment]
如果你需要打三星，在这里选三星。

![image](https://user-images.githubusercontent.com/37934724/230729201-c2bed232-0631-4e03-9f30-45fdaec5c766.png)

**Comment by CNLSL** [comment]
作战档案刷道中舰船掉落
