### ISSUE TITLE
请求将alas的各项设置保存在本地/保存过滤器文本

### ISSUE THREAD

**Issue by cxt986524267** [LmeSzinc/AzurLaneAutoScript#2466]
### 你的功能请求是否与问题有关？

如果因为某些情况需要重装alas的话，所有设置需要重新配置。现在只能手动复制所有过滤器。

### 解决方案

1.将所有设置信息保存本地，在重新安装alas后可以覆盖文件
2.如果保存全部设置不好做的话，仅保存过滤器文本也可以。
3.甚至不需要使alas能自动检测文本进行配置，只要能保存就可以了。

**Comment by 18870** [comment]
配置在 `./config` 文件夹里

**Comment by cxt986524267** [comment]
感谢，因为之前覆盖之后没有成功。issue关闭了 打扰了。
