### ISSUE TITLE
大世界隐秘海域自律结束后重新扫描一遍地图，以此帮助解决明石商店被跳过的

### ISSUE THREAD

**Issue by linwei5d** [LmeSzinc/AzurLaneAutoScript#2473]
### 你的功能请求是否与问题有关？

隐秘海域自律结束后，如果站在明石左边会跳过购买明石商店，因为有一天直接连续跳过5次，所以认为急需改进

### 解决方案

完成隐秘海域之后重新扫描地图

### 其他内容

![image](https://user-images.githubusercontent.com/58349183/230893677-c9738261-9e03-4bde-8632-15d3ef2813e1.png)

**Comment by LmeSzinc** [comment]
如何上报bug How to Report Bugs
在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

在提问题前，请先阅读 [常见问题(FAQ)](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn)。
检查 Alas 的更新和最近的 commit，确认使用的是最新版。
上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
