### ISSUE TITLE
委托任务选船（即“推荐”）增加优先度过滤器来避免低等级刷红尖尖+魔方的工具人航母被委托抓走、并且lv飙升

### ISSUE THREAD

**Issue by pein0saga** [LmeSzinc/AzurLaneAutoScript#2475]
### 你的功能请求是否与问题有关？

很多时候需要用到大量低等级小雪森去刷图（比刷紧急委托任务获取魔方和红尖尖）

但是低等级被锁定的小雪森会被刷新出的新任务悄咪咪地拷走去当苦力做委托，从而缺少刷图的低等级的船只

【因为船坞格子不够，所以必须锁定避免没几个回合就被强化退役】

`【紧急委托任务需要LV32以下的白皮航母，但是被抓走以后不但导致缺船而且lv5飙升到两三十】`

而指挥官经常拥有大量lv100+的限定的满破金皮紫皮做仓管，很多不适合推图（而且油耗高）正好可以用来做委托，
同时又能避免小雪森被委托机器人抓走受到迫害

### 解决方案

对于委托任务系统自动选船增加【等级下限、稀有度、满破与否】过滤功能（可选）

比如优先让未满级的、lv100+的、满破、金皮（等级从低到高）优先被拉去做委托任务。

极端情况下，如果不满足上述过滤条件就自动放开限制。

**Comment by SaiCateDoan** [comment]
1级的船又不会被拉去做委托？

**Comment by pein0saga** [comment]
> 1级的船又不会被拉去做委托？

谢谢提醒，已经更正，最低是LV5

**Comment by pein0saga** [comment]
> 1级的船又不会被拉去做委托？

比如LV1轻航竞技神就满足很多委托条件 用的是24h委托过滤器

<img width="1504" alt="Snipaste_2023-04-15_16-46-30" src="https://user-images.githubusercontent.com/2074641/232202153-501a21a1-6049-4f2f-83f5-6b5f98b64a07.png">
<img width="1484" alt="Snipaste_2023-04-15_16-45-31" src="https://user-images.githubusercontent.com/2074641/232202162-22648b40-926e-411e-9ca1-33460cd278fd.png">
<img width="1485" alt="Snipaste_2023-04-15_16-44-40" src="https://user-images.githubusercontent.com/2074641/232202167-7a9025c9-6b15-4015-9184-b9f39d3632a6.png">
<img width="1466" alt="Snipaste_2023-04-15_16-44-19" src="https://user-images.githubusercontent.com/2074641/232202171-c2570d9f-b554-4a85-9811-6965d1f57134.png">

**Comment by pein0saga** [comment]
因为还有“防止委托过多”功能，所以会产生很多中断，出现很多LV-LV32的船，然后一有委托完成就被抓走去完成新委托

**Comment by SaiCateDoan** [comment]
我测试了一下，没锁定的轻航并不会被委托的推荐功能选取

**Comment by pein0saga** [comment]
> 我测试了一下，没锁定的轻航并不会被委托的推荐功能选取
> 
> Lv1的也不会

我把轻航锁定了，否则会被强化退役掉（格子少，船坞很容易就满了）。

**Comment by SaiCateDoan** [comment]
如果我没记错的话，alas会自动退役掉用过的轻航，然后2-4也会获取新的轻航，只要稍微有点船坞应该就能运行，倒是你锁定了轻航，alas退役不掉，会把船坞占满

**Comment by pein0saga** [comment]
> 2-4也会获取新的轻航

紧急任务我已经运行了一星期了，驱逐、巡样都被自动强化掉了，都能顺利运行。我锁定轻航是担心刚掉落的轻航不久就被强化了，有可能导致紧急委托小队中CV30级了，但是掉落的N级的CV都被强化了（这边N的CV掉落率低于R的CV）。如果我指定要竞技神，可能就更难保证了。而且对于强化模式，是优先强化掉N的船，然后退役R和SR，最后格子越来越少，导致十几艘R+SR和几艘N，N中还一定有CV或者指定的竞技神（好像不指定船就有概率换不上装备）

撇开紧急委托不谈，我新出来的LV1船就单独想要留着LV70以后突破甚至改造的时候用的，肯定要锁下来。但是锁下来就可能会被委托抓走

**Comment by pein0saga** [comment]
> 不锁定的船

这里说的就是紧急委托小队的备选N CV船。备选船肯定不在当前编队里（如果放在其他编队就不能自动换船，也会影响其他编队完整性）

**Comment by pein0saga** [comment]
> 如果我没记错的话，alas会自动退役掉用过的轻航，然后2-4也会获取新的轻航，只要稍微有点船坞应该就能运行，倒是你锁定了轻航，alas退役不掉，会把船坞占满

我这边N CV获取率很低，不会因为锁CV导致占太多，锁的数量够用就行（而且我还要留着用来后期突破改造开图鉴）

**Comment by pein0saga** [comment]
> 我测试了一下，没锁定的轻航并不会被委托的推荐功能选取
> 
> Lv1的也不会

谢谢提醒，我查到了具体机制：
一键委托逻辑：【火包女且Official整理】
1.自动筛选出符合要求的舰种
2.从已筛选出的舰船里选择等级最低船直至填补所有空缺
3.如果委托有最低等级要求（比如至少有一个70级舰船）则优先筛选出所有满足等级要求的舰船，再从这些舰船中最低等级的选择一个，剩余的舰船筛选满足第二条
**4.无法筛选出等级为1的舰船
5.无法筛选出未锁定的舰船**
6.同等级的筛选顺序依照船坞中的排序，依照从上到下、从左到右的优先级进行筛选

本文引自 哔哩哔哩Wiki-碧蓝海事局：http://wiki.biligame.com/blhx，文字内容遵守【署名-非商业性使用-相同方式共享 3.0 (CC BY-NC-SA 3.0)】协议
转载请保留原文链接：https://wiki.biligame.com/blhx/%E5%86%9B%E4%BA%8B%E5%A7%94%E6%89%98

现在问题是有时候N CV LV20+就要红脸换人了，但需要保证船坞有足够多的LV1的未锁定备选N CV没被强化或者退役掉。（ LV20+也不能保证下次被利用，因为会被委托抓走）

**Comment by pein0saga** [comment]
> 如果我没记错的话，alas会自动退役掉用过的轻航，然后2-4也会获取新的轻航，只要稍微有点船坞应该就能运行，倒是你锁定了轻航，alas退役不掉，会把船坞占满
我用的是“强化退役”，NCV 基本上全被强化掉了，除非我看一眼，手动锁起来保住N稀有度的CV。掉落的基本上全是R\SR的掉落在船坞里（因为N船被喂狗粮的优先级更高）

最终的解决方案还是用过改代码延长NCV的保质期去规避苛刻的理想条件。

首先关闭ALAS，然后把AzurLaneAutoScript\config\deploy.yaml 中的KeepLocalChanges改成true；
接着修改AzurLaneAutoScript\module\campaign\gems_farming.py的参数，31改成70

```
logger.hr('FINDING FLAGSHIP')

        scanner = ShipScanner(
            level=(1, 70), emotion=(10, 150), fleet=self.config.Fleet_Fleet1, status='free')
        scanner.disable('rarity')
```
