### ISSUE TITLE
优化刷紧急委托“自动换前排”功能（1增加“白鹰白皮限制”的开关 2 按出击次数轮换前排 ）

### ISSUE THREAD

**Issue by pein0saga** [LmeSzinc/AzurLaneAutoScript#2476]
### 你的功能请求是否与问题有关？

1. 祖上砸锅卖铁扩容的船坞爆满， lv100的白鹰白皮驱逐几乎没有了（很多退役让给限定船活动船）
2. 想看到更多更多有爱的驱逐船船翱翔在大海之上，而不是被美利坚白鹰白皮势力垄断（哪怕多消耗一点油）
3. #2065 前排心情多多少少有点问题，自己也遇上类似问题（虽然但是应该是克雷文没满100lv，只能手动换船）如果加上可选的“前排出击满XX次自动换船”，也可以变相控制心情、解决一系列问题。

### 解决方案

1. 增加“白鹰白皮驱逐限制”的开关
暂时的方案是修改AzurLaneAutoScript\module\campaign\gems_farming.py
`index='dd', rarity='common', faction='eagle', extra='can_limit_break'`
根据自己XP删除修改相关内容
AzurLaneAutoScript\config\deploy.yaml KeepLocalChanges改成true

2. 按固定出击次数轮换前排（可选）

**Comment by LmeSzinc** [comment]
`刷紧急委托` 任务本身就是最大收益导向的，包括换1级后排省1油和换前排 这些都是为提高游戏收益而设计的。如果这些功能都变成可开关的，或者用非1油的前排，`刷紧急委托` 任务就没有了存在的意义，因为普通的 `主线图` 任务也可以做到，你应该使用普通的 `主线图` 任务来运行。

按出击次数换船的想法，说实话很烂。出击次数与当前角色等级，当前角色心情不存在明确的换算关系，因为初始等级和初始心情是不定的，关卡获得的经验也是不定的。出击次数的持久化则是一个更难解决的问题，也就是Alas需要记住当前打到第几次，停止再启动Alas后仍能恢复上一次的计数，恢复时还需要判断先前的记录是否可信。

**Comment by pein0saga** [comment]
> `刷紧急委托` 任务本身就是最大收益导向的，包括换1级后排省1油和换前排 这些都是为提高游戏收益而设计的。如果这些功能都变成可开关的，或者用非1油的前排，`刷紧急委托` 任务就没有了存在的意义，因为普通的 `主线图` 任务也可以做到，你应该使用普通的 `主线图` 任务来运行。
> 
> 按出击次数换船的想法，说实话很烂。出击次数与当前角色等级，当前角色心情不存在明确的换算关系，因为初始等级和初始心情是不定的，关卡获得的经验也是不定的。出击次数的持久化则是一个更难解决的问题，也就是Alas需要记住当前打到第几次，停止再启动Alas后仍能恢复上一次的计数，恢复时还需要判断先前的记录是否可信。

谢谢解释，其实我表达不当。其实是想要定制化的更自由的个人需求（出击次数换船也是特定情况下作为一个调节因子，非通用）。别人那里发现了AzurLaneAutoScript\module\campaign下修改文件可以自给自足，满足这些个人需求。

（KeepLocalChanges改成true）

**Comment by pein0saga** [comment]
谢谢[appleapple802](https://github.com/appleapple802)的贡献

_Originally posted by @appleapple802 in https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1940#issuecomment-1336312858_

**Comment by pein0saga** [comment]
备注：修改gems_farming.py可以实现（注意锁船）
“根据心情自动换船换装备”、“调节油耗、稀有度”、“自定义船只”三者之间的调节，

- [ ] 根据心情自动换船换装备 （主线任务需要手动换）
     - [ ] 自动换船范围：“调节稀有度增加油耗”  rarity='rare' （SR、联动的船刷好感和科研经验）
     - [ ] 自动换船范围：“自定义阵营船只”（其他阵营的船刷好感和经验）

这是通用的“普通的主线图 ”所做不到的
