### ISSUE TITLE
请求增加除本期信标外的档案信标

### ISSUE THREAD

**Issue by C1ence4er** [LmeSzinc/AzurLaneAutoScript#2477]
### 解决方案

每日信标打完后能接着转向档案信标进行作战

### 其他内容

![Y$R1J2I64_Z T59){J$0Z(J](https://user-images.githubusercontent.com/36452590/231336502-396eec64-a09a-493b-a1be-c5b2aa5c46fe.png)

**Comment by LmeSzinc** [comment]
`余烬信标` 设置，选择 `当前 + 档案`
![image](https://user-images.githubusercontent.com/37934724/231350951-d82d57da-ca3f-4efe-bb43-9e2b94d4ff65.png)
