### ISSUE TITLE
尝试重新下载，更改Repository但仍无法打开客户端

### ISSUE THREAD

**Issue by Yzcddk** [LmeSzinc/AzurLaneAutoScript#2486]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

1.已在https://github.com/LmeSzinc/AzurLaneAutoScript/releases/tag/v2023.03.28.2  下载了最新的 AlasApp_0.4.1_fullcn.7z 
2.更改了deploy.yaml中的Repository为：'https://github.com/LmeSzinc/AzurLaneAutoScript' 和 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git'

以上方法均无法打开客户端

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/61278450/231760386-8f4c2f93-f0f9-402d-864e-11697f0ac552.png)

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2414#issuecomment-1488493830

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/releases/tag/v2023.04.19
