### ISSUE TITLE
Couldn't run the tw server.

### ISSUE THREAD

**Issue by Zorachristine** [LmeSzinc/AzurLaneAutoScript#249]
Couldn't run the tw server. How to fix it?
![image](https://user-images.githubusercontent.com/73385275/100241125-52faac80-2f6e-11eb-8579-7bf991683015.png)

**Comment by whoamikyo** [comment]
delete your alas.ini and run again.

**Comment by Zorachristine** [comment]
The problem still exists.

**Comment by LmeSzinc** [comment]
Fixed.
