### ISSUE TITLE
SyntaxError: invalid syntax <<<<<<< Updated upstream

### ISSUE THREAD

**Issue by Shawn88-ops** [LmeSzinc/AzurLaneAutoScript#2497]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

今天早上alas本体可以正常启动但是调度器启动报错，貌似报错是有语法错误？是什么依赖库更新了吗？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
ERROR    07:18:28.657 │ SyntaxError: invalid syntax (alas.py, line 482)            
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ C:\Users\86177\OneDrive\桌面\AlasApp_0.3.8_cn\AzurLaneAutoScript\modul │
         │ e\webui\process_manager.py:145 in run_process                          │
         │                                                                        │
         │   143 │   │   │   # Run alas                                           │
         │   144 │   │   │   if func == "alas":                                   │
         │ ❱ 145 │   │   │   │   from alas import AzurLaneAutoScript              │
         │   146 │   │   │   │                                                    │
         │   147 │   │   │   │   if e is not None:                                │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │              _ = ['--port', '22267']                               │ │
         │ │           args = Namespace(electron=True)                          │ │
         │ │ AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'>     │ │
         │ │    config_name = 'alas'                                            │ │
         │ │   console_hdlr = <RichHandler (NOTSET)>                            │ │
         │ │              e = SyntaxError('invalid syntax',                     │ │
         │ │                  ('C:\\Users\\86177\\OneDrive\\桌面\\AlasApp_0.3.… │ │
         │ │                  482, 2, '<<<<<<< Updated upstream\n'))            │ │
         │ │           func = 'alas'                                            │ │
         │ │         parser = ArgumentParser(prog='gui.py', usage=None,         │ │
         │ │                  description=None, formatter_class=<class          │ │
         │ │                  'argparse.HelpFormatter'>,                        │ │
         │ │                  conflict_handler='error', add_help=True)          │ │
         │ │              q = <AutoProxy[Queue] object, typeid 'Queue' at       │ │
         │ │                  0x247e67108c8>                                    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         ╭────────────────────────────────────────────────────────────────────────╮
         │  C:\Users\86177\OneDrive\桌面\AlasApp_0.3.8_cn\AzurLaneAutoScript\alas │
         │ .py:482                                                                │
         │ <<<<<<< Updated upstream                                               │
         │  ▲                                                                     │
         ╰────────────────────────────────────────────────────────────────────────╯
         SyntaxError: invalid syntax
```

### 截图

![image](https://user-images.githubusercontent.com/57652481/232170007-0e055f7e-55cd-49d5-a451-5dc392bc9493.png)

**Comment by Shawn88-ops** [comment]
重新启动后可以正常使用，现在就是好奇这个报错怎么回事了（蚌埠住了）

**Comment by Shawn88-ops** [comment]
啊

> 

啊这，我确实改过，在重启三次仍旧报错的时候会kill adb然后重连，但是之前都好好的怎么突然报错了，是因为代码更新的问题吗？

**Comment by Shawn88-ops** [comment]
> > 啊
> > > 
> > 
> > 
> > 啊这，我确实改过，在重启三次仍旧报错的时候会kill adb然后重连，但是之前都好好的怎么突然报错了，是因为代码更新的问题吗？
> 
> 可能是无意间复制或者删除了一个字符导致崩了，或者是不是删、加了空格？python对缩进有严格要求，缩进控制着循环的控制域，代码前部多一个或者少一个空格也会导致报错。 你可以修改alas/config/deploy.yaml里第30行的KeepLocalChanges: false为true， 这样就可以保存本地变更，自动更新时会避开你修改的文件，等一周或者一个月再手动更新一下完事了。

自从之前改过能跑之后没动过文件代码了，keeplocalchanges是改过了的，不然远程连接也会给我重新覆盖来着

**Comment by Shawn88-ops** [comment]
从来没有过，是alas自启动更新的

**Comment by SaiCateDoan** [comment]
不管怎么说，看起来跟雷电模拟器是没啥关系了
看起来就是修改代码导致冲突了，自己慢慢捣鼓吧

**Comment by LmeSzinc** [comment]
打开 console.bat ，执行：
```
git reset --hard
```

**Comment by Shawn88-ops** [comment]
> 打开 console.bat ，执行：
> 
> ```
> git reset --hard
> ```

也不至于直接回退版本吧，我看到最新的源码貌似是对def loop(self)下的代码做了一些删除，之前我在下面写过重启adb的代码被更新掉了，应该是那里起了冲突？

**Comment by SaiCateDoan** [comment]
我的建议是，如果你不能熟练使用git，那就覆盖更新之后再手动修改代码

**Comment by Shawn88-ops** [comment]
问题应该不大，重启之后更新的源码默认覆写了冲突区，能跑就行.jpg
话说回来，想请问一下现在有没有针对雷电模拟器3次失败restart时重启adb的优化呢，没有的话我还得自己加

**Comment by SaiCateDoan** [comment]
> 问题应该不大，重启之后更新的源码默认覆写了冲突区，能跑就行.jpg 话说回来，想请问一下现在有没有针对雷电模拟器3次失败restart时重启adb的优化呢，没有的话我还得自己加

关于雷电模拟器这个，我其实有一个绝妙的方法可以解决，但是我有点担心不懂的人硬用所以没写文档
用Alas的adb手动替换掉雷电的adb，包括adb文件夹里的两个dll，然后触控方案选MaaTouch
我这样测试了一星期没出任何bug
另外我想问一下，雷电模拟器有什么特别的优势吗，为什么一定要用雷电模拟器

**Comment by Shawn88-ops** [comment]
雷电模拟器的内存占用是最小的那一批，内存占用貌似也就蓝叠能跟雷电模拟器打打，但是蓝叠录屏没有雷电方便，对于我这小破电脑雷电就雷电吧
用alas的adb替换雷电的adb真的不会导致其他脚本如maa出现找不到adb的情况吗？真的是可以改的吗？

**Comment by Shawn88-ops** [comment]
我知道你们挺忙的，无偿对于单个模拟器优化很花时间，所以我自己改改，能跑就行，但毕竟还是希望有空可以有人优化的呢~

**Comment by SaiCateDoan** [comment]
adb是可以替换的，不会影响maa，我也测试过了
我记得alas有重启adb相关的功能，你可以把你觉得有用的代码迁移到合适的位置，用那个选项控制，然后pr
alas贼缺开发

**Comment by SaiCateDoan** [comment]
> 问一下maatouch和minitouch具体有啥区别吗？之前在群里看的好像结论是没啥区别？

使用起来没区别，但是实现原理不一样
minitouch在雷电上会有触控失效的bug，但是maatouch不会有（至少我没测试出来）

**Comment by Shawn88-ops** [comment]
> adb是可以替换的，不会影响maa，我也测试过了 我记得alas有重启adb相关的功能，你可以把你觉得有用的代码迁移到合适的位置，用那个选项控制，然后pr alas贼缺开发

我要是能写python我早就pr了hhh，python课在这个学期，现在我只有对于这个语言最基本的了解

**Comment by Shawn88-ops** [comment]
> 

我现在雷电模拟器多开minitouch直接就ban了，只能用模拟器自带的ADB，倒是没跑出过BUG，除了ADB慢了一些之外倒也没啥问题（没记错的话好像0.3s多了）

**Comment by Shawn88-ops** [comment]
不至于，像我之前提的issue有个大佬改的命令一样改一下就行，抛出错误的时候用os.system('adb kill-server') 和os.system('adb start-server')也比计划重启开销要来得小吧
issue链接：https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2130
