### ISSUE TITLE
委托过滤器相关

### ISSUE THREAD

**Issue by zengshzh** [LmeSzinc/AzurLaneAutoScript#2499]
### 你的功能请求是否与问题有关？

希望新增“心智单元”类的tag。
在某次改版以后。部分钻头委托会产出心智单元，但是并不是所有的钻头委托都是。
就我个人而言，我会倾向于优先选择心智委托，但是我很难将心智委托从钻头委托中挑选出来

### 解决方案

扫描可能的委托产物，如果有心智单元则归类为心智tag

### 其他内容

![image](https://user-images.githubusercontent.com/48642377/232205450-c955aed3-1b9f-4327-b855-2a7b148075bb.png)
一个不含心智的钻头类委托

**Comment by SaiCateDoan** [comment]
Alas可以通过区分指定委托的形式选择含有心智的委托，但确实都属于Drill分类下
但是，因为使用不够精确的过滤器会导致收益惨不忍睹，Alas没有必要重新为心智做分类
同时，Alas内置的过滤器提供了以心智为主要收益的模式，正常的需求可以使用默认过滤器解决
![image](https://user-images.githubusercontent.com/48789988/232220378-145f497d-c4de-4658-9a20-cc8302bcee55.png)

**Comment by SaiCateDoan** [comment]
PS：如果你想写一个收益不低于默认过滤器的委托过滤器，那你一定需要一个一个委托写过去，此时是否在代码上区分心智委托其实影响不大

**Comment by LmeSzinc** [comment]
`UrgentDrill`

**Comment by zengshzh** [comment]
刚刚查了下碧蓝航线wiki:https://wiki.biligame.com/blhx/%E5%86%9B%E4%BA%8B%E5%A7%94%E6%89%98,
只有额外委托的钻头才会给心智，也就是ExtraDrill，谢谢大佬们的解答
