### ISSUE TITLE
alas无法启动

### ISSUE THREAD

**Issue by PikipikiTime** [LmeSzinc/AzurLaneAutoScript#2500]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [ ] 我正在使用最新版的 Alas

### 描述你的问题

清理垃圾误删了一部分alas的文件，重新下载后无法从github获取文件，从github下了zip解压出来放到alas的文件夹并替换掉部分文件后还是无法启动，一直是一个页面

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![无标题](https://user-images.githubusercontent.com/109199138/232215512-d450bcac-a4cb-47f1-b302-4f885523c9dd.png)

**Comment by LmeSzinc** [comment]
完全删除之前的文件夹，不要替换文件

**Comment by PikipikiTime** [comment]
> 完全删除之前的文件夹，不要替换文件

跳过文件不替换没用，我删了文件又从压缩包解出来还是截图的那个界面

**Comment by LmeSzinc** [comment]
完全删除之前的文件夹，不要替换文件的意思是：不要将压缩包解压到原来的文件夹上，而不是点击跳过文件替换的按钮。
你需要完全删除之前的文件夹，然后右键点击压缩包，左键点击 解压到... ，并选择一个新的路径。

**Comment by PikipikiTime** [comment]
> 完全删除之前的文件夹，不要替换文件的意思是：不要将压缩包解压到原来的文件夹上，而不是点击跳过文件替换的按钮。 你需要完全删除之前的文件夹，然后右键点击压缩包，左键点击 解压到... ，并选择一个新的路径。

![无标题 1png](https://user-images.githubusercontent.com/109199138/232258139-9453a6dc-ac25-415e-bafb-100eafe88726.png)
huan换成新路径后还是不行

**Comment by PikipikiTime** [comment]
> 完全删除之前的文件夹，不要替换文件的意思是：不要将压缩包解压到原来的文件夹上，而不是点击跳过文件替换的按钮。 你需要完全删除之前的文件夹，然后右键点击压缩包，左键点击 解压到... ，并选择一个新的路径。

下了4.2安装包后直接解决了，感谢更新
