### ISSUE TITLE
运行自动安装包时搞到一半卡住了……？

### ISSUE THREAD

**Issue by 345teas** [LmeSzinc/AzurLaneAutoScript#2502]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

解压了AlasApp_0.4.1_fullcn.7z，检查完了config/deploy.yaml的那两个，运行了alas.exe过了会然后就卡了，说是没法建立新连接？
（不怎么懂电脑，看不懂）（看了其他人的问题似乎没有类似的）
（；´д｀）ゞ

### 如何复现

1，解压AlasApp_0.4.1_fullcn.7z
2，运行alas.exe
3，卡住

### 预期行为

正常运行安装

### 相关 Logs

```Text
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /openatx/stf-binaries/0.3.0/node_modules/%40devicefarmer/minitouch-prebuilt/prebuilt/x86/bin/minitouch (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000218876E6208>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
```

**Comment by LmeSzinc** [comment]
log 发全，流量不要钱

**Comment by 345teas** [comment]
一个星期后再打开莫名其妙就行了……打扰了不好意思……
（话说这个能删掉的吗
