### ISSUE TITLE
启动命令行提示不满足uiautomator2cache==0.3.0.1条件

### ISSUE THREAD

**Issue by pein0saga** [LmeSzinc/AzurLaneAutoScript#2510]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

（并不是全新安装）

启动命令行提示不满足uiautomator2cache==0.3.0.1条件

然后我就去requirements.txt里面把uiautomator2cache==0.3.0.1用井号注释掉了，就能顺利启动

然后看见更新器记录里面有

`2f0382c4 | LmeSzinc | 2023-04-19 22:58:22 +0800 | Opt: abspath in appdir of uiautomator2 cache`

2f0382c4

我ALAS的安装路径一直是带有空格的Program Files，命令行都要用"*/Program Files/*" 不知道和路径是否相关

我19日下午还是能正常使用的

我是否需要单独检查升级 uiautomator2cache的版本？

```
7a16b71e | LmeSzinc | 2023-04-01 02:12:25 +0800 | Opt: Use local assets cache in uiautomator2
631fec2a | LmeSzinc | 2023-04-19 12:53:36 +0800 | Dep: Upgrade to uiautomator2cache==0.3.0.1
343520cc | LmeSzinc | 2023-04-01 02:32:13 +0800 | Dep: Add uiautomator2cache
```

### 如何复现

启动程序

### 预期行为

无阻碍启动

**Comment by LmeSzinc** [comment]
需要 log 和截图

**Comment by LEalduin** [comment]
![image](https://user-images.githubusercontent.com/115489062/233268984-d899caa7-e207-4d17-9d8b-76e5cf9f7670.png)
遇到了类似问题

**Comment by pein0saga** [comment]
> uiautomator2cache

搜遍互联网找不到这个模块相关信息（依赖），最近的PR的神秘代码都是关于它的。

只知道黄色小车[openatx](https://github.com/openatx) 
“Install the UiAutomator2 Driver
http://appium.io › docs › quickstart › uiauto2-driver
Running this command will locate and install the latest version of the UiAutomator2 driver, making it available for automation.”

**Comment by LmeSzinc** [comment]
@LEalduin 阅读安装教程 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E7%BC%96%E8%BE%91%E5%AE%89%E8%A3%85%E8%AE%BE%E7%BD%AE

**Comment by LmeSzinc** [comment]
uiautomator2cache 是我单独做的库，提供了 uiautomator2 里的 atx-agent, uiautomator, minitouch, minicap 的缓存文件，防止网络稀烂的用户无法在 Alas 运行时下载它们。单独成库的优势是不需要将 binary 加入 git 导致仓库体积增加。

**Comment by pein0saga** [comment]
> > @LEalduin 阅读安装教程 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E7%BC%96%E8%BE%91%E5%AE%89%E8%A3%85%E8%AE%BE%E7%BD%AE
> 
> 更换了一下pypi镜像解决了
我之前两个源都用的国内的，但是有次连不上，就全改用国外加上gitproxy了。你是把pypi镜像改国内了吗？

**Comment by pein0saga** [comment]
> @LEalduin 阅读安装教程 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E7%BC%96%E8%BE%91%E5%AE%89%E8%A3%85%E8%AE%BE%E7%BD%AE

和KeepLocalChanges: true有关吗？
是不是因为KeepLocalChanges: true所以我东西没能成功更新？要手动改一下？

**Comment by pein0saga** [comment]
> > @LEalduin 阅读安装教程 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E7%BC%96%E8%BE%91%E5%AE%89%E8%A3%85%E8%AE%BE%E7%BD%AE
> 
> 更换了一下pypi镜像解决了

谢谢，已经好了，上次改回国外源的时候，pypi改错了。现在用了国外官方源，已经开始下载确是文件了（虽然用了proxy还是慢哭了
