### ISSUE TITLE
求求大佬可不可以引入一个任务完成关闭电脑的功能呀

### ISSUE THREAD

**Issue by p1naster** [LmeSzinc/AzurLaneAutoScript#2515]
### 你的功能请求是否与问题有关？

感谢大佬无偿提供这么棒棒的工具，泪流满面，不知道是否有捐赠入口想请喝咖啡/可乐支持下~ 
另外有个功能请求嘛~ 目前我是用家里的电脑挂的游戏，想一天集中过两次收拾一下任务就好啦。我看你到Alas设置有一个“当任务队列清空后关必游戏”的功能，所以想如果有一个任务完成后自动自动关闭电脑就太好了~ 

### 解决方案

在任内务队列清空后，引入一个任务完成关闭电脑的功能，添加执行shutdown的小脚本~谢谢大佬

### 其他内容

![image](https://user-images.githubusercontent.com/17944213/233764037-d7083b1d-0e38-4b75-88dd-a187a034dc3a.png)

**Comment by uWayLu** [comment]
這反設計初衷啦，或是你根據作息習慣直接在系統層設定每日定時關機？

**Comment by p1naster** [comment]
收到 谢谢大佬 哈哈~
