### ISSUE TITLE
活动委托OCR识别出错

### ISSUE THREAD

**Issue by snowly233** [LmeSzinc/AzurLaneAutoScript#2525]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

活动委托在OCR识别中log显示出一些错误的符号，导致无法分类至活动委托

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://user-images.githubusercontent.com/75160294/234828229-a6a0282c-b656-4d74-b4ab-5a9f61ef9253.png)

**Comment by guoh064** [comment]
委托类别里面就没有写过假日航线的filter_string，需要适配。
方便的话请提供该委托的截图。 @snowly233
