### ISSUE TITLE
能不能多加一个设置选项如果是单项任务失败仅暂停此项而继续队列中的其他项

### ISSUE THREAD

**Issue by bsyyno1** [LmeSzinc/AzurLaneAutoScript#2526]
### 你的功能请求是否与问题有关？

最近碰到好几次这样的情况，因为用的新设备运行里面没有信标的出击队伍，主程序就直接卡住无法继续导致后续队列中的其他任务无法运行……再比如中间碰到船坞或者仓库满了也会跳出来，导致科研和委托收不了

### 解决方案

增加设置的选项单任务无法进行时仅报错不跳出，继续运行后续任务

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/pull/1033#issuecomment-1213320420
