### ISSUE TITLE
同时启用活动图和主线图时心情计算出错

### ISSUE THREAD

**Issue by zjhaoz** [LmeSzinc/AzurLaneAutoScript#2527]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

同时启用主线图和活动图时心情的计算会出错。

### 如何复现

同时启用活动图和主线图，并且用同一支舰队去刷，比如2号舰队，在完成主线图后主线图设置中显示心情为30（举例），但是活动图同样的2号舰队心情却是满的，导致刷的途中出现心情不足并导致alas 报错

### 预期行为

舰队的心情应该在所有设置都保持同步，而不是在每个设置中单独计算

**Comment by snowly233** [comment]
似乎以前是可以分别选择普通舰队和困难舰队心情设置，但是最近貌似撤回更新了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1849#issuecomment-1312664751
