### ISSUE TITLE
台服 不接取活动每日委托

### ISSUE THREAD

**Issue by xzjjasper** [LmeSzinc/AzurLaneAutoScript#2537]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

台服活动委托识别不在genre内，不太懂该怎么修正，要在`commission/project_data.py`添加委托名称么？
```
INFO     09:36:26.018 │ <<< COMMISSION DETECT >>>                                  
INFO     09:36:26.138 │ [COMMISSION 0.117s] 料理製作                               
WARNING  09:36:26.140 │ Name with unknown genre: 料理製作
```

**Comment by LmeSzinc** [comment]
b5398cb97f8b406f5cdf1c7191fc5ee02372740b
