### ISSUE TITLE
【需求】在运行结束时自动把模拟器放置在显示器顶层的功能

### ISSUE THREAD

**Issue by rfzmiaoling** [LmeSzinc/AzurLaneAutoScript#254]
**Is your feature request related to a problem? Please describe.**
此需求不来自于一个错误

**Describe the solution you'd like**
运行结束时将模拟器置顶
- 正常运行结束且没有打开收菜模式时
- 半自动运行，每次关卡结束时
- 运行出现报错时

**Comment by LmeSzinc** [comment]
不会添加此功能

1. 需要适配不同模拟器十分麻烦
2. 个人希望 Alas 能在后台静默运行，避免强制窗口对焦影响工作，发出声音造成惊吓等
