### ISSUE TITLE
大世界每月开荒时不能正确处理机关

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#2549]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

今天发现24海域的危险海域有机关但是alas开荒时未处理，检查了当日log中所有包含"One of the fleet mechanism is solved"出现5次，但"All fleet mechanism are solved"只出现1次，认为大部分机关并没有被成功处理，会造成损失。
[2023-05-01_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11365733/2023-05-01_alas.txt)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![1682906831478](https://user-images.githubusercontent.com/50830808/235463295-85b4fd07-f057-4f8b-a68b-2a09436230cc.png)
![1682931789925](https://user-images.githubusercontent.com/50830808/235463304-f3d94da1-73ee-4b2c-8fd1-7af2a5aaf5cc.png)
![1682872644554](https://user-images.githubusercontent.com/50830808/235463309-cc4dd823-4dfb-476e-abd0-1040374b9837.png)
![1682878154685](https://user-images.githubusercontent.com/50830808/235463321-93ac0e5f-fb7e-4483-90cc-87bd1b7d46f2.png)
![1682886576972](https://user-images.githubusercontent.com/50830808/235463332-50eb6ae4-e4e3-4c61-8886-478cbb90a979.png)

### 还有别的吗？

勾选了完成地图随机事件。

**Comment by q310812350** [comment]
我也发现了类似的bug，似乎alas在让舰队移动时会点到机关旁边的格子，然后过去之后alas会发现什么也没有发生，然后就退出了

**Comment by shoucandanghehe** [comment]
我注意到两支舰队同时踩那个机关
alas会让指定出击的舰队分别踩一次机关
不会调动另一只舰队正确触发机关

**Comment by guoh064** [comment]
@LmeSzinc 乐事，这里的map_rescan_current的结果根本没有用上，result值没有被刷新，一定返回False。<del>想必问题出在这里。</del>让我速速交个PR
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/20eee7432825ea72745df37e5f176104076a98c5/module/os/map.py#L811-L830
