### ISSUE TITLE
战斗失败之后切换另一队继续

### ISSUE THREAD

**Issue by EncodedWitcher** [LmeSzinc/AzurLaneAutoScript#2554]
### 你的功能请求是否与问题有关？

低耗队刷图偶尔会翻车
然后界面卡在旗舰大破失败的界面
可以发现整个调度器因为这个直接卡住然后终止了

### 解决方案

旗舰大破或者前排全灭或者超时的时候
切换到另一对继续作战
或者和其他脚本一样，添加 失败后撤退/切换队伍继续 的选项

**Comment by LmeSzinc** [comment]
大部分人的玩法是将队伍分为道中队和boss队，官方的自律寻敌设定也是这样的，并且不会用boss队打道中，因为它们的配对侧重点不同。配对不行打不过图，你应该提升练度或者开挂打，当然，这不在Alas的范围内。
