### ISSUE TITLE
Alas中的更新器无法正常更新

### ISSUE THREAD

**Issue by NeverBeforr** [LmeSzinc/AzurLaneAutoScript#2561]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Alas中的更新器无法正常更新
在更新器中点击进行更新后，会出现更新成功，正在重启的提示，但自动重启后仍然还是原来版本，没有更新成功。但再下载一个新的安装包后打开，新的这个Alas就会是最新版本。

### 如何复现

1. 前往 '更新器'
2. 点击 '进行更新'
3. 出现 '更新完成，正在重启'
4. 出现问题，更新没有成功

### 预期行为

能正常更新

### 截图

![1](https://user-images.githubusercontent.com/103736124/236686584-ef584485-8746-4756-b7bf-b40f59db2e87.png)
![2](https://user-images.githubusercontent.com/103736124/236686589-db9cf07b-701d-4090-b7e8-3812e734507c.png)
![3](https://user-images.githubusercontent.com/103736124/236686593-eb724302-983b-455a-831d-1b807feaec47.png)
![4](https://user-images.githubusercontent.com/103736124/236686634-8c391efe-c9c6-497f-a564-6e5a58ffd545.png)

**Comment by shiyuqianyi** [comment]
直接用新版本的覆盖过去

**Comment by NeverBeforr** [comment]
> 是不是在config里把更新给关了，我记得我上次就是改了更新参数结果玩崩成这样的

请问下这个要怎么看呢

**Comment by NeverBeforr** [comment]
> > > 是不是在config里把更新给关了，我记得我上次就是改了更新参数结果玩崩成这样的
> > 
> > 
> > 请问下这个要怎么看呢
> 
> 我也记不清了，你可以试试直接把新下载的包里的config给覆盖了，再改一下更新地址

好的，多谢
