### ISSUE TITLE
物资达到60w的时候会无法派遣委托和退役

### ISSUE THREAD

**Issue by familior** [LmeSzinc/AzurLaneAutoScript#2562]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当物资达到60w的时候无法派遣委托和退役，可能其他获取物资的玩法也无法正常进行

### 如何复现

物资达到60w时

### 预期行为

脚本卡住

### 相关 Logs

```Text
无
```

### 截图

![image](https://user-images.githubusercontent.com/84607943/236778038-c1c76e88-fdd2-4466-88ed-0c89634caca8.png)
![08N@)DG(((()N Y` O3N`F5](https://user-images.githubusercontent.com/84607943/236778181-65e69ca8-b8ac-4abf-97fd-f26d940397e8.jpg)

### 还有别的吗？

无

**Comment by guoh064** [comment]
买点咖喱

**Comment by ec7529a2** [comment]
目前alas没有相关处理，只能想办法手动消耗物资了，比如商店里买点装备箱之类的

> 买点咖喱

这是60万物资，不是2.5万石油，买咖喱没用

**Comment by guoh064** [comment]
哦物资
那可以反复切换导驱前后排，一次200

**Comment by SaiCateDoan** [comment]
买点箱子

**Comment by LmeSzinc** [comment]
之前打算加一个处理溢出资源的任务，但是功能比较简单我打算用来培养新开发。

这里需要无底洞的无条件的无副作用的资源消耗方案，买猫箱买科研图纸都是被否决的。取 90% 上限，石油超出 2.25w 去后宅买咖喱，物资超过 54w 去商店买垃圾，经验书超过 2700 找多余白皮喂100级然后退役。
