### ISSUE TITLE
下载中出现错误 ValueError: invalid variable ‘$’EXa19116'’

### ISSUE THREAD

**Issue by YHN0** [LmeSzinc/AzurLaneAutoScript#2564]
### 你的功能请求是否与问题有关？

下载中出现错误

### 其他内容

![屏幕截图 2023-05-09 220140](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/133022973/c2193d94-da2b-46dc-bde5-879cfe1f9dbd)

**Comment by LmeSzinc** [comment]
先解压再运行
