### ISSUE TITLE
长时间运行后卡在奇怪的循环

### ISSUE THREAD

**Issue by GitUpYao** [LmeSzinc/AzurLaneAutoScript#260]
**Describe the bug**
循环主线图捞船.不定时出现.进入收菜循环后不进图.检查过停止条件并不是这里的问题（可以直接看日志最后一段）

**To Reproduce**
随机出现，无法固定重现

**Log**

[2020-12-15_alas.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5690717/2020-12-15_alas.zip)

**Comment by LmeSzinc** [comment]
已修复
确认当 委托收获关闭 且 出击界面出现委托完成的提醒 时, 会进入循环.

~~话说, 你是第一个关闭 启用委托收获 这个选项的人~~
