### ISSUE TITLE
[EN]活动关卡名称错误

### ISSUE THREAD

**Issue by vikilyc** [LmeSzinc/AzurLaneAutoScript#2620]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

现显示活动关卡为假日航线, 活动功能无法正常开启.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                                             EVENT
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
WARNING  2023-05-25 16:41:47.081 │ Map file not found: campaign.event_20201126_cn.a1
WARNING  2023-05-25 16:41:47.088 │ Existing files: ['sp3', 'sp', 'sp2', 'sp1', 'sp4']
CRITICAL 2023-05-25 16:41:47.095 │ Possible reason #1: This event (event_20201126_cn) does not have a1
CRITICAL 2023-05-25 16:41:47.101 │ Possible reason #2: You are using an old Alas, please check for update, or make map files yourself using
         dev_tools/map_extractor.py
```

**Comment by zhmou** [comment]
出现相同问题
下拉菜单中只有 假日航线 这一个活动
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/43105172/95d15347-bdb9-485c-8f45-81ff82249dbc)

**Comment by halfyua** [comment]
台服也有相同情况

**Comment by HWHKL** [comment]
国服也一样，修改成sp1后会无限寻找，输入t1无法被识别；下面是无限循环的log，最后直接报错退出alas，他也说了是Campaign name error，该加ocr勒
INFO     15:02:20.705 │ <<< UI ENSURE INDEX >>>                                    
INFO     15:02:20.747 │ No stage found.                                            
INFO     15:02:21.532 │ No stage found.                                            
INFO     15:02:21.982 │ No stage found.                                            
INFO     15:02:22.173 │ No stage found.                                            
INFO     15:02:22.455 │ No stage found.                                            
INFO     15:02:23.740 │ UI get current page                                        
INFO     15:02:23.746 │ [UI] page_event                                            
INFO     15:02:23.747 │ Already at page_event   
WARNING  15:02:57.370 │ Campaign name error                                        
ERROR    15:02:57.371 │ ScriptEnd: Campaign name error

**Comment by LmeSzinc** [comment]
#2644
