### ISSUE TITLE
侵蚀1练级 请求增加自定义保留作战补给凭证数量的功能

### ISSUE THREAD

**Issue by Frocean** [LmeSzinc/AzurLaneAutoScript#2622]
### 你的功能请求是否与问题有关？

为了避免无法购买港口商店的商品，Alas会保留100000作战补给凭证
但是快月末了发现这样做兑换卷不太够用，所以希望能够自定义上述保留凭证数值

### 解决方案

自定义作战补给凭证保留数值

**Comment by guoh064** [comment]
兑换券不够一般都是深渊、隐秘和据点没打满……
（以我为例现在有12000+的兑换券，肯定够换了）
以及，双倍指令书可换可不换（有alas不一定要用双倍）

**Comment by Frocean** [comment]
我用alas月初auto到现在有将近9k，都打满了的，也不知道这个人差怎么差这么多= =
如果换指令书要10.6k大概，双倍占3k，alas不用双倍倒是挺在理的，就希望有时间能稍微加一下吧（虽然最近大版本估计没时间）

**Comment by guoh064** [comment]
另外，我如果没理解错的话，你是想让侵蚀一保留的黄币数量大于10w？
侵蚀一的目的是消耗**多余**黄币换取经验，如果本身黄币就不够的话那是否要开侵蚀一都成问题。

**Comment by ErzsebetDAZE** [comment]
没有太明白你说的10w黄币限制和缺兑换券之间的逻辑关系.
修改黄币限制在AzurLaneAutoScript\module\config\config_manual.py文件的309行左右,更改OS_CL1_YELLOW_COINS_PRESERVE的值即可

**Comment by Frocean** [comment]
是的，我是想让侵蚀1保留的黄币数量大于10w，但是如果自己盯着目标数，加上到月底之前大世界都要一直开，黄币数量也会变动，忙起来就没法保证自己能关注到黄币问题了；
黄币限制和兑换券的方面上，是因为我目前显示的重置后可兑换兑换卷数量未满足个人期望，而可控制这个数额的可控选项除去必打的坐标外，只有紫币、黄币、战利品和能源，于是考虑从黄币角度来解决这个问题；黄币是100:1兑换兑换券，所以想设定黄币限制，以在保证月末之前一直开侵蚀1练级的条件，加上其他资源，在月末的期望数量下，做到能兑换完月度商店
虽然我也不知道为什么我只有9k
黄币条件修改主要个人也找不到在哪改，感谢E佬指出，这就去改
那问题多半是解决了，关掉了
