### ISSUE TITLE
活动图无法使用 报错Possible reason #1: This event (event_20201126_cn) does not          have b1        

### ISSUE THREAD

**Issue by jdjn123** [LmeSzinc/AzurLaneAutoScript#2625]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/68859249/fa2461d0-4ffd-4b8c-8bcf-cccf9de89d19)
![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/68859249/5aa30f04-2fa4-451a-8703-ac14cd16c490)
活动图功能无法使用

### 如何复现

1. 前往 '活动图无法使用'
3. 点击 '....'
4. 滑动到 '....'
5. 出现问题

### 预期行为

自动打活动图

### 相关 Logs

```Text
INFO     19:21:26.539 │ Reuse forward: ForwardItem(serial='127.0.0.1:62001',       
         local='tcp:20708', remote='tcp:53516')                                    
INFO     19:21:26.622 │ [Screen_size] 1280x720                                     
WARNING  19:21:26.668 │ Map file not found: campaign.event_20201126_cn.b1          
WARNING  19:21:26.669 │ Existing files: ['sp', 'sp1', 'sp2', 'sp3', 'sp4']         
CRITICAL 19:21:26.670 │ Possible reason #1: This event (event_20201126_cn) does not
         have b1                                                                   
CRITICAL 19:21:26.671 │ Possible reason #2: You are using an old Alas, please check
         for update, or make map files yourself using dev_tools/map_extractor.py   
CRITICAL 19:21:26.672 │ Request human takeover                                     
INFO     19:21:26.673 │ No provider specified, skip sending
```

### 截图

![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/68859249/555912c4-0ae7-42c9-b1d4-8aa2ad8de098)

### 还有别的吗？

无

**Comment by XZ-XuZhang** [comment]
假日航线已经结束了，当然会出错，新的活动好像还没适配。

**Comment by udisns** [comment]
新的活动还没适配，这次大更改的东西太多了可能还没来得及弄吧

**Comment by Cyan-grey** [comment]
很显然你在提问之前并没有
“”我已经搜索了现有的 issues
 我在提问题之前至少花费了 5 分钟来思考和准备
 我已经阅读了 Wiki 中的 常见问题(FAQ)“”

**Comment by yangdoubao733** [comment]
新活动还在适配，别急

**Comment by LmeSzinc** [comment]
#2637
