### ISSUE TITLE
新活动适配

### ISSUE THREAD

**Issue by udisns** [LmeSzinc/AzurLaneAutoScript#2633]
### 你的功能请求是否与问题有关？

速速更新新活动，别逼我跪下来求你

**Comment by tom20051012** [comment]
同跪求新活动适配

**Comment by Cyan-grey** [comment]
免费用着人家的东西还来催更，每次出新活动，不都是要一段时间来适配吗，又不是不更新，急什么

**Comment by PkuRinko** [comment]
> 免费用着人家的东西还来催更，每次出新活动，不都是要一段时间来适配吗，又不是不更新，急什么

这次有点慢，而且人家都说了“跪下来求你”，这不就是开玩笑吗，别上纲上线

**Comment by quarterQ4** [comment]
这次更新的地方确实太多啦，多等等好了😁

**Comment by LmeSzinc** [comment]
#2637
