### ISSUE TITLE
半自动点击器自动点击重开

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#2634]
### 你的功能请求是否与问题有关？

大佬，现在的半自动点击器在关卡结束后是点击空白处回到选关界面，能不能加个选项允许半自动点击器在结束后自动点击重开关卡？这样新活动开了哪怕还没来得及做出关卡适配也能先用这个功能自动刷PT了，毕竟开了周回也只需要点开始退役再来一次这点东西，总比手点强多了

**Comment by LmeSzinc** [comment]
#2637
