### ISSUE TITLE
紧急委托无法识别活动图编号

### ISSUE THREAD

**Issue by TarringFox** [LmeSzinc/AzurLaneAutoScript#2639]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

截止到提交该issue时，紧急委托功能无法识别活动图编号（t1-t6，ht1-ht6），会错误的认为填写了ABCD图编号

### 如何复现

1.使用“刷紧急委托”任务
2. 关卡名称填写活动图编号，例如T1
3. 运行
4. 出现问题

### 截图

![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58627619/a5330983-624b-4840-b449-ed4f970b5cb8)
![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58627619/a6b2cdcc-fda8-4901-8919-9a3a95033f77)

**Comment by fabiopr2** [comment]
lowercase T3
although it will still be a problem '-'

**Comment by MapleRabbit** [comment]
转换地图名的地方好像有问题(196-203)，导致T3被转成A3了

**Comment by LmeSzinc** [comment]
#2644
