### ISSUE TITLE
更新后无法进入碧蓝航线，提示未安装

### ISSUE THREAD

**Issue by Setaria-hx** [LmeSzinc/AzurLaneAutoScript#2642]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

未找到AzurLane软件包，请确认已找到AzurLane
安装在设备“127.0.0.1:62001”上

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     20:18:31.935 │ Start scheduler loop: alas                                 
INFO     20:18:31.938 │ [Server] cn                                                
INFO     20:18:31.956 │ Bind task {'Alas', 'General'}                              
INFO     20:18:31.959 │ Pending tasks: ['Restart', 'Commission', 'Research',       
         'Reward', 'Freebies', 'Event']                                            
INFO     20:18:31.960 │ [Task] Restart (Enable, 2020-01-01 00:00:00)               
INFO     20:18:31.962 │ Bind task {'Restart', 'Alas', 'General'}                   
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     20:18:33.822 │ DEVICE                                                     
INFO     20:18:33.823 │ [AdbBinary]                                                
         D:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     20:18:33.827 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     20:18:33.829 │ <<< DETECT DEVICE >>>                                      
INFO     20:18:33.830 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     20:18:33.833 │ 127.0.0.1:62001                                            
INFO     20:18:33.834 │ Auto device detection found only one device, using it      
INFO     20:18:33.839 │ already connected to 127.0.0.1:62001                       
INFO     20:18:33.841 │ [AdbDevice] AdbDevice(serial=127.0.0.1:62001)              
INFO     20:18:33.842 │ <<< DETECT PACKAGE >>>                                     
INFO     20:18:33.844 │ Get package list                                           
INFO     20:18:34.356 │ Here are the available packages in device                  
         "127.0.0.1:62001", copy to Alas.Emulator.PackageName to use it            
INFO     20:18:34.358 │ No available packages on device "127.0.0.1:62001"          
CRITICAL 20:18:34.359 │ No AzurLane package found, please confirm AzurLane has been
         installed on device "127.0.0.1:62001"                                     
CRITICAL 20:18:34.361 │ Request human takeover
```

### 还有别的吗？

夜神 7.0.5.5

**Comment by LmeSzinc** [comment]
字面意思，你需要确认你在模拟器上安装有碧蓝航线游戏客户端

**Comment by Setaria-hx** [comment]
b服，模拟器上已经安装客户端了，而且更新前还能使用

**Comment by Setaria-hx** [comment]
> 字面意思，你需要确认你在模拟器上安装有碧蓝航线游戏客户端。 如果你玩的是不知名的渠道服，打开 console.bat 执行这个，其中 换成你的serial`<serial>`
> 
> ```
> adb -s <serial> shell
> ```
> 
> 然后执行
> 
> ```
> dumpsys package | grep "Package \["
> ```
> 
> 发结果出来

已经安装了客户端，是b服，在更新前还使用过

**Comment by LmeSzinc** [comment]
按我上面给的步骤执行命令，发结果出来看看

**Comment by qweiy811** [comment]
我玩的是渠道服，也遇到了这个问题，也是更新之前用过脚本，请大佬看看

这是显示的logs
INFO     21:47:31.879 │ DEVICE                                                     
INFO     21:47:31.880 │ [AdbBinary] D:\Game\AlasApp_0.4.2_full\AzurLaneAutoScript\t
         oolkit\Lib\site-packages\adbutils\binaries\adb.exe                        
INFO     21:47:31.883 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     21:47:31.884 │ <<< DETECT DEVICE >>>                                      
INFO     21:47:31.885 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     21:47:31.887 │ emulator-5554                                              
INFO     21:47:31.888 │ Current serial 127.0.0.1:5555 not found but paired device  
         emulator-5554 found. Using serial: emulator-5554                          
INFO     21:47:31.890 │ "emulator-5554" is a `emulator-*` serial, skip adb connect 
INFO     21:47:31.891 │ [AdbDevice] AdbDevice(serial=emulator-5554)                
INFO     21:47:31.893 │ <<< DETECT PACKAGE >>>                                     
INFO     21:47:31.894 │ Get package list                                           
INFO     21:47:31.970 │ Here are the available packages in device "emulator-5554", 
         copy to Alas.Emulator.PackageName to use it                               
INFO     21:47:31.972 │ No available packages on device "emulator-5554"            
CRITICAL 21:47:31.973 │ No AzurLane package found, please confirm AzurLane has been
         installed on device "emulator-5554"                                       
CRITICAL 21:47:31.974 │ Request human takeover    


以下按上面步骤的执行结果
D:\Game\AlasApp_0.4.2_full\AzurLaneAutoScript
>>>adb -s emulator-5554 shell
b0q:/ $ dumpsys package | grep "Package \["
  Package [com.github.uiautomator] (717d0a5):
  Package [com.android.cts.priv.ctsshim] (3a37c4):
  Package [com.android.internal.display.cutout.emulation.corner] (2850c30):
  Package [com.android.internal.display.cutout.emulation.double] (b66bb5c):
  Package [com.bluestacks.settings] (b523148):
  Package [com.location.provider] (9186011):
  Package [com.android.providers.telephony] (2a78f0d):
  Package [com.android.providers.calendar] (ffc0ec2):
  Package [com.android.providers.media] (6dd94d3):
  Package [com.google.android.onetimeinitializer] (a7c74eb):
  Package [com.google.android.ext.shared] (ad448b7):
  Package [com.android.wallpapercropper] (4dab953):
  Package [com.android.documentsui] (ccd97af):
  Package [com.android.externalstorage] (37ea9a):
  Package [com.android.htmlviewer] (c081ec1):
  Package [com.android.companiondevicemanager] (d95c24a):
  Package [com.android.providers.downloads] (de2d810):
  Package [com.github.uiautomator.test] (959d221):
  Package [com.bluestacks.filemanager] (7f80f68):
  Package [com.android.defcontainer] (b31e7ec):
  Package [com.android.providers.downloads.ui] (3cb0f09):
  Package [com.android.vending] (2695b1a):
  Package [com.android.pacprocessor] (df2486d):
  Package [com.android.simappdialog] (df7fe69):
  Package [com.android.internal.display.cutout.emulation.tall] (f891825):
  Package [com.android.certinstaller] (3eba3):
  Package [com.android.carrierconfig] (5d7dab4):
  Package [android] (600550e):
  Package [com.android.contacts] (b11047f):
  Package [com.android.camera2] (b5c99aa):
  Package [com.android.backupconfirm] (dc2a676):
  Package [com.bluestacks.BstCommandProcessor] (ee2ab2f):
  Package [com.lenovo.leos.appstore] (498f763):
  Package [com.bluestacks.nowgg] (33a0b6f):
  Package [com.bluestacks.piggy] (4a6c15a):
  Package [com.bluestacks.quest] (fdaf481):
  Package [com.android.provision] (b5ec314):
  Package [com.android.statementservice] (4eefc80):
  Package [com.bluestacks.launcher] (48760ac):
  Package [com.android.settings.intelligence] (9b5d17b):
  Package [com.android.calendar] (1460a57):
  Package [com.android.systemui.theme.dark] (99c5b62):
  Package [com.android.providers.settings] (c05653c):
  Package [com.android.sharedstoragebackup] (c7a4cdc):
  Package [com.android.printspooler] (8735624):
  Package [com.android.webview] (1883747):
  Package [com.android.inputdevices] (b8c92c5):
  Package [com.android.bips] (6a0199):
  Package [com.bluestacks.billing.service] (bd01e55):
  Package [com.android.onetimeinitializer] (6f105f8):
  Package [com.google.android.syncadapters.contacts] (22c89a4):
  Package [com.android.keychain] (8f0b41a):
  Package [com.android.chrome] (71a36a9):
  Package [com.android.printservice.recommendation] (f55693c):
  Package [com.android.dialer] (9addd28):
  Package [com.android.gallery3d] (5a24fd3):
  Package [com.google.android.gms] (b78cb4b):
  Package [com.google.android.gsf] (7619928):
  Package [android.ext.services] (e7a81be):
  Package [com.google.android.partnersetup] (8ad872d):
  Package [com.android.packageinstaller] (2a6e058):
  Package [com.android.carrierdefaultapp] (eb96617):
  Package [com.android.proxyhandler] (e44cb3):
  Package [com.android.inputmethod.latin] (e2abd14):
  Package [com.google.android.syncadapters.calendar] (e289641):
  Package [com.bilibili.blhx.lenovo] (fc53d21):
  Package [gg.now.billing.service] (f799c34):
  Package [com.google.android.gsf.login] (c55f7e6):
  Package [com.bluestacks.home] (d6dea9e):
  Package [com.android.wallpaper.livepicker] (fc03dcc):
  Package [com.bluestacks.gamecenter] (b996ab8):
  Package [com.google.android.backuptransport] (406d127):
  Package [com.android.storagemanager] (bbc7182):
  Package [com.android.bookmarkprovider] (f4423ce):
  Package [com.android.settings] (5cb1fd4):
  Package [com.taptap] (fc407f4):
  Package [com.android.calculator2] (643e001):
  Package [com.android.cts.ctsshim] (b0d7b3d):
  Package [gg.now.billing.service2] (bdb8e39):
  Package [com.android.vpndialogs] (786922c):
  Package [com.android.phone] (d27557d):
  Package [com.android.shell] (179ac72):
  Package [com.android.providers.blockednumber] (58558c3):
  Package [com.android.providers.userdictionary] (4a46540):
  Package [com.bluestacks.bsxlauncher] (151a12e):
  Package [com.android.location.fused] (58cc79):
  Package [com.android.deskclock] (50d72e1):
  Package [com.android.systemui] (2b21dbe):
  Package [com.android.traceur] (a9a5063):
  Package [com.google.android.gms.setup] (97eb1de):
  Package [com.google.android.play.games] (1400dea):
  Package [gg.now.accounts] (ec7d651):
  Package [com.android.wallpaperpicker] (13f2b24):
  Package [com.android.providers.contacts] (9dabe1f):
  Package [com.android.captiveportallogin] (f294e8e):

**Comment by qweiy811** [comment]
使用的是蓝叠模拟器

**Comment by LmeSzinc** [comment]
@qweiy811 联想渠道服已添加

**Comment by aaa6859** [comment]
我也遇到了这个问题，自己排查发现是UIAutoMator运行异常，重启一下UIAutoMator就好了
