### ISSUE TITLE
遠匯點作戰活動是否缺漏SP

### ISSUE THREAD

**Issue by bookbug666** [LmeSzinc/AzurLaneAutoScript#2645]
### 你的功能请求是否与问题有关？

看T/HT圖都上了但獨缺SP，是漏了嗎
```
═════════════════════════════════════════════════
                     EVENTSP                     
═════════════════════════════════════════════════
INFO     00:55:28.805 │                          
         ./campaign/event_20230525_cn/sp.py not  
         exists                                  
INFO     00:55:28.806 │ This event do not have   
         SP, skip                                
INFO     00:55:28.818 │ Bind task {'EventSp',    
         'EventGeneral', 'Alas', 'TaskBalancer', 
         'General'}                              
INFO     00:55:28.819 │ Save config              
         ./config\alas.json,                     
         EventSp.Scheduler.Enable=False          
INFO     00:55:28.823 │ Scheduler: End task      
         `EventSp`                               
INFO     00:55:28.824 │ [Server] jp              
INFO     00:55:28.837 │ Bind task {'Alas',       
         'General'}                              
INFO     00:55:28.839 │ No task pending          
INFO     00:55:28.840 │ [Task] Commission        
         (Enable, 2023-05-28 01:05:14)           
INFO     00:55:28.841 │ Bind task {'Commission', 
         'Alas', 'General'}                      
INFO     00:55:28.847 │ Wait until 2023-05-28    
         01:05:14 for task `Commission`          
INFO     00:55:28.848 │ Stay there during wait   
```

### 解决方案

加入SP關卡 ~~大老慢慢來就好了不急~~

### 其他内容

另外，手動開荒使用alas補三星會出現因為沒有TS/HTS關卡而報錯的情況
這方面不知道能否稍微改進(如果覺得無關我可以再開一個issue)

**Comment by LmeSzinc** [comment]
SP 图的每回合只能走两格的华容道想不出来了。

关卡自增中的一次性关卡应该加上判定，比如 T3 解锁了就跳过 TS1。

**Comment by guoh064** [comment]
> SP 图的每回合只能走两格的华容道想不出来了。
> 
> 关卡自增中的一次性关卡应该加上判定，比如 T3 解锁了就跳过 TS1。

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/50830808/12dea47c-a0e7-48c3-803f-84a08c979ae9)

来点笨办法，注意到精英走2格，小兵走1格：
<details>

1. 第一个舰队从E8到E6或从F8到F6
2. 第一个舰队从E6/F6到E7
此时D6和C7一个到E7和第一舰队**打架**（打完后剩余3个精英），另一个到D8（无论第二个舰队初始在E8还是F8）；
G6和H7分别到达F7和G8
3. 第一个舰队**踩**F7（打完后剩余2个精英）
4. 第二个舰队到F6
此时G8到F7和第一舰队**打架**（打完后剩余1个精英），D8到达E7或F8
5. 第二个舰队到F8或E7（与剩余一个精英错开），
6. 第一个舰队**踩**E7或F8（打完后不剩精英）
打完后刷新小兵，两个舰队在E7和F8上。
7. 第一个舰队去F6。
8. 第二个舰队去F7。
此时小兵前进，最近的变为C5，D5，G5，H5，C8，H8，G2到了G3
9. 第一个舰队**踩**G5。
10. 第二个舰队去F6。
此时小兵前进，H5到G5和第一个舰队**打架**，其余舰队都到不了F6，G3到了G4。
11. 第一个舰队**踩**G4。
上述总共7战打完后出boss。
12. 第二个舰队踩boss
随后小兵会动，但是已经没有影响了。

</details>

**Comment by bookbug666** [comment]
> SP 图的每回合只能走两格的华容道想不出来了。

~~看到了，痛苦機制，真的難蚌~~
