### ISSUE TITLE
后宅喂食添加“一天仅喂食一次”选项

### ISSUE THREAD

**Issue by AzusaYukina** [LmeSzinc/AzurLaneAutoScript#2647]
### 解决方案

在后宅喂食选项下添加该选项，以实现每天只喂一次完成每日任务/每周任务

**Comment by LmeSzinc** [comment]
这样做带来的收益是什么

**Comment by AzusaYukina** [comment]
实际上主要目的也就是完成每日和每周任务，因为目前的机制会快速消耗掉库存的食物，而使用了 Alas 之后很多时候后宅一层仅作为心情恢复加速使用，就导致现在开和不开都不是很合适的现状

**Comment by SaiCateDoan** [comment]
我猜一下，是不是后宅食物吃完了，每天的食物获取量不能稳定大于0，会出现每日任务有概率做不了的情况，是这样吗

**Comment by D9Lose** [comment]
> 这样做带来的收益是什么

赞同这个做法
1.一楼存在全部拉取回复心情值，而不是获取经验值的情况 （列如紧急委托）
2.一楼存在暂时没有船可练级（心智不足），但是没有一楼没有下船的情况。
3.在以上情况下，为了不浪费粮食使用，会关闭alas的喂食功能，但是这样同时每天每周的喂食任务也做不了。
4.新增次功能以后既可以避免以上情况，还可以不浪费粮食（情况2），不浪费（情况1的）经验，还可以完成任务。
