### ISSUE TITLE
今天碧蓝出击和科研界面更新了

### ISSUE THREAD

**Issue by lvzhenbo** [LmeSzinc/AzurLaneAutoScript#265]
**Describe the bug**
界面更新后，脚本无法自动点击

**To Reproduce**

**Expected behavior**

**Screenshots**
![屏幕截图 2020-12-22 171335](https://user-images.githubusercontent.com/32427677/102871267-2ce70000-4479-11eb-8a63-9c379d1e74dc.png)
![屏幕截图 2020-12-22 171348](https://user-images.githubusercontent.com/32427677/102871306-3b351c00-4479-11eb-8fc3-d5cdaa945b20.png)

**Log**
Post the entire log snippet that caused you to receive the error

**Comment by LmeSzinc** [comment]
已适配
