### ISSUE TITLE
打捞的meta556没有自动锁定

### ISSUE THREAD

**Issue by NEKOice** [LmeSzinc/AzurLaneAutoScript#2654]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

打捞的meta556没有自动锁定

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by ErosionSpark** [comment]
反正不能退役，无所谓啦

**Comment by GaoFeng807033914** [comment]
重复获取后会变成结晶，在仓库里

**Comment by SaiCateDoan** [comment]
![O7{SPQZH%UB Q _8H7 )UIU](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48789988/525fae0c-c019-4969-bfaa-02f62197b3ed)
