### ISSUE TITLE
安装完成后，运行Alas.exe无法正常弹出脚本窗口

### ISSUE THREAD

**Issue by cTrist** [LmeSzinc/AzurLaneAutoScript#2659]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

第一次用，当已经安装完毕无法正常弹出程序窗口。运行Alas.exe后最后窗口截图如图所示。任务管理器的后台应用会短暂显示多个alas，随后自行关闭

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![00f9915d4f85599906249514cfcff08](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/97895966/cacc6051-ea4c-4f98-af00-c7a2e121a279)
![Uploading 739ffa44424c4b67a1fa98e1a9901a2.png…]()

**Comment by SaarChaffee** [comment]
试试这个https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#alas-%E5%BC%95%E5%AF%BC%E5%AE%8C%E6%88%90%E5%90%8E%E9%97%AA%E9%80%80--alas-crashes-after-boot-completion-2481

**Comment by cTrist** [comment]
仍然会出现闪退的现象



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月30日(周二) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 安装完成后，运行Alas.exe无法正常弹出脚本窗口 (Issue #2659)




 
试试这个https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#alas-%E5%BC%95%E5%AF%BC%E5%AE%8C%E6%88%90%E5%90%8E%E9%97%AA%E9%80%80--alas-crashes-after-boot-completion-2481

**Comment by iceynano** [comment]
你电脑上有几个硬盘？如果有多个硬盘可以尝试把Alas丢到U盘或者其他硬盘上运行试试
