### ISSUE TITLE
舰队出击时若使用了高效作战指令书会导致程序长时间等待

### ISSUE THREAD

**Issue by orangetooth** [LmeSzinc/AzurLaneAutoScript#266]
![image](https://user-images.githubusercontent.com/52886035/102892319-a93e0b00-449a-11eb-8cb3-24d571ef03c6.png)

![image](https://user-images.githubusercontent.com/52886035/102892289-9cb9b280-449a-11eb-952e-b209ff917b0d.png)

点击立即前往后会再弹出一个确认窗口
希望能尽快加入对使用高效作战指令书的适配

**Comment by LmeSzinc** [comment]
现在没有这个弹窗了
