### ISSUE TITLE
“游戏内服务器”检测功能似乎失效

### ISSUE THREAD

**Issue by ArkhalisDragon** [LmeSzinc/AzurLaneAutoScript#2663]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Alas > Alas设置 > 游戏内服务器

游戏内服务器检测功能似乎已失效，我开启该功能之后报错：

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接'

### 如何复现

1. 前往 'Alas'
2. 点击 'Alas设置'
3. 滑动到 '游戏内服务器'
4. 出现问题

### 预期行为

no

### 相关 Logs

```Text
no
```

### 截图

no

### 还有别的吗？

no

**Comment by Horizon101011** [comment]
这里的10054是因为用户侧无法连接造成的，推测是网络供应商掐掉了
如果你不能正常使用该功能，可以考虑使用代理或关闭

**Comment by ArkhalisDragon** [comment]
> 这里的10054是因为用户侧无法连接造成的，推测是网络供应商掐掉了 如果你不能正常使用该功能，可以考虑使用代理或关闭

我已经关掉了，反正平时也用不着（
