### ISSUE TITLE
刷紧急委托功能会把100级非0破驱逐添加进队伍

### ISSUE THREAD

**Issue by coooooin** [LmeSzinc/AzurLaneAutoScript#2667]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [x] 我正在使用最新版的 Alas

### 描述你的问题

刷战力党，白鹰驱逐存在100级0破，1破，2破复制人，更换前排时未对突破星级进行判定，导致把非0破驱逐添加进队伍。目前个人暂时的处理方案只能先退役复制人重新拉未满级的，但未实际解决问题。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

想法是通过OCR判断星级，过滤非1星的舰娘

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/108573937/b005ba20-127e-4c80-a3fe-88ce6a2ce167)

**Comment by pein0saga** [comment]
这不是bug，本来规定的就是“可突破”的100级dd，没有限制死0破。

这只是你个人的需求，不要用bug标签

**Comment by ec7529a2** [comment]
OCR是用来识别字符的，不是用来识别图形的，在这里用不了
刷委托换船时已知船是白皮，那么只要简单看一下左起第二颗星亮不亮就行了，甚至还可以把识别位置写死

> 这不是bug，本来规定的就是“可突破”的100级dd，没有限制死0破。
> 
> 这只是你个人的需求，不要用bug标签

这是bug，这个任务的本意是用尽可能少的油过图，达到尽可能大的委托/油耗比例，当然要用0破船，游戏内筛选可突破只是因为没有直接筛选0破的选项，然后开发时忘记了有人刷战力冲榜这事，没多看一眼船有几颗星，所以把1破2破选上了

**Comment by pein0saga** [comment]
> OCR是用来识别字符的，不是用来识别图形的，在这里用不了 刷委托换船时已知船是白皮，那么只要简单看一下左起第二颗星亮不亮就行了，甚至还可以把识别位置写死
> 
> > 这不是bug，本来规定的就是“可突破”的100级dd，没有限制死0破。
> > 这只是你个人的需求，不要用bug标签
> 
> 这是bug，这个任务的本意是用尽可能少的油过图，达到尽可能大的委托/油耗比例，当然要用0破船，游戏内筛选可突破只是因为没有直接筛选0破的选项，然后开发时忘记了有人刷战力冲榜这事，没多看一眼船有几颗星，所以把1破2破选上了

那你让没有0破100级dd的人怎么刷委托？总不能让所有人都委屈求全绕着个人的需求改吧？ALAS是面向大众、解放双手的需求的，不是面向极少数的追求极致的群体。肯定要兼顾上方便易用性。0破1级练到足够强的0破100级dd，需要很多材料来强化。而手动特意去准备这个船也违反了方便易用的宗旨。（特别是对于第一次上手ALAS的新用户）

**Comment by ec7529a2** [comment]
> `刷紧急委托` 任务本身就是最大收益导向的，包括换1级后排省1油和换前排，这些都是为提高游戏收益而设计的。如果这些功能都变成可开关的，或者用非1油的前排，`刷紧急委托` 任务就没有了存在的意义，因为普通的 `主线图` 任务也可以做到，你应该使用普通的 `主线图` 任务来运行。

以上内容摘自LmeSzinc在#2476 的[comment](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2476#issuecomment-1503704316)

用3油耗刷委托是大众需求，因为额外魔方和钻石只有这一个来源；用4或更多油耗刷委托才是个人需求。
1级和100级的唯一区别是334本经验书。

所以刷委托会用1破和2破的船确实是一个影响收益的bug。

顺便补充一句，刷委托越少，钻石就越少，船坞就越少，就越影响刷委托的速度。

**Comment by EunHye12** [comment]
还需要吗？我加了个只上白皮1星的。

**Comment by coooooin** [comment]
> 还需要吗？我加了个只上白皮1星的。

需要的，现在还是有这问题

**Comment by EunHye12** [comment]
> > 还需要吗？我加了个只上白皮1星的。
> 
> 需要的，现在还是有这问题

那你有自己私人仓库吗？我没有权限加入这个项目的编辑。有的话给我个链接然后给我权限编辑我给你上传代码。
如果没有私人仓库的话就看B站有一篇攻略建立私人alas仓库。https://www.bilibili.com/read/cv24094352?spm_id_from=333.1007.0.0

**Comment by coooooin** [comment]
> > > 还需要吗？我加了个只上白皮1星的。
> > 
> > 
> > 需要的，现在还是有这问题
> 
> 那你有自己私人仓库吗？我没有权限加入这个项目的编辑。有的话给我个链接然后给我权限编辑我给你上传代码。 如果没有私人仓库的话就看B站有一篇攻略建立私人alas仓库。https://www.bilibili.com/read/cv24094352?spm_id_from=333.1007.0.0

我可能会建议你加alasQ群联系lme加入用户组获得编辑权限，因为搞私人仓库的话就只能是私人用了，我觉得这个问题应该也有其他战力党可能会遇到，只是他们的战力还刷没到我这程度或者和我一样用不搞白鹰dd满级复制人的方式去规避了

**Comment by coooooin** [comment]
> > > 还需要吗？我加了个只上白皮1星的。
> > 
> > 
> > 需要的，现在还是有这问题
> 
> 那你有自己私人仓库吗？我没有权限加入这个项目的编辑。有的话给我个链接然后给我权限编辑我给你上传代码。 如果没有私人仓库的话就看B站有一篇攻略建立私人alas仓库。https://www.bilibili.com/read/cv24094352?spm_id_from=333.1007.0.0

我可能会建议你加alasQ群联系lme加入用户组获得编辑权限，因为搞私人仓库的话就只能是私人用了，我觉得这个问题应该也有其他战力党可能会遇到，只是他们的战力还刷没到我这程度或者和我一样用不搞白鹰dd满级复制人的方式去规避了

**Comment by LmeSzinc** [comment]
你可以提交 Pull Requests，像这样 https://github.com/LmeSzinc/AzurLaneAutoScript/pulls
