### ISSUE TITLE
添加选项，使得遇到各种报错之后，延时半小时重启游戏和Alas任务

### ISSUE THREAD

**Issue by linwei5d** [LmeSzinc/AzurLaneAutoScript#2670]
### 你的功能请求是否与问题有关？

可能是个人设备和环境的问题（手机碧蓝＋手机docker），有时候跑着跑着侵蚀1，alas会点到右上角的暂停，这时候alas会不断尝试，最后报错，导致alas停下来需要人工重启，这样会降低收益

### 解决方案

查看exception.py 发现代码大都是pass，考虑能否在 “重启设置” 那边加一个按钮，使用户可以决定报错（主要是bug和human take over）时是否延迟任务半个小时并在新任务启动前重启游戏；；或者自动处理点到游戏暂停这种情况

### 其他内容

![Screenshot_2023-05-30-09-30-21-033_com kiwibrowser browser](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58349183/9fa45ffc-3185-443c-a66b-0e02c204c0ef)

此时手机截图为运行侵蚀1，但是点到了右上角的暂停，导致alas无法处理这种情况并停止

**Comment by LmeSzinc** [comment]
1. https://github.com/LmeSzinc/AzurLaneAutoScript/pull/1033#issuecomment-1213320420
2. 有问题应该发log和截图
