### ISSUE TITLE
手机如何远程访问alas

### ISSUE THREAD

**Issue by dmsxj3** [LmeSzinc/AzurLaneAutoScript#2678]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

本机可以通过浏览器访问127.0.0.1:22267访问alas，但是手机会显示网页无法打开，net err_connection_refused
如何用别的电脑或者手机访问alas呢

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
主页 - 远程控制
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/2d192998-4dd9-4e0d-8805-0c901e58daae)

**Comment by dmsxj3** [comment]
感谢但是ssh安装失败怎么办
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/101034739/49565210-533d-436d-95d4-9721569670a3)
win10  ssh安装失败

**Comment by dmsxj3** [comment]
我通过msi包安装后，但是alas显示未安装
![屏幕截图 2023-05-31 172115](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/101034739/d4a684b6-e847-441d-9bbd-6c4137961976)
![屏幕截图 2023-05-31 172216](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/101034739/0abed457-bd60-4482-a12d-aecb8606a72e)
![微信图片_20230531172408](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/101034739/84779a75-f4d1-47bb-9629-54eb7a7b6133)
![屏幕截图 2023-05-31 172454](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/101034739/d73188d5-3af9-4578-a07f-63f54b849168)

**Comment by dmsxj3** [comment]
> 如果装SSH失败可以试试内网穿透或者虚拟组网工具 贝锐的花生壳（虽然方便但是危险，不太建议）、蒲公英（安全但是每次用需要先打开软件）都可以，而且都是免费的

好的谢谢，我试试
