### ISSUE TITLE
大世界商店适配滚动条以及实装自定义过滤器

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#2681]
### 你的功能请求是否与问题有关？

如题，大世界商店于9月1日优化了港口商店逻辑。
这一改动过后，可以实装自定义过滤器，筛选自己想买的物品了，而不用担心维修箱和效能等垃圾物品占据刷新格子。

### 解决方案

1. 增加自定义过滤器

**Comment by SaiCateDoan** [comment]
还没优化呢，你先别急

**Comment by guoh064** [comment]
![cp-ph15an0dbzr654 (7)](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/50830808/5bec5a96-d1c2-49c1-ae63-e0708328620f)
你这么一说我还真不确定以前有没有滚动条了，但今天看了是有的

**Comment by guoh064** [comment]
Duplicate of #3067
