### ISSUE TITLE
Alas 首次安装错误  提示信息：fatal:open /dev/null or dup failed: No such file or directory

### ISSUE THREAD

**Issue by D9Lose** [LmeSzinc/AzurLaneAutoScript#2682]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

H盘符为980 PRO  正常接口 非移动硬盘盒子

Alas 首次安装错误  提示信息：fatal:open /dev/null or dup failed: No such file or directory

[allowe failure]，erroe_code 128
file not found ： ./.git/config
file not found ： ./.git/index
file not found ： ./.git/HEAD

### 如何复现

软件正常解压full_CN后双击alas.exe
屏幕cmd信息一闪而过 什么事情都没有发生
管理员运行后依然如此

### 相关 Logs

```Text
没有任何log
```

### 截图

![alas安装报错报告](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39555559/114a4699-4420-465c-93cc-19dbb6d2d4de)
![QQ图片20230601145006](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39555559/c3c35181-0ee7-4d6c-9c62-d886456df03e)

### 还有别的吗？

尝试过的方法
C:\Windows\System32\drivers\null.sys    替换过，无效
cmd下运行sfc /scannow                          修复过，无效
修改驱动状态                                            没有这个驱动，无法关闭开启
手动添加注册表 null                                无效

**Comment by iceynano** [comment]
`fatal:open /dev/null or dup failed` 这样的报错是null服务未启动导致的，简单的排除方法是在cmd下运行 `type NUL` 或者 `echo > nul` ，如果报错提示系统找不到文件或路径说明null服务未启动，正常情况应当无回显。

解决方法：确保 `%systemroot%\system32\drivers` 下有 `null.sys` ，然后检查注册表项 `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\Null`，它看起来应当像这个issue里所展示的：
https://github.com/itchio/itch/issues/2139#issuecomment-424002171
然后以管理员身份运行cmd，在cmd中依次运行以下命令：
`sc config null start= system`
`sc start null`
`sc query null`
此时null的STATE应当是RUNNING。结束相关后台程序后重新运行git，问题应该会解决。
PS: 此条回复是对于本issue已经生效的方案，现存档方便以后查看。
