### ISSUE TITLE
打开Alas一直显示更新失败

### ISSUE THREAD

**Issue by Bigorange11** [LmeSzinc/AzurLaneAutoScript#2686]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

几个小时前打开的时候还是正常可以打开的，后来关闭了一次再打开就一直提示更新失败了，重启了电脑也没有作用
![QQ截图20230601121838](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135260683/b071e257-c13c-4679-9ca6-0bf453135153)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474
