### ISSUE TITLE
2023/06/02：UPdate failed升级失败，程序无法正常启动，failure error_code：128

### ISSUE THREAD

**Issue by 96064409** [LmeSzinc/AzurLaneAutoScript#2687]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

显示升级失败，程序无法启动，删除重新安装后依然存在问题

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
"E:\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in E:/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: CODING 提示: team 3532843 is locked
fatal: unable to access 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git/': The requested URL returned error: 403
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default

Last command: "E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help
```

### 截图

![360截图20230602012327253](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/61927938/3f6aacb3-a44f-49db-8820-3dc3607b8d3e)

### 还有别的吗？

没有

**Comment by XFYPER** [comment]
暂时把config/deploy.yaml里的Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改成Repository: https://github.com/LmeSzinc/AzurLaneAutoScript.git
要挂梯子
估计抽风了

**Comment by LmeSzinc** [comment]
双击打开 console.bat ，执行：
```
python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git
```
再重新打开 Alas。

注意：这是托管在群友的小水管上的，**不要通过这个地址完整下载 Alas**。

**Comment by l497996153** [comment]
> 暂时把config/deploy.yaml里的Repository: [https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改成Repository](https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git%E6%94%B9%E6%88%90Repository): https://github.com/LmeSzinc/AzurLaneAutoScript.git 要挂梯子 估计抽风了

换完之后在这步出问题了请问怎么解决？
==================== UIAUTOMATOR2 INIT ====================
[I 230601 15:01:17 init:156] uiautomator2 version: 2.16.17
[I 230601 15:01:17 init:372] Install minicap, minitouch
[D 230601 15:01:17 init:59] Use cached assets: C:\Users\liuzh\Downloads\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2cache\cache\minitouch-69336c8f34\minitouch
[D 230601 15:01:17 init:238] Push to /data/local/tmp/minitouch:0755
[D 230601 15:01:17 init:256] apk-debug package-info: {'package_name': 'com.github.uiautomator', 'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 5, 29, 22, 59, 50), 'last_update_time': datetime.datetime(2023, 5, 29, 22, 59, 50), 'signature': '4b76292'}
[D 230601 15:01:17 init:257] apk-debug-test package-info: {'package_name': 'com.github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags': ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2023, 5, 29, 22, 59, 51), 'last_update_time': datetime.datetime(2023, 5, 29, 22, 59, 51), 'signature': '4b76292'}
[I 230601 15:01:17 init:390] Already installed com.github.uiautomator apks
[D 230601 15:01:17 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 230601 15:01:17 init:296] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 230601 15:01:17 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 230601 15:01:17 init:350] Check atx-agent version
[D 230601 15:01:17 init:359] Forward: local:tcp:58927 -> remote:tcp:7912
[D 230601 15:01:18 init:359] Forward: local:tcp:58927 -> remote:tcp:7912
[D 230601 15:01:18 init:362] atx-agent version 0.10.0
[D 230601 15:01:18 init:365] device wlan ip: 10.0.2.15
Successfully init AdbDevice(serial=127.0.0.1:7555)

显示成功init之后紧接着print出了traceback然后就是这个error
    raise AdbError(self.read_string_block())
adbutils.errors.AdbError: closed

**Comment by Agnes4m** [comment]
同样的问题，更换Repository解决

**Comment by l497996153** [comment]
uiautomator2的repository在哪改啊？deploy.yaml里面没找到。
目前把InstallUiautomator2设置成false了，不重装就可以启动

**Comment by Drink1ark** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/89714889/1c2aae03-8f01-4fed-96f4-6def2077738c)

**Comment by Drink1ark** [comment]
还是不行

**Comment by AbyssAzrael** [comment]
> 双击打开 console.bat ，执行：
> 
> ```
> python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git
> ```
> 
> 再重新打开 Alas。
> 
> 注意：这是托管在群友的小水管上的，**不要通过这个地址完整下载 Alas**。

还是不行
![error](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/82253519/110ef17c-7e6f-4497-a1c7-c6763766e321)

**Comment by Drink1ark** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/89714889/5fc7bd7c-d9b3-48a7-9b7b-3da0c0453431)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/89714889/c808228d-5ea4-410d-b713-8aecad2ee8d8)
还是不行，难崩

**Comment by ZK-0001** [comment]
> 暂时把config/deploy.yaml里的Repository: [https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改成Repository](https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git%E6%94%B9%E6%88%90Repository): https://github.com/LmeSzinc/AzurLaneAutoScript.git 要挂梯子 估计抽风了

我用这个方案更新成功了

**Comment by Xiaer-cloud** [comment]
改仓库之后能进去了，难崩

>

**Comment by SaarChaffee** [comment]
> > 双击打开 console.bat ，执行：
> > ```
> > python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再重新打开 Alas。
> > 注意：这是托管在群友的小水管上的，**不要通过这个地址完整下载 Alas**。
> 
> 还是不行 ![error](https://user-images.githubusercontent.com/82253519/242770580-110ef17c-7e6f-4497-a1c7-c6763766e321.png)



> ![image](https://user-images.githubusercontent.com/89714889/242771161-5fc7bd7c-d9b3-48a7-9b7b-3da0c0453431.png) ![image](https://user-images.githubusercontent.com/89714889/242771210-c808228d-5ea4-410d-b713-8aecad2ee8d8.png) 还是不行，难崩

改成https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git

**Comment by Drink1ark** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/89714889/05fd5410-60ba-4cae-a619-8855a919ec37)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/89714889/567350d4-59d1-47b4-a1cd-0f3da62cc807)
都试过了

**Comment by Z-SHUO6260** [comment]
刚才我改完Repository之后把加速github什么的代理全都关了，然后就能正常更新了，你可以试试

**Comment by SaarChaffee** [comment]
如果使用`https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git`显示failure error code：128的，
改成`https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git`

**Comment by Drink1ark** [comment]
可以更新了但是更新一半闪退

**Comment by ningmenggouqicha** [comment]
> 如果使用`https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git`显示失败错误码：128的， 改成`https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git`

感谢老哥，解决了，改完关掉梯子重新启动就好了

**Comment by SaarChaffee** [comment]
> > 如果使用`https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git`显示失败错误码：128的， 改成`https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git`
> 
> 感谢老哥，解决了，改完关掉梯子重新启动就好了

有梯子的直接用gh的链

**Comment by Drink1ark** [comment]
万分感谢

**Comment by wEuphorIA** [comment]
感谢

**Comment by sylarlyn** [comment]
> 有梯子的，把config/deploy.yaml里的Repository: [https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改成Repository](https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git%E6%94%B9%E6%88%90Repository): [ https://github.com/LmeSzinc/AzurLaneAutoScript.git](https://github.com/LmeSzinc/AzurLaneAutoScript.git)

按照你的的方法修改之后就行了
