### ISSUE TITLE
ALAS无法启动

### ISSUE THREAD

**Issue by sd3422524** [LmeSzinc/AzurLaneAutoScript#2693]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

fatal: unable to access 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git/': The requested URL returned error: 403

我尝试上了一下这个代码仓库，提示要求登录，大概是这个原因吧。
看样子是又要更换新仓库了？ : )
期待修复，谢谢！

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![$LO(O`}B (B54TVF6X_3GP2](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/79265386/20d9e547-d2b5-4fb3-b530-8f8033689f1b)

**Comment by sadwwwwwwww** [comment]
我也

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474
