### ISSUE TITLE
启动alas时更新失败

### ISSUE THREAD

**Issue by VANNIANSHOU** [LmeSzinc/AzurLaneAutoScript#2694]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动alas时更新失败，疑似是库挂了？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

<img width="1280" alt="屏幕截图 2023-06-02 082626" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129166512/314b9ce0-475c-4a04-b567-7a3c9f6bd643">

**Comment by AshenMo** [comment]
原来不是我一个人的问题啊

**Comment by appleapple802** [comment]
+1

**Comment by scp-048** [comment]
+1更新失败

**Comment by lackoxy** [comment]
+1

**Comment by VictorNortonXue** [comment]
+1

**Comment by 2101103665** [comment]
原来是bug

**Comment by yuki-sai** [comment]
把config/deploy.yaml文件下的Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改回github就行了，就是改成Repository:https://github.com/LmeSzinc/AzurLaneAutoScript，多试几次就能更新了，他现在这个地址点进去要登陆，估计是这个原因导致更新不了

**Comment by junbluedd** [comment]
网好切换github源就可以更新了

**Comment by Arclight-Beauty** [comment]
> 把config/deploy.yaml文件下的Repository: [https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git改回github就行了，就是改成Repository:https://github.com/LmeSzinc/AzurLaneAutoScript，多试几次就能更新了，他现在这个地址点进去要登陆，估计是这个原因导致更新不了](https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git%E6%94%B9%E5%9B%9Egithub%E5%B0%B1%E8%A1%8C%E4%BA%86%EF%BC%8C%E5%B0%B1%E6%98%AF%E6%94%B9%E6%88%90Repository:https://github.com/LmeSzinc/AzurLaneAutoScript%EF%BC%8C%E5%A4%9A%E8%AF%95%E5%87%A0%E6%AC%A1%E5%B0%B1%E8%83%BD%E6%9B%B4%E6%96%B0%E4%BA%86%EF%BC%8C%E4%BB%96%E7%8E%B0%E5%9C%A8%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E7%82%B9%E8%BF%9B%E5%8E%BB%E8%A6%81%E7%99%BB%E9%99%86%EF%BC%8C%E4%BC%B0%E8%AE%A1%E6%98%AF%E8%BF%99%E4%B8%AA%E5%8E%9F%E5%9B%A0%E5%AF%BC%E8%87%B4%E6%9B%B4%E6%96%B0%E4%B8%8D%E4%BA%86)

感谢，问题解决了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474

**Comment by wang-zh** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39694902/2b971395-e0d1-4bf5-aadf-5954c734f0a7)
我的还是不行
