### ISSUE TITLE
[ failure ], error_code: 128

### ISSUE THREAD

**Issue by EVOLUTION-CIAO** [LmeSzinc/AzurLaneAutoScript#2695]
### 在提问之前...

- [x] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

==================== FETCH REPOSITORY BRANCH ====================
"H:/GAME HELPER/Alas/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: CODING 提示: team 3532843 is locked
fatal: unable to access 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git/': The requested URL returned error: 403

### 如何复现

1. 按提示修改deploy.yaml（许久前）
2. 今天打开开始显示此错误
3. GH上又下了AlasApp_0.4.2_fullcn，发现deploy.yaml不用修改
4. 打开仍旧显示此错误出现问题

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/97382367/8f062c11-4be8-4ef6-9534-7dabd9839024)

**Comment by White-Armor** [comment]
之前不是有一个办法吗：
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474

**Comment by EVOLUTION-CIAO** [comment]
> 之前不是有一个办法吗： [#2687 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474)

更换完显示
fatal: unable to access 'https://github.com/LmeSzinc/AzurLaneAutoScript.git/': SSL certificate problem: unable to get local issuer certificate
[ failure ], error_code: 128

**Comment by EVOLUTION-CIAO** [comment]
> 之前不是有一个办法吗： [#2687 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474)

如果用另一个方法
[双击打开 console.bat ，执行：
python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git]
它则会加载一会然后显示
fatal: unable to access 'https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git/': Failed to connect to git.saarcenter.com port 443: Timed out
[ failure ], error_code: 128

**Comment by SaarChaffee** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1573064912

**Comment by lostprobe99** [comment]
可以试试git@github.com:LmeSzinc/AzurLaneAutoScript.git

**Comment by EVOLUTION-CIAO** [comment]
> 可以试试[git@github.com](mailto:git@github.com):LmeSzinc/AzurLaneAutoScript.git

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/97382367/7537bd5c-d325-45ee-bba0-881f15cc5c91)
但是我type不了

**Comment by EVOLUTION-CIAO** [comment]
OK
我修改成
https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git
就正常了

**Comment by EVOLUTION-CIAO** [comment]
> > [#2687 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1573064912)
> 
> OK 我修改成 https://e.coding.net/saarcenter/alas/AzurLaneAutoScript.git 就正常了

现在又不行了

**Comment by iceynano** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474

**Comment by EVOLUTION-CIAO** [comment]
额...好吧，这次在console.bat 输入
python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git
又好了，但这个稳定吗？

**Comment by iceynano** [comment]
我的想法是 你能上github了 何不为alas设置代理直接用github的仓库 这些在config/deploy里都可以找到

**Comment by EVOLUTION-CIAO** [comment]
> 我的想法是 你能上github了 何不为alas设置代理直接用github的仓库 这些在config/deploy里都可以找到

可能是因为我是那种按照初始设定没问题的就不再深入的问题吧

**Comment by iceynano** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/34570144/b36c9704-3a69-4af6-aeba-1dffdeffe53f)
设置gitproxy 端口就填你的fq工具所使用的端口 比如 clash默认的就是7890
