### ISSUE TITLE
在云服务器上基于frp内网穿透的远程控制功能无法生成url

### ISSUE THREAD

**Issue by ChinoJunko** [LmeSzinc/AzurLaneAutoScript#2697]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

特征为显示运行中与服务器离线交替出现，且处于运行中状态时也无法生成URL
![`M5A_935XNK BU@W_Q3441Z](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/64834652/1e0b39f3-125c-4d5b-90a3-6460d257cb4a)
服务器环境为windows server 2012 R2
在服务器上运行frp服务端和客户端的配置如下：
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/64834652/58837ae8-304e-434a-be8b-68eae60f8503)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/64834652/f76b7591-d3db-45c1-9944-7e778b5d6e81)
对alas的deploy.yaml修改仅有三处：
1. EnableRemoteAccess: true
2. SSHServer: 114.5.1.4:6666
3. Webui密码
其中114.5.1.4为服务器公网IP

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by SaarChaffee** [comment]
使用frp远程控制的话，Alas的配置文件仅需在`Webui: Password`设置密码。frp的配置可以参考如下：
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53519746/585f1b99-e144-4417-b9ec-7ebd7df99ae1)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53519746/5e2f84b0-a9bd-4bbb-9547-74cdcf2259fb)

**Comment by ChinoJunko** [comment]
OK，已解决。但是server_addr处填写的应该是0.0.0.0
