### ISSUE TITLE
请检查配置/部署中的部署设置。并重新打开Alas.exe

### ISSUE THREAD

**Issue by huaizhus** [LmeSzinc/AzurLaneAutoScript#2699]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Last command: "E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help

### 相关 Logs

```Text
Last command: "E:/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy. yaml and re-open Alas.exe
Take the screenshot of entire window if you need help
```

### 截图

![捕获](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135334081/ee06e2f9-538e-4c57-becf-23c181fdc10f)

**Comment by rookie-1000** [comment]
找到console.bat      输入  python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git  回车

**Comment by Nagami-Suzuka** [comment]
中国のGitサーバーがブロックされたため、いま元のアドレスがアクセスでくなくなった。
ルートディレクトリでconsole.batを実行し、下記のコマンドを入力してください
`python -m deploy.set Repository=https://git.saarcenter.com/LmeSzinc/AzurLaneAutoScript.git`
