### ISSUE TITLE
Repository: 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git'

### ISSUE THREAD

**Issue by shenshiqiSSQ** [LmeSzinc/AzurLaneAutoScript#2706]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Repository: 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git'这个在国内被锁住了访问不了，建议用gitee

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

没有了

### 相关 Logs

```Text
没有了
```

### 还有别的吗？

没有了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474
