### ISSUE TITLE
仓库也改了，安装地点也改了，还是这个弹窗

### ISSUE THREAD

**Issue by wewieai** [LmeSzinc/AzurLaneAutoScript#2708]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

"D:\AlasApp_0.4.2_cn\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env no need to patch
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
uiautomator2 is not installed skip patching
==================== SHOW DEPLOY CONFIG ====================
Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
remote: CODING 提示: team 3532843 is locked
fatal: unable to access 'https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git/': The requested URL returned error: 403
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Repository: https://e.coding.net/llop18870/alas/AzurLaneAutoScript.git
PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
Language: zh-CN
Rest of the configs are the same as default

Last command: "D:/AlasApp_0.4.2_cn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Mythosy** [comment]
把config/deploy.yaml文件里，autoUpdate后面的true改成flase就行了，以后记得改回来就行

**Comment by cloudchina** [comment]
看这个Repository没有改吧

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572526474
