### ISSUE TITLE
启动abd服务时导致mumu模拟器崩溃

### ISSUE THREAD

**Issue by CastleYu** [LmeSzinc/AzurLaneAutoScript#2715]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

前天安装了mumu12作为玩别的游戏用，后面在原来的mumu6上使用alas时模拟器出现崩溃。

### 如何复现

没有找到明确的稳定复现方法，有时候在运行调度器的任意一段时间后会莫名崩溃，有时候mumu会在启动后立刻崩溃。
**其中在alas启动时的'启动adb服务'阶段出现模拟器崩溃的情况较多**

### 截图

![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/61407907/b3037656-8061-4701-9984-36cbbaad4d5d)

[mumu错误报告.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11645309/mumu.zip)

### 还有别的吗？

开始有一段时间mumu6和mumu12同时开启的情况下使用了alas和maa，后来发现adb自动检测可能会被mumu12抢走后面就单独开一个了

**Comment by SaarChaffee** [comment]
mumu6 和 mumu12 不能同时开，这是 mumu 的历史遗留问题，mumu12 能同时用自己的端口以及第一个实例可以用旧端口 7555。有多开需求推荐只使用 mumu12 而不是 6 和 12 一起开。

**Comment by CastleYu** [comment]
> mumu6 和 mumu12 不能同时开，这是 mumu 的历史遗留问题，mumu12 能同时用自己的端口以及第一个实例可以用旧端口 7555。有多开需求推荐只使用 mumu12 而不是 6 和 12 一起开。

我现在是只开了mumu6也会导致崩溃，那我现在只能一起切换到mumu12上？

**Comment by SaarChaffee** [comment]
> 

看看 Alas 的截图配置，mumu6 是用不了 DroidCast 以及 DroidCast_raw 的。然后 mumu6 已经很老了，建议换到 12 上。

**Comment by CastleYu** [comment]
嗯……性能检测后自动选择了DroidCast_raw ，我试试换个截图方式

**Comment by CastleYu** [comment]
启动即崩溃，alas根本没动，感觉应该是某次导致了非alas的问题发生，我还是去转移到12上了

**Comment by CastleYu** [comment]
换用mumu12后依然出现崩溃，最终解决方式居然是把火绒和联想电脑管家关了。。。

**Comment by D9Lose** [comment]
> 换用mumu12后依然出现崩溃，最终解决方式居然是把火绒和联想电脑管家关了。。。

联想笔记本确实有这个问题，用mm系列需要卸载联想电脑管家

**Comment by CastleYu** [comment]
> > 换用mumu12后依然出现崩溃，最终解决方式居然是把火绒和联想电脑管家关了。。。
> 
> 联想笔记本确实有这个问题，用mm系列需要卸载联想电脑管家

不排除这种可能，但是我这样后来又崩了（）
最后现在让我稳定不崩的方式居然是把VMware服务关了。。。
