### ISSUE TITLE
10-2 BOSS出现后无法识别其位置

### ISSUE THREAD

**Issue by FinchOrigin** [LmeSzinc/AzurLaneAutoScript#2719]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

开荒 10-2 时，在BOSS出现alas后无法识别其位置导致报错

### 如何复现

1. alas主线图配置 10-2
2. 等待BOSS出现
3. 出现问题

### 预期行为

正确识别BOSS位置并进入BOSS战

### 相关 Logs

```Text
日志过长，Github禁止创建Issue，麻烦下载下方的 1685927646883.zip 获取日志详情

Comment is too long (maximum is 65536 characters)
```

### 截图

[1685927646883.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11647879/1685927646883.zip)

**Comment by LmeSzinc** [comment]
发现了沉睡 3 年的 typo

**Comment by FinchOrigin** [comment]
10-2已经开荒完成了，这个问题出现的概率似乎不大，可能只有舰队图标和BOSS图标有重合的时候才复现吧。我现在在挂12-4练船顺带炼金，老咸鱼刚回坑比较缺油缺物资......，暂时没法验证修复结果

**Comment by FinchOrigin** [comment]
不在复现
