### ISSUE TITLE
战斗结束后确认点击过多（Too many clicks after combat）

### ISSUE THREAD

**Issue by 6U-U9** [LmeSzinc/AzurLaneAutoScript#272]
**Describe the bug**

在演习结束后有大概率进入“军需补给”界面
开启辅助点击后，大世界战斗结束后会点击到地图，导致舰队移动
可能在每次战斗后都存在过多点击的问题

**To Reproduce**
演习结束后进入“军需补给”界面很容易复现

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/53718342/102958563-28bdef80-4518-11eb-9fc8-e22b0f1b6196.mp4

**Log**
蓝叠模拟器 4.230
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5733215/log.txt)

**Comment by LmeSzinc** [comment]
已修复演习结束后会进入军需补给的问题, 大世界会有单独的辅助点击功能.
