### ISSUE TITLE
在队列设置中添加改顺序功能

### ISSUE THREAD

**Issue by deAlue** [LmeSzinc/AzurLaneAutoScript#2721]
### 你的功能请求是否与问题有关？

现在收获总是在队列最开始，这样导致队列最后一个任务结束后打到的每日奖励，每周奖励领不到。

### 解决方案

希望可以添加一个拖动更改顺序的功能，可以自定义任务执行顺序，让活动图和刷关先打，打完再统一收获奖励，做委托科研之类的。

**Comment by D9Lose** [comment]
所有调度器顺序，均经过长时间的验证考验，已经证实可以长时间运行7*24X30天以上


你应该知道的
- Alas自己会不定期收获委托，和完成任务，所以你的第一句就不成立。


你应该做的
- 把你的账号调整到正常范围，比如（按照github的游戏设置 对照修改 。满油满物资去浪费掉，设置好meta阵容，吧所有的强制教程点掉。）
- 调整号alas设置、正确设置心情值、把你想要的调度器添加。点击启动，就可以了。


你不应该做的事情
-脱离alas的使用场景，自己发明创造玩法。胡乱设置心情值（特别是无视心情），导致后面的调度器被堵塞。
- 非7*24小时运行，alas的运行逻辑按照7X24小时运行开发，所有问题在这个运行条件下 都有相应的解决方案
我个人猜测你是那种打开alas把所有能关都给关掉的代练哥，或者萌新。只运行了几分钟就开始痛诉这里，没有运行，哪里没有运行。 
（原因是长时间运行 他自己知道去收菜去完成任务，说变了就是你脱离使用范围了）

**Comment by TarringFox** [comment]
上云.jpg
