### ISSUE TITLE
希望沉船后可以换队打完关卡

### ISSUE THREAD

**Issue by ryzalin** [LmeSzinc/AzurLaneAutoScript#2722]
### 你的功能请求是否与问题有关？

现在的ALAS在一队沉船后会报错，过一段时间后会重启然后撤退。
希望有个选项可以在沉船后换2队继续打完关卡，这样不会太亏。

### 解决方案

希望有个选项可以在沉船后换2队继续打完关卡，这样不会太亏。

**Comment by q310812350** [comment]
> 相反地，现在的主流玩法是一队全清，二队只提供跨队支援不出击。让二队出击反而增加了不必要的体力消耗。

确实大部分老玩家是这样的，但对于我这样入坑时间比较短的玩家来说，跨队不齐，上两队低耗队打起来比较稳定，因此如果有个可选项就好了。
当然，如果修改起来比较麻烦的话就算了，确实可能需求的人很少。

**Comment by Cyan-grey** [comment]
> > 相对地，现在的主流玩法是一队全清，二队只提供跨队支援不出击。让二队出击而增加了不必要的体力消耗。
> 
> 确实大部分分老玩家是这样的，但是对于我这样进入坑时间比短的玩家来说，跨队不齐，上两队低队打起来比比稳定，因此如果有一个可选的项目就好了。 当然，如果修改起来比比较麻痹的话就算了，确实可能需要的人很少。

那你这个就属于故意沉船的打法了，那这个得算进“粪提”了吧，作者还是比较反感的（所以辅助里面没有红脸出击的选项），刚玩还是不推荐这样，没实力组出成品低耗还是推荐上满去D3练级

**Comment by q310812350** [comment]
> > > 相对地，现在的主流玩法是一队全清，二队只提供跨队支援不出击。让二队出击而增加了不必要的体力消耗。
> > 
> > 
> > 确实大部分分老玩家是这样的，但是对于我这样进入坑时间比短的玩家来说，跨队不齐，上两队低队打起来比比稳定，因此如果有一个可选的项目就好了。 当然，如果修改起来比比较麻痹的话就算了，确实可能需要的人很少。
> 
> 那你这个就属于故意沉船的打法了，那这个得算进“粪提”了吧，作者还是比较反感的（所以辅助里面没有红脸出击的选项），刚玩还是不推荐这样，没实力组出成品低耗还是推荐上满去D3练级

不是啊，因为低耗确实有随机性，有可能沉船。比如80%的概率一队3油能打穿，20%概率一队会沉船但二队4油继续打肯定能打过，那对于我来说最优解肯定是先一队3油看看能不能打穿，如果打不穿再换队继续打到底呀。
这与刚玩不刚玩没关系，完全是看彩船跨队齐不齐，初始号和自建号同样玩一年，跨队的差距很可能就是天差地别。
另外辅助里是有红脸出击的选项的。
以及确实是小众需求，如果比较麻烦就算了吧。

**Comment by EunHye12** [comment]
我可以帮你弄。但不能改在alas官方上面。你弄个自用alas仓库，然后给我开发者权限。我添加你这个低耗1队沉船换2队打完加上去
