### ISSUE TITLE
ssh: Could not resolve hostname git: Name or service not known

### ISSUE THREAD

**Issue by xingyedekong** [LmeSzinc/AzurLaneAutoScript#2726]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

进不去，重下alas还是进不去

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![QQ图片20230607175211](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135824425/379ed9f4-8fdb-4042-90da-dae53cc0c7b2)

**Comment by babytotdd** [comment]
Repository: https://github.com/LmeSzinc/AzurLaneAutoScript 
改回来就可以了

**Comment by iceynano** [comment]
仓库地址有其他字符，手打重新编辑一遍

**Comment by iceynano** [comment]
请先阅读[文档](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#编辑安装设置)
