### ISSUE TITLE
2023-6-8：启动alas更新时报错：fatal: read error: Invalid argument error_code: 128

### ISSUE THREAD

**Issue by deAlue** [LmeSzinc/AzurLaneAutoScript#2736]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在启动alas时，更新报错error_code: 128，fatal: read error: Invalid argument。参考过之前Invalid argument的解决方法，在console.bat使用python-gui.py启动会报错：Git fetch failed。重置dns hosts都没用。并且这个问题在我的**另一台电脑上也有出现**。

### 如何复现

1. 运行alas.exe
2. 出现问题

### 截图

![无标题](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/110904929/5e661a0d-e418-437a-8bf5-83fcbced8499)

**Comment by blood-shadow-1201** [comment]
去b站搜cookmaker233，试试看他专栏里的方案

**Comment by inory121** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2687#issuecomment-1572516052 改仓库地址或者
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2708#issuecomment-1574790794 直接跳过更新

**Comment by deAlue** [comment]
好的已经解决，解决办法：**在steam++加速github**，加速方式为**DNS驱动拦截模式**。
_（有时比较玄学关掉加速器就能连）_

**Comment by under8ground** [comment]
steam++没看到效果，创建私有源码仓库前面试过了可以 
现在又不行了
