### ISSUE TITLE
刷紧急委托无法更换后排

### ISSUE THREAD

**Issue by Mirageorwhatever** [LmeSzinc/AzurLaneAutoScript#2737]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在本次更新前，刷紧急委托功能运行正常。
更新后，在使用刷紧急委托功能时，当需要更换后排时，alas会在角色选择界面，重复点击某个位置，直到出现“过多点击”报错。
在最后一次报错中，alas已经选好了更换的角色，但依然无法正确的点击确定按钮，
猜测是这次更新又动了UI。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2023-06-08_20-55-12-130147](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/84392723/68debd6a-0082-4b98-9671-5641f42e4de7)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11690282/log.txt)

**Comment by LmeSzinc** [comment]
更新 Alas
