### ISSUE TITLE
美服通用商店卡在家园

### ISSUE THREAD

**Issue by amyburden** [LmeSzinc/AzurLaneAutoScript#2746]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

运行通用商店任务卡在家园

### 如何复现

运行通用商店

### 相关 Logs

```Text
INFO     12:43:53.947 │ Scheduler: End task `ShopFrequent`                         
CRITICAL 12:43:53.948 │ Task `ShopFrequent` failed 3 or more times.                
CRITICAL 12:43:53.949 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 12:43:53.951 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 12:43:53.952 │ Request human takeover                                     
INFO     12:43:53.953 │ No provider specified, skip sending
```

**Comment by LmeSzinc** [comment]
> 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。

**Comment by amyburden** [comment]
![2023-06-09_12-43-43-533122](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/9306303/29bea160-a8f6-4679-9109-6be50f42fb32)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11713669/log.txt)

**Comment by LmeSzinc** [comment]
更新你的Alas

**Comment by amyburden** [comment]
已经是最新的了依旧有问题

**Comment by amyburden** [comment]
═══════════════════════════════════════════════════════════════════════════════════
                                   SHOPFREQUENT                                    
═══════════════════════════════════════════════════════════════════════════════════
INFO     08:20:16.941 │ <<< UI ENSURE >>>                                          
INFO     08:20:16.942 │ UI get current page                                        
INFO     08:20:16.950 │ [UI] page_main                                             
INFO     08:20:16.951 │ Goto page_munitions                                        
INFO     08:20:16.953 │ <<< UI GOTO PAGE_MUNITIONS >>>                             
INFO     08:20:17.121 │ Page switch: page_main -> page_dormmenu                    
INFO     08:20:17.124 │ Click ( 559,  689) @ MAIN_GOTO_DORMMENU                    
INFO     08:20:18.019 │ Page switch: page_dormmenu -> page_academy                 
INFO     08:20:18.021 │ Click ( 314,  313) @ DORMMENU_GOTO_ACADEMY

**Comment by amyburden** [comment]
game remain in the academy

**Comment by amyburden** [comment]
![2023-06-11_08-23-17-983809](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/9306303/fda861f9-79b8-4537-a40c-713c8ed5bc24)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11714978/log.txt)

**Comment by amyburden** [comment]
我知道了，github那个地址默认不是正常github导致没有更新成功，更改了config里面的github url就可以了
