### ISSUE TITLE
日服战术学院无法选择新角色

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#2752]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

开始战术学院任务后，在选择角色界面无法选择新角色

[错误.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11713596/default.zip)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

简中服在执行战术学院任务时，即便标记了常用，也无法选择等级为1的角色作为技能训练对象

**Comment by LmeSzinc** [comment]
#2750
