### ISSUE TITLE
主线图中使用周回模式点击异常

### ISSUE THREAD

**Issue by gy1041** [LmeSzinc/AzurLaneAutoScript#2773]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [ ] 我正在使用最新版的 Alas

### 描述你的问题

问题如标题所述

### 如何复现

1. 勾选主线图中使用周回模式
2. 点击 启用该功能
3. 调度器启动
4. 出现问题

### 预期行为

alas重复点击，无法正常使用

### 截图

![IMG_20230616_095721](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/74300555/716671ae-e707-4fc6-b7f9-620ce0db8e1d)

**Comment by LmeSzinc** [comment]
> 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
