### ISSUE TITLE
请求增加定时启动的功能

### ISSUE THREAD

**Issue by TallinnMelody** [LmeSzinc/AzurLaneAutoScript#2784]
### 解决方案

由于寝室会定时断网，程序会出现错误而停止运行，想问一下能不能增加一个定时启动的功能，设定程序在每日的固定时间重新运行，以免去每日早上点击的烦恼。
（或者有其他程序外的方法也可以，谢谢）

**Comment by TallinnMelody** [comment]
j

**Comment by LmeSzinc** [comment]
设置 `Alas设置` - `模拟器设置` - `游戏内服务器` 就可以了。Alas 能在 电脑无网络连接 或者 游戏服务器维护 的时候保持等待，并在 电脑网络连接恢复 或者 游戏服务器维护结束 的时候，自动登录游戏并恢复运行。

**Comment by TallinnMelody** [comment]
感谢，我之前没注意到这个功能
