### ISSUE TITLE
请求更新台服活动

### ISSUE THREAD

**Issue by NightOwlHaohao** [LmeSzinc/AzurLaneAutoScript#2797]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

活动目前是复刻峡湾间的反击,但alas还是冷誓光庭

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![屏幕截图 2023-06-22 201504](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/25108395/e1ae0ea8-1ad1-4701-9aed-5ae7a980b2c4)

**Comment by LmeSzinc** [comment]
台服没人玩也没人维护了，等路过的有缘人吧

**Comment by peacock127** [comment]
QQ 也再等這個更新的說
還以為是複刻就沒人更了

**Comment by ianlee0800** [comment]
能的話我可以協助後續更新
