### ISSUE TITLE
似乎mumu12能多开了？

### ISSUE THREAD

**Issue by defencer** [LmeSzinc/AzurLaneAutoScript#2803]
### 你的功能请求是否与问题有关？

mumu因为adb端口问题导致多卡困难，在官网搜了下，好像12可以多开了？

### 解决方案

https://mumu.163.com/help/20230214/35047_1073151.html#a1

**Comment by SaiCateDoan** [comment]
是的，但是Alas没有专门的人负责更新文档，需要等一个有缘人

**Comment by SaarChaffee** [comment]
已更新

**Comment by SaarChaffee** [comment]
最新的文档可以参考https://alas-wiki.saarcenter.com/zh-CN/manual/emulator/emulator-support.html
