### ISSUE TITLE
depoly.yaml

### ISSUE THREAD

**Issue by zaizai35741** [LmeSzinc/AzurLaneAutoScript#2824]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

alas更新失败，无法打开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![螢幕擷取畫面 2023-07-01 152211](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53345766/e65dbe65-a77b-4638-ba20-eb6619e9baa9)

**Comment by LmeSzinc** [comment]
阅读 [中文安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B)
