### ISSUE TITLE
关于自建反和谐仓库，使用ALAS反和谐功能后，出现CRLF换行符错误的问题

### ISSUE THREAD

**Issue by ryzalin** [LmeSzinc/AzurLaneAutoScript#2831]
### 你的功能请求是否与问题有关？

我把反和谐的功能回退到了两天前只push localization.txt之前的状态。所以不算bug，毕竟是我自己在折腾。
我自建了一个反和谐仓库，在使用ALAS反和谐功能后，我发现pull下来的localization.txt文件使用的是windows的CRLF换行，push进模拟器后会导致游戏闪退。我反复确认了仓库中的localization.txt文件使用的是UNIX的LF换行。
印象中之前也有使用过默认的反和谐功能（不是自建仓库），并没有出现过类似的情况。因此想请问是我哪里弄错了吗？

### 其他内容

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11930108/log.txt)

**Comment by LmeSzinc** [comment]
我不清楚你魔改了什么文件，替换了损坏的文件也可能导致游戏无法启动，因此你的问题与 localization.txt 无必然联系。
这里的损坏不仅指文件本身的损坏，还有文件不是游戏客户端预期的格式，等等

**Comment by SaiCateDoan** [comment]
这是git的设置问题，默认的设置会根据系统自适应换行符，在windows上就是CRLF，在linux上就是LF
你可以搜索一下如何修改这个设置

**Comment by ryzalin** [comment]
> 这是git的设置问题，默认的设置会根据系统自适应换行符，在windows上就是CRLF，在linux上就是LF 你可以搜索一下如何修改这个设置

如果是安装了git工具的话我倒是设置好了这方面的东西，但我看源代码似乎是调用的toolkit里打包的git工具，那个工具我就不清楚是怎么操作的了
