### ISSUE TITLE
自动更新或在服务器维护时不报错

### ISSUE THREAD

**Issue by AaronRhein** [LmeSzinc/AzurLaneAutoScript#2845]
### 你的功能请求是否与问题有关？

是否可以添加自动更新游戏或定时上线检查更新之类的功能？
目前长期居住在北美，时差12小时，游戏3点更新，不能即时重启alas

### 解决方案

是否可以设定一个自动更新或者是设定时间的重启设置来避免游戏更新时alas报错？

### 其他内容

non

**Comment by julystone** [comment]
此功能是已完成了的，请重新观察，当前游戏维护并不会中止alas

**Comment by AaronRhein** [comment]
上个月有一次在维护之后报错了，这次维护我试一下

**Comment by SaiCateDoan** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48789988/bdfc4aec-54ef-43c4-82d7-0959ad87a741)

设置好服务器之后，alas在发生错误后会检查服务器状态，发现在维护之后就会等待开服
（这个功能在网络环境比较特别的时候可能会无法正常使用）
