### ISSUE TITLE
ImportError: cannot import name ‘InvalidSchemeCombination’ from ‘pip._internal.exceptions’

### ISSUE THREAD

**Issue by zy214** [LmeSzinc/AzurLaneAutoScript#2857]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

今早alas无法启动，下载AlasApp_0.4.3_fullcn替换过文件。更改 Repository能连接后python这边报错。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/28728254/60ccbf2a-b60f-44a3-a229-7b90eea0124d)

**Comment by zy214** [comment]
试过默认清华源，阿里源还有null

**Comment by lucky2023666** [comment]
刚也遇到了解决了。PypiMirror: https://mirrors.aliyun.com/pypi/simple/

**Comment by LmeSzinc** [comment]
文件损坏了，重新安装 Alas 而不是替换文件
以及不要更新 pip（无视这句如果你不知道 pip 是什么）

**Comment by zy214** [comment]
> 文件损坏了，重新安装 Alas 而不是替换文件 以及不要更新 pip（无视这句如果你不知道 pip 是什么）

好的 已解决
