### ISSUE TITLE
请求增添六期科研自定义过滤器

### ISSUE THREAD

**Issue by MyMaHck** [LmeSzinc/AzurLaneAutoScript#2874]
### 你的功能请求是否与问题有关？

如题，请求增添S6、定向研发中的舰船名称等等

### 解决方案

无

### 其他内容

无

**Comment by LmeSzinc** [comment]
#2875

**Comment by ErzsebetDAZE** [comment]
> #2875

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn 自定义过滤器的六期科研舰船名能加上去吗

**Comment by bookbug666** [comment]
兄弟，科研才開不到24小時，商店功能更是才剛修正，晚點等有空的人補全吧，沒那麼急迫的
