### ISSUE TITLE
登录时出现了如下问题

### ISSUE THREAD

**Issue by rfzmiaoling** [LmeSzinc/AzurLaneAutoScript#288]
![image](https://user-images.githubusercontent.com/74125777/103270799-c40d0400-49f3-11eb-9c73-2176da27e0c0.png)

**Comment by rfzmiaoling** [comment]
国服，在上次更新后出现的问题

**Comment by LmeSzinc** [comment]
发一下 ``./config/alas.ini`

**Comment by rfzmiaoling** [comment]
重新安装了一下解决了
