### ISSUE TITLE
对科研逻辑的优化建议

### ISSUE THREAD

**Issue by Ashe428** [LmeSzinc/AzurLaneAutoScript#2884]
### 你的功能请求是否与问题有关？

在设置不用魔方的情况下，如果遇到图片里这样的情况，alas会停止添加新的项目直至次日北京时间0点刷新（此时距离北京时间0点还有13小时，本人时差党，下方log里的时间不仅具有参考性）。
![WechatIMG18](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/83379711/6025c353-c11c-4817-af8b-0645f28d37bd)

### 解决方案

希望alas能在图片里的这种情况下（甚至在5个全都是魔方科研的情况下），强制添加用时最短的项目或者选择不使魔方的项目以刷新科研列表。

### 其他内容

INFO     23:11:06.322 │ RESEARCH SELECT                                                                  
INFO     23:11:06.376 │ [RESEARCH 0.054s] ['H-387-MI', 'H-387-MI', 'T-384-MI', 'H-207-RF', 'H-387-MI']   
INFO     23:11:06.378 │ [Project] S6 H-387-MI                                                            
INFO     23:11:06.379 │ [Project] S3 H-387-MI                                                            
INFO     23:11:06.380 │ [Project] S6 T-384-MI                                                            
INFO     23:11:06.380 │ [Project] S6 H-207-RF                                                            
INFO     23:11:06.381 │ [Project] S6 H-387-MI                                                            
INFO     23:11:06.382 │ [Research preset] series_6_blueprint_203                                         
INFO     23:11:06.382 │ Use cube: do_not_use Use coin: always_use Use part: always_use                   
INFO     23:11:06.383 │ [Allow delay] True                                                               
INFO     23:11:06.383 │ [Filter_sort] reset                                                              
INFO     23:11:06.384 │ Research reset unavailable                                                       
INFO     23:11:06.385 │ No research project started                                                      
INFO     23:11:06.386 │ Enforce choosing research project                                                
INFO     23:11:06.386 │ [Research preset] series_6_blueprint_203_cube                                    
INFO     23:11:06.386 │ Use cube: do_not_use Use coin: always_use Use part: always_use                   
INFO     23:11:06.387 │ [Allow delay] True                                                               
INFO     23:11:06.388 │ [Filter_sort] reset                                                              
INFO     23:11:06.388 │ Research reset unavailable                                                       
INFO     23:11:06.389 │ No research project started                                                      
INFO     23:11:06.390 │ Unable to start a project, stop filling queue, queue added: 0                    
INFO     23:11:06.391 │ Research queue: ['running', 'waiting', 'empty', 'empty', 'empty']                
INFO     23:11:06.392 │ [Research queue slot] 3                                                          
INFO     23:11:06.393 │ Delay task `Research` to 2023-07-15 00:17:08 (target=datetime.datetime(2023, 7,  
         15, 0, 17, 8, 106097))                                                                          
INFO     23:11:06.403 │ Bind task {'Research', 'Alas', 'General'}                                        
INFO     23:11:06.404 │ Save config ./config\alas.json,                                                  
         Research.Scheduler.NextRun=datetime.datetime(2023, 7, 15, 0, 17, 8)                             
INFO     23:11:06.409 │ Scheduler: End task `Research`                                                   
INFO     23:11:06.411 │ [Server] cn                                                                      
INFO     23:11:06.428 │ Bind task {'Alas', 'General'}                                                    
INFO     23:11:06.431 │ No task pending                                                                  
INFO     23:11:06.431 │ [Task] OpsiObscure (Enable, 2023-07-14 23:14:01)                                 
INFO     23:11:06.432 │ Bind task {'OpsiObscure', 'Alas', 'General', 'OpsiGeneral'}                      
INFO     23:11:06.436 │ Wait until 2023-07-14 23:14:01 for task `OpsiObscure`                            
INFO     23:11:06.437 │ Goto main page during wait

**Comment by bookbug666** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29662367/0cf64ab1-ab31-49fb-9d8f-76992c255ab1)
不是有現成的選項嗎

**Comment by Ashe428** [comment]
>
