### ISSUE TITLE
心情和出击相关的功能建议

### ISSUE THREAD

**Issue by foxlesbiao** [LmeSzinc/AzurLaneAutoScript#2894]
### 你的功能请求是否与问题有关？

无关

### 解决方案

心情消耗完毕后，可不可以切换队伍继续出击。
比如我的二队没有心情了，自动切换为一队来继续出击。

### 其他内容

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/41581909/591e2676-f9d2-4983-86c3-a450f6e69801)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/41581909/7b8725d1-006a-4896-b35b-f26c2ec602f6)

**Comment by ec7529a2** [comment]
如果你要打的关卡可以使用主界面的编队按钮预设的编队，那么你可以简单的开两个任务，设置为用不同的编队打就行
如果关卡只能手动编队，且你需要其中一队全清另一队待机，那么你可以开两个任务，其中一个设置为一队全清，另一个设置为二队全清，因为全清不会消耗另一队的心情，所以这两个任务不会互相干扰
如果关卡只能手动编队，且你需要其中一队打道中另一队打boss，那么目前没办法

**Comment by foxlesbiao** [comment]
> 如果你要打的关卡可以使用主界面的编队按钮预设的编队，那么你可以简单的开两个任务，设置为用不同的编队打就行 如果关卡只能手动编队，且你需要其中一队全清另一队待机，那么你可以开两个任务，其中一个设置为一队全清，另一个设置为二队全清，因为全清不会消耗另一队的心情，所以这两个任务不会互相干扰 如果关卡只能手动编队，且你需要其中一队打道中另一队打 boss，那么目前没办法

woc 还可以这样的啊，我的错误 :)

**Comment by tuman-qahraman** [comment]
> 如果你要打的关卡可以使用主界面的编队按钮预设的编队，那么你可以简单的开两个任务，设置为用不同的编队打就行 如果关卡只能手动编队，且你需要其中一队全清另一队待机，那么你可以开两个任务，其中一个设置为一队全清，另一个设置为二队全清，因为全清不会消耗另一队的心情，所以这两个任务不会互相干扰 如果关卡只能手动编队，且你需要其中一队打道中另一队打boss，那么目前没办法

原来如此，非常感谢！
