### ISSUE TITLE
脚本点雷电模拟器点不到

### ISSUE THREAD

**Issue by xingyedekong** [LmeSzinc/AzurLaneAutoScript#2897]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

脚本点雷电模拟器点不到

### 如何复现

脚本点雷电模拟器点不到

### 预期行为

脚本点雷电模拟器点不到

### 相关 Logs

```Text
脚本点雷电模拟器点不到
```

### 截图

![QQ图片20230719213859](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135824425/65ea8252-98ef-42ce-a638-7929586489e0)

### 还有别的吗？

脚本点雷电模拟器点不到

**Comment by bookbug666** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Emulator_cn#-%E5%9C%A8%E9%9B%B7%E7%94%B5%E6%A8%A1%E6%8B%9F%E5%99%A8%E4%B8%8A%E8%BF%90%E8%A1%8Calas

**Comment by LmeSzinc** [comment]
> 在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。

**Comment by xingyedekong** [comment]
非常感谢！
