### ISSUE TITLE
科研项目识别错误

### ISSUE THREAD

**Issue by zengshzh** [LmeSzinc/AzurLaneAutoScript#2902]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

这是个6期1小时魔方科研
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48642377/f8f1db90-7f60-4dd8-b7a9-ff1a4d621613)
但是alas把他判定成了五期，并且导致选择错误（上图的结果是手动修改后的）：
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48642377/e71bee4f-18ba-4cca-b5b3-3f27aa4b6005)
这是我的自定义过滤器：
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48642377/3f5bc91e-d9c1-46d8-94c6-e3cb3b242ad0)

**Comment by LmeSzinc** [comment]
#2903
