### ISSUE TITLE
请教活动图开荒设置

### ISSUE THREAD

**Issue by suzukiayato** [LmeSzinc/AzurLaneAutoScript#2909]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

想问一下活动图的自动开荒是要怎么设置的呢？目前这个最新的活动我是手动打了T1-T3的100%通关+三星，手动点来点去觉得太烦了，然后就在Alas的活动-活动图里的“关卡设置”里填写了T4，又在停止条件里的“达成关卡成就后停止”那里选了100%通关+三星，然后勾选了“达成关卡成就后向前开荒”，但是它自己进去T4之后还没一秒就报错了，连续试了好几次都这样，就想问问究竟是要如何设置的。

### 如何复现

上面已经写了。

### 预期行为

希望能得到回复如何正确设置活动图自动开荒。

### 相关 Logs

```Text
INFO     03:32:46.216 │ Scheduler: Start task `Event`                               
════════════════════════════════════════════════════════════════════════════════════
                                       EVENT                                        
════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════ T4 ════════════════════════════════════════
INFO     03:32:46.388 │ T4                                                          
INFO     03:32:46.389 │ Count: 0                                                    
INFO     03:32:46.401 │ UI get current page                                         
INFO     03:32:46.410 │ [UI] page_event                                             
INFO     03:32:46.412 │ Already at page_event                                       
INFO     03:32:46.414 │ <<< UI ENSURE INDEX >>>                                     
INFO     03:32:46.512 │ [campaign 0.052s] ['T1', 'T3', 'T2', 'T4']                  
INFO     03:32:46.516 │ [Chapter] t                                                 
INFO     03:32:46.518 │ [Stage] t1, t3, t2, t4                                      
INFO     03:32:46.520 │ [Index] 1                                                   
INFO     03:32:46.583 │ [OCR_OIL 0.046s] 9471                                       
──────────────────────────────────────── T4 ────────────────────────────────────────
INFO     03:32:46.588 │ T4                                                          
INFO     03:32:46.591 │ Expect emotion reduce: (10, 2)                              
INFO     03:32:46.624 │ Bind task {'General', 'TaskBalancer', 'EventGeneral',       
         'Event', 'Alas'}                                                           
INFO     03:32:46.628 │ Save config ./config\alas.json,                             
         Event.Emotion.Fleet1Value=125,                                             
         Event.Emotion.Fleet1Record=datetime.datetime(2023, 7, 21, 3, 32, 46),      
         Event.Emotion.Fleet2Value=117,                                             
         Event.Emotion.Fleet2Record=datetime.datetime(2023, 7, 21, 3, 32, 46)       
INFO     03:32:46.654 │ [Emotion fleet_1] 125                                       
INFO     03:32:46.657 │ [Emotion fleet_2] 117                                       
INFO     03:32:46.660 │ <<< ENTER MAP >>>                                           
INFO     03:32:46.708 │ Click ( 849,  275) @ t4                                     
INFO     03:32:47.172 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.456 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.770 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.772 │ [MAP_CLEAR_ALL_THIS_TIME] True                              
INFO     03:32:47.774 │ [Map_info] 0%,                                              
INFO     03:32:47.775 │ [StopCondition_MapAchievement] map_3_stars                  
INFO     03:32:47.790 │ No auto search option.                                      
INFO     03:32:47.792 │ Click ( 968,  524) @ MAP_PREPARATION                        
INFO     03:32:48.111 │ Using fleet: [1, 2, 1]                                      
INFO     03:32:48.139 │ Hard satisfied: Fleet_1: None, Fleet_2: None, Submarine:    
         None                                                                       
INFO     03:32:48.142 │ Click (1045,  463) @ SUBMARINE_CHOOSE                       
INFO     03:32:48.365 │ Current selected: [1]                                       
INFO     03:32:48.367 │ Click (1048,  478) @ SUBMARINE_CHOOSE                       
INFO     03:32:48.687 │ Click (1149,  322) @ FLEET_2_CLEAR                          
INFO     03:32:48.961 │ Click (1041,  203) @ FLEET_1_CHOOSE                         
INFO     03:32:49.268 │ Current selected: [1]                                       
INFO     03:32:49.271 │ Click (1057,  206) @ FLEET_1_CHOOSE                         
INFO     03:32:49.563 │ Click (1058,  320) @ FLEET_2_CHOOSE                         
INFO     03:32:49.890 │ Current selected: [1]                                       
INFO     03:32:49.892 │ Click (1071,  433) @ FLEET_2_BAR_INDEX_2                    
WARNING  03:32:50.170 │ Can not set submarine call because auto search not          
         available, assuming disabled                                               
WARNING  03:32:50.172 │ Please do the followings: goto any stage -> auto search role
         -> set submarine role to standby                                           
WARNING  03:32:50.174 │ If you already did, ignore this warning                     
INFO     03:32:50.175 │ Click (1035,  606) @ FLEET_PREPARATION                      
INFO     03:32:53.810 │ Enemy searching appeared.                                   
INFO     03:32:53.948 │ No fleet lock option.                                       
INFO     03:32:53.950 │ <<< MAP INIT >>>                                            
ERROR    03:32:53.952 │ KeyError: ((2, 1), (2, 5), (8, 1), (8, 5))                  
         ╭─────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\alas.py:68 in   │
         │ run                                                                     │
         │                                                                         │
         │    66 │   │   try:                                                      │
         │    67 │   │   │   self.device.screenshot()                              │
         │ ❱  68 │   │   │   self.__getattribute__(command)()                      │
         │    69 │   │   │   return True                                           │
         │    70 │   │   except TaskEnd:                                           │
         │                                                                         │
         │ ╭───────────────────────────── locals ─────────────────────────────╮    │
         │ │ command = 'event'                                                │    │
         │ │       e = KeyError(((2, 1), (2, 5), (8, 1), (8, 5)))             │    │
         │ │    self = <alas.AzurLaneAutoScript object at 0x000002AC6D8CC108> │    │
         │ ╰──────────────────────────────────────────────────────────────────╯    │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\alas.py:354 in  │
         │ event                                                                   │
         │                                                                         │
         │   352 │   │   from module.campaign.run import CampaignRun               │
         │   353 │   │   CampaignRun(config=self.config, device=self.device).run(  │
         │ ❱ 354 │   │   │   name=self.config.Campaign_Name, folder=self.config.Ca │
         │       mode=self.config.Campaign_Mode)                                   │
         │   355 │                                                                 │
         │   356 │   def event2(self):                                             │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ CampaignRun = <class 'module.campaign.run.CampaignRun'>             │ │
         │ │        self = <alas.AzurLaneAutoScript object at                    │ │
         │ │               0x000002AC6D8CC108>                                   │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\campaign │
         │ \run.py:356 in run                                                      │
         │                                                                         │
         │   354 │   │   │   # Run                                                 │
         │   355 │   │   │   try:                                                  │
         │ ❱ 356 │   │   │   │   self.campaign.run()                               │
         │   357 │   │   │   except ScriptEnd as e:                                │
         │   358 │   │   │   │   logger.hr('Script end')                           │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ folder = 'event_20211125_cn'                                        │ │
         │ │   mode = 'normal'                                                   │ │
         │ │   name = 't4'                                                       │ │
         │ │   self = <module.campaign.run.CampaignRun object at                 │ │
         │ │          0x000002AC1DA7E4C8>                                        │ │
         │ │  total = 0                                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\campaign │
         │ \campaign_base.py:130 in run                                            │
         │                                                                         │
         │   128 │   │   if not self.map_is_auto_search:                           │
         │   129 │   │   │   self.handle_map_fleet_lock()                          │
         │ ❱ 130 │   │   │   self.map_init(self.MAP)                               │
         │   131 │   │   else:                                                     │
         │   132 │   │   │   self.map = self.MAP                                   │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\flee │
         │ t.py:810 in map_init                                                    │
         │                                                                         │
         │    808 │   │   """                                                      │
         │    809 │   │   logger.hr('Map init')                                    │
         │ ❱  810 │   │   self.map_data_init(map_)                                 │
         │    811 │   │   self.map_control_init()                                  │
         │    812                                                                  │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\campaign\event_ │
         │ 20211125_cn\t4.py:103 in map_data_init                                  │
         │                                                                         │
         │   101 │   │   # Clear mode still has fortress                           │
         │   102 │   │   self.config.MAP_HAS_FORTRESS = True                       │
         │ ❱ 103 │   │   super().map_data_init(map_)                               │
         │   104 │                                                                 │
         │   105 │   def handle_clear_mode_config_cover(self):                     │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ __class__ = <class 'campaign.event_20211125_cn.t4.Campaign'>        │ │
         │ │      map_ = <module.map.map_base.CampaignMap object at              │ │
         │ │             0x000002AC1DACA448>                                     │ │
         │ │      self = <campaign.event_20211125_cn.t4.Campaign object at       │ │
         │ │             0x000002AC1CE15B08>                                     │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\flee │
         │ t.py:832 in map_data_init                                               │
         │                                                                         │
         │    830 │   │   self.map = map_                                          │
         │    831 │   │   self.map.reset()                                         │
         │ ❱  832 │   │   self.handle_clear_mode_config_cover()                    │
         │    833 │   │   self.map.poor_map_data = self.config.POOR_MAP_DATA       │
         │    834 │   │   self.map.load_map_data(use_loop=self.map_is_clear_mode)  │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\campaign\event_ │
         │ 20211125_cn\t4.py:107 in handle_clear_mode_config_cover                 │
         │                                                                         │
         │   105 │   def handle_clear_mode_config_cover(self):                     │
         │   106 │   │   # Preserve fortress data, but release fortress block      │
         │ ❱ 107 │   │   self.map.fortress_data = [self.map.fortress_data[0], ()]  │
         │   108                                                                   │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:202 in fortress_data                                            │
         │                                                                         │
         │   200 │   def fortress_data(self, data):                                │
         │   201 │   │   enemy, block = data                                       │
         │ ❱ 202 │   │   enemy = self.to_selected((enemy,) if not isinstance(enemy │
         │       enemy)                                                            │
         │   203 │   │   block = self.to_selected((block,) if not isinstance(block │
         │       block)                                                            │
         │   204 │   │   self._fortress_data = [enemy, block]                      │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ block = ()                                                          │ │
         │ │  data = [                                                           │ │
         │ │         │   <module.map.map_grids.SelectedGrids object at           │ │
         │ │         0x000002AC1D7DA1C8>,                                        │ │
         │ │         │   ()                                                      │ │
         │ │         ]                                                           │ │
         │ │ enemy = <module.map.map_grids.SelectedGrids object at               │ │
         │ │         0x000002AC1D7DA1C8>                                         │ │
         │ │  self = <module.map.map_base.CampaignMap object at                  │ │
         │ │         0x000002AC1DACA448>                                         │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:794 in to_selected                                              │
         │                                                                         │
         │   792 │   │   │   SelectedGrids:                                        │
         │   793 │   │   """                                                       │
         │ ❱ 794 │   │   return SelectedGrids([self[location_ensure(loca)] for loc │
         │   795 │                                                                 │
         │   796 │   def flatten(self):                                            │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ grids = (                                                           │ │
         │ │         │   <module.map.map_grids.SelectedGrids object at           │ │
         │ │         0x000002AC1D7DA1C8>,                                        │ │
         │ │         )                                                           │ │
         │ │  self = <module.map.map_base.CampaignMap object at                  │ │
         │ │         0x000002AC1DACA448>                                         │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:794 in <listcomp>                                               │
         │                                                                         │
         │   792 │   │   │   SelectedGrids:                                        │
         │   793 │   │   """                                                       │
         │ ❱ 794 │   │   return SelectedGrids([self[location_ensure(loca)] for loc │
         │   795 │                                                                 │
         │   796 │   def flatten(self):                                            │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │   .0 = <tuple_iterator object at 0x000002AC1D0DD188>                │ │
         │ │ loca = <module.map.map_grids.SelectedGrids object at                │ │
         │ │        0x000002AC1D7DA1C8>                                          │ │
         │ │ self = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:49 in __getitem__                                               │
         │                                                                         │
         │    47 │   │   │   GridInfo:                                             │
         │    48 │   │   """                                                       │
         │ ❱  49 │   │   return self.grids[tuple(item)]                            │
         │    50 │                                                                 │
         │    51 │   def __contains__(self, item):                                 │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ item = [(2, 1), (2, 5), (8, 1), (8, 5)]                             │ │
         │ │ self = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         ╰─────────────────────────────────────────────────────────────────────────╯
         KeyError: ((2, 1), (2, 5), (8, 1), (8, 5))                                 
WARNING  03:32:55.058 │ Saving error: ./log/error/1689881575058                     
INFO     03:32:55.379 │ No provider specified, skip sending
```

### 截图

INFO     03:32:46.216 │ Scheduler: Start task `Event`                               
════════════════════════════════════════════════════════════════════════════════════
                                       EVENT                                        
════════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════ T4 ════════════════════════════════════════
INFO     03:32:46.388 │ T4                                                          
INFO     03:32:46.389 │ Count: 0                                                    
INFO     03:32:46.401 │ UI get current page                                         
INFO     03:32:46.410 │ [UI] page_event                                             
INFO     03:32:46.412 │ Already at page_event                                       
INFO     03:32:46.414 │ <<< UI ENSURE INDEX >>>                                     
INFO     03:32:46.512 │ [campaign 0.052s] ['T1', 'T3', 'T2', 'T4']                  
INFO     03:32:46.516 │ [Chapter] t                                                 
INFO     03:32:46.518 │ [Stage] t1, t3, t2, t4                                      
INFO     03:32:46.520 │ [Index] 1                                                   
INFO     03:32:46.583 │ [OCR_OIL 0.046s] 9471                                       
──────────────────────────────────────── T4 ────────────────────────────────────────
INFO     03:32:46.588 │ T4                                                          
INFO     03:32:46.591 │ Expect emotion reduce: (10, 2)                              
INFO     03:32:46.624 │ Bind task {'General', 'TaskBalancer', 'EventGeneral',       
         'Event', 'Alas'}                                                           
INFO     03:32:46.628 │ Save config ./config\alas.json,                             
         Event.Emotion.Fleet1Value=125,                                             
         Event.Emotion.Fleet1Record=datetime.datetime(2023, 7, 21, 3, 32, 46),      
         Event.Emotion.Fleet2Value=117,                                             
         Event.Emotion.Fleet2Record=datetime.datetime(2023, 7, 21, 3, 32, 46)       
INFO     03:32:46.654 │ [Emotion fleet_1] 125                                       
INFO     03:32:46.657 │ [Emotion fleet_2] 117                                       
INFO     03:32:46.660 │ <<< ENTER MAP >>>                                           
INFO     03:32:46.708 │ Click ( 849,  275) @ t4                                     
INFO     03:32:47.172 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.456 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.770 │ [Map_clear_percentage] 0.0                                  
INFO     03:32:47.772 │ [MAP_CLEAR_ALL_THIS_TIME] True                              
INFO     03:32:47.774 │ [Map_info] 0%,                                              
INFO     03:32:47.775 │ [StopCondition_MapAchievement] map_3_stars                  
INFO     03:32:47.790 │ No auto search option.                                      
INFO     03:32:47.792 │ Click ( 968,  524) @ MAP_PREPARATION                        
INFO     03:32:48.111 │ Using fleet: [1, 2, 1]                                      
INFO     03:32:48.139 │ Hard satisfied: Fleet_1: None, Fleet_2: None, Submarine:    
         None                                                                       
INFO     03:32:48.142 │ Click (1045,  463) @ SUBMARINE_CHOOSE                       
INFO     03:32:48.365 │ Current selected: [1]                                       
INFO     03:32:48.367 │ Click (1048,  478) @ SUBMARINE_CHOOSE                       
INFO     03:32:48.687 │ Click (1149,  322) @ FLEET_2_CLEAR                          
INFO     03:32:48.961 │ Click (1041,  203) @ FLEET_1_CHOOSE                         
INFO     03:32:49.268 │ Current selected: [1]                                       
INFO     03:32:49.271 │ Click (1057,  206) @ FLEET_1_CHOOSE                         
INFO     03:32:49.563 │ Click (1058,  320) @ FLEET_2_CHOOSE                         
INFO     03:32:49.890 │ Current selected: [1]                                       
INFO     03:32:49.892 │ Click (1071,  433) @ FLEET_2_BAR_INDEX_2                    
WARNING  03:32:50.170 │ Can not set submarine call because auto search not          
         available, assuming disabled                                               
WARNING  03:32:50.172 │ Please do the followings: goto any stage -> auto search role
         -> set submarine role to standby                                           
WARNING  03:32:50.174 │ If you already did, ignore this warning                     
INFO     03:32:50.175 │ Click (1035,  606) @ FLEET_PREPARATION                      
INFO     03:32:53.810 │ Enemy searching appeared.                                   
INFO     03:32:53.948 │ No fleet lock option.                                       
INFO     03:32:53.950 │ <<< MAP INIT >>>                                            
ERROR    03:32:53.952 │ KeyError: ((2, 1), (2, 5), (8, 1), (8, 5))                  
         ╭─────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\alas.py:68 in   │
         │ run                                                                     │
         │                                                                         │
         │    66 │   │   try:                                                      │
         │    67 │   │   │   self.device.screenshot()                              │
         │ ❱  68 │   │   │   self.__getattribute__(command)()                      │
         │    69 │   │   │   return True                                           │
         │    70 │   │   except TaskEnd:                                           │
         │                                                                         │
         │ ╭───────────────────────────── locals ─────────────────────────────╮    │
         │ │ command = 'event'                                                │    │
         │ │       e = KeyError(((2, 1), (2, 5), (8, 1), (8, 5)))             │    │
         │ │    self = <alas.AzurLaneAutoScript object at 0x000002AC6D8CC108> │    │
         │ ╰──────────────────────────────────────────────────────────────────╯    │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\alas.py:354 in  │
         │ event                                                                   │
         │                                                                         │
         │   352 │   │   from module.campaign.run import CampaignRun               │
         │   353 │   │   CampaignRun(config=self.config, device=self.device).run(  │
         │ ❱ 354 │   │   │   name=self.config.Campaign_Name, folder=self.config.Ca │
         │       mode=self.config.Campaign_Mode)                                   │
         │   355 │                                                                 │
         │   356 │   def event2(self):                                             │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ CampaignRun = <class 'module.campaign.run.CampaignRun'>             │ │
         │ │        self = <alas.AzurLaneAutoScript object at                    │ │
         │ │               0x000002AC6D8CC108>                                   │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\campaign │
         │ \run.py:356 in run                                                      │
         │                                                                         │
         │   354 │   │   │   # Run                                                 │
         │   355 │   │   │   try:                                                  │
         │ ❱ 356 │   │   │   │   self.campaign.run()                               │
         │   357 │   │   │   except ScriptEnd as e:                                │
         │   358 │   │   │   │   logger.hr('Script end')                           │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ folder = 'event_20211125_cn'                                        │ │
         │ │   mode = 'normal'                                                   │ │
         │ │   name = 't4'                                                       │ │
         │ │   self = <module.campaign.run.CampaignRun object at                 │ │
         │ │          0x000002AC1DA7E4C8>                                        │ │
         │ │  total = 0                                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\campaign │
         │ \campaign_base.py:130 in run                                            │
         │                                                                         │
         │   128 │   │   if not self.map_is_auto_search:                           │
         │   129 │   │   │   self.handle_map_fleet_lock()                          │
         │ ❱ 130 │   │   │   self.map_init(self.MAP)                               │
         │   131 │   │   else:                                                     │
         │   132 │   │   │   self.map = self.MAP                                   │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\flee │
         │ t.py:810 in map_init                                                    │
         │                                                                         │
         │    808 │   │   """                                                      │
         │    809 │   │   logger.hr('Map init')                                    │
         │ ❱  810 │   │   self.map_data_init(map_)                                 │
         │    811 │   │   self.map_control_init()                                  │
         │    812                                                                  │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\campaign\event_ │
         │ 20211125_cn\t4.py:103 in map_data_init                                  │
         │                                                                         │
         │   101 │   │   # Clear mode still has fortress                           │
         │   102 │   │   self.config.MAP_HAS_FORTRESS = True                       │
         │ ❱ 103 │   │   super().map_data_init(map_)                               │
         │   104 │                                                                 │
         │   105 │   def handle_clear_mode_config_cover(self):                     │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ __class__ = <class 'campaign.event_20211125_cn.t4.Campaign'>        │ │
         │ │      map_ = <module.map.map_base.CampaignMap object at              │ │
         │ │             0x000002AC1DACA448>                                     │ │
         │ │      self = <campaign.event_20211125_cn.t4.Campaign object at       │ │
         │ │             0x000002AC1CE15B08>                                     │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\flee │
         │ t.py:832 in map_data_init                                               │
         │                                                                         │
         │    830 │   │   self.map = map_                                          │
         │    831 │   │   self.map.reset()                                         │
         │ ❱  832 │   │   self.handle_clear_mode_config_cover()                    │
         │    833 │   │   self.map.poor_map_data = self.config.POOR_MAP_DATA       │
         │    834 │   │   self.map.load_map_data(use_loop=self.map_is_clear_mode)  │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\campaign\event_ │
         │ 20211125_cn\t4.py:107 in handle_clear_mode_config_cover                 │
         │                                                                         │
         │   105 │   def handle_clear_mode_config_cover(self):                     │
         │   106 │   │   # Preserve fortress data, but release fortress block      │
         │ ❱ 107 │   │   self.map.fortress_data = [self.map.fortress_data[0], ()]  │
         │   108                                                                   │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ self = <campaign.event_20211125_cn.t4.Campaign object at            │ │
         │ │        0x000002AC1CE15B08>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:202 in fortress_data                                            │
         │                                                                         │
         │   200 │   def fortress_data(self, data):                                │
         │   201 │   │   enemy, block = data                                       │
         │ ❱ 202 │   │   enemy = self.to_selected((enemy,) if not isinstance(enemy │
         │       enemy)                                                            │
         │   203 │   │   block = self.to_selected((block,) if not isinstance(block │
         │       block)                                                            │
         │   204 │   │   self._fortress_data = [enemy, block]                      │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ block = ()                                                          │ │
         │ │  data = [                                                           │ │
         │ │         │   <module.map.map_grids.SelectedGrids object at           │ │
         │ │         0x000002AC1D7DA1C8>,                                        │ │
         │ │         │   ()                                                      │ │
         │ │         ]                                                           │ │
         │ │ enemy = <module.map.map_grids.SelectedGrids object at               │ │
         │ │         0x000002AC1D7DA1C8>                                         │ │
         │ │  self = <module.map.map_base.CampaignMap object at                  │ │
         │ │         0x000002AC1DACA448>                                         │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:794 in to_selected                                              │
         │                                                                         │
         │   792 │   │   │   SelectedGrids:                                        │
         │   793 │   │   """                                                       │
         │ ❱ 794 │   │   return SelectedGrids([self[location_ensure(loca)] for loc │
         │   795 │                                                                 │
         │   796 │   def flatten(self):                                            │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ grids = (                                                           │ │
         │ │         │   <module.map.map_grids.SelectedGrids object at           │ │
         │ │         0x000002AC1D7DA1C8>,                                        │ │
         │ │         )                                                           │ │
         │ │  self = <module.map.map_base.CampaignMap object at                  │ │
         │ │         0x000002AC1DACA448>                                         │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:794 in <listcomp>                                               │
         │                                                                         │
         │   792 │   │   │   SelectedGrids:                                        │
         │   793 │   │   """                                                       │
         │ ❱ 794 │   │   return SelectedGrids([self[location_ensure(loca)] for loc │
         │   795 │                                                                 │
         │   796 │   def flatten(self):                                            │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │   .0 = <tuple_iterator object at 0x000002AC1D0DD188>                │ │
         │ │ loca = <module.map.map_grids.SelectedGrids object at                │ │
         │ │        0x000002AC1D7DA1C8>                                          │ │
         │ │ self = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         │                                                                         │
         │ C:\Users\SUZUKI\Downloads\Compressed\AzurLaneAutoScript\module\map\map_ │
         │ base.py:49 in __getitem__                                               │
         │                                                                         │
         │    47 │   │   │   GridInfo:                                             │
         │    48 │   │   """                                                       │
         │ ❱  49 │   │   return self.grids[tuple(item)]                            │
         │    50 │                                                                 │
         │    51 │   def __contains__(self, item):                                 │
         │                                                                         │
         │ ╭────────────────────────────── locals ───────────────────────────────╮ │
         │ │ item = [(2, 1), (2, 5), (8, 1), (8, 5)]                             │ │
         │ │ self = <module.map.map_base.CampaignMap object at                   │ │
         │ │        0x000002AC1DACA448>                                          │ │
         │ ╰─────────────────────────────────────────────────────────────────────╯ │
         ╰─────────────────────────────────────────────────────────────────────────╯
         KeyError: ((2, 1), (2, 5), (8, 1), (8, 5))                                 
WARNING  03:32:55.058 │ Saving error: ./log/error/1689881575058                     
INFO     03:32:55.379 │ No provider specified, skip sending

**Comment by manmanzhou** [comment]
一般活动图是先更a1-3的海图然后过一天更b1-3，但是现在列表里显示有t1-4而且好像有点问题，不太清楚怎么回事，建议等修复吧。或者先用 工具-半自动点击 自己打吧

**Comment by manmanzhou** [comment]
刚发现这次第一天就解锁的t1-4，我的问题。

**Comment by FinchOrigin** [comment]
更新，目前我使用master分支最新提交是可以正常刷T4的

**Comment by suzukiayato** [comment]
好的，现在已经是可以正常使用了，非常感谢！
