### ISSUE TITLE
活动图海图识别与ui拖动均存在问题

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#2910]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

新活动图开荒时出现5次以上Too many click for a button: MAP_SWIPE_0_-2，并出现1次以上Wrong Prediction。
已更新至今天5点后版本。
[error.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12114476/error.zip)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by manmanzhou** [comment]
我运行T1正常，T2T3均Wrong Prediction

**Comment by PkuRinko** [comment]
在运行t3时若出现1队初始位置在2队上方时几乎百分百在拖动至地图底部时出错

**Comment by guoh064** [comment]
看上去被3637d26修复了。目前t3全清已完成，正在测试三星和开荒。
