### ISSUE TITLE
计划作战模式的设置补充文档说明,怎么和alas一起配合使用

### ISSUE THREAD

**Issue by gsxgmpkt9020** [LmeSzinc/AzurLaneAutoScript#2913]
### 你的功能请求是否与问题有关？

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/0b1a05f1-234e-4500-87b7-8e9cc709ceeb)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/0f6d0a81-d124-4a26-b5fc-321253c800ae)

**Comment by bookbug666** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
