### ISSUE TITLE
卡在NA海域东北D无限死循环，EMHOD塞壬试验场无法自动进入，产生了20万行的无效重复跑图的log（无报错）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [LmeSzinc/AzurLaneAutoScript#2921]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

最近1H的运行
[2023-06-26_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12136052/2023-06-26_alas.txt)

最近24H的运行 （太大了，手动删了很多）

[2023-07-22_largealas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12136056/2023-07-22_largealas.txt)

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/e6d8eea1-0444-4d87-8450-f3fc07f843b7)

### 如何复现

发现问题后，关掉ALAS，手动在NA海域东北D自律寻敌，解决敌人。一直都是安全海域，什么都没有。
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/07f580e3-c23e-4617-9f66-ea191bba7b46)

然后打开ALAS运行
NA海域东北D出现塞壬试验场的标志
（接下来就是继续死循环）
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/ed89c001-fc9a-43c9-90f6-fb3c405e8ccc)

接了绿色任务是否就需要手动操作了，需要手动做任务？比如这个塞壬试验场？

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/3fcb7e41-f8ec-42c9-bf82-8a7f3e2eb983)

碧蓝航线没有取消任务的选项吗？

我明明主线和模拟战都做完了

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/87abd8ba-3cd1-4bc9-b0dd-fcba14493ddf)

是不是我必须手动完成这些任务以后，才能用ALAS刷大世界？（只能把ALAS大世界所有任务关闭来刷活动，否则一直卡在这里死循环）

**Comment by illyaaaa** [comment]
塞壬试验场一共有 12 个，属于大世界主线内容
需要你手动做完
