### ISSUE TITLE
因为没搞清活动机制导致蹭经验低等级小船因为瞬间低血量被强制撤离（已经解决）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [LmeSzinc/AzurLaneAutoScript#2924]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

交汇世界的弧光T3攻略期间出现机甲支援以后，小队会被强制撤离
![alas0723](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/47f4aa90-099b-4541-b845-da44c63003cc)
[2023-07-23_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12138194/2023-07-23_alas.txt)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
需要提供log
