### ISSUE TITLE
如何正确设置Alas设置中的重启模拟器功能

### ISSUE THREAD

**Issue by onecombo** [LmeSzinc/AzurLaneAutoScript#2926]
### 你的功能请求是否与问题有关？

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/33618120/7d8d1598-16f4-4ae6-9920-7c25cee42a62)
在下愚钝，无法理解这个功能的设置指导。
想详细咨询一下如何正确设置这个功能。
现在的问题是，每次到0点Alas会卡在重启上停止，感觉就是这里出了问题，但不清楚如何改正。

希望得到开发者或正确设置的用户指点一二，不胜感谢。

**Comment by onecombo** [comment]
另外想请问，模拟器中的ATX app起到了什么作用？
其中：
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/33618120/bdd686fb-7505-43ac-888d-3bb0b662f0b8)
这个UI开头的服务每次重启模拟器时都会关闭，需要我手动开启。
这个功能是否重要？我是否该在意这个服务的运行情况？

**Comment by FinchOrigin** [comment]
重启模拟器的代码似乎被删了，好像是有问题，所以这个选项没有起到应有的作用，按理讲设置和不设置都是一样的，不如提供一份卡任务的日志，方便开发者定位问题吧

**Comment by onecombo** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/33618120/b7dd7d1a-9b86-4943-bb8a-81b6751a7942)

**Comment by LmeSzinc** [comment]
> No app stop/start, because HandleError disabled
> Please enable Alas.Error.HandleError or manually login to AzurLane

因为你关闭了异常处理，所以Alas不处理异常，这里没有问题。

**Comment by onecombo** [comment]
多谢，确实是这个功能的原因，我错误的以为它的作用只是处理战斗中的异常。
