### ISSUE TITLE
在刷紧急委托中增加本次活动的T2或T1关卡

### ISSUE THREAD

**Issue by Bread200** [LmeSzinc/AzurLaneAutoScript#2931]
### 你的功能请求是否与问题有关？

在刷紧急委托中若输入T1或T2关卡，运行时在进入活动图界面后会直接跳转到2-4进行刷紧急委托

### 解决方案

在刷紧急委托的关卡中增加T1或T2关卡

**Comment by Bread200** [comment]
> > 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
![log截图](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/137496220/5f0a2fd6-7808-4d98-9038-4b3b467fe2e6)

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/137496220/55a6f8c4-26c8-4e58-ae24-488a4ad02025)

**Comment by the-world1234** [comment]
看一下活动-活动通用设置-活动PT限制

**Comment by Bread200** [comment]
> 

谢谢大佬，是我自己蠢了，浪费你们时间了，感谢

**Comment by Bread200** [comment]
> 看一下活动-活动通用设置-活动PT限制

谢谢大佬，是我自己蠢了，浪费你们时间了，感谢
