### ISSUE TITLE
希望可以增加MUMU模拟器的自动检测

### ISSUE THREAD

**Issue by Qianbai2035** [LmeSzinc/AzurLaneAutoScript#2940]
### 你的功能请求是否与问题有关？

提示错误代码10061，但模拟器没错，只是版本有问题

### 解决方案

MUMU模拟器默认为127.0.0.1:5555地址，但现在下载一般为mumu12，地址需要修改为127.0.0.1:7555，希望作者可以加额外一步检测qwq

**Comment by bookbug666** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29662367/18954a88-491d-4e5e-912d-79df72e3424c)
mumu12的port要從問題診斷看，通常也不會是7555，請再確認一下

**Comment by yangwangkong** [comment]
16384，但是偶尔7555也可以连结上，不知道什么鬼

**Comment by bookbug666** [comment]
> 我看了一眼我的，是16384，我怀疑这玩意是随机的

[Mumu官方解釋](https://mumu.163.com/help/20230214/35047_1073151.html#:~:text=MuMu%E6%A8%A1%E6%8B%9F%E5%99%A8ADB%E7%AB%AF%E5%8F%A3%E4%BF%A1%E6%81%AF%E8%A7%84%E5%88%99%E5%A6%82%E4%B8%8B%EF%BC%9A) 他會是+32
