### ISSUE TITLE
收获的里面的预设，我勾选了大舰队的，然后报错，alas就一直用不了

### ISSUE THREAD

**Issue by 555mimipp** [LmeSzinc/AzurLaneAutoScript#2954]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![Snipaste_2023-08-02_03-31-07](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29752424/944aba2b-fcee-47ba-9c8e-f99debf5aa4b)
![Snipaste_2023-08-02_03-31-41](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29752424/8a384732-7120-4452-ac0b-4ca608ef235e)
![Snipaste_2023-08-02_03-31-57](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29752424/5d316459-7dc9-47de-bd4e-a6f77863738a)

### 如何复现

在设置收获里的【大舰队】选项两个打钩，然后删除了下次运行时间、并启动了该功能。之后就会出现报错
![Snipaste_2023-08-02_03-47-17](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29752424/375904f6-f2b9-4420-b06f-687ad1b6349d)

### 预期行为

接下来就出现发生错误
![Snipaste_2023-08-02_03-46-16](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29752424/12880b4d-a622-4c42-b2ad-35d4d6c5e512)

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     03:02:43.737 │ Start scheduler loop: alas                                 
INFO     03:02:43.739 │ [Server] cn                                                
INFO     03:02:43.752 │ Bind task {'Alas', 'General'}                              
INFO     03:02:43.853 │ Server "长戟计划" is available.                            
INFO     03:02:43.855 │ No task pending                                            
INFO     03:02:43.857 │ [Task] Commission (Enable, 2023-08-02 03:35:43)            
INFO     03:02:43.858 │ Bind task {'Alas', 'Commission', 'General'}                
INFO     03:02:44.841 │ Wait until 2023-08-02 03:35:43 for task `Commission`       
INFO     03:02:44.842 │ Close game during wait                                     
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     03:02:44.899 │ DEVICE                                                     
INFO     03:02:44.900 │ [AdbBinary]                                                
         D:\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe 
INFO     03:02:44.902 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     03:02:44.903 │ <<< DETECT DEVICE >>>                                      
INFO     03:02:44.904 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     03:02:44.906 │ 127.0.0.1:7555                                             
INFO     03:02:44.911 │ connected to 127.0.0.1:16384                               
INFO     03:02:44.912 │ [AdbDevice] AdbDevice(serial=127.0.0.1:16384)              
INFO     03:02:44.913 │ [PackageName] com.bilibili.azurlane                        
INFO     03:02:44.914 │ [Server] cn                                                
INFO     03:02:44.914 │ Screenshot interval set to 0.3s                            
CRITICAL 03:02:44.915 │ No app stop/start, because HandleError disabled            
CRITICAL 03:02:44.916 │ Please enable Alas.Error.HandleError or manually login to  
         AzurLane                                                                  
ERROR    03:02:44.917 │ RequestHumanTakeover:                                      
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\webui\process_manager.py:151 in           │
         │ run_process                                                            │
         │                                                                        │
         │   149 │   │   │   │   if e is not None:                                │
         │   150 │   │   │   │   │   AzurLaneAutoScript.stop_event = e            │
         │ ❱ 151 │   │   │   │   AzurLaneAutoScript(config_name=config_name).loop │
         │   152 │   │   │   elif func == "Daemon":                               │
         │   153 │   │   │   │   from module.daemon.daemon import AzurLaneDaemon  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │                  _ = ['--port', '22267']                           │ │
         │ │               args = Namespace(electron=True)                      │ │
         │ │ AzurLaneAutoScript = <class 'alas.AzurLaneAutoScript'>             │ │
         │ │     AzurLaneConfig = <class 'module.config.config.AzurLaneConfig'> │ │
         │ │        config_name = 'alas'                                        │ │
         │ │       console_hdlr = <RichHandler (NOTSET)>                        │ │
         │ │                  e = RequestHumanTakeover()                        │ │
         │ │               func = 'alas'                                        │ │
         │ │             parser = ArgumentParser(prog='gui.py', usage=None,     │ │
         │ │                      description=None, formatter_class=<class      │ │
         │ │                      'argparse.HelpFormatter'>,                    │ │
         │ │                      conflict_handler='error', add_help=True)      │ │
         │ │                  q = <AutoProxy[Queue] object, typeid 'Queue' at   │ │
         │ │                      0x1825e3ee9c8>                                │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\AzurLaneAutoScript\alas.py:495 in loop                              │
         │                                                                        │
         │   493 │   │   │   │   self.config.task_call('Restart')                 │
         │   494 │   │   │   # Get task                                           │
         │ ❱ 495 │   │   │   task = self.get_next_task()                          │
         │   496 │   │   │   # Init device and change server                      │
         │   497 │   │   │   _ = self.device                                      │
         │                                                                        │
         │ ╭─────────────────────────── locals ────────────────────────────╮      │
         │ │ self = <alas.AzurLaneAutoScript object at 0x000001825E127248> │      │
         │ ╰───────────────────────────────────────────────────────────────╯      │
         │                                                                        │
         │ D:\AzurLaneAutoScript\alas.py:439 in get_next_task                     │
         │                                                                        │
         │   437 │   │   │   │   if method == 'close_game':                       │
         │   438 │   │   │   │   │   logger.info('Close game during wait')        │
         │ ❱ 439 │   │   │   │   │   self.device.app_stop()                       │
         │   440 │   │   │   │   │   release_resources()                          │
         │   441 │   │   │   │   │   self.device.release_during_wait()            │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │            method = 'close_game'                                   │ │
         │ │ release_resources = <function release_resources at                 │ │
         │ │                     0x000001825EE9B708>                            │ │
         │ │              self = <alas.AzurLaneAutoScript object at             │ │
         │ │                     0x000001825E127248>                            │ │
         │ │              task = Commission (Enable, 2023-08-02 03:35:43)       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\device\device.py:212 in app_stop          │
         │                                                                        │
         │   210 │   │   │   logger.critical('No app stop/start, because HandleEr │
         │   211 │   │   │   logger.critical('Please enable Alas.Error.HandleErro │
         │       AzurLane')                                                       │
         │ ❱ 212 │   │   │   raise RequestHumanTakeover                           │
         │   213 │   │   super().app_stop()                                       │
         │   214 │   │   self.stuck_record_clear()                                │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'module.device.device.Device'>                  │ │
         │ │      self = <module.device.device.Device object at                 │ │
         │ │             0x000001825EEC72C8>                                    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         RequestHumanTakeover
```

### 截图

应用发生内部错误
×
+-------------------------- Traceback (most recent call last) ---------------------------+
|                                                                                        |
| D:\AzurLaneAutoScript\toolkit\lib\site-packages\pywebio\session\threadbased.py:254 in  |
| run                                                                                    |
|                                                                                        |
|   253                 try:                                                             |
| > 254                     callback(event['data'])                                      |
|   255                 except Exception as e:                                           |
|                                                                                        |
| +-------------------------------------- locals --------------------------------------+ |
| | callback = <function put_buttons.<locals>.click_callback at 0x000001A7918A6288>    | |
| |        e = Exception('quq')                                                        | |
| |    event = {                                                                       | |
| |                'event': 'callback',                                                | |
| |                'task_id': 'CB-click_callback-5kttUuWZSk',                          | |
| |                'data': 0                                                           | |
| |            }                                                                       | |
| |     self = <pywebio.session.threadbased.ThreadBasedSession object at               | |
| |            0x000001A7914A2908>                                                     | |
| +------------------------------------------------------------------------------------+ |
| D:\AzurLaneAutoScript\toolkit\lib\site-packages\pywebio\output.py:801 in               |
| click_callback                                                                         |
|                                                                                        |
|    800         if isinstance(onclick, Sequence):                                       |
| >  801             return onclick[btn_idx]()                                           |
|    802         else:                                                                   |
|                                                                                        |
| +--------------------------- locals ---------------------------+                       |
| | btn_idx = 0                                                  |                       |
| |    btns = [                                                  |                       |
| |               {                                              |                       |
| |                   'label': 'Raise exception',                |                       |
| |                   'value': 0,                                |                       |
| |                   'color': 'primary',                        |                       |
| |                   'disabled': False                          |                       |
| |               }                                              |                       |
| |           ]                                                  |                       |
| | onclick = [<function raise_exception at 0x000001A790401048>] |                       |
| |  values = ['']                                               |                       |
| +--------------------------------------------------------------+                       |
|                                                                                        |
| D:\AzurLaneAutoScript\module\webui\utils.py:522 in raise_exception                     |
|                                                                                        |
|   521     if x > 0:                                                                    |
| > 522         raise_exception(x - 1)                                                   |
|   523     else:                                                                        |
|                                                                                        |
| +- locals -+                                                                           |
| | x = 3    |                                                                           |
| +----------+                                                                           |
|                                                                                        |
| D:\AzurLaneAutoScript\module\webui\utils.py:522 in raise_exception                     |
|                                                                                        |
|   521     if x > 0:                                                                    |
| > 522         raise_exception(x - 1)                                                   |
|   523     else:                                                                        |
|                                                                                        |
| +- locals -+                                                                           |
| | x = 2    |                                                                           |
| +----------+                                                                           |
|                                                                                        |
| D:\AzurLaneAutoScript\module\webui\utils.py:522 in raise_exception                     |
|                                                                                        |
|   521     if x > 0:                                                                    |
| > 522         raise_exception(x - 1)                                                   |
|   523     else:                                                                        |
|                                                                                        |
| +- locals -+                                                                           |
| | x = 1    |                                                                           |
| +----------+                                                                           |
|                                                                                        |
| D:\AzurLaneAutoScript\module\webui\utils.py:524 in raise_exception                     |
|                                                                                        |
|   523     else:                                                                        |
| > 524         raise Exception("quq")                                                   |
|   525                                                                                  |
|                                                                                        |
| +- locals -+                                                                           |
| | x = 0    |                                                                           |
| +----------+                                                                           |
+----------------------------------------------------------------------------------------+
Exception: quq

**Comment by LmeSzinc** [comment]
你关闭了异常处理所以没有异常处理，这里不存在问题

> CRITICAL 03:02:44.915 │ No app stop/start, because HandleError disabled            
> CRITICAL 03:02:44.916 │ Please enable Alas.Error.HandleError or manually login to AzurLane

**Comment by 555mimipp** [comment]
噢噢，好了，现在又能使用了嘿嘿。谢谢大大
