### ISSUE TITLE
深渊海域中重启会导致直接退出深渊海域

### ISSUE THREAD

**Issue by lan23333** [LmeSzinc/AzurLaneAutoScript#2964]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题，不知道在别的海域会不会有同样的问题

### 如何复现

1. 进入深渊海域
2. 无限Loading触发重启游戏动作
3. alas会退出当前深渊海域，寻找下一个

### 预期行为

重启后应该继续确保当前海域完成才退出进入下一个

**Comment by LmeSzinc** [comment]
需要提供 log

**Comment by guoh064** [comment]
这又是一个work as intended的情况：`os_init`会检测当前海域是不是特殊海域，是则调用退出。这个在海域执行完毕时能够加快速度，但是特殊海域有几率在重启（包括闪断推送）的情况下被干掉。
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/a78783741d86dbc17aebb72b9d382070eba3f85b/module/os/map.py#L28-L78
我的建议是加一行点一次自律的操作，如果出现2个/4个以上的info_bar就认为自律结束，否则仍然可以继续自律；
