### ISSUE TITLE
现在模拟器的分辨率还是一定得是1280x720吗？

### ISSUE THREAD

**Issue by 450177215** [LmeSzinc/AzurLaneAutoScript#2966]
### 你的功能请求是否与问题有关？

rt

**Comment by cjwmiku** [comment]
Alas 是为长时间运行，甚至是 7*24 运行而设计的，这一点与市面上多数针对手机的脚本不同。Alas 在早期已经放弃了对安卓真机的支持，同时也放弃了对除 1280x720 以外的分辨率的支持。
使用 1280x720 分辨率的原因是：

720p 在图像清晰度和截图耗时之间有较好的平衡，480p 下海图识别正确率明显下降，1080p 截图耗时几乎翻倍
异型屏没有统一的标准，适配非 16:9 分辨率带来的维护成本和获得的收益不符
