### ISSUE TITLE
军火商（通用商店）过滤器默认不应该有FoodT6 、 FoodT5条目（或者加入说明提醒）

### ISSUE THREAD

**Issue by gsxgmpkt9020** [LmeSzinc/AzurLaneAutoScript#2972]
### 你的功能请求是否与问题有关？

一般来说最广大的指挥官很难有时间24h推图（也许）

金钱溢出的话已经有选项可以“消耗溢出物资”

对于没时间的指挥官有时候会钱比油少，所以如果没有特地注意过滤器的条目的话，很难发现有FoodT6 、 FoodT5条目是默认购买的。很多人Food都是完全溢出的，金钱更紧缺一些

<img width="1314" alt="Snipaste_2023-08-05_07-54-00" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/c2d39701-496c-4996-a377-bc089c509943">

<img width="804" alt="Snipaste_2023-08-05_07-49-36" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/2074641/43b672b0-c807-4c0b-bd46-2fb19df17fb7">

**Comment by cjwmiku** [comment]
能不能动下你的小手，删了不就行了，过滤器也都有wiki，还有你怎么断定别人和你缺这点物资的

**Comment by 24k12315** [comment]
foodt5和foodt6只能通过红尖尖购买，性价比远远超过物资。如果不想购买这两个东西。可以通过alaswiki的物品筛选，自行删除该物品的自动购买

**Comment by cjwmiku** [comment]
> foodt5和foodt6只能通过红尖尖购买，价值极高超过物资。如果不想购买这两个东西。可以通过alaswiki的物品筛选，自行删除该物品的自动购买

alas并不会买需要红尖尖的物品

**Comment by D9Lose** [comment]
> > foodt5和foodt6只能通过红尖尖购买
> 
> * 你没有仔细看置顶图片吗？6000的皇家料理不是foodt5？在军火商购买不就没有花费红尖？
> * 是可以自行删除过滤器，但是并不是每个人都能第一时间发现这个过滤器，特别是ALAS新手，这个默认的FOOD过滤（准确说是白名单）不适合很多人（除非24h挂机的骨灰级玩家）。

虽然但是，alas的设计场景不就是7*24小时全托管吗？ 物资是溢出的，需要买东西“浪费掉”，才能保持不发生物资溢出（60w）报错。 而alas的默认条件又包含了不沉船、A胜，那说明alas本身就不是新人向的脚本，本身有一定练度和东西，再使用alas托管会好些。

**Comment by cjwmiku** [comment]
你用工具前，不看工具有什么功能就直接用吗。
你怎么觉得别人和你一样缺这点物资。
再说不想买食物的会自己去删掉的。
还有我感觉t5和t6属于高价值的，能提高经验收益，为什么不买呢？

**Comment by LmeSzinc** [comment]
1. 使用每日产出的物资购买钻石道具，是赚的
2. 即便食物溢出，钻石道具也会带来额外经验收益
3. 游戏物资收益已经改版很久，每天正常打高级图能有很多物资

基于这几点，默认过滤器购买食物没有问题
