### ISSUE TITLE
希望ALAS的Maa插件添加新肉鸽的选项

### ISSUE THREAD

**Issue by Gruddieu** [LmeSzinc/AzurLaneAutoScript#2974]
### 你的功能请求是否与问题有关？

因为MAA的稳定版/公测版更新了新肉鸽的选项，所以希望ALAS的Maa插件可以添加新肉鸽选项

### 其他内容

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/77685704/0e3a5cc0-20cc-4c8b-bbe8-bf30729d6ed8)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/77685704/3170bf77-a6e4-418a-97ad-b633ecdda250)

**Comment by LmeSzinc** [comment]
#2976
