### ISSUE TITLE
Alas有适配更高分辨率的打算吗

### ISSUE THREAD

**Issue by sasaku-s** [LmeSzinc/AzurLaneAutoScript#2985]

**Comment by cjwmiku** [comment]
![Uploading Screenshot_2023-08-07-08-39-09-810_com.android.browser.jpg…]()

**Comment by cjwmiku** [comment]
Alas 是为长时间运行，甚至是 7*24 运行而设计的，这一点与市面上多数针对手机的脚本不同。Alas 在早期已经放弃了对安卓真机的支持，同时也放弃了对除 1280x720 以外的分辨率的支持。

放弃安卓真机的原因是：

安卓机在长时间运行下，容易出现黑屏/假死的情况
部分安卓机型截图会压缩，早期代码中有不少基于颜色识别的方法
需要另外占用一台安卓机。由于 ocr 模型的存在，将 Alas 迁移至安卓存在困难
使用 1280x720 分辨率的原因是：

720p 在图像清晰度和截图耗时之间有较好的平衡，480p 下海图识别正确率明显下降，1080p 截图耗时几乎翻倍
异型屏没有统一的标准，适配非 16:9 分辨率带来的维护成本和获得的收益不符

**Comment by sasaku-s** [comment]
明白了，谢谢大佬！

**Comment by sasaku-s** [comment]
> Alas 是为长时间运行，甚至是 7*24 运行而设计的，这一点与市面上多数针对手机的脚本不同。Alas 在早期已经放弃了对安卓真机的支持，同时也放弃了对除 1280x720 以外的分辨率的支持。
> 
> 放弃安卓真机的原因是：
> 
> 安卓机在长时间运行下，容易出现黑屏/假死的情况 部分安卓机型截图会压缩，早期代码中有不少基于颜色识别的方法 需要另外占用一台安卓机。由于 ocr 模型的存在，将 Alas 迁移至安卓存在困难 使用 1280x720 分辨率的原因是：
> 
> 720p 在图像清晰度和截图耗时之间有较好的平衡，480p 下海图识别正确率明显下降，1080p 截图耗时几乎翻倍 异型屏没有统一的标准，适配非 16:9 分辨率带来的维护成本和获得的收益不符

谢谢大佬，明白啦！
