### ISSUE TITLE
希望增加一个异地登录导致自身账号登出异常，不处理这个异常的开关。

### ISSUE THREAD

**Issue by wxnsznbd** [LmeSzinc/AzurLaneAutoScript#2993]
### 你的功能请求是否与问题有关？

在别人异地登录账号后，alas往往直接选择登录，再把别人挤下去。能否在异常处理那加一个判断，如果判断出是异地登录导致的异常，那么是否可以让人选择是否处理这个异常，是直接重登还是放着不管。

### 解决方案

能否在异常处理之前，检测一下是否为异地登录导致自身账号登出，所导致的异常，并在异常处理那增加一个选项，异地登录导致账号登出是否重登，

### 其他内容

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/58931297/02d16d8c-eac3-46c1-8edd-ae525e3cc5a4)

**Comment by wxnsznbd** [comment]
能否在异常类型里加一项异常，由异地登录引起的异常，然后给一个自定义设置，是否处理这个异常重登，或者保持不变。

**Comment by cjwmiku** [comment]
异地登录可以先把alas关了，alas有远程网页控制

**Comment by wxnsznbd** [comment]
自己看了源码，改了改，勉强能用。就是每回开alas都得覆盖一次

**Comment by cjwmiku** [comment]
> 自己看了源码，改了改，勉强能用。就是每回开alas都得覆盖一次

把网页放桌面就行了，直接通过网页开关
