### ISSUE TITLE
MUMU模拟器12 使用Alas时严重卡顿

### ISSUE THREAD

**Issue by sasaku-s** [LmeSzinc/AzurLaneAutoScript#3008]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

电脑：
i7-11800h
RTX3060 laptop
16GB内存

如果单独使用MUMU模拟器游戏很流畅（我锁的60FPS），Alas启动之后30FPS上下浮动。但是都能运行，也不报错，查看任务管理器占用都不高。这个问题是从7月25日左右开始出现的，一开始以为是MUMU或Alas需要更新，全部更新到最新版还是没有解决。Alas的性能测试也跑了，模拟器安卓型号也是>9（安卓12）。暂时没使用过其他模拟器。

尚未解决。（挠头）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sasaku-s** [comment]
> #2968

已解决

对，但好别扭。
在您回复之前，我换了一下夜神模拟器，可以正常使用。然后看到您的方法，我想试一下，但。。。。。我是家庭版，甚至没有hyper-v。然后我思索一会，先安装了hyper-v，给他打开重启，之后再关闭重启，然后mumu就也好了（麻了）。

**Comment by sasaku-s** [comment]
其实没有解决。
但我觉得是mumu的问题，我尝试了其他模拟器都还好。同时我也觉得我的PC有问题（但我想不通），启动alas一定会有降帧，mumu最严重直接掉一半，其他一般降5左右。

系统是Win11家庭版 23H2 22631.2129

**Comment by AzusaYukina** [comment]
其实mumu12最近某次更新之后，只要开了HyperV之后性能就严重下降……
隔壁碧蓝甚至直接从165帧掉到个位数……
暂时不清楚mumu12更新了什么，可能退版本是最优解决方法

**Comment by sasaku-s** [comment]
> 其实mumu12最近某次更新之后，只要开了HyperV之后性能就严重下降…… 隔壁碧蓝甚至直接从165帧掉到个位数…… 暂时不清楚mumu12更新了什么，可能退版本是最优解决方法

目前好像正常了

我通过重新开关内核隔离和DMA之后，他现在似乎正常了（我拉的90fps，能稳在88左右），我也不知道MuMu在整啥花活。

**Comment by suzukiayato** [comment]
我使用的是3.5.12版本，也没打开内存完整性和Hyper-V，依旧掉帧非常严重，但是之前用雷电模拟器的时候并没有这个问题，感觉应该就是模拟器哪里出问题了。

**Comment by sasaku-s** [comment]
> 

我重装系统了，换了win10专业版，现在没问题。
我现在觉得是win11的问题，他可能为了兼容桌面App做了微软自家虚拟机的接口兼容。
但如果不重装就只能换模拟器，我除了mumu12都可以用。

**Comment by suzukiayato** [comment]
我目前用的就是Win10专业版22H2，弄了一下无论如何都是会卡顿掉帧，看来也只好换一个模拟器了，我原本是用的雷电好长时间了都没有这种情况，哪怕看见别人说不要用雷电，就是嫌雷电占用内存太高用起来卡才卸载了装了MuMu12，没想到居然会有这种问题，看来还是只能再卸载去换一个别的模拟器了。

**Comment by iceynano** [comment]
http://a11.gdl.netease.com/MuMuNG-setup-V3.5.8.1940-0813210244.exe
这是mumu12 V3.5.8版本的下载地址 [23/08/21 验证可用]
PS: 此条回复作为存档使用

**Comment by cifei1** [comment]
Win10 ，mumu12--3.5.12(1972)，已关闭内存完整性和Hyper-V，也还是很卡，准备再等等mumu更新看，不行就换别的模拟器了

**Comment by sasaku-s** [comment]
mumu12✘
mumu6✔
烂透了，等更新

**Comment by esbylan** [comment]
说一下我的解决方案：
我个人是win11家庭版 dev版本的，电脑是华为的办公本，11代的英特尔低压U，16g内存无独显，配置算比较拉胯的。
用的mumu12，不开alas模拟器60帧没问题，开了之后直接变个位数帧数。
issue里提到过的方案例安装hyper-v之后开启再关闭、关闭内核隔离都没有效果。
然后我把mumu12卸载了换成mumu6，开启后模拟器提示我要关闭hyper-v，用了模拟器的一键关闭之后重启电脑，模拟器依旧提示需要关闭hyper-v，遂按照[mumu的教程](https://mumu.163.com/help/20210511/35041_946700.html)，关闭了所有相关windows功能、禁用hyper-v相关的所有windows服务，模拟器依旧提示需要关闭hyper-v
然后我发现了这个教程里有一个一键关闭hyper-v的脚本文件，
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/31299495/106b3d14-b0a1-4d8e-9061-e7cd9791a4e4)
下载之后以管理员身份运行了脚本，重启电脑，在BIOS界面会提示要关闭两个功能，按WIN or F3确认关闭，全部关闭之后进入系统，再开启mumu6就不提示需要关闭hyper-v了，开启alas之后也是60帧流畅运行。
**这里我附上mumu教程里的一键脚本**->>[自动关闭Hyper-V/VBS](https://note.youdao.com/share/?token=D448113D8FA342D49C7059C7CB922D70&gid=93078739)
由于我网络环境限制，碧蓝的资源包下载时间实在是太久了，加上安装完还要改设置，这里我就不回去试mumu12了，如果有mumu12的朋友有这个帧数过低的问题可以用mumu这个关闭hyper-v的脚本测试一下有没有用。

**Comment by MrQMou** [comment]
> 说一下我的解决方案： 我个人是win11家庭版 dev版本的，电脑是华为的办公本，11代的英特尔低压U，16g内存无独显，配置算比较拉胯的。 用的mumu12，不开alas模拟器60帧没问题，开了之后直接变个位数帧数。 issue里提到过的方案例安装hyper-v之后开启再关闭、关闭内核隔离都没有效果。 然后我把mumu12卸载了换成mumu6，开启后模拟器提示我要关闭hyper-v，用了模拟器的一键关闭之后重启电脑，模拟器依旧提示需要关闭hyper-v，遂按照[mumu的教程](https://mumu.163.com/help/20210511/35041_946700.html)，关闭了所有相关windows功能、禁用hyper-v相关的所有windows服务，模拟器依旧提示需要关闭hyper-v 然后我发现了这个教程里有一个一键关闭hyper-v的脚本文件， ![image](https://user-images.githubusercontent.com/31299495/263631511-106b3d14-b0a1-4d8e-9061-e7cd9791a4e4.png) 下载之后以管理员身份运行了脚本，重启电脑，在BIOS界面会提示要关闭两个功能，按WIN or F3确认关闭，全部关闭之后进入系统，再开启mumu6就不提示需要关闭hyper-v了，开启alas之后也是60帧流畅运行。**注意运行完脚本一定要重启电脑，然后在BIOS界面按提示关闭相关功能，而不是像官方教程里说的重启模拟器。** **这里我附上mumu教程里的一键脚本**->>[自动关闭Hyper-V/VBS](https://note.youdao.com/share/?token=D448113D8FA342D49C7059C7CB922D70&gid=93078739) 由于我网络环境限制，碧蓝的资源包下载时间实在是太久了，加上安装完还要改设置，这里我就不回去试mumu12了，如果有mumu12的朋友有这个帧数过低的问题可以用mumu这个关闭hyper-v的脚本测试一下有没有用。

mumu12 版本3.5.15来反馈，未执行此bat文件之前，不开启alas稳定60帧，开启后在5—40帧之间波动，
执行此bat文件并重启后，不开启alas稳定60帧，开启后在30-55帧之间波动。
我的设备情况：联想小新air14锐龙 2020版，r5-4600u ，无独显。

**Comment by linlin2557** [comment]
> > 说一下我的解决方案： 我个人是win11家庭版 dev版本的，电脑是华为的办公本，11代的英特尔低压U，16g内存无独显，配置算比较拉胯的。 用的mumu12，不开alas模拟器60帧没问题，开了之后直接变个位数帧数。 issue里提到过的方案例安装hyper-v之后开启再关闭、关闭内核隔离都没有效果。 然后我把mumu12卸载了换成mumu6，开启后模拟器提示我要关闭hyper-v，用了模拟器的一键关闭之后重启电脑，模拟器依旧提示需要关闭hyper-v，遂按照[mumu的教程](https://mumu.163.com/help/20210511/35041_946700.html)，关闭了所有相关windows功能、禁用hyper-v相关的所有windows服务，模拟器依旧提示需要关闭hyper-v 然后我发现了这个教程里有一个一键关闭hyper-v的脚本文件， ![image](https://user-images.githubusercontent.com/31299495/263631511-106b3d14-b0a1-4d8e-9061-e7cd9791a4e4.png) 下载之后以管理员身份运行了脚本，重启电脑，在BIOS界面会提示要关闭两个功能，按WIN or F3确认关闭，全部关闭之后进入系统，再开启mumu6就不提示需要关闭hyper-v了，开启alas之后也是60帧流畅运行。**注意运行完脚本一定要重启电脑，然后在BIOS界面按提示关闭相关功能，而不是像官方教程里说的重启模拟器。** **这里我附上mumu教程里的一键脚本**->>[自动关闭Hyper-V/VBS](https://note.youdao.com/share/?token=D448113D8FA342D49C7059C7CB922D70&gid=93078739) 由于我网络环境限制，碧蓝的资源包下载时间实在是太久了，加上安装完还要改设置，这里我就不回去试mumu12了，如果有mumu12的朋友有这个帧数过低的问题可以用mumu这个关闭hyper-v的脚本测试一下有没有用。
> 
> mumu12 版本3.5.15来反馈，未执行此bat文件之前，不开启alas稳定60帧，开启后在5—40帧之间波动， 执行此bat文件并重启后，不开启alas稳定60帧，开启后在30-55帧之间波动。 我的设备情况：联想小新air14锐龙 2020版，r5-4600u ，无独显。

mumu12版本3.5.21反馈，没有使用bat文件，但创建了一个独立的不使用hyper-V的启动项，在主启动项内勾选并启用Hyper-V后以不使用Hyper-V启动项启动系统，在不启动alas的情况下稳定60帧，开启后在30-55帧波动
我的设备情况：联想小新Air14锐龙2020版，r5-4600U，无独显，Windows11 22H2 专业工作站版本

**Comment by XiaJiLun** [comment]
i7+4060运行alas之后GPU不跑了，帧数就个位数，hyper-v开不开都一样，GPU就是跑不起来
<img width="1137" alt="屏幕截图 2024-01-13 162753" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/110099645/2ebb54db-1f0a-4f9d-86f5-8cc28b454373">
<img width="965" alt="屏幕截图 2024-01-13 162910" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/110099645/90711f16-d56a-4114-89a0-a16afe7ab707">
