### ISSUE TITLE
为什么脚本在2小时紫箱子和2小时魔方里面选择了紫箱子

### ISSUE THREAD

**Issue by xingyedekong** [LmeSzinc/AzurLaneAutoScript#3010]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

为什么脚本在2小时紫箱子和2小时魔方里面选择了紫箱子
我该如何调整委托过滤器？
感谢各位大佬

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![QQ图片20230814034942](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135824425/1364e395-1a4d-44cd-a38a-b15972393c56)
![QQ图片20230814035022](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135824425/b7ae3bb9-38f8-4e21-ae3f-a92ae48e09c5)
![QQ图片20230814035315](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135824425/6dca7151-ff7f-4876-ba9d-0840ba9e36ca)

**Comment by programerluffy** [comment]
这两个都属于 **Daily 每日委托** 里的 **Resource 日常资源开发**，没有明确的优先级，通常说的策略，一般是指紧急委托里的魔方>石油。如果能做完每日委托，可以不用管它

**Comment by LmeSzinc** [comment]
10个高收益每日委托是必须要完成的，无需区分
