### ISSUE TITLE
在出击选项追加紧急委托的更换舰船

### ISSUE THREAD

**Issue by CuRSaK** [LmeSzinc/AzurLaneAutoScript#3025]
### 你的功能请求是否与问题有关？

这样就可以在极低耗(3油)的情况下无需手动更换舰船，以确保可以7x24全自动运行，将效益最大化

**Comment by guoh064** [comment]
请使用紧急委托功能。该功能（在活动适配后）能够识别活动关卡并出击。

**Comment by CuRSaK** [comment]
> 请使用紧急委托功能。该功能（在活动适配后）能够识别活动关卡并出击。

原来是这样！被名字误导了，感谢！
