### ISSUE TITLE
科研自定义优先度顺序执行错误

### ISSUE THREAD

**Issue by MyMaHck** [LmeSzinc/AzurLaneAutoScript#3027]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

科研自定义优先度中：S6-H2＞S6-G2.5，实际log相反
将设置与log截图全部贴出
又或者是自定义语句可能有问题，烦请指教（参考了自定义的示例）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/117053757/4ceb4449-fa3d-464e-9e2a-55d7a2732c4e)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/117053757/b1cdf945-259c-416b-ba6e-180661f8a0f5)

**Comment by LmeSzinc** [comment]
把过滤器复制粘贴出来，S6-Hindenburg8 后面的大于号的打开角度要小一点

中文大于号实在是太多了，我目前找到的有
```
> \u003E correct
＞ \uFF1E
﹥ \uFE65
› \u203a
```

**Comment by MyMaHck** [comment]
> 把过滤器复制粘贴出来，S6-Hindenburg8 后面的大于号的打开角度要小一点
> 
> 中文大于号实在是太多了，我目前找到的有
> 
> ```
> > \u003E correct
> ＞ \uFF1E
> ﹥ \uFE65
> › \u203a
> ˃ \u02c3
> ᐳ \u1433
> ❯ \u276F
> ```

感谢！确实有几个是微软中文输出法打出的大于号，我已经全部改为英文大于号

**Comment by MyMaHck** [comment]
@LmeSzinc @LostMyMind 感谢！确实有几个是微软中文输出法打出的大于号，我已经全部改为英文大于号，打扰了！
