### ISSUE TITLE
对于社区管理违背和谐共处原则，对我进行人身攻击的不能理解

### ISSUE THREAD

**Issue by unicorn5514** [LmeSzinc/AzurLaneAutoScript#3032]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我在alas社区QQ群因使用手机拍摄屏幕进行提问时，遭到了群管理等人的人身攻击，以及大量侮辱性词汇。我在提问时由于电脑并没有登陆QQ，没有采用截图方式进行提问，对此我表示歉意。但是我认为群管理对我的辱骂及人身攻击是并不合理且违反社区规则:“这个社区的目标是让 Alas 用户体验到Lme的亚撒西！ ”“以礼貌和尊重的态度进行沟通 ”。若群内禁止使用手机拍摄的图片，或许可以发布公告，而不必对不知道此规则的人进行辱骂。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望得到管理人员的道歉。

### 截图

![Cache_6a836e9db5d2c751](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/0a95134d-cfe6-4a44-b6be-b14483d408b5)
![Cache_-14d308585964876e](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/cecab1ff-9b4f-4633-83cb-ada34b3206d8)
![QQ截图20230819172251](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/9c64e907-d683-4480-a320-e8cd657b8df1)
![QQ截图20230819172317](htt
![QQ截图20230819172459](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/64458323-7973-4e62-a9b3-9d195a9c4c51)
ps://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/8a4c57fd-c5d9-4368-bc43-766985536412)
![QQ截图2023081917
![QQ截图20230819172514](https://github.com/L
![QQ截图20230819172622](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/60a64afe-ae91-4137-bfb3-262193f82417)
meSzinc/AzurLaneAutoScript/
![QQ截图20230819173806](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/d4cef4f0-b42a-48a7-96c4-10cbfaf1beb4)
assets/129422686/634d971f-cb42-44ec-b898-6d73b2ac93d4)
2424](https://github.com/L
![QQ截图20230819173745](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/1f1e6c03-5939-4415-a825-b835a70a76db)
meSzinc/AzurLaneAutoScript/assets/129422686/97ba51bc-f090-4081-96cb-9c396a932a3e)
![QQ截图20230819172532](https://
![QQ截图20230819172554]
![QQ截图202308191726
![QQ截图20230819172615](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/29baf4ca-a9e8-42f7-96ce-142e18a297f0)
07](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/d008af2a-7741-4359-9890-2cc473d930ff)
(https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/992c9d6a-293a-454a-a858-620df903cf25)
github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/9469fa58-f38e-418b-a58e-ee39b80c564d)

![QQ截图20230819172400](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/648c58ac-5b32-4086-96db-bd61a8ef81bc)

**Comment by unicorn5514** [comment]
[](url)
![QQ截图20230819172554](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/6b14ec35-3181-45c1-bf49-cd701ce6ecbb)

**Comment by unicorn5514** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/feaee803-de80-4798-969d-06047d105d79)

**Comment by unicorn5514** [comment]
[](url)
![QQ截图20230819172317](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/1f49a2c6-f396-4411-970a-ac9da0025d08)

**Comment by unicorn5514** [comment]
![QQ截图20230819172317](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/129422686/0b471335-d3d8-46f4-88fd-01937a697496)

**Comment by KamikoshiSorawo** [comment]
又不是拍log会看不清啥的 就算你是电脑截图这b东西肯定也会攻击你 问你为啥不看说明书

**Comment by LmeSzinc** [comment]
别装了看着就让人恶心，耻辱柱上记录得很清楚 https://github.com/Muiuploii/AlasCommunityShameList/issues/13

群友开始就叫你别拍屏要截图，一般人就说 稍等我重新截一下，或者不废话直接发张新的。你是完全没看见，然后给自己找的借口是我不想登QQ，真是重量级回答，礼貌已经给过你了结果你是不吃软的只吃硬的，跟个大爷一样等着被伺候。

群公告和github都写了，`在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你`，你是一点儿也没做到，花费5秒钟就幻想有客服来服务你，你不尊重别人的时间别人为什么要尊重你

还群公告没写不能拍屏所以你不能罚我，我的天，跟老师问你为什么没交作业学生回答我忘带了一般的借口，群公告是不是得全文粘贴中华人民共和国刑法你才知道不能杀人？成年人了，什么事情该做什么事情不该做，5分钟思考和准备如何理解，不应该由我来教会与你

**Comment by iceynano** [comment]
如果你认为社区言论使你感到不愉快，请你自行离开，我们素来没有留客的传统

**Comment by huayihui2022** [comment]
qq懒得上，提issue发这么多截图倒是挺勤快。和我在二群预言的一样，lme还得自己再骂你一顿，你不尊重人为什么想别人尊重你

**Comment by hunrong** [comment]
过于基础的使用问题，杂乱的聊天记录，令人不适的拍屏。原来你的电脑当时并没有登陆QQ是他人的问题，没有采用截图方式进行提问也是理所应当。被攻击先发issues控诉，不愿阅读功能描述，忽略编辑者们整理好的注释，还奢望你和你那糟糕的拍屏技术会获得友善的回复。
以Alas立项的初衷和现在的使用/维护/更新体验来说，社区环境为什么会变成这样我也不能理解呢，也许你和曾经那些热爱拍屏/随意提问/log是啥/无视答复/旧问重提的过客们，会有什么头绪。
