### ISSUE TITLE
新活动一直无法运行

### ISSUE THREAD

**Issue by Bigorange11** [LmeSzinc/AzurLaneAutoScript#3035]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

新活动一直都无法运行，一直如此提示，请问是我设置的问题吗
![QQ截图20230819184127](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135260683/85a5cc25-e848-488f-954d-206509345a5d)
![QQ截图20230819184143](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135260683/6e604b82-2058-4a68-8c9d-0eb5b10f4a66)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Bigorange11** [comment]
> 

对耶！把前面的点了就好了，感谢！

**Comment by guoh064** [comment]
其实lme做了，你只需要直接填写a1就可以了

**Comment by bookbug666** [comment]
A1之前的沒有做，但中間跳出來新的有做
至少先點掉E-01到E-03開出A1之後就能正常使用alas開荒了

**Comment by mulaikurisu** [comment]
哈哈，e01根本就不是关卡，填a1c1就会自动点掉前面的剧情
