### ISSUE TITLE
请问这个critical怎么解决，alas会发生错误并停止运行

### ISSUE THREAD

**Issue by Bread200** [LmeSzinc/AzurLaneAutoScript#3037]
log截图如下，alas会直接发生错误停止运行，我六点起床发现两点多就停止运行了
![相关log](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/137496220/5733ab2d-f0bb-4959-b777-396956ae1a67)
我在error文件夹里没有发现相关log和游戏截图，只能手动截图游戏画面，合计获得奖励（自律寻敌结束后展示获得物品）的框被我点掉了，所以我手动加了一个还原当时的情况
![未知错误(1)](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/137496220/95f258bf-80b1-40e1-9e50-53caf08673d2)

**Comment by Bread200** [comment]
合计获得奖励的框一般是这样
![合计获得奖励](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/137496220/5d89d294-52d9-48dc-ae9a-ed31bbe4e77e)

**Comment by AzusaYukina** [comment]
用的云手机吗，看记录很像我在 #2991 里面的现象
如果是的话就是因为云手机太慢了

**Comment by Bread200** [comment]
> 用的云手机吗，看记录很像我在 #2991 里面的现象 如果是的话就是因为云手机太慢了

我是用的mumu模拟器，我看了一下当天的log，和你的log区别还蛮大的，我也不确定是不是太卡了，主要是这句话“Please finish the story mode of OpSi to unlock auto search before using any OpSi  functions”我不能理解，好像是让我先通关大世界主线，但是我已经把大世界主线打完了，具体怎么翻译我也不是很了解

**Comment by 24k12315** [comment]
进海域默认开启自律关了吗

**Comment by Bread200** [comment]
> 进海域默认开启自律关了吗

关了的，我用了两个月了吧，就出现了那两次，最近也没出现了

**Comment by cifei1** [comment]
同样问题，请问默认开启自律那个开关是碧蓝的还是alas的？

**Comment by Bread200** [comment]
[https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2982](url)

**Comment by Bread200** [comment]
#2942

**Comment by Bread200** [comment]
这个问题是无法解决，还是没必要解决，请问有相关人员回复一下吗

**Comment by LmeSzinc** [comment]
8月已经结案陈词了
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/34accfb5-addd-42ac-9346-b2938253e758)

**Comment by Bread200** [comment]
> 8月已经结案陈词了 ![image](https://user-images.githubusercontent.com/37934724/275224794-34accfb5-addd-42ac-9346-b2938253e758.png)

1.我关了自律，我关了自律，我关了自律，重要的事情说三遍，我从一开始使用我就是严格按照了使用规则，并且检查过至少2次，这个回复之后我又检查了很多次但还是会出现这个问题
2.在我回复我是否关了之前，为什么要默认我没有关自律，并将这个issue设置为wrong settings
3.有其他人也出现了这个问题， #3153 ，包括这个issue里也有人
4.如果有需要我可以录屏证明，但这个问题还不知道具体原因，也不知道什么时候会出现，可能需要一段时间
5.我经过观察，很大可能是在点击计划作战之后，右边的三个按钮变成了两个，“自律寻敌”这个按钮不见了导致出现了这个问题，理由如下：
我只记住了多少分钟，大概是在15:33的时候我的alas报错并停止运行，但我的模拟器继续运行到了15:38，遇到了塞壬装置才停止，也就是这个报错是在点击了计划作战之后才出现的，但我当时没有录屏，有需要我可以24h录屏看能不能复现
@LmeSzinc
