### ISSUE TITLE
alas设置中的重启模拟器可否用于云手机重启

### ISSUE THREAD

**Issue by Luxcis** [LmeSzinc/AzurLaneAutoScript#3046]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

星界云手机运行时间长了之后截图性能下降很多，导致凌晨执行任务经常报错，需要重启后才能解决

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

<img width="1018" alt="after" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/49968787/dc70bfe5-cd1e-4031-9827-b4fe50af1852">
<img width="1034" alt="before" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/49968787/19c5204c-2f7a-4838-aa95-540fb3de1105">

### 还有别的吗？

今天的运行错误日志
[logs.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12424921/logs.zip)

**Comment by guoh064** [comment]
#2995

**Comment by Luxcis** [comment]
> #2995

这个已经合并到当前版本了吗？
