### ISSUE TITLE
feature:希望添加自动更新功能

### ISSUE THREAD

**Issue by Nicholasjl** [LmeSzinc/AzurLaneAutoScript#3050]
### 你的功能请求是否与问题有关？

即检测到更新后无需手动确认，自动升级alas。

### 解决方案

添加选项：自动更新，勾选后检测到远程的更新会自动在空闲时执行更新逻辑

**Comment by guoh064** [comment]
如果你什么操作都没有做的话，每天半夜会自动更新的。时间大约是三点

**Comment by Nicholasjl** [comment]
好的，谢谢，没有感知到这个功能，原来已经默默的做了
