### ISSUE TITLE
Alas使用了内建adb而非环境里的adb

### ISSUE THREAD

**Issue by TBB000623** [LmeSzinc/AzurLaneAutoScript#3055]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我不清楚Alas会在什么情况下会使用内建的`\toolkit\Lib\site-packages\adbutils`里面的adb，但是我知道它和我环境里面的adb不是同一个版本的，所以有时在有Alas的情况下再打开其它脚本会反复出现连接不上的问题（其它脚本使用我环境的`adb`命令）。我目前的其它脚本都可以指定（或者默认的使用）我环境里的`adb`位置。
我观察到如果已经打开了adb, 那Alas会自动使用这个已打开的；但是如果adb不在进程里面，似乎偶尔会打开内建的那个adb。有没有办法解决这个问题，或者是否可以在Alas内部也设置调用adb的命令，留空的时候使用内建adb？

### 如何复现

尚且没有观察到稳定复现的步骤

### 预期行为

使用环境里的`adb`命令，而非快速安装后脚本自带的adb

**Comment by illyaaaa** [comment]
# config/deploy.yaml
49~53 行
Adb:
    # Filepath of ADB executable `adb.exe`
    # [Easy installer] Use './toolkit/Lib/site-packages/adbutils/binaries/adb.exe'
    # [Other] Use you own latest ADB, but not the ADB in your emulator
    AdbExecutable: E://adb.exe 
    ↑ 替换为你的 adb 地址

**Comment by LmeSzinc** [comment]
1. 环境变量里的adb是什么版本？
2. `其他脚本` 是什么？

**Comment by TBB000623** [comment]
> 1. 环境变量里的adb是什么版本？
> 2. `其他脚本` 是什么？

在Terminal中执行`adb`得到
`Android` Debug Bridge version 1.0.41
Version 33.0.2-8557947
Installed as C:\ADB\platform-tools\adb.exe`

我以MAA为例子。我的Alas会长期保持后台状态（但未必总是执行任务），在Alas的平台之外我会单独打开MAA配置任务，此时MAA的消息平台中会经常性的出现长时间尝试连接模拟器（作为对比，我MAA配置里填入了环境中adb的绝对路径，以及对应的模拟器内置的adb已经被我用同名同版本的文件替代，后台没有adb服务时MAA单独运行尚未出现问题），此时检查后台发现运行的adb服务来自于Alas内置的adb，关闭adb服务后重新执行MAA和Alas运行正常。

**Comment by TBB000623** [comment]
> #config/deploy.yaml
> 
> 49~53 行 Adb: # Filepath of ADB executable `adb.exe` # [Easy installer] Use './toolkit/Lib/site-packages/adbutils/binaries/adb.exe' # [Other] Use you own latest ADB, but not the ADB in your emulator AdbExecutable: E://adb.exe ↑ 替换为你的 adb 地址

依照该方法后不再出现问题，不能复现当时场景，视为已解决
