### ISSUE TITLE
傻瓜式安装法alas.bat 无法正确连接雷电模拟器4.0.47

### ISSUE THREAD

**Issue by wsds321** [LmeSzinc/AzurLaneAutoScript#307]
运行环境雷电模拟器4.0.47出现.
配置环境后打开alas.bat,链接雷电模拟器时输入 SERIAL 时候 反复尝试emulator-5554和127.0.0.1:5555都不能够链接
选择手动设置后设置Serial为emulator-5554,无法正确识别与连接.
情况见图
![abd](https://user-images.githubusercontent.com/77583226/104850620-13778d80-592b-11eb-9346-67eefc56bcd3.jpg)

**Comment by LmeSzinc** [comment]
雷电模拟器是很魔法
建议直接用快捷方式打开, 见 [安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn) 中的 "快捷方式运行" 一小节, 然后检查模拟器连接
