### ISSUE TITLE
大世界港口行为改变导致EMP减益无法自动消除

### ISSUE THREAD

**Issue by guoh064** [LmeSzinc/AzurLaneAutoScript#3076]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

9月1日大世界更新后，在港口所在海域会直接显示入港按钮，这导致`module.os.map`中`port_goto`会直接显示Arrive port而不真正移动船只，这变相导致了EMP减益消除不掉。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12503647/log.txt)

### 截图

![port](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/50830808/ec7f9b83-0374-4d73-a4fb-37b588b13154)
![port2](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/50830808/dadd0fd4-518b-4646-810c-ab2856c2a45b)

**Comment by bookbug666** [comment]
原來是這樣才會導致沒走
目前已知EN JP都有這類情況，TW不清楚

**Comment by guoh064** [comment]
我更新之后这个月开荒没有再碰到EMP了，很遗憾，估计得收集一段时间数据才行，或者看其他人的反馈。

**Comment by guoh064** [comment]
应该没啥问题了，这几个月都没出现开荒卡死的情况。
