### ISSUE TITLE
Feature: Better filter implement for OS shop.

### ISSUE THREAD

**Issue by SaarChaffee** [LmeSzinc/AzurLaneAutoScript#3082]
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/283ee7e687022fc425ab0048713048b57a2db4fe/module/os_handler/shop.py#L125-L142

**Comment by SaarChaffee** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/pull/3086#issuecomment-1705958349

**Comment by LmeSzinc** [comment]
lme:
> 其实这里我不是很满意，这里没用过滤器，你可以直接推翻重写
> 他是for select in item name，这个问题太大了，不仅是没有大小写判断，如果这个select是空字符串或者是单字母，那相当于是全选了

**Comment by SaarChaffee** [comment]
#3086
