### ISSUE TITLE
大世界商店更新，侵蚀一白币预留问题

### ISSUE THREAD

**Issue by DontSerious** [LmeSzinc/AzurLaneAutoScript#3085]
大世界商店更新，可以在月初就把东西买完了，刷侵蚀一的白币预留能否移除呢

**Comment by SaarChaffee** [comment]
预留了 100000
https://github.com/SaarChaffee/AzurLaneAutoScript/blob/8ac8ea9bccee1754fba875907d2c6464155a3555/module/os_handler/shop.py#L242-L246

**Comment by akiziname** [comment]
> 如果预留的移除了，会导致遇到明石，没黄币买东西，继续刷，直到把行动力刷空。 倒是感觉可用把预留的黄币数量调低一些。

可不可以做到黄币不够了以后推迟侵蚀一，跟之前低于100000一样

**Comment by akiziname** [comment]
> 如果预留的移除了，会导致遇到明石，没黄币买东西，继续刷，直到把行动力刷空。 倒是感觉可用把预留的黄币数量调低一些。

可不可以做到黄币不够了以后推迟侵蚀一，跟之前低于100000一样
如果太麻烦的话大佬直接改低一点也可以

**Comment by akiziname** [comment]
> > 
> 
> 修改*\AzurLaneAutoScript\module\config\config_manual.py第319行OS_CL1_YELLOW_COINS_PRESERVE的值为你想要的数值即可。 每次更新需要重新更改，或者可以选择将保持本地更改打开。 请谨慎填写，不然就会和我上面说的一样反而亏掉不少行动力。

感谢大佬，我自己早就改好了，被侵蚀一的那一段.config.OS_CL1_YELLOW_COINS_PRESERVE误导了，在config.py里找了好长时间没找到

**Comment by SaarChaffee** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2842#issuecomment-1621039068
