### ISSUE TITLE
adbtimeout error no matter which emulator I choose

### ISSUE THREAD

**Issue by Yashirow** [LmeSzinc/AzurLaneAutoScript#3087]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

Tried with LDPlayer, adb timeout error. Also tried with MuMu, same adb timeout error.

Don't know why it doesn't work, I followed the installation guide.

I tried to replace ldplayer adb and/or mumu's one but it doesn't change anything.

### Relevant log output

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     17:36:37.961 │ Start scheduler loop: alas                                 
INFO     17:36:37.963 │ [Server] cn                                                
INFO     17:36:37.974 │ Bind task {'Alas', 'General'}                              
INFO     17:36:40.120 │ Server "Avrora" is available.                              
INFO     17:36:40.122 │ Pending tasks: ['Commission', 'Tactical', 'Research',      
         'Dorm', 'Meowfficer', 'Guild', 'Reward', 'Freebies', 'Daily']             
INFO     17:36:40.123 │ [Task] Commission (Enable, 2020-01-01 00:00:00)            
INFO     17:36:40.124 │ Bind task {'Commission', 'Alas', 'General'}                
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     17:36:41.234 │ DEVICE                                                     
INFO     17:36:41.235 │ [IS_ON_PHONE_CLOUD] False                                  
INFO     17:36:41.236 │ [AdbBinary] D:\Games\Azur Lane\AzurLaneAutoScript\toolkit\L
         ib\site-packages\adbutils\binaries\adb.exe                                
INFO     17:36:41.239 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     17:36:41.240 │ <<< DETECT DEVICE >>>                                      
INFO     17:36:41.241 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:36:41.243 │ 127.0.0.1:7555                                             
INFO     17:36:41.251 │ already connected to 127.0.0.1:7555                        
INFO     17:36:41.252 │ [AdbDevice] AdbDevice(serial=127.0.0.1:7555)               
INFO     17:36:41.253 │ [PackageName] com.YoStarEN.AzurLane                        
INFO     17:36:41.254 │ [Server] en                                                
INFO     17:36:41.258 │ [nemud.app_keep_alive]                                     
INFO     17:36:41.259 │ Screenshot interval set to 0.3s                            
INFO     17:36:41.260 │ Patching screenshot method for mumu                        
INFO     17:36:41.261 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     17:36:41.263 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:36:41.264 │ Reverse server listening on 192.168.74.1:20657, client can 
         send data to 192.168.74.1:20657                                           
INFO     17:36:41.271 │ sdk_ver: 23                                                
INFO     17:36:41.276 │ [nc command] ['nc']                                        
ERROR    17:36:56.280 │ AdbTimeout: adb read timeout                               
INFO     17:36:56.285 │ disconnected 127.0.0.1:7555                                
INFO     17:36:56.299 │ connected to 127.0.0.1:7555                                
INFO     17:36:56.300 │ <<< DETECT DEVICE >>>                                      
INFO     17:36:56.301 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:36:56.303 │ 127.0.0.1:7555                                             
INFO     17:36:56.304 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:36:56.305 │ Reverse server listening on 192.168.74.1:20687, client can 
         send data to 192.168.74.1:20687                                           
ERROR    17:37:11.311 │ AdbTimeout: adb read timeout                               
INFO     17:37:12.317 │ disconnected 127.0.0.1:7555                                
INFO     17:37:12.328 │ connected to 127.0.0.1:7555                                
INFO     17:37:12.329 │ <<< DETECT DEVICE >>>                                      
INFO     17:37:12.330 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:37:12.333 │ 127.0.0.1:7555                                             
INFO     17:37:12.333 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:37:12.334 │ Reverse server listening on 192.168.74.1:20010, client can 
         send data to 192.168.74.1:20010
```

**Comment by LmeSzinc** [comment]
try screenshot method `DroidCast_raw`

**Comment by Yashirow** [comment]
Same error unfortunately.

<details>
<summary>log</summary>

═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     17:04:25.056 │ Start scheduler loop: alas                                 
INFO     17:04:25.059 │ [Server] cn                                                
INFO     17:04:25.069 │ Bind task {'Alas', 'General'}                              
INFO     17:04:27.069 │ Server "Avrora" is available.                              
INFO     17:04:27.072 │ Pending tasks: ['Restart', 'Commission', 'Tactical',       
         'Research', 'Dorm', 'Meowfficer', 'Guild', 'Reward', 'Freebies']          
INFO     17:04:27.073 │ [Task] Restart (Enable, 2023-09-06 09:00:00)               
INFO     17:04:27.073 │ Bind task {'Alas', 'General', 'Restart'}                   
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     17:04:30.941 │ DEVICE                                                     
INFO     17:04:30.941 │ [IS_ON_PHONE_CLOUD] False                                  
INFO     17:04:30.943 │ [AdbBinary] D:\Games\Azur Lane\AzurLaneAutoScript\toolkit\L
         ib\site-packages\adbutils\binaries\adb.exe                                
INFO     17:04:30.945 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     17:04:30.946 │ <<< DETECT DEVICE >>>                                      
INFO     17:04:30.947 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:04:30.950 │ 127.0.0.1:7555                                             
INFO     17:04:30.951 │ Auto device detection found only one device, using it      
INFO     17:04:30.960 │ already connected to 127.0.0.1:7555                        
INFO     17:04:30.961 │ [AdbDevice] AdbDevice(serial=127.0.0.1:7555)               
INFO     17:04:30.962 │ [PackageName] com.YoStarEN.AzurLane                        
INFO     17:04:30.963 │ [Server] en                                                
INFO     17:04:30.969 │ [nemud.app_keep_alive]                                     
INFO     17:04:30.970 │ Screenshot interval set to 0.3s                            
INFO     17:04:30.971 │ Patching screenshot method for mumu                        
INFO     17:04:30.972 │ Skip task `Restart` at scheduler start                     
INFO     17:04:30.972 │ Delay task `Restart` to 2023-09-07 09:00:00                
         (server_update='00:00')                                                   
INFO     17:04:30.981 │ Bind task {'Alas', 'General', 'Restart'}                   
INFO     17:04:30.983 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2023, 9, 7, 9, 0)             
INFO     17:04:30.988 │ [Server] en                                                
INFO     17:04:31.005 │ Bind task {'Alas', 'General'}                              
INFO     17:04:31.007 │ Pending tasks: ['Commission', 'Tactical', 'Research',      
         'Dorm', 'Meowfficer', 'Guild', 'Reward', 'Freebies']                      
INFO     17:04:31.008 │ [Task] Commission (Enable, 2020-01-01 00:00:00)            
INFO     17:04:31.009 │ Bind task {'Alas', 'Commission', 'General'}                
INFO     17:04:31.032 │ Scheduler: Start task `Commission`                         
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     17:04:31.035 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:04:31.036 │ Reverse server listening on 192.168.74.1:20010, client can 
         send data to 192.168.74.1:20010                                           
INFO     17:04:31.042 │ sdk_ver: 23                                                
INFO     17:04:31.050 │ [nc command] ['nc']                                        
ERROR    17:04:46.055 │ AdbTimeout: adb read timeout                               
INFO     17:04:46.064 │ disconnected 127.0.0.1:7555                                
INFO     17:04:46.075 │ connected to 127.0.0.1:7555                                
INFO     17:04:46.076 │ <<< DETECT DEVICE >>>                                      
INFO     17:04:46.077 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:04:46.080 │ 127.0.0.1:7555                                             
INFO     17:04:46.081 │ Auto device detection found only one device, using it      
INFO     17:04:46.082 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:04:46.083 │ Reverse server listening on 192.168.74.1:20163, client can 
         send data to 192.168.74.1:20163                                           
ERROR    17:05:01.087 │ AdbTimeout: adb read timeout                               
INFO     17:05:02.094 │ disconnected 127.0.0.1:7555                                
INFO     17:05:02.105 │ connected to 127.0.0.1:7555                                
INFO     17:05:02.107 │ <<< DETECT DEVICE >>>                                      
INFO     17:05:02.108 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:05:02.111 │ 127.0.0.1:7555                                             
INFO     17:05:02.112 │ Auto device detection found only one device, using it      
INFO     17:05:02.113 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:05:02.113 │ Reverse server listening on 192.168.74.1:20101, client can 
         send data to 192.168.74.1:20101                                           
ERROR    17:05:17.118 │ AdbTimeout: adb read timeout                               
INFO     17:05:20.123 │ disconnected 127.0.0.1:7555                                
INFO     17:05:20.134 │ connected to 127.0.0.1:7555                                
INFO     17:05:20.135 │ <<< DETECT DEVICE >>>                                      
INFO     17:05:20.136 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:05:20.139 │ 127.0.0.1:7555                                             
INFO     17:05:20.140 │ Auto device detection found only one device, using it      
INFO     17:05:20.141 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:05:20.141 │ Reverse server listening on 192.168.74.1:20833, client can 
         send data to 192.168.74.1:20833                                           
ERROR    17:05:35.147 │ AdbTimeout: adb read timeout                               
INFO     17:05:38.152 │ disconnected 127.0.0.1:7555                                
INFO     17:05:38.165 │ connected to 127.0.0.1:7555                                
INFO     17:05:38.167 │ <<< DETECT DEVICE >>>                                      
INFO     17:05:38.167 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     17:05:38.170 │ 127.0.0.1:7555                                             
INFO     17:05:38.170 │ Auto device detection found only one device, using it      
INFO     17:05:38.172 │ Connecting to local emulator, using host 192.168.74.1      
INFO     17:05:38.173 │ Reverse server listening on 192.168.74.1:20064, client can 
         send data to 192.168.74.1:20064                                           
ERROR    17:05:53.177 │ AdbTimeout: adb read timeout                               
CRITICAL 17:05:53.178 │ Retry screenshot_adb_nc() failed                           
CRITICAL 17:05:53.179 │ Request human takeover                                     
INFO     17:05:53.180 │ No provider specified, skip sending                        


</details>

```CRITICAL 17:05:53.179 │ Request human takeover``` could this be related ?

**Comment by louishhy** [comment]
Emulator: Mumu Player 12, Alas: v0.4.4
Same problem and related output (`AdbTimeout: adb read timeout` after `[nc command] ['nc']`).
Same error after tweaking to `DroidCast_raw`.

Resolved after fully restarting the computer, Alas and the emulator. (It is the first full restart after the installation of Alas)

**Comment by jpersonaps3** [comment]
I got into the same issue. Finally realized that it was the yellow cab app "ATX" in the simulator causing the issue. Uninstall it, and let ALAS automatically install it again. That would solve the problem.
