### ISSUE TITLE
Bug: 奸商商店无法购买金体力箱

### ISSUE THREAD

**Issue by SaarChaffee** [LmeSzinc/AzurLaneAutoScript#3093]
[1693968105663.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12532804/1693968105663.zip)

**Comment by SaarChaffee** [comment]
@guoh064 我这里 SHOP_BUY_CONFIRM 是正常的，复现不了你的问题

**Comment by guoh064** [comment]
没事，有可能是星界链最近太卡了，我再试试别的截图方法吧

**Comment by LmeSzinc** [comment]
字体有变化

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/b6319652-b034-4dd1-8adf-8e4326019f38)
