### ISSUE TITLE
科研项目选择有bug，过滤器选六期但是会做三期的

### ISSUE THREAD

**Issue by thginsk** [LmeSzinc/AzurLaneAutoScript#3100]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

已经在“科研”中选择了科研过滤器：六期 蓝图+203，但是我看他有时候会选择三期的项目做，包括舰装解析/资金募集，有一次还做了消耗6魔方的项目H339（”使用魔方“设置了0.5小时+无项目可做时）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by cloudchina** [comment]
我倾向5期，过滤的是五期蓝图+152，也是会去做三期的，后面要是再碰到就截图，传日志吧

**Comment by cloudchina** [comment]
我刚才碰到了，见附件，日志看最下面，今天（2023.9.17日11：50多）的
![1](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/96337073/943fb723-323d-4e48-93f6-8311d639564d)
![2](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/96337073/daafe805-310c-413a-971e-507b72f4cb1b)
![3](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/96337073/000bba9f-f277-4c56-85a1-2fb6ac2fad95)
[2023-09-16_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12642035/2023-09-16_alas.txt)

**Comment by cloudchina** [comment]
我的问题确实是这样，不知道提出问题的人碰到的问题是不是这样。
看来还是对过滤器了解得不够多，感谢

> 因为ALAS觉得做三期2h收益比5期金船5h高。 蓝图指的是彩船蓝图（下面简称彩图），因为金船蓝图获取不仅比彩图多，需求还比彩图少，所以金图是会先于彩图溢出的。 这样看，五期金5h提供的就只有寥寥无几的彩装备图收益了，而2h委托里，五期魔方因为你的选项所以不能做，三期2h虽然没有收益，但是刷新收益也是收益，alas认为哪怕扣除了两个小时的刷新收益也比做五期金5h强。 如果你不想这样，就只能考虑手写过滤器了。 附上预置的五期蓝图+152（非必要不使用魔方）过滤器： `S5-DR0.5 > S5-PRY0.5 > S5-Q0.5 > S5-H0.5 > Q0.5 > S5-DR2.5 > S5-G1.5 > S5-Q1 > S5-DR5 > 0.5 > S5-G4 > S5-Q2 > S5-PRY2.5 > reset > S5-DR8 > Q1 > 1 > S5-E-315 > S5-G2.5 > G1.5 > 1.5 > S5-E-031 > S5-Q4 > Q2 > E2 > 2 > DR2.5 > PRY2.5 > G2.5 > 2.5 > S5-PRY5 > S5-PRY8 > Q4 > G4 > 4 > S5-C6 > DR5 > PRY5 > 5 > C6 > 6 > S5-C8 > S5-C12 > DR8 > PRY8 > C8 > 8 > C12 > 12`
