### ISSUE TITLE
须臾望月抄活动无法识别到B1

### ISSUE THREAD

**Issue by Scp-096-r** [LmeSzinc/AzurLaneAutoScript#3126]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

Alas已更新至最新版，但须臾望月抄的第二章图无法识别，在A图打完后只能进行C图。
提示不存在B图，现有文件只有 ['a1', 'a2', 'a3', 'c1', 'c2', 'c3'] 
Possible reason #2: You are using an old Alas, please check for update, or make map files yourself using dev_tools/map_extractor.py 

只是我的本地文件有这种情况么？是的话需要替换哪一个文件？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![屏幕截图 2023-09-15 192012](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/62314841/b1a5f609-385f-441c-9726-26d1a0fb0688)

**Comment by Lin-9229** [comment]
文件只有6个副本，还没创建B和D的（来自路人发言）

**Comment by Scp-096-r** [comment]
> 文件只有6个副本，还没创建B和D的（来自路人发言）![image](https://user-images.githubusercontent.com/118144305/268270064-3c7191d9-31c5-4c18-87ec-ba7faa4c5b76.png)

哦～那就没啥了，我还以为是我这边的问题。
