### ISSUE TITLE
希望新增调度器在某些指定的时间段内不安排任何任务

### ISSUE THREAD

**Issue by HS7097** [LmeSzinc/AzurLaneAutoScript#3134]
### 你的功能请求是否与问题有关？

Alas启动后会独占ADB
关闭后其他使用ADB的程序能正常连接

### 解决方案

允许设定多个时间段让调度器不安排任何任务
单个任务默认20分钟的执行时间
以保证Windows任务计划程序自动终止Alas进程时Alas不在执行任何任务

**Comment by HS7097** [comment]
> 如果你想的话，可以参考#2515 修改alas.py的代码，通过os.system来执行自己写好的bat，bat里判断一下时间，如果刚好在某个时间段里就关闭alas。

emm，主要是定时执行，如果是空闲时自动释放ADB那么可能与其他任务的定时执行有冲突；
Alas不能保存被关闭前正在执行什么任务，主要是开荒或者说正在自动战斗，因此出此下策提案；
游戏内的所有任务一般都可以在20min到30min完成，只有极个别，比如开荒等待心情回复以及海图识别可能会占用时间，可以考虑在启用空闲时间段时禁用所有的自动开荒，谢谢大佬

**Comment by LmeSzinc** [comment]
感觉是一个 XY 问题，我不知道你为什么要释放 ADB 20分钟

**Comment by HS7097** [comment]
> 感觉是一个 XY 问题，我不知道你为什么要释放 ADB 20分钟

不是，我要是开了alas，我就用不了MAA了，而且我是要提前20分钟关闭Alas，根本不是关闭20分钟
