### ISSUE TITLE
刷紧急委托更换前排时可选从常用船中更换

### ISSUE THREAD

**Issue by Heipen** [LmeSzinc/AzurLaneAutoScript#3135]
### 你的功能请求是否与问题有关？

高练3油刷活动图时，有的活动图适合唐卡，有的活动奥利克富特好用，希望可以有个途径来手动筛选一下指定从某几艘船中更换

### 解决方案

可以选择从常用船中更换，这样用户可以通过将需要出击的前排船设为常用来对选择进行限定。

**Comment by Azunyan15** [comment]
同求。比如这次活动3油C2，非唐卡的100级白鹰驱逐打不过boss

**Comment by Heipen** [comment]
还是再建议一下用常用来挑选，目前挑选前排时本就会有一堆筛选项，额外点一下常用应该容易做到吧？现有的方案灵活性还是太差了，比如我想只用婚船或本次活动后新增的z20。

**Comment by Heipen** [comment]
呼吁了快一年终于实现了。。。https://github.com/LmeSzinc/AzurLaneAutoScript/commit/a70d4c467547443879c1ed6434bd59f0c6f7635b
