### ISSUE TITLE
请求适配一下64位的NOX模拟器

### ISSUE THREAD

**Issue by lvzhenbo** [LmeSzinc/AzurLaneAutoScript#315]
**Describe the bug**
今天手贱去看了一眼NOX官网，手贱卸载了32位NOX安装了64位NOX，然后脚本打不开了

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32427677/105461663-7e78e980-5cc8-11eb-8787-335ac3520c50.png)

**Log**
Post the entire log snippet that caused you to receive the error

**Comment by lvzhenbo** [comment]
看了一眼注册表，多了一个A
![image](https://user-images.githubusercontent.com/32427677/105462075-17a80000-5cc9-11eb-90c3-cd58e65895d0.png)

**Comment by lvzhenbo** [comment]
然后百度了怎么获取Serial，得到是127.0.0.1:59865

**Comment by LmeSzinc** [comment]
#482
