### ISSUE TITLE
指挥喵强化时，进入强化界面后不会选择强化材料，导致强化无法生效

### ISSUE THREAD

**Issue by Sun2030** [LmeSzinc/AzurLaneAutoScript#3155]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

指挥喵强化功能失效，仓库里有很多强化材料（均未上锁），但只是进入强化界面而不进行选择，导致无法强化
补充信息：问题发生时训练队列中有10个已训练完的猫箱，仓库容量为40/40，即仓库已满

### 如何复现

1. 让 “收获-指挥喵” 任务立刻生效
2. 出现问题

### 预期行为

进入强化界面后应该选择强化材料而不是不动并退出

### 相关 Logs

```Text
日志见截图部分
此外还有问题发生时的视频录像
```

### 截图

日志截图:
<img width="494" alt="屏幕截图 2023-09-24 165603" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/94839268/2a224880-624b-40b8-a56a-d316a8bda126">
<img width="491" alt="屏幕截图 2023-09-24 165628" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/94839268/0c4622ae-ba50-4472-8453-b0a81af08630">

alas设置截图：
<img width="484" alt="屏幕截图 2023-09-24 171544" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/94839268/fdcd647d-b08a-4abd-a705-ebd61e912fd3">

游戏画面录像：
[夜神模拟器 2023-09-24 16-44-11.mp4_20230924_165108.webm](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/94839268/7ba2a1a5-48ee-4300-85ec-59f95830056a)

### 还有别的吗？

按个人理解，问题的原因是否可能与`被“同时最多训练10个猫箱”的提示条遮挡导致ocr强化材料的时候失败`有关
所以日志中会显示`找到0个强化材料`

**Comment by KamilYZ** [comment]
加一，同样的问题
以下是log截图、强化材料截图、设置截图
![}@ QX1`(5H~~3N42H71SIB_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/475be27c-30d3-4f68-8a03-00faf90a7608)
![SA7XNZU8O PTDQLZ$SLGKUU_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/4cded8ef-bb51-4318-b86e-5f92ead9f455)
![~18PSC~4(46RQ{ POFOORWF_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/ad998db4-4843-417a-a0fc-4b91f87653ea)
![POBM%~8)` @E2BD)RJQRJJ6_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/0515d7a9-e7e3-43cc-ac6b-ee4d9a3aba6a)

**Comment by KamilYZ** [comment]
![}@ QX1`(5H~~3N42H71SIB_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/e8dde30a-fd7a-4550-a872-4d6583344851)
![SA7XNZU8O PTDQLZ$SLGKUU_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/985d6b98-b8b6-4b2d-a191-80425e0de41f)
![~18PSC~4(46RQ{ POFOORWF_tmb](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/106416335/989c8428-dda0-4cfd-99a5-179862edbd4e)
没传上去，再传一遍
