### ISSUE TITLE
明石商店无法跳过剧情

### ISSUE THREAD

**Issue by 24k12315** [LmeSzinc/AzurLaneAutoScript#3158]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

停留在剧情界面不挑过

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![2023-09-24_03-54-02-246603](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/118600831/2703a89a-3d07-4c5e-b0b7-580a2aff2376)

### 还有别的吗？

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12713222/log.txt)

**Comment by LmeSzinc** [comment]
确认你正在使用最新的alas
