### ISSUE TITLE
大世界商店不购买

### ISSUE THREAD

**Issue by qyyxxx407** [LmeSzinc/AzurLaneAutoScript#3161]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

才发现星界云的大世界商店不进行购买，请问是是ui改版之后没有适配还是bug呢

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
#3086

**Comment by zkeli7e** [comment]
日服遇到了同样的问题，本地版本SHA1：7d122a7b
LOG：
INFO     05:42:04.181 │ Task OpsiShop is disabled before assets update             
INFO     05:42:04.182 │ Delay task `OpsiShop` to 2023-10-15 23:00:00               
         (server_update='00:00')                                                   
INFO     05:42:04.190 │ Bind task {'OpsiShop', 'General', 'Alas', 'OpsiGeneral'}   
INFO     05:42:04.191 │ Save config ./config\alas.json,                            
         OpsiShop.Scheduler.NextRun=datetime.datetime(2023, 10, 15, 23, 0)         
INFO     05:42:04.204 │ Scheduler: End task `OpsiShop`                             
INFO     05:42:04.205 │ [Server] jp                                                
INFO     05:42:04.213 │ Bind task {'General', 'Alas'}                              
INFO     05:42:04.214 │ No task pending                                            
INFO     05:42:04.215 │ [Task] Commission (Enable, 2023-10-15 06:14:11)            
INFO     05:42:04.216 │ Bind task {'Commission', 'General', 'Alas'}                
INFO     05:42:04.219 │ Wait until 2023-10-15 06:14:11 for task `Commission`       
INFO     05:42:04.220 │ Goto main page during wait                                 
INFO     05:42:04.282 │ [Package_name] com.YoStarJP.AzurLane                       
INFO     05:42:04.283 │ App is already running, goto main page                     
INFO     05:42:04.283 │ <<< UI ENSURE >>>                                          
INFO     05:42:04.284 │ UI get current page                                        
INFO     05:42:04.287 │ [UI] page_main                                             
INFO     05:42:04.288 │ Already at page_main

**Comment by LoSiTeE** [comment]
> #3086

请问这个问题是不是暂时还没有解决？如果没解决的话我先手动把港口商店里的东西买了

**Comment by LoSiTeE** [comment]
@LmeSzinc 

请问这个问题是否解决？如果没解决的话我先手动把港口商店里的东西买了

**Comment by hu22829831** [comment]
> @LmeSzinc
> 
> 请问这个问题是否解决？如果没解决的话我先手动把港口商店里的东西买了

运行日志都没有OPSISHOP，轮到就直接跳过不运行，运行时间变下一天零点

**Comment by LoSiTeE** [comment]
> > @LmeSzinc
> > 请问这个问题是否解决？如果没解决的话我先手动把港口商店里的东西买了
> 
> 运行日志都没有OPSISHOP，轮到就直接跳过不运行，运行时间变下一天零点

我也是……直接就跳过了。我现在都手动买

**Comment by wxlomo** [comment]
目前似乎还是存在问题 任务会直接跳过

**Comment by SaarChaffee** [comment]
#3086
