### ISSUE TITLE
alas更新器一直显示“有新版本可用”

### ISSUE THREAD

**Issue by MrQMou** [LmeSzinc/AzurLaneAutoScript#3164]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

今天上午打开alas后提示“有新版本可用”，但更新后仍有该提示，且更新器内的本地与上游仓库内容一致。
删除本地alas文件并重新下载后仍是如此。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![QQ截图20230929162515](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/77443094/33af421a-aed7-4281-8ed9-ea7adcfc193b)
![QQ截图20230929162601](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/77443094/918733d7-4b6e-4366-9765-356c41e9613f)

**Comment by Sally001** [comment]
是的，我也是重复显示有更新

**Comment by Mr-Dizzy** [comment]
+1

**Comment by Atoria999** [comment]
+1

**Comment by LmeSzinc** [comment]
发log文件夹下当天的 `*_gui.txt`

**Comment by MrQMou** [comment]
> 发log文件夹下当天的 `*_gui.txt`

[2023-09-29_gui.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/12775067/2023-09-29_gui.txt)

**Comment by LmeSzinc** [comment]
另外的事情，检查：
1. 是否在中国大陆，在中国大陆才用国内源
2. 有没有使用代理软件，代理软件需要配置规则绕过国内网站
```
2023-09-29 16:30:58.903 | ERROR | Failed to get remote commit: HTTPSConnectionPool(host='vip.123pan.cn', port=443): Max
retries exceeded with url: /1818706573/pack/LmeSzinc_AzurLaneAutoScript_master/latest.json (Caused by                  
NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D6736DA88>: Failed to establish a   
new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))                                                 
2023-09-29 16:30:58.905 | ERROR | Failed to get latest commit                                                          
```

**Comment by MrQMou** [comment]
> 另外的事情，检查：
> 
> 1. 是否在中国大陆，在中国大陆才用国内源
> 2. 有没有使用代理软件，代理软件需要配置规则绕过国内网站
> 
> ```
> 2023-09-29 16:30:58.903 | ERROR | Failed to get remote commit: HTTPSConnectionPool(host='vip.123pan.cn', port=443): Max
> retries exceeded with url: /1818706573/pack/LmeSzinc_AzurLaneAutoScript_master/latest.json (Caused by                  
> NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D6736DA88>: Failed to establish a   
> new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))                                                 
> 2023-09-29 16:30:58.905 | ERROR | Failed to get latest commit                                                          
> ```

在接收到今天凌晨的更新后问题已修复。
我在国内，且未使用代理软件。
作者辛苦

**Comment by Mr-Dizzy** [comment]
> 另外的事情，检查：
> 
> 1. 是否在中国大陆，在中国大陆才用国内源
> 2. 有没有使用代理软件，代理软件需要配置规则绕过国内网站
> 
> ```
> 2023-09-29 16:30:58.903 | ERROR | Failed to get remote commit: HTTPSConnectionPool(host='vip.123pan.cn', port=443): Max
> retries exceeded with url: /1818706573/pack/LmeSzinc_AzurLaneAutoScript_master/latest.json (Caused by                  
> NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D6736DA88>: Failed to establish a   
> new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))                                                 
> 2023-09-29 16:30:58.905 | ERROR | Failed to get latest commit                                                          
> ```

确认修复，感谢更新以及国庆快乐
