### ISSUE TITLE
Can't use Alas with auto-search

### ISSUE THREAD

**Issue by DozeHow** [LmeSzinc/AzurLaneAutoScript#317]
When enable the auto-search in setting-Attack fleet option, Alas will try to click the FLEET_SIDEBAR to check the options but failed here. It's 99% because of the wrong position wrote in the code.

*Screenshots*

![image](https://user-images.githubusercontent.com/6416397/105598247-1986c780-5d8c-11eb-95e4-2bb9f156617b.png)
![image](https://user-images.githubusercontent.com/6416397/105599119-5488fb00-5d8c-11eb-805e-1bf8c8ed5dc9.png)
![image](https://user-images.githubusercontent.com/6416397/105598655-33c0a580-5d8c-11eb-98a8-6c54db01c928.png)

**Comment by LmeSzinc** [comment]
Please disable it before it's done.
The suppot for auto-search is done yet. The localization for auto-search in EN haven't started either.
