### ISSUE TITLE
alas一直占用网络，下载和上传什么东西

### ISSUE THREAD

**Issue by TomoyoIsPower** [LmeSzinc/AzurLaneAutoScript#3177]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

只要开启alas，就一直在占用网络，不知道在下载和上传什么

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by MengNianxiaoyao** [comment]
有上传截图到统计局的设置，你可能开了；然后还有检查更新；但我这里一直都是0

**Comment by Georgebillion** [comment]
本人alas这边也没看到非常大的网络波动啊？有无具体细节？？？附上我自己的占用
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/40432824/1ee0aea9-bc09-49da-874a-ff7994ec1cd6)
