### ISSUE TITLE
通用商店无法自动购买T3黄书

### ISSUE THREAD

**Issue by CNLSL** [LmeSzinc/AzurLaneAutoScript#3183]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

军火商设置自动购买T3书 红书蓝书均正常购买 唯独黄书没有购买 过滤器设置为BookT3 
购买过程没有报错停止

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
[如何上报bug How to Report Bugs](https://github.com/LmeSzinc/AzurLaneAutoScript#%E5%A6%82%E4%BD%95%E4%B8%8A%E6%8A%A5bug-how-to-report-bugs)
在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。


上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
