### ISSUE TITLE
请求增加邮件提示的功能

### ISSUE THREAD

**Issue by hitbobtom** [LmeSzinc/AzurLaneAutoScript#3186]
### 你的功能请求是否与问题有关？

希望可以在遇到脚本无法处理的异常，导致脚本停止运行时，添加邮件提醒的功能

### 解决方案

class RequestHumanTakeover(Exception):
    # Request human takeover
    # Alas is unable to handle such error, probably because of wrong settings.
    **server.sendmail(sendAddress, toAddress, msg.as_string())**
    pass

smtplib.SMTP_SSL

### 其他内容

![QQ图片20231007191231](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/84380288/a66d73d5-b91c-4870-aa1d-cf2ae0265d7e)

**Comment by SaiCateDoan** [comment]
![cf368ff91dc53d8bda23db43bdc5cd94](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48789988/5a05ee46-c66d-4184-b0aa-9b4e046df910)
已经有了.jpg
