### ISSUE TITLE
请求增加战斗结算截图

### ISSUE THREAD

**Issue by carrotluo5** [LmeSzinc/AzurLaneAutoScript#3188]
### 你的功能请求是否与问题有关？

现有战斗掉落截图应该是每战截图

### 解决方案

希望能增加每场战斗完的掉落截图，这样自律也能截，方便统计一下心智掉落之类的。
<img width="640" alt="屏幕截图 2023-10-08 184720" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/73460600/06c39b9b-c37d-48d8-a4f7-190e6b90ee3e">

**Comment by LmeSzinc** [comment]
累计的结果没有统计学上的意义，是无效的
