### ISSUE TITLE
日常推图增加金币过滤器

### ISSUE THREAD

**Issue by Hardy-Swa** [LmeSzinc/AzurLaneAutoScript#3189]
### 你的功能请求是否与问题有关？

目前日常刷图在金币溢出的情况下仍会继续运行，无疑是造成了不必要的浪费，希望能有一个超出金币设定阈值后停止刷图的选项

### 解决方案

类似已有的石油低于某一数值后停止运行，增加一个玩家可以自行设置的金币阈值以及执行选项。

**Comment by LmeSzinc** [comment]
不刷图也会导致石油溢出然后浪费，这个功能意义不大，嫌钱多可以打开这个

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/e4772c10-69bf-4250-8035-099dcbb34f26)
