### ISSUE TITLE
使用主线图配置10-2困难图时卡在队伍配置界面不动

### ISSUE THREAD

**Issue by S07453881** [LmeSzinc/AzurLaneAutoScript#3204]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用主线图配置10-2困难图时卡在队伍配置界面不动

### 如何复现

1. 前往 主线图-困难-10-2
2. 点击  立即前往
3. 滑动到 队伍选择
4. 出现问题

### 相关 Logs

```Text
INFO     16:48:55.945 │ 10-2                                                       
INFO     16:48:55.946 │ Expect emotion reduce: (14, 0)                             
INFO     16:48:55.972 │ Bind task {'General', 'Alas', 'Main'}                      
INFO     16:48:55.974 │ Save config ./config\alas.json,                            
         Main.Emotion.Fleet1Value=119,                                             
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 10, 19, 16, 48, 55),    
         Main.Emotion.Fleet2Value=119,                                             
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 10, 19, 16, 48, 55)     
INFO     16:48:55.994 │ [Emotion fleet_1] 119                                      
INFO     16:48:55.997 │ [Emotion fleet_2] 119                                      
INFO     16:48:55.998 │ <<< ENTER MAP >>>                                          
INFO     16:48:56.040 │ Click ( 464,  418) @ 10-2                                  
INFO     16:48:56.654 │ [Map_clear_percentage] 0.2180232558139535                  
INFO     16:48:56.956 │ [Map_clear_percentage] 0.6308139534883721                  
INFO     16:48:57.237 │ [Map_clear_percentage] 0.6744186046511628                  
INFO     16:48:57.567 │ [Map_clear_percentage] 0.6744186046511628                  
INFO     16:48:57.864 │ [Map_clear_percentage] 0.6744186046511628                  
INFO     16:48:57.866 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     16:48:57.867 │ [Map_info] 67%, star_1, star_2, star_3, 3_stars            
INFO     16:48:57.869 │ [StopCondition_MapAchievement] map_3_stars                 
INFO     16:48:57.882 │ No auto search option.                                     
INFO     16:48:57.883 │ Click (1005,  518) @ MAP_PREPARATION                       
WARNING  16:49:57.898 │ Wait too long                                              
WARNING  16:49:57.900 │ Waiting for {'RETIRE_APPEAR_3', 'DAILY_CHECK', 'GAME_TIPS',
         'DOCK_CHECK', 'FLEET_PREPARATION', 'STORY_SKIP_3', 'STORY_CLOSE',         
         'MAP_PREPARATION', 'GET_MISSION', 'IN_MAP', 'BOOK_POPUP_CHECK', '10-2',   
         'AUTO_SEARCH_MENU_CONTINUE'}                                              
INFO     16:49:57.925 │ [u2.Device] Device(atx_agent_url=http://127.0.0.1:9343)    
INFO     16:49:58.045 │ [Package_name] com.bilibili.azurlane                       
ERROR    16:49:58.047 │ GameStuckError: Wait too long                              
WARNING  16:49:58.052 │ Saving error: ./log/error/1697705398052                    
WARNING  16:49:58.242 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  16:49:58.244 │ If you are playing by hand, please stop Alas               
INFO     16:49:58.245 │ Task call: Restart                                         
INFO     16:49:58.265 │ Bind task {'General', 'Alas', 'Main'}                      
INFO     16:49:58.267 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2023, 10, 19, 16, 49, 58),    
         Restart.Scheduler.Enable=True                                             
[alas] exited. Reason: Manual stop
```

### 截图

![MuMu12-20231019-165342](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/99027027/5715a527-0469-4457-9089-25086d10fc9b)

**Comment by ZeroBloodedge** [comment]
出现了同样的问题

**Comment by libaobao123** [comment]
INFO     16:49:56.212 │ 12-4                                                       
INFO     16:49:56.215 │ Expect emotion reduce: (12, 2)                             
INFO     16:49:56.233 │ Bind task {'Main', 'Alas', 'General'}                      
INFO     16:49:56.235 │ Save config ./config\alas.json,                            
         Main.Emotion.Fleet1Value=119,                                             
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 10, 19, 16, 49, 56),    
         Main.Emotion.Fleet2Value=150,                                             
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 10, 19, 16, 49, 56)     
INFO     16:49:56.245 │ [Emotion fleet_1] 119                                      
INFO     16:49:56.247 │ [Emotion fleet_2] 150                                      
INFO     16:49:56.249 │ <<< ENTER MAP >>>                                          
INFO     16:49:56.291 │ Click ( 914,  547) @ 12-4                                  
INFO     16:49:57.099 │ [Map_clear_percentage] 0.46511627906976744                 
INFO     16:49:57.460 │ [Map_clear_percentage] 0.997093023255814                   
INFO     16:49:57.463 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     16:49:57.464 │ [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 
         3_stars, threat_safe, clear_mode                                          
INFO     16:49:57.465 │ [StopCondition_MapAchievement] non_stop                    
INFO     16:49:57.466 │ [Fast_Forward] on                                          
INFO     16:49:57.475 │ [Auto_Search] on                                           
INFO     16:49:57.478 │ Click ( 909,  525) @ MAP_PREPARATION                       
WARNING  16:50:57.504 │ Wait too long                                              
WARNING  16:50:57.505 │ Waiting for {'IN_RETIREMENT_CHECK',                        
         'AUTO_SEARCH_MAP_OPTION_ON', 'POPUP_CANCEL', 'FLEET_PREPARATION',         
         'DAILY_CHECK', 'AUTO_SEARCH_MENU_CONTINUE', '12-4', 'MAP_PREPARATION',    
         'GET_MISSION', 'RETIRE_APPEAR_1', 'BOOK_POPUP_CHECK'}                     
INFO     16:50:57.541 │ [Package_name] com.bilibili.azurlane                       
ERROR    16:50:57.543 │ GameStuckError: Wait too long                              
WARNING  16:50:57.544 │ Saving error: ./log/error/1697705457544                    
WARNING  16:50:57.677 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  16:50:57.679 │ If you are playing by hand, please stop Alas               
INFO     16:50:57.680 │ Task call: Restart                                         
INFO     16:50:57.695 │ Bind task {'Main', 'Alas', 'General'}                      
INFO     16:50:57.697 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2023, 10, 19, 16, 50, 57),    
         Restart.Scheduler.Enable=True                                             
INFO     16:51:07.709 │ Scheduler: End task `Main`                                 
CRITICAL 16:51:07.711 │ Task `Main` failed 3 or more times.                        
CRITICAL 16:51:07.712 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 16:51:07.714 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 16:51:07.715 │ Request human takeover                                     
INFO     16:51:07.716 │ No provider specified, skip sending

**Comment by libaobao123** [comment]
`INFO     16:49:56.212 │ 12-4                                                       
INFO     16:49:56.215 │ Expect emotion reduce: (12, 2)                             
INFO     16:49:56.233 │ Bind task {'Main', 'Alas', 'General'}                      
INFO     16:49:56.235 │ Save config ./config\alas.json,                            
         Main.Emotion.Fleet1Value=119,                                             
         Main.Emotion.Fleet1Record=datetime.datetime(2023, 10, 19, 16, 49, 56),    
         Main.Emotion.Fleet2Value=150,                                             
         Main.Emotion.Fleet2Record=datetime.datetime(2023, 10, 19, 16, 49, 56)     
INFO     16:49:56.245 │ [Emotion fleet_1] 119                                      
INFO     16:49:56.247 │ [Emotion fleet_2] 150                                      
INFO     16:49:56.249 │ <<< ENTER MAP >>>                                          
INFO     16:49:56.291 │ Click ( 914,  547) @ 12-4                                  
INFO     16:49:57.099 │ [Map_clear_percentage] 0.46511627906976744                 
INFO     16:49:57.460 │ [Map_clear_percentage] 0.997093023255814                   
INFO     16:49:57.463 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     16:49:57.464 │ [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 
         3_stars, threat_safe, clear_mode                                          
INFO     16:49:57.465 │ [StopCondition_MapAchievement] non_stop                    
INFO     16:49:57.466 │ [Fast_Forward] on                                          
INFO     16:49:57.475 │ [Auto_Search] on                                           
INFO     16:49:57.478 │ Click ( 909,  525) @ MAP_PREPARATION                       
WARNING  16:50:57.504 │ Wait too long                                              
WARNING  16:50:57.505 │ Waiting for {'IN_RETIREMENT_CHECK',                        
         'AUTO_SEARCH_MAP_OPTION_ON', 'POPUP_CANCEL', 'FLEET_PREPARATION',         
         'DAILY_CHECK', 'AUTO_SEARCH_MENU_CONTINUE', '12-4', 'MAP_PREPARATION',    
         'GET_MISSION', 'RETIRE_APPEAR_1', 'BOOK_POPUP_CHECK'}                     
INFO     16:50:57.541 │ [Package_name] com.bilibili.azurlane                       
ERROR    16:50:57.543 │ GameStuckError: Wait too long                              
WARNING  16:50:57.544 │ Saving error: ./log/error/1697705457544                    
WARNING  16:50:57.677 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  16:50:57.679 │ If you are playing by hand, please stop Alas               
INFO     16:50:57.680 │ Task call: Restart                                         
INFO     16:50:57.695 │ Bind task {'Main', 'Alas', 'General'}                      
INFO     16:50:57.697 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2023, 10, 19, 16, 50, 57),    
         Restart.Scheduler.Enable=True                                             
INFO     16:51:07.709 │ Scheduler: End task `Main`                                 
CRITICAL 16:51:07.711 │ Task `Main` failed 3 or more times.                        
CRITICAL 16:51:07.712 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 16:51:07.714 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 16:51:07.715 │ Request human takeover                                     
INFO     16:51:07.716 │ No provider specified, skip sending        `

**Comment by libaobao123** [comment]
相同的问题

**Comment by Yuuki-Rin** [comment]
所以需要出击的都这样了
应该是官方改了布局的关系

**Comment by windskyxb** [comment]
相同的问题

**Comment by clark1091** [comment]
相同的问题，并且即使进了图后也会有概率卡在这里
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/a04d9eb6-ed10-472f-af47-29292e7a90e7)

**Comment by ZBY2003** [comment]
一样的问题，手动点开始战斗就可以了，怀疑是按键位置变了

**Comment by xpxxy** [comment]
same issue, did they change the UI ？

**Comment by Georgebillion** [comment]
已知现在11-4/12-4都是无效，估计是UI调整了，等作者做一下修复

**Comment by Georgebillion** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/40432824/808a2422-a4c2-494b-8f74-c91f790e7612)
比较了一下，还是有点偏差，是不是只需要把这个按钮修复上新的就能行了？

**Comment by Georgebillion** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/40432824/f98d88e2-09fc-42ca-aa75-de54b4097e6d)
且编队选择的识别图貌似也有偏差，所有图片均未进行过缩放操作

**Comment by kyuubee** [comment]
3-4主线也卡住了 需要手动点一下帮助他进去就能继续了 
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/3439653/a2dc94bb-98f7-44f1-bdb3-85cd993a8cc8)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/3439653/aebef675-b58d-4339-a7f7-e6813d01d75c)

**Comment by MengNianxiaoyao** [comment]
涉及舰队选择的按钮和点击进图的按钮都有偏差，需要等待更新

**Comment by SUPERDAIDAI007** [comment]
主线12-2/12-4也会卡住，等更新吧

**Comment by LmeSzinc** [comment]
#3205

**Comment by windskyxb** [comment]
> #3205

目前正常了

**Comment by KurupekoChiotzin** [comment]
更新後9-4困難圖會卡住

log:
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/79458408/ac58469d-39aa-413b-b6c0-e248fa5a3d23)

遊戲畫面:
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/79458408/4009c454-20f7-4b69-b3a0-c93273b2cf8d)

更新器:
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/79458408/07bc7908-5b41-46f5-9b50-13c304126b67)

**Comment by ZBY2003** [comment]
![Screenshot_20231020_002531_Microsoft Remote Desktop](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/95997466/74e41257-3301-44e0-9798-73c40e3bceb4)
alas已更新
主线关卡正常，但是困难图出现问题

困难图选择8-2且已经选好队伍（游戏维护前正常运行）
但是日志中显示为困难图12-4且未配队

**Comment by Phlogist** [comment]
相同问题，困难图识别不了

**Comment by cifei1** [comment]
> ![Screenshot_20231020_003545_Microsoft Remote Desktop](https://user-images.githubusercontent.com/95997466/276688881-118b0957-0293-4141-936e-4781a098b9eb.jpg) ![Screenshot_20231020_003600_Microsoft Remote Desktop](https://user-images.githubusercontent.com/95997466/276688900-1c9ad663-315a-4c8f-9758-a8070fb67d0f.jpg)
> 
> alas已更新 主线关卡正常，但是困难图出现问题
> 
> 困难图选择8-2且已经选好队伍（游戏维护前正常运行） 但是日志中显示为困难图12-4且未配队

同样问题

**Comment by yotv2000tw** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/51760140/c666e54a-0027-41a3-bc63-aa0fd4c187d7)
普通11-4會卡在這
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/51760140/0e86f5f8-e1d6-4bc9-b6ae-b577ea8101fe)
在進圖前會在這邊空點好幾下才進

**Comment by flying-crane** [comment]
更新到最新版本，仍然存在无法出击的问题，B服
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/32824459/f0ca5ba1-2c6b-4598-b3a4-4ded8da9c3c1)
仍然卡在Click ( 983,  522) @ MAP_PREPARATION
以下是具体log：

════════════════════════════════════════════════════ CAMPAIGN_12_4 ════════════════════════════════════════════════════
2023-10-22 23:46:02.136 | INFO | CAMPAIGN_12_4                                                                         
2023-10-22 23:46:02.137 | INFO | Count: 0                                                                              
2023-10-22 23:46:02.142 | INFO | <<< UI ENSURE >>>                                                                     
2023-10-22 23:46:02.143 | INFO | UI get current page                                                                   
2023-10-22 23:46:02.144 | INFO | [UI] page_main                                                                        
2023-10-22 23:46:02.144 | INFO | Goto page_campaign                                                                    
2023-10-22 23:46:02.145 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>                                                         
2023-10-22 23:46:02.146 | INFO | Page switch: page_main -> page_campaign_menu                                          
2023-10-22 23:46:02.146 | INFO | Click (1075,  378) @ MAIN_GOTO_CAMPAIGN                                               
2023-10-22 23:46:02.433 | INFO | Page switch: page_campaign_menu -> page_campaign                                      
2023-10-22 23:46:02.434 | INFO | Click ( 377,  369) @ CAMPAIGN_MENU_GOTO_CAMPAIGN                                      
2023-10-22 23:46:02.731 | INFO | Page arrive: page_campaign                                                            
2023-10-22 23:46:02.744 | INFO | [Mode_switch_1] hard                                                                  
2023-10-22 23:46:02.745 | INFO | <<< UI ENSURE INDEX >>>                                                               
2023-10-22 23:46:02.763 | INFO | No stage found.                                                                       
2023-10-22 23:46:03.048 | INFO | No stage found.                                                                       
2023-10-22 23:46:03.393 | INFO | [campaign 0.031s] ['12--1', '12--3', '12--2', '12--4']                                
2023-10-22 23:46:03.394 | INFO | [Chapter] 12                                                                          
2023-10-22 23:46:03.395 | INFO | [Stage] 12-1, 12-3, 12-2, 12-4                                                        
2023-10-22 23:46:03.396 | INFO | [Index] 12                                                                            
2023-10-22 23:46:03.428 | INFO | [OCR_OIL 0.020s] 17158                                                                
──────────────────────────────────────────────────────── 12-4 ─────────────────────────────────────────────────────────
2023-10-22 23:46:03.430 | INFO | 12-4                                                                                  
2023-10-22 23:46:03.430 | INFO | Expect emotion reduce: (4, 24)                                                        
2023-10-22 23:46:03.439 | INFO | Bind task {'General', 'Main', 'Alas'}                                                 
2023-10-22 23:46:03.440 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=119,                         
Main.Emotion.Fleet1Record=datetime.datetime(2023, 10, 22, 23, 46, 3), Main.Emotion.Fleet2Value=119,                    
Main.Emotion.Fleet2Record=datetime.datetime(2023, 10, 22, 23, 46, 3)                                                   
2023-10-22 23:46:03.445 | INFO | [Emotion fleet_1] 119                                                                 
2023-10-22 23:46:03.446 | INFO | [Emotion fleet_2] 119                                                                 
2023-10-22 23:46:03.446 | INFO | <<< ENTER MAP >>>                                                                     
2023-10-22 23:46:03.464 | INFO | Click ( 902,  556) @ 12-4                                                             
2023-10-22 23:46:03.938 | INFO | [Map_clear_percentage] 0.4476744186046512                                             
2023-10-22 23:46:04.238 | INFO | [Map_clear_percentage] 0.997093023255814                                              
2023-10-22 23:46:04.239 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False                                                       
2023-10-22 23:46:04.240 | INFO | [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 3_stars, threat_safe,      
clear_mode                                                                                                             
2023-10-22 23:46:04.241 | INFO | [StopCondition_MapAchievement] non_stop                                               
2023-10-22 23:46:04.241 | INFO | [Fast_Forward] on                                                                     
2023-10-22 23:46:04.244 | INFO | [Auto_Search] on                                                                      
2023-10-22 23:46:04.245 | INFO | Click ( 974,  522) @ MAP_PREPARATION                                                  
2023-10-22 23:47:04.258 | WARNING | Wait too long                                                                      
2023-10-22 23:47:04.259 | WARNING | Waiting for {'IN_RETIREMENT_CHECK', 'RETIRE_APPEAR_1', 'MAP_PREPARATION', '12-4',  
'GET_MISSION', 'FLEET_PREPARATION', 'AUTO_SEARCH_MAP_OPTION_ON', 'BOOK_POPUP_CHECK', 'AUTO_SEARCH_MENU_CONTINUE'}      
2023-10-22 23:47:04.277 | INFO | [Package_name] com.bilibili.azurlane                                                  
2023-10-22 23:47:04.278 | ERROR | GameStuckError: Wait too long                                                        
2023-10-22 23:47:04.278 | WARNING | Saving error: ./log/error/1697989624278
