### ISSUE TITLE
更新之後，2-4的刷警急委託的選隊問題還在

### ISSUE THREAD

**Issue by hank10322** [LmeSzinc/AzurLaneAutoScript#3206]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

雖然剛剛有更新了(也更新到最新版本)，但是在選隊的介面還是會有問題。會卡住，之後就會再次重啟，以此往復
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/45732841/565276b9-c3b4-45d3-87d0-631d56468204)

### 如何复现

1. 前往 '2-4關卡'
2. 点击 '清空>選擇'
4. 出现问题

### 预期行为

成功選隊，並進入關卡

### 相关 Logs

```Text
_No response_
```

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/45732841/1920186e-8f3d-4d1e-8301-4d6819756a99)

**Comment by Jinyilong** [comment]
12-4也是这样

**Comment by LmeSzinc** [comment]
#3204
