### ISSUE TITLE
日服主线图功能中 进图点击位置错误

### ISSUE THREAD

**Issue by STEVE-1936550490** [LmeSzinc/AzurLaneAutoScript#3211]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

国服昨天也是主线图出击点击位置不对，10月20日一点的更新修复了（国服），貌似日服没改？

### To Reproduce

1. 启用主线图功能
2. 运行到进图页面
3. 点击“出击”按钮位置错误

**Comment by lordbernkastel** [comment]
潜艇编队的点击坐标有问题，等待后续修复吧。把潜艇舰队编号设置为“不使用”可以临时解决这个问题。

**Comment by LmeSzinc** [comment]
#3204
