### ISSUE TITLE
希望可以在科研筛选器里增加一个优先哪艘船的项目

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#3216]
### 你的功能请求是否与问题有关？

如题，虽然现有的筛选器已经相当全面，但在几艘船相差较大时就会出现点小麻烦，比如我一口气磕了一百多张彩图想提早做满7234进队，结果这几天一查图纸发现预设配置下Alas给我选了半个多月的兴登堡几乎一张7234都没出，就很胃疼= =

### 解决方案

加个优先哪艘船的筛选器

**Comment by guoh064** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn#%E4%BE%8B%E5%AD%90

**Comment by CNLSL** [comment]
> 先从代码里把内置的过滤器提取出来，再参考上面老哥发的wiki改一下就好了。

请问内置过滤器在哪个位置呀
