### ISSUE TITLE
活动重复刷图功能无法开启

### ISSUE THREAD

**Issue by mooganic** [LmeSzinc/AzurLaneAutoScript#3229]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用“活动图”任务试图刷活动图t1，然后alas无法进入t1，看起来会把t1识别成a1，然后找不到a1就一直卡在那里

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![1698385293492](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/41576653/ff0bd4d6-a4f7-4d8e-b5cc-6bc0c8cb65db)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13185301/log.txt)

**Comment by Delta-R** [comment]
Alas的活动还没更新,你看看活动名称还是上次的

**Comment by xwylxq** [comment]
还没更新呢，别急等几天

**Comment by Lon-dawn** [comment]
等等吧，活动名称刷新了就能用了

**Comment by mooganic** [comment]
好的，等大佬们的更新

**Comment by LmeSzinc** [comment]
#3239
