### ISSUE TITLE
能不能只识别游戏窗口

### ISSUE THREAD

**Issue by HuangTianMatt** [LmeSzinc/AzurLaneAutoScript#3230]
### 你的功能请求是否与问题有关？

我是海外玩家，在朱诺服务器。最近不知道咋地，等朱诺一直登不进去，得开加速器，但是新服可以(多半是服务器资源分给新服了)。但是我只要开了加速器，就会有窗口，然后脚本就会一直识别然后报unknown ui page。一个模拟器我也没办法让加速器窗口不被关掉的同时保证加速线路

### 解决方案

如题，让脚本只识别游戏窗口，或者推荐个可以同时翻墙回国和运行脚本的模拟器?

**Comment by LmeSzinc** [comment]
不知道你用的什么垃圾加速器还有窗口遮挡画面的，市面主流的都没有这个问题

**Comment by HuangTianMatt** [comment]
我用的biubiu加速器，只要打开挂后台，即使界面是碧蓝航线，也会一直显示unknown ui page

**Comment by HuangTianMatt** [comment]
> 不知道你用的什么垃圾加速器还有窗口遮挡画面的，市面主流的都没有这个问题

我用的biubiu加速器，只要打开挂后台，即使界面是碧蓝航线，也会一直显示unknown ui page

**Comment by D9Lose** [comment]
> > 不知道你用的什么垃圾加速器还有窗口遮挡画面的，市面主流的都没有这个问题
> 
> 我用的biubiu加速器，只要打开挂后台，即使界面是碧蓝航线，也会一直显示unknown ui page


换个思路呗，路由器上分流   pc软件上代理   模拟器不就不用开加速器了吗？

**Comment by LmeSzinc** [comment]
有问题就换，加速器多了去了
