### ISSUE TITLE
活动-活动图中不能选择最新的活动

### ISSUE THREAD

**Issue by Mei-Misaki** [LmeSzinc/AzurLaneAutoScript#3235]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

alas从github上下载，且已经更新。在活动-活动图功能中，活动名称还是“须臾望月抄”，无法选择最新的活动。
![屏幕截图 2023-10-28 162212](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37899589/4f46ba84-07a3-477e-8644-40960b418366)
![屏幕截图 2023-10-28 162134](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37899589/5e810c04-4ab5-4aa5-bd66-8ee39aeffe7a)

### 如何复现

1. 前往 'alas首页'
2. 点击 '活动'，再点击'活动图'
3. 滑动到 '关卡设置-活动名称'
4. 出现问题

### 预期行为

应当自动选择至最新的活动。

**Comment by kyuubee** [comment]
1. 修改campaign\readme.md 添加当前任务名称和时间
 2. 调用dev_tools\map_extractor.py 导出新的活动地图，拷贝到上面的日期对应的文件夹中
 3. 修改module\campaign\run.py ，加入对应的活动文件夹名称 映射活动名
 4. 做了这么几步虽然不能开荒 进图会报错 但是你至少可以运行

**Comment by clark1091** [comment]
开荒就算了，这么操作能自律刷图吗？

**Comment by LmeSzinc** [comment]
#3239
