### ISSUE TITLE
【活动图】关于活动适配前的刷图需求

### ISSUE THREAD

**Issue by shawnyuan-cn** [LmeSzinc/AzurLaneAutoScript#3238]
## 功能请求

能否不区分活动，**在自律战斗的情况下**，一定程度上做到：

1. 识别活动关卡入口：ABCD、T、SP等；
2. 选择编队开启作战；
3. 统计心情消耗：因为出击次数不定，可以根据主观选择（单队全清与两队出击），两队出击的情况则以最后一战作为旗舰队次数心情-2。

## 提出以上建议的原因

活动图自动向前开荒当然是一个非常便利的功能，但：

1. 对于各位开发者来说，每次活动的地图数据都需要一定时间进行统计、导入，想必也需要一定维护成本；高优先级、工作量大，但对于开荒结束的玩家实际应用次数较少，反而是对于档案这种常驻的类型提升了一定的游戏体验；
2. 对于游戏玩家，无论是尽早刷够PT毕业，还是通过低耗赚取活动图的高收益，尽快适配活动入口，关卡入口反而是最重要，也是需求最多的。

**PS：以上仅个人的拙见，我了解可以在本地通过修改配置实现刷图，并没有不尊重各位开发者大大劳动成果的想法。**

**Comment by LmeSzinc** [comment]
#3239
