### ISSUE TITLE
大世界商店增加購買商品

### ISSUE THREAD

**Issue by Arrest3579** [LmeSzinc/AzurLaneAutoScript#3246]
### 你的功能请求是否与问题有关？

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/14796986/6a6152ef-adfd-4875-bb94-e7116c61236d)
詳細不確定哪些沒買到
不過可以肯定的是有東西沒買到

**Comment by wxlomo** [comment]
我这里似乎大世界商店的任务会直接被跳过...也就是什么都没买到

**Comment by LmeSzinc** [comment]
#3086
