### ISSUE TITLE
开荒、隐秘海域等添加侵蚀等级上限设置

### ISSUE THREAD

**Issue by Chen-Luan** [LmeSzinc/AzurLaneAutoScript#3248]
### 你的功能请求是否与问题有关？

大世界开荒、隐秘海域等添加侵蚀等级上限设置，超过上限的不打，避免舰队强度过低引起卡关

**Comment by cjwmiku** [comment]
这就是你自己的问题了，上个能打过的队伍不就行了，练度不够多挂alas，上练级队自己挂71吧

**Comment by D9Lose** [comment]
las使用条件：默认A胜利 默认无沉船 默认7X24小时运行  
提升你自己的练度，回到正常的挂机流程中去。
