### ISSUE TITLE
刷紧急委托无法锁定旗舰

### ISSUE THREAD

**Issue by Chen-Luan** [LmeSzinc/AzurLaneAutoScript#3249]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

刷紧急委托设置中，无法强制锁定旗舰，而文本描述中却提到“选择不更换则会强制红脸出击”，希望添加一个“不更换旗舰”的功能

**Comment by Horizon101011** [comment]
不需要换船请直接使用活动图功能

紧急委托本身就是以自动换船追求最佳收益为前提的
