### ISSUE TITLE
自动保存好像出bug了？

### ISSUE THREAD

**Issue by fhwhite** [LmeSzinc/AzurLaneAutoScript#3255]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

刚才想修改设置，发现修改之后没有右上角显示的自动保存，并且设置也确实没有起效

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by fhwhite** [comment]
一天也没用，刚才手动改了配置文件，打算先用着，发现出了#3252的问题
Pending tasks: ['Event', 'OpsiMeowfficerFarming', 'GemsFarming']                      
2023-10-31 23:24:51.992 | INFO | [Task] Event (Enable, 2023-11-31 12:00:00)  
修改之后就能自动保存了，之前我重启alas也没报这个错误，而是卡在sp任务完成不能跳过，刚才start直接就报了

**Comment by D9Lose** [comment]
按照报错格式，提交log和相关截图
不要让别人去猜你的log

**Comment by LmeSzinc** [comment]
#3252
