### ISSUE TITLE
侵蚀一任务在启动时会请求两次计划作战按钮，导致无法开启计划作战一直待机

### ISSUE THREAD

**Issue by q9722088** [LmeSzinc/AzurLaneAutoScript#3266]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我使用的是星界云手机alas版本+阿里云电脑，发现在执行侵蚀一作战的时候会一直处于无法正常作战的状态

### 如何复现

正常开启侵蚀一作战

### 预期行为

侵蚀一顺利启动，不会一直处于错误循环状态

### 相关 Logs

```Text
参考下方截图
```

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/35258828/16497cc1-9863-45e5-b71d-eae4e38ccaa1)

### 还有别的吗？

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/35258828/e8183648-0026-45c7-beaa-912317366703)
侵蚀一设置截图

**Comment by LmeSzinc** [comment]
alas版已经内置了alas，不要通过外部服务器连接
