### ISSUE TITLE
TW assets 需要更新，附上可使用的圖

### ISSUE THREAD

**Issue by yhtojy** [LmeSzinc/AzurLaneAutoScript#3277]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

map\
MAP_OFFENSIVE.PNG
![MAP_OFFENSIVE](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/3877705/f257cb5f-babb-4aa4-8122-4e6489a1c72f)

SWITCH_OVER.PNG
![SWITCH_OVER](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/3877705/7feb9006-5a17-43fc-b643-7d5f17fb9a9a)

MAP_OFFENSIVE.png 應該已經壞很久了，所以只要觸發滿艙退役，基本上就會超時、重開、然後撤退了
以上都測試過了，不會PR，所以就只提供圖檔了
感謝大大的ALAS讓我解放雙手

**Comment by LmeSzinc** [comment]
#3544
