### ISSUE TITLE
安装依赖的时候报错ERROR: Exception: Traceback (most recent call last)

### ISSUE THREAD

**Issue by 1966799011** [LmeSzinc/AzurLaneAutoScript#328]
![图片](https://user-images.githubusercontent.com/78476090/106785484-68840500-6688-11eb-9b1d-9514c140d0e7.png)

**Comment by whoamikyo** [comment]
it looks like the pip cache is corrupted, try run these commands in your CMD.

```
cd %USERPROFILE%\AppData\Local\pip
del /f /s /q cache > NUL
```
