### ISSUE TITLE
刷紧急委托时不知什么原因不会自动进行

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#3284]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![image](https://githubfast.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/59768685-9a5a-4e8c-9f17-6d8defc3d7ae)
![image](https://githubfast.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/e8ad72e7-b066-4bcd-aa6d-07e3be5eaf58)

如图，我按照alas提供的描述准备了富特和唐斯两只百级零破白鹰驱逐放在后宅二楼准备用刷紧急委托功能全天3油刷B1，但是alas在刷空一只的心情后就不会自动换前排继续刷了，哪怕心情全满了到任务启动时间也只会往后顺延计时器，不会自动启动。由于是全天候挂机，我无法准确提供停工时的日志，如果是我用法有误，希望大佬们能指点一下= =

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

INFO     15:14:01.438 │ Having daily commissions to do, delay task `GemsFarming`   
INFO     15:14:01.440 │ Delay task `GemsFarming` to 2023-11-12 15:24:20            
         (target=datetime.datetime(2023, 11, 12, 15, 24, 20), minute=120)          
INFO     15:14:01.456 │ Bind task {'Alas', 'Commission', 'General'}                
INFO     15:14:01.458 │ Save config ./config\alas.json,                            
         GemsFarming.Scheduler.NextRun=datetime.datetime(2023, 11, 12, 15, 24, 20) 
INFO     15:14:01.464 │ Scheduler: End task `Commission`       

观察一会发现有这样的log，但是委托队伍里并没有混入要上场的白皮船。后续如果发现其他中断情况再观察

INFO     15:34:49.590 │ Delay task `Commission` to 2023-11-12 16:24:44             
         (target=datetime.datetime(2023, 11, 12, 16, 24, 44))                      
INFO     15:34:49.598 │ Bind task {'Alas', 'Commission', 'General'}                
INFO     15:34:49.599 │ Save config ./config\alas.json,                            
         Commission.Scheduler.NextRun=datetime.datetime(2023, 11, 12, 16, 24, 44)  
INFO     15:34:49.607 │ Daily commission: 2, filtered_urgent: 2                    
INFO     15:34:49.608 │ Having daily commissions to do, delay task `GemsFarming`   
INFO     15:34:49.609 │ Delay task `GemsFarming` to 2023-11-12 16:24:44            
         (target=datetime.datetime(2023, 11, 12, 16, 24, 44), minute=120)          
INFO     15:34:49.623 │ Bind task {'Alas', 'Commission', 'General'}                
INFO     15:34:49.624 │ Save config ./config\alas.json,                            
         GemsFarming.Scheduler.NextRun=datetime.datetime(2023, 11, 12, 16, 24, 44) 
INFO     15:34:49.629 │ Scheduler: End task `Commission`                        

同样的log又出现了一次，刷紧急的计时器被推迟到和接委托相同，看上去似乎是委托干扰到了刷紧急的启动条件，无论有没有低耗船在跑委托都会导致这项任务卡住

**Comment by studyingCHJ** [comment]
你选了“防止紧急委托数量过多”，会先把日常委托做完

**Comment by clark1091** [comment]
咦原来这个选项是这么工作的？我还以为是和委托那里协同的，希望后面UI里能多补充一句说明吧，有点误导= =
