### ISSUE TITLE
请求实现主线图15图开荒和打捞功能，尤其是15-4绿海打捞

### ISSUE THREAD

**Issue by Arcohyp** [LmeSzinc/AzurLaneAutoScript#3296]
### 你的功能请求是否与问题有关？

检索了以往的issues，暂未发现关于主线15图开荒和打捞的内容

### 解决方案

1.可能需要增加assets: 
（1）15图的出击界面和前面主线图的不一样（4行内容导致选择/清空/推荐/取消等按键有偏移），可能需要更新assets/服务器/map下出击方面的内容
（2）15图需要处理航空驱离，航空打击（为了通关相对轻松），可能需要添加assets/服务器/handler的内容
（3）可能需要添加新船（比如15-4的航空船敌人）的图片
（4）其他可能需要的图片？

2.可能需要修改的代码文件：
（1）map_fleet_preparation.py：针对15图选择新的button
（2）strategy.py：处理航空驱离（比如指定网格点，15-4的J8到旁边一格等），航空打击（K9或者A1）。可能为了简化好像没有导驱的打击？
（3）campaign/campaign_main文件夹下的地图信息：大概就是一队1、3boss，和所有小怪，二队2boss；或者反过来。
（4）其他UI相关的内容？

### 其他内容

如果能实现不胜感激，不然只能等官方出自律寻敌再打捞吧

**Comment by Mr-Dizzy** [comment]
真要写的话，弄个简单点的出2boss切换2队打，1队打所有道中和1、3boss这种比较现实而且也就够用了

**Comment by Arcohyp** [comment]
是的，这样确实会比较简单粗暴。但参考了一下14图的非自律代码逻辑，优先点亮灯塔/捡照明弹被放在了前几个battle下，那么考虑到大多数玩家的实际需要，降低推图门槛，15图内的战斗逻辑最好是：
战斗过程中：
1.驱逐前往航空支援的敌方舰队道路中的敌方舰队
（1）打开策略
（2）选择舰队驱逐
（3）选择被驱逐的敌方舰队（点击会出现白色航空标志，并出现4个方向的箭头）
（4）点击任意一个出现的箭头
（5）弹窗确认驱逐
（6）回到策略
2.使用航空打击航空支援的敌方舰队（可选）
3.优先与航空支援的敌方舰队交战
4.捡取子弹（有实现的函数）
5.出2boss切换2队打，1队打所有道中和1、3boss；或反过来。
个人认为以上1、2、3、5是15图的特质，类似14图的捡照明弹或点亮灯塔，合理利用机制玩游戏或许更加优雅？

**Comment by Arcohyp** [comment]
> 真要写的话，弄个简单点的出2boss切换2队打，1队打所有道中和1、3boss这种比较现实而且也就够用了

行吧，简单有效，参考着改了下，剩下的就交给其他大佬优化了
from module.campaign.campaign_base import CampaignBase
from module.map.map_base import CampaignMap
from module.map.map_grids import SelectedGrids, RoadGrids
from module.logger import logger
# from .campaign_15_1 import Config as ConfigBase

MAP = CampaignMap('15-4')
MAP.shape = 'K9'
MAP.camera_data = ['B2', 'C8', 'D7', 'H2', 'H6', 'H7']
MAP.camera_data_spawn_point = ['H2']
MAP.map_data = """
    ME -- ME ME Me -- ME ++ ++ ME ME
    ME -- -- -- -- ME -- ++ ++ -- ME
    ++ -- -- -- -- -- ME SP SP ME Me
    ++ ME -- ++ ++ -- -- -- -- ME --
    -- Me ME MA ++ ME -- -- -- -- ME
    ME ME ME -- -- -- -- ++ ME -- Me
    ME -- __ -- ME ME -- ME ME -- ++
    -- -- ++ -- Me -- ME ME ME ME --
    MB Me -- ME ME Me ++ ++ ++ -- ME
"""
MAP.weight_data = """
    10 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 20 50
    50 50 50 50 50 50 50 50 50 50 30
"""
MAP.spawn_data = [
    {'battle': 0, 'enemy': 5, 'mystery': 2},
    {'battle': 1, 'enemy': 1},
    {'battle': 2, 'enemy': 1},
    {'battle': 3, 'enemy': 1},
    {'battle': 4},
    {'battle': 5},
    {'battle': 6},
    {'battle': 7, 'boss': 1},
]
A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, \
A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, \
A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, \
A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, \
A5, B5, C5, D5, E5, F5, G5, H5, I5, J5, K5, \
A6, B6, C6, D6, E6, F6, G6, H6, I6, J6, K6, \
A7, B7, C7, D7, E7, F7, G7, H7, I7, J7, K7, \
A8, B8, C8, D8, E8, F8, G8, H8, I8, J8, K8, \
A9, B9, C9, D9, E9, F9, G9, H9, I9, J9, K9, \
    = MAP.flatten()


class Config:
    HOMO_EDGE_COLOR_RANGE = (0, 49)
    HOMO_EDGE_HOUGHLINES_THRESHOLD = 210

    # Disabled because having errors
    MAP_SWIPE_PREDICT_WITH_SEA_GRIDS = False
    # Ambushes can be avoid by having more DDs.
    MAP_WALK_OPTIMIZE = False
    # ===== Start of generated config =====
    MAP_HAS_SIREN = False
    MAP_HAS_MOVABLE_ENEMY = False
    MAP_HAS_MAP_STORY = False
    MAP_HAS_FLEET_STEP = False
    MAP_HAS_AMBUSH = True
    MAP_HAS_MYSTERY = True
    # ===== End of generated config =====


class Campaign(CampaignBase):
    MAP = MAP
    ENEMY_FILTER = '1L > 1M > 1E > 1C > 2L > 2M > 2E > 2C > 3L > 3M > 3E > 3C'

    def battle_0(self):
        return self.battle_default()

    def battle_3(self):
        self.fleet_1.clear_chosen_enemy(H5)
        self.fleet_1.pick_up_ammo()

        return self.fleet_1.battle_default()

    # F1: 4 5
    # 4,5 = normal

    # F2: 6
    def battle_6(self):
        # switch to fleet 2
        self.fleet_2.clear_chosen_enemy(D3)
        # switch to fleet 1
        return self.fleet_1.battle_default()

    # F1: 7 8
    # 7 = normal
    def battle_8(self):
        return self.fleet_1.clear_boss()
