### ISSUE TITLE
运行时未知原因引发mxnet"Failed to allocate CPU Memory"错误

### ISSUE THREAD

**Issue by Tachibana-Kin** [LmeSzinc/AzurLaneAutoScript#3299]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

前期运行时出现不间断卡死。alas上报wait too long

回溯error logs 时发现一黑白屏现象

2023/11/21晚8时许，重开alas。在运行Zotero(基于 Firefox 构建)时，zotero闪退，alas报错误“Failed to allocate CPU Memory”随后终止。重开一次无效后触发BSoD。

20：47 编写时再次终止运行。模拟器自动重启，报错1040

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13426308/log.txt)
![2023-11-21_20-15-41-554984](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/19606268/0af32a2d-e3fd-4a64-8f10-98d1e851919d)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13426407/log.txt)
![2023-11-21_20-15-41-554984](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/19606268/df821866-bf23-4169-930f-900e4ac0959c)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13426429/log.txt)
![2023-11-21_13-57-51-837221](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/19606268/a91f5477-6cbb-4a50-8938-e864d05d7de5)
[112123-11812-01.dmp](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13426449/112123-11812-01.dmp)

### 还有别的吗？

模拟器：夜神模拟器 7.0.5.9 Android12版本  在卸载docker for windows以后，卸载虚拟机组建后从hyper-v版bluestacks迁移。

Windows 11 22621.2787(Insider Release Preview通道)

**Comment by Tachibana-Kin** [comment]
模拟器报错1040疑似归因于nv驱动（附夜神11/22崩溃时日志与dump
[Nox.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13433116/Nox.zip)

**Comment by LmeSzinc** [comment]
`Failed to allocate CPU Memory` 的字面意思，你的电脑内存不足导致 Alas 和模拟器同步崩溃

**Comment by Tachibana-Kin** [comment]
鉴于主机16g物理内存和20g的虚拟内存，暂不考虑硬件问题导致崩溃
将显卡驱动降一级，并修改渲染方式后，正常运行2h余
基于现状，初步结论为夜神模拟器与nv新驱动之间疑似存在兼容性问题。
