### ISSUE TITLE
最新活动「苍闪忍法帖」无法自动刷本

### ISSUE THREAD

**Issue by x1906875173** [LmeSzinc/AzurLaneAutoScript#3303]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

最新活动「苍闪忍法帖」无法自动刷本

### 如何复现

1. 前往 '苍闪忍法帖'活动
2. 点击 '关卡'

4. 出现问题

### 预期行为

正常打本

### 相关 Logs

```Text
无
```

### 截图

无

### 还有别的吗？

无

**Comment by SaarChaffee** [comment]
搁这贴瓷砖呢？

**Comment by bookbug666** [comment]
大哥...你發的時候遊戲都沒維修呢

**Comment by x1906875173** [comment]
> 大哥...你發的時候遊戲都沒維修呢

早晚都有人会发的，我提早发，成为第一人😋

**Comment by sasaku-s** [comment]
生产队的驴都不能这么赶啊
