### ISSUE TITLE
自动开荒某些地图卡住

### ISSUE THREAD

**Issue by chenhao1999** [LmeSzinc/AzurLaneAutoScript#3316]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

自动开荒功能在遇到带有那个提交资源或者直接破坏的选项那个箱子的地图会卡住
推测是因为游戏自带的大世界自动不会清理这个箱子而且这个箱子只要不清除就不会变成安全海域
脚本也不能正常识别并且点掉这个箱子，导致自动开荒一直卡在这个图上不往前推进度

### 如何复现

1. 前往 '大世界'，打开脚本自动开荒模式
2. 找到一个含有那个带选项的箱子且没变成安全海域的地图
3. 使用脚本的自动开荒功能来对这个地图进行开荒
4. 运行到最后地图上会只剩下那个带有选项的箱子，且开荒进度停住
5. 开荒失败后脚本会回到港口并且将开荒进度清零，之后一直死循环

### 预期行为

脚本可以正确识别那个箱子，不要被卡住

**Comment by LmeSzinc** [comment]
阅读
https://github.com/LmeSzinc/AzurLaneAutoScript#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
