### ISSUE TITLE
能否加上黄脸时道中和boss队自动互换

### ISSUE THREAD

**Issue by laiwei-f** [LmeSzinc/AzurLaneAutoScript#3327]

**Comment by LmeSzinc** [comment]
意义不明

**Comment by laiwei-f** [comment]
但是考虑到活动图一些关卡可以锁油刷pt，加上智能互换也许更高效；

**Comment by laiwei-f** [comment]
2333，后面两句太幽默了，也是，我一般三星之后随便六船刷pt了，倒是没想过可以5油策略，确实这样更具性价比

**Comment by tuman-qahraman** [comment]
> > 但是考虑到活动图一些关卡可以锁油刷pt，加上智能互换也许更高效；
> 
> 锁油的图刷pt还是要低耗，20油与5油没有任何可比性。 而且如果你要满油刷，实际的瓶颈是在石油而不是心情，alas满油刷一天sp5之类的160油关卡，能直接消耗一、两万油，中东美军也顶不住。

我是日服玩家，没有低耗。
