### ISSUE TITLE
刷紧急委托添加撤退条件

### ISSUE THREAD

**Issue by qwe3123s** [LmeSzinc/AzurLaneAutoScript#3333]
### 你的功能请求是否与问题有关？

无

### 解决方案

在7-2三站战拾取完物资后撤退，即第四战开始前。添加到刷紧急委托或者主线图。

### 其他内容

alas挂久了后，后宅食物已经不够用了，前中期物资也比较缺。7-2刷物资和食物，只需要三战，BOSS空弹对于低耗难度较高，3油三战性价比高。功能添加到刷紧急委托就挺好。

**Comment by guoh064** [comment]
锁油时代啦，别7-2炼金了，快去12-4/13-4提款吧

**Comment by qwe3123s** [comment]
我主要是刷食物，物资拿去买外观箱子了
