### ISSUE TITLE
有考虑增加15图主线自律吗？

### ISSUE THREAD

**Issue by aml2023529** [LmeSzinc/AzurLaneAutoScript#3338]
### 你的功能请求是否与问题有关？

是否可以增加只看见了14并没有看见15如果有请告诉我在那设置

### 其他内容

ARNING  21:40:36.436 │ Map file not found: campaign.campaign_main.campaign_15_4   
WARNING  21:40:36.438 │ Existing files: ['campaign_10_1', 'campaign_10_2',         
         'campaign_10_3', 'campaign_10_4', 'campaign_11_1', 'campaign_11_2',       
         'campaign_11_3', 'campaign_11_4', 'campaign_12_1', 'campaign_12_2',       
         'campaign_12_2_leveling', 'campaign_12_3', 'campaign_12_4',               
         'campaign_12_4_leveling', 'campaign_12_4_timeout_leveling',               
         'campaign_13_1', 'campaign_13_2', 'campaign_13_3', 'campaign_13_4',       
         'campaign_14_1', 'campaign_14_2', 'campaign_14_3', 'campaign_14_4',       
         'campaign_14_base', 'campaign_1_1', 'campaign_1_1_affinity_farming',      
         'campaign_1_2', 'campaign_1_3', 'campaign_1_4', 'campaign_2_1',           
         'campaign_2_2', 'campaign_2_3', 'campaign_2_4', 'campaign_3_1',           
         'campaign_3_2', 'campaign_3_3', 'campaign_3_4', 'campaign_4_1',           
         'campaign_4_2', 'campaign_4_3', 'campaign_4_4', 'campaign_5_1',           
         'campaign_5_2', 'campaign_5_3', 'campaign_5_4', 'campaign_6_1',           
         'campaign_6_2', 'campaign_6_3', 'campaign_6_4', 'campaign_7_1',           
         'campaign_7_2', 'campaign_7_2_mystery_farming', 'campaign_7_3',           
         'campaign_7_4', 'campaign_8_1', 'campaign_8_2', 'campaign_8_3',           
         'campaign_8_4', 'campaign_8_4_leveling', 'campaign_9_1', 'campaign_9_2',  
         'campaign_9_3', 'campaign_9_4']

**Comment by lzy0702** [comment]
附议。
由于15-3和15-4分别有2个和3个boss需要打，建议单独增加额外选项决定两队打boss的顺序

**Comment by zhulinyv** [comment]
附议：
15 图有超级大航，建议增加选项来优先迎击。

**Comment by StortInter** [comment]
对于15-4我有尝试过自己添加地图文件，逻辑是：

> 1队进行1-3战（大航-侦察-大航）
> 1队捡弹药
> 1队boss战
> 1队进行4-5战
> 2队boss战
> 1队进行第6战
> 1队boss战

`battle_0`到`battle_2`通过手动指定位置进行：

```python
class Campaign(CampaignBase):
    MAP = MAP

    def base_clear_enemy(self):
        if self.fleet_1.clear_enemy(weakest=True, genre=['light', 'carrier', 'treasure', 'main', 'enemy']):
            return True
        return self.battle_default()

    def battle_0(self):
        if self.fleet_1.clear_roadblocks([RoadGrids([A1])]):
            return True
        return self.battle_default()

    def battle_1(self):
        if self.clear_roadblocks([RoadGrids([J8])]):
            return True
        return self.battle_default()

    def battle_2(self):
        if self.clear_roadblocks([RoadGrids([K9])]):
            return True
        return self.battle_default()

    def battle_3(self):
        self.pick_up_ammo()
        if self.brute_clear_boss_mod(self.fleet_1):
            return True
        return self.battle_default()

    def battle_4(self):
        return self.base_clear_enemy()

    def battle_5(self):
        return self.base_clear_enemy()

    def battle_6(self):
        if self.brute_clear_boss():
            return True
        return self.battle_default()

    def battle_7(self):
        return self.base_clear_enemy()

    def battle_8(self):
        return self.brute_clear_boss_mod(self.fleet_1)

    def brute_clear_boss_mod(self, fleet):
        boss = self.map.select(is_boss=True)
        if boss:
            logger.info('Brute clear BOSS')
            grids = self.brute_find_roadblocks(boss[0], fleet=fleet)
            if grids:
                if self.brute_fleet_meet():
                    return True
                logger.info('Brute clear BOSS roadblocks')
                grids = grids.sort('weight', 'cost')
                logger.info('Grids: %s' % str(grids))
                self.clear_chosen_enemy(grids[0])
                return True
            else:
                return fleet.clear_boss()
        elif self.map.select(may_boss=True, is_caught_by_siren=True):
            logger.info('BOSS appear on fleet grid')
            self.fleet_2.switch_to()
            return self.clear_chosen_enemy(self.map.select(may_boss=True, is_caught_by_siren=True)[0])
        else:
            logger.warning('BOSS not detected, trying all boss spawn point.')
            return self.clear_potential_boss()

```

问题在于“支援舰队”会影响地图识别和触控，我有尝试添加图片检测关闭它，但是每一战这玩意就会冒出来，需要在每次海图识别之前把它点掉；还有就是舰队在打完boss之后就不再继续识别了，虽然这里修改了boss战的函数，但未能解决，应该还需要修改一下执行逻辑。

**Comment by LmeSzinc** [comment]
#3563
