### ISSUE TITLE
4399求添加AGREEMENT_CONFIRM

### ISSUE THREAD

**Issue by W1NDes** [LmeSzinc/AzurLaneAutoScript#3339]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

4399有时候会出现账号用户协议同意，会导致alas卡死。登录所需的相关图片已经提供。十分感谢。

### 如何复现

1. 启动'alas'

### 预期行为

希望开发团队可以实现处理4399渠道服的登录协议同意：
首先会出现第一张同意按钮：
![MuMu12-20231207-221429](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/4aa133c7-82d8-49f9-95ed-2bee0236464d)
点击后会出现第二张图，需要点击授权同意才可以正常登录账号：
![MuMu12-20231207-221357](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/e8f220e4-a73e-4ce5-b6f4-dd6efbc32b62)
原始截图文件在截图一栏

### 截图

![MuMu12-20231207-221429 - 副本](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/413429d4-f213-46de-bea2-156ef27090fb)
![MuMu12-20231207-221357 - 副本](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/f6d485a2-7fcd-4183-8372-c325551f34d2)

**Comment by LmeSzinc** [comment]
渠道服不提供支持，适配可以提交PR

**Comment by W1NDes** [comment]
> 渠道服不提供支持，适配可以提交PR

好的
