### ISSUE TITLE
请求添加报错提示功能

### ISSUE THREAD

**Issue by Kanbale** [LmeSzinc/AzurLaneAutoScript#3346]
### 你的功能请求是否与问题有关？

希望在执行时遇到错误、重启无效导致自动程序终止的时候，能够发送一个系统通知以及可以调整的警告提示声。很多时候在后台默默报错了卡住了都不知道。
并且在昨晚出现了没有任何报错内容突然终止（只有提示发生错误，控制台输出没有任何问题显示（在小游戏时发生））

**Comment by guoh064** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Onepush-configuration-%5BCN%5D

**Comment by Kanbale** [comment]
现在已经成功设置好邮箱推送了。不过还是希望能有更直接的在电脑上推送的方式（类似系统通知弹窗），但大概考虑到云服务器等运行环境所以没有吧。
