### ISSUE TITLE
委托无法关闭，且修改委托时间无效

### ISSUE THREAD

**Issue by xxxscarlxrd404** [LmeSzinc/AzurLaneAutoScript#3347]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

背景：石油已满的情况下会导致委托无法完成，alas报错自动重启并陷入死循环

### 如何复现

1. 前往 '收获'-'委托'
2. 仅有已开启，**开关button丢失**
3. 尝试**修改时间**至明日，在委托详情页提示_已保存设置_
5. 回到‘总览’页面，委托时间未修改，仍是之前的时间

### 预期行为

1.委托行为可关闭
2.可修改委托时间

### 截图

<img width="1798" alt="image" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48848451/6beeac39-ad3a-46d0-91da-555426e910bf">
<img width="1800" alt="image" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48848451/daa9d377-8820-410f-ad64-862fc50288f0">

**Comment by weeswelai** [comment]
请自行后宅买咖喱消耗溢出的石油 (为什么用alas石油还能溢出?

**Comment by guoh064** [comment]
赶快收了神通吧

**Comment by DSC-Qian** [comment]
委托是默认开着的，貌似原因是防止被人拿去收费代挂时收委托还要加钱（可能记错）

**Comment by TarringFox** [comment]
花几千油买咖喱就跟杀了你吗似的？反正这个开关就常开了，不爽就用别家脚本去

**Comment by xxxscarlxrd404** [comment]
> 花几千油买咖喱就跟杀了你吗似的？反正这个开关就常开了，不爽就用别家脚本去
两三周没关注游戏运行情况了，发现脚本异常，尝试恢复运行之后循环报错，就以为是个bug，没必要戾气这么大吧

**Comment by xxxscarlxrd404** [comment]
> 请自行后宅买咖喱消耗溢出的石油 (为什么用alas石油还能溢出?

好的，忘了石油还能买后宅物资了...

**Comment by TarringFox** [comment]
> > 花几千油买咖喱就跟杀了你吗似的？反正这个开关就常开了，不爽就用别家脚本去
> > 两三周没关注游戏运行情况了，发现脚本异常，尝试恢复运行之后循环报错，就以为是个bug，没必要戾气这么大吧

想关委托还说出来，被骂可太正常了。基本上想这么干的十有八九沾点破烂游戏理解和成分不明。下次有这种的还骂，这是必要之恶。
以及你，光瞪着alas，在这“啊啊啊怎么又报错了”的抱怨都不去看一眼游戏里画面，你也是天才。
好了，你不是知道该怎么解决这个卡住的问题了吗，去解决掉，然后再运行就行了。

**Comment by xxxscarlxrd404** [comment]
> > > 花几千油买咖喱就跟杀了你吗似的？反正这个开关就常开了，不爽就用别家脚本去
> > > 两三周没关注游戏运行情况了，发现脚本异常，尝试恢复运行之后循环报错，就以为是个bug，没必要戾气这么大吧
> 
> 想关委托还说出来，被骂可太正常了。基本上想这么干的十有八九沾点破烂游戏理解和成分不明。下次有这种的还骂，这是必要之恶。 以及你，光瞪着alas，在这“啊啊啊怎么又报错了”的抱怨都不去看一眼游戏里画面，你也是天才。 好了，你不是知道该怎么解决这个卡住的问题了吗，去解决掉，然后再运行就行了。

因为我挂机的机器不在本地，当时只能frp远程看alas的管理界面，看日志是委托报错就下意识的想先关闭委托和尝试把委托时间修改到几小时后再运行，发现修改时间也不生效之后才以为是个bug。没想到还有这么层历史原因
题外话（收费代挂委托还另外加钱着实有点神必
