### ISSUE TITLE
ALAS无法找到ADB端口

### ISSUE THREAD

**Issue by zeiyu314** [LmeSzinc/AzurLaneAutoScript#3359]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

<img width="482" alt="image" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/44489550/76d26e4d-a243-4777-a55e-812676ff0c1e">
如图。
<img width="315" alt="image" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/44489550/eb56f61c-dc78-4ba2-b156-e9f610af6dab">
我尝试手动设置端口，但是每次启动都会被覆盖。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题
使用蓝叠模拟器版本5.11.1004 P64
和最新版ALAS

**Comment by Sean-Shikkk** [comment]
应该是blue stack adb端口换了，alas serial 填auto我也连不上，serial填 127.0.0.1:7016， screenshot method 选adb就可以了，我的blue stack 版本是5.12.0

**Comment by LmeSzinc** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/22befb4e-7ca5-4470-bd42-723e5850bb40)

**Comment by zeiyu314** [comment]
> 应该是blue stack adb端口换了，alas serial 填auto我也连不上，serial填 127.0.0.1:7016， screenshot method 选adb就可以了，我的blue stack 版本是5.12.0

感谢
