### ISSUE TITLE
大世界每日陷入死循环

### ISSUE THREAD

**Issue by merakian2** [LmeSzinc/AzurLaneAutoScript#3367]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

本来应让舰队前往任务海域中的实验场，但Alas在点击自律寻敌后被游戏提示视野内无可自律事件，随后不断往返NY港口和西大陆架B，陷入死循环。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

地图内有双舰队机关，Alas对其也没有反应。

### 截图

![com bilibili blhx vivo_Screenshot_2023 12 21_21 13 31](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/98706851/bf15d5ce-3e2a-4b09-9325-d19a71fa8e89)
![com bilibili blhx vivo_Screenshot_2023 12 21_21 17 00](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/98706851/11bab2d1-2f73-4d1f-a02e-411e00ec720c)

### 还有别的吗？

使用Bluestacks 4最新版，Naugot 32位引擎。

**Comment by merakian2** [comment]
[2023-12-21_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/13752914/2023-12-21_alas.txt)
log太长了放不下，所以在这里提供

**Comment by LmeSzinc** [comment]
大世界主线自己完成

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/69576768-7ea2-47d1-8613-61a21208cb8b)

**Comment by merakian2** [comment]
> 大世界主线自己完成
> 
> ![image](https://private-user-images.githubusercontent.com/37934724/292530051-69576768-7ea2-47d1-8613-61a21208cb8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjIzNjcsIm5iZiI6MTcwMzM2MjA2NywicGF0aCI6Ii8zNzkzNDcyNC8yOTI1MzAwNTEtNjk1NzY3NjgtN2VhMi00N2QxLTg2MTMtNjFhMjEyMDhjYjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIwMDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzBlNWQ5ZTg3MjA2ZDAyZmU2ODBhNmI0Yjg0M2MwYWU0YmUxYTRkYmY5MWE0ZmVhNTVkN2FmNGY5YWZjM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y_UlWby57XMtBDJiHx7xAfRMd3-py99Gelm-azCkwuA)

![com bilibili blhx vivo_Screenshot_2023 12 23_15 07 09](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/98706851/5335aaa0-f6ef-49ff-8780-658ce4941e19)
大世界主线这算没有完成么？我已经顺着游戏的指引进核心区打过一次了。

**Comment by LmeSzinc** [comment]
> 大世界主线自己完成
> 
> ![image](https://private-user-images.githubusercontent.com/37934724/292530051-69576768-7ea2-47d1-8613-61a21208cb8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzEwNjYsIm5iZiI6MTcwNDMzMDc2NiwicGF0aCI6Ii8zNzkzNDcyNC8yOTI1MzAwNTEtNjk1NzY3NjgtN2VhMi00N2QxLTg2MTMtNjFhMjEyMDhjYjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAxMTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMTU5MTFkMzllOTI5NTUyZWNiNTg4OTk2ZTdlYWFhM2FmYzgzMmRkMzQyNjFmOTZhNWNjMDg5OGIxOTI2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3zVQj2sM1CYLM6zimPZScODhPsJER3afNOOxiv80fDI)

完成这张图里的事件
