### ISSUE TITLE
希望增加一个队伍绑定功能

### ISSUE THREAD

**Issue by AbyssAzrael** [LmeSzinc/AzurLaneAutoScript#3372]
### 你的功能请求是否与问题有关？

我的每日AB图和活动c2用的同一个低耗队伍，刷完每日ab图后再连续出击c2会导致心情对不上，造成红脸

### 解决方案

将不同任务里的舰队绑定一下（？）以适配心情变化
例如 每日活动X图与活动图的某个出击舰队能绑定在一起
希望出一个类似功能使这样出击方便一点
（顺带我上次提的温泉功能也没回复）

**Comment by LmeSzinc** [comment]
不能在多个任务之间共享角色
