### ISSUE TITLE
请问目前是否有记录某一队沉船的功能（以截图或者文字log的方式）？

### ISSUE THREAD

**Issue by john-c-frank** [LmeSzinc/AzurLaneAutoScript#3377]
### 你的功能请求是否与问题有关？

低耗队有的时候不确定是否存在小概率的沉船可能性，只能人工盯着看两三把，无法一直监视

### 解决方案

记录某一队沉船的功能（以截图或者文字log的方式）

**Comment by LmeSzinc** [comment]
脚本不负责解决练度问题
