### ISSUE TITLE
最近挂活动总是一直有问题直接停止

### ISSUE THREAD

**Issue by Bigorange11** [LmeSzinc/AzurLaneAutoScript#3378]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

最近挂活动总是一直有问题直接停止，现在还处于清图阶段，但是经常启动之后，就会直接停止，不会选怪去打，请问大家都有这种情况吗
![999](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135260683/26c7da99-8a7d-481e-b0e3-a2a0f11f1719)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![999](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/135260683/51f82544-3290-4d12-bec6-35f4bc6f8461)

**Comment by Bigorange11** [comment]
> 什么模拟器？雷电吗？

是的！没错！用什么模拟器更好嘛

**Comment by SteveWYSism** [comment]
> > 什么模拟器？雷电吗？
> 
> 是的！没错！用什么模拟器更好嘛

试试蓝叠&你这个是太多次重复点击，运行时看看游戏内的点击有没有问题，有时候跳小黄鸡也会出这个问题

**Comment by Neroli1108** [comment]
夜神模拟器有相同的问题。

**Comment by clearwater753** [comment]
mumu模拟器有相同的问题

**Comment by LmeSzinc** [comment]
## 如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

- 在提问题前，请先阅读 [常见问题(FAQ)](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn)。
- 检查 Alas 的更新和最近的 commit，确认使用的是最新版。
- 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
