### ISSUE TITLE
Wrong mxnet version in requirements

### ISSUE THREAD

**Issue by observeroftime02** [LmeSzinc/AzurLaneAutoScript#34]
Installing the requirements via "pip install  -r requirements.txt" produces the following error:

> ERROR: Could not find a version that satisfies the requirement mxnet==1.4.1 (from -r requirements.txt (line 9)) (from versions: 0.11.1b20170915, 0.11.1b20170922, 0.11.1b20170929, 0.11.1b20171006, 0.11.1b20171013, 0.12.0b20171020, 0.12.0b20171027, 0.12.0, 0.12.1b20171103, 0.12.1, 1.0.0, 1.0.0.post1, 1.0.0.post3, 1.0.0.post4, 1.0.1b20180114, 1.0.1b20180121, 1.0.1b20180128, 1.0.1b20180202, 1.1.0b20180209, 1.1.0b20180216, 1.1.0.post0, 1.2.0b20180223, 1.2.0b20180302, 1.2.0b20180309, 1.2.0b20180323, 1.2.0b20180330, 1.2.0b20180406, 1.2.0b20180413, 1.2.0b20180420, 1.2.0b20180427, 1.2.0b20180504, 1.2.0, 1.6.0)
ERROR: No matching distribution found for mxnet==1.4.1 (from -r requirements.txt (line 9))

Can a different version be used?

**Comment by lovelessangel** [comment]
I found the same error before. Finally I solved this problem by changed the version of python. Are you using a x86 version? I sugguest you download this one: https://www.python.org/ftp/python/3.7.6/python-3.7.6-amd64.exe

**Comment by whoamikyo** [comment]
read https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/doc/Quick_guide.md
