### ISSUE TITLE
希望增加“任务队列清空后“的停止界面选择以长期降低功耗

### ISSUE THREAD

**Issue by lxyabc98** [LmeSzinc/AzurLaneAutoScript#3401]
### 你的功能请求是否与问题有关？

![{EC0E56CB-4CFA-4c21-B406-3B857757E28E}](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/92701713/d7148cd6-a45d-4705-a7f2-0d898188923c)
m2芯片在静态界面功耗只有6W不到，但是动态界面如l2d，大世界会上升到13W甚至更高。
已有方案除了关闭游戏都有可能停留在长期高功耗的界面，而反复关闭游戏对模拟器不是太友好，希望增加一个游戏内必然是静态界面的选项

### 解决方案

前往主界面后任意进入一个静态界面如“个人信息”，“任务”，“仓库”，“科研”

**Comment by LmeSzinc** [comment]
选关闭游戏就好，模拟器本质也是一个软件，没什么好心疼的
