### ISSUE TITLE
活动困难图与普通图部分舰船会出现交叉

### ISSUE THREAD

**Issue by PsionicZephyr** [LmeSzinc/AzurLaneAutoScript#3402]
### 你的功能请求是否与问题有关？

活动困难图所用的舰船常常会和普通图舰队中的舰船有交叉，alas会将困难图舰队判定为一个独立的舰队，这就导致心情控制会出现差错。
比如在使用低耗队完成每日A&B图任务后，再反复刷C2时实际心情会比预期要低。测试中即便设置成防止绿脸（>40）最终也极有可能发展出红脸的情况。

### 解决方案

加入一个勾选框，勾选时无视困难图设定，正常记录出击舰队设置中的舰队心情，或者干脆开放自行设定心情控制阈值。

**Comment by LmeSzinc** [comment]
配对问题，多任务之间不能共享角色
