### ISSUE TITLE
gui界面有时侧边栏和其他框会消失，只能显示等待中的任务列表

### ISSUE THREAD

**Issue by lin-charles** [LmeSzinc/AzurLaneAutoScript#3404]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![QQ截图20240102195819](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/15243252/d20cac58-7401-4f65-bc58-68a37a6b4ac8)
如图所示，有时侧边栏和其他的框会消失，只能显示等待中的任务列表
任务正常执行，只是gui界面出问题

### 如何复现

1.拥有两个以上的配置文件
2.在侧边栏切换配置文件，反复几次后触发

使用远程桌面，有时断开再连接也会触发

使用的是最新版本Alas

### 预期行为

![QQ截图20240102195819](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/15243252/4546cfce-1249-4a58-9aaf-c96605e4b64c)
 进入该界面

**Comment by guoh064** [comment]
按`Ctrl+R`刷新

**Comment by sasaku-s** [comment]
别点太快
