### ISSUE TITLE
> 真要写的话，弄个简单点的出2boss切换2队打，1队打所有道中和1、3boss这种比较现实而且也就够用了

### ISSUE THREAD

**Issue by BZBY** [LmeSzinc/AzurLaneAutoScript#3417]
> 真要写的话，弄个简单点的出2boss切换2队打，1队打所有道中和1、3boss这种比较现实而且也就够用了

行吧，简单有效，参考着改了下，剩下的就交给其他大佬优化了
from module.campaign.campaign_base import CampaignBase
from module.map.map_base import CampaignMap
from module.map.map_grids import SelectedGrids, RoadGrids
from module.logger import logger
# from .campaign_15_1 import Config as ConfigBase

MAP = CampaignMap('15-4')
MAP.shape = 'K9'
MAP.camera_data = ['B2', 'C8', 'D7', 'H2', 'H6', 'H7']
MAP.camera_data_spawn_point = ['H2']
MAP.map_data = """
    ME -- ME ME Me -- ME ++ ++ ME ME
    ME -- -- -- -- ME -- ++ ++ -- ME
    ++ -- -- -- -- -- ME SP SP ME Me
    ++ ME -- ++ ++ -- -- -- -- ME --
    -- Me ME MA ++ ME -- -- -- -- ME
    ME ME ME -- -- -- -- ++ ME -- Me
    ME -- __ -- ME ME -- ME ME -- ++
    -- -- ++ -- Me -- ME ME ME ME --
    MB Me -- ME ME Me ++ ++ ++ -- ME
"""
MAP.weight_data = """
    10 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 50 50
    50 50 50 50 50 50 50 50 50 20 50
    50 50 50 50 50 50 50 50 50 50 30
"""
MAP.spawn_data = [
    {'battle': 0, 'enemy': 5, 'mystery': 2},
    {'battle': 1, 'enemy': 1},
    {'battle': 2, 'enemy': 1},
    {'battle': 3, 'enemy': 1},
    {'battle': 4},
    {'battle': 5},
    {'battle': 6},
    {'battle': 7, 'boss': 1},
]
A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, \
A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, \
A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, \
A4, B4, C4, D4, E4, F4, G4, H4, I4, J4, K4, \
A5, B5, C5, D5, E5, F5, G5, H5, I5, J5, K5, \
A6, B6, C6, D6, E6, F6, G6, H6, I6, J6, K6, \
A7, B7, C7, D7, E7, F7, G7, H7, I7, J7, K7, \
A8, B8, C8, D8, E8, F8, G8, H8, I8, J8, K8, \
A9, B9, C9, D9, E9, F9, G9, H9, I9, J9, K9, \
    = MAP.flatten()

class Config:
    HOMO_EDGE_COLOR_RANGE = (0, 49)
    HOMO_EDGE_HOUGHLINES_THRESHOLD = 210

    # Disabled because having errors
    MAP_SWIPE_PREDICT_WITH_SEA_GRIDS = False
    # Ambushes can be avoid by having more DDs.
    MAP_WALK_OPTIMIZE = False
    # ===== Start of generated config =====
    MAP_HAS_SIREN = False
    MAP_HAS_MOVABLE_ENEMY = False
    MAP_HAS_MAP_STORY = False
    MAP_HAS_FLEET_STEP = False
    MAP_HAS_AMBUSH = True
    MAP_HAS_MYSTERY = True
    # ===== End of generated config =====

class Campaign(CampaignBase):
    MAP = MAP
    ENEMY_FILTER = '1L > 1M > 1E > 1C > 2L > 2M > 2E > 2C > 3L > 3M > 3E > 3C'

    def battle_0(self):
        return self.battle_default()

    def battle_3(self):
        self.fleet_1.clear_chosen_enemy(H5)
        self.fleet_1.pick_up_ammo()

        return self.fleet_1.battle_default()

    # F1: 4 5
    # 4,5 = normal

    # F2: 6
    def battle_6(self):
        # switch to fleet 2
        self.fleet_2.clear_chosen_enemy(D3)
        # switch to fleet 1
        return self.fleet_1.battle_default()

    # F1: 7 8
    # 7 = normal
    def battle_8(self):
        return self.fleet_1.clear_boss()

_Originally posted by @Arcohyp in https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3296#issuecomment-1859425275_

**Comment by BZBY** [comment]
根据上面大佬的代码，（格式有点乱。。。）在AzurLaneAutoScript\campaign\campaign_main\里搞一个：
campaign_15_base.py
`from module.campaign.campaign_base import CampaignBase as CampaignBase_
from module.logger import logger


class Config:
    HOMO_EDGE_COLOR_RANGE = (0, 49)
    HOMO_EDGE_HOUGHLINES_THRESHOLD = 210

    # Disabled because having errors
    MAP_SWIPE_PREDICT_WITH_SEA_GRIDS = False
# Ambushes can be avoid by having more DDs.
    MAP_WALK_OPTIMIZE = False
# ===== Start of generated config =====
    MAP_HAS_SIREN = False
    MAP_HAS_MOVABLE_ENEMY = False
    MAP_HAS_MAP_STORY = False
    MAP_HAS_FLEET_STEP = False
    MAP_HAS_AMBUSH = True
    MAP_HAS_MYSTERY = True
# ===== End of generated config =====

class CampaignBase(CampaignBase_):
    ENEMY_FILTER = '1L > 1M > 1E > 1C > 2L > 2M > 2E > 2C > 3L > 3M > 3E > 3C'
    picked_light_house = []
    picked_flare = []

    def map_data_init(self, map_):
        super().map_data_init(map_)
        self.picked_light_house = []
        self.picked_flare = []

    def handle_mystery_items(self, button=None, drop=None):
        """
        Handle get flares, but not counted as mystery.
        """
        super().handle_mystery_items(button=button, drop=None)
        return False

    def pick_up_flare(self, grid):
        """
        Args:
            grid (GridInfo):

        Returns:
            bool: False
        """
        grid.is_flare = True
        if grid in self.picked_flare:
            logger.info(f'Flares {grid} already picked up')
        elif grid.is_accessible:
            logger.info(f'Pick up flares on {grid}')
            # get_items shows after flares picked up.
            self.goto(grid)
            self.picked_flare.append(grid)
        else:
            logger.info(f'Flares {grid} not accessible, will check in next battle')

        return False

    def pick_up_light_house(self, grid):
        """
        Args:
            grid (GridInfo):

        Returns:
            bool: False
        """
        if grid in self.picked_light_house:
            logger.info(f'Light house {grid} already picked up')
        elif grid.is_accessible:
            logger.info(f'Pick up light house on {grid}')
            self.goto(grid)
            self.picked_light_house.append(grid)
            self.ensure_no_info_bar()
        else:
            logger.info(f'Light house {grid} not accessible, will check in next battle')

        return False
`

**Comment by Arcohyp** [comment]
以上代码在执行的时候会出现无法拖动地图的情况。实测是15图支援舰队占据了可移动的区域。可以交给alas自动重启解决，只要不介意多烧点油。当然也可以加入什么移动前先点击缩小支援舰队那边的空间。

顺带一提，不加campaign_15_base.py也可以执行，把上面15-4里的那个import config注释掉，当时回答的时候没注意到md的格式。

驱逐的代码也尝试自己写了，只不过我这边感觉可以再优化。

在strategy.py
前面改一下：
          
          from module.template.assets import (TEMPLATE_FORMATION_1, TEMPLATE_FORMATION_2,
                                    TEMPLATE_FORMATION_3, TEMPLATE_EXPEL_SELECTED)
          from module.handler.assets import (EXPEL_CONFIRM, EXPEL_CANCEL, EXPEL_ENTER)
其中selected，是敌方舰队被选中驱逐的那个图案，expel这些都是按钮自己截图吧。记得运行一下button_extract.py
![EXPEL_CANCEL](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/36880700/193337e0-e926-4bfc-a88c-a747f425704b)
![EXPEL_ENTER](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/36880700/c17ea02e-f1f0-43a3-b70d-02db17709df6)
![EXPEL_CONFIRM](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/36880700/efe4f9a5-ee19-442a-b5ce-2778375de9e3)
![TEMPLATE_EXPEL_SELECTED](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/36880700/378f05ac-4b7c-4dcd-9bb9-5e67998183d5)


后面加入：

          def is_selected_in_expel(self, image):
                  return TEMPLATE_EXPEL_SELECTED.match(image)
      
          def is_in_strategy_expel_target(self):
              return self.appear(EXPEL_CANCEL, offset=(20, 20))
      
          def strategy_expel_enter(self):
              """
              Pages:
                  in: STRATEGY_OPENED, EXPEL_ENTER
                  out: EXPEL_CANCEL
              """
              logger.info('Expel enter')
              while 1:
                  if self.appear(EXPEL_ENTER, offset=120, interval=5):
                      self.device.click(EXPEL_ENTER)
      
                  if self.appear(EXPEL_CANCEL, offset=(20, 20)):
                      break
      
                  self.device.screenshot()
      
          def strategy_expel_cancel(self):
              """
              Pages:
                  in: EXPEL_CANCEL
                  out: STRATEGY_OPENED
              """
              logger.info('Expel cancel')
              while 1:
                  if self.appear(EXPEL_CANCEL, offset=(20, 20), interval=5):
                      self.device.click(EXPEL_CANCEL)
      
                  if self.appear(STRATEGY_OPENED, offset=120):
                      break
      
                  self.device.screenshot()
      
          def strategy_expel_confirm(self):
              """
              Pages:
                  in: STRATEGY_OPENED, EXPEL_CANCEL
                  out: EXPEL_CONFIRM
              """
              logger.info('Expel confirm')
              while 1:
                  if self.appear(EXPEL_CONFIRM, offset=(20, 20), interval=5):
                      self.device.click(EXPEL_CONFIRM)
      
                  if self.appear(STRATEGY_OPENED, offset=120):
                      break
                  self.device.screenshot()

fleet.py后加入，这块可以优化，我没怎么学过python，突击搞的这个：

     def _expel_target(self, location_1, location_2):
        """
        Expel enemy from location_1 to location2

        Args:
            location_1 (tuple, str, GridInfo): Departure.
            location_2 (tuple, str, GridInfo): Destination.

        Returns:
            bool: If enemy moved.

        Pages:
            in: IN_EXPEL
            out: IN_MAP
        """
        departure = location_ensure(location_1)
        destination = location_ensure(location_2)
        expel = False
        while 1:
            # Focus to target
            self.in_sight(departure, sight=self._walk_sight)
            self.focus_to_grid_center()
            grid_1 = self.convert_global_to_local(departure)
            grid_1.__str__ = departure

            self.device.click(grid_1)
            selected = False

            # Usually no need to wait
            arrive_timer = Timer(0.1, count=0)
            # If nothing happens, click again.
            walk_timeout = Timer(2, count=6).start()

            while 1:
                self.device.screenshot()
                self.view.update(image=self.device.image)
                selected = self.is_selected_in_expel(self.device.image)
                grid_2 = self.convert_global_to_local(destination)
                grid_2.__str__ = destination

                if selected:
                    self.device.click(grid_2)
                    expel = True
                    logger.info(f'Enemy has been expelled '
                                f'from {location2node(departure)} to {location2node(destination)} .')
                    return expel
                    # break
                # set a time-counter to record

    def expel_target(self, location_1, location_2):
        """
        Open strategy, expel enemy from location_1 to location2, close strategy.

        Args:
            location_1 (tuple, str, GridInfo): Departure.
            location_2(tuple, str, GridInfo): Destination.

        Returns:
            bool: If enemy moved

        Pages:
            in: IN_MAP
            out: IN_MAP
        """
        self.strategy_open()
        self.strategy_expel_enter()
        if self._expel_target(location_1, location_2):
            self.strategy_expel_confirm()
            result = True
        else:
            self.strategy_expel_cancel()
            result = False
        # Hunt zone view re-enabled by game, after entering sub move mode
        # self.strategy_set_execute(sub_view=False)
        self.strategy_close()
        return result

camera.py 修改_update函数，加入这个self.is_in_strategy_expel_target()：

        try:
              if not self.is_in_map() \
                      and not self.is_in_strategy_submarine_move() \
                      and not self.is_in_strategy_expel_target():
                  logger.warning('Image to detect is not in_map')
                  raise MapDetectionError('Image to detect is not in_map')
              self.view.load(self.device.image)

最后的15_4里的战斗逻辑改成这个就行了:

    """
    Using F1 to battle with 1st and 3rd boss
    Using F2 to battle with 2nd boss
    The whole battle process is:
        F1: 0 1 2 3(1st boss) 4 5 7 8(3rd boss) 
        F2: 6(2nd boss)
    """

    def battle_0(self):
        self.expel_target(J8, I8)
        self.clear_chosen_enemy(K9)
        return self.battle_default()

    def battle_1(self):
        self.clear_chosen_enemy(A1)
        return self.battle_default()

    def battle_3(self):
        self.pick_up_ammo(D5)
        self.clear_chosen_enemy(H5)

        return self.battle_default()

    # F1: 4 5
    # 4,5 = normal

    # F2: 6
    def battle_6(self):
        # switch to fleet 2
        self.fleet_boss.clear_chosen_enemy(D3)
        # switch to fleet 1
        return self.battle_default()

    # F1: 7 8
    # 7 = normal
    def battle_8(self):
        return self.clear_boss()

因为在写出暴力刷图代码后直接打捞成功（感谢），后续这些代码简单测试了一下就没多改了。仅供参考：）

**Comment by zhulinyv** [comment]
@Arcohyp 谢谢大佬，已经在用啦！中间出了一点小问题：为了图方便，我直接从楼上把 EXPEL_ENTER 这张图片本另存到了 `AzurLaneAutoScript/assets/cn/handler` 目录，但按钮位置和我的不一样导致 Alas 不能正确点击，需要自己截图。

**Comment by Arcohyp** [comment]
> @Arcohyp 谢谢大佬，已经在用啦！中间出了一点小问题：为了图方便，我直接从楼上把 EXPEL_ENTER 这张图片本另存到了 `AzurLaneAutoScript/assets/cn/handler` 目录，但按钮位置和我的不一样导致 Alas 不能正确点击，需要自己截图。 ![EXPEL_ENTER](https://private-user-images.githubusercontent.com/66541860/295132657-1e24ed3c-7152-4243-b09a-0acffd21ac45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDc0MjgsIm5iZiI6MTcwNDg0NzEyOCwicGF0aCI6Ii82NjU0MTg2MC8yOTUxMzI2NTctMWUyNGVkM2MtNzE1Mi00MjQzLWIwOWEtMGFjZmZkMjFhYzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDAwMzg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjFiNzQyODg1ZDFlZWMwNzRlNzRhMWUxMTVkNTBjMDNiNDJkZmIxMTE5NDY1ZWM0M2U1MDc5ZmJiZmI3YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2A1K9PYpGIpaoxKHfgEb0WMek9FGcQYVE7ERKcAbjfk)

谢谢提醒，用这个图更好。我当时使用的是省油带导驱时代的队伍所以位置有偏移：）

可以在这里设置EXPEL_ENTER的offset，具体可以参考appear这个函数，不过考虑到之前项目就没实现导驱打击，可以默认不用动了。

          def strategy_expel_enter(self):
                    """
                    Pages:
                        in: STRATEGY_OPENED, EXPEL_ENTER
                        out: EXPEL_CANCEL
                    """
                    logger.info('Expel enter')
                    while 1:
                        # Here you can modify the offset to suit the missile strike icon appear.
                        if self.appear(EXPEL_ENTER, offset=120, interval=5):
                            self.device.click(EXPEL_ENTER)
            
                        if self.appear(EXPEL_CANCEL, offset=(20, 20)):
                            break
            
                        self.device.screenshot()
