### ISSUE TITLE
我想自定义演习的出击时间，请告诉我在代码的哪里可以修改

### ISSUE THREAD

**Issue by sgszx** [LmeSzinc/AzurLaneAutoScript#3428]
### 你的功能请求是否与问题有关？

我已经尝试了修改template.json里的Exercise字段参数，exercise.py中的get_server_updata的调用缺省，但是都不成功。

**Comment by LmeSzinc** [comment]
XY问题，说出你的原始需求

**Comment by sgszx** [comment]
> XY问题，说出你的原始需求

我希望调整演习的默认更新出击时间，卡在刷新前赚分，比如11:00,17:00,23:00。
通过搜索我发现该需求不足以支持一项功能更新，因此我希望自行修改本地python文件以实现功能。

**Comment by 947917148aoa** [comment]
AzurLaneAutoScript\module\config\argument\args.json
7380行 修改为 "display": "display"
按ctrl+shift+r刷新

**Comment by sgszx** [comment]
> AzurLaneAutoScript\module\config\argument\args.json 7380行 修改为 "display": "display" 按ctrl+shift+r刷新

牛的，原来有这个隐藏功能啊

**Comment by 947917148aoa** [comment]
AzurLaneAutoScript\deploy\git.py
95行 修改为if self.AutoUpdate:
禁止启动alas更新，保证修改不会被恢复
副作用未知
