### ISSUE TITLE
应该是设置上的问题但我对次问题完全没有头绪

### ISSUE THREAD

**Issue by zzlsjdy** [LmeSzinc/AzurLaneAutoScript#3436]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动ALAS时有时候会卡在这个地方不动，过一定时间后有可能启动成功，有时候会继续卡住

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

找到该问题的原因，并尽可能改变程序的启动方式

### 截图

![屏幕截图 2024-01-17 223840](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140072623/5c90dbfc-ca5e-4f62-bb5e-c60c4f3c5b28)

**Comment by zzlsjdy** [comment]
"C:\Users\ASUS\Downloads\AlasApp_0.4.3_fullcn\AzurLaneAutoScript
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
./toolkit/Lib/site-packages/adbutils/mixin.py apkutils2 no need to patch
==================== SHOW DEPLOY CONFIG ====================
Language: zh-CN
Theme: dark
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/.git/
[ success ]
==================== SET GIT PROXY ====================
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify true
[ success ]
==================== SET GIT REPOSITORY ====================
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://github.com/LmeSzinc/AzurLaneAutoScript
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
fatal: unable to access 'https://github.com/LmeSzinc/AzurLaneAutoScript/': Failed to connect to github.com port 443: Timed out
[ failure ], error_code: 128
+-----------------------------------------------------+
|                    UPDATE FAILED                    |
+-----------------------------------------------------+
==================== SHOW DEPLOY CONFIG ====================
Language: zh-CN
Theme: dark
Rest of the configs are the same as default

Last command: "C:/Users/ASUS/Downloads/AlasApp_0.4.3_fullcn/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
Please check your deploy settings in config/deploy.yaml and re-open Alas.exe
Take the screenshot of entire window if you need help

**Comment by zzlsjdy** [comment]
删除所以文件后在下载并调试和正常了，希望不会再出现了

**Comment by LmeSzinc** [comment]
国内用户乖乖用国内源，不要自作聪明乱改
