### ISSUE TITLE
希望更新15图的周回模式

### ISSUE THREAD

**Issue by zxz1994** [LmeSzinc/AzurLaneAutoScript#3440]

**Comment by lzy0702** [comment]
附议，那些奇怪的机制在周回模式下都不存在了，只要道中能捡弹药就行了

**Comment by lzy0702** [comment]
由于战术侦察的debuff没了，可以把15-4的3个boss战全交给boss队，或者干脆就道中队一直打，直到弹药耗尽再切另一队

**Comment by AirParty** [comment]
实测,15-4绿海用官方自律,1队道中,2队boss.可以全s胜打完了.

**Comment by tuman-qahraman** [comment]
+1，让脚本能点击官方自律就行

**Comment by shimw6828** [comment]
有个非常简单的办法，在`D:\AzurLaneAutoScript\campaign\campaign_main`文件夹下（我的软件是放在了D盘），随便copy一个地图，并改名为`campaign_15_1.py`，这样就不会报没有地图文件的错误了。而由于开启的是自律模式，地图文件的信息其实不会被调用，开始战斗后会直接进入自律，所以根本不会报错。
另外，我顺便在文件里面改了`MAP = CampaignMap('15-1')`，但我觉得这个应该不起任何作用。

**Comment by zxz1994** [comment]
> 有个非常简单的办法，在`D:\AzurLaneAutoScript\campaign\campaign_main`文件夹下（我的软件是放在了D盘），随便copy一个地图，并改名为`campaign_15_1.py`，这样就不会报没有地图文件的错误了。而由于开启的是自律模式，地图文件的信息其实不会被调用，开始战斗后会直接进入自律，所以根本不会报错。 另外，我顺便在文件里面改了`MAP = CampaignMap('15-1')`，但我觉得这个应该不起任何作用。

有用，但有个问题，15图多了个支援舰队。导致编队界面有点错位。会选择重新选择第二编队，职能会自动变成一队全清，之后也会识别错误无法自动修改。而现在一队全清只能b胜，很影响收益

**Comment by shimw6828** [comment]
已收到！非常感谢您的支持

**Comment by shimw6828** [comment]
> > 有个非常简单的办法，在`D:\AzurLaneAutoScript\campaign\campaign_main`文件夹下（我的软件是放在了D盘），随便copy一个地图，并改名为`campaign_15_1.py`，这样就不会报没有地图文件的错误了。而由于开启的是自律模式，地图文件的信息其实不会被调用，开始战斗后会直接进入自律，所以根本不会报错。 另外，我顺便在文件里面改了`MAP = CampaignMap('15-1')`，但我觉得这个应该不起任何作用。
> 
> 有用，但有个问题，15图多了个支援舰队。导致编队界面有点错位。会选择重新选择第二编队，职能会自动变成一队全清，之后也会识别错误无法自动修改。而现在一队全清只能b胜，很影响收益

这个问题可以用一个非常愚蠢的办法来解决。我个人觉得选择编队这一步在这里比较多余，只有少量的场景会用上，所以我们只要把编队选择的步骤去掉，这样就可以直接进图自律了。只要自己把队伍设置提前调好，之后就不会变了。下面是修改方法：
首先需要改一下这个文件`D:\AzurLaneAutoScript\config\deploy.yaml`的第30行修改为`KeepLocalChanges: true`，保证本地的修改可以生效。然后将`D:\AzurLaneAutoScript\module\map\map_operation.py`中175行和177行用#注释掉，`# self.fleet_preparation()`和`# self.handle_auto_search_setting()`。这样就可以在不影响其他功能的前提下自律了。当然，这肯定是不长久的，我也不知道会出啥子bug

**Comment by KitaharaHaru** [comment]
> > > 有个非常简单的办法，在`D:\AzurLaneAutoScript\campaign\campaign_main`文件夹下（我的软件是放在了D盘），随便copy一个地图，并改名为`campaign_15_1.py`，这样就不会报没有地图文件的错误了。而由于开启的是自律模式，地图文件的信息其实不会被调用，开始战斗后会直接进入自律，所以根本不会报错。 另外，我顺便在文件里面改了`MAP = CampaignMap('15-1')`，但我觉得这个应该不起任何作用。
> > 
> > 
> > 有用，但有个问题，15图多了个支援舰队。导致编队界面有点错位。会选择重新选择第二编队，职能会自动变成一队全清，之后也会识别错误无法自动修改。而现在一队全清只能b胜，很影响收益
> 
> 这个问题可以用一个非常愚蠢的办法来解决。我个人觉得选择编队这一步在这里比较多余，只有少量的场景会用上，所以我们只要把编队选择的步骤去掉，这样就可以直接进图自律了。只要自己把队伍设置提前调好，之后就不会变了。下面是修改方法： 首先需要改一下这个文件`D:\AzurLaneAutoScript\config\deploy.yaml`的第30行修改为`KeepLocalChanges: true`，保证本地的修改可以生效。然后将`D:\AzurLaneAutoScript\module\map\map_operation.py`中175行和177行用#注释掉，`# self.fleet_preparation()`和`# self.handle_auto_search_setting()`。这样就可以在不影响其他功能的前提下自律了。当然，这肯定是不长久的，我也不知道会出啥子bug

按键的位置信息在AzurLaneAutoScript\module\handler\assets.py里，但位置信息是由dev_tools/button_extract.py自动生成的，应该需要搭建起整个项目再进行修改。
在看使用手册了，但不确定能不能看得懂。没有alas接管倒油有点头疼

**Comment by shimw6828** [comment]
> > > > 有个非常简单的办法，在`D:\AzurLaneAutoScript\campaign\campaign_main`文件夹下（我的软件是放在了D盘），随便copy一个地图，并改名为`campaign_15_1.py`，这样就不会报没有地图文件的错误了。而由于开启的是自律模式，地图文件的信息其实不会被调用，开始战斗后会直接进入自律，所以根本不会报错。 另外，我顺便在文件里面改了`MAP = CampaignMap('15-1')`，但我觉得这个应该不起任何作用。
> > > 
> > > 
> > > 有用，但有个问题，15图多了个支援舰队。导致编队界面有点错位。会选择重新选择第二编队，职能会自动变成一队全清，之后也会识别错误无法自动修改。而现在一队全清只能b胜，很影响收益
> > 
> > 
> > 这个问题可以用一个非常愚蠢的办法来解决。我个人觉得选择编队这一步在这里比较多余，只有少量的场景会用上，所以我们只要把编队选择的步骤去掉，这样就可以直接进图自律了。只要自己把队伍设置提前调好，之后就不会变了。下面是修改方法： 首先需要改一下这个文件`D:\AzurLaneAutoScript\config\deploy.yaml`的第30行修改为`KeepLocalChanges: true`，保证本地的修改可以生效。然后将`D:\AzurLaneAutoScript\module\map\map_operation.py`中175行和177行用#注释掉，`# self.fleet_preparation()`和`# self.handle_auto_search_setting()`。这样就可以在不影响其他功能的前提下自律了。当然，这肯定是不长久的，我也不知道会出啥子bug
> 
> 按键的位置信息在AzurLaneAutoScript\module\handler\assets.py里，但位置信息是由dev_tools/button_extract.py自动生成的，应该需要搭建起整个项目再进行修改。 在看使用手册了，但不确定能不能看得懂。没有alas接管倒油有点头疼

选择队伍的按键信息其实是AzurLaneAutoScript\module\map\assets.py。队伍选择的操作是在AzurLaneAutoScript\module\map\map_fleet_preparation.py的第334行，fleet_1.ensure_to_be(self.config.Fleet_Fleet1)选择第一队。这种写死的位置想要使用，只能对十五图的情况进行判断，把十五图的按键位置和操作独立出来，可以写个if弄一下。

**Comment by LmeSzinc** [comment]
#3563

**Comment by shimw6828** [comment]
已收到！非常感谢您的支持
