### ISSUE TITLE
领取任务奖励时无法处理剧情任务弹窗

### ISSUE THREAD

**Issue by W1NDes** [LmeSzinc/AzurLaneAutoScript#3442]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

领取任务奖励时无法处理剧情任务弹窗，影响挂机，感觉可以通过检测“获取新任务”来解决

### 如何复现

1. 做完一个角色剧情任务
2. 让alas运行领取奖励

### 截图

![图片](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/c7f111dd-3813-4601-a8fa-2048bbf37057)

**Comment by LmeSzinc** [comment]
#3530
