### ISSUE TITLE
大舰队相关，开启补给处会卡住

### ISSUE THREAD

**Issue by adfnkjasd** [LmeSzinc/AzurLaneAutoScript#3452]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [x] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![QQ截图20240127144425](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39746646/97fc170c-f9cb-490a-918a-91284013b728)
![QQ截图20240127144402](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39746646/1358af7f-d6b6-46d2-8061-01645c1a2226)
![QQ截图20240127144421](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/39746646/660766a0-6f97-47e6-86bc-662d986ff4b2)
如图所示，在是大司令官的情况下，大舰队筹备的右下角是购买补给，开启alas中的“收取大舰队补给”的时候会点击右下，但如果舰队币不足的话就会弹出舰队币不足的窗口，alas就会卡在这，不停重启设置。

**Comment by adfnkjasd** [comment]
希望能增加一个14天舰队支援礼包是否购买的开关，老咸鱼了，一个人建的大舰队肝到7级了，现在也只有一个人，图的就是科研的那仓库和船坞位子，不想再换了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2265#issuecomment-1438804942

**Comment by lzy0702** [comment]
就增加一项跳过这个功能的选项即可，单独开舰队的也不差这点舰队币

**Comment by adfnkjasd** [comment]
> [#2265 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2265#issuecomment-1438804942)

不缺这些舰队币，换什么活跃舰队不现实，都用脚本了肯定是老咸鱼，换去活跃舰队累够呛，就只要求增加一个够不够买的开关罢了

**Comment by adfnkjasd** [comment]
> > > [#2265 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2265#issuecomment-1438804942)
> > 
> > 
> > 不缺这些舰队币，换什么活跃舰队不现实，都用脚本了肯定是老咸鱼，换去活跃舰队累够呛，就只要求增加一个够不够买的开关罢了
> 
> 活跃舰队的舰队活动也可以用脚本啊，有啥累够呛的。

现在的活跃舰队都很多要求，日贡多少多少，工作性质脚本也不是天天都开 而且也舍不得自己肝出来的舰队等级
