### ISSUE TITLE
大舰队购买补给添加判断条件

### ISSUE THREAD

**Issue by adfnkjasd** [LmeSzinc/AzurLaneAutoScript#3454]
### 你的功能请求是否与问题有关？

勾选alas大舰队补给功能后，如果职位是司令官或副司令，在购买补给时如果资金不够会卡住，请求增加判断条件，小于3000则跳过购买，执行下一个任务。

### 解决方案

ocr识别大舰队资金，小于3000则跳过购买补给，进行下一项任务

**Comment by LmeSzinc** [comment]
#3452
