### ISSUE TITLE
随机（我没发现什么触发条件）出现too many clicks错误然后alas停止运行

### ISSUE THREAD

**Issue by fhouia** [LmeSzinc/AzurLaneAutoScript#3455]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

alas运行时会有几率出现不断重复click指令，但是无事发生的情况，通常是page_main。多次触发后会自动执行restart，之后在登陆界面重复login_check，最后alas报错停止运行。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
──────────────────────────────────── SHOP BUY ─────────────────────────────────────
INFO     18:03:17.469 │ SHOP BUY                                                   
INFO     18:03:17.470 │ Loading template folder: ./assets/shop/general             
INFO     18:03:17.871 │ [next_template_index] 76                                   
INFO     18:03:18.126 │ [Price_ocr 0.169s] [5000, 2000, 400, 750, 10000, 72, 1200, 
         24, 25000, 2000]                                                          
INFO     18:03:18.129 │ [Item detected] 10                                         
INFO     18:03:18.594 │ [Price_ocr 0.167s] [5000, 2000, 400, 750, 10000, 72, 1200, 
         24, 25000, 2000]                                                          
INFO     18:03:18.597 │ [Item detected] 10                                         
INFO     18:03:18.598 │ Shop row 1: ['BoxT4_x1_Coins_x5000',                       
         'BoxT3_x1_Coins_x2000', 'BoxT2_x1_Coins_x400',                            
         'PlatePlaneT1_x1_Coins_x750', 'BoxT3_x1_Coins_x10000']                    
INFO     18:03:18.600 │ Shop row 2: ['BookRedT3_x1_Gems_x72',                      
         'BookYellowT2_x1_Coins_x1200', 'Cube_x1_Gems_x24',                        
         'BoxT4_x1_Coins_x25000', 'BoxT3_x1_Coins_x2000']                          
INFO     18:03:18.630 │ [SHOP_GOLD_COINS 0.029s] 527693                            
INFO     18:03:18.659 │ [SHOP_GEMS 0.028s] 980                                     
INFO     18:03:18.660 │ Gold coins: 527693, Gems: 980                              
INFO     18:03:18.661 │ Shop buy finished                                          
INFO     18:03:18.663 │ Delay task `ShopFrequent` to 2024-01-30 00:00:00           
         (server_update='00:00, 12:00, 18:00')                                     
INFO     18:03:18.677 │ Bind task ['General', 'Alas', 'ShopFrequent']              
INFO     18:03:18.679 │ Save config ./config\alas.json,                            
         ShopFrequent.Scheduler.NextRun=datetime.datetime(2024, 1, 30, 0, 0)       
INFO     18:03:18.695 │ Scheduler: End task `ShopFrequent`                         
INFO     18:03:18.697 │ [Server] cn                                                
INFO     18:03:18.718 │ Bind task ['General', 'Alas']                              
INFO     18:03:18.721 │ No task pending                                            
INFO     18:03:18.723 │ [Task] Research (Enable, 2024-01-29 18:57:38)              
INFO     18:03:18.724 │ Bind task ['General', 'Alas', 'Research']                  
INFO     18:03:18.733 │ Wait until 2024-01-29 18:57:38 for task `Research`         
INFO     18:03:18.734 │ Goto main page during wait                                 
INFO     18:03:19.057 │ [Package_name] com.bilibili.azurlane                       
INFO     18:03:19.058 │ App is already running, goto main page                     
INFO     18:03:19.059 │ <<< UI ENSURE >>>                                          
INFO     18:03:19.060 │ UI get current page                                        
INFO     18:03:19.082 │ [UI] page_munitions                                        
INFO     18:03:19.084 │ Goto page_main                                             
INFO     18:03:19.085 │ <<< UI GOTO PAGE_MAIN >>>                                  
INFO     18:03:19.108 │ Page switch: page_munitions -> page_main                   
INFO     18:03:19.109 │ Click (1238,   33) @ GOTO_MAIN                             
INFO     18:03:19.860 │ Page arrive: page_main                                     
INFO     18:57:40.320 │ Scheduler: Start task `Research`                           
═══════════════════════════════════════════════════════════════════════════════════
                                     RESEARCH                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     18:57:40.867 │ <<< UI ENSURE >>>                                          
INFO     18:57:40.870 │ UI get current page                                        
INFO     18:57:40.885 │ [UI] page_main                                             
INFO     18:57:40.887 │ Goto page_research                                         
INFO     18:57:40.890 │ <<< UI GOTO PAGE_RESEARCH >>>                              
INFO     18:57:40.902 │ Page switch: page_main -> page_reshmenu                    
INFO     18:57:40.905 │ Click ( 715,  696) @ MAIN_GOTO_RESHMENU                    
INFO     18:57:46.331 │ Page switch: page_main -> page_reshmenu                    
INFO     18:57:46.333 │ Click ( 691,  689) @ MAIN_GOTO_RESHMENU                    
INFO     18:57:51.551 │ Page switch: page_main -> page_reshmenu                    
INFO     18:57:51.552 │ Click ( 696,  684) @ MAIN_GOTO_RESHMENU                    
INFO     18:57:56.624 │ Page switch: page_main -> page_reshmenu                    
INFO     18:57:56.626 │ Click ( 732,  684) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:01.659 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:01.661 │ Click ( 739,  682) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:06.762 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:06.768 │ Click ( 751,  696) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:11.912 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:11.914 │ Click ( 701,  701) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:17.045 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:17.047 │ Click ( 749,  690) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:22.097 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:22.099 │ Click ( 667,  696) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:27.162 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:27.164 │ Click ( 716,  690) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:32.226 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:32.228 │ Click ( 699,  692) @ MAIN_GOTO_RESHMENU                    
INFO     18:58:37.465 │ Page switch: page_main -> page_reshmenu                    
INFO     18:58:37.542 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L185 research()                                        
                research.py L564 run()                                             
                      ui.py L250 ui_ensure()                                       
                      ui.py L220 ui_goto()                                         
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  18:58:37.550 │ Too many click for a button: MAIN_GOTO_RESHMENU            
WARNING  18:58:37.552 │ History click: ['MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU',
         'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU',         
         'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU',         
         'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU', 'MAIN_GOTO_RESHMENU',         
         'MAIN_GOTO_RESHMENU']                                                     
ERROR    18:58:37.555 │ GameTooManyClickError: Too many click for a button:        
         MAIN_GOTO_RESHMENU                                                        
WARNING  18:58:37.562 │ Saving error: ./log/error/1706525917562                    
WARNING  18:58:37.920 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  18:58:37.921 │ If you are playing by hand, please stop Alas               
INFO     18:58:37.923 │ Task call: Restart                                         
INFO     18:58:37.955 │ Bind task ['General', 'Alas', 'Research']                  
INFO     18:58:37.957 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2024, 1, 29, 18, 58, 37),     
         Restart.Scheduler.Enable=True                                             
INFO     18:58:47.969 │ Scheduler: End task `Research`                             
INFO     18:58:48.126 │ Server "水星行动" is available.                            
INFO     18:58:48.129 │ [Server] cn                                                
INFO     18:58:48.160 │ Bind task ['General', 'Alas']                              
INFO     18:58:48.164 │ Pending tasks: ['Restart', 'Research']                     
INFO     18:58:48.165 │ [Task] Restart (Enable, 2024-01-29 18:58:37)               
INFO     18:58:48.166 │ Bind task ['General', 'Alas', 'Restart']                   
INFO     18:58:48.182 │ Scheduler: Start task `Restart`                            
═══════════════════════════════════════════════════════════════════════════════════
                                      RESTART                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     18:58:48.575 │ <<< APP RESTART >>>                                        
INFO     18:58:48.576 │ App stop: com.bilibili.azurlane                            
INFO     18:58:48.657 │ App start: com.bilibili.azurlane                           
INFO     18:58:48.926 │ <<< APP LOGIN >>>                                          
INFO     18:58:48.986 │ [Device Orientation] 0 (Normal)                            
INFO     18:58:54.035 │ [Device Orientation] 0 (Normal)                            
INFO     18:58:59.177 │ [Device Orientation] 0 (Normal)                            
INFO     18:59:04.231 │ [Device Orientation] 0 (Normal)                            
INFO     18:59:09.260 │ [Device Orientation] 0 (Normal)                            
INFO     18:59:13.465 │ Click ( 504,  357) @ LOGIN_CHECK                           
INFO     18:59:13.517 │ Login success                                              
INFO     18:59:18.488 │ Click ( 461,  365) @ LOGIN_CHECK                           
INFO     18:59:23.550 │ Click ( 459,  318) @ LOGIN_CHECK                           
INFO     18:59:28.605 │ Click ( 493,  336) @ LOGIN_CHECK                           
INFO     18:59:33.731 │ Click ( 489,  351) @ LOGIN_CHECK                           
INFO     18:59:38.895 │ Click ( 477,  351) @ LOGIN_CHECK                           
INFO     18:59:44.021 │ Click ( 513,  327) @ LOGIN_CHECK                           
INFO     18:59:49.247 │ Click ( 462,  342) @ LOGIN_CHECK                           
INFO     18:59:54.444 │ Click ( 469,  340) @ LOGIN_CHECK                           
INFO     18:59:59.627 │ Click ( 499,  334) @ LOGIN_CHECK                           
INFO     19:00:04.804 │ Click ( 450,  336) @ LOGIN_CHECK                           
INFO     19:00:09.834 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  19:00:09.838 │ Too many click for a button: LOGIN_CHECK                   
WARNING  19:00:09.840 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  19:00:09.842 │ Too many click for a button: LOGIN_CHECK                   
INFO     19:00:09.843 │ App stop: com.bilibili.azurlane                            
INFO     19:00:09.909 │ App start: com.bilibili.azurlane                           
INFO     19:00:10.132 │ <<< APP LOGIN >>>                                          
INFO     19:00:10.192 │ [Device Orientation] 0 (Normal)                            
INFO     19:00:15.239 │ [Device Orientation] 0 (Normal)                            
INFO     19:00:20.328 │ [Device Orientation] 0 (Normal)                            
INFO     19:00:25.588 │ [Device Orientation] 0 (Normal)                            
INFO     19:00:30.678 │ [Device Orientation] 0 (Normal)                            
INFO     19:00:32.061 │ Click ( 504,  341) @ LOGIN_CHECK                           
INFO     19:00:32.116 │ Login success                                              
INFO     19:00:42.971 │ Click ( 456,  332) @ LOGIN_CHECK                           
INFO     19:00:48.245 │ Click ( 487,  367) @ LOGIN_CHECK                           
INFO     19:00:53.548 │ Click ( 482,  352) @ LOGIN_CHECK                           
INFO     19:00:58.632 │ Click ( 479,  335) @ LOGIN_CHECK                           
INFO     19:01:03.851 │ Click ( 447,  315) @ LOGIN_CHECK                           
INFO     19:01:09.142 │ Click ( 512,  355) @ LOGIN_CHECK                           
INFO     19:01:14.338 │ Click ( 446,  360) @ LOGIN_CHECK                           
INFO     19:01:19.594 │ Click ( 450,  333) @ LOGIN_CHECK                           
INFO     19:01:24.843 │ Click ( 489,  365) @ LOGIN_CHECK                           
INFO     19:01:30.193 │ Click ( 470,  338) @ LOGIN_CHECK                           
INFO     19:01:35.255 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  19:01:35.258 │ Too many click for a button: LOGIN_CHECK                   
WARNING  19:01:35.259 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  19:01:35.261 │ Too many click for a button: LOGIN_CHECK                   
INFO     19:01:35.262 │ App stop: com.bilibili.azurlane                            
INFO     19:01:35.324 │ App start: com.bilibili.azurlane                           
INFO     19:01:35.523 │ <<< APP LOGIN >>>                                          
INFO     19:01:35.578 │ [Device Orientation] 0 (Normal)                            
INFO     19:01:40.741 │ [Device Orientation] 0 (Normal)                            
INFO     19:01:46.018 │ [Device Orientation] 0 (Normal)                            
INFO     19:01:51.239 │ [Device Orientation] 0 (Normal)                            
INFO     19:01:56.484 │ [Device Orientation] 0 (Normal)                            
INFO     19:02:01.751 │ [Device Orientation] 0 (Normal)                            
INFO     19:02:04.551 │ Click ( 499,  341) @ LOGIN_CHECK                           
INFO     19:02:04.602 │ Login success                                              
INFO     19:02:09.765 │ Click ( 481,  318) @ LOGIN_CHECK                           
INFO     19:02:14.987 │ Click ( 447,  337) @ LOGIN_CHECK                           
INFO     19:02:20.248 │ Click ( 461,  338) @ LOGIN_CHECK                           
INFO     19:02:25.511 │ Click ( 469,  342) @ LOGIN_CHECK                           
INFO     19:02:30.796 │ Click ( 502,  369) @ LOGIN_CHECK                           
INFO     19:02:36.059 │ Click ( 467,  331) @ LOGIN_CHECK                           
INFO     19:02:41.349 │ Click ( 452,  329) @ LOGIN_CHECK                           
INFO     19:02:46.630 │ Click ( 461,  316) @ LOGIN_CHECK                           
INFO     19:02:51.645 │ Click ( 495,  332) @ LOGIN_CHECK                           
INFO     19:02:56.933 │ Click ( 451,  377) @ LOGIN_CHECK                           
INFO     19:03:01.944 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  19:03:01.947 │ Too many click for a button: LOGIN_CHECK                   
WARNING  19:03:01.949 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  19:03:01.951 │ Too many click for a button: LOGIN_CHECK                   
INFO     19:03:01.952 │ App stop: com.bilibili.azurlane                            
INFO     19:03:02.032 │ App start: com.bilibili.azurlane                           
CRITICAL 19:03:02.269 │ Login failed more than 3                                   
CRITICAL 19:03:02.271 │ Azur Lane server may be under maintenance, or you may lost 
         network connection                                                        
CRITICAL 19:03:02.273 │ Request human takeover                                     
INFO     19:03:02.275 │ No provider specified, skip sending
```

### 还有别的吗？

模拟器为雷电9，alas一直为最新版本，出现此bug后点击启动会直接报错停止运行，此时只能重启模拟器，然后alas不用重启也能正常运行。非常神奇的是，之前用蓝叠hyper5模拟器时未曾出现过此bug。

**Comment by fhouia** [comment]
此外，以下是上次错误时我复制下来的log：



═══════════════════════════════════════════════════════════════════════════════════
                                       MAIN                                        
═══════════════════════════════════════════════════════════════════════════════════
══════════════════════════════════ CAMPAIGN_12_4 ══════════════════════════════════
INFO     20:12:01.350 │ CAMPAIGN_12_4                                              
INFO     20:12:01.351 │ Count: 0                                                   
INFO     20:12:01.363 │ <<< UI ENSURE >>>                                          
INFO     20:12:01.364 │ UI get current page                                        
INFO     20:12:01.373 │ [UI] page_main                                             
INFO     20:12:01.376 │ Goto page_campaign                                         
INFO     20:12:01.378 │ <<< UI GOTO PAGE_CAMPAIGN >>>                              
INFO     20:12:01.390 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:01.392 │ Click (1083,  371) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:06.468 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:06.470 │ Click (1087,  348) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:11.592 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:11.593 │ Click (1100,  352) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:16.705 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:16.707 │ Click (1090,  363) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:21.827 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:21.828 │ Click (1080,  366) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:26.941 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:26.943 │ Click (1101,  365) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:32.066 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:32.068 │ Click (1095,  374) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:37.192 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:37.194 │ Click (1108,  361) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:42.329 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:42.331 │ Click (1040,  360) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:47.441 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:47.442 │ Click (1055,  328) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:52.561 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:52.563 │ Click (1081,  365) @ MAIN_GOTO_CAMPAIGN                    
INFO     20:12:57.670 │ Page switch: page_main -> page_campaign_menu               
INFO     20:12:57.704 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L343 main()                                            
                     run.py L360 run()                                             
             campaign_ui.py L176 ensure_campaign_ui()                              
             campaign_ui.py L164 campaign_set_chapter()                            
             campaign_ui.py L121 campaign_set_chapter_main()                       
                      ui.py L257 ui_goto_campaign()                                
                      ui.py L250 ui_ensure()                                       
                      ui.py L220 ui_goto()                                         
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  20:12:57.710 │ Too many click for a button: MAIN_GOTO_CAMPAIGN            
WARNING  20:12:57.712 │ History click: ['MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN',
         'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN',         
         'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN',         
         'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN', 'MAIN_GOTO_CAMPAIGN',         
         'MAIN_GOTO_CAMPAIGN']                                                     
ERROR    20:12:57.714 │ GameTooManyClickError: Too many click for a button:        
         MAIN_GOTO_CAMPAIGN                                                        
WARNING  20:12:57.716 │ Saving error: ./log/error/1705925577716                    
WARNING  20:12:57.998 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  20:12:58.000 │ If you are playing by hand, please stop Alas               
INFO     20:12:58.001 │ Task call: Restart                                         
INFO     20:12:58.015 │ Bind task ['General', 'Alas', 'Main']                      
INFO     20:12:58.017 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2024, 1, 22, 20, 12, 58),     
         Restart.Scheduler.Enable=True                                             
INFO     20:13:08.026 │ Scheduler: End task `Main`                                 
INFO     20:13:08.029 │ [Server] cn                                                
INFO     20:13:08.052 │ Bind task ['General', 'Alas']                              
INFO     20:13:08.055 │ Pending tasks: ['Restart', 'Main']                         
INFO     20:13:08.056 │ [Task] Restart (Enable, 2024-01-22 20:12:58)               
INFO     20:13:08.057 │ Bind task ['General', 'Alas', 'Restart']                   
INFO     20:13:08.067 │ Scheduler: Start task `Restart`                            
═══════════════════════════════════════════════════════════════════════════════════
                                      RESTART                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     20:13:08.157 │ <<< APP RESTART >>>                                        
INFO     20:13:08.158 │ App stop: com.bilibili.azurlane                            
INFO     20:13:08.275 │ App start: com.bilibili.azurlane                           
INFO     20:13:08.514 │ <<< APP LOGIN >>>                                          
INFO     20:13:08.577 │ [Device Orientation] 0 (Normal)                            
INFO     20:13:13.889 │ [Device Orientation] 0 (Normal)                            
INFO     20:13:19.017 │ [Device Orientation] 0 (Normal)                            
INFO     20:13:24.135 │ [Device Orientation] 0 (Normal)                            
INFO     20:13:28.902 │ Click ( 483,  356) @ LOGIN_CHECK                           
INFO     20:13:28.955 │ Login success                                              
INFO     20:13:34.028 │ Click ( 462,  323) @ LOGIN_CHECK                           
INFO     20:13:39.136 │ Click ( 438,  342) @ LOGIN_CHECK                           
INFO     20:13:44.266 │ Click ( 458,  355) @ LOGIN_CHECK                           
INFO     20:13:49.395 │ Click ( 518,  362) @ LOGIN_CHECK                           
INFO     20:13:54.498 │ Click ( 513,  344) @ LOGIN_CHECK                           
INFO     20:13:59.648 │ Click ( 466,  345) @ LOGIN_CHECK                           
INFO     20:14:04.742 │ Click ( 481,  367) @ LOGIN_CHECK                           
INFO     20:14:09.868 │ Click ( 497,  350) @ LOGIN_CHECK                           
INFO     20:14:14.979 │ Click ( 493,  357) @ LOGIN_CHECK                           
INFO     20:14:20.083 │ Click ( 487,  381) @ LOGIN_CHECK                           
INFO     20:14:25.221 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  20:14:25.225 │ Too many click for a button: LOGIN_CHECK                   
WARNING  20:14:25.226 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  20:14:25.228 │ Too many click for a button: LOGIN_CHECK                   
INFO     20:14:25.229 │ App stop: com.bilibili.azurlane                            
INFO     20:14:25.317 │ App start: com.bilibili.azurlane                           
INFO     20:14:25.511 │ <<< APP LOGIN >>>                                          
INFO     20:14:25.567 │ [Device Orientation] 0 (Normal)                            
INFO     20:14:30.824 │ [Device Orientation] 0 (Normal)                            
INFO     20:14:35.916 │ [Device Orientation] 0 (Normal)                            
INFO     20:14:41.023 │ [Device Orientation] 0 (Normal)                            
INFO     20:14:43.096 │ Click ( 506,  369) @ LOGIN_CHECK                           
INFO     20:14:43.148 │ Login success                                              
INFO     20:14:48.232 │ Click ( 451,  347) @ LOGIN_CHECK                           
INFO     20:14:53.332 │ Click ( 446,  334) @ LOGIN_CHECK                           
INFO     20:14:58.455 │ Click ( 471,  349) @ LOGIN_CHECK                           
INFO     20:15:03.562 │ Click ( 468,  332) @ LOGIN_CHECK                           
INFO     20:15:08.697 │ Click ( 481,  375) @ LOGIN_CHECK                           
INFO     20:15:13.802 │ Click ( 457,  357) @ LOGIN_CHECK                           
INFO     20:15:18.953 │ Click ( 497,  360) @ LOGIN_CHECK                           
INFO     20:15:24.048 │ Click ( 478,  336) @ LOGIN_CHECK                           
INFO     20:15:29.164 │ Click ( 434,  358) @ LOGIN_CHECK                           
INFO     20:15:34.300 │ Click ( 489,  329) @ LOGIN_CHECK                           
INFO     20:15:39.420 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  20:15:39.424 │ Too many click for a button: LOGIN_CHECK                   
WARNING  20:15:39.425 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  20:15:39.426 │ Too many click for a button: LOGIN_CHECK                   
INFO     20:15:39.427 │ App stop: com.bilibili.azurlane                            
INFO     20:15:39.503 │ App start: com.bilibili.azurlane                           
INFO     20:15:39.686 │ <<< APP LOGIN >>>                                          
INFO     20:15:39.752 │ [Device Orientation] 0 (Normal)                            
INFO     20:15:44.988 │ [Device Orientation] 0 (Normal)                            
INFO     20:15:50.105 │ [Device Orientation] 0 (Normal)                            
INFO     20:15:55.204 │ [Device Orientation] 0 (Normal)                            
INFO     20:15:56.977 │ Click ( 484,  355) @ LOGIN_CHECK                           
INFO     20:15:57.029 │ Login success                                              
INFO     20:16:02.110 │ Click ( 458,  349) @ LOGIN_CHECK                           
INFO     20:16:07.212 │ Click ( 479,  372) @ LOGIN_CHECK                           
INFO     20:16:12.331 │ Click ( 475,  335) @ LOGIN_CHECK                           
INFO     20:16:17.447 │ Click ( 464,  337) @ LOGIN_CHECK                           
INFO     20:16:22.594 │ Click ( 460,  336) @ LOGIN_CHECK                           
INFO     20:16:27.706 │ Click ( 479,  346) @ LOGIN_CHECK                           
INFO     20:16:32.803 │ Click ( 475,  353) @ LOGIN_CHECK                           
INFO     20:16:37.927 │ Click ( 454,  328) @ LOGIN_CHECK                           
INFO     20:16:43.048 │ Click ( 456,  366) @ LOGIN_CHECK                           
INFO     20:16:48.151 │ Click ( 466,  334) @ LOGIN_CHECK                           
INFO     20:16:53.267 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L166 restart()                                         
                   login.py L158 app_restart()                                     
                   login.py L132 handle_app_login()                                
                   login.py  L55 _handle_app_login()                               
                 control.py  L35 click()                                           
                  device.py L183 handle_control_check()                            
                  device.py L219 click_record_check()                              
                  device.py  L41 show_function_call()                              
WARNING  20:16:53.271 │ Too many click for a button: LOGIN_CHECK                   
WARNING  20:16:53.272 │ History click: ['LOGIN_CHECK', 'LOGIN_CHECK',              
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK',
         'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK', 'LOGIN_CHECK']
WARNING  20:16:53.273 │ Too many click for a button: LOGIN_CHECK                   
INFO     20:16:53.274 │ App stop: com.bilibili.azurlane                            
INFO     20:16:53.350 │ App start: com.bilibili.azurlane                           
CRITICAL 20:16:53.511 │ Login failed more than 3                                   
CRITICAL 20:16:53.512 │ Azur Lane server may be under maintenance, or you may lost 
         network connection                                                        
CRITICAL 20:16:53.514 │ Request human takeover                                     
INFO     20:16:53.517 │ No provider specified, skip sending

**Comment by LmeSzinc** [comment]
雷电专属问题，更换模拟器解决

**Comment by fhouia** [comment]
了解，非常感谢
