### ISSUE TITLE
当满油时无法领取军事委托奖励，会一直尝试领取直到报错

### ISSUE THREAD

**Issue by knoic** [LmeSzinc/AzurLaneAutoScript#3466]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当满油时无法领取远征奖励，会一直尝试领取直到报错

### 如何复现

1. 前往 '远征领取界面（满油前提下）'
2. 点击 '收取远征奖励'
3. 滑动到 '....'
4. 无法领取，一直尝试点击领取，直到报错

### 预期行为

满油无法领取远征奖励时，跳过该操作，或者去其他地方消耗油后再重新领取

**Comment by sisyphusovo** [comment]
远征是哪个

**Comment by knoic** [comment]
> 远征是哪个

军事委托，“远征”是舰队collection里的军事委托，口误

**Comment by yeluo2022** [comment]
这是24小时挂机脚本，如果没有做到配置好任务进行7*24挂机，造成的问题就自己解决
