### ISSUE TITLE
[TW]使用自律尋敵,戰鬥中出現WARNING | Wait too long

### ISSUE THREAD

**Issue by benny724** [LmeSzinc/AzurLaneAutoScript#350]
**Describe the bug**
使用自律尋敵功能,在第二場戰鬥中
出現WARNING | Wait too long and then restart game 

**Screenshots**
![2021-02-14_22-36-11-856131](https://user-images.githubusercontent.com/70300665/107879720-7aca3280-6f15-11eb-8b1b-f0bef84208bd.png)
![2021-02-14_22-36-31-268022](https://user-images.githubusercontent.com/70300665/107879725-7f8ee680-6f15-11eb-8695-c622c0701418.png)

**Log**
Post the entire log snippet that caused you to receive the error
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5977902/log.txt)

**Comment by LmeSzinc** [comment]
TW 还未适配自律寻敌. 需要更新的内容可参考 #322 #331

**Comment by LmeSzinc** [comment]
已适配, #353
