### ISSUE TITLE
 作战档案 神圣的悲喜剧 B3 刷图出错

### ISSUE THREAD

**Issue by Malatan** [LmeSzinc/AzurLaneAutoScript#3508]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

 作战档案 神圣的悲喜剧 B3 打了一场以后就会显示这个 试了2次 都这样
B3已经三星和安全海域

### 如何复现

1. 前往 '作战档案 神圣的悲喜剧 B3'
2. 点击 '周回和高效✔，阵容锁定和自律寻敌×'
3. 滑动到 '....'
4. 出现问题

### 截图

![Screenshot 2024-02-24 002007](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/40026469/69c25481-666a-4692-bef5-0e46865f31e8)
![Screenshot 2024-02-24 001904](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/40026469/8e2039ce-a0d7-4ff6-9f3e-f02440e5d646)

**Comment by LmeSzinc** [comment]
上传完整 log
