### ISSUE TITLE
ModuleNotFoundError: No module named 'jellyfish'

### ISSUE THREAD

**Issue by wqdasd31** [LmeSzinc/AzurLaneAutoScript#351]
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/5978065/log.txt)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
Post the entire log snippet that caused you to receive the error

**Comment by whoamikyo** [comment]
under AzurLaneAutoScript folder, open console.bat and type `pip install jellyfish` then enter.

**Comment by wqdasd31** [comment]
> under AzurLaneAutoScript folder, open console.bat and type `pip install jellyfish` then enter.

thank u
