### ISSUE TITLE
B服活动每日卡死

### ISSUE THREAD

**Issue by loy4dot** [LmeSzinc/AzurLaneAutoScript#3521]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用活动每日D图或者SP都会报错

### 相关 Logs

```Text
INFO     13:22:19.455 │ D3                                                         
INFO     13:22:19.456 │ Expect emotion reduce: (14, 0)                             
INFO     13:22:19.472 │ Bind task ['General', 'Alas', 'TaskBalancer',              
         'EventGeneral', 'EventD']                                                 
INFO     13:22:19.474 │ Save config ./config\alas.json,                            
         EventD.Emotion.Fleet1Value=119,                                           
         EventD.Emotion.Fleet1Record=datetime.datetime(2024, 3, 2, 13, 22, 19),    
         EventD.Emotion.Fleet2Value=119,                                           
         EventD.Emotion.Fleet2Record=datetime.datetime(2024, 3, 2, 13, 22, 19)     
INFO     13:22:19.482 │ [Emotion fleet_1] 119                                      
INFO     13:22:19.484 │ [Emotion fleet_2] 119                                      
CRITICAL 13:22:19.485 │ Fleet 1 Emotion Control="Keep Happy Bonus" and Fleet 1     
         Recover Location="Docks" can not be used together, please check your      
         emotion settings                                                          
CRITICAL 13:22:19.486 │ Request human takeover                                     
INFO     13:22:19.487 │ No provider specified, skip sending
```

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/326329f9-12ed-4e98-bc36-03860aec0721)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/0cc3ea0e-eeeb-451b-b244-487542cc467c)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/03785b5f-2afc-4a6a-b58d-dc8329be9ebe)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/245a564d-6512-4636-ade3-5798ca75a5f9)

**Comment by loy4dot** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/1e6c3d41-17d7-4c41-aff0-b4350ba4ef05)

**Comment by loy4dot** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/8527ae21-eb9e-47fd-811f-fe1ec2e46f91)

**Comment by loy4dot** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/abaf5a65-7945-45bd-9100-eaa281a6178e)

**Comment by loy4dot** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/20570346/67c796e2-9b22-45e2-8c11-1280d9934b18)

**Comment by GodofTheFallen** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/15105315/eb99816f-fd4a-41aa-95a3-fd78c2e2d211)
这俩选项冲突，属于设置有误

**Comment by NJUsunset** [comment]
舰队1心情设置里，保持经验加成和未放置后宅冲突
