### ISSUE TITLE
希望能增加一个编队绑定功能以适配可能的心情变化

### ISSUE THREAD

**Issue by AbyssAzrael** [LmeSzinc/AzurLaneAutoScript#3535]
### 你的功能请求是否与问题有关？

活动时每日活动关和正常刷pt的活动关用的是同一个编组，导致心情错乱

### 解决方案

希望在编队选择增加一个类似于“使用2队[通用编队1]”这样的功能，将两个不同的task中使用编队的心情互相绑定

### 其他内容

![1](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/82253519/0dcca545-8e13-406e-8f60-4b03fdbdc1ff)

**Comment by LmeSzinc** [comment]
多个任务之间不能共享角色

**Comment by AbyssAzrael** [comment]
> 多个任务之间不能共享角色

也就是说只能再多练一套工具人分开执行任务吗
有些复刻活动每日ABCD图全要打，不放后宅满119心情打不完全图都红脸，但是任务调度又是连战，很头疼

**Comment by AbyssAzrael** [comment]
> > 多个任务之间不能共享角色
> 
> 也就是说只能再多练一套工具人分开执行任务吗 有些复刻活动每日ABCD图全要打，不放后宅满119心情打不完全图都红脸，但是任务调度又是连战，很头疼

所以希望能开发一个优先于每个子任务的心情管理系统，否则多个任务使用同一编队中的角色会很麻烦
我也不了解代码语言，不懂这样的功能实现起来困不困难，只能说希望还是能有一个类似的功能管理
