### ISSUE TITLE
希望能添加再油满了的情况下自动买咖喱功能

### ISSUE THREAD

**Issue by 624980976** [LmeSzinc/AzurLaneAutoScript#3541]
### 你的功能请求是否与问题有关？

现在alas中如果油满了会导致程序进入[点击收取->无法收取->重启游戏->点击收取]的死循环中,看了一下其他玩家提交的issues,@LmeSzinc给出的方法都是去后宅买咖喱,我认为一个7x24小时挂机脚本应当自动买咖喱

### 解决方案

能添加再油满了的情况下自动买咖喱功能

**Comment by guoh064** [comment]
我认为一个7x24脚本的用户应当开启刷图功能来消耗石油，这样满的只会是金币，而金币满的情况已经处理了（dog

**Comment by 624980976** [comment]
满金币的情况的处理设置在哪里呢?

**Comment by guoh064** [comment]
每日任务-通用商店-消耗溢出物资

**Comment by 624980976** [comment]
好的,我找到了,谢谢
