### ISSUE TITLE
大世界，潜艇支援脱离对话框阻止侵蚀1练级功能的启动

### ISSUE THREAD

**Issue by Yourwing** [LmeSzinc/AzurLaneAutoScript#3545]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![Snipaste_2024-03-13_16-02-07](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/38237566/bd7e81d8-c573-4096-9bda-33e8b9115301)

### 如何复现

1. 前往大型作战
2. 启用指令-潜水支援
3. 在仍有残留次数的情况下启动ALAS功能-侵蚀1练级
4. 出现问题

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
