### ISSUE TITLE
请问本次活动的每日地图应该怎么设置？

### ISSUE THREAD

**Issue by TakinaNoa** [LmeSzinc/AzurLaneAutoScript#3554]
### 你的功能请求是否与问题有关？

这不是一个功能请求，但我不清楚本次活动的每日地图应该怎么设置，因为本次活动地图名是sp1、sp2、sp3、sp4，sp4可以通过活动图设置自动战斗，但是前面三个在每日地图页面内没有相关的设置项，请问这个应该怎么选择怎么设置呢？谢谢

**Comment by fhwhite** [comment]
同

**Comment by yuko0931** [comment]
同问

**Comment by Decandy-star** [comment]
我是每日活动A里面改就好了

**Comment by TakinaNoa** [comment]
> 我是每日活动A里面改就好了

请问是怎么改的

**Comment by Emokable** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/93334525/7108daca-4a98-4be1-a019-12e59e65a8a3)
这样改一下名字就行了

**Comment by hsf1021** [comment]
把活动每日A图的所有A 替换成SP就完事了 自己再补一个SP4（如果开了自动刷SP4可以不补） 活动结束换回A就好
它做了识别 没单独做个每日刷SP图的局域栏而已
![{891804D1-A68F-40fd-87FA-F95517B9A9D9}](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/64143174/5058f9c2-369d-4311-9774-99901989e968)

**Comment by TakinaNoa** [comment]
> 把活动每日A图的所有A 替换成SP就完事了 自己再补一个SP4（如果开了自动刷SP4可以不补） 活动结束换回A就好 它做了识别 没单独做个每日刷SP图的局域栏而已 ![{891804D1-A68F-40fd-87FA-F95517B9A9D9}](https://private-user-images.githubusercontent.com/64143174/313402441-5058f9c2-369d-4311-9774-99901989e968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjAwMzAsIm5iZiI6MTcxMDc1OTczMCwicGF0aCI6Ii82NDE0MzE3NC8zMTM0MDI0NDEtNTA1OGY5YzItMzY5ZC00MzExLTk3NzQtOTk5MDE5ODllOTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDExMDIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMGQ5MzFmZjA0ZGE0OTM2Zjg1NDk0MWJkN2M0YzRjMjM3Y2E0NDk3M2MxYjgwNmE4ZmRiYjBmOGE0Yjc0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qUS-56eLxeVwrwuFY5gArvXB824PtP43KDnZLj7YJ2o)

嗯嗯好的，明白了，谢谢
