### ISSUE TITLE
关于使用雷电模拟器的若干问题

### ISSUE THREAD

**Issue by qx100** [LmeSzinc/AzurLaneAutoScript#356]
**前言**
我使用的是雷电模拟器，在使用该脚本时遇到了一些小问题。现将问题与解决方法陈列如下，希望其他人可以借鉴我的方法使用这个脚本，也同样希望开发者可以从中获得一些启发，将脚本改进的越来越好。

**问题描述与解决**
* 1.关于雷电模拟器的端口问题
雷电模拟器的端口的规则是5555+index*2。其中index就是模拟器的编号，可从雷电多开器中查看。
例如我使用的是2号模拟器，那么就应该使用127.0.0.1:5559来设置serial。这里与[傻瓜教程](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn)里的相关内容有出入。
但是在cmd里面使用adb devices命令查看时,出现了emulator-5554，我对此并无更多了解。更多的情况可以参阅[这篇帖子](https://blog.csdn.net/zcp528/article/details/107480381)。

* 2.关于alsa.bat选择晚语言后闪退问题
出现这个问题是由于批处理文件里面雷电模拟器的默认注册表路径错误导致。
右键点击alas.bat,选择编辑，找到如下图所示代码段
![image](https://user-images.githubusercontent.com/25811098/108180000-3ae79300-7141-11eb-999f-ac9e53eaa2cc.png)
以及这里的
![image](https://user-images.githubusercontent.com/25811098/108183357-f4943300-7144-11eb-85f4-f83694b5ca3f.png)
然后打开注册表编辑器，找到雷电模拟器的注册表路径,如下图所示，那个ldplayer64似乎是由于我安装了64位雷电模拟器导致，没有则可以忽略。
![image](https://user-images.githubusercontent.com/25811098/108180218-771af380-7141-11eb-81ae-14d82e122a4a.png)
然后复制路径，修改bat文件，修改后的代码如下图所示
![image](https://user-images.githubusercontent.com/25811098/108183618-391fce80-7145-11eb-92ce-ec87bf635b5a.png)
以及
![image](https://user-images.githubusercontent.com/25811098/108183889-88fe9580-7145-11eb-9bab-01d291ddc93b.png)

* 3.关于alsa.bat无法将toolkit文件夹中的adb.exe复制到雷电安装文件夹下
尝试使用了管理员权限仍然无法实现
于是手动将当前目录下的toolkit\Lib\site-packages\adbutils\binaries\adb.exe复制，然后打开雷电模拟器的安装目录，将原有的adb.exe重命名为adb.exe.bak,然后粘贴进去。

* 4.关于无法重启雷电模拟器的问题
到了重启模拟器的一步，雷电模拟器并没有重启，而是无响应。
经了解，雷电模拟器有一个内置的ldconsole.exe命令行，可以利用它来重启模拟器。同样是编辑alas.bat，找到下图所示代码段
![image](https://user-images.githubusercontent.com/25811098/108182260-c8c47d80-7143-11eb-8ef6-49d01818ae45.png)

将其修改为

![image](https://user-images.githubusercontent.com/25811098/108182614-28bb2400-7144-11eb-9f41-5eec268e1c71.png)

--index 后面的2是由于我使用的是2号模拟器，可以根据实际使用的模拟器编号修改。

**最后**
经过如上一番折腾，终于可以使用脚本开始自动肝游戏了。希望对使用雷电模拟器的你有所帮助。

**Comment by LmeSzinc** [comment]
#482
