### ISSUE TITLE
log中的游戏服务器显示错误

### ISSUE THREAD

**Issue by JerryZhousy** [LmeSzinc/AzurLaneAutoScript#3567]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

我的游戏本体为从Google Play下载的国际服，并且在Alas中的游戏服务器也设置为了国际服，但在log “INFO     22:01:53.112” 中游戏服务器依旧为cn

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     22:01:53.107 │ Start scheduler loop: alas                                 
INFO     22:01:53.112 │ [Server] cn                                                
INFO     22:01:53.142 │ Bind task ['General', 'Alas']                              
INFO     22:01:53.584 │ Server "Little Enterprise" is available.                   
INFO     22:01:53.598 │ Pending tasks: ['Restart', 'Main']                         
INFO     22:01:53.601 │ [Task] Restart (Enable, 2024-03-19 21:59:35)               
INFO     22:01:53.602 │ Bind task ['General', 'Alas', 'Restart']
```

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/159777343/4a973e43-a042-46ed-a703-f90d59df94a5)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/159777343/232c19d2-7ba3-4f24-af20-d82e9e2c3534)

**Comment by JerryZhousy** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/159777343/f4b5020a-9a0a-4b91-a7cb-185f296b3410)

**Comment by JerryZhousy** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/159777343/e0296493-537d-4708-81bb-2d7ff8e98316)

**Comment by LmeSzinc** [comment]
这是默认值 不影响，服务器会在Device类初始化并连接到设备之后变更
