### ISSUE TITLE
更新时找不到pip，没有正确更新依赖库

### ISSUE THREAD

**Issue by Clyde-Li** [LmeSzinc/AzurLaneAutoScript#357]
Issue:
更新时，pip安装依赖报错
When updating Alas, the program cannot found pip. Requirements are not installed correctly.

This image shows the error information:
![image](https://user-images.githubusercontent.com/33029051/108229409-b5131a00-7137-11eb-9b86-9e86ab2f6fa5.png)

Possible reason:
最后顺着脚本找了半天，发现实际上调用的是toolkit\command\pip.cmd。toolkit\command被加在了PATH的最前面。
Finally I found alas.bat is actually trying to call "toolkit\command\pip.cmd". "toolkit\command" was inserted into a very top place of the PATH.

toolkit\command\pip.cmd:
@"H:\Work\Github\ALAS\ADT-V4\AzurLaneAutoScript\toolkit\python.exe" "H:\Work\Github\ALAS\ADT-V4\AzurLaneAutoScript\toolkit\Scripts\pip.exe" %*

Additional details
我是用Alas-Deploy-Tool-V4.bat部署的，电脑只有一个C盘。
There is no H drive in my laptop. I deployed the Alas by Alas-Deploy-Tool-V4.bat with auto mode.

**Comment by h29800020** [comment]
我也有這問題

**Comment by QQ-6767** [comment]
该问题+1

**Comment by AlexHalogen** [comment]
我也遇到这个问题，运行一次console.bat就解决了(?)
看起来好像是打包了作者自己的toolkit/command/，并且在alas-deploy-tool-v4安装过程中时没有自动生成对应安装位置的cmd文件

Solved(?) by running console.bat that regenerated toolkit/command/; Seems like the script writer's own toolkit/command/ were packed in the release, and alas-deploy-tool-v4.bat did not generate cmds based on install location

**Comment by thankyyyyyy** [comment]
> 我也遇到这个问题，运行一次console.bat就解决了（？）
> 好像是打包了作者自己的toolkit/command/，在并且在alas-deploy-tool-v4安装过程中时没有自动生成对应安装位置的cmd文件
> 
> 通过运行重新生成 toolkit/command/ 的 console.bat 解决（？）；似乎脚本编写者自己的工具包/命令/被打包在发行版中，并且 alas-deploy-tool-v4.bat 没有根据安装位置生成 cmds



> 我也遇到这个问题，运行一次console.bat就解决了（？）
> 好像是打包了作者自己的toolkit/command/，在并且在alas-deploy-tool-v4安装过程中时没有自动生成对应安装位置的cmd文件
> 
> 通过运行重新生成 toolkit/command/ 的 console.bat 解决（？）；似乎脚本编写者自己的工具包/命令/被打包在发行版中，并且 alas-deploy-tool-v4.bat 没有根据安装位置生成 cmds

老哥我纯小白什么都不会的那种，能详细点吗。就是怎么运行console.bat    ？能稍微花点时间写个步骤吗     @AlexHalogen

**Comment by LmeSzinc** [comment]
#482
