### ISSUE TITLE
（手动安装教程）运行python -m uiautomator2 init，出现ModuleNotFoundError: No module named 'apkutils2'

### ISSUE THREAD

**Issue by Zhang-Yexun** [LmeSzinc/AzurLaneAutoScript#3581]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

问题:运行python -m uiautomator2 init，出现ModuleNotFoundError: No module named 'apkutils2'
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/d613b38a-4a6d-4b98-ab5f-f4e7f47c4b4b)
我在文件管理器中发现了这个文件夹
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/1adacb36-dd0d-4a76-834a-8b172f98bde3)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/59fc1964-9931-4d2e-ac5e-800579fe9fb7)
于是我想是不是要重新装，于是删除之后又重新装了一次
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/b846dbc6-e937-47ee-88e2-720cc298d44e)
但是最终结果还是没有找到
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/5b258e49-e23c-4028-b540-52af3dd6860d)

### 如何复现

1. 
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

别的:
前期准备
1.运行环境：
已经使用conda了创建名为 alas 的python 版本为 3.7.6的虚拟环境，并安装玩依赖
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/e1a9a8dc-09c9-493c-a909-080ec7d29f83)
2.模拟器运行，且ADB处于运行状态:
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/8da3a2f4-257d-4b9b-8cf9-dcff4d797118)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/140472860/202b3236-b99f-4fb2-bdcb-14d478c6ac44)

**Comment by LmeSzinc** [comment]
下载的包缓存文件损坏了，在虚拟环境内执行
```
pip uninstall -y apkutils2
pip install --no-cache-dir apkutils2
```
