### ISSUE TITLE
能否将大世界相关功能优先级后调至每日任务之后或是提供自定义优先级设置

### ISSUE THREAD

**Issue by AdorableParker** [LmeSzinc/AzurLaneAutoScript#3583]
### 你的功能请求是否与问题有关？

在快到次日0点时启动alas，任务执行时间都为今日0点的情况下，因为大世界相关功能执行时间较长，但又排在前面，导致大部分能够在当日完成的日常任务功能被迫无法完成，而推迟到次日0点之后才能被执行。

### 解决方案

希望能够提供自定义任务优先级设置，或是将每日任务等一些相对执行时间较短的任务先完成，以尽可能完成更多的任务

**Comment by LmeSzinc** [comment]
不能，这游戏的日课就是这么长，每天需要挂机够足够的时长
