### ISSUE TITLE
拆装备的科研只能拆白装

### ISSUE THREAD

**Issue by Joxos** [LmeSzinc/AzurLaneAutoScript#3600]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

拆装备的科研只能拆白装，然而很多情况下蓝装也是不需要的；Alas会在没有白装的情况下使用白箱子。能否让Alas可以拆蓝装？

### 如何复现

1. 调度科研前拆完仓库的白装
2. 刷出拆装备的科研
3. 让Alas操作
4. 出现问题

### 还有别的吗？

配置如下：

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37507136/015c0620-e793-4a08-a654-e9ddf2a6f13c)

**Comment by guoh064** [comment]
拆蓝装的话，万一把He-50b（ju87前置）和37mm高射炮Mle1925（彩防空前置）拆了怎么办？总不能再给所有装备加模板识别吧
