### ISSUE TITLE
希望能够提供一些接口以便在alas报错时重新启动

### ISSUE THREAD

**Issue by AZRadius** [LmeSzinc/AzurLaneAutoScript#3602]
### 你的功能请求是否与问题有关？

希望能够提供一些接口，用户可以通过接口获取
1：alas的具体状态，如运行中，闲置，发生错误；同时如果alas状态为运行中，希望查询到是否有任务正在执行中。
2：通过提供的接口，启动或者停止alas调度器

**Comment by LmeSzinc** [comment]
Alas设置 - 调试设置 - 错误推送设置
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/fa0cd900-9bc4-41a5-acc4-5bae22996d50)

**Comment by radmeng** [comment]
请问第二点"2：通过提供的接口，启动或者停止alas调度器"；目前的alas能够实现吗

**Comment by izumedonabe** [comment]
请问该问题是否得到解决？现在有相同需求
