### ISSUE TITLE
9-4普通海图识别出错

### ISSUE THREAD

**Issue by Cusweety** [LmeSzinc/AzurLaneAutoScript#3624]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用主线图功能开荒普通模式9-4（3星+100%）时因海图识别错误（大概）卡住，可复现，重复三次仍会卡住，于是来反馈一下看看是咱的问题还是有bug。

### 如何复现

1. 前往 'alas主线图'功能，选择9-4、普通、3星+100%、向前开荒、最低油1k、单舰队+潜艇出战、索敌依照地图文件
2. 点击 '启动调度器'
3. alas前往9-4并试图使舰队前往D4位置（但是该位置为地形障碍且日志显示操作为“swipe”）
4. 出现问题（重启设置，并重复以上步骤）

### 预期行为

正常情况应该为正常开荒，绕过障碍并打击敌方舰队，而非一直戳一个无法前往的位置。
猜测是海图识别错误导致的。

### 相关 Logs

```Text
日志过长，完整的放在相关参考资料那里了。
这里放一下9-4识别出来的海图：
2024-04-10 13:30:30.263 | INFO | -- -- -- -- -- -- -- --                                                               
2024-04-10 13:30:30.264 | INFO | -- -- Fl -- -- -- FL --                                                               
2024-04-10 13:30:30.265 | INFO | -- -- 3L -- -- -- -- --                                                               
2024-04-10 13:30:30.267 | INFO | 2M -- -- -- -- -- 3L --                                                               
2024-04-10 13:30:30.268 | INFO | -- -- -- -- -- -- -- ..  
其中一直挨戳的是D4，请看截图
```

### 截图

![2024-04-10_13-30-30-663367](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/54624623/b9ce1275-2a57-4f24-9a19-64857d8b53bd)
![2024-04-10_13-31-52-488027](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/54624623/63a270c8-4dad-42e8-a90b-c930e8044c9d)
![2024-04-10_13-45-00-553220](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/54624623/c9dcf8ac-6131-49ef-a1f1-ef3ada279706)

### 还有别的吗？

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/14928580/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/14928582/log.txt)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/14928583/log.txt)

**Comment by Cusweety** [comment]
咦？才发现F4也挨戳了

**Comment by Air111** [comment]
swipe的问题，你是不是在用nemu_ipc？

**Comment by Cusweety** [comment]
我并不清楚nemu_ipc是什么，但运行日志的确有提到这个关键词，请问这会对alas产生什么影响吗？我应该如何解决这个问题？

**Comment by Air111** [comment]
> 我并不清楚nemu_ipc是什么，但运行日志的确有提到这个关键词，请问这会对alas产生什么影响吗？我应该如何解决这个问题？

如果频繁出现，暂时将“模拟器截图方案”和“模拟器控制方案”改为其它的

**Comment by Cusweety** [comment]
明白

**Comment by jcm007** [comment]
> > 我并不清楚nemu_ipc是什么，但运行日志的确有提到这个关键词，请问这会对alas产生什么影响吗？我应该如何解决这个问题？
> 
> 如果频繁出现，暂时将“模拟器截图方案”和“模拟器控制方案”改为其它的
确实是这个问题，改用了其他的方案以后，虽然速度上可能有差别，但是识别和操作上可靠性高了些。

**Comment by Air111** [comment]
> 确实是这个问题，改用了其他的方案以后，虽然速度上可能有差别，但是识别和操作上可靠性高了些。

现在不应该还是这个原因，如果你用nemu_ipc有问题最好发新的issue
