### ISSUE TITLE
关卡图标有遮挡，致使无法识别。手机端和电脑端都有这种情况

### ISSUE THREAD

**Issue by xiaohehe222** [LmeSzinc/AzurLaneAutoScript#3631]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

手机端和电脑端都有这种情况

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/125237252/fa855c06-ab8c-4d14-a296-cc8a4ede3025)
![屏幕截图 2024-04-11 214609](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/125237252/19b7994b-42f6-415f-aacd-ff8fd7d6ba47)

**Comment by Lazy-Beee** [comment]
感觉是关卡图标样式变了

**Comment by LmeSzinc** [comment]
#3632
