### ISSUE TITLE
4399悬浮球关闭，悬浮窗不关闭会严重影响其余功能正常执行

### ISSUE THREAD

**Issue by sjf520111** [LmeSzinc/AzurLaneAutoScript#3661]
### 你的功能请求是否与问题有关？

4399每次启动游戏会出现悬浮球，在ALAS操作时，会影响（目前已知）：大世界日常、MATE信标图像识别异常；ALAS偶尔会出现误点、打开悬浮球弹出页面，导致脚本停止运行。

### 解决方案

悬浮球在游戏启动时是产生于固定坐标，可以拖拽移至固定区域隐藏悬浮球。可以添加一个选项，勾选可以在游戏启动时固定拖拽隐藏悬浮球。

**Comment by Air111** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3339#issuecomment-1867917492
