### ISSUE TITLE
无法领取信标档案奖励

### ISSUE THREAD

**Issue by Air111** [LmeSzinc/AzurLaneAutoScript#3667]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [ ] 我正在使用最新版的 Alas

### 描述你的问题

我一直感觉信标档案奖励没法领取，看了一下过去一个月的log，一天一次`No dossier reward red dot`，而`Found dossier reward red dot`无结果

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/1b71236e3aa45103feaf576137416a9c0de1a892/module/meta_reward/meta_reward.py#L120-L122

发现此处代码有误，在设置`offset`时`threshold`的取值范围应为[0,1]

此外，dossier meta page的红色感叹号与`DOSSIER_REWARD_RECEIVE`有不小的差别，下图match的similarity仅有0.8，而且位置好像偏了一点，可能应该新加asset而不是复用`DOSSIER_REWARD_CHECK`页面的红色感叹号。

![Screenshot_2024 04 23_01 03 23 876](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/54128005/920341c2-bc6a-4035-8372-c25932116b4a)

**Comment by Air111** [comment]
e74df69 应该还是得用`DOSSIER_REWARD_NOTICE`

**Comment by guoh064** [comment]
DOSSIER_REWARD_NOTICE 和 DOSSIER_REWARD_RECEIVE 相近，增大 offset 参数共用一个 assets

_Originally posted by @LmeSzinc in https://github.com/LmeSzinc/AzurLaneAutoScript/pull/2996#discussion_r1320193497_
            
这个你自己改吧，如果两个叹号其实不太一样的话那可以考虑把similarity降低一点。
