### ISSUE TITLE
主线图功能增加15图

### ISSUE THREAD

**Issue by PPPPPPPAD** [LmeSzinc/AzurLaneAutoScript#3669]
### 解决方案

希望主线图功能增加15图，目前似乎最高只能支持14-4

### 其他内容

目前主线图关卡名称填写15-1后日志如下═══════════════════════════════════════════════════════════════════════════════════
                                       MAIN                                        
═══════════════════════════════════════════════════════════════════════════════════
WARNING  08:21:21.043 │ Map file not found: campaign.campaign_main.campaign_15_1   
WARNING  08:21:21.045 │ Existing files: ['campaign_10_1', 'campaign_10_2',         
         'campaign_10_3', 'campaign_10_4', 'campaign_11_1', 'campaign_11_2',       
         'campaign_11_3', 'campaign_11_4', 'campaign_12_1', 'campaign_12_2',       
         'campaign_12_2_leveling', 'campaign_12_3', 'campaign_12_4',               
         'campaign_12_4_leveling', 'campaign_12_4_timeout_leveling',               
         'campaign_13_1', 'campaign_13_2', 'campaign_13_3', 'campaign_13_4',       
         'campaign_14_1', 'campaign_14_2', 'campaign_14_3', 'campaign_14_4',       
         'campaign_14_base', 'campaign_1_1', 'campaign_1_1_affinity_farming',      
         'campaign_1_2', 'campaign_1_3', 'campaign_1_4', 'campaign_2_1',           
         'campaign_2_2', 'campaign_2_3', 'campaign_2_4', 'campaign_3_1',           
         'campaign_3_2', 'campaign_3_3', 'campaign_3_4', 'campaign_4_1',           
         'campaign_4_2', 'campaign_4_3', 'campaign_4_4', 'campaign_5_1',           
         'campaign_5_2', 'campaign_5_3', 'campaign_5_4', 'campaign_6_1',           
         'campaign_6_2', 'campaign_6_3', 'campaign_6_4', 'campaign_7_1',           
         'campaign_7_2', 'campaign_7_2_mystery_farming', 'campaign_7_3',           
         'campaign_7_4', 'campaign_8_1', 'campaign_8_2', 'campaign_8_3',           
         'campaign_8_4', 'campaign_8_4_leveling', 'campaign_9_1', 'campaign_9_2',  
         'campaign_9_3', 'campaign_9_4']                                           
CRITICAL 08:21:21.047 │ Possible reason #1: This event (campaign_main) does not    
         have campaign_15_1                                                        
CRITICAL 08:21:21.048 │ Possible reason #2: You are using an old Alas, please check
         for update, or make map files yourself using dev_tools/map_extractor.py   
CRITICAL 08:21:21.050 │ Request human takeover                                     
INFO     08:21:21.052 │ No provider specified, skip sending

**Comment by Air111** [comment]
你可以切到dev分支，顺便帮忙测试

**Comment by PPPPPPPAD** [comment]
> 你可以切到dev分支，顺便帮忙测试

试了下15-1周回倒是没啥问题

**Comment by LmeSzinc** [comment]
#3563
