### ISSUE TITLE
alas前天深夜更新完无法打开

### ISSUE THREAD

**Issue by aswwdd** [LmeSzinc/AzurLaneAutoScript#3695]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [ ] 我正在使用最新版的 Alas

### 描述你的问题

![QQ截图20240427150128](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/91826432/f4ac569a-780c-463d-a009-66f89c0c3ec6)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

怎么样能解决这个问题

### 截图

![QQ截图20240427145919](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/91826432/1be3bdc2-f031-483c-9366-a5f75e72f315)

**Comment by Air111** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/releases 阅读说明下载最新版重新安装
