### ISSUE TITLE
大世界刷短猫时频繁因报错：Too many click for a button: MAP_SWIPE_0_0 而中止

### ISSUE THREAD

**Issue by Heipen** [LmeSzinc/AzurLaneAutoScript#3698]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

游戏中具体表现：自律完成后本应大范围搜图，实际只在一个小区域中快速进行非常非常短的拖动，使得地图几乎没动，也便点不到地图外以离开地图。
大世界刷短猫过程中平均每一到两个图就会出现一次同样的报错，随后重启游戏。重复几次alas便会停止运行。目前为止我的error中已经有了十几个结尾报错完全相同的log

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
2024-04-28 10:25:21.594 | INFO | Map swipe: (0, 0)                                                                     
2024-04-28 10:25:21.596 | INFO | Swipe ( 709,  504) -> ( 742,  479)                                                    
2024-04-28 10:25:21.882 | INFO |            tile_center: 0.955 (good match)                                            
2024-04-28 10:25:21.894 | INFO | 0.067s  _   edge_lines: 1 hori, 1 vert                                                
2024-04-28 10:25:21.896 | INFO | Edges:   \   homo_loca: ( 17,  74)                                                    
2024-04-28 10:25:21.900 | INFO |           grids_offset: (1, 0)                                                        
2024-04-28 10:25:21.901 | INFO |            center_loca: (4, 1)                                                        
2024-04-28 10:25:21.902 | INFO |                 Camera: G2                                                            
2024-04-28 10:25:21.929 | INFO | 0.025s         predict: 38                                                            
2024-04-28 10:25:21.930 | INFO | -- -- -- -- -- -- -- --                                                               
2024-04-28 10:25:21.930 | INFO | -- -- -- -- -- -- -- --                                                               
2024-04-28 10:25:21.930 | INFO | -- -- -- -- -- -- -- --                                                               
2024-04-28 10:25:21.931 | INFO | .. -- -- -- -- -- -- --                                                               
2024-04-28 10:25:21.932 | INFO | .. -- -- -- -- -- -- --                                                               
2024-04-28 10:25:21.933 | INFO | Map swipe: (0, 0)                                                                     
2024-04-28 10:25:21.936 | INFO | Function calls:                                                                       
          <string>   L1 <module>                                                                                       
          spawn.py L105 spawn_main()                                                                                   
          spawn.py L118 _main()                                                                                        
        process.py L297 _bootstrap()                                                                                   
        process.py  L99 run()                                                                                          
process_manager.py L151 run_process()                                                                                  
           alas.py L514 loop()                                                                                         
           alas.py  L68 run()                                                                                          
           alas.py L330 opsi_meowfficer_farming()                                                                      
         os_run.py  L60 opsi_meowfficer_farming()                                                                      
operation_siren.py L385 os_meowfficer_farming()                                                                        
            map.py L711 run_auto_search()                                                                              
            map.py L883 map_rescan()                                                                                   
            map.py L857 map_rescan_once()                                                                              
         camera.py L349 focus_to()                                                                                     
         camera.py  L85 map_swipe()                                                                                    
         camera.py  L20 _map_swipe()                                                                                   
         camera.py  L59 _map_swipe()                                                                                   
        control.py L148 swipe_vector()                                                                                 
        control.py  L89 swipe()                                                                                        
         device.py L232 handle_control_check()                                                                         
         device.py L268 click_record_check()                                                                           
         device.py  L40 show_function_call()                                                                           
2024-04-28 10:25:21.939 | WARNING | Too many click for a button: MAP_SWIPE_0_0                                         
2024-04-28 10:25:21.941 | WARNING | History click: ['MAP_SWIPE_0_1', 'MAP_SWIPE_-1_0', 'MAP_SWIPE_-1_0',               
'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 
'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0', 'MAP_SWIPE_0_0']                                   
2024-04-28 10:25:21.942 | ERROR | GameTooManyClickError: Too many click for a button: MAP_SWIPE_0_0                    
2024-04-28 10:25:21.943 | WARNING | Saving error: ./log/error/1714271121943
```

### 截图

![2024-04-28_10-25-21-824486](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/126669219/d2c7f425-2e8e-4a0a-806d-d1394a8263fd)

**Comment by Heipen** [comment]
补充一点，似乎当且仅当海域内刷出了探测/收集装置、商人时才能正常进入下一海域，否则100%触发该bug

**Comment by qyyxxx407** [comment]
我的活动开荒也遇见了同样的问题

**Comment by TinyTitanPro** [comment]
我使用的是星界云内置的alas，短猫时也有这样的情况

**Comment by qyyxxx407** [comment]
哈哈哈哈哈，我也是星界的alas，那应该就是星界的问题了，但是我电脑用模拟器开荒也时常出现同样的报错

**Comment by Harribelwww** [comment]
每次新活动图开荒时大概率会遇到这个问题，log：
[2024-04-28_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141156/2024-04-28_alas.txt)

**Comment by SteveWYSism** [comment]
+1 使用的星界链的alas 新活动开荒也会出现这个问题

**Comment by Air111** [comment]
星界链好像强制用MaaTouch，有没有可能是 d512c4d 导致这个问题被暴露出来
https://github.com/MaaAssistantArknights/MaaTouch/pull/2

**Comment by qyyxxx407** [comment]
> 星界链好像强制用MaaTouch，有没有可能是 [d512c4d](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/d512c4dadf29b41d4c4a818b0f842ef71a7d5695) 导致这个问题被暴露出来 [MaaAssistantArknights/MaaTouch#2](https://github.com/MaaAssistantArknights/MaaTouch/pull/2)

应该不是，我模拟器使用的minitouch也是一样乱扫

**Comment by Air111** [comment]
> 应该不是，我模拟器使用的minitouch也是一样乱扫

发下你的log？

**Comment by qyyxxx407** [comment]
> > 应该不是，我模拟器使用的minitouch也是一样乱扫
> 
> 发下你的log？

[
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141925/log.txt)
](url)

**Comment by Air111** [comment]
> [
> [log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141925/log.txt)
> ](url)

好吧。我模拟器一直没复现出来，又看多是云手机，属实学艺不精。

**Comment by AshenMo** [comment]
我是mumu12，跟楼主遇到一样的情况，分别在2024-04-28 10:13:55.623
[2024-04-28_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15142156/2024-04-28_alas.txt)

**Comment by SteveWYSism** [comment]
> > [
> > [log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141925/log.txt)
> > ](url)
> 
> 好吧。我模拟器一直没复现出来，又看多是云手机，属实学艺不精。

是的 没办法稳定复现 使用的mumu12 在用maatouch短猫的时候大部分时候可以正常拖动视角，有时候就突然短点然后报错

**Comment by always-fan** [comment]
> > > [
> > > [log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141925/log.txt)
> > > ](url)
> > 
> > 
> > 好吧。我模拟器一直没复现出来，又看多是云手机，属实学艺不精。
> 
> 是的 没办法稳定复现 使用的mumu12 在用maatouch短猫的时候大部分时候可以正常拖动视角，有时候就突然短点然后报错

我用MUMU12，每当打完一次大世界地图，后就会出现这样的情况，跟楼主一样的log

**Comment by always-fan** [comment]
> > > > [
> > > > [log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15141925/log.txt)
> > > > ](url)
> > > 
> > > 
> > > 好吧。我模拟器一直没复现出来，又看多是云手机，属实学艺不精。
> > 
> > 
> > 是的 没办法稳定复现 使用的mumu12 在用maatouch短猫的时候大部分时候可以正常拖动视角，有时候就突然短点然后报错
> 
> 我用MUMU12，每当打完一次大世界地图，后就会出现这样的情况，跟楼主一样的log

改下模拟器的控制方案，我改成uiautomator2方式后，可以是可以了，但速度慢了很多

**Comment by xyf007** [comment]
MuMu12 下，点击方式为 minitouch 和 ADB 都遇到了同样的 SWIPE 问题，uiautomator2 可用

**Comment by methodref** [comment]
看起来最新的提交 已经处理了这个问题了
处理速度 真的很快 👍🏻
[Bug fix #3708](https://github.com/LmeSzinc/AzurLaneAutoScript/pull/3708)

**Comment by xyf007** [comment]
> 看起来最新的提交 已经处理了这个问题了 处理速度 真的很快 👍🏻 [Bug fix #3708](https://github.com/LmeSzinc/AzurLaneAutoScript/pull/3708)

好像没完全修好，我主线图依然会出现一些 `WARNING | Wrong Prediction. I4 = '2L'` 这种移动位置不准确的问题，不过没发生 MAP_SWIPE_0_0 而终止的问题了

**Comment by MoGHenry** [comment]
还是在出bug

ERROR    22:08:10.037 │ MaaTouchSyncTimeout: timed 
         out                                       
INFO     22:08:13.044 │ disconnected 127.0.0.1:5555
INFO     22:08:13.047 │ connected to 127.0.0.1:5555
INFO     22:08:13.050 │ <<< DETECT DEVICE >>>      
INFO     22:08:13.052 │ Here are the available     
         devices, copy to Alas.Emulator.Serial to  
         use it or set Alas.Emulator.Serial="auto" 
INFO     22:08:13.055 │ 127.0.0.1:5555             
INFO     22:08:13.057 │ emulator-5554              
INFO     22:08:13.059 │ <<< MAATOUCH INIT >>>      
INFO     22:08:13.070 │ [Device Orientation] 1     
         (HOME key on the right)                   
INFO     22:08:13.289 │ ^ 10 1280 720 255          
INFO     22:08:13.292 │ $ 255                      
INFO     22:08:13.295 │ MaaTouch stream connected  
INFO     22:08:13.298 │ max_contact: 10; max_x:    
         1280; max_y: 720; max_pressure: 255       
ERROR    22:08:15.419 │ MaaTouchSyncTimeout: timed 
         out                                       
CRITICAL 22:08:15.422 │ Retry swipe_maatouch()     
         failed

**Comment by TobyLi223** [comment]
NFO     08:14:17.927 │ [homo_storage] ((10, 7), [(110.307, 103.657), (1012.311, 103.657),         
         (-32.959, 600.567), (1113.057, 600.567)])                                                 
INFO     08:14:18.091 │            tile_center: 0.908 (good match)                                 
INFO     08:14:18.093 │ 0.118s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:18.095 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:18.108 │            center_loca: (5, 4)                                             
INFO     08:14:18.255 │ 0.144s         predict: 84                                                 
INFO     08:14:18.257 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:18.259 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:18.261 │ .. -- -- FL -- -- -- -- FL -- FL --                                        
INFO     08:14:18.263 │ .. -- -- -- FL -- -- FL -- -- -- ..                                        
INFO     08:14:18.265 │ .. -- FL -- -- FL -- -- -- -- -- ..                                        
INFO     08:14:18.267 │ .. -- -- -- -- -- FL FL FL -- -- ..                                        
INFO     08:14:18.269 │ .. FL -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:18.271 │ .. .. -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:18.323 │             -- -- --                                                       
INFO     08:14:18.324 │       -- -- -- -- -- -- --                                                 
INFO     08:14:18.325 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:18.327 │    -- -- -- -- QU -- -- -- --                                              
INFO     08:14:18.329 │ -- -- -- -- -- -- -- -- -- -- EN                                           
INFO     08:14:18.331 │ -- -- -- -- -- FL -- -- -- -- --                                           
INFO     08:14:18.333 │ -- -- -- -- -- -- -- -- -- -- --                                           
INFO     08:14:18.335 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:18.337 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:18.339 │       -- -- -- -- -- -- --                                                 
INFO     08:14:18.341 │             -- -- --                                                       
WARNING  08:14:18.343 │ Convert radar to local, but found multiple current fleets: [D3, I3, K3, E4,
         H4, C5, F5, G6, H6, I6, B7, D7, D8]                                                       
WARNING  08:14:18.344 │ Assuming the nearest fleet to camera canter is current fleet: D3           
INFO     08:14:18.346 │ Radar (0, -2) -> Local D1 (fleet=D3)                                       
INFO     08:14:18.348 │ Click ( 448,  106) @ D1                                                    
INFO     08:14:18.403 │ <<< WAIT UNTIL WALK STABLE >>>                                             
INFO     08:14:18.405 │ Screenshot interval set to 0.35s                                           
INFO     08:14:18.637 │            tile_center: 0.908 (good match)                                 
INFO     08:14:18.640 │ 0.111s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:18.642 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:18.660 │            center_loca: (5, 4)                                             
INFO     08:14:18.662 │ [homo_loca] [54 58]                                                        
WARNING  08:14:18.850 │ Map walk out of step.                                                      
INFO     08:14:22.080 │            tile_center: 0.908 (good match)                                 
INFO     08:14:22.082 │ 0.091s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:22.084 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:22.094 │            center_loca: (5, 4)                                             
INFO     08:14:22.097 │ [homo_loca] [54 58]                                                        
INFO     08:14:22.449 │            tile_center: 0.908 (good match)                                 
INFO     08:14:22.452 │ 0.094s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:22.454 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:22.465 │            center_loca: (5, 4)                                             
INFO     08:14:22.467 │ [homo_loca] [54 58]                                                        
INFO     08:14:22.822 │            tile_center: 0.925 (good match)                                 
INFO     08:14:22.824 │ 0.093s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:22.826 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:22.841 │            center_loca: (5, 4)                                             
INFO     08:14:22.842 │ [homo_loca] [54 57]                                                        
INFO     08:14:23.173 │            tile_center: 0.908 (good match)                                 
INFO     08:14:23.175 │ 0.101s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:23.177 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:23.187 │            center_loca: (5, 4)                                             
INFO     08:14:23.188 │ [homo_loca] [54 57]                                                        
INFO     08:14:23.189 │ Walk stabled, result:                                                      
INFO     08:14:23.190 │ Screenshot interval set to 0.2s                                            
INFO     08:14:23.298 │            tile_center: 0.908 (good match)                                 
INFO     08:14:23.301 │ 0.103s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:23.302 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:23.313 │            center_loca: (5, 4)                                             
INFO     08:14:23.424 │ 0.109s         predict: 84                                                 
INFO     08:14:23.426 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:23.427 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:23.429 │ .. -- -- FL -- -- -- -- FL -- FL --                                        
INFO     08:14:23.430 │ .. -- -- -- FL -- -- FL -- -- -- ..                                        
INFO     08:14:23.432 │ .. -- FL -- -- FL -- -- -- -- -- ..                                        
INFO     08:14:23.433 │ .. -- -- -- -- -- FL FL FL -- -- ..                                        
INFO     08:14:23.435 │ .. FL -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:23.436 │ .. .. -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:23.480 │             -- -- --                                                       
INFO     08:14:23.481 │       -- -- -- -- -- -- --                                                 
INFO     08:14:23.482 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:23.483 │    -- -- -- -- QU -- -- -- --                                              
INFO     08:14:23.484 │ -- -- -- -- -- -- -- -- -- -- EN                                           
INFO     08:14:23.485 │ -- -- -- -- -- FL -- -- -- -- --                                           
INFO     08:14:23.487 │ -- -- -- -- -- -- -- -- -- -- --                                           
INFO     08:14:23.489 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:23.491 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:23.492 │       -- -- -- -- -- -- --                                                 
INFO     08:14:23.493 │             -- -- --                                                       
WARNING  08:14:23.495 │ Convert radar to local, but found multiple current fleets: [D3, I3, K3, E4,
         H4, C5, F5, G6, H6, I6, B7, D7, D8]                                                       
WARNING  08:14:23.498 │ Assuming the nearest fleet to camera canter is current fleet: D3           
INFO     08:14:23.500 │ Radar (0, -2) -> Local D1 (fleet=D3)                                       
INFO     08:14:23.501 │ Click ( 464,  111) @ D1                                                    
INFO     08:14:23.557 │ <<< WAIT UNTIL WALK STABLE >>>                                             
INFO     08:14:23.558 │ Screenshot interval set to 0.35s                                           
INFO     08:14:23.734 │            tile_center: 0.908 (good match)                                 
INFO     08:14:23.737 │ 0.095s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:23.739 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:23.748 │            center_loca: (5, 4)                                             
INFO     08:14:23.750 │ [homo_loca] [54 57]                                                        
WARNING  08:14:23.976 │ Map walk out of step.                                                      
INFO     08:14:27.245 │            tile_center: 0.908 (good match)                                 
INFO     08:14:27.247 │ 0.093s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:27.248 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:27.259 │            center_loca: (5, 4)                                             
INFO     08:14:27.261 │ [homo_loca] [54 57]                                                        
INFO     08:14:27.586 │            tile_center: 0.922 (good match)                                 
INFO     08:14:27.589 │ 0.095s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:27.591 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:27.602 │            center_loca: (5, 4)                                             
INFO     08:14:27.604 │ [homo_loca] [54 58]                                                        
INFO     08:14:27.960 │            tile_center: 0.883 (7 matches)                                  
INFO     08:14:27.963 │ 0.113s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:27.965 │ Edges:       homo_loca: ( 53,  57)                                         
INFO     08:14:27.975 │            center_loca: (5, 4)                                             
INFO     08:14:27.978 │ [homo_loca] [53.49215551 57.99994125]                                      
INFO     08:14:28.295 │            tile_center: 0.908 (good match)                                 
INFO     08:14:28.300 │ 0.094s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:28.301 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:28.312 │            center_loca: (5, 4)                                             
INFO     08:14:28.314 │ [homo_loca] [54 58]                                                        
INFO     08:14:28.315 │ Walk stabled, result:                                                      
INFO     08:14:28.316 │ Screenshot interval set to 0.2s                                            
INFO     08:14:28.416 │            tile_center: 0.908 (good match)                                 
INFO     08:14:28.419 │ 0.095s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:28.420 │ Edges:       homo_loca: ( 54,  58)                                         
INFO     08:14:28.431 │            center_loca: (5, 4)                                             
INFO     08:14:28.542 │ 0.107s         predict: 84                                                 
INFO     08:14:28.542 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:28.544 │ -- -- -- -- -- -- -- -- -- -- -- --                                        
INFO     08:14:28.546 │ .. -- -- FL -- -- -- -- FL -- FL --                                        
INFO     08:14:28.547 │ .. -- -- -- -- -- -- FL -- -- -- ..                                        
INFO     08:14:28.549 │ .. -- FL -- -- FL -- -- -- -- -- ..                                        
INFO     08:14:28.550 │ .. -- -- -- -- -- -- FL FL -- -- ..                                        
INFO     08:14:28.551 │ .. FL -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:28.552 │ .. .. -- FL -- -- -- -- -- -- -- ..                                        
INFO     08:14:28.603 │             -- -- --                                                       
INFO     08:14:28.604 │       -- -- -- -- -- -- --                                                 
INFO     08:14:28.605 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:28.606 │    -- -- -- -- QU -- -- -- --                                              
INFO     08:14:28.608 │ -- -- -- -- -- -- -- -- -- -- EN                                           
INFO     08:14:28.609 │ -- -- -- -- -- FL -- -- -- -- --                                           
INFO     08:14:28.611 │ -- -- -- -- -- -- -- -- -- -- --                                           
INFO     08:14:28.613 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:28.614 │    -- -- -- -- -- -- -- -- --                                              
INFO     08:14:28.617 │       -- -- -- -- -- -- --                                                 
INFO     08:14:28.618 │             -- -- --                                                       
WARNING  08:14:28.620 │ Convert radar to local, but found multiple current fleets: [D3, I3, K3, H4,
         C5, F5, H6, I6, B7, D7, D8]                                                               
WARNING  08:14:28.622 │ Assuming the nearest fleet to camera canter is current fleet: D3           
INFO     08:14:28.624 │ Radar (0, -2) -> Local D1 (fleet=D3)                                       
INFO     08:14:28.625 │ Click ( 464,   90) @ D1                                                    
INFO     08:14:28.681 │ <<< WAIT UNTIL WALK STABLE >>>                                             
INFO     08:14:28.683 │ Screenshot interval set to 0.35s                                           
INFO     08:14:28.877 │            tile_center: 0.912 (good match)                                 
INFO     08:14:28.880 │ 0.095s      edge_lines: 0 hori, 0 vert                                     
INFO     08:14:28.882 │ Edges:       homo_loca: ( 54,  57)                                         
INFO     08:14:28.893 │            center_loca: (5, 4)                                             
INFO     08:14:28.895 │ [homo_loca] [54 57]                                                        
WARNING  08:14:29.110 │ Map walk out of step.                                                      
深渊海域也是这样？大概，哪怕点击都点击不了正确的位置，

**Comment by GOODGINKO** [comment]
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15183438/log.txt)
![screenshot-1714620448091](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/162420328/54602b8c-6271-4648-b304-74bf097659b9)
设备星界链ALAS版
MAP_SWIPE_0_0报错不再出现
大世界需要拖动屏幕的任务，在运行一段时间后会出现MaaTouchSyncTimeout: timed out错误导致alas中止

**Comment by freesrz93** [comment]
> 星界链好像强制用MaaTouch，有没有可能是 [d512c4d](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/d512c4dadf29b41d4c4a818b0f842ef71a7d5695) 导致这个问题被暴露出来 [MaaAssistantArknights/MaaTouch#2](https://github.com/MaaAssistantArknights/MaaTouch/pull/2)

星界链 + minitouch 报同样错误
取消注释 https://github.com/LmeSzinc/AzurLaneAutoScript/blob/d512c4dadf29b41d4c4a818b0f842ef71a7d5695/module/map/camera.py#L61 后恢复正常
