### ISSUE TITLE
活动日常增加作战档案

### ISSUE THREAD

**Issue by CNLSL** [LmeSzinc/AzurLaneAutoScript#3705]
### 你的功能请求是否与问题有关？

为活动日常增加作战档案，每天自动进行4场指定作战档案

**Comment by LmeSzinc** [comment]
启用作战档案任务
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/37934724/37247974-6365-46c1-9e21-bad375f00a7b)
