### ISSUE TITLE
Script stuck on fleet selection

### ISSUE THREAD

**Issue by gentoolman** [LmeSzinc/AzurLaneAutoScript#3718]
### Before you asking

- [X] I have searched the existing issues
- [X] I spend at least 5 minutes for thinking and preparing
- [X] I checked Frequently Asked Questions (FAQ) in Wiki page
- [X] I am using the latest version of Alas

### Describe the bug

As soon as I configured and started the main farming or anything else regarding farmin, the script gets stuck upon selecting the fleet. I checked the configs and even the config files but could not find anything. Any ideas for this? Do the fleets need certain names?

### To Reproduce

1. Activate main farming
2. Start the script
3. Fleet window gets opened
4. No fleet selection

### Expected behavior

The correct fleet gets selected and the scripts keeps on working

**Comment by guoh064** [comment]
try unlocking at least four fleets

**Comment by LmeSzinc** [comment]
## How to Report Bugs

Spend at least 5 minutes for thinking and preparing, before someone spend his/her 5 minutes to help you. Issues like "Why isn't running", "Why stuck here" will not be answered.

- Upload error logs under log/error, which include log.txt and recent screenshots. If it's an unexpected behavior not an error, provide today's log under log and at least one screenshot.

**Comment by gentoolman** [comment]
> try unlocking at least four fleets

This one worked, thank you
