### ISSUE TITLE
希望可以添加一个设置一队二队出击几次就换队的功能

### ISSUE THREAD

**Issue by he110W0r1d-shell** [LmeSzinc/AzurLaneAutoScript#372]
例如一队出击5次切换成二队继续打，不然可能出现5/5的弹药打完了之后，在伤害减少的情况下继续打导致翻车的情况。（好像5次打完了之后继续打还会加速消耗心情值？）

**Comment by LmeSzinc** [comment]
不会添加这个功能.

1. 一队道中一队BOSS, 道中队顶着空弹打完道中, BOSS队只打BOSS是这个游戏大多数人的玩法. 
BOSS比道中难, 所以BOSS队的油耗通常较高, 用BOSS队打道中会增加油耗. 道中队强调续航, BOSS队强调输出, 用无续航的BOSS队打道中会损血较多, 增加BOSS队的翻车概率.
2. Alas 是为了能实现复杂战斗逻辑 (比如减少BOSS队被敌人堵住的概率) 而设计的. 每场战斗的逻辑由地图文件控制, 很难靠几个选项描述. 实现减少BOSS队被敌人堵住的原理是, 用BOSS队去踩住敌人刷新点, 或者尽量移动到BOSS刷新点. 这里就包含队伍切换, 另外增加队伍切换的设置很难保证对现有逻辑的兼容.
3. 有自己独特玩法的使用者, 需要在 `campaign/<活动名称>/<地图名称>.py` 中自己编写战斗逻辑. 同时 Alas 提供相关的函数.
例如 `self.clear_enemy()` 表示使用当前队伍打一个任意敌人, 没有敌人的话就什么都不做.
如果需要指定BOSS队打, 就是 `self.fleet_2.clear_enemy()`
如果只是需要切换到BOSS队, 就 `self.fleet_2.switch_to()`.
4. 空弹出击不会增加心情消耗, 心情系统的详细介绍在 [WIKI的心情页面](https://wiki.biligame.com/blhx/%E5%BF%83%E6%83%85)
