### ISSUE TITLE
wiki/reward_shop_filter_string里的SpecializedCore翻译错误

### ISSUE THREAD

**Issue by LivP0810** [LmeSzinc/AzurLaneAutoScript#3728]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/reward_shop_filter_string 里的Medal shop 兑换商店，SpecializedCore 	Specialized Core 	特装核心，国服的翻译是特装原型

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Air111** [comment]
看得懂就行，就连官方都没统一命名规范，detail/info，arrangement code/gear code

**Comment by guoh064** [comment]
https://azurlane.koumakan.jp/wiki/Shops#Specialized_Core_Collection_Plan

**Comment by Air111** [comment]
已修改
