### ISSUE TITLE
reward loop wait的作用是啥

### ISSUE THREAD

**Issue by wqdasd31** [LmeSzinc/AzurLaneAutoScript#374]
2021-03-03 21:54:57.477 | INFO | Reward loop wait
2021-03-03 21:54:57.477 | INFO | [Reward_loop_wait] 25 min 31 sec
感觉每次出现都得等很久。。

**Comment by LmeSzinc** [comment]
[FAQ Why Alas get stuck in reward loop 为什么Alas卡在收获里](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#why-alas-get-stuck-in-reward-loop-%E4%B8%BA%E4%BB%80%E4%B9%88alas%E5%8D%A1%E5%9C%A8%E6%94%B6%E8%8E%B7%E9%87%8C)
