### ISSUE TITLE
请问是否能开机自启？

### ISSUE THREAD

**Issue by fhwhite** [LmeSzinc/AzurLaneAutoScript#3743]
### 你的功能请求是否与问题有关？

不知道alas是否有自启功能，就是不用点启动按钮，alas启动后自动开始运行

我设置的电脑启动后，延迟1分钟启动游戏，延迟2分钟启动alas，然后用笨办法最小化最大化alas，识别启动按钮，点击，但不知道是其他自启程序影响还是什么情况，最近经常不点启动，想来问问，是否有官方的自启方法

**Comment by Air111** [comment]
修改`deploy.yaml`可以在启动alas后自动运行
 https://github.com/LmeSzinc/AzurLaneAutoScript/blob/eb119a33692b70dc1c3f6b7cef4000b485f2cbdb/config/deploy.template.yaml#L155-L159

**Comment by fhwhite** [comment]
> 修改`deploy.yaml`可以在启动alas后自动运行
> 
> https://github.com/LmeSzinc/AzurLaneAutoScript/blob/eb119a33692b70dc1c3f6b7cef4000b485f2cbdb/config/deploy.template.yaml#L155-L159

谢谢大佬，搞定了，终于可以自启

**Comment by Dq8515** [comment]
能问下怎么自启的吗？用subprocess库完全启动不了，os.startfile启动会报错，找不到配置文件

**Comment by Dq8515** [comment]
> 能问下怎么自启的吗？用subprocess库完全启动不了，os.startfile启动会报错，找不到配置文件

目前通过改console.bat，直接启动console.bat解决了
