### ISSUE TITLE
短猫相接老是自动开启

### ISSUE THREAD

**Issue by XHBGDXX** [LmeSzinc/AzurLaneAutoScript#3749]
每次启动程序后,队列里面自动添加短猫相接,并且有时候把启动的勾选框取消了,显示保存设置后,它还是会自动把启动框勾选上.

**Comment by methodref** [comment]
游戏的机制 + 最大化收益 + 可持续进行
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2117#issuecomment-1382723790

**Comment by XHBGDXX** [comment]
问题是有时候关不掉啊,把启动的勾选框取消了推出设置界面,他又自动启动了

**Comment by XHBGDXX** [comment]
> 游戏的机制 + 最大化收益 + 可持续进行 [#2117 （评论）](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2117#issuecomment-1382723790)

问题是有时候关不掉啊,把启动的勾选框取消了,退出设置界面他又莫名其妙的自动启动了

**Comment by methodref** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53255854/2e38b305-ea8c-4c56-8b55-59ef0152e360)
关闭侵蚀1练级
