### ISSUE TITLE
增加windows平台后台启动脚本

### ISSUE THREAD

**Issue by steelonion** [LmeSzinc/AzurLaneAutoScript#3750]
### 你的功能请求是否与问题有关？

当前Release包中的console.bat会在配置完成环境变量后拉起一个交互式命令提示符，无法集成进其他启动脚本中

### 解决方案

添加一个后台程序启动脚本，使用目录内的解释器直接拉起`gui.py`，方便后续集成

### 其他内容

- 目前我在使用中已经修改console.bat，用来达到开机后自动顺序拉起模拟器和Alas后台程序的目的
- N100平台配合bluestacks安卓7模拟器有模拟器死机案例，不想每次外接显示器鼠标重启所以才会有这个需求
- 换bluestacks安卓11模拟器后稳定性问题解决，原因不明😂

**Comment by Ashe428** [comment]
我用bs安卓11在opengl和vulkan模式下会卡死，唯有dx不会，但是dx会有聊天栏和装备界面ui错误的情况。不知道你那边有没有同样的问题。

**Comment by steelonion** [comment]
> 我用bs安卓11在opengl和vulkan模式下会卡死，唯有dx不会，但是dx会有聊天栏和装备界面ui错误的情况。不知道你那边有没有同样的问题。

安卓11没有出现过卡死的现象

**Comment by Ashe428** [comment]
> > 我用bs安卓11在opengl和vulkan模式下会卡死，唯有dx不会，但是dx会有聊天栏和装备界面ui错误的情况。不知道你那边有没有同样的问题。
> 
> 安卓11没有出现过卡死的现象

可否发一下硬件配置和模拟器设置参考一下？

**Comment by LmeSzinc** [comment]
`.../python.exe --run alas`

命令行启动参数：
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/d20886131ebecf28ef9787ef5f377ff8d22edd9c/gui.py#L43-L48

**Comment by steelonion** [comment]
> > > 我用bs安卓11在opengl和vulkan模式下会卡死，唯有dx不会，但是dx会有聊天栏和装备界面ui错误的情况。不知道你那边有没有同样的问题。
> > 
> > 
> > 安卓11没有出现过卡死的现象
> 
> 可否发一下硬件配置和模拟器设置参考一下？

n100+16G
现在换mumu12模拟器了，蓝碟大世界不太稳定
