### ISSUE TITLE
New UI | 新界面

### ISSUE THREAD

**Issue by SaarChaffee** [LmeSzinc/AzurLaneAutoScript#3768]
关闭【设置】-【选项】-【使用新版主界面】以正常使用 Alas
![6123a109d59b2de5165437cf7ad76460](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53519746/0c9b00a9-24d7-44e7-9f98-8037ba062ede)

**Comment by SaarChaffee** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/53519746/9f6118f0-401f-473c-96ea-212a6908ddea)

**Comment by K1NSA** [comment]
原来是换UI了吗
我说怎么半天弄不好，晕了
