### ISSUE TITLE
需要新ui适配

### ISSUE THREAD

**Issue by ShinoriWHite** [LmeSzinc/AzurLaneAutoScript#3769]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

大版本更新后图像识别无法适配最新的ui，导致系统罢工

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Emokable** [comment]
设置里可以切回旧UI先用着

**Comment by HS7097** [comment]
> 设置里可以切回旧UI先用着

新UI卡死，打开左侧任务汇总之后就没有反应了
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                           COMMISSION                                                           
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
INFO     20:17:50.410 │ [Device Orientation] 0 (Normal)                                                                         
INFO     20:17:50.411 │ Create forward: ForwardItem(serial='127.0.0.1:5615', local='tcp:20727',                                 
         remote='localabstract:minitouch')                                                                                      
INFO     20:17:50.425 │ v 1                                                                                                     
INFO     20:17:50.426 │ ^ 2 32767 32767 0                                                                                       
INFO     20:17:50.426 │ $ 27343                                                                                                 
INFO     20:17:50.427 │ minitouch running on port: 20727, pid: 27343                                                            
INFO     20:17:50.428 │ max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0                                             
INFO     20:17:50.482 │ [Screen_size] 1280x720                                                                                  
INFO     20:17:50.490 │ early_ocr_import start                                                                                  
INFO     20:17:50.491 │ <<< UI ENSURE >>>                                                                                       
INFO     20:17:50.492 │ UI get current page                                                                                     
INFO     20:17:50.493 │ Loading OCR dependencies                                                                                
INFO     20:17:50.754 │ [UI] page_reward                                                                                        
INFO     20:17:50.756 │ Already at page_reward                                                                                  
INFO     20:17:50.757 │ <<< REWARD RECEIVE >>>                                                                                  
INFO     20:17:51.152 │ early_ocr_import finish                                                                                 
INFO     20:17:57.064 │ Click (  23,  153) @ MAIN_GOTO_REWARD      

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/103177863/a137797a-7817-456d-aff6-ebb0b5e43dcc)

**Comment by Arcelibs** [comment]
同上，切回舊UI滑出就卡
═══════════════════════════════════════════════════════════════════════════════════
                                    COMMISSION                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     21:02:08.166 │ [nemud.app_keep_alive]                                     
INFO     21:02:08.167 │ Reuse forward: ForwardItem(serial='127.0.0.1:5555',        
         local='tcp:20997', remote='tcp:53516')                                    
INFO     21:02:08.168 │ [Device Orientation] 0 (Normal)                            
INFO     21:02:08.170 │ Reuse forward: ForwardItem(serial='127.0.0.1:5555',        
         local='tcp:20471', remote='localabstract:minitouch')                      
INFO     21:02:08.171 │ v 1                                                        
INFO     21:02:08.172 │ ^ 2 32767 32767 0                                          
INFO     21:02:08.173 │ $ 4683                                                     
INFO     21:02:08.174 │ minitouch running on port: 20471, pid: 4683                
INFO     21:02:08.174 │ max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
INFO     21:02:08.222 │ [Screen_size] 1280x720                                     
INFO     21:02:08.365 │ early_ocr_import call                                      
INFO     21:02:08.366 │ early_ocr_import start                                     
INFO     21:02:08.366 │ <<< UI ENSURE >>>                                          
INFO     21:02:08.368 │ UI get current page                                        
INFO     21:02:08.368 │ Loading OCR dependencies                                   
INFO     21:02:08.399 │ [UI] page_main                                             
INFO     21:02:08.400 │ Goto page_reward                                           
INFO     21:02:08.402 │ <<< UI GOTO PAGE_REWARD >>>                                
INFO     21:02:08.435 │ Page switch: page_main -> page_reward                      
INFO     21:02:08.441 │ Click (  19,  164) @ MAIN_GOTO_REWARD                      
INFO     21:02:08.859 │ early_ocr_import finish                                    
INFO     21:02:09.241 │ Page arrive: page_reward                                   
INFO     21:02:09.243 │ <<< REWARD RECEIVE >>>    


![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/49543451/73fea7f5-5150-4631-9077-fd2d09ff9183)

**Comment by imRhoAias** [comment]
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/133833496/19db87e0-a448-4395-8ed2-bf59ea986f0b)
我也卡哩

**Comment by Emniceay** [comment]
> 设置里可以切回旧UI先用着

不太行，会自动待机 然后就会进入报错

**Comment by Emokable** [comment]
> > 设置里可以切回旧UI先用着
> 
> 不太行，会自动待机 然后就会进入报错

还真是，希望早点适配新UI

**Comment by ShinoriWHite** [comment]
感谢评论区指引
附暂时解决方法汇总：在设置-选项栏内关闭“使用新版主界面”与“主界面屏幕常亮”两个选项。
不过还是希望能有新ui适配。
