### ISSUE TITLE
日服旧UI无法接委托和战术学院

### ISSUE THREAD

**Issue by Huisei1** [LmeSzinc/AzurLaneAutoScript#3772]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

<img width="621" alt="Snipaste_2024-05-21_21-33-30" src="https://github.com/LmeSzinc/AzurLaneAutoScript/assets/109328479/6ab79a9e-1330-4f5e-bd5d-fecb9890a397">
日服委托界面疑似下移，ALAS无法点击委托、战术学院，点击位置偏上，然后一直卡在这里直到重启，手动点进委托、战术学院界面可以正常运行

### 相关 Logs

```Text
INFO     21:30:46.925 │ <<< UI ENSURE >>>                                          
INFO     21:30:46.928 │ UI get current page                                        
INFO     21:30:46.935 │ [UI] page_main                                             
INFO     21:30:46.938 │ Goto page_reward                                           
INFO     21:30:46.941 │ <<< UI GOTO PAGE_REWARD >>>                                
INFO     21:30:46.950 │ Page switch: page_main -> page_reward                      
INFO     21:30:46.952 │ Click (  40,  180) @ MAIN_GOTO_REWARD                      
INFO     21:30:52.562 │ Page switch: page_main -> page_reward                      
INFO     21:30:52.565 │ Click (  32,  164) @ MAIN_GOTO_REWARD                      
INFO     21:30:53.715 │ Page arrive: page_reward
```

**Comment by crmmc** [comment]
同样遇到,在领取委托时,因为主界面侧边栏位置改变导致脚本点击的位置不正确,点击不到按钮,任务无法进行下一步,报错退出

**Comment by Air111** [comment]
两个issue总共五个人怎么就没一个发完整log

**Comment by Air111** [comment]
@Arcelibs 你是到REWARD RECEIVE之后没反应手动停止了吗

**Comment by Arcelibs** [comment]
> @Arcelibs 你是到REWARD RECEIVE之后没反应手动停止了吗

到REWARD RECEIVE就卡住沒往下繼續執行了，跟樓主的圖一樣

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/49543451/6fc5a3c7-6315-4d9c-b5db-e6f42810b8a3)

**Comment by Air111** [comment]
应该等（约1分钟）到alas报错，然后把./log/error/xxx整个上传。另外，下载下来4张图片没有一张是1280x720的，是我的问题吗？

算了，等日服的dev修吧

**Comment by Arcelibs** [comment]
> 应该等（约1分钟）到alas报错，然后把./log/error/xxx整个上传。另外，下载下来4张图片没有一张是1280x720的，是我的问题吗？
> 
> 算了，等日服的dev修吧

久等了 error log的圖片我也附在裡面了
[1716307428966-errorlog.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15392512/1716307428966-errorlog.zip)

**Comment by Huisei1** [comment]
> 应该等（约1分钟）到alas报错，然后把./log/error/xxx整个上传。另外，下载下来4张图片没有一张是1280x720的，是我的问题吗？
> 
> 算了，等日服的dev修吧

INFO     00:09:36.045 │ <<< UI ENSURE >>>                                          
INFO     00:09:36.047 │ UI get current page                                        
INFO     00:09:36.065 │ [UI] page_event_list                                       
INFO     00:09:36.067 │ Goto page_reward                                           
INFO     00:09:36.068 │ <<< UI GOTO PAGE_REWARD >>>                                
INFO     00:09:36.088 │ Page switch: page_event_list -> page_main                  
INFO     00:09:36.090 │ Click (1251,   34) @ GOTO_MAIN                             
INFO     00:09:36.804 │ UI additional: EVENT_LIST_CHECK -> GOTO_MAIN               
INFO     00:09:36.807 │ Click (1245,   22) @ GOTO_MAIN                             
INFO     00:09:37.432 │ Page switch: page_event_list -> page_main                  
INFO     00:09:37.434 │ Click (1234,   35) @ GOTO_MAIN                             
INFO     00:09:38.113 │ UI additional: EVENT_LIST_CHECK -> GOTO_MAIN               
INFO     00:09:38.444 │ Click (1020,  668) @ GET_ITEMS_1                           
INFO     00:09:41.486 │ Click (1036,  645) @ GET_ITEMS_1                           
INFO     00:09:42.543 │ Page switch: page_event_list -> page_main                  
INFO     00:09:42.546 │ Click (1239,   33) @ GOTO_MAIN                             
INFO     00:09:43.291 │ UI additional: EVENT_LIST_CHECK -> GOTO_MAIN               
INFO     00:09:43.295 │ Click (1251,   27) @ GOTO_MAIN                             
INFO     00:09:43.900 │ Page switch: page_main -> page_reward                      
INFO     00:09:43.902 │ Click (  19,  172) @ MAIN_GOTO_REWARD                      
INFO     00:09:44.888 │ Click (1180,   91) @ LOGIN_ANNOUNCE_2                      
INFO     00:09:49.205 │ Page switch: page_main -> page_reward                      
INFO     00:09:49.207 │ Click (  15,  170) @ MAIN_GOTO_REWARD                      
INFO     00:09:50.258 │ Page arrive: page_reward                                   
INFO     00:09:50.261 │ <<< REWARD RECEIVE >>>                                     
INFO     00:12:49.358 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L151 run_process()                                     
                    alas.py L514 loop()                                            
                    alas.py  L68 run()                                             
                    alas.py L189 commission()                                      
              commission.py L558 run()                                             
              commission.py L516 commission_receive()                              
                  device.py L161 screenshot()                                      
                  device.py L219 stuck_record_check()                              
                  device.py  L40 show_function_call()                              
WARNING  00:12:49.362 │ Wait too long                                              
WARNING  00:12:49.364 │ Waiting for {'OS_CHECK', 'BATTLE_PASS_CHECK', 'WITHDRAW',  
         'GET_ITEMS_3', 'SUPPLY_PACK_CHECK', 'GAME_TIPS', 'MAP_PREPARATION',       
         'PLAYER_CHECK', 'REWARD_GOTO_COMMISSION', 'RPG_GOTO_STAGE',               
         'MEOWFFICER_INFO', 'LOGIN_CHECK', 'RPG_STATUS_POPUP', 'SP_CHECK',         
         'CAMPAIGN_MENU_CHECK', 'STORY_CLOSE', 'DAILY_CHECK', 'POPUP_CANCEL',      
         'STORAGE_CHECK', 'DORM_CHECK', 'MONTHLY_PASS_NOTICE', 'RAID_CHECK',       
         'EXCHANGE_CHECK', 'CAMPAIGN_CHECK', 'GET_MISSION', 'GET_ITEMS_2',         
         'GET_SHIP', 'GUILD_CHECK', 'BATTLE_PASS_NOTICE', 'DORM_INFO',             
         'RAID_FLEET_PREPARATION', 'GET_ITEMS_1', 'FLEET_PREPARATION',             
         'EVENT_LIST_CHECK', 'GUILD_POPUP_CONFIRM', 'RESET_FLEET_PREPARATION',     
         'RPG_GOTO_STORY', 'RESET_TICKET_POPUP', 'GAME_ROOM_CHECK',                
         'MEOWFFICER_BUY', 'MAINTENANCE_ANNOUNCE', 'AUTO_SEARCH_MENU_EXIT',        
         'EVENT_CHECK', 'PURCHASE_POPUP', 'DORM_FEED_CANCEL', 'COMMISSION_CHECK',  
         'MEOWFFICER_CHECK', 'EXP_INFO_S_REWARD', 'COALITION_CHECK', 'REWARD_1',   
         'TACTICAL_CHECK', 'LOGIN_ANNOUNCE_2', 'BUILD_CHECK',                      
         'EXERCISE_PREPARATION', 'META_CHECK', 'DORMMENU_CHECK', 'RESEARCH_CHECK', 
         'LOGIN_RETURN_SIGN', 'SHIPYARD_CHECK', 'RPG_LEAVE_CITY', 'ACADEMY_CHECK', 
         'AUTO_SEARCH_REWARD', 'MISSION_CHECK', 'MAIN_GOTO_FLEET', 'SHOP_CHECK',   
         'MUNITIONS_CHECK', 'FLEET_CHECK', 'DORM_TROPHY_CONFIRM', 'EXERCISE_CHECK',
         'LOGIN_ANNOUNCE', 'WAR_ARCHIVES_CHECK', 'RESHMENU_CHECK', 'REWARD_CHECK', 
         'STORY_SKIP_3'}                                                           
INFO     00:12:49.389 │ [Package_name] com.YoStarJP.AzurLane                       
ERROR    00:12:49.392 │ GameStuckError: Wait too long                              
WARNING  00:12:49.396 │ Saving error: ./log/error/1716307969396                    
WARNING  00:12:49.682 │ Game stuck, com.YoStarJP.AzurLane will be restarted in 10  
         seconds                                                                   
WARNING  00:12:49.684 │ If you are playing by hand, please stop Alas               
INFO     00:12:49.686 │ Task call: Restart                                         
INFO     00:12:49.703 │ Bind task ['General', 'Alas', 'Commission']                
INFO     00:12:49.705 │ Save config ./config\日服.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2024, 5, 22, 0, 12, 49),      
         Restart.Scheduler.Enable=True                                             
INFO     00:12:59.718 │ Scheduler: End task `Commission`                           
INFO     00:12:59.720 │ [Server] jp                                                
INFO     00:12:59.750 │ Bind task ['General', 'Alas']                              
INFO     00:12:59.754 │ Pending tasks: ['Restart', 'Commission', 'Research',       
         'Exercise', 'Dorm', 'Guild', 'Gacha', 'Reward', 'ShopFrequent',           
         'ShopOnce', 'Freebies', 'Minigame', 'OpsiAshBeacon', 'OpsiDaily',         
         'OpsiShop', 'OpsiAbyssal', 'OpsiStronghold', 'OpsiObscure', 'OpsiArchive',
         'Daily', 'Hard', 'OpsiAshAssist', 'OpsiMeowfficerFarming',                
         'OpsiHazard1Leveling']                                                    
INFO     00:12:59.758 │ [Task] Restart (Enable, 2024-05-22 00:12:49)               
INFO     00:12:59.760 │ Bind task ['General', 'Alas', 'Restart']                   
INFO     00:12:59.770 │ Scheduler: Start task `Restart`                    
![Screenshot_2024 05 22_00 11 25 286](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/109328479/7a75b3fe-f80c-4b48-a741-348d0faf5a22)
这是完整的error log和1080*720的截图

**Comment by Air111** [comment]
需要一张委托收完显示“确认”的截图

**Comment by Arcelibs** [comment]
> 需要一张委托收完显示“确认”的截图

這張可以嗎
![Screenshot_2024 05 22_01 06 17 194](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/49543451/a80d27fa-b6a3-444c-a474-0859581be303)

**Comment by Air111** [comment]
> 這張可以嗎

是指收获界面点击“完成”之后。不必麻烦了，我看discord有人发了，应该很快就会修
