### ISSUE TITLE
跑B，D图报错

### ISSUE THREAD

**Issue by laiwei-f** [LmeSzinc/AzurLaneAutoScript#3777]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

B,D图报错
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/130133950/7982a95e-2f11-4819-b64a-6a891264799b)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/130133950/cdd2ad3d-922d-42db-8399-c34e79cead63)

**Comment by Air111** [comment]
bd图中午12点才开放，麻烦先看一下最新的commit时间？

**Comment by laiwei-f** [comment]
😂😭

**Comment by xinlei13** [comment]
b,d图还没训练呢，等更新吧
