### ISSUE TITLE
主线图和活动图都无法出击

### ISSUE THREAD

**Issue by 1127626014** [LmeSzinc/AzurLaneAutoScript#3778]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

主线图和活动图都会卡在这里。我在FAQ和issue也没看到解决办法

### 如何复现

1. 前往 '活动图'
2. 点击 'AI地图'
3. 滑动到 '出击界面'
4. 出现问题

### 截图

![2024-05-22_16-03-11-980395](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/57735361/36b2dd90-34b3-4073-ad1d-0b480d39fb5b)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15400381/log.txt)

**Comment by MegumiN152** [comment]
一样+1

**Comment by JOYACEpoor** [comment]
+1,表现为一直在点击编队的选择按钮

**Comment by NERUI** [comment]
编队要开到第四个还是第五个才能正常使用主线图和活动图出击功能

**Comment by JOYACEpoor** [comment]
> 编队要开到第四个还是第五个才能正常使用主线图和活动图出击功能

测试了，是真的，开了第四个编队就正常了

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/3429#issuecomment-1897768067
