### ISSUE TITLE
困难图已通关，但未找到B, D图文件

### ISSUE THREAD

**Issue by xianl1** [LmeSzinc/AzurLaneAutoScript#3781]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

已确认B，D图已开放；
在未通关A，B图的情况下通关C，D图，报错找不到地图文件。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![Screenshot_20240522-234354](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/83954447/931899fb-1b88-41a2-80c6-8faa6a3fd414)
![Screenshot_20240522-234340](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/83954447/1eb1d5e1-f2ba-4500-b400-d093577f73de)
![屏幕截图 2024-05-22 234314](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/83954447/35d16a39-bee7-41d3-9c2b-acd4b9247f9a)

**Comment by JovLuc** [comment]
没更，等着

**Comment by xianl1** [comment]
> 没更，等着

谢谢。

**Comment by sgds24** [comment]
我也遇到这个问题了，但是我是B和D无法识别
![2024-05-23_15-36-46-154613](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/74462141/ca033e63-d6d8-490f-9f23-c9b1a8781107)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15413401/log.txt)

**Comment by sgds24** [comment]
> 我也遇到这个问题了，但是我是B和D无法识别 ![2024-05-23_15-36-46-154613](https://private-user-images.githubusercontent.com/74462141/333086933-ca033e63-d6d8-490f-9f23-c9b1a8781107.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTA2NTIsIm5iZiI6MTcxNjQ1MDM1MiwicGF0aCI6Ii83NDQ2MjE0MS8zMzMwODY5MzMtY2EwMzNlNjMtZDZkOC00OTBmLTlmMjMtYzliMWE4NzgxMTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA3NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlODMxMWRkNmEyNjk2NmM3NjRlOGZjZGJkNmUzMWEzMTYzMDgwYjMxMzM5ZDdhODAwMWI2MzQ3N2Y0YTUzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZ_ArMsgdVUtNrlWHpAMHaWKWDAPL731nSP9ophfrLU) [log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/15413401/log.txt)

是我设置问题
