### ISSUE TITLE
希望增加一个自律失败后自动中断任务返回主页的功能

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#3795]
### 你的功能请求是否与问题有关？

如题，现有的程序里对自律失败没有定义，3油撞大航概率翻船直接就中断整个程序运行要求人工介入了，挂一宿发现只刷了半小时不说还卡一大堆委托学院科研后宅属实难绷

### 解决方案

每隔一分钟或几分钟判别是否战斗失败，如失败则撤退返回首页，并按预先设置决定是否中断翻船任务，之类的流程？
大世界也同理，有时网络波动会卡屏，要是能判别是否正常运行并自动重启游戏就好了

**Comment by LmeSzinc** [comment]
有三次重试，能连续失败三次一定是设置有问题

**Comment by clark1091** [comment]
重试顶多只是点两下屏幕，并没把失败界面点掉结束战斗，你找个图带俩狗粮故意自律失败一次看看alas反应，必定卡在失败界面提示wait too long



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 凌晨1:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 希望增加一个自律失败后自动中断任务返回主页的功能 (Issue #3795)




 
有三次重试，能连续失败三次一定是设置有问题

**Comment by clark1091** [comment]
如果是说非锁定下血量控制这个设置的话，紧急委托没这个选项不提，这设置完也不妨碍战斗中旗舰大半血直接暴毙卡在失败界面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 凌晨1:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 希望增加一个自律失败后自动中断任务返回主页的功能 (Issue #3795)




 
有三次重试，能连续失败三次一定是设置有问题
