### ISSUE TITLE
一个更易于使用的心情设置

### ISSUE THREAD

**Issue by 156351564** [LmeSzinc/AzurLaneAutoScript#3797]
### 你的功能请求是否与问题有关？

现有的心情设置会在以下情况中导致心情计算错误
[#1849](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1849)

### 解决方案

添加一个更简单的心情设置供用户选择。不再计算心情消耗，而是在出现低心情提示后直接退出关卡，等待一段时间回复心情（一小时/两小时），然后再执行出击/活动。
![5E$6OVNR{GEA0M2K8))GEO](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/123047458/8d63ceaf-e0e5-4b71-ae86-0965ae0084ab)

这样即可避免用户操作导致心情计算错误的报错，也无需用户自己填写当前心情

**Comment by LmeSzinc** [comment]
不手操就不需要手动填写心情

**Comment by MisakaMikoto-35c5** [comment]
游戏内沉船也会导致心情计算错误，但这种情况对于一些玩家来说属于会正常发生的小概率事件。

现在程序对于这种事件的处理是一段时间以后把进程杀了重启，然后再过一段时间结束进程请求人工介入。建议遇到这种情况可以直接将当前心情值归零，即使不归零也可以直接取消掉出击任务确保其他任务能继续进行。

**Comment by Book-fall2wish** [comment]
> 不手操就不需要手动填写心情

的确出现弹框以后重置心情数值更好一点，因为多任务用了同样的船也会导致心情计算出错，比如每日困难有海伦娜，刷活动pt也有海伦娜，就会导致游戏类计算了两次出击心情，但是alas里只计算了一次。往往会导致出现脚本终止的错误
