### ISSUE TITLE
请求新增一个计算前排心情且不更换前排的3油刷图功能

### ISSUE THREAD

**Issue by Heipen** [LmeSzinc/AzurLaneAutoScript#3799]
### 你的功能请求是否与问题有关？

现有的刷紧急委托的方案并不适配高难一些的3油低耗活动图（b3甚至c1），这些活动图可能要求婚舰或指定前排，以至于无法通过现有的筛选来选择前排。且该场景大部分对出击频率要求不高，主要目的为低耗获取pt，因而无需不间断刷取。

### 解决方案

在现有刷紧急委托基础上计算前排心情，黄脸后不更换而是休息，等待心情恢复。
（或是我之前建议过的前排仅从玩家通过“常用”标记的舰船中选取，也可解决此类问题。#3135 ）

**Comment by LmeSzinc** [comment]
意义不明，刷紧急委托的目的就是刷委托通过委托获取收益
