### ISSUE TITLE
侵蚀一启动前扫描当前海域内的明石

### ISSUE THREAD

**Issue by Cshrimps** [LmeSzinc/AzurLaneAutoScript#3801]
### 你的功能请求是否与问题有关？

重新启动的侵蚀一忽略了当前海域内的明石，导致中断频率较高时体力无法倒转

### 解决方案

在启动侵蚀一之前，点按自律按钮，自律活动结束后扫描当前海域内是否存在明石

**Comment by LmeSzinc** [comment]
#2367
