### ISSUE TITLE
大世界一键开关

### ISSUE THREAD

**Issue by RrkwM** [LmeSzinc/AzurLaneAutoScript#3810]
### 你的功能请求是否与问题有关？

老咸鱼回坑时有活动没肝，大世界怎么玩也不太记得，要一个一个取消勾选大世界任务有点麻烦

### 解决方案

在大世界通用设置里加个开关，一键启用或禁用全部大世界任务

**Comment by LmeSzinc** [comment]
意义不明，挂机等运行就可以了
