### ISSUE TITLE
科研出现问题

### ISSUE THREAD

**Issue by dfmjndm** [LmeSzinc/AzurLaneAutoScript#3827]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/57401901/2bad856c-459e-43ce-a47d-af6aac49f21c)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/57401901/9b79a973-342c-4666-8f4c-666e332e3ac3)
加个处理吧

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#%E6%B2%A1%E6%9C%89%E7%AC%A6%E5%90%88%E5%A7%94%E6%89%98%E8%A6%81%E6%B1%82%E7%9A%84%E8%A7%92%E8%89%B2%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E5%BC%80%E5%A7%8B%E5%A7%94%E6%89%98--no-ship-matches-the-required-for-the-commission-which-cannot-be-started-2460
