### ISSUE TITLE
请求加入Linux版本！

### ISSUE THREAD

**Issue by Mhyho** [LmeSzinc/AzurLaneAutoScript#3833]
### 你的功能请求是否与问题有关？

否

### 解决方案

最近因一些不可抗力的原因不得不全面专向linux环境，所以这个要求虽然听起来可能很过分，但作者大佬能否在之后的版本中考虑加入linux版本呢？感激不尽！

**Comment by xhqss** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn

**Comment by Mhyho** [comment]
> https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn

我自爆双眼…可能连续熬夜之后有些急躁没有完全看完…………谢谢
