### ISSUE TITLE
能否支持mumu原生的截图方式

### ISSUE THREAD

**Issue by WolfCanglong** [LmeSzinc/AzurLaneAutoScript#3848]
### 解决方案

MAA最近支持了这个，在那边叫mumu增强截图模式或者mumu extras，估计是原生接口，真的很快就十几ms的延迟，而且我发现在挂多个模拟器的情况下这个模式能明显降低系统资源的占用，模拟器帧数会比其他截图方式稳定许多，不知ALAS能不能也支持下

**Comment by bookbug666** [comment]
已經有了
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/29662367/0ead62e8-272e-4f21-9c49-a26c31660b6c)

**Comment by Air111** [comment]
#3621
