### ISSUE TITLE
新邮件领取

### ISSUE THREAD

**Issue by fhwhite** [LmeSzinc/AzurLaneAutoScript#3858]
### 你的功能请求是否与问题有关？

希望能自动领取全部邮件到仓库，如果现在已经能实现，应该是在过滤里填什么吗，没找到邮件相关的配置信息

**Comment by Air111** [comment]
ui更新都需要时间进行适配，别急

**Comment by fhwhite** [comment]
> ui更新都需要时间进行适配，别急

好的，收到，我就怕已经部署完了我不知道咋用，所以才来问问，哈哈
