### ISSUE TITLE
侵蚀1练级bug

### ISSUE THREAD

**Issue by ymdm2** [LmeSzinc/AzurLaneAutoScript#3865]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

侵蚀1练级时，出现塞壬探测装置，alas会消耗紫币搜索沉没的物资，但不会自动探索拾取物资，而是直接计划作战刷新地图，导致紫币的直接浪费。看到过一次，不知道是不是个例。

**Comment by Air111** [comment]
在log文件夹中找到当天log([日期]_[配置名称].txt)上传并提供大概时间

**Comment by ymdm2** [comment]
忘了是哪一天了，这里也就顺便提一嘴，逻辑没问题就算了。就算bug存在，也影响不大
