### ISSUE TITLE
alas无法识别带提示信息的锁屏界面

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#3901]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题，alas虽然会点击空白锁屏返回港区主界面，但不知道识别怎么写的，当锁屏上有任务结束信息时就会无法识别报错
![bug1](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/bc764903-aa7c-4a7b-b14e-c160cf4f936e)
![bug2](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/5f61f685-1f4b-4c9c-ade7-f0b6e99072a8)

### 预期行为

无法识别时至少先点一下屏幕，不要只重复识别而不点击

### 相关 Logs

```Text
INFO     18:34:28.944 │ Scheduler: Start task `Tactical`                           
═══════════════════════════════════════════════════════════════════════════════════
                                     TACTICAL                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     18:34:29.043 │ <<< UI ENSURE >>>                                          
INFO     18:34:29.043 │ UI get current page                                        
INFO     18:34:29.197 │ Unknown ui page                                            
INFO     18:34:29.426 │ [Package_name] com.bilibili.azurlane                       
INFO     18:34:29.442 │ [Device Orientation] 1 (HOME key on the right)             
INFO     18:34:29.515 │ Unknown ui page                                            
INFO     18:34:29.821 │ Unknown ui page                                            
INFO     18:34:30.117 │ Unknown ui page                                            
INFO     18:34:30.419 │ Unknown ui page                                            
INFO     18:34:30.714 │ Unknown ui page                                            
INFO     18:34:31.015 │ Unknown ui page                                            
INFO     18:34:31.315 │ Unknown ui page                                            
INFO     18:34:31.619 │ Unknown ui page                                            
INFO     18:34:31.924 │ Unknown ui page                                            
INFO     18:34:32.217 │ Unknown ui page                                            
INFO     18:34:32.519 │ Unknown ui page                                            
INFO     18:34:32.814 │ Unknown ui page                                            
INFO     18:34:33.113 │ Unknown ui page                                            
INFO     18:34:33.420 │ Unknown ui page                                            
INFO     18:34:33.715 │ Unknown ui page                                            
INFO     18:34:34.020 │ Unknown ui page                                            
INFO     18:34:34.313 │ Unknown ui page                                            
INFO     18:34:34.618 │ Unknown ui page                                            
INFO     18:34:34.922 │ Unknown ui page                                            
INFO     18:34:35.231 │ Unknown ui page                                            
INFO     18:34:35.528 │ Unknown ui page                                            
INFO     18:34:35.828 │ Unknown ui page                                            
INFO     18:34:36.127 │ Unknown ui page                                            
INFO     18:34:36.441 │ Unknown ui page                                            
INFO     18:34:36.729 │ Unknown ui page                                            
INFO     18:34:37.028 │ Unknown ui page                                            
INFO     18:34:37.328 │ Unknown ui page                                            
INFO     18:34:37.629 │ Unknown ui page                                            
INFO     18:34:37.932 │ Unknown ui page                                            
INFO     18:34:38.226 │ Unknown ui page                                            
INFO     18:34:38.530 │ Unknown ui page                                            
INFO     18:34:38.827 │ Unknown ui page                                            
WARNING  18:34:39.116 │ Unknown ui page                                            
INFO     18:34:39.117 │ [EMULATOR__SCREENSHOT_METHOD] DroidCast_raw                
INFO     18:34:39.118 │ [EMULATOR__CONTROL_METHOD] minitouch                       
INFO     18:34:39.119 │ [SERVER] cn                                                
WARNING  18:34:39.120 │ Starting from current page is not supported                
WARNING  18:34:39.120 │ Supported page: ['page_main', 'page_campaign_menu',        
         'page_campaign', 'page_fleet', 'page_main_white', 'page_unknown',         
         'page_exercise', 'page_daily', 'page_event', 'page_sp', 'page_coalition', 
         'page_os', 'page_archives', 'page_reward', 'page_mission', 'page_guild',  
         'page_commission', 'page_tactical', 'page_battle_pass', 'page_event_list',
         'page_raid', 'page_research', 'page_shipyard', 'page_meta',               
         'page_storage', 'page_reshmenu', 'page_dormmenu', 'page_dorm',            
         'page_meowfficer', 'page_academy', 'page_game_room', 'page_shop',         
         'page_munitions', 'page_supply_pack', 'page_build', 'page_mail']          
WARNING  18:34:39.122 │ Supported page: Any page with a "HOME" button on the       
         upper-right                                                               
CRITICAL 18:34:39.122 │ Please switch to a supported page before starting Alas     
INFO     18:34:39.123 │ Game server may be under maintenance or network may be     
         broken, check server status now                                           
INFO     18:34:39.246 │ Server "杜立特空袭" is available.                          
CRITICAL 18:34:39.247 │ Game page unknown                                          
WARNING  18:34:39.251 │ Saving error: ./log/error/1718793279251                    
INFO     18:34:39.576 │ No provider specified, skip sending
```

**Comment by clark1091** [comment]
INFO     21:51:58.163 │ Update droidcast resolution                                
INFO     21:51:58.173 │ newCommandTimeout updated to 168h0m0s                      
INFO     21:51:58.174 │ [u2.Device] Device(atx_agent_url=http://127.0.0.1:50470)   
INFO     21:51:58.176 │ [Device Orientation] 1 (HOME key on the right)             
INFO     21:51:58.178 │ Reuse forward: ForwardItem(serial='127.0.0.1:16384',       
         local='tcp:20204', remote='localabstract:minitouch')                      
INFO     21:51:58.180 │ v 1                                                        
INFO     21:51:58.180 │ ^ 10 720 1280 0                                            
INFO     21:51:58.181 │ $ 2584                                                     
INFO     21:51:58.182 │ minitouch running on port: 20204, pid: 2584                
INFO     21:51:58.183 │ max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0  
INFO     21:51:58.191 │ [Device Orientation] 1 (HOME key on the right)             
INFO     21:51:58.192 │ Droicast resolution: (720, 1280)                           
INFO     21:51:58.193 │ Reuse forward: ForwardItem(serial='127.0.0.1:16384',       
         local='tcp:20355', remote='tcp:53516')                                    
INFO     21:51:58.255 │ [Screen_size] 1280x720                                     
INFO     21:51:58.432 │ early_ocr_import call                                      
INFO     21:51:58.434 │ early_ocr_import start                                     
INFO     21:51:58.434 │ <<< UI ENSURE >>>                                          
INFO     21:51:58.435 │ UI get current page                                        
INFO     21:51:58.437 │ Loading OCR dependencies                                   
INFO     21:51:58.895 │ Unknown ui page                                            
INFO     21:51:58.988 │ early_ocr_import finish                                    
INFO     21:51:59.089 │ [Package_name] com.bilibili.azurlane                       
INFO     21:51:59.098 │ [Device Orientation] 1 (HOME key on the right)             
INFO     21:51:59.162 │ Unknown ui page                                            
INFO     21:51:59.470 │ Unknown ui page                                            
INFO     21:51:59.762 │ Unknown ui page                                            
INFO     21:52:00.073 │ Unknown ui page                                            
INFO     21:52:00.367 │ Unknown ui page                                            
INFO     21:52:00.664 │ Unknown ui page                                            
INFO     21:52:00.970 │ Unknown ui page                                            
INFO     21:52:01.264 │ Unknown ui page                                            
INFO     21:52:01.570 │ Unknown ui page                                            
INFO     21:52:01.870 │ Unknown ui page                                            
INFO     21:52:02.172 │ Unknown ui page                                            
INFO     21:52:02.471 │ Unknown ui page                                            
INFO     21:52:02.769 │ Unknown ui page                                            
INFO     21:52:03.070 │ Unknown ui page                                            
INFO     21:52:03.377 │ Unknown ui page                                            
[alas] exited. Reason: Manual stop

以上是我保持锁屏信息不变下重启alas的log，可见又卡死了

**Comment by clark1091** [comment]
![bug1](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/66a27c23-4960-4bd0-af6a-1c2aec799000)
![bug2](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/134053964/afb488bd-b358-46d4-968a-5a5d3f9d5aa7)

图片添加似乎失败了，再试试

**Comment by clark1091** [comment]
......总之就是当锁屏界面有任意任务完成提示（委托、学院、科研）时alas就会不认识这个界面是啥，然后卡死

**Comment by Air111** [comment]
先把厌战下了，现在待机界面识别的是右下角的电量图标

**Comment by MengNianxiaoyao** [comment]
> 所以锁屏时右下角不能有东西？行吧……不过点一下屏幕应该也可以有吧

是需要识别特征区域才能判断处于什么界面，但因为厌战遮挡住了特征区域，所以导致识别不了

**Comment by loy4dot** [comment]
这个不止是有提示。锁屏页面有时候就是会卡住。模拟器需要按ESC才能退出，鼠标单机都退不出这个页面
![Uploading 2024-06-30_21-42-14-035587.png…]()

**Comment by MengNianxiaoyao** [comment]
现在可以关闭锁屏界面里，在设置里关掉
