### ISSUE TITLE
运行过程中会出现奇怪的循环

### ISSUE THREAD

**Issue by bsyyno1** [LmeSzinc/AzurLaneAutoScript#3952]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在运行过程中会出现反复切换 活动图-出击界面-主界面的情况 而且一直循环不提示报错 多次发生 

### 如何复现

正常操作  只不过每次卡进循环的点 左上总是显示正在运行“委托”

### 相关 Logs

```Text
日志输出在截图中
```

### 截图

![log错误](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/99700518/fc71bb6a-833a-4ca6-a27c-5654652f528a)

**Comment by Air111** [comment]
提供在 log 目录下当天的 log

**Comment by bsyyno1** [comment]
[2024-07-01_alas.txt](https://github.com/user-attachments/files/16049167/2024-07-01_alas.txt)
之前不知道本地还会存log文件 只在页面里面找  看了一下可能是因为 刷紧急委托的时候 设置的地图是A3 系统认为是活动图 但是进入之后找不到A3这个图 所以就会进入循环而反复找这个图  没发现的原因主要是在运行的项目显示是委托 没有往那个方面去找

**Comment by Famoz2023** [comment]
这个循环我在“每月开荒”任务中复现

**Comment by sink-er** [comment]
俺也一样，俺现在“委托”循环

**Comment by Air111** [comment]
> video_2024-07-04_20-32-04.mp4 
> [2024-07-04_gui.txt](https://github.com/user-attachments/files/16100226/2024-07-04_gui.txt) [2024-07-04_alas.txt](https://github.com/user-attachments/files/16100227/2024-07-04_alas.txt) 说是错误设置或错误使用，但我没有动过设置，几天前还正常，之后就这样了，这几天根本没法用，有什么解决方法没。 @LmeSzinc

关闭活动每日A图

**Comment by sink-er** [comment]
> > video_2024-07-04_20-32-04.mp4
> > [2024-07-04_gui.txt](https://github.com/user-attachments/files/16100226/2024-07-04_gui.txt) [2024-07-04_alas.txt](https://github.com/user-attachments/files/16100227/2024-07-04_alas.txt) 说是错误设置或错误使用，但我没有动过设置，几天前还正常，之后就这样了，这几天根本没法用，有什么解决方法没。 @LmeSzinc
> 
> 关闭活动每日A图

阿里嘎多，看了下是“活动图”没有取消干净
