### ISSUE TITLE
7-2 BUG

### ISSUE THREAD

**Issue by EAlyce** [LmeSzinc/AzurLaneAutoScript#3966]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

═══════════════════════════════════════════════════════════════════════════════════
INFO     16:15:21.162 │ Start scheduler loop: alas                                 
INFO     16:15:21.233 │ [Server] cn                                                
INFO     16:15:21.251 │ Bind task ['General', 'Alas']                              
INFO     16:15:21.593 │ Server "瞭望台行动" is available.                          
INFO     16:15:21.596 │ Pending tasks: ['Main']                                    
INFO     16:15:21.597 │ [Task] Main (Enable, 2024-04-19 04:06:00)                  
INFO     16:15:21.598 │ Bind task ['General', 'Alas', 'Main']                      
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     16:15:21.994 │ DEVICE                                                     
INFO     16:15:21.995 │ [IS_ON_PHONE_CLOUD] False                                  
INFO     16:15:21.996 │ [AdbBinary] D:\Users\Desktop\AzurLaneAutoScript\toolkit\Lib
         \site-packages\adbutils\binaries\adb.exe                                  
INFO     16:15:21.999 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     16:15:22.000 │ <<< DETECT DEVICE >>>                                      
INFO     16:15:22.001 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     16:15:22.003 │ emulator-5554                                              
INFO     16:15:22.004 │ Current serial 127.0.0.1:5555 not found but paired device  
         emulator-5554 found. Using serial: emulator-5554                          
INFO     16:15:22.006 │ "emulator-5554" is a `emulator-*` serial, skip adb connect 
INFO     16:15:22.007 │ [AdbDevice] AdbDevice(serial=emulator-5554)                
INFO     16:15:22.009 │ [PackageName] com.bilibili.azurlane                        
INFO     16:15:22.010 │ [Server] cn                                                
INFO     16:15:22.011 │ Screenshot interval set to 0.3s                            
INFO     16:15:22.013 │ <<< MINITOUCH INIT >>>                                     
INFO     16:15:22.013 │ Scheduler: Start task `Main`                               
═══════════════════════════════════════════════════════════════════════════════════
                                       MAIN                                        
═══════════════════════════════════════════════════════════════════════════════════
INFO     16:15:22.026 │ [nemud.app_keep_alive]                                     
INFO     16:15:22.026 │ [Device Orientation] 0 (Normal)                            
INFO     16:15:22.028 │ Reuse forward: ForwardItem(serial='emulator-5554',         
         local='tcp:20494', remote='tcp:53516')                                    
INFO     16:15:22.028 │ Reuse forward: ForwardItem(serial='emulator-5554',         
         local='tcp:20206', remote='localabstract:minitouch')                      
INFO     16:15:22.042 │ v 1                                                        
INFO     16:15:22.043 │ ^ 10 1279 719 2                                            
INFO     16:15:22.044 │ $ 2442                                                     
INFO     16:15:22.045 │ minitouch running on port: 20206, pid: 2442                
INFO     16:15:22.046 │ max_contact: 10; max_x: 1279; max_y: 719; max_pressure: 2  
INFO     16:15:22.088 │ [Screen_size] 1280x720                                     
INFO     16:15:22.339 │ early_ocr_import call                                      
INFO     16:15:22.341 │ early_ocr_import start                                     
INFO     16:15:22.345 │ Loading OCR dependencies                                   
══════════════════════════════════ CAMPAIGN_7_2 ═══════════════════════════════════
INFO     16:15:22.361 │ CAMPAIGN_7_2                                               
INFO     16:15:22.362 │ Count: 0                                                   
INFO     16:15:22.363 │ Already in map, retreating.                                
INFO     16:15:22.364 │ <<< MAP WITHDRAW >>>                                       
INFO     16:15:22.407 │ Click ( 793,  695) @ WITHDRAW                              
INFO     16:15:23.084 │ Click ( 784,  519) @ POPUP_CONFIRM_WITHDRAW                
INFO     16:15:23.170 │ early_ocr_import finish                                    
INFO     16:15:25.046 │ In stage.                                                  
INFO     16:15:26.511 │ <<< UI ENSURE >>>                                          
INFO     16:15:26.512 │ UI get current page                                        
INFO     16:15:26.536 │ [UI] page_campaign                                         
INFO     16:15:26.537 │ Already at page_campaign                                   
INFO     16:15:26.564 │ [Mode_switch_1] hard                                       
INFO     16:15:26.566 │ <<< UI ENSURE INDEX >>>                                    
INFO     16:15:26.612 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     16:15:26.679 │ [campaign 0.080s] ['7--2', '7--3', '7--4', '7--1']         
INFO     16:15:26.681 │ [Chapter] 7                                                
INFO     16:15:26.682 │ [Stage] 7-2, 7-3, 7-4, 7-1                                 
INFO     16:15:26.683 │ [Index] 7                                                  
INFO     16:15:26.729 │ [OCR_OIL 0.027s] 17936                                     
─────────────────────────────────────── 7-2 ───────────────────────────────────────
INFO     16:15:26.732 │ 7-2                                                        
INFO     16:15:26.733 │ <<< ENTER MAP >>>                                          
INFO     16:15:26.796 │ Click ( 446,  216) @ 7-2                                   
INFO     16:15:27.202 │ [Map_clear_percentage] 0.2238372093023256                  
INFO     16:15:27.503 │ [Map_clear_percentage] 0.8313953488372093                  
INFO     16:15:27.802 │ [Map_clear_percentage] 0.997093023255814                   
INFO     16:15:27.804 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     16:15:27.805 │ [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 
         3_stars, threat_safe, clear_mode                                          
INFO     16:15:27.807 │ [StopCondition_MapAchievement] non_stop                    
INFO     16:15:27.808 │ [Fast_Forward] on                                          
INFO     16:15:27.821 │ [Auto_Search] off                                          
INFO     16:15:27.823 │ Click ( 873,  516) @ MAP_PREPARATION                       
INFO     16:15:28.103 │ Handling 2x book setting, mode=prep.                       
INFO     16:15:28.112 │ Using fleet: [1, 2, 0]                                     
INFO     16:15:28.152 │ Hard satisfied: Fleet_1: None, Fleet_2: None, Submarine:   
         None                                                                      
INFO     16:15:28.157 │ Click (1150,  357) @ FLEET_2_CLEAR                         
INFO     16:15:28.408 │ Click (1055,  222) @ FLEET_1_CHOOSE                        
INFO     16:15:28.707 │ Current selected: [1]                                      
INFO     16:15:28.709 │ Click (1065,  231) @ FLEET_1_CHOOSE                        
INFO     16:15:29.000 │ Click (1063,  332) @ FLEET_2_CHOOSE                        
INFO     16:15:29.302 │ Current selected: [1]                                      
INFO     16:15:29.304 │ Click (1045,  451) @ FLEET_2_BAR_INDEX_2                   
INFO     16:15:29.612 │ Click (1042,  570) @ FLEET_PREPARATION                     
INFO     16:15:33.825 │ Enemy searching appeared.                                  
INFO     16:15:33.890 │ [Fleet_Lock] off                                           
INFO     16:15:33.892 │ Click (1188,  500) @ FLEET_UNLOCKED                        
INFO     16:15:34.179 │ [Fleet_Lock] on                                            
INFO     16:15:34.180 │ <<< MAP INIT >>>                                           
INFO     16:15:34.181 │ Load map_data, has_loop=False, use_loop=True               
INFO     16:15:34.183 │ Load spawn_data, has_loop=False, use_loop=True             
INFO     16:15:34.184 │ grid_connection: wall=False, portal=False                  
INFO     16:15:34.186 │ Load mechanism, land_base=False, maze=False,               
         fortress=False, bouncing_enemy=False                                      
INFO     16:15:34.354 │           vanish_point: (  635, -1676)                     
INFO     16:15:34.355 │          distant_point: (-2246, -1676)                     
INFO     16:15:34.388 │ 0.129s  _   Horizontal: 6 (6 inner, 2 edge)                
INFO     16:15:34.390 │ Edges: /_\    Vertical: 9 (10 inner, 2 edge)               
INFO     16:15:34.392 │ [homo_storage] ((8, 5), [(230.16, 151.393), (1157.57,      
         151.393), (127.64, 613.588), (1289.607, 613.588)])                        
INFO     16:15:34.454 │            tile_center: 0.955 (good match)                 
INFO     16:15:34.469 │ 0.075s  _   edge_lines: 3 hori, 2 vert                     
INFO     16:15:34.470 │ Edges: /_\   homo_loca: ( 25,  53)                         
INFO     16:15:34.476 │            center_loca: (3, 2)                             
INFO     16:15:34.477 │ [view.center_offset] [0.52337754 0.53846002]               
INFO     16:15:34.478 │       camera_corrected: A1 -> D3                           
INFO     16:15:34.479 │                 Camera: D3                                 
INFO     16:15:34.530 │ 0.050s         predict: 39                                 
INFO     16:15:34.531 │ -- -- -- -- -- -- -- Fl                                    
INFO     16:15:34.532 │ -- -- -- -- -- -- -- --                                    
INFO     16:15:34.533 │ -- -- 2L -- -- -- -- --                                    
INFO     16:15:34.534 │ -- -- -- -- -- 2L -- --                                    
INFO     16:15:34.535 │ Fl -- -- 2L -- -- -- ..                                    
INFO     16:15:34.536 │ Fleet set to 1                                             
INFO     16:15:34.546 │ Fleet: 1, fleet_current_index: 1                           
INFO     16:15:34.548 │ [Map_buff] double_line                                     
INFO     16:15:34.550 │ Skip strategy bar check.                                   
ERROR    16:15:34.551 │ TypeError: argument of type 'int' is not iterable          
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\alas.py:69 in run                  │
         │                                                                        │
         │    67 │   │   │   if not skip_first_screenshot:                        │
         │    68 │   │   │   │   self.device.screenshot()                         │
         │ ❱  69 │   │   │   self.__getattribute__(command)()                     │
         │    70 │   │   │   return True                                          │
         │    71 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │               command = 'main'                                     │ │
         │ │                     e = TypeError("argument of type 'int' is not   │ │
         │ │                         iterable")                                 │ │
         │ │                  self = <alas.AzurLaneAutoScript object at         │ │
         │ │                         0x000001D75402C188>                        │ │
         │ │ skip_first_screenshot = False                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\Users\Desktop\AzurLaneAutoScript\alas.py:344 in main                │
         │                                                                        │
         │   342 │   │   from module.campaign.run import CampaignRun              │
         │   343 │   │   CampaignRun(config=self.config, device=self.device).run( │
         │ ❱ 344 │   │   │   name=self.config.Campaign_Name, folder=self.config.C │
         │       mode=self.config.Campaign_Mode)                                  │
         │   345 │                                                                │
         │   346 │   def main2(self):                                             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ CampaignRun = <class 'module.campaign.run.CampaignRun'>            │ │
         │ │        self = <alas.AzurLaneAutoScript object at                   │ │
         │ │               0x000001D75402C188>                                  │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\campaign\run.py:387 in run  │
         │                                                                        │
         │   385 │   │   │   self.device.click_record_clear()                     │
         │   386 │   │   │   try:                                                 │
         │ ❱ 387 │   │   │   │   self.campaign.run()                              │
         │   388 │   │   │   except ScriptEnd as e:                               │
         │   389 │   │   │   │   logger.hr('Script end')                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ folder = 'campaign_main'                                           │ │
         │ │   mode = 'normal'                                                  │ │
         │ │   name = 'campaign_7_2'                                            │ │
         │ │   self = <module.campaign.run.CampaignRun object at                │ │
         │ │          0x000001D772D3D0C8>                                       │ │
         │ │  total = 0                                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\campaign\campaign_base.py:1 │
         │ 30 in run                                                              │
         │                                                                        │
         │   128 │   │   if not self.map_is_auto_search:                          │
         │   129 │   │   │   self.handle_map_fleet_lock()                         │
         │ ❱ 130 │   │   │   self.map_init(self.MAP)                              │
         │   131 │   │   else:                                                    │
         │   132 │   │   │   self.map = self.MAP                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\map\fleet.py:836 in         │
         │ map_init                                                               │
         │                                                                        │
         │    834 │   │   logger.hr('Map init')                                   │
         │    835 │   │   self.map_data_init(map_)                                │
         │ ❱  836 │   │   self.map_control_init()                                 │
         │    837 │                                                               │
         │    838 │   def map_data_init(self, map_):                              │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                  │ │
         │ │        0x000001D773E98948>                                         │ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\map\fleet.py:882 in         │
         │ map_control_init                                                       │
         │                                                                        │
         │    880 │   │   self.handle_strategy(index=self.fleet_show_index)       │
         │    881 │   │   self.hp_reset()                                         │
         │ ❱  882 │   │   self.hp_get()                                           │
         │    883 │   │   self.lv_reset()                                         │
         │    884 │   │   self.lv_get()                                           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\combat\hp_balancer.py:90 in │
         │ hp_get                                                                 │
         │                                                                        │
         │    88 │   │   # Chinese comma                                          │
         │    89 │   │   weight = self.config.HpControl_HpBalanceWeight           │
         │ ❱  90 │   │   if '，' in self.config.HpControl_HpBalanceWeight:        │
         │    91 │   │   │   weight = self.config.HpControl_HpBalanceWeight.repla │
         │    92 │   │   │   logger.info(f'HpControl_HpBalanceWeight              │
         │       {self.config.HpControl_HpBalanceWeight} is revised to {weight}') │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │   self = <campaign.campaign_main.campaign_7_2.Campaign object at   │ │
         │ │          0x000001D773F31B48>                                       │ │
         │ │ weight = 1693                                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         TypeError: argument of type 'int' is not iterable                         
INFO     16:15:35.161 │ No provider specified, skip sending   

### 如何复现

![20240704_161657](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48439969/28603b50-b66f-45c0-8260-1d1d2cd8d07c)
![20240704_161716](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48439969/58ce9f51-e7f0-4bb8-a17d-33cb30a0f3a3)
![20240704_161726](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48439969/7e9924cf-50d5-497c-85d7-7d7d0cc414f5)
![20240704_161733](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/48439969/e866e8c7-a8cb-4874-b6b3-9eac2bd1d641)

### 预期行为

如图，运行后报错

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
INFO     16:15:21.162 │ Start scheduler loop: alas                                 
INFO     16:15:21.233 │ [Server] cn                                                
INFO     16:15:21.251 │ Bind task ['General', 'Alas']                              
INFO     16:15:21.593 │ Server "瞭望台行动" is available.                          
INFO     16:15:21.596 │ Pending tasks: ['Main']                                    
INFO     16:15:21.597 │ [Task] Main (Enable, 2024-04-19 04:06:00)                  
INFO     16:15:21.598 │ Bind task ['General', 'Alas', 'Main']                      
═════════════════════════════════════ DEVICE ══════════════════════════════════════
INFO     16:15:21.994 │ DEVICE                                                     
INFO     16:15:21.995 │ [IS_ON_PHONE_CLOUD] False                                  
INFO     16:15:21.996 │ [AdbBinary] D:\Users\Desktop\AzurLaneAutoScript\toolkit\Lib
         \site-packages\adbutils\binaries\adb.exe                                  
INFO     16:15:21.999 │ [AdbClient] AdbClient(127.0.0.1, 5037)                     
INFO     16:15:22.000 │ <<< DETECT DEVICE >>>                                      
INFO     16:15:22.001 │ Here are the available devices, copy to                    
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"         
INFO     16:15:22.003 │ emulator-5554                                              
INFO     16:15:22.004 │ Current serial 127.0.0.1:5555 not found but paired device  
         emulator-5554 found. Using serial: emulator-5554                          
INFO     16:15:22.006 │ "emulator-5554" is a `emulator-*` serial, skip adb connect 
INFO     16:15:22.007 │ [AdbDevice] AdbDevice(serial=emulator-5554)                
INFO     16:15:22.009 │ [PackageName] com.bilibili.azurlane                        
INFO     16:15:22.010 │ [Server] cn                                                
INFO     16:15:22.011 │ Screenshot interval set to 0.3s                            
INFO     16:15:22.013 │ <<< MINITOUCH INIT >>>                                     
INFO     16:15:22.013 │ Scheduler: Start task `Main`                               
═══════════════════════════════════════════════════════════════════════════════════
                                       MAIN                                        
═══════════════════════════════════════════════════════════════════════════════════
INFO     16:15:22.026 │ [nemud.app_keep_alive]                                     
INFO     16:15:22.026 │ [Device Orientation] 0 (Normal)                            
INFO     16:15:22.028 │ Reuse forward: ForwardItem(serial='emulator-5554',         
         local='tcp:20494', remote='tcp:53516')                                    
INFO     16:15:22.028 │ Reuse forward: ForwardItem(serial='emulator-5554',         
         local='tcp:20206', remote='localabstract:minitouch')                      
INFO     16:15:22.042 │ v 1                                                        
INFO     16:15:22.043 │ ^ 10 1279 719 2                                            
INFO     16:15:22.044 │ $ 2442                                                     
INFO     16:15:22.045 │ minitouch running on port: 20206, pid: 2442                
INFO     16:15:22.046 │ max_contact: 10; max_x: 1279; max_y: 719; max_pressure: 2  
INFO     16:15:22.088 │ [Screen_size] 1280x720                                     
INFO     16:15:22.339 │ early_ocr_import call                                      
INFO     16:15:22.341 │ early_ocr_import start                                     
INFO     16:15:22.345 │ Loading OCR dependencies                                   
══════════════════════════════════ CAMPAIGN_7_2 ═══════════════════════════════════
INFO     16:15:22.361 │ CAMPAIGN_7_2                                               
INFO     16:15:22.362 │ Count: 0                                                   
INFO     16:15:22.363 │ Already in map, retreating.                                
INFO     16:15:22.364 │ <<< MAP WITHDRAW >>>                                       
INFO     16:15:22.407 │ Click ( 793,  695) @ WITHDRAW                              
INFO     16:15:23.084 │ Click ( 784,  519) @ POPUP_CONFIRM_WITHDRAW                
INFO     16:15:23.170 │ early_ocr_import finish                                    
INFO     16:15:25.046 │ In stage.                                                  
INFO     16:15:26.511 │ <<< UI ENSURE >>>                                          
INFO     16:15:26.512 │ UI get current page                                        
INFO     16:15:26.536 │ [UI] page_campaign                                         
INFO     16:15:26.537 │ Already at page_campaign                                   
INFO     16:15:26.564 │ [Mode_switch_1] hard                                       
INFO     16:15:26.566 │ <<< UI ENSURE INDEX >>>                                    
INFO     16:15:26.612 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     16:15:26.679 │ [campaign 0.080s] ['7--2', '7--3', '7--4', '7--1']         
INFO     16:15:26.681 │ [Chapter] 7                                                
INFO     16:15:26.682 │ [Stage] 7-2, 7-3, 7-4, 7-1                                 
INFO     16:15:26.683 │ [Index] 7                                                  
INFO     16:15:26.729 │ [OCR_OIL 0.027s] 17936                                     
─────────────────────────────────────── 7-2 ───────────────────────────────────────
INFO     16:15:26.732 │ 7-2                                                        
INFO     16:15:26.733 │ <<< ENTER MAP >>>                                          
INFO     16:15:26.796 │ Click ( 446,  216) @ 7-2                                   
INFO     16:15:27.202 │ [Map_clear_percentage] 0.2238372093023256                  
INFO     16:15:27.503 │ [Map_clear_percentage] 0.8313953488372093                  
INFO     16:15:27.802 │ [Map_clear_percentage] 0.997093023255814                   
INFO     16:15:27.804 │ [MAP_CLEAR_ALL_THIS_TIME] False                            
INFO     16:15:27.805 │ [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 
         3_stars, threat_safe, clear_mode                                          
INFO     16:15:27.807 │ [StopCondition_MapAchievement] non_stop                    
INFO     16:15:27.808 │ [Fast_Forward] on                                          
INFO     16:15:27.821 │ [Auto_Search] off                                          
INFO     16:15:27.823 │ Click ( 873,  516) @ MAP_PREPARATION                       
INFO     16:15:28.103 │ Handling 2x book setting, mode=prep.                       
INFO     16:15:28.112 │ Using fleet: [1, 2, 0]                                     
INFO     16:15:28.152 │ Hard satisfied: Fleet_1: None, Fleet_2: None, Submarine:   
         None                                                                      
INFO     16:15:28.157 │ Click (1150,  357) @ FLEET_2_CLEAR                         
INFO     16:15:28.408 │ Click (1055,  222) @ FLEET_1_CHOOSE                        
INFO     16:15:28.707 │ Current selected: [1]                                      
INFO     16:15:28.709 │ Click (1065,  231) @ FLEET_1_CHOOSE                        
INFO     16:15:29.000 │ Click (1063,  332) @ FLEET_2_CHOOSE                        
INFO     16:15:29.302 │ Current selected: [1]                                      
INFO     16:15:29.304 │ Click (1045,  451) @ FLEET_2_BAR_INDEX_2                   
INFO     16:15:29.612 │ Click (1042,  570) @ FLEET_PREPARATION                     
INFO     16:15:33.825 │ Enemy searching appeared.                                  
INFO     16:15:33.890 │ [Fleet_Lock] off                                           
INFO     16:15:33.892 │ Click (1188,  500) @ FLEET_UNLOCKED                        
INFO     16:15:34.179 │ [Fleet_Lock] on                                            
INFO     16:15:34.180 │ <<< MAP INIT >>>                                           
INFO     16:15:34.181 │ Load map_data, has_loop=False, use_loop=True               
INFO     16:15:34.183 │ Load spawn_data, has_loop=False, use_loop=True             
INFO     16:15:34.184 │ grid_connection: wall=False, portal=False                  
INFO     16:15:34.186 │ Load mechanism, land_base=False, maze=False,               
         fortress=False, bouncing_enemy=False                                      
INFO     16:15:34.354 │           vanish_point: (  635, -1676)                     
INFO     16:15:34.355 │          distant_point: (-2246, -1676)                     
INFO     16:15:34.388 │ 0.129s  _   Horizontal: 6 (6 inner, 2 edge)                
INFO     16:15:34.390 │ Edges: /_\    Vertical: 9 (10 inner, 2 edge)               
INFO     16:15:34.392 │ [homo_storage] ((8, 5), [(230.16, 151.393), (1157.57,      
         151.393), (127.64, 613.588), (1289.607, 613.588)])                        
INFO     16:15:34.454 │            tile_center: 0.955 (good match)                 
INFO     16:15:34.469 │ 0.075s  _   edge_lines: 3 hori, 2 vert                     
INFO     16:15:34.470 │ Edges: /_\   homo_loca: ( 25,  53)                         
INFO     16:15:34.476 │            center_loca: (3, 2)                             
INFO     16:15:34.477 │ [view.center_offset] [0.52337754 0.53846002]               
INFO     16:15:34.478 │       camera_corrected: A1 -> D3                           
INFO     16:15:34.479 │                 Camera: D3                                 
INFO     16:15:34.530 │ 0.050s         predict: 39                                 
INFO     16:15:34.531 │ -- -- -- -- -- -- -- Fl                                    
INFO     16:15:34.532 │ -- -- -- -- -- -- -- --                                    
INFO     16:15:34.533 │ -- -- 2L -- -- -- -- --                                    
INFO     16:15:34.534 │ -- -- -- -- -- 2L -- --                                    
INFO     16:15:34.535 │ Fl -- -- 2L -- -- -- ..                                    
INFO     16:15:34.536 │ Fleet set to 1                                             
INFO     16:15:34.546 │ Fleet: 1, fleet_current_index: 1                           
INFO     16:15:34.548 │ [Map_buff] double_line                                     
INFO     16:15:34.550 │ Skip strategy bar check.                                   
ERROR    16:15:34.551 │ TypeError: argument of type 'int' is not iterable          
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\alas.py:69 in run                  │
         │                                                                        │
         │    67 │   │   │   if not skip_first_screenshot:                        │
         │    68 │   │   │   │   self.device.screenshot()                         │
         │ ❱  69 │   │   │   self.__getattribute__(command)()                     │
         │    70 │   │   │   return True                                          │
         │    71 │   │   except TaskEnd:                                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │               command = 'main'                                     │ │
         │ │                     e = TypeError("argument of type 'int' is not   │ │
         │ │                         iterable")                                 │ │
         │ │                  self = <alas.AzurLaneAutoScript object at         │ │
         │ │                         0x000001D75402C188>                        │ │
         │ │ skip_first_screenshot = False                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │ D:\Users\Desktop\AzurLaneAutoScript\alas.py:344 in main                │
         │                                                                        │
         │   342 │   │   from module.campaign.run import CampaignRun              │
         │   343 │   │   CampaignRun(config=self.config, device=self.device).run( │
         │ ❱ 344 │   │   │   name=self.config.Campaign_Name, folder=self.config.C │
         │       mode=self.config.Campaign_Mode)                                  │
         │   345 │                                                                │
         │   346 │   def main2(self):                                             │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ CampaignRun = <class 'module.campaign.run.CampaignRun'>            │ │
         │ │        self = <alas.AzurLaneAutoScript object at                   │ │
         │ │               0x000001D75402C188>                                  │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\campaign\run.py:387 in run  │
         │                                                                        │
         │   385 │   │   │   self.device.click_record_clear()                     │
         │   386 │   │   │   try:                                                 │
         │ ❱ 387 │   │   │   │   self.campaign.run()                              │
         │   388 │   │   │   except ScriptEnd as e:                               │
         │   389 │   │   │   │   logger.hr('Script end')                          │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ folder = 'campaign_main'                                           │ │
         │ │   mode = 'normal'                                                  │ │
         │ │   name = 'campaign_7_2'                                            │ │
         │ │   self = <module.campaign.run.CampaignRun object at                │ │
         │ │          0x000001D772D3D0C8>                                       │ │
         │ │  total = 0                                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\campaign\campaign_base.py:1 │
         │ 30 in run                                                              │
         │                                                                        │
         │   128 │   │   if not self.map_is_auto_search:                          │
         │   129 │   │   │   self.handle_map_fleet_lock()                         │
         │ ❱ 130 │   │   │   self.map_init(self.MAP)                              │
         │   131 │   │   else:                                                    │
         │   132 │   │   │   self.map = self.MAP                                  │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\map\fleet.py:836 in         │
         │ map_init                                                               │
         │                                                                        │
         │    834 │   │   logger.hr('Map init')                                   │
         │    835 │   │   self.map_data_init(map_)                                │
         │ ❱  836 │   │   self.map_control_init()                                 │
         │    837 │                                                               │
         │    838 │   def map_data_init(self, map_):                              │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ map_ = <module.map.map_base.CampaignMap object at                  │ │
         │ │        0x000001D773E98948>                                         │ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\map\fleet.py:882 in         │
         │ map_control_init                                                       │
         │                                                                        │
         │    880 │   │   self.handle_strategy(index=self.fleet_show_index)       │
         │    881 │   │   self.hp_reset()                                         │
         │ ❱  882 │   │   self.hp_get()                                           │
         │    883 │   │   self.lv_reset()                                         │
         │    884 │   │   self.lv_get()                                           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ self = <campaign.campaign_main.campaign_7_2.Campaign object at     │ │
         │ │        0x000001D773F31B48>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\Users\Desktop\AzurLaneAutoScript\module\combat\hp_balancer.py:90 in │
         │ hp_get                                                                 │
         │                                                                        │
         │    88 │   │   # Chinese comma                                          │
         │    89 │   │   weight = self.config.HpControl_HpBalanceWeight           │
         │ ❱  90 │   │   if '，' in self.config.HpControl_HpBalanceWeight:        │
         │    91 │   │   │   weight = self.config.HpControl_HpBalanceWeight.repla │
         │    92 │   │   │   logger.info(f'HpControl_HpBalanceWeight              │
         │       {self.config.HpControl_HpBalanceWeight} is revised to {weight}') │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │   self = <campaign.campaign_main.campaign_7_2.Campaign object at   │ │
         │ │          0x000001D773F31B48>                                       │ │
         │ │ weight = 1693                                                      │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         TypeError: argument of type 'int' is not iterable                         
INFO     16:15:35.161 │ No provider specified, skip sending
```

**Comment by Air111** [comment]
先锋血量权重填写有误
