### ISSUE TITLE
大世界购买商店是否应当保留至少10w黄币

### ISSUE THREAD

**Issue by cbx25736** [LmeSzinc/AzurLaneAutoScript#3972]
### 你的功能请求是否与问题有关？

大世界购买商店是否应当保留至少10w黄币以避免在日常中遇到明石无法购买

### 解决方案

购买商店应当保留部分黄币以备购买明石，在月末可以考虑降低保留的部分

**Comment by LmeSzinc** [comment]
默认已保留
