### ISSUE TITLE
大世界“侵蚀1练级”会自动开启“短猫相接”

### ISSUE THREAD

**Issue by Mikuooo** [LmeSzinc/AzurLaneAutoScript#3977]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

好像是这次更新后出现的，之前没有这个情况。关闭短猫相接也没用，alas会尝试重启blhx后继续打开短猫相接。

### 如何复现

1. 勾选“侵蚀1练级”
2. 启动alas

### 预期行为

又试了以下，在练级海域才会执行侵蚀1练级，在其他海域还没执行侵蚀1链接就直接执行短猫相接了，所以这个预期行为参考意义可能不大

1. 勾选侵蚀1练级后启动alas
2. alas进入大世界并进入NA海域西南B
3. alas打开计划模式检查设置
4. alas开始自动作战
（以上都没问题）
5. alas**自动勾选**短猫相接
6. alas自动作战进入战斗
7. alas退出战斗退出海域开始执行短猫相接任务

### 相关 Logs

![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/56612689/43510086-4440-4f37-9edb-c78e4165090d)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/56612689/fce23d68-bdfe-4b22-a279-6ef1f466c36e)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/56612689/9b649c79-48f3-4a07-923e-48cdd0bbf0e4)

**Comment by Air111** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/2842#issuecomment-1621039068

**Comment by hanshYan955** [comment]
在短猫相接那里有个行动力保留，设置区间为1000-2000，如果你的体力箱子过多他也会自动开启短猫相接，你手动把短猫运行时间改到明天，他今天就不会再短猫了。除非白票小于10w

**Comment by Mikuooo** [comment]
> 在短猫相接那里有个行动力保留，设置区间为1000-2000，如果你的体力箱子过多他也会自动开启短猫相接，你手动把短猫运行时间改到明天，他今天就不会再短猫了。除非白票小于10w

好的，谢谢
