### ISSUE TITLE
日服 七期科研那不勒斯5小时识别失败

### ISSUE THREAD

**Issue by jichuan-zhang** [LmeSzinc/AzurLaneAutoScript#3983]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题，识别不出来这是个dr5

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
INFO     00:32:08.843 │ Research goto detail (project 3)                           
INFO     00:32:08.844 │ Click ( 797,  210) @ ENTRANCE_4                            
INFO     00:32:10.059 │ [DURATION_DETAIL 0.021s] 05:00:00                          
WARNING  00:32:10.179 │ Ship recognition failed                                    
WARNING  00:32:10.181 │ Invalid research S7-D-5 (Invalid)                          
INFO     00:32:10.182 │ [Project] S7-D-5 (Invalid)
```

### 截图

截图界面是这两张
![Screenshot_20240712-005622](https://github.com/user-attachments/assets/56ba7d89-6cca-4256-aee8-611360003c16)
![Screenshot_20240712-005625](https://github.com/user-attachments/assets/41573cd7-741f-4960-83ef-98f6aef85802)

**Comment by jichuan-zhang** [comment]
![Screenshot_20240712-005725](https://github.com/user-attachments/assets/46e9febc-9671-4bf0-9a97-958f1a5721c7)

**Comment by twd07** [comment]
一样的问题，这边2.5也识别不了，目测现在日服科研还不完善，相关问题更新前科研先手动吧。

**Comment by LmeSzinc** [comment]
1f20da207b204d18d0bbd7b0c46116e2ace5a058
