### ISSUE TITLE
疑似大世界索敌出错 [story option 0]

### ISSUE THREAD

**Issue by LccKitaku** [LmeSzinc/AzurLaneAutoScript#3991]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如图，因为是挂着后台并不清楚实际是在哪里出了问题，发现4个小时没跑完日常往回翻才发现大量反复出现的这样的代码段落
![QQ_1720905611155](https://github.com/user-attachments/assets/f13033bd-e571-42c8-af71-5e98fcc938a9)
![QQ_1720905611155](https://github.com/user-attachments/assets/23402135-999f-4e0a-9e90-94c0fb8afa5a)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

mumu12，其他功能均正常运行

**Comment by Air111** [comment]
上传`./log/error/1720905237502`

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
