### ISSUE TITLE
能否出击的时候增加个功能，当某个舰娘心情不足时进行切换到备选舰娘

### ISSUE THREAD

**Issue by senjyouhara** [LmeSzinc/AzurLaneAutoScript#3993]
### 你的功能请求是否与问题有关？

是

### 解决方案

目前出击的时候，当某个舰娘心情不足时是无法进行编队切换的，这部分只能进行手动干预，希望添加这个功能，可以通过名称添加备选舰娘

### 其他内容

![image](https://github.com/user-attachments/assets/b1cdf072-6736-4837-863d-2aa8c70d15b5)

**Comment by Air111** [comment]
配置好主线图2并开启，让它调度就行

**Comment by senjyouhara** [comment]
> 配置好主线图2并开启，让它调度就行

好吧，看来就是多个主线图互相切了
