### ISSUE TITLE
Perspective Transformation

### ISSUE THREAD

**Issue by asd111333** [LmeSzinc/AzurLaneAutoScript#4]
Hi LmeSzinz,

whoamikyo told me your project and I have read perspective.md. Very impressed, far better than my implementation. 

I created a fork of Egoistically/ALAuto. In the homg_trans_beta branch, I implemented the perspective transformation in another way. util/homg_trans.py contains all the related code. You may want to take a look.

After quickly scanned through your project, I think future development based on your code may be easier than the ALAuto project. So If you think it is okay, I would like to help this project to have better EN server support. Just tell we what you think should be added.

**Comment by whoamikyo** [comment]
99% of the EN assets already ok, I should do a PR soon to the main project.

**Comment by LmeSzinc** [comment]
Welcome.

I look whoamikyo's recent commit, know that current event of EN is iris of the light and dark
so optimise d2.py.
1. Add `MAP.spawn_data`, this records what spawns after each battle. Get this information by manully running through D2.
2. Write logistic in `Class Campaign`
Imitate event maps like campaign\event_20200423_cn\d3.py, campaign\event_20200521_cn\d1.py. Map logistics can be found in module/map/map.py

For the project,
try to use the reward mudule to recieve commission, see if it recognise english well.
If good, replace the dictionary in module/reward/commission.py. key: genre of commission, value: keywords of commission name.

**Comment by whoamikyo** [comment]
> Welcome.
> 
> I look whoamikyo's recent commit, know that current event of EN is iris of the light and dark
> so optimise d2.py.
> 
> 1. Add `MAP.spawn_data`, this records what spawns after each battle. Get this information by manully running through D2.
> 2. Write logistic in `Class Campaign`
>    Imitate event maps like campaign\event_20200423_cn\d3.py, campaign\event_20200521_cn\d1.py. Map logistics can be found in module/map/map.py
> 
> For the project,
> try to use the reward mudule to recieve commission, see if it recognise english well.
> If good, replace the dictionary in module/reward/commission.py. key: genre of commission, value: keywords of commission name.

Thanks for the feedback, incredibly even with these parameters the d2 map ran perfectly, but I will test it with your parameters too
