### ISSUE TITLE
有可能在手機上實現嗎

### ISSUE THREAD

**Issue by seriaati** [LmeSzinc/AzurLaneAutoScript#400]
我電腦太爛了模擬器打開電腦直接燒起來，有可能用usb連接手機之類的來達成腳本運行嗎。

**Comment by foreveruand** [comment]
是可以的，连接用的是adb，安卓手机也是支持adb的。开发者选项打开adb调试，地址设置正确就可以了，一般是手机的端口号是5555，安卓11可以直接在手机上开启无线调试，不需要USB连接（安卓11以下root后也可以用termux开启）。但是需要更改手机的分辨率。

**Comment by seriaati** [comment]
謝謝, 我會試試看的

**Comment by julystone** [comment]
问题是，alas需要分辨率1280*720，你的真机不一定是这种屏幕吧？

**Comment by laijirong** [comment]
> 问题是，alas需要分辨率1280*720，你的真机不一定是这种屏幕吧？

使用adb设置分辨率“adb shell wm size 1280x720”
