### ISSUE TITLE
新版本中无法选用Hermit模拟器控制方案

### ISSUE THREAD

**Issue by yzufo** [LmeSzinc/AzurLaneAutoScript#4003]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在最新的版本中，哪怕是手动选择了Hermit的模拟器控制方案。在运行后也会切换成minitouch.

版本回退到4f249ed1a此问题消失。

**Comment by Air111** [comment]
ff6307b

你是在什么设备上因为什么需要使用？

**Comment by yzufo** [comment]
> [ff6307b](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/ff6307b09df73d498f93c01f68d2587fb4b89fb4)
> 
> 你是在什么设备上因为什么需要使用？

使用在M系列芯片 Mac mini，Alas运行在Docker，模拟器是Android studio Virtual Device

**Comment by kenzining** [comment]
同样的问题，环境相同。

**Comment by LmeSzinc** [comment]
使用 DroidCast_raw 截图和 MaaTouch 点击

**Comment by yzufo** [comment]
> 使用 DroidCast_raw 截图和 MaaTouch 点击

修改配置后问题仍然存在。



INFO     16:37:51.973 │ [nemud.app_keep_alive]                                                   
INFO     16:37:51.977 │ Create forward: ForwardItem(serial='host.docker.internal:5555',          
         local='tcp:20397', remote='tcp:53516')                                                  
ERROR    16:37:51.986 │ ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end  
         closed connection without response'))                                                   
INFO     16:37:51.987 │ [Device Orientation] 0 (Normal)                                          
INFO     16:37:51.989 │ <<< DROIDCAST INIT >>>                                                   
INFO     16:37:51.991 │ Stopping DroidCast                                                       
INFO     16:37:52.147 │ ^ 10 1280 720 255                                                        
INFO     16:37:52.155 │ $ 255                                                                    
INFO     16:37:52.157 │ MaaTouch stream connected                                                
INFO     16:37:52.160 │ max_contact: 10; max_x: 1280; max_y: 720; max_pressure: 255              
WARNING  16:37:54.013 │ atx-agent has something wrong, auto recovering                           
INFO     16:37:54.016 │ device host.docker.internal:5555 is online                               
INFO     16:37:54.083 │ uiautomator2 version: 2.16.7                                             
INFO     16:37:54.089 │ Install minicap, minitouch                                               
INFO     16:37:54.090 │ Use cached assets: /app/pyroot/lib/python3.7/site-packages/uiautomator2ca
         che/cache/minitouch-f7a806902f/minitouch                                                
INFO     16:37:54.092 │ Push to /data/local/tmp/minitouch:0755                                   
INFO     16:37:54.113 │ apk-debug package-info: {'package_name': 'com.github.uiautomator',       
         'version_name': '2.3.3', 'version_code': '2003003', 'flags': ['DEBUGGABLE', 'HAS_CODE', 
         'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'], 'first_install_time': datetime.datetime(2024, 
         7, 18, 23, 9, 20), 'last_update_time': datetime.datetime(2024, 7, 18, 23, 9, 20),       
         'signature': 'ae17cd86], past signatures:['}                                            
INFO     16:37:54.116 │ apk-debug-test package-info: {'package_name':                            
         'com.github.uiautomator.test', 'version_name': '', 'version_code': '', 'flags':         
         ['DEBUGGABLE', 'HAS_CODE', 'ALLOW_CLEAR_USER_DATA', 'ALLOW_BACKUP'],                    
         'first_install_time': datetime.datetime(2024, 7, 18, 23, 9, 20), 'last_update_time':    
         datetime.datetime(2024, 7, 18, 23, 9, 20), 'signature': 'ae17cd86], past signatures:['} 
INFO     16:37:54.119 │ Already installed com.github.uiautomator apks                            
INFO     16:37:54.120 │ Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')                 
INFO     16:37:54.128 │ Install atx-agent 0.10.0                                                 
INFO     16:37:54.130 │ Use cached assets: /app/pyroot/lib/python3.7/site-packages/uiautomator2ca
         che/cache/atx-agent_0.10.0_linux_armv7.tar.gz-cf3333ae7b/atx-agent_0.10.0_linux_armv7.ta
         r.gz                                                                                    
INFO     16:37:54.250 │ Push to /data/local/tmp/atx-agent:0755                                   
INFO     16:37:54.286 │ Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr',
         '127.0.0.1:7912')                                                                       
INFO     16:37:54.291 │ Check atx-agent version                                                  
INFO     16:37:54.292 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:54.801 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:55.321 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:55.839 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:56.356 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:56.874 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:57.397 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:57.912 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:58.432 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
INFO     16:37:58.947 │ Forward: local:tcp:39079 -> remote:tcp:7912                              
ERROR    16:37:58.966 │ ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end  
         closed connection without response'))                                                   
         ╭───────────────────────── Traceback (most recent call last) ──────────────────────────╮
         │                                                                                      │
         │ /app/pyroot/lib/python3.7/site-packages/urllib3/connectionpool.py:710 in urlopen     │
         │                                                                                      │
         │    708 │   │   │   │   body=body,                                                    │
         │    709 │   │   │   │   headers=headers,                                              │
         │ ❱  710 │   │   │   │   chunked=chunked,                                              │
         │    711 │   │   │   )                                                                 │
         │    712                                                                               │
         │                                                                                      │
         │ ╭───────────────────────────────────── locals ─────────────────────────────────────╮ │
         │ │ _is_ssl_error_message_from_http_proxy = <function                                │ │
         │ │                                         HTTPConnectionPool.urlopen.<locals>._is… │ │
         │ │                                         at 0xffff7e2b8560>                       │ │
         │ │                      assert_same_host = False                                    │ │
         │ │                                  body = None                                     │ │
         │ │                              body_pos = None                                     │ │
         │ │                               chunked = False

**Comment by kenzining** [comment]
选择了maatouch后启动alas，一定概率会莫名其妙触发安装minicap, minitouch，log与楼上给出的log基本一致。

**Comment by LmeSzinc** [comment]
将这个atx-agent 推送进 /data/local/tmp
https://github.com/openatx/atx-agent/releases/download/0.10.0/atx-agent_0.10.0_linux_arm64.tar.gz

**Comment by yzufo** [comment]
> 将这个atx-agent 推送进 /data/local/tmp https://github.com/openatx/atx-agent/releases/download/0.10.0/atx-agent_0.10.0_linux_arm64.tar.gz

推送后问题解决。感谢。
@kenzining FYI

**Comment by kenzining** [comment]
问题解决，已连续稳定运行两天。
