### ISSUE TITLE
阴阳师在模拟器里如果脚本自动执行阴阳师就会卡在进入界面一直报错，如果手动进入游戏，脚本又会出现找不到游戏界面的错误。

### ISSUE THREAD

**Issue by lvk19941208** [LmeSzinc/AzurLaneAutoScript#4009]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

阴阳师在模拟器里如果脚本自动执行阴阳师就会卡在进入界面一直报错，如果手动进入游戏，脚本又会出现找不到游戏界面的错误。
![RJ3}XZTJ_@ _AOOQHXRCQDW](https://github.com/user-attachments/assets/7889e7a0-18ed-4962-bada-70739db9e4e0)
![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/13916e25-5ea2-438e-970d-adf18081e621)
![O{Y663 _O`2J SV{2AMJWL](https://github.com/user-attachments/assets/f2d6f734-1fb6-4466-9988-e032ad06a540)
![H7XMU3Z_0UGA_6}N (阴阳师在模拟器里如果脚本自动执行阴阳师就会卡在进入界面一直报错，如果手动进入游戏，脚本又会出现找不到游戏界面的错误。
![RJ3}XZTJ_@ _AOOQHXRCQDW](https://github.com/user-attachments/assets/7889e7a0-18ed-4962-bada-70739db9e4e0)
![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/13916e25-5ea2-438e-970d-adf18081e621)
![O{Y663 _O`2J SV{2AMJWL](https://github.com/user-attachments/assets/f2d6f734-1fb6-4466-9988-e032ad06a540)
3}F](https://github.com/user-attachments/assets/a63ce198-45c6-4fdb-ada1-52f8b905ba91)
![6BF D1X9E9FINU~QJU1$2ZC](https://github.com/user-attachments/assets/d2d9394e-0b9c-4759-9ea8-d48820789929)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望脚本能够正常运行

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── KEKKAIUTILIZE ─────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-19 20:28:21.988 | logger.py:333│ [Screen_size] 1280x720
INFO     2024-07-19 20:28:21.993 | script.py:350│ module_path:
         E:\YYSJB\OnmyojiAutoScript-easy-install\tasks\KekkaiUtilize\script_task.py, module_name: script_task
INFO     2024-07-19 20:28:22.137 | game_ui.py:96│ UI get current page
[I 240719 20:28:22 __init__:874] [pid:10576] [127.0.0.1:7555] newCommandTimeout updated to 168h0m0s
INFO     2024-07-19 20:28:22.209 | logger.py:333│ [u2.Device] Device(atx_agent_url=http://127.0.0.1:61450)
INFO     2024-07-19 20:28:22.275 | logger.py:333│ [Package_name] com.netease.onmyoji.wyzymnqsd_cps
INFO     2024-07-19 20:28:22.291 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
WARNING  2024-07-19 20:28:32.240 | game_ui.py:153│ Unknown ui page
INFO     2024-07-19 20:28:32.245 | logger.py:333│ [EMULATOR__SCREENSHOT_METHOD] ScreenshotMethod.WINDOW_BACKGROUND
INFO     2024-07-19 20:28:32.248 | logger.py:333│ [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH
WARNING  2024-07-19 20:28:32.251 | game_ui.py:156│ Starting from current page is not supported
WARNING  2024-07-19 20:28:32.266 | game_ui.py:157│ Supported page: ['page_main', 'page_summon', 'page_exploration',
         'page_town', 'page_awake_zones', 'page_soul_zones', 'page_realm_raid', 'page_goryou_realm', 'page_delegation',
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan', 'page_six_gates', 'page_bondling_fairyland',
         'page_kekkai_toppa', 'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel', 'page_hyakkisen',
         'page_shikigami_records', 'page_onmyodo', 'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',
         'page_collection']
WARNING  2024-07-19 20:28:32.288 | game_ui.py:158│ Supported page: Any page with a "HOME" button on the upper-right
CRITICAL 2024-07-19 20:28:32.301 | game_ui.py:159│ Please switch to a supported page before starting oas
INFO     2024-07-19 20:28:32.307 | script.py:377│ Game server may be under maintenance or network may be broken, check
         server status now
CRITICAL 2024-07-19 20:28:32.318 | script.py:379│ Game page unknown
WARNING  2024-07-19 20:28:32.323 | script.py:96│ Saving error: ./log/error/1721392112323
INFO     2024-07-19 20:28:32.379 | config.py:377│ Notifier: OAS1
INFO     2024-07-19 20:28:32.388 | script_process.py:139│ Script oas1 process exit
ERROR    2024-07-19 20:28:32.402 | logger.py:363│ Error: 1
```

### 截图

![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/39c0cd69-7346-4321-8df0-fef7fdd03da3)
![6BF D1X9E9FINU~QJU1$2ZC](https://github.com/user-attachments/assets/3e1d9064-6d3e-4678-b441-5700680a035a)
![H7XMU3Z_0UGA_6}N (![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/39c0cd69-7346-4321-8df0-fef7fdd03da3)
![6BF D1X9E9FINU~QJU1$2ZC](https://github.com/user-attachments/assets/3e1d9064-6d3e-4678-b441-5700680a035a)
3}F](https://github.com/user-attachments/assets/13d17977-622e-4132-a496-ed744be6b928)
![O{Y663 _O`2J SV{2AMJWL](https://github.com/user-attachments/assets/0f3e2afe-e291-4edf-af9d-f33d4e900b99)
![RJ3}XZTJ_@ _AOOQHXRCQDW](https://github.com/user-attachments/assets/7c6b8fe2-3376-4b76-9c7c-e54eeedbc337)

### 还有别的吗？

没有了

**Comment by guoh064** [comment]
你走错repo了吧……？

**Comment by lvk19941208** [comment]
> 你走错repo了吧……？

啊啊啊啊，对不起
