### ISSUE TITLE
请问作战档案怎么设置成每天只打4次。

### ISSUE THREAD

**Issue by yszseraph** [LmeSzinc/AzurLaneAutoScript#4032]
### 你的功能请求是否与问题有关？

作战档案里只能设置打几次，打完后就停止移出调度器了。第二天又要自己手动加入调度器。

### 解决方案

请问能否像活动每日那样，固定每天打几次。

**Comment by Air111** [comment]
你只需把功能开着，不需要设置停止条件，档案密钥用完后任务会自己推迟到明天

**Comment by yszseraph** [comment]
> 你只需把功能开着，不需要设置停止条件，档案密钥用完后任务会自己推迟到明天

这样就必须把60次都清空才能实现吗？我想设置保持60次余量，之后每天只打4次，然后领取4次，请问这样设置可以实现吗？
