### ISSUE TITLE
错误操作卡设置界面

### ISSUE THREAD

**Issue by FlowerLing** [LmeSzinc/AzurLaneAutoScript#4034]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

环境win11 mumu12 1280*720 directX  
alas执行以下步骤，有概率进入设置界面导致识别错误
═════════════════════════════════════ OS INIT ═════════════════════════════════════
INFO     09:45:50.568 │ OS INIT                                                    
INFO     09:45:50.615 │ <<< UI ENSURE >>>                                          
INFO     09:45:50.620 │ UI get current page                                        
INFO     09:45:50.733 │ [UI] page_meta                                             
INFO     09:45:50.735 │ Goto page_os                                               
INFO     09:45:50.742 │ <<< UI GOTO PAGE_OS >>>                                    
INFO     09:45:50.805 │ Page switch: page_meta -> page_main                        
INFO     09:45:50.810 │ Click (1239,   37) @ GOTO_MAIN                             
INFO     09:45:54.299 │ UI additional: META_CHECK -> GOTO_MAIN                     
INFO     09:45:54.305 │ Click (1224,   38) @ GOTO_MAIN                             
INFO     09:47:38.697 │ Page switch: page_main_white -> page_campaign_menu         
INFO     09:47:38.700 │ Click (1154,  490) @ MAIN_GOTO_CAMPAIGN_WHITE      

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═════════════════════════════════════ OS INIT ═════════════════════════════════════
INFO     09:45:50.568 │ OS INIT                                                    
INFO     09:45:50.615 │ <<< UI ENSURE >>>                                          
INFO     09:45:50.620 │ UI get current page                                        
INFO     09:45:50.733 │ [UI] page_meta                                             
INFO     09:45:50.735 │ Goto page_os                                               
INFO     09:45:50.742 │ <<< UI GOTO PAGE_OS >>>                                    
INFO     09:45:50.805 │ Page switch: page_meta -> page_main                        
INFO     09:45:50.810 │ Click (1239,   37) @ GOTO_MAIN                             
INFO     09:45:54.299 │ UI additional: META_CHECK -> GOTO_MAIN                     
INFO     09:45:54.305 │ Click (1224,   38) @ GOTO_MAIN                             
INFO     09:47:38.697 │ Page switch: page_main_white -> page_campaign_menu         
INFO     09:47:38.700 │ Click (1154,  490) @ MAIN_GOTO_CAMPAIGN_WHITE
```

### 截图

![QQ图片20240726114715](https://github.com/user-attachments/assets/c37e1e78-d6cd-414b-ae73-83cb57e25a50)

**Comment by FlowerLing** [comment]
完整报错log如下

INFO     12:08:23.785 │ <<< UI ENSURE >>>                                          
INFO     12:08:23.787 │ UI get current page                                        
INFO     12:08:23.796 │ [UI] page_main                                             
INFO     12:08:23.798 │ Goto page_exercise                                         
INFO     12:08:23.801 │ <<< UI GOTO PAGE_EXERCISE >>>                              
INFO     12:08:23.808 │ Page switch: page_main_white -> page_campaign_menu         
INFO     12:08:23.810 │ Click (1224,  500) @ MAIN_GOTO_CAMPAIGN_WHITE              
INFO     12:08:24.573 │ Page switch: page_event_list -> page_main                  
INFO     12:08:24.575 │ Click (1238,   39) @ GOTO_MAIN                             
INFO     12:08:25.014 │ Click (1009,  639) @ GET_ITEMS_1                           
INFO     12:08:25.646 │ UI additional: EVENT_LIST_CHECK -> GOTO_MAIN               
INFO     12:08:25.648 │ Click (1238,   41) @ GOTO_MAIN                             
INFO     12:08:26.665 │ Page switch: page_event_list -> page_main                  
INFO     12:08:26.666 │ Click (1239,   28) @ GOTO_MAIN                             
INFO     12:11:26.918 │ Function calls:                                            
                   <string>   L1 <module>                                          
                   spawn.py L105 spawn_main()                                      
                   spawn.py L118 _main()                                           
                 process.py L297 _bootstrap()                                      
                 process.py  L99 run()                                             
         process_manager.py L152 run_process()                                     
                    alas.py L537 loop()                                            
                    alas.py  L69 run()                                             
                    alas.py L246 exercise()                                        
                exercise.py L201 run()                                             
                      ui.py L283 ui_ensure()                                       
                      ui.py L238 ui_goto()                                         
                  device.py L175 screenshot()                                      
                  device.py L237 stuck_record_check()                              
                  device.py  L43 show_function_call()                              
WARNING  12:11:26.922 │ Wait too long                                              
WARNING  12:11:26.924 │ Waiting for {'AUTO_SEARCH_REWARD', 'TACTICAL_CHECK',       
         'COMMISSION_CHECK', 'GET_SHIP', 'GUILD_POPUP_CONFIRM', 'OS_CHECK',        
         'DAILY_CHECK', 'EVENT_LIST_CHECK', 'COALITION_ACADEMY_MAIN_CHECK',        
         'RESEARCH_CHECK', 'MAINTENANCE_ANNOUNCE', 'BUILD_CHECK', 'EXERCISE_CHECK',
         'MEOWFFICER_BUY', 'STORY_SKIP_3', 'WITHDRAW', 'SUPPLY_PACK_CHECK',        
         'LOGIN_RETURN_SIGN', 'MEOWFFICER_CHECK', 'FLEET_CHECK', 'SHOP_CHECK',     
         'EVENT_CHECK', 'META_CHECK', 'MONTHLY_PASS_NOTICE', 'CAMPAIGN_CHECK',     
         'LOGIN_ANNOUNCE', 'POPUP_SINGLE_WHITE', 'MEOWFFICER_INFO',                
         'COALITION_ACADEMY_CAMPAIGN_CHECK', 'EXCHANGE_CHECK',                     
         'WAR_ARCHIVES_CHECK', 'DORM_INFO', 'DORMMENU_CHECK', 'RESET_TICKET_POPUP',
         'MUNITIONS_CHECK', 'RESET_FLEET_PREPARATION', 'PURCHASE_POPUP',           
         'FLEET_PREPARATION', 'RAID_FLEET_PREPARATION', 'GET_MISSION',             
         'EXERCISE_PREPARATION', 'POPUP_CONFIRM_WHITE', 'GET_ITEMS_2', 'SP_CHECK', 
         'CAMPAIGN_MENU_CHECK', 'RAID_CHECK', 'DORM_CHECK', 'RESHMENU_CHECK',      
         'MAIN_GOTO_FLEET', 'MAIN_GOTO_MEMORIES_WHITE', 'LOGIN_CHECK',             
         'GUILD_CHECK', 'POPUP_CANCEL', 'DORM_TROPHY_CONFIRM', 'MAP_PREPARATION',  
         'STORAGE_CHECK', 'ACADEMY_CHECK', 'GAME_ROOM_CHECK', 'MAIL_CHECK',        
         'GET_ITEMS_1', 'MAIN_GOTO_CAMPAIGN_WHITE', 'PLAYER_CHECK',                
         'SHIPYARD_CHECK', 'BATTLE_PASS_NOTICE', 'STORY_CLOSE', 'DORM_FEED_CANCEL',
         'AUTO_SEARCH_MENU_EXIT', 'BATTLE_PASS_CHECK', 'MISSION_CHECK',            
         'REWARD_CHECK', 'GAME_TIPS', 'LOGIN_ANNOUNCE_2'}                          
INFO     12:11:27.031 │ [Package_name] com.bilibili.azurlane                       
ERROR    12:11:27.033 │ GameStuckError: Wait too long                              
WARNING  12:11:27.034 │ Saving error: ./log/error/1721967087034                    
WARNING  12:11:27.146 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  12:11:27.148 │ If you are playing by hand, please stop Alas               
INFO     12:11:27.150 │ Task call: Restart                                         
INFO     12:11:27.165 │ Bind task ['General', 'Alas', 'Exercise']                  
INFO     12:11:27.167 │ Save config ./config\灵(大世界).json,                      
         Restart.Scheduler.NextRun=datetime.datetime(2024, 7, 26, 12, 11, 27),     
         Restart.Scheduler.Enable=True                                             
INFO     12:11:37.174 │ Scheduler: End task `Exercise`                             
CRITICAL 12:11:37.175 │ Task `Exercise` failed 3 or more times.                    
CRITICAL 12:11:37.176 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 12:11:37.178 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 12:11:37.181 │ Request human takeover                                     
INFO     12:11:37.368 │ No provider specified, skip sending

**Comment by zenosai** [comment]
+1，出现好久了

**Comment by LaSibyl** [comment]
+1,经常会卡在设置界面

**Comment by zenosai** [comment]
主要原因是`Page switch`与`UI additional`之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。
![image](https://github.com/user-attachments/assets/5ded6112-2058-4e3d-b666-494aee06f160)
或许在`self.device.click(button)`后可以增加少量延迟再执行`self.ui_additional()`

**Comment by FlowerLing** [comment]
> 主要原因是`Page switch`与`UI additional`之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。 ![image](https://private-user-images.githubusercontent.com/92961570/358975387-5ded6112-2058-4e3d-b666-494aee06f160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTQ2MDEsIm5iZiI6MTcyNDUxNDMwMSwicGF0aCI6Ii85Mjk2MTU3MC8zNTg5NzUzODctNWRlZDYxMTItMjA1OC00ZTNkLWI2NjYtNDk0YWVlMDZmMTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE1NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDE2MDYwODJhNzllYTY1NjM1NzU2ODU2NGY4OGZjZDc2N2Y4ZGY4OWMzNzQ0ODRjOGFjOGMwYzM0ZWQzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iE2nS5Q35KbdOOboj1AcfpPFcK8tCW3UXQWtkXebk0E) 或许在`self.device.click(button)`后可以增加少量延迟再执行`self.ui_additional()`

谢谢帮助！经过几天测试后在两句中间加入sleep函数（我设置的3秒，time.sleep(3)）可以有效解决该问题，但是每次启动alas时候会自动同步回原代码，我看也有一些用户反映该问题，官方后续会考虑在在新版资源中加入该句吗？

**Comment by chenfan226** [comment]
> > 主要原因是`Page switch`与`UI additional`之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。 ![image](https://private-user-images.githubusercontent.com/92961570/358975387-5ded6112-2058-4e3d-b666-494aee06f160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MTQ2MDEsIm5iZiI6MTcyNDUxNDMwMSwicGF0aCI6Ii85Mjk2MTU3MC8zNTg5NzUzODctNWRlZDYxMTItMjA1OC00ZTNkLWI2NjYtNDk0YWVlMDZmMTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDE1NDUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDE2MDYwODJhNzllYTY1NjM1NzU2ODU2NGY4OGZjZDc2N2Y4ZGY4OWMzNzQ0ODRjOGFjOGMwYzM0ZWQzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iE2nS5Q35KbdOOboj1AcfpPFcK8tCW3UXQWtkXebk0E) 或许在`self.device.click(button)`后可以增加少量延迟再执行`self.ui_additional()`
> 
> 谢谢帮助！经过几天测试后在两句中间加入sleep函数（我设置的3秒，time.sleep(3)）可以有效解决该问题，但是每次启动alas时候会自动同步回原代码，我看也有一些用户反映该问题，官方后续会考虑在在新版资源中加入该句吗？

能展示一下您修改过后的代码吗？

**Comment by FlowerLing** [comment]
对目录中的module/ui/ui.py中258行的self.device.click(button)​
与
self.ui_button_interval_reset(button)之间加入time.sleep(3)实际上也许可以更短，考虑到网络波动等卡顿问题设置了延迟3秒，自上次修改至今未再次复现原反馈的问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LmeSzinc/AzurLaneAutoScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月10日(星期二) 晚上8:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LmeSzinc/AzurLaneAutoScript] 错误操作卡设置界面 (Issue #4034)





   
主要原因是Page switch与UI additional之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。  或许在self.device.click(button)后可以增加少量延迟再执行self.ui_additional()
  
谢谢帮助！经过几天测试后在两句中间加入sleep函数（我设置的3秒，time.sleep(3)）可以有效解决该问题，但是每次启动alas时候会自动同步回原代码，我看也有一些用户反映该问题，官方后续会考虑在在新版资源中加入该句吗？
  
能展示一下您修改过后的代码吗？

**Comment by chenfan226** [comment]
> 对目录中的module/ui/ui.py中258行的self.device.click(button)​与 self.ui_button_interval_reset(button)之间加入time.sleep(3)实际上也许可以更短，考虑到网络波动等卡顿问题设置了延迟3秒，自上次修改至今未再次复现原反馈的问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LmeSzinc/AzurLaneAutoScript" ***@***.***&gt;; 发送时间:&nbsp;2024年9月10日(星期二) 晚上8:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [LmeSzinc/AzurLaneAutoScript] 错误操作卡设置界面 (Issue #4034) 主要原因是Page switch与UI additional之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。 或许在self.device.click(button)后可以增加少量延迟再执行self.ui_additional() 谢谢帮助！经过几天测试后在两句中间加入sleep函数（我设置的3秒，time.sleep(3)）可以有效解决该问题，但是每次启动alas时候会自动同步回原代码，我看也有一些用户反映该问题，官方后续会考虑在在新版资源中加入该句吗？ 能展示一下您修改过后的代码吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢，并且在首部声明time函数对吗 (import time)

**Comment by FlowerLing** [comment]
嗯嗯，需要声明一下&nbsp;


花花
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月10日(星期二) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LmeSzinc/AzurLaneAutoScript] 错误操作卡设置界面 (Issue #4034)














  
对目录中的module/ui/ui.py中258行的self.device.click(button)​与 self.ui_button_interval_reset(button)之间加入time.sleep(3)实际上也许可以更短，考虑到网络波动等卡顿问题设置了延迟3秒，自上次修改至今未再次复现原反馈的问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LmeSzinc/AzurLaneAutoScript" @.&gt;; 发送时间:&nbsp;2024年9月10日(星期二) 晚上8:26 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [LmeSzinc/AzurLaneAutoScript] 错误操作卡设置界面 (Issue #4034) 主要原因是Page switch与UI additional之间的问题，前一个点击后页面跳转会有延迟而后一个又检测到需要跳转，造成在主页面重复点击跳转主页面按钮而实际上是设置按钮，导致卡在设置页面。 或许在self.device.click(button)后可以增加少量延迟再执行self.ui_additional() 谢谢帮助！经过几天测试后在两句中间加入sleep函数（我设置的3秒，time.sleep(3)）可以有效解决该问题，但是每次启动alas时候会自动同步回原代码，我看也有一些用户反映该问题，官方后续会考虑在在新版资源中加入该句吗？ 能展示一下您修改过后的代码吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
感谢，并且在首部声明time函数对吗 (import time)

**Comment by LmeSzinc** [comment]
Alas 禁止使用 sleep，写个 sleep(3) 还好意思乱教别人我是真的救命
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/1.-Start

![对于这类程序员建议他们尽早转行](https://github.com/user-attachments/assets/41210234-432f-4c9e-9403-7ad5104a8c3b)
