### ISSUE TITLE
希望Alas的Maa插件的自动肉鸽里的肉鸽主题添加“萨卡兹的无终奇语”选项

### ISSUE THREAD

**Issue by Gruddieu** [LmeSzinc/AzurLaneAutoScript#4043]
### 你的功能请求是否与问题有关？

Maa最新稳定版（V5.5.0）更新了“萨卡兹的无终奇语”肉鸽主题，所以希望Alas的Maa插件里的自动肉鸽的肉鸽主题能添加一下

### 解决方案

Alas的Maa插件的自动肉鸽里的肉鸽主题可选“萨卡兹的无终奇语”选项

### 其他内容

![屏幕截图 2024-07-30 140202](https://github.com/user-attachments/assets/425b0be4-2012-4a35-bc39-6e9012638911)
![屏幕截图 2024-07-30 140241](https://github.com/user-attachments/assets/e9f2ae0f-5fb4-4bd5-a981-387e0ead1c2f)
![屏幕截图 2024-07-30 140259](https://github.com/user-attachments/assets/f8696a9a-a53c-4cc8-b20a-32fbf8a91671)

**Comment by Shawn88-ops** [comment]
附议+1
