### ISSUE TITLE
星界链云手机的ALAS无法更改截图方案和点击方案

### ISSUE THREAD

**Issue by wuming121464** [LmeSzinc/AzurLaneAutoScript#4048]
### 你的功能请求是否与问题有关？

是，在星界链的云手机里运行alas性能测试，有更快的截图方案（aScreenCap），但是选择后会恢复到默认的DroidCast_raw，点击方案也是一样

### 解决方案

希望可以允许更改星界链云手机内alas的截图方案和点击方案，就如本地alas一样

### 其他内容

![性能测试](https://github.com/user-attachments/assets/d8df6c4a-b370-4c93-8a7b-c939c2be4999)

**Comment by MengNianxiaoyao** [comment]
星界链的好像是在代码中锁定了截图方案，因为其他方案截图有问题

**Comment by wuming121464** [comment]
> 星界链的好像是在代码中锁定了截图方案，因为其他方案截图有问题

**Comment by MengNianxiaoyao** [comment]
DroidCast_raw已经是除两个黑科技之外最快的了，而且你测试出来最快的那个截出的图不一定不是黑的
