### ISSUE TITLE
请求添加开启白、蓝、紫箱子以及分解装备的功能

### ISSUE THREAD

**Issue by BlasterJackOne** [LmeSzinc/AzurLaneAutoScript#4058]
### 你的功能请求是否与问题有关？

在急需物资的情况下，“后备隐藏能源”装备箱就要起作用了，虽然平时囤到的箱子实际上可以算作收益，但是真到了缺物资的时候手动打开分解又是非常麻烦的事情，今天做科研看到做实验品募集时，我观察到脚本会自动去仓库开箱子并分解装备满足科研，所以请求添加这一功能到外部可选功能

### 解决方案

科研任务的实验品募集任务会自动到仓库里开箱子，只需要移植成新的功能就可以了，也许可以添加一下蓝箱子（甚至紫箱子）的兼容，当然这样分解的装备稀有度也需要一定程度调整

### 其他内容

无

**Comment by LmeSzinc** [comment]
游戏内已有类似功能
![image](https://github.com/user-attachments/assets/3be73917-8dff-49e7-98b3-3fecbd90dd28)
