### ISSUE TITLE
指挥猫添加功能 当物资大于设置的数值时，自动购买设置数量的猫

### ISSUE THREAD

**Issue by yuzhiyizhan** [LmeSzinc/AzurLaneAutoScript#4059]
### 你的功能请求是否与问题有关？

指挥猫添加功能 当物资大于设置的数值时，自动购买设置数量的猫

### 解决方案

指挥猫添加功能 当物资大于设置的数值时，自动购买设置数量的猫

### 其他内容

每天刷13-4 天天买物资不够，不买了又溢出，所以想请求添加这个功能，如果没必要就算了，谢谢大佬

**Comment by LmeSzinc** [comment]
打开 `通用商店` - `军火商` - `消耗溢出物资`
![image](https://github.com/user-attachments/assets/2310a7f4-dfc3-42d7-8d23-c9915dcbecaf)
