### ISSUE TITLE
log 日志目录能自定义生成位置吗

### ISSUE THREAD

**Issue by Liu-BQ** [LmeSzinc/AzurLaneAutoScript#4067]
### 你的功能请求是否与问题有关？

log 日志目录能自定义生成位置吗，比如说现在项目目录实在  /app/alas/AzurLaneAutoScript   ,想让日志生成在 /app/alas/alas_log下

**Comment by LmeSzinc** [comment]
不能，程序产生的文件不应超出自身所在的文件夹，你需要自己创建 linux 文件链接
