### ISSUE TITLE
小游戏卡住

### ISSUE THREAD

**Issue by fhwhite** [LmeSzinc/AzurLaneAutoScript#4070]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

小游戏每月上限10000点已经拿到，刚才发现报错，小游戏卡住了，想修改小游戏时间到下个月月初也不行，设置里改完了，实际运行还是当前时间，只能暂时关闭

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                     MINIGAME                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     01:04:35.154 │ Connecting to local emulator, using host 192.168.123.109   
INFO     01:04:35.162 │ [Device Orientation] 0 (Normal)                            
INFO     01:04:35.163 │ Reuse forward: ForwardItem(serial='emulator-5554',         
         local='tcp:20910', remote='localabstract:minitouch')                      
INFO     01:04:35.171 │ v 1                                                        
INFO     01:04:35.172 │ ^ 2 32767 32767 0                                          
INFO     01:04:35.173 │ $ 19597                                                    
INFO     01:04:35.174 │ minitouch running on port: 20910, pid: 19597               
INFO     01:04:35.175 │ max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
INFO     01:04:35.175 │ Reverse server listening on 192.168.123.109:20639, client  
         can send data to 192.168.123.109:20639                                    
INFO     01:04:35.185 │ sdk_ver: 25                                                
INFO     01:04:35.194 │ [nc command] ['nc']                                        
INFO     01:04:35.412 │ [Screen_size] 1280x720                                     
INFO     01:04:35.594 │ early_ocr_import call                                      
INFO     01:04:35.595 │ early_ocr_import start                                     
INFO     01:04:35.596 │ <<< UI ENSURE >>>                                          
INFO     01:04:35.598 │ UI get current page                                        
INFO     01:04:35.600 │ Loading OCR dependencies                                   
INFO     01:04:36.522 │ [UI] page_academy                                          
INFO     01:04:36.523 │ Goto page_game_room                                        
INFO     01:04:36.525 │ <<< UI GOTO PAGE_GAME_ROOM >>>                             
INFO     01:04:36.553 │ Page switch: page_academy -> page_game_room                
INFO     01:04:36.555 │ Click (1079,  356) @ ACADEMY_GOTO_GAME_ROOM                
INFO     01:04:36.625 │ early_ocr_import finish                                    
INFO     01:04:37.885 │ Page arrive: page_game_room                                
INFO     01:04:37.941 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     01:04:38.001 │ [COIN_HOLDER 0.070s] 10                                    
INFO     01:04:38.003 │ coin count : 10                                            
INFO     01:04:38.052 │ coin count > 0, spend                                      
══════════════════════════════════ MINIGAME RUN ═══════════════════════════════════
INFO     01:04:38.055 │ MINIGAME RUN                                               
INFO     01:04:38.056 │ Enter minigame                                             
INFO     01:04:38.068 │ Click (1063,  660) @ GOTO_CHOOSE_GAME                      
INFO     01:04:38.597 │ Choose minigame                                            
INFO     01:04:38.614 │ [MINIGAME_SCROLL_AREA] 0.00                                
         (102.68811881188118-101.0)/(560-202)                                      
INFO     01:04:38.616 │ MINIGAME_SCROLL_AREA set to 1.0                            
INFO     01:04:38.617 │ [MINIGAME_SCROLL_AREA] 0.00                                
         (102.68811881188118-101.0)/(560-202)                                      
INFO     01:04:38.618 │ Swipe (1228,  185) -> (1226,  716)                         
INFO     01:04:39.527 │ [MINIGAME_SCROLL_AREA] 0.84 (461.5-15.0)/(560-30)          
INFO     01:04:39.697 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:40.017 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:40.294 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:40.600 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:40.888 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:41.171 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:41.498 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:41.801 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:42.106 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:42.368 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:42.682 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:43.006 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)                                      
INFO     01:04:43.305 │ [MINIGAME_SCROLL_AREA] 0.99                                
         (456.68811881188117-101.0)/(560-202)
```

**Comment by BleakMaple** [comment]
我同样遇到了这个问题

**Comment by rsgzl-true** [comment]
我的有GameStuckError:Wait too long报错：
2024-08-09 10:29:13.655 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:13.845 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:14.046 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:14.248 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:14.446 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:14.647 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)                      
2024-08-09 10:29:14.847 | INFO | [MINIGAME_SCROLL_AREA] 0.99 (456.68811881188117-101.0)/(560-202)   
2024-08-09 10:29:14.850 | INFO | Function calls:                                                                       
             <string>   L1 <module>                                                                                    
             spawn.py L105 spawn_main()                                                                                
             spawn.py L118 _main()                                                                                     
           process.py L297 _bootstrap()                                                                                
           process.py  L99 run()                                                                                       
   process_manager.py L152 run_process()                                                                               
              alas.py L537 loop()                                                                                      
              alas.py  L69 run()                                                                                       
              alas.py L234 minigame()                                                                                  
          minigame.py L202 run()                                                                                       
          minigame.py  L43 minigame_run()                                                                              
new_year_challenge.py  L43 choose_game()                                                                               
            device.py L175 screenshot()                                                                                
            device.py L237 stuck_record_check()                                                                        
            device.py  L43 show_function_call()                                                                        
2024-08-09 10:29:14.853 | WARNING | Wait too long                                                                      
2024-08-09 10:29:14.854 | WARNING | Waiting for {'COIN_POPUP', 'GAME_ROOM_CHECK', 'NEW_YEAR_CHALLENGE_ENTRANCE',       
'NEW_YEAR_CHALLENGE_FIRST_TIME', 'GOTO_CHOOSE_GAME', 'NEW_YEAR_CHALLENGE_START', 'GET_ITEMS_1'}                        
2024-08-09 10:29:14.920 | INFO | [Package_name] com.bilibili.azurlane                                                  
2024-08-09 10:29:14.920 | ERROR | GameStuckError: Wait too long                                                        
2024-08-09 10:29:14.922 | WARNING | Saving error: ./log/error/1723170554922
以下是完整errLog文件         
[1723170554922.zip](https://github.com/user-attachments/files/16555247/1723170554922.zip)

**Comment by Frocean** [comment]
同样的问题

**Comment by rsgzl-true** [comment]
盲猜是写死了滑动到最底端，小游戏是固定玩新年对决，而官方昨天维护后追加了一些小游戏，现在滑动到最底就不是新年对决了
“5.「啾啾游戏屋」新增常驻玩法：「蛋糕保卫战」、「啾啾大冒险」、「抚顺大冒险Ⅱ」、「啾啾雪合战」、「糖果与魔法之夜」、「啾啾转转乐」”

**Comment by YeQing5566** [comment]
INFO     16:42:43.300 │ Function calls:                                            
                      <string>   L1 <module>                                       
                      spawn.py L105 spawn_main()                                   
                      spawn.py L118 _main()                                        
                    process.py L297 _bootstrap()                                   
                    process.py  L99 run()                                          
            process_manager.py L152 run_process()                                  
                       alas.py L537 loop()                                         
                       alas.py  L69 run()                                          
                       alas.py L234 minigame()                                     
                   minigame.py L202 run()                                          
                   minigame.py  L43 minigame_run()                                 
         new_year_challenge.py  L43 choose_game()                                  
                     device.py L175 screenshot()                                   
                     device.py L237 stuck_record_check()                           
                     device.py  L43 show_function_call()                           
WARNING  16:42:43.302 │ Wait too long                                              
WARNING  16:42:43.303 │ Waiting for {'NEW_YEAR_CHALLENGE_FIRST_TIME',              
         'NEW_YEAR_CHALLENGE_START', 'GET_ITEMS_1', 'COIN_POPUP',                  
         'GOTO_CHOOSE_GAME', 'NEW_YEAR_CHALLENGE_ENTRANCE', 'GAME_ROOM_CHECK'}     
INFO     16:42:43.475 │ [Package_name] com.bilibili.azurlane                       
ERROR    16:42:43.476 │ GameStuckError: Wait too long                              
WARNING  16:42:43.477 │ Saving error: ./log/error/1723192963477                    
WARNING  16:42:43.706 │ Game stuck, com.bilibili.azurlane will be restarted in 10  
         seconds                                                                   
WARNING  16:42:43.708 │ If you are playing by hand, please stop Alas               
INFO     16:42:43.709 │ Task call: Restart                                         
INFO     16:42:43.717 │ Bind task ['General', 'Alas', 'Minigame']                  
INFO     16:42:43.718 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2024, 8, 9, 16, 42, 43),      
         Restart.Scheduler.Enable=True                                             
INFO     16:42:53.723 │ Scheduler: End task `Minigame`                             
CRITICAL 16:42:53.725 │ Task `Minigame` failed 3 or more times.                    
CRITICAL 16:42:53.726 │ Possible reason #1: You haven't used it correctly. Please  
         read the help text of the options.                                        
CRITICAL 16:42:53.727 │ Possible reason #2: There is a problem with this task.     
         Please contact developers or try to fix it yourself.                      
CRITICAL 16:42:53.728 │ Request human takeover                                     
INFO     16:42:54.105 │ No provider specified, skip sending

**Comment by rsgzl-true** [comment]
pr里已经有一个修复了，#4069，等管理员审核就好

**Comment by Dr-NaCl** [comment]
这个是新加了小游戏导致的问题

**Comment by saltyfish71** [comment]
请问，现在好了吗？我在新的更新过后，小游戏出现了新的bug。

**Comment by saltyfish71** [comment]
还是关于小游戏的，点进打年糕以后，经常继续在原来滑动条的部分接着滑动。

**Comment by YeQing5566** [comment]
请问是还没修复么

**Comment by saltyfish71** [comment]
> 请问是还没修复么

貌似是的，而且最近还要等活动的更新
