### ISSUE TITLE
报错后推送通知到邮箱等渠道（或windows系统通知弹窗）

### ISSUE THREAD

**Issue by YeQing5566** [LmeSzinc/AzurLaneAutoScript#4071]
### 你的功能请求是否与问题有关？

后台运行或者云电脑挂机容易关注不到运行状况，报错请求人工干预后会延误很久，请求添加通知推送功能，最好是可以推送通知到邮箱等通讯渠道，因为不了解开发难度，如难以实现还请见谅

**Comment by Air111** [comment]
alas设置-调试设置-错误推送设置

**Comment by NJUsunset** [comment]
这个功能已经实现了
