### ISSUE TITLE
作战档案无法顺利运行

### ISSUE THREAD

**Issue by 965652556** [LmeSzinc/AzurLaneAutoScript#4081]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

作战档案无法顺利运行

### 如何复现

1. 前往 ‘活动'
2. 点击 '作战档案'
3. 设置好 '作战档案'
4. 启动alas
5. 出现问题

**Comment by Air111** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%B8%8A%E6%8A%A5bug-how-to-report-bugs
