### ISSUE TITLE
侵蚀1模块暂停运行之后进行其他项目，完成后回到侵蚀1时不会检查当前海域

### ISSUE THREAD

**Issue by NJUsunset** [LmeSzinc/AzurLaneAutoScript#4082]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当调度器中的其他任务触发之后，Alas会退出当前的侵蚀1战斗并进行其他任务。完成任务返回大世界进行侵蚀1时，Alas并不会启动自律作战完成当前海域的工作，而是直接点击计划任务触发刷新海域。这会导致损失当前海域的白币收入，以及可能的猫点行动力损失。
同样的问题也出现在从其他海域（比如港口）进入侵蚀1海域时，进入海域这个行为会消耗5行动力并刷新海域，而Alas并不会清理当前海域而直接点击计划任务，这种行为会让大世界直接刷新当前海域，导致损失白币和可能的行动力。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

在触发侵蚀1任务后以及从其他海域跳转到侵蚀1海域时，首先运行自律作战清理当前海域，检查猫点和其他特殊设施，完成之后再开启计划任务进入通常的侵蚀1流程。

### 还有别的吗？

附一张设置图以确认设置正确
![image](https://github.com/user-attachments/assets/cfe84815-994b-4c4e-90f3-de89e267f948)

**Comment by Air111** [comment]
#2367

**Comment by NJUsunset** [comment]
> #2367

感谢
