### ISSUE TITLE
所有敌人均会移动的地图优先清理距离最近的敌人

### ISSUE THREAD

**Issue by Air111** [LmeSzinc/AzurLaneAutoScript#4095]
### 你的功能请求是否与问题有关？

而不是优先按`ENEMY_FILTER`的顺序

**Comment by noah47MP** [comment]
新活动里sp开荒时的精英怪会移动，但其他不会移动。故在清理完精英怪后会滞留在sp中不动

**Comment by Air111** [comment]
> 新活动里sp开荒时的精英怪会移动，但其他不会移动。故在清理完精英怪后会滞留在sp中不动

什么意思
