### ISSUE TITLE
Project Identity Auto Farmer 

### ISSUE THREAD

**Issue by ShiroBlank** [LmeSzinc/AzurLaneAutoScript#4097]
### Is your feature request related to a problem?

I think implementing a bot that automatically completes project identity would be nice.

### Describe the solution you'd like

n/a

### Additional context

n/a

**Comment by LmeSzinc** [comment]
No plans.

> it's literally a pure story VN
it's only purpose is for YOU to read it, it has no gameplay bonuses at all
skipping it with alas is pointless, you achieve the same effect by just not interacting with it

said Jiur
