### ISSUE TITLE
刷紧急委托时，后排角色到达33级后继续出击

### ISSUE THREAD

**Issue by Azunyan15** [LmeSzinc/AzurLaneAutoScript#4098]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在“刷紧急委托”功能中，若指定旗舰航母为突击者，在更换旗舰时选择“航母-白鹰-普通”后不会进行下拉，刷图掉落的其他白皮航母（博格、兰利）默认排序优先级高于突击者，导致换人页面无突击者可用，Alas会使用超过33级的突击者继续出击

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

在换人页面若检测不到1级突击者，则进行下拉

**Comment by LmeSzinc** [comment]
## 如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

- 在提问题前，请先阅读 [常见问题(FAQ)](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn)。
- 检查 Alas 的更新和最近的 commit，确认使用的是最新版。
- 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。
