### ISSUE TITLE
添加相关的功能。

### ISSUE THREAD

**Issue by Misaka13163** [LmeSzinc/AzurLaneAutoScript#4104]
### 你的功能请求是否与问题有关？

在低耗刷取活动pt的时候短猫任务不会直接触发而是一直等待，在短暂延后活动图任务的情况下当活动图任务时间到了也会马上进入活动图开始工作。

### 解决方案

增加一个类似筛选器的功能，在相同时间遇到不同任务都刷新时，玩家可以根据自己的情况优先某些任务。
（当然当前这个功能也可以通过玩家手动修改足够的任务时间来实现，但是不可避免地会出现空转，而且我认为这有违背：“将游戏和alas丢在后台直接忘掉”这一准则。）

**Comment by Air111** [comment]
刷紧急委托优先级低于短猫。如果你指的是活动图任务那么会有心情控制来触发推迟

**Comment by Misaka13163** [comment]
> 刷紧急委托优先级低于短猫。如果你指的是活动图任务那么会有心情控制来触发推迟

因为低耗婚的只够凑一支队伍所以选择的无视红脸出击了（哪来的折磨舰娘的屑），这种时候低耗会一直顶住短猫。

**Comment by Air111** [comment]
> > 刷紧急委托优先级低于短猫。如果你指的是活动图任务那么会有心情控制来触发推迟
> 
> 因为低耗婚的只够凑一支队伍所以选择的无视红脸出击了（哪来的折磨舰娘的屑），这种时候低耗会一直顶住短猫。

婚不200就+3%不知道你图什么。另外石油也会触发任务的推迟

**Comment by Misaka13163** [comment]
> > > 刷紧急委托优先级低于短猫。如果你指的是活动图任务那么会有心情控制来触发推迟
> > 
> > 
> > 因为低耗婚的只够凑一支队伍所以选择的无视红脸出击了（哪来的折磨舰娘的屑），这种时候低耗会一直顶住短猫。
> 
> 婚不200就+3%不知道你图什么。另外石油也会触发任务的推迟

因为还要升级技能和练级所以只练了两只用来专门打活动c2的，面板方面婚+前排放秘书舰1位的话就勉强够了。且alas针对活动的c图也没有按照心情换人的功能，所以最终只练了一队。且就算婚+后宅2楼给的心情也不够活动期间的低耗需求，所以我选择了直接红脸打。

我之前也试过调整石油来延迟任务，但是因为低耗会刷很多紧急委托有时候委托给的油会和低耗的油达到微妙的平衡，甚至偶尔油表倒转之类的。当前我的解决方案是到点手动关闭一下任务，等到调度器进入待机模式了再将低耗活动图的任务重新打开。

如果调度器优先级调整不太方便的话是否可以在停止条件上增加一个延迟或者停止的方案呢？
