### ISSUE TITLE
15圖使用腳本將會發生錯誤，進入關卡後無法順利執行

### ISSUE THREAD

**Issue by pajh103082** [LmeSzinc/AzurLaneAutoScript#4108]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

15圖使用腳本將會發生錯誤，進入關卡後無法順利執行，貌似會卡在戰略的選擇

### 如何复现

1. 前往 '15圖任意關卡'
2. 点击 '立刻前往，進入關卡'
3. 開始腳本自動處理>選擇戰略>進入無限迴圈"陣型、潛艇自主尋敵"
4. 出现问题

**Comment by LmeSzinc** [comment]
## 如何上报bug How to Report Bugs

在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你。"XX怎么运行不了"，"XX卡住了"，这样的描述将不会得到回复。

- 在提问题前，请先阅读 [常见问题(FAQ)](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn)。
- 检查 Alas 的更新和最近的 commit，确认使用的是最新版。
- 上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。若不是错误而是非预期的行为，提供在 log 目录下当天的 log和至少一张游戏截图。

**Comment by pajh103082** [comment]
![2024-08-15_21-28-27-104176](https://github.com/user-attachments/assets/3178f408-6e25-4143-a940-84d1e8c8aa19)
[log.txt](https://github.com/user-attachments/files/16687932/log.txt)
