### ISSUE TITLE
海图中当舰队与BOSS存在遮挡关系时无法正常运行

### ISSUE THREAD

**Issue by Gerlat1x** [LmeSzinc/AzurLaneAutoScript#4120]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在海图中，舰队与BOSS直接存在遮挡关系时会导致识别错误或点击错误，具体如视频所示。

https://github.com/user-attachments/assets/97609b34-943d-4320-9e48-2d96df321d62

相关log：
[log.txt](https://github.com/user-attachments/files/16735442/log.txt)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Air111** [comment]
为什么一队会跑到B8去，发一下完整（不确定就直接发当天全部）log看一下

**Comment by Gerlat1x** [comment]
完整的log：[2024-08-24_alas.txt](https://github.com/user-attachments/files/16739347/2024-08-24_alas.txt)
BATTLE_12出现问题

**Comment by LmeSzinc** [comment]
42bda736c07321a7e28c815614de2cdf5bd090f9
