### ISSUE TITLE
模拟器无法连接

### ISSUE THREAD

**Issue by Justhz0110** [LmeSzinc/AzurLaneAutoScript#4131]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

使用雷电模拟器无法使用ALAS，求助

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![微信截图_20240827222308](https://github.com/user-attachments/assets/e208121e-4984-47e8-b9e0-9390d06aa5c6)

**Comment by D9Lose** [comment]
怎么看起来你开了一个雷电又开了一个夜神模拟器啊
建议检查一下alas的serial地址是否正确
