### ISSUE TITLE
关于大世界的错误代码3

### ISSUE THREAD

**Issue by Touyamafann** [LmeSzinc/AzurLaneAutoScript#4153]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如下图所示在大世界会发生错误，此外如果点了每月开荒会重复点开区域然后卡死

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图
![QQ截图20240907052308](https://github.com/user-attachments/assets/fd0576b0-011b-42e4-bd3a-296a9d940789)

**Comment by Air111** [comment]
正确上报bug https://github.com/LmeSzinc/AzurLaneAutoScript#%E5%A6%82%E4%BD%95%E4%B8%8A%E6%8A%A5bug-how-to-report-bugs

看起来跟#3747 重复
