### ISSUE TITLE
领取石油卡死

### ISSUE THREAD

**Issue by EAlyce** [LmeSzinc/AzurLaneAutoScript#4160]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

石油溢出时一直重复领取导致卡死

### 截图

![20240910_114230](https://github.com/user-attachments/assets/23e0890d-c445-454e-92cd-95b2457291ab)

**Comment by LmeSzinc** [comment]
后宅买咖喱
