### ISSUE TITLE
战斗结束后不点击

### ISSUE THREAD

**Issue by Y1zZz** [LmeSzinc/AzurLaneAutoScript#4174]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

战斗结束后，alas不会继续点击，一直卡在战斗结算页面，但是alas一直不报错

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

正常运行吧

### 相关 Logs

```Text
因为不报错，大概没有日志生成吧……
```

**Comment by Air111** [comment]
#4172
等的时间够长就会报错

**Comment by ZBY2003** [comment]
是不是选用了新版战斗界面？换回旧版战斗界面可以解决
