### ISSUE TITLE
我尝试适配1080p分辨率

### ISSUE THREAD

**Issue by Mr-EEEeee** [LmeSzinc/AzurLaneAutoScript#4177]
### 你的功能请求是否与问题有关？

因为之前ALAS不适配1080p的主要原因是截图速度问题，如今mumu12的nemu_ipc截图方案速度已经很快，我在想现在是否能在1080p下使用脚本。

因为有时看剧情和皮肤或是大建等情况确实需要浏览，720p真有点糊不太够用，而模拟器需要重启才能切换分辨率，十分不方便，这个需求对碧蓝航线我感觉挺大的，尤其是现在优化过UI后。

我在尝试增加可选分辨率后，在1080p下日志只能显示"Unknown ui page"，截图正常，我浏览文档和源码后发现匹配图片貌似是根据720p下的实际X,Y轴位置，所以无法匹配？

### 解决方案

所以要支持1080p是需要修改所有图片及位置吗？还是说可以乘比例放大坐标直接匹配720p的图片，是否会导致准确率问题？真心希望能增加对mumu12的nemu_ipc截图方案1080p的支持。

**Comment by LmeSzinc** [comment]
这是一种标准，既然制定了标准就要坚持。如果你添加 1920x1080，那么就会有人要求 3840x2160、3440x1440、960x480……，开发时间就会浪费在分辨率兼容性上，结果只有少数人在使用各种非标准分辨率。

**Comment by cm-MMK-2** [comment]
"Unknown ui page"是根据截图找不到游戏中当前界面是匹配哪个界面
我试了下截图以后把图片缩放到720p，是没有问题的，点击位置什么都对
自己临时用一下的话可以改screenshot.py中的check_screen_size函数，
开头加个修改图片分辨率:
self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)

**Comment by appleapple802** [comment]
我自己試了一下 應該是改在
screenshot 函數中縮放，而不是在 check_screen_size 中
才不會遇到橫豎屏的問題

def screenshot(self):
    # ... 獲取截圖 ...
    self.image = method()
    self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)
    # ... 後續處理 ...

**Comment by x1renn** [comment]
除了大世界，测试了大部分日常功能确实基本都没问题。
`resize` 的不同插值计算方法推荐使用 `cv2.INTER_LANCZOS4`，综合匹配率最高，计算延迟是毫秒级的，所以也不用太担心性能。
在 1080p 分辨率下进行性能测试，`nemu_ipc` 的截图速度为 0.011s，远超其他方法，完全可用，但因为整体 OCR 识别肯定会有匹配问题，除非新开分支维护，不可能提交，大伙看到的按需本地修改吧。

在 module/device/screenshot.py 中添加以下代码
```python    
def screenshot(self):
    ......
        self.image = method()

        # match resolution
        width, height = image_size(self.image)
        if width != 1280 or height != 720:
            self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)
            # logger.info("resized")
```
在 module/base/base.py 中降低整体匹配阈值
```python
def appear(self, button, offset=0, interval=0, similarity=0.82, threshold=10):
```
在 module/daily/daily.py 中降低个别匹配阈值
``` python   
if self.config.Daily_UseDailySkip:
    # hard to match, lower threshold to match resolution
    if self.appear_then_click(DAILY_SKIP, offset=(20, 20), interval=5, similarity=0.78):
        continue
```
在 module/shop/ui.py 中降低个别匹配阈值
```python
def ui_goto_shop(self):
    ......
        # hard to match, lower threshold to match resolution
        if self.appear_then_click(ACADEMY_GOTO_MUNITIONS, offset=(200, 200), interval=5, similarity=0.8):
            continue
```
~~对了，记得把 config/deploy.yaml 中设置 `KeepLocalChanges: true`~~

由于 `5aa9231` 对 bug#5126 的修复，导致 1080p 周回识别出现问题，不太懂在哪改，就直接修改了 switch 的代码目前运行正常
module/ui/switch.py
```python
def get(self, main):
    ......
                for data in self.state_list:
                if main.appear(data['check_button'], offset=data['offset']):
                    return data['state']
                # 新增
                elif main.appear(data['click_button']):
                    return data['state']
```

---
新编，由于 Sep 2, 2025 的提交移除了保存本地代码的相关代码，需自行编写额外脚本在 alas 启动更新后再执行代码修改。
可在根目录下新建 LocalChanges.py
```python
import re

TASKS = {
    "module/device/screenshot.py": {
    "old": r'self\.image = method\(\)',
    "new": '''self.image = method()
            width, height = image_size(self.image)
            if width != 1280 or height != 720:
                self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)
                # logger.info("resized")''',
    "count": 1
    },
    "module/base/base.py": {
        "old": r'def appear\(self, button, offset=0, interval=0, similarity=0\.85, threshold=10\)',
        "new": 'def appear(self, button, offset=0, interval=0, similarity=0.82, threshold=10)',
        "count": 1
    },
    "module/daily/daily.py": {
        "old": r'if self\.config\.Daily_UseDailySkip:\s*\n\s*if self\.appear_then_click\(DAILY_SKIP, offset=\(20, 20\), interval=5\)',
        "new": '''if self.config.Daily_UseDailySkip:
                if self.appear_then_click(DAILY_SKIP, offset=(20, 20), interval=5, similarity=0.78)''',
        "count": 1,
        "flags": re.MULTILINE
    },
    "module/shop/ui.py": {
        "old": r'if self\.appear_then_click\(ACADEMY_GOTO_MUNITIONS, offset=\(200, 200\), interval=5\):',
        "new": 'if self.appear_then_click(ACADEMY_GOTO_MUNITIONS, offset=(200, 200), interval=5, similarity=0.8):',
        "count": 1
    },
    "module/ui/switch.py": {
        "old": r"for\s+data\s+in\s+self\.state_list:\s*\n\s*if\s+main\.appear\(\s*data\['check_button'\]\s*,\s*offset\s*=\s*data\['offset'\]\s*\)\s*:\s*\n\s*return\s+data\['state'\]",
        "new": '''for data in self.state_list:
                if main.appear(data['check_button'], offset=data['offset']):
                    return data['state']
                elif main.appear(data['click_button']):
                    return data['state']''',
        "count": 1,
        "flags": re.MULTILINE
    }
}

def patch_file(filepath: str, old_pattern: str, new_text: str, count=1, flags=0):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    new_content, n = re.subn(old_pattern, new_text, content, count=count, flags=flags)
    if n == 0:
        print(f'[WARN] {filepath} 未匹配，跳过')
        return
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f'[OK] {filepath} 已替换 {n} 处')

def main():
    for fp, rule in TASKS.items():
        patch_file(fp, rule["old"], rule["new"],
                   count=rule.get("count", 1),
                   flags=rule.get("flags", 0))
    print('全部补丁完成！')

if __name__ == '__main__':
    main()
```
再使用批处理，可嵌套 vbs 来静默命令行，最后把 alas 的快捷方式指向 .bat/.vbs 脚本，实现了 alas 的自动更新以及本地代码修改，其他固定修改同理让大模型写个正则匹配一下替换即可。
```bat
@echo off
start /wait alas.exe
python LocalChanges.py
```

**Comment by FallChill** [comment]
我试了一下，宿舍计划无法进行

**Comment by Mr-EEEeee** [comment]
> 我试了一下，宿舍计划无法进行

具体适配的基本操作就是去降低对应按钮 appear_then_click 函数的 similarity 直到可以运行

**Comment by FallChill** [comment]
ok，感谢指点

**Comment by RedDestiny** [comment]
> 除了大世界，测试了大部分日常功能确实基本都没问题。 `resize` 的不同插值计算方法推荐使用 `cv2.INTER_LANCZOS4`，综合匹配率最高，计算延迟是毫秒级的，所以也不用太担心性能。 在 1080p 分辨率下进行性能测试，`nemu_ipc` 的截图速度为 0.011s，远超其他方法，完全可用，但因为整体 OCR 识别肯定会有匹配问题，除非新开分支维护，不可能提交，大伙看到的按需本地修改吧。
> 
> 在 module/device/screenshot.py 中添加以下代码
> 
> def screenshot(self):
>     ......
>         self.image = method()
> 
>         # match resolution
>         width, height = image_size(self.image)
>         if width != 1280 or height != 720:
>             self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)
>             # logger.info("resized")
> 
> 在 module/base/base.py 中降低整体匹配阈值
> 
> def appear(self, button, offset=0, interval=0, similarity=0.82, threshold=10):
> 
> 在 module/daily/daily.py 中降低个别匹配阈值
> 
> if self.config.Daily_UseDailySkip:
>     # hard to match, lower threshold to match resolution
>     if self.appear_then_click(DAILY_SKIP, offset=(20, 20), interval=5, similarity=0.78):
>         continue
> 
> 在 module/shop/ui.py 中降低个别匹配阈值
> 
> def ui_goto_shop(self):
>     ......
>         # hard to match, lower threshold to match resolution
>         if self.appear_then_click(ACADEMY_GOTO_MUNITIONS, offset=(200, 200), interval=5, similarity=0.8):
>             continue
> 
> ~对了，记得把 config/deploy.yaml 中设置 `KeepLocalChanges: true`~
> 
> 由于 `5aa9231` 对 bug#5126 的修复，导致 1080p 周回识别出现问题，不太懂在哪改，就直接修改了 switch 的代码目前运行正常 module/ui/switch.py
> 
> def get(self, main):
>     ......
>                 for data in self.state_list:
>                 if main.appear(data['check_button'], offset=data['offset']):
>                     return data['state']
>                 # 新增
>                 elif main.appear(data['click_button']):
>                     return data['state']
> 
> 新编，由于 Sep 2, 2025 的提交移除了保存本地代码的相关代码，需自行编写额外脚本在 alas 启动更新后再执行代码修改。 可在根目录下新建 LocalChanges.py
> 
> import re
> 
> TASKS = {
>     "module/device/screenshot.py": {
>     "old": r'self\.image = method\(\)',
>     "new": '''self.image = method()
>             width, height = image_size(self.image)
>             if width != 1280 or height != 720:
>                 self.image = cv2.resize(self.image, (1280, 720), interpolation=cv2.INTER_LANCZOS4)
>                 # logger.info("resized")''',
>     "count": 1
>     },
>     "module/base/base.py": {
>         "old": r'def appear\(self, button, offset=0, interval=0, similarity=0\.85, threshold=10\)',
>         "new": 'def appear(self, button, offset=0, interval=0, similarity=0.82, threshold=10)',
>         "count": 1
>     },
>     "module/daily/daily.py": {
>         "old": r'if self\.config\.Daily_UseDailySkip:\s*\n\s*if self\.appear_then_click\(DAILY_SKIP, offset=\(20, 20\), interval=5\)',
>         "new": '''if self.config.Daily_UseDailySkip:
>                 if self.appear_then_click(DAILY_SKIP, offset=(20, 20), interval=5, similarity=0.78)''',
>         "count": 1,
>         "flags": re.MULTILINE
>     },
>     "module/shop/ui.py": {
>         "old": r'if self\.appear_then_click\(ACADEMY_GOTO_MUNITIONS, offset=\(200, 200\), interval=5\):',
>         "new": 'if self.appear_then_click(ACADEMY_GOTO_MUNITIONS, offset=(200, 200), interval=5, similarity=0.8):',
>         "count": 1
>     },
>     "module/ui/switch.py": {
>         "old": r"for\s+data\s+in\s+self\.state_list:\s*\n\s*if\s+main\.appear\(\s*data\['check_button'\]\s*,\s*offset\s*=\s*data\['offset'\]\s*\)\s*:\s*\n\s*return\s+data\['state'\]",
>         "new": '''for data in self.state_list:
>                 if main.appear(data['check_button'], offset=data['offset']):
>                     return data['state']
>                 elif main.appear(data['click_button']):
>                     return data['state']''',
>         "count": 1,
>         "flags": re.MULTILINE
>     }
> }
> 
> def patch_file(filepath: str, old_pattern: str, new_text: str, count=1, flags=0):
>     with open(filepath, 'r', encoding='utf-8') as f:
>         content = f.read()
>     new_content, n = re.subn(old_pattern, new_text, content, count=count, flags=flags)
>     if n == 0:
>         print(f'[WARN] {filepath} 未匹配，跳过')
>         return
>     with open(filepath, 'w', encoding='utf-8') as f:
>         f.write(new_content)
>     print(f'[OK] {filepath} 已替换 {n} 处')
> 
> def main():
>     for fp, rule in TASKS.items():
>         patch_file(fp, rule["old"], rule["new"],
>                    count=rule.get("count", 1),
>                    flags=rule.get("flags", 0))
>     print('全部补丁完成！')
> 
> if __name__ == '__main__':
>     main()
> 
> 再使用批处理，可嵌套 vbs 来静默命令行，最后把 alas 的快捷方式指向 .bat/.vbs 脚本，实现了 alas 的自动更新以及本地代码修改，其他固定修改同理让大模型写个正则匹配一下替换即可。
> 
> @echo off
> start /wait alas.exe
> python LocalChanges.py

试了下，在mumu12模拟器上，1080p亲测可行

**Comment by isokazeee** [comment]
感觉可以自己修改/assets下的图，就不需要修改匹配阈值了，我自己修改了一下大世界的一些图片，大世界每日也是能跑的

**Comment by mkzxcvbnm** [comment]
我用ai改了个macOS版本2560*1440分辨率切换的脚本 目前用着正常

主要遇到的问题是截图转分辨率后的达不到阈值  大部分是正常的 有部分转换后达不到的 用了像素偏移修正和亮度、颜色和边缘加权平均提高了相似度来解决

下面是部分摘要 

## 2560×1440 补丁

启用脚本备份并修改：

- `module/device/screenshot.py`
- `module/device/control.py`
- `module/device/method/adb.py`
- `module/device/method/uiautomator_2.py`
- `module/webui/updater.py`
- `module/webui/app.py`
- `module/base/button.py`
- `module/base/base.py`
- `module/guild/operations.py`

1440p 模式使用 ADB 获取原始截图，转换成 1280×720 后交给现有模板、颜色和 OCR 逻辑。内部继续使用 720p 坐标；点击和滑动出口统一映射到实际尺寸。1440p 下强制使用 ADB 控制，避免 minitouch、scrcpy 等已有换算与补丁重复缩放。原生 720p 保持原有行为。

## 岛屿卡住与采样对齐

初版使用 `INTER_AREA` 缩小。脚本能点击“岛屿手机 → 集成管理”，但无法识别已到达目标页，约三分钟后产生 `GameStuckError`。随后 Alas 主动执行 `App stop` 和 `App start`，用户看到的“闪退”实际是卡死恢复。

该页使用左上角 `ISLAND_MANAGE_CHECK` 标题判断，调用链：

`ui_page_appear()` → `appear(offset=(30,30))` → `Button.match()`

错误截图中最佳位置为 `(123,20)`，与模板完全一致，但相似度约 0.831，未达到 0.85。问题来自缩小采样造成的像素差异，并非入口按钮坐标错误。

使用同一 BlueStacks、同一页面的原始 1440p 与原生 720p ADB 截图比较：

| 方式 | “集成管理”与原模板相似度 |
|---|---:|
| 原生 720p | 0.9999 |
| 初版标准 AREA/LINEAR | 0.8312 |
| 最近邻 | 0.9247 |
| 新版采样对齐 | 0.9917 |

另外六个设施标题与原生 720p 的平均相似度从 0.9427 提升到 0.9934。

V2 标记为 `ALAS_1440_SAMPLING_V2`，使用 `(2x+0.5, 2y-0.5)` 固定取样。大舰队底部按钮暴露出纵向偏移会随屏幕高度累计，因此 V3 改为 `ALAS_1440_SAMPLING_V3`：`map_y = 2y - 0.5 + y/719`，纵向偏移从顶部 `-0.5` 平滑变化到底部 `+0.5`；横向仍为 `map_x = 2x + 0.5`。实现继续采用 `cv2.remap`、`INTER_LINEAR`、`BORDER_REPLICATE` 并缓存映射。岛屿标题保持约 0.991，成对截图平均像素误差从约 4.16 降至 3.15。

修正仅作用于 2560×1440；1440×2560 根据方向转正后复用；1280×720 原样返回。不修改模板和阈值。曾测试模板与区域同时做 σ=0.6 高斯平滑，正确分数可到 0.915，但也会提高错误模板分数；采样对齐达到 0.9917，因此未加入全局平滑或降阈值。

## 大舰队作战编队页卡住

在 2560×1440 下，大舰队任务能够进入作战页、打开快速编队并切换到最右舰队。日志最后停在：

```text
[Dispatch_fleet] | 1 | [ 2 ]
Already at the most right fleet
```

随后进入 `_guild_operations_dispatch_execute()`。该循环等待 `GUILD_DISPATCH_FLEET_UNFILLED`、`GUILD_DISPATCH_FLEET` 或 `GUILD_DISPATCH_IN_PROGRESS`，本身没有超时。当前页面四个舰位为空，正常流程应识别 `GUILD_DISPATCH_FLEET_UNFILLED` 后点击“推荐”，但实测模板相似度如下：

| 元素 | 当前 1440p 对齐采样得分 |
|---|---:|
| 未编队按钮 `GUILD_DISPATCH_FLEET_UNFILLED` | 约 0.832 |
| 可出击按钮 `GUILD_DISPATCH_FLEET` | 0.7481 |
| 推荐按钮 `GUILD_DISPATCH_RECOMMEND` | 0.9339 |
| 关闭按钮 `GUILD_DISPATCH_CLOSE` | 0.9171 |

默认阈值是 0.85，因此未编队按钮未被识别，循环没有任何点击。对不同全局采样相位进行搜索，未编队按钮最高约 0.8329；标准 `INTER_AREA` 缩小约 0.8434，仍低于阈值。其他两个固定元素得分正常，证明不是全页坐标偏移。不同 UI 元素在 1440p 渲染时可能具有不同的像素相位和抗锯齿结果，单一全局采样映射无法让所有局部模板都达到原生 720p 的相似度。

最终没有增加大舰队按钮特例。当前统一备用判断标记为 `ALAS_1440_FALLBACK_V2`。普通 RGB 模板匹配先执行并保存本次最高分（`ALAS_1440_RGB_GATE_V1`）；只有 RGB 未达到原调用阈值、设备处于 1440p，并且 `RGB分数 ≥ max(0.70, 原调用阈值 - 0.15)` 时，才继续计算亮度、逐像素颜色和边缘。以默认阈值 0.85 为例：分数低于 0.70 直接失败，0.70 至 0.85 才进入备用判断，达到 0.85 则由原判断直接成功。保存第一次 RGB 结果避免重复做同一模板匹配。

备用判断的分项门槛仍为亮度 ≥0.82、颜色 ≥0.88、边缘 ≥0.90；综合分为 `亮度×0.50 + 颜色×0.35 + 边缘×0.15`，并要求综合分 ≥ `max(0.89, 原调用阈值)`。当前未编队模板的 RGB 分数约 0.832，能进入备用判断，并得到 L=0.876、C=0.924、E=0.970、综合 0.907；错误的已编队模板综合约 0.860，被拒绝。实测 RGB 0.69 的低相似样本不会调用备用算法。720p 完全不进入备用判断。

`_guild_operations_dispatch_execute()` 另加入 `ALAS_GUILD_TIMEOUT_V1`：连续 30 秒且至少 60 次检查没有识别到动作时记录警告并正常返回失败。它不抛出 `GameStuckError`，也不主动保存错误截图；调用方会退出编队页并结束本次大舰队派遣，避免无限循环和截图长期累积。
