### ISSUE TITLE
无法自动开荒活动图

### ISSUE THREAD

**Issue by a867e** [LmeSzinc/AzurLaneAutoScript#4182]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

打埋葬于彼岸之花活动图报错
![image](https://github.com/user-attachments/assets/475bdebe-ef2f-41ea-9a0d-6f3201bc5dca)
![image](https://github.com/user-attachments/assets/a41b4a58-8d61-418c-bcfb-faecc50ebf29)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Emniceay** [comment]
你要不要看一看活动名称叫啥？

**Comment by Dyolem** [comment]
> > 你要不要看一看活动名称叫啥？
> 
> 看alas版本更新到最新以为可以了，忽略了活动名还没更新了........


没有看懂你们的对话😀总之就是alas还没有自动更新活动图的名字还有一些东西对吗？所以现在应该做的就是等待？

**Comment by Windsland52** [comment]
> > > 你要不要看一看活动名称叫啥？
> > 
> > 
> > 看alas版本更新到最新以为可以了，忽略了活动名还没更新了........
> 
> 没有看懂你们的对话😀总之就是alas还没有自动更新活动图的名字还有一些东西对吗？所以现在应该做的就是等待？

等更新

**Comment by twd07** [comment]
campaign里虽然已经更了event_20240912_cn但实际还没有加进来，再等等。
