### ISSUE TITLE
好像“活动图-2” 的活动名称typo了

### ISSUE THREAD

**Issue by ZhaiXB** [LmeSzinc/AzurLaneAutoScript#4192]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

日服，刚刚最新一次更新后发现 “活动图-2” 里的 "活动名称" 成了“eevent_20240912_cn”，应该是typo了 多了个e，导致会引起一系列错误，这个任务用不了了。 (第一个“活动图”任务正常)

### 截图

![image](https://github.com/user-attachments/assets/64cb8641-b919-4ffb-ab02-0873f6de8cb3)

**Comment by ZhaiXB** [comment]
哦哦找到了，好像是这个最新commit里的最底下2517行打错了。
![image](https://github.com/user-attachments/assets/aee41dfa-dcc1-4af7-8b36-04d49681c134)

**Comment by LmeSzinc** [comment]
78a9191936cb93c6c3d94cad323e6b5d80d96527
