### ISSUE TITLE
活动图战斗结束不点击

### ISSUE THREAD

**Issue by theyu6663** [LmeSzinc/AzurLaneAutoScript#4194]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

活动图A1和A2第一次战斗结束后就不点击了，alas显示运行正常，但是就是没法自动点击进行战斗

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
8
```

**Comment by theyu6663** [comment]
而且我只有大号会这样，小号却没有影响，我把大号登到小号的mumu模拟器依然不能用，有人知道是怎么回事吗

**Comment by visa980911** [comment]
我也是这次更新后出现的问题，而且是各种战斗后都不会点结束，包括主线、meta和演习

**Comment by Air111** [comment]
#4172

**Comment by gelikedabu** [comment]
用老ui可以解决问题
