### ISSUE TITLE
战斗结束经常出现

### ISSUE THREAD

**Issue by as4284652** [LmeSzinc/AzurLaneAutoScript#4199]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

然后卡在结束界面 新UI没用 卡在那不动然后重起设置 一直循环

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![MQUGX@9 V 3QZZC5YN4FR$1](https://github.com/user-attachments/assets/7f456b43-ab6e-4b27-9f81-c0f2b1ffc429)

**Comment by LmeSzinc** [comment]
log发全
