### ISSUE TITLE
强化逻辑简化（大概）

### ISSUE THREAD

**Issue by WratithCr** [LmeSzinc/AzurLaneAutoScript#4204]
### Is your feature request related to a problem?

我观察到强化检测到没有合适舰船时会换几艘船循环两三次，不过装填没满时没有合适舰船可以直接跳出循环。

### Describe the solution you'd like

简单加一个装填没满的判定条件就行（不过不加好像也没啥影响）

### Additional context

我就来划个水（（づ￣3￣）づ╭❤～）

**Comment by LmeSzinc** [comment]
装填满 与 强化完成 并不完全等价
