### ISSUE TITLE
从16号开始，每天夜里0点重启都容易在卡在签到页面加载的时候

### ISSUE THREAD

**Issue by KonradvonFranken** [LmeSzinc/AzurLaneAutoScript#4224]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

就error的log来看，只要在签到页面加载不到三秒，alas就会认为进入游戏失败，然后重启。三次失败之后就会自动暂停alas，连续6个半夜只有18号0点失败两次之后巧合进去了。
个人感觉这个两三秒内加载不了就重启太短了，但是找不到位置改动。如果十几秒没进去才重启比较好，这也是正常人手机玩的时候大概卡多久就重启的时间。
[log.txt](https://github.com/user-attachments/files/17080657/log.txt)
[log.txt](https://github.com/user-attachments/files/17080659/log.txt)
[log.txt](https://github.com/user-attachments/files/17080660/log.txt)
这三张是今天0点error的log。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Air111** [comment]
上传在log同一文件夹里的截图

**Comment by KonradvonFranken** [comment]
![2024-09-21_00-01-51-789455](https://github.com/user-attachments/assets/f2a2603d-0341-4d19-a880-42ac68c352cd)
![2024-09-21_00-01-17-757543](https://github.com/user-attachments/assets/99627645-a8ca-4b25-b6ce-b9d45cebb065)
![2024-09-21_00-00-41-182231](https://github.com/user-attachments/assets/69e39a86-85d0-4a2f-9409-98303996733e)

**Comment by KonradvonFranken** [comment]
> 上传在log同一文件夹里的截图

发了，全是卡在加载界面。而且今天我试图熬过0点，却发现alas今天不知道为什么扫描委托的时候只会往下拉一下扫几个就不扫了，大量委托没扫都没扫就认为自己扫完了，执行下一个任务去了。感觉又是一个bug，我调整了截图频率0.1切到0.3，还是没用就又切回来了，模拟器确定一直是设置60帧。
下午给alas替我接委托的时候还正常的，我也没改过设置。可能是半夜alas会出现什么奇怪bug导致它执行出现问题？
睡醒之后下午看看怎么样。

**Comment by KonradvonFranken** [comment]
[2024-09-23_alas.txt](https://github.com/user-attachments/files/17090519/2024-09-23_alas.txt)
今天就是反复尝试让alas重新执行委托，但是就是这个样子，我有4小时钻和2小时钻在中间，自定义让它做了1.5小时魔方和7小时单元之后接，它完全没法扫到4小时委托，2小时的也是扫了但是不排序。

**Comment by KonradvonFranken** [comment]
> [2024-09-23_alas.txt](https://github.com/user-attachments/files/17090519/2024-09-23_alas.txt) 今天就是反复尝试让alas重新执行委托，但是就是这个样子，我有4小时钻和2小时钻在中间，自定义让它做了1.5小时魔方和7小时单元之后接，它完全没法扫到4小时委托，2小时的也是扫了但是不排序。

似乎它扫到的2小时钻也只是我在做的那个，麻了

**Comment by KonradvonFranken** [comment]
> > [2024-09-23_alas.txt](https://github.com/user-attachments/files/17090519/2024-09-23_alas.txt) 今天就是反复尝试让alas重新执行委托，但是就是这个样子，我有4小时钻和2小时钻在中间，自定义让它做了1.5小时魔方和7小时单元之后接，它完全没法扫到4小时委托，2小时的也是扫了但是不排序。
> 
> 似乎它扫到的2小时钻也只是我在做的那个，麻了

把钻石委托自定义里放回最前面它也一样。但愿这不是bug只是alas更新之后，委托没有空位的时候自动结束委托任务去做下一个吧

**Comment by KonradvonFranken** [comment]
> > 上传在log同一文件夹里的截图
> 
> 发了，全是卡在加载界面。而且今天我试图熬过0点，却发现alas今天不知道为什么扫描委托的时候只会往下拉一下扫几个就不扫了，大量委托没扫都没扫就认为自己扫完了，执行下一个任务去了。感觉又是一个bug，我调整了截图频率0.1切到0.3，还是没用就又切回来了，模拟器确定一直是设置60帧。 下午给alas替我接委托的时候还正常的，我也没改过设置。可能是半夜alas会出现什么奇怪bug导致它执行出现问题？ 睡醒之后下午看看怎么样。

确定了，委托应该没bug，应该就是alas更新了之后发现委托全在做的时候不会再挨个挨个委托扫一下而已。

**Comment by LmeSzinc** [comment]
#4236
