### ISSUE TITLE
接到新好感度個人劇情任務時報錯

### ISSUE THREAD

**Issue by a5317264** [LmeSzinc/AzurLaneAutoScript#4228]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

領取完個人劇情，跳出下一個任務時無法正常運行

### 如何复现

1.前往任務獎勵
2.領取獎勵
3.看完劇情
4.跳出新任務
5.報錯停止

### 预期行为

應正確辨識並退出

### 截图

![2024-09-15_03-50-50-724352](https://github.com/user-attachments/assets/3f2c161a-b0fb-4289-a132-75c5a128a4ea)
[log.txt](https://github.com/user-attachments/files/17091470/log.txt)
![2024-09-15_10-17-35-649402](https://github.com/user-attachments/assets/16ba8cc6-ba17-4146-982e-51df3d0cdf37)
[log.txt](https://github.com/user-attachments/files/17091471/log.txt)

**Comment by LmeSzinc** [comment]
cf7b208a4f587bed17afddd78f206738165e4c70
