### ISSUE TITLE
mumu模拟器12中，活动图设置和之前一样，但变成了无限点击选择舰队界面

### ISSUE THREAD

**Issue by back8237** [LmeSzinc/AzurLaneAutoScript#4240]
### 在提问之前...

- [x] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在活动关卡a1中，选择舰队时似乎是点击位置出了问题，一直点不上第一舰队，而是反复点击选择舰队按钮本身
dpi是1280*720

### 如何复现

1. 前往 '活动关卡页面'
2. 点击 '活动关卡'
3. 滑动到 '选择按钮'
4. 反复点击两个坐标，但是无法完成预定任务导致重启

### 预期行为

希望可以解决这个问题，应该是坐标弄错了？

### 相关 Logs

```Text
反复点击两个错误的坐标，导致超时重启：
INFO     21:48:21.675 │ Click (1053,  474) @ SUBMARINE_CHOOSE                      
INFO     21:48:21.875 │ Click (1158,  337) @ FLEET_2_CLEAR                         
INFO     21:48:22.077 │ Click (1040,  228) @ FLEET_1_CHOOSE                        
INFO     21:48:25.296 │ Click (1075,  218) @ FLEET_1_CHOOSE                        
INFO     21:48:28.513 │ Click (1057,  226) @ FLEET_1_CHOOSE                        
INFO     21:48:31.733 │ Click (1044,  210) @ FLEET_1_CHOOSE                        
INFO     21:48:34.950 │ Click (1059,  213) @ FLEET_1_CHOOSE                        
INFO     21:48:38.174 │ Click (1053,  226) @ FLEET_1_CHOOSE                        
INFO     21:48:41.392 │ Click (1049,  233) @ FLEET_1_CHOOSE
```

**Comment by back8237** [comment]
呃，截图传不上来，我再试试
![屏幕截图 2024-09-25 220103](https://github.com/user-attachments/assets/4399f940-cdc2-4efd-a8a4-dea421332c0e)

**Comment by Air111** [comment]
手操至解锁所有舰队

**Comment by back8237** [comment]
> 手操至解锁所有舰队

谢谢，请问这个问题页面怎么改成类似已解决的状态，或者将它删除掉，没怎么用过github

**Comment by Air111** [comment]
> > 手操至解锁所有舰队
> 
> 谢谢，请问这个问题页面怎么改成类似已解决的状态，或者将它删除掉，没怎么用过github

Close issue
