### ISSUE TITLE
大世界自动开荒会忽视地图中的“特殊资源”，导致海域无法压制而陷入寻路循环。

### ISSUE THREAD

**Issue by kenzining** [LmeSzinc/AzurLaneAutoScript#4249]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题。大世界自动开荒功能会在视野内无可自律事件退出自律寻敌后，ocr搜索地图时，会忽视地图中的“特殊资源”，直接跳转出海域。
<img width="476" alt="image" src="https://github.com/user-attachments/assets/8b5f1678-825d-4f6c-acba-f797ea26ac71">
进而导致海域压制无法完成，陷入搜索海域的循环，卡死在这个任务。

### 如何复现

1. 开启 '每月开荒'
2. 运行至含有 '特殊资源' 的海域
3. 出现问题

### 预期行为

自动与“特殊资源”交互并正常完成海域压制。
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/e735ec94-521c-4eef-b250-93d8df6b61e1">

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE
