### ISSUE TITLE
请求在功勋商店处添加启用开关键

### ISSUE THREAD

**Issue by besita01** [LmeSzinc/AzurLaneAutoScript#4251]
### 你的功能请求是否与问题有关？

功勋商店有很多溢出的东西不想要，只想要一些金布里，技能书等特定的东西，选择项里也没有列出。没有单独的开关，关了的话军需商店也跟着关了，希望给功勋商店单独做一个开关键。

**Comment by Dreamry2C** [comment]
[tip:商店过滤器留空会执行默认配置，而仅输入一个空格将不进行购买操作。](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/reward_shop_filter_string#write-filter-string-in-reward-shop)
