### ISSUE TITLE
每月开荒，从NY港口循环两次后脚本停止

### ISSUE THREAD

**Issue by leonswiftls** [LmeSzinc/AzurLaneAutoScript#4254]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

与#4246情况类似，修船设置为0.3，具体表现为从NY港口开始，在已完成海域点击一遍后重新回到NY港口，循环两次后脚本停止。

### 如何复现

1. 前往 '大型作战'
2. 点击 开始'每月开荒'
3. 出现问题

### 截图

![2024-10-04_12-21-49-591077](https://github.com/user-attachments/assets/5018d14c-8680-4815-b116-da4e8b4a527d)

### 还有别的吗？

log文件地址：https://mypikpak.com/s/VO8LqQr1IEPNdT0q2t_N7Rs3o1

**Comment by Air111** [comment]
直接在github上传log文件。此外，还需要上传同一文件夹内的截图 https://github.com/LmeSzinc/AzurLaneAutoScript?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%B8%8A%E6%8A%A5bug-how-to-report-bugs

**Comment by leonswiftls** [comment]
直接在log位置粘贴之后显示字符过多，提交不了，才换成网盘的

**Comment by Air111** [comment]
> 直接在log位置粘贴之后显示字符过多，提交不了，才换成网盘的

可以上传文件，Attach files或者直接拖都行

**Comment by leonswiftls** [comment]
[log.txt](https://github.com/user-attachments/files/17257224/log.txt)

**Comment by Air111** [comment]
按照这个修改游戏设置

https://github.com/LmeSzinc/AzurLaneAutoScript#%E4%BF%AE%E6%94%B9%E6%B8%B8%E6%88%8F%E8%AE%BE%E7%BD%AE

然后把上一次完成的区域修改为111，看一下113海域的开荒是否正常

**Comment by leonswiftls** [comment]
感谢，已解决
