### ISSUE TITLE
大世界报错

### ISSUE THREAD

**Issue by Paragasdoor** [LmeSzinc/AzurLaneAutoScript#4261]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

[2024-10-07_alas.txt](https://github.com/user-attachments/files/17272714/2024-10-07_alas.txt)

进到大世界里面遇到黑图不会自动点雷达索敌，左右反复点导致报错

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 还有别的吗？

突然又出现了新问题：不能进Alas了，错误如图

**Comment by Paragasdoor** [comment]
![Alas](https://github.com/user-attachments/assets/a87aa784-4e99-4fea-b3e0-24963bfd52d8)

**Comment by LmeSzinc** [comment]
确认你的电脑能上网
