### ISSUE TITLE
[JP] 日服更新之后UI变化导致无法委托

### ISSUE THREAD

**Issue by yulu901107** [LmeSzinc/AzurLaneAutoScript#4273]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

日服UI更新之后，委托列表的展开界面的上下间距变大了10个像素，导致`COMMISSION_ADVICE`和`COMMISSION_START`两个按钮均向下偏离了10个像素，致使最终无法识别，而无法进行委托。

同时`COMMISSION_ADVICE`和`COMMISSION_START`两个按钮的英文部分的字号变大了，字形也有所改变，但是日文字体暂没变化。

目前国服和日服的委托UI的布局是不同的，国服仍维持原来的间距，但是日服的界面间距变大了。

界面变更如图：
![Snipaste_2024-10-12_00-35-21](https://github.com/user-attachments/assets/2edc52ad-3832-485e-8c7b-109dc6733560)

### 如何复现

1. 有空闲委托的位子
2. 执行委托任务
3. 界面会卡在点开委托任务UI的地方

**Comment by beankin** [comment]
遇到了同样的问题

**Comment by ZhaiXB** [comment]
[new.zip](https://github.com/user-attachments/files/17348782/new.zip)
不知道发出来合不合规矩，但我已经把我本地的相关文件更新了一下，就能正常委托了。
压缩包里两个图片文件是放进 \AzurLaneAutoScript\assets\jp\commission
那个py是放进 \AzurLaneAutoScript\module\commission

**Comment by SZNSCORD** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/pull/4272
更新一下文件就行了

**Comment by a5341008** [comment]
> #4272 更新一下文件就行了

刷新没更新，大佬需要手动更新还是？

**Comment by yulu901107** [comment]
> > #4272 更新一下文件就行了
> 
> 刷新没更新，大佬需要手动更新还是？

#4272 还在PR中，要等合并，合并之后才会有更新推送，耐心等待。
如果实在等不及的话，只能去那个PR里，手动下载修改的文件，然后自行覆盖。

**Comment by yulu901107** [comment]
#4272 已合并至主线，更新之后看看是否还有问题
