### ISSUE TITLE
无法正确的侵蚀一练级

### ISSUE THREAD

**Issue by qazwsx3068** [LmeSzinc/AzurLaneAutoScript#4297]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

选择侵蚀一练级后开始调度器后开始短猫相接，更改体力和海域判定后依旧不行

### 如何复现

![image](https://github.com/user-attachments/assets/3f3a7a50-110f-4728-8f97-0a2217dba4e1)
![image](https://github.com/user-attachments/assets/66972930-c764-414d-8453-26951e08171e)
![image](https://github.com/user-attachments/assets/60bc52d0-d533-4ea9-9625-5cfa75e593f6)

**Comment by YAMATOabc** [comment]
侵蚀一和短猫相接是互补的一整套流程，应该保证初始设置不变，继续进行侵蚀一

**Comment by qazwsx3068** [comment]
好的，我去修改一下试试
