### ISSUE TITLE
台服活动“歡迎來到童心學院”无法正常识别

### ISSUE THREAD

**Issue by a5341008** [LmeSzinc/AzurLaneAutoScript#4301]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

勾选了活动，点击的是右下角无效处。

### 如何复现

1. 前往 '童心學院'
2. 点击 '右下角'
3. 滑动到 '卡住'
4. 出现问题：往复到重启，直到保存

### 预期行为

个人觉得应该是国服活动的坐标识别导致无法识别，能否告知如何修改或者直接解决？

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                           COALITION                                                            
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
INFO     20:48:59.855 │ Create forward: ForwardItem(serial='172.25.213.22', local='tcp:20002', remote='tcp:53516')              
INFO     20:48:59.887 │ [Device Orientation] 1 (HOME key on the right)                                                          
INFO     20:48:59.902 │ Create forward: ForwardItem(serial='172.25.213.22', local='tcp:20564', remote='localabstract:minitouch')
INFO     20:48:59.933 │ v 1                                                                                                     
INFO     20:48:59.949 │ ^ 10 720 1280 0                                                                                         
INFO     20:48:59.949 │ $ 46234                                                                                                 
INFO     20:48:59.949 │ minitouch running on port: 20564, pid: 46234                                                            
INFO     20:48:59.965 │ max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0                                               
INFO     20:49:00.402 │ [Screen_size] 1280x720                                                                                  
INFO     20:49:00.793 │ early_ocr_import call                                                                                   
─────────────────────────────────────────────────── COALITION_20240627_HARD ────────────────────────────────────────────────────
INFO     20:49:00.793 │ early_ocr_import start                                                                                  
INFO     20:49:00.808 │ COALITION_20240627_HARD                                                                                 
INFO     20:49:00.808 │ Count: 0                                                                                                
INFO     20:49:00.808 │ Loading OCR dependencies                                                                                
INFO     20:49:00.824 │ UI get current page                                                                                     
INFO     20:49:00.902 │ [UI] page_main                                                                                          
INFO     20:49:00.902 │ <<< UI GOTO PAGE_CAMPAIGN_MENU >>>                                                                      
INFO     20:49:00.918 │ Page switch: page_main -> page_campaign_menu                                                            
INFO     20:49:00.980 │ Click (1063,  367) @ MAIN_GOTO_CAMPAIGN                                                                 
INFO     20:49:02.418 │ early_ocr_import finish                                                                                 
INFO     20:49:03.308 │ Page arrive: page_campaign_menu                                                                         
INFO     20:49:03.324 │ Event available                                                                                         
INFO     20:49:03.324 │ <<< UI GOTO PAGE_COALITION >>>                                                                          
INFO     20:49:03.339 │ Page switch: page_campaign_menu -> page_coalition                                                       
INFO     20:49:03.355 │ Click ( 784,  217) @ CAMPAIGN_MENU_GOTO_EVENT                                                           
INFO     20:49:04.512 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:04.527 │ Click (1139,  630) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                                    
INFO     20:49:09.761 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:09.777 │ Click (1143,  632) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                                    
INFO     20:49:15.043 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:15.043 │ Click (1145,  639) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                                    
INFO     20:49:20.355 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:20.371 │ Click (1142,  626) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                                    
INFO     20:49:25.824 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:25.824 │ Click (1147,  632) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                                    
INFO     20:49:31.011 │ Page switch: page_coalition_menu -> page_coalition                                                      
INFO     20:49:31.027 │ Click (1138,  639) @ COALITION_ACADEMY_GOTO_CAMPAIGN
```

**Comment by Air111** [comment]
提供报错保存的截图

**Comment by a5341008** [comment]
![2024-10-19_22-05-43-256730](https://github.com/user-attachments/assets/f6557c2b-1d4d-44f6-94c8-4929fc61b77e)


> 提供报错保存的截图

═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                       COALITION                                                       
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
─────────────────────────────────────────────── COALITION_20240627_HARD ───────────────────────────────────────────────
2024-10-19 22:04:44.859 | INFO | COALITION_20240627_HARD                                                               
2024-10-19 22:04:44.864 | INFO | Count: 0                                                                              
2024-10-19 22:04:44.871 | INFO | UI get current page                                                                   
2024-10-19 22:04:44.885 | INFO | [UI] page_main                                                                        
2024-10-19 22:04:44.890 | INFO | <<< UI GOTO PAGE_CAMPAIGN_MENU >>>                                                    
2024-10-19 22:04:44.899 | INFO | Page switch: page_main -> page_campaign_menu                                          
2024-10-19 22:04:44.906 | INFO | Click (1075,  318) @ MAIN_GOTO_CAMPAIGN                                               
2024-10-19 22:04:46.131 | INFO | Page arrive: page_campaign_menu                                                       
2024-10-19 22:04:46.137 | INFO | Event available                                                                       
2024-10-19 22:04:46.144 | INFO | <<< UI GOTO PAGE_COALITION >>>                                                        
2024-10-19 22:04:46.154 | INFO | Page switch: page_campaign_menu -> page_coalition                                     
2024-10-19 22:04:46.159 | INFO | Click ( 788,  250) @ CAMPAIGN_MENU_GOTO_EVENT                                         
2024-10-19 22:04:47.341 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:04:47.347 | INFO | Click (1136,  637) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:04:52.441 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:04:52.457 | INFO | Click (1141,  635) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:04:57.566 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:04:57.566 | INFO | Click (1142,  627) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:02.613 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:02.613 | INFO | Click (1146,  642) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:07.660 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:07.660 | INFO | Click (1137,  633) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:12.722 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:12.722 | INFO | Click (1142,  619) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:17.785 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:17.800 | INFO | Click (1142,  638) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:22.894 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:22.910 | INFO | Click (1139,  642) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:27.925 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:27.941 | INFO | Click (1135,  626) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:33.004 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:33.019 | INFO | Click (1142,  634) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:38.157 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:38.163 | INFO | Click (1138,  630) @ COALITION_ACADEMY_GOTO_CAMPAIGN                                  
2024-10-19 22:05:43.272 | INFO | Page switch: page_coalition_menu -> page_coalition                                    
2024-10-19 22:05:43.272 | INFO | Function calls:                                                                       
          <string>   L1 <module>                                                                                       
          spawn.py L105 spawn_main()                                                                                   
          spawn.py L118 _main()                                                                                        
        process.py L297 _bootstrap()                                                                                   
        process.py  L99 run()                                                                                          
process_manager.py L152 run_process()                                                                                  
           alas.py L537 loop()                                                                                         
           alas.py  L69 run()                                                                                          
           alas.py L372 coalition()                                                                                    
      coalition.py L145 run()                                                                                          
 campaign_event.py L177 ui_goto_coalition()                                                                            
             ui.py L256 ui_goto()                                                                                      
        control.py  L37 click()                                                                                        
         device.py L250 handle_control_check()                                                                         
         device.py L286 click_record_check()                                                                           
         device.py  L43 show_function_call()                                                                           
2024-10-19 22:05:43.288 | WARNING | Too many click for a button: COALITION_ACADEMY_GOTO_CAMPAIGN                       
2024-10-19 22:05:43.303 | WARNING | History click: ['MAIN_GOTO_CAMPAIGN', 'CAMPAIGN_MENU_GOTO_EVENT',                  
'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN',               
'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN',               
'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN',               
'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN', 'COALITION_ACADEMY_GOTO_CAMPAIGN']               
2024-10-19 22:05:43.303 | ERROR | GameTooManyClickError: Too many click for a button: COALITION_ACADEMY_GOTO_CAMPAIGN  
2024-10-19 22:05:43.319 | WARNING | Saving error: ./log/error/1729346743319

**Comment by a5341008** [comment]
> 提供报错保存的截图

已提供

**Comment by jiashooter** [comment]
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                           COALITION                                                            
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
─────────────────────────────────────────────────── COALITION_20240627_HARD ────────────────────────────────────────────────────
INFO     11:25:17.023 │ COALITION_20240627_HARD                                                                                 
INFO     11:25:17.025 │ Count: 0                                                                                                
INFO     11:25:17.026 │ UI get current page                                                                                     
INFO     11:25:17.411 │ Unknown ui page                                                                                         
INFO     11:25:17.784 │ UI additional: IDLE -> REWARD_GOTO_MAIN                                                                 
INFO     11:25:17.786 │ Click ( 807,  629) @ REWARD_GOTO_MAIN                                                                   
INFO     11:25:17.987 │ Unknown ui page                                                                                         
INFO     11:25:18.032 │ [Package_name] com.hkmanjuu.azurlane.gp                                                                 
INFO     11:25:18.042 │ [Device Orientation] 1 (HOME key on the right)                                                          
INFO     11:25:18.270 │ Unknown ui page                                                                                         
INFO     11:25:18.545 │ [UI] page_main                                                                                          
INFO     11:25:18.548 │ <<< UI GOTO PAGE_CAMPAIGN_MENU >>>                                                                      
INFO     11:25:18.554 │ Page switch: page_main_white -> page_campaign_menu                                                      
INFO     11:25:18.557 │ Click (1221,  526) @ MAIN_GOTO_CAMPAIGN_WHITE                                                           
INFO     11:25:19.147 │ Page arrive: page_campaign_menu                                                                         
INFO     11:25:19.158 │ Event available                                                                                         
INFO     11:25:19.161 │ <<< UI GOTO PAGE_COALITION >>>                                                                          
INFO     11:25:19.166 │ Page switch: page_campaign_menu -> page_coalition                                                       
INFO     11:25:19.169 │ Click ( 672,  281) @ CAMPAIGN_MENU_GOTO_EVENT                                                           
INFO     11:25:19.749 │ Page arrive: page_coalition                                                                             
INFO     11:25:19.767 │ [CoalitionMode] unknown                                                                                 
INFO     11:25:20.051 │ [CoalitionMode] story                                                                                   
INFO     11:25:20.054 │ Expect emotion reduce: (6, 0)                                                                           
INFO     11:25:20.070 │ Bind task ['General', 'Alas', 'TaskBalancer', 'EventGeneral', 'Coalition']                              
INFO     11:25:20.072 │ Save config ./config/alas.json, Coalition.Emotion.Fleet1Value=150,                                      
         Coalition.Emotion.Fleet1Record=datetime.datetime(2024, 10, 21, 11, 25, 20), Coalition.Emotion.Fleet2Value=119,         
         Coalition.Emotion.Fleet2Record=datetime.datetime(2024, 10, 21, 11, 25, 20)                                             
INFO     11:25:20.079 │ [Emotion fleet_1] 150                                                                                   
INFO     11:25:20.082 │ [Emotion fleet_2] 119                                                                                   
INFO     11:25:20.108 │ Click ( 944,  511) @ ACADEMY_HARD                                                                       
INFO     11:25:20.954 │ [FleetMode] multi                                                                                       
INFO     11:25:20.957 │ Click (1093,  558) @ ACEDEMY_FLEET_PREPARATION                                                          
INFO     11:25:21.860 │ No oil icon                                                                                             
INFO     11:25:22.151 │ No oil icon                                                                                             
INFO     11:25:22.456 │ No oil icon                                                                                             
INFO     11:25:22.751 │ No oil icon                                                                                             
WARNING  11:25:23.050 │ Get oil timeout                                                                                         
INFO     11:25:23.053 │ <<< TRIGGERED STOP CONDITION: OIL LIMIT >>>                                                             
INFO     11:25:23.055 │ Delay task `Coalition` to 2024-10-21 15:01:03 (minute=(120, 240))                                       
INFO     11:25:23.071 │ Bind task ['General', 'Alas', 'TaskBalancer', 'EventGeneral', 'Coalition']                              
INFO     11:25:23.073 │ Save config ./config/alas.json, Coalition.Scheduler.NextRun=datetime.datetime(2024, 10, 21, 15, 1, 3)   
INFO     11:25:23.079 │ <<< SCRIPT END >>>             

还有无法识别到燃油的icon的报错！

**Comment by LmeSzinc** [comment]
#4305
