### ISSUE TITLE
需要自动重启调度器

### ISSUE THREAD

**Issue by HexatomicRing** [LmeSzinc/AzurLaneAutoScript#4316]
### 你的功能请求是否与问题有关？

调度器偶尔会因为各种问题停止，但实际上直接重启调度器就可以继续。如果没有及时看到，容易白等几个小时。

此外有些模拟器随着开启时间的增加会逐渐变卡，可能需要在重启调度器失败后尝试重启模拟器。

### 解决方案

1. 增加选项，在调度器停止后间隔若干秒尝试重启调度器
2. 增加选项，在调度器重启全部失败后尝试重启游戏
3. 增加选项，在重启游戏失败后尝试重启模拟器，并在重启后启用最小化或老板键功能
4. 以上重启选项可以同时启用通知提醒或静默提醒（例如在最小化托盘图标的右下角加一个感叹号）

**Comment by Air111** [comment]
你是不是没有启用异常处理

**Comment by HexatomicRing** [comment]
> 你是不是没有启用异常处理

我没有找到异常处理功能。通知提醒确实有，但我认为Alas应该先尝试重启游戏，失败后再通知人工。
