### ISSUE TITLE
希望增加科研提交的部件种类筛选功能

### ISSUE THREAD

**Issue by hllyd** [LmeSzinc/AzurLaneAutoScript#4320]
### 你的功能请求是否与问题有关？

因为长期跑科研，白通用部件只剩下个位数了，一滴都掏不出来了
很需要一个筛选部件的功能，不然只能手动或者放弃所有舰装解析了

### 解决方案

可以通过舰装解析的项目名判断需要的部件种类，也可以通过提交部件的图标判断
或者只是加入筛选词条，自己写筛选条件也可以（现在的筛选词条好像只筛选时间，没有筛选项目的）

**Comment by guoh064** [comment]
多刷紧急委托
