### ISSUE TITLE
請求更新台服活動“埋葬於彼岸之花”

### ISSUE THREAD

**Issue by a5341007** [LmeSzinc/AzurLaneAutoScript#4345]
### 你的功能请求是否与问题有关？

埋葬於彼岸之花更新了，請求更新一下。

### 解决方案

請求推送文件

### 其他内容

![image](https://github.com/user-attachments/assets/5735f090-7b13-41e5-878e-5e6a2f47f2fa)

**Comment by a5341007** [comment]
@Air111 勞煩您有空更新一下，感謝。

**Comment by Air111** [comment]
你可以在每次维护开始后就发一个issue，提供活动开始日期和活动名称（繁中），这样比较有机会赶上针对国服活动更新的脚本更新，不然更新时间就得看lme心情了x

**Comment by a5341007** [comment]
> 你可以在每次维护开始后就发一个活动，提供活动开始日期和名称（繁中），这样比较有机会赶上针对国服活动更新的剧本更新，不然更新时间就得看lme心情了x

好的，謝謝您。
