### ISSUE TITLE
关于希望能够增加对模拟器1080p分辨率的支持

### ISSUE THREAD

**Issue by Amami-Nagi** [LmeSzinc/AzurLaneAutoScript#4346]
### 你的功能请求是否与问题有关？

打扰了，这边由于一直用的是4k或者更高分辨率的屏幕，720p的显示效果实在是糊的没有办法看了，每次换别的游戏或者先要自己手操都要重启一遍模拟器来更改分辨率，如今高分辨率显示器也在慢慢普及了，我想询问一下有没有将来添加对于更高分辨率的支持的安排，我认为在高分辨率这还是有点用的，感谢

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/4177#issuecomment-2351017884
