### ISSUE TITLE
希望增加一个刷图时检测是否战败并进行处理的功能

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#4350]
### 你的功能请求是否与问题有关？

低耗刷图时偶尔会用一些有战败几率的配置，这种在低耗时是可接受的，但alas一旦遇到战败就会直接报错需要手动重启，造成很大不便。既然已经做了3油低耗的刷紧急委托，那要不要考虑更进一步把战败时自动撤退并继续刷之类的选项也加进alas里？

**Comment by LmeSzinc** [comment]
打不过就打低级图或者开挂，脚本不负责解决这个问题
