### ISSUE TITLE
maa更新后alas调用maa报错

### ISSUE THREAD

**Issue by Shawn88-ops** [LmeSzinc/AzurLaneAutoScript#4354]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题目，更新maa前可以正常连接，更新maa后提示动态链接库(DLL)初始化例程失败，鉴于alas的maa板块并没有日志并且复制会导致界面卡死，因此只有报错截图，是本机确少必要dll还是怎么回事呢

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/13c8d027-7259-45e2-8090-89978af1896b)
![image](https://github.com/user-attachments/assets/ca0d5d86-0d27-49c5-97f5-f79e39fbdd74)
![image](https://github.com/user-attachments/assets/265912ed-f481-4585-9d39-3d29e8838f61)
![image](https://github.com/user-attachments/assets/852aabfb-7c1b-4399-93fe-ab54c5604382)

**Comment by LDVC124** [comment]
maa 更新了.net 和 vc++, 也许alas需要兼容

**Comment by Shawn88-ops** [comment]
emm也就是说应该不是本机的问题吧

**Comment by jcm007** [comment]
×我已经搜索了现有的 issues
#4314

**Comment by Shawn88-ops** [comment]
有更早的啊，那没事了，可惜还没修

**Comment by Shawn88-ops** [comment]
更新新版本后依然无法调用maa是为什么呢
![image](https://github.com/user-attachments/assets/6497a1c7-1995-4285-a4bb-39bc8b7f2f6b)
![image](https://github.com/user-attachments/assets/2e8ca109-6ecc-40a0-88c0-a994c2c72fcb)
![image](https://github.com/user-attachments/assets/a9b4171f-5279-4561-b026-ff3f3320a73a)

**Comment by AsahiWys** [comment]
我已解决无法调用maa的问题。

**Comment by AsahiWys** [comment]
我已解决无法调用maa的问题。

**Comment by AsahiWys** [comment]
我已解决无法调用maa的问题。
原因如下：
alas先加载了安装包中内置的低版本dll文件，导致maa无法使用高版本dll文件。
解决方法：
进入alas的安装目录中，找到文件夹中的MSVCP140.dll（或显示为msvcp.dll）将其删除即可。
经测试删除该文件后可正常使用。

**Comment by Shawn88-ops** [comment]
> 我已解决无法调用maa的问题。 原因如下： alas先加载了安装包中内置的低版本dll文件，导致maa无法使用高版本dll文件。 附本人电脑上的文件地址作为参考 F:\Game\phone\tools\AlasApp_0.4.7_fullcn\AzurLaneAutoScript\toolkit\Lib\site-packages\PIL 解决方法： 进入alas的安装目录中，找到文件夹中的MSVCP140.dll（或显示为msvcp.dll）将其删除即可。 经测试删除该文件后可正常使用。

感谢！已经成功解决
