### ISSUE TITLE
請求更新台服活動「雪境迷蹤」

### ISSUE THREAD

**Issue by a5341007** [LmeSzinc/AzurLaneAutoScript#4378]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

求推送更新，感謝Lme和各位大佬

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图
![image](https://github.com/user-attachments/assets/c99eaa1c-6321-483c-8ece-0c3a2546a840)

_No response_

**Comment by starryac1** [comment]
开发大佬能不能分享一个手动改活动的位置，找不到改哪里才能匹配老活动

**Comment by Air111** [comment]
d5c7eaa
