### ISSUE TITLE
有考虑使用紧急委托在活动困难图刷取时增加更换舰船的功能吗

### ISSUE THREAD

**Issue by ycm17705746621** [LmeSzinc/AzurLaneAutoScript#4381]
### 你的功能请求是否与问题有关？

使用紧急委托功能在C2进行刷取时无法更换舰船

### 解决方案

1.长按后排1号位位置，进行装备记录，并脱下所有装备
2.短按后排1号位位置，进入舰船选择界面，直接点击确定以让此舰退出编队
3.短按后排1号位位置，按照设定逻辑选择舰船
4.前排流程类似，不再赘述

**Comment by guoh064** [comment]
#4022

**Comment by ycm17705746621** [comment]
> #4022

对于  #4022 中提到的问题我有些构想，第一个问题是否可以尝试使用常用舰船功能来标记原舰船，并在尝试替换舰船失败后在常用舰船中匹配与原舰船同名的零破舰船；对于代码美观与可读性的问题……也许可以尝试将原逻辑作为父类，继承子类重写关于舰船更换的逻辑用于困难图？或是尝试把原本用于更换舰船的逻辑单独封装为一个类，并写一个用于在困难图更换舰船的类，再根据self.stage[0]是否为"C"或"D"来分别调用？
