### ISSUE TITLE
請求更新台服活動「危險發明逼近中！」

### ISSUE THREAD

**Issue by a5341007** [LmeSzinc/AzurLaneAutoScript#4399]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

雪境迷蹤活動已關閉。
麻煩大佬們推送更新了。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/bbebf583-ca16-4e34-9655-b126aee85bb7)
![image](https://github.com/user-attachments/assets/fd521359-f507-4a1e-948d-4bc657d67515)

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/pull/4404/commits/4eef4050efdd369445911574893b2160cd777e7e
