### ISSUE TITLE
雷电模拟器替换ADB后仍然无法成功链接

### ISSUE THREAD

**Issue by Syaoran-Tang** [LmeSzinc/AzurLaneAutoScript#441]
RT

确认替换了模拟器里的原ADB，确认模拟器里开启了ADB远程调试，adb devices也确认了serial名称无误。但是还是无法链接，求解

**Comment by Zorachristine** [comment]
請先確認雷電模擬器的ADB是否有禁止連接，
如下圖所示，ADB的選項選擇為「開啟本地連接」
![image](https://user-images.githubusercontent.com/73385275/121012579-6f538d80-c7ca-11eb-882b-0ce603ed37a1.png)

如果還是不行，那麼再試試先前已回覆的解決方式#307

**Comment by LmeSzinc** [comment]
#482
