### ISSUE TITLE
猫窝在特定搭配下会识别错误

### ISSUE THREAD

**Issue by W1NDes** [LmeSzinc/AzurLaneAutoScript#4420]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当伯克喵和大橘猫窝一起使用的时候，猫窝fort会卡在self.appear(MEOWFFICER FORT GET XP 1)，然后一直死循环，无法动。相关截图附下

### 如何复现

1. 前往 '猫窝'
2. 把`伯克喵`和`大橘猫窝`放在第一栏
3. 启用指挥猫功能
4. 出现问题

### 相关 Logs

```Text
════════════════════════════════════════════════════════ MEOWFFICER BUY ════════════════════════════════════════════════════════
INFO     10:06:48.130 │ MEOWFFICER BUY                                                                                          
INFO     10:06:48.143 │ Loading OCR model: ./bin/cnocr_models/azur_lane                                                         
INFO     10:06:48.202 │ [OCR_MEOWFFICER 0.070s] 13/15                                                                           
INFO     10:06:48.205 │ [Meowfficer_remain] 13                                                                                  
INFO     10:06:48.207 │ Already bought 2 today, stopped                                                                         
═══════════════════════════════════════════════════════ MEOWFFICER FORT ════════════════════════════════════════════════════════
INFO     10:06:48.209 │ MEOWFFICER FORT                                                                                         
INFO     10:06:48.222 │ Click ( 851,  640) @ MEOWFFICER_FORT_ENTER
```

### 截图

![模拟器和脚本卡在此处](https://github.com/user-attachments/assets/cd3e544a-880c-41ad-9fc4-0a979a68060a)
![大橘猫窝的造型](https://github.com/user-attachments/assets/c2ee655c-5ad8-4b2f-8f9e-b26ecf83b14d)
![图片识别到的](https://github.com/user-attachments/assets/fe28bf8c-21af-486a-a772-cdadf2988f1a)
![伯克喵和猫窝](https://github.com/user-attachments/assets/6638f131-e39e-45b2-89ed-65d716294fc1)

**Comment by LmeSzinc** [comment]
等待报错，上传log

**Comment by W1NDes** [comment]
> 等待报错，上传log

好的，我挂完日常复现一遍

**Comment by W1NDes** [comment]
Merge pull request #4423 后已经正常了
