### ISSUE TITLE
刷紧急委托无法选择新版本活动关卡

### ISSUE THREAD

**Issue by YeQing5566** [LmeSzinc/AzurLaneAutoScript#4421]
### 你的功能请求是否与问题有关？

目前活动关卡似乎无法可持续的自动低耗，例如刷紧急委托会自动换前排和装备，以及后排也会如此，还会判断等级，便可以自动低耗
但刷紧急委托，只能选择就版本活动的关卡，例如A3，D3，但新活动的关卡名无法生效

### 解决方案

依据刷紧急委托，复刻一份低耗刷活动pt的功能
或者直接复用刷紧急委托，新增对新活动关卡名的支持

**Comment by LmeSzinc** [comment]
现在又没有活动，打个锤子活动图

**Comment by YeQing5566** [comment]
> 现在又没有活动，打个锤子活动图

之前联动活动时遇到的问题，今天提的issue

**Comment by YeQing5566** [comment]
> 现在又没有活动，打个锤子活动图
当时是尝试在刷紧急委托输入T4好像？然后开始运行后自动重置为了2-4

**Comment by YeQing5566** [comment]
> 自己设置pt上限了吧

嘶，上限的优先级是会作用于非活动出击（刷紧急委托）么，下周活动我试试，有可能哦

**Comment by noelfwfaw** [comment]
> > 自己设置pt上限了吧
> 
> 嘶，上限的优先级是会作用于非活动出击（刷紧急委托）么，下周活动我试试，有可能哦

会作用的。

**Comment by YeQing5566** [comment]
> > > 自己设置pt上限了吧
> > 
> > 
> > 嘶，上限的优先级是会作用于非活动出击（刷紧急委托）么，下周活动我试试，有可能哦
> 
> 会作用的。

好的，感谢大家的解答，下次我再试试利用刷紧急委托刷活动
