### ISSUE TITLE
使用刷紧急委托功能会在一段时间后莫名进入演习界面

### ISSUE THREAD

**Issue by wuhu128** [LmeSzinc/AzurLaneAutoScript#4434]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

在某次更新后，使用刷紧急委托功能会在一段时间后莫名进入演习界面，之后会报错停止运行

### 如何复现

1. 运行刷紧急委托
2. 一段时间后，自动进入演习界面
3. 出现问题

### 预期行为

修复该问题

### 相关 Logs

```Text
日志过长，无法全部粘贴，详见截图中的链接
```

### 截图

更多截图和日志见此链接https://pan.baidu.com/s/1xD1wlmCoa12lMkM4-m38ag?pwd=a3p6

**Comment by Shane-Xue** [comment]
#4425 有人已经提过了
