### ISSUE TITLE
委托等级过高，条件困难，无法正常派遣委托，直接就跳过委托

### ISSUE THREAD

**Issue by lanlanTAT** [LmeSzinc/AzurLaneAutoScript#4449]
### 你的功能请求是否与问题有关？

萌新50多级，50级的委托需要100等级以上的舰船，但唯一一艘还在编队里无法调用，而alas选取该委托推荐没有适合的船，就卡死跳过委托

### 解决方案

能否是增加选项让alas不选择某个等级的委托，或者委托条件不达标，排除该委托后另选其他委托进行

**Comment by lanlanTAT** [comment]
升级了艘100级舰船，且未在编队中，但因推荐中不会选用其舰船，导致一直重启游戏，手动选取后委托开始后方才恢复

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#%E6%B2%A1%E6%9C%89%E7%AC%A6%E5%90%88%E5%A7%94%E6%89%98%E8%A6%81%E6%B1%82%E7%9A%84%E8%A7%92%E8%89%B2%E5%AF%BC%E8%87%B4%E6%97%A0%E6%B3%95%E5%BC%80%E5%A7%8B%E5%A7%94%E6%89%98--no-ship-matches-the-required-for-the-commission-which-cannot-be-started-2460
