### ISSUE TITLE
刷紧急委托换装备时有概率识别错误无法更换导致前后排经常空着格子上场

### ISSUE THREAD

**Issue by clark1091** [LmeSzinc/AzurLaneAutoScript#4455]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

如题，我给前排配的是这么一套装备，但第二天起来一看前排身上只剩一门炮了。如果这是使用问题，那求问如何设置能阻止这种情况发生？是要提高模拟器分配的资源还是电脑保持高性能模式？我的配置是12800hx和3080ti laptop，32G内存，给mumu分配了1个核心3G内存

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/9e2dc5f7-65f1-4ab9-8ff6-28d1716b4815)

**Comment by clark1091** [comment]
log没办法发，因为我完全搞不清楚这是啥时候出的错，也不可能人工盯梢一整天找时间点，只知道每天爬起来都能看见少了装备= =

**Comment by clark1091** [comment]
但现在这个版本出现的也太频繁了，甚至一天会翻车两三次

**Comment by noelfwfaw** [comment]
> 但现在这个版本出现的也太频繁了，甚至一天会翻车两三次

你把虚拟机配置调高些，60帧。
紧急委托没啥人维护；
你把整个log文件上传，怎么看log是程序员的事。

**Comment by clark1091** [comment]
截到出错时的log了
───────────────────────────────── CHANGE VANGUARD ─────────────────────────────────
INFO     22:07:42.875 │ CHANGE VANGUARD                                            
INFO     22:07:42.876 │ <<< UI CLICK >>>                                           
INFO     22:07:42.883 │ Click ( 508,  482) @ FLEET_ENTER                           
INFO     22:07:43.481 │ <<< UI CLICK >>>                                           
INFO     22:07:43.487 │ Click (1145,   14) @ DOCK_FILTER                           
INFO     22:07:44.077 │ Setting options DOCK,                                      
INFO     22:07:44.090 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     22:07:44.104 │ Setting options DOCK, sort='level', index='dd',            
         faction=['eagle', 'iron'], rarity='common', extra='can_limit_break'       
INFO     22:07:44.117 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     22:07:44.130 │ Click ( 743,  165) @ FILTER_INDEX_3_0                      
INFO     22:07:44.184 │ Click ( 421,  275) @ FILTER_FACTION_1_0                    
INFO     22:07:44.237 │ Click ( 859,  283) @ FILTER_FACTION_4_0                    
INFO     22:07:44.289 │ Click ( 454,  415) @ FILTER_RARITY_1_0                     
INFO     22:07:44.342 │ Click ( 894,  489) @ FILTER_EXTRA_4_0                      
INFO     22:07:44.487 │ [DOCK] sort/level, index/dd, faction/eagle, faction/iron,  
         rarity/common, extra/no_limit                                             
INFO     22:07:44.791 │ [DOCK] sort/level, index/dd, faction/eagle, faction/iron,  
         rarity/common, extra/can_limit_break                                      
INFO     22:07:44.805 │ <<< UI CLICK >>>                                           
INFO     22:07:44.809 │ Click ( 804,  656) @ DOCK_FILTER_CONFIRM                   
INFO     22:07:46.298 │ Favourite_filter set to off                                
INFO     22:07:46.300 │ [Favourite_filter] off                                     
INFO     22:07:46.303 │ <<< FINDING VANGUARD >>>                                   
INFO     22:07:46.306 │ Limitaions set to {'level': (100, 100), 'emotion': (10,    
         150), 'rarity': 'any', 'fleet': 4, 'status': 'free'}                      
INFO     22:07:46.309 │ Dork_sorting set to Descending                             
INFO     22:07:46.311 │ [Dork_sorting] Descending                                  
INFO     22:07:46.674 │ [DOCK_LEVEL_OCR 0.361s] [0, 100, 100, 100, 100, 100, 100,  
         0, 0, 0, 0, 0, 0, 0]                                                      
INFO     22:07:46.850 │ [DOCK_EMOTION_OCR 0.175s] [0, 150, 150, 1, 130, 150, 70, 0,
         0, 0, 0, 0, 0, 0]                                                         
INFO     22:07:46.972 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_0_0)                                           
INFO     22:07:46.974 │ Ship(rarity=None, level=100, emotion=150, fleet=5,         
         status='free', button=CARD_1_0)                                           
INFO     22:07:46.976 │ Ship(rarity=None, level=100, emotion=150, fleet=6,         
         status='free', button=CARD_2_0)                                           
INFO     22:07:46.979 │ Ship(rarity=None, level=100, emotion=1, fleet=4,           
         status='free', button=CARD_3_0)                                           
INFO     22:07:46.981 │ Ship(rarity=None, level=100, emotion=130, fleet=0,         
         status='free', button=CARD_4_0)                                           
INFO     22:07:46.982 │ Ship(rarity=None, level=100, emotion=150, fleet=0,         
         status='free', button=CARD_5_0)                                           
INFO     22:07:46.984 │ Ship(rarity=None, level=100, emotion=70, fleet=0,          
         status='free', button=CARD_6_0)                                           
INFO     22:07:46.985 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_0_1)                                           
INFO     22:07:46.987 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_1_1)                                           
INFO     22:07:46.990 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_2_1)                                           
INFO     22:07:46.991 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_3_1)                                           
INFO     22:07:46.993 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_4_1)                                           
INFO     22:07:46.995 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_5_1)                                           
INFO     22:07:46.997 │ Ship(rarity=None, level=0, emotion=0, fleet=0,             
         status='free', button=CARD_6_1)                                           
INFO     22:07:46.999 │ Limitaions set to {'level': (100, 100), 'emotion': (10,    
         150), 'rarity': 'any', 'fleet': 0, 'status': 'free'}                      
INFO     22:07:47.002 │ Favourite_filter set to off                                
INFO     22:07:47.004 │ [Favourite_filter] off                                     
INFO     22:07:47.309 │ [DOCK_LEVEL_OCR 0.304s] [0, 100, 100, 100, 100, 100, 100,  
         0, 0, 0, 0, 0, 0, 0]                                                      
INFO     22:07:47.495 │ [DOCK_EMOTION_OCR 0.183s] [0, 150, 150, 1, 130, 150, 70, 0,
         0, 0, 0, 0, 0, 0]                                                         
INFO     22:07:47.665 │ [DOCK_SELECTED 0.046s] 0/1                                 
INFO     22:07:47.668 │ Click ( 945,  154) @ CARD_5_0                              
INFO     22:07:47.852 │ [DOCK_SELECTED 0.042s] 0/1                                 
INFO     22:07:48.150 │ [DOCK_SELECTED 0.048s] 1/1                                 
INFO     22:07:48.153 │ <<< UI CLICK >>>                                           
INFO     22:07:48.159 │ Click (1172,   26) @ DOCK_FILTER                           
INFO     22:07:48.720 │ Setting options DOCK,                                      
INFO     22:07:48.735 │ [DOCK] sort/level, index/dd, faction/eagle, faction/iron,  
         rarity/common, extra/can_limit_break                                      
INFO     22:07:48.750 │ Click ( 329,  168) @ FILTER_INDEX_0_0                      
INFO     22:07:48.804 │ Click ( 243,  303) @ FILTER_FACTION_0_0                    
INFO     22:07:48.856 │ Click ( 321,  432) @ FILTER_RARITY_0_0                     
INFO     22:07:48.909 │ Click ( 299,  496) @ FILTER_EXTRA_0_0                      
INFO     22:07:49.059 │ [DOCK] sort/level, index/all, faction/all, rarity/common,  
         extra/can_limit_break                                                     
INFO     22:07:49.353 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     22:07:49.366 │ Setting options DOCK, sort='level', index='all',           
         faction='all', rarity='all', extra='no_limit'                             
INFO     22:07:49.380 │ [DOCK] sort/level, index/all, faction/all, rarity/all,     
         extra/no_limit                                                            
INFO     22:07:49.392 │ <<< UI CLICK >>>                                           
INFO     22:07:49.397 │ Click ( 829,  653) @ DOCK_FILTER_CONFIRM                   
INFO     22:07:51.105 │ Favourite_filter set to off                                
INFO     22:07:51.107 │ [Favourite_filter] off                                     
INFO     22:07:51.111 │ Dork_sorting set to Descending                             
INFO     22:07:51.114 │ [Dork_sorting] Descending                                  
INFO     22:07:51.131 │ Click (1038,  665) @ SHIP_CONFIRM                          
INFO     22:07:52.006 │ Change vanguard ship success                               
──────────────────────────── EQUIP VANGUARD EQUIPMENT ─────────────────────────────
INFO     22:07:52.010 │ EQUIP VANGUARD EQUIPMENT                                   
INFO     22:07:52.013 │ <<< UI CLICK >>>                                           
INFO     22:07:52.020 │ Click ( 958,  677) @ FLEET_DETAIL                          
INFO     22:07:52.312 │ Click ( 776,  380) @ FLEET_DETAIL_ENTER                    
INFO     22:07:53.214 │ Equipment take off                                         
INFO     22:07:53.224 │ Click (1173,   94) @ EQUIPMENT_OPEN                        
INFO     22:07:53.502 │ Click ( 984,  574) @ EQUIP_OFF                             
INFO     22:07:54.110 │ Click ( 780,  513) @ POPUP_CONFIRM_EQUIPMENT_TAKE_OFF      
INFO     22:07:54.710 │ Equipment take off ended                                   
INFO     22:07:54.713 │ Take on equipment                                          
INFO     22:07:54.716 │ SHIP_SIDE_NAVBAR set to right=2 bottom=2                   
INFO     22:07:54.720 │ Nav item active: 3 from range (0, 3)                       
INFO     22:07:54.723 │ Click (  37,  345) @ SHIP_SIDE_NAVBAR_0_2                  
INFO     22:07:55.010 │ Nav item active: 2 from range (0, 3)                       
INFO     22:07:55.011 │ Take on 0                                                  
INFO     22:07:55.015 │ <<< UI CLICK >>>                                           
INFO     22:07:55.322 │ Click ( 917,  190) @ EQUIP_TAKE_ON_0                       
INFO     22:07:57.409 │ Equipping_filter set to off                                
INFO     22:07:57.412 │ [Equipping_filter] on                                      
INFO     22:07:57.415 │ Click (  34,  546) @ EQUIPPING_ON                          
INFO     22:07:57.709 │ [Equipping_filter] off                                     
INFO     22:07:59.082 │ Equip equipment                                            
INFO     22:07:59.085 │ <<< UI CLICK >>>                                           
INFO     22:07:59.228 │ Click ( 335,  142) @ EQUIPMENT                             
INFO     22:07:59.825 │ Equip confirm                                              
INFO     22:07:59.828 │ <<< UI CLICK >>>                                           
INFO     22:08:00.137 │ Click ( 930,  664) @ EQUIP_CONFIRM                         
INFO     22:08:00.728 │ Take on 1                                                  
INFO     22:08:00.730 │ <<< UI CLICK >>>                                           
INFO     22:08:03.440 │ Click ( 944,  358) @ EQUIP_TAKE_ON_1                       
INFO     22:08:04.034 │ Equipping_filter set to off                                
INFO     22:08:04.036 │ [Equipping_filter] on                                      
INFO     22:08:04.039 │ Click (  51,  563) @ EQUIPPING_ON                          
INFO     22:08:04.335 │ [Equipping_filter] unknown                                 
INFO     22:08:04.637 │ [Equipping_filter] off                                     
INFO     22:08:05.396 │ Equip equipment                                            
INFO     22:08:05.399 │ <<< UI CLICK >>>                                           
INFO     22:08:05.536 │ Click ( 973,  154) @ EQUIPMENT                             
INFO     22:08:05.827 │ Equip confirm                                              
INFO     22:08:05.830 │ <<< UI CLICK >>>                                           
INFO     22:08:06.138 │ Click ( 874,  649) @ EQUIP_CONFIRM                         
INFO     22:08:06.739 │ Take on 2                                                  
INFO     22:08:06.741 │ <<< UI CLICK >>>                                           
INFO     22:08:06.762 │ Click ( 887,  569) @ EQUIP_TAKE_ON_2                       
INFO     22:08:09.444 │ Equipping_filter set to off                                
INFO     22:08:09.447 │ [Equipping_filter] on                                      
INFO     22:08:09.449 │ Click (  42,  524) @ EQUIPPING_ON                          
INFO     22:08:09.750 │ [Equipping_filter] off                                     
INFO     22:08:11.095 │ Equip equipment                                            
INFO     22:08:11.097 │ <<< UI CLICK >>>                                           
INFO     22:08:11.246 │ Click ( 338,  312) @ EQUIPMENT                             
INFO     22:08:11.549 │ Equip confirm                                              
INFO     22:08:11.551 │ <<< UI CLICK >>>                                           
INFO     22:08:11.844 │ Click ( 848,  653) @ EQUIP_CONFIRM                         
INFO     22:08:12.442 │ Take on 3                                                  
INFO     22:08:12.444 │ <<< UI CLICK >>>                                           
INFO     22:08:15.179 │ Click ( 144,  290) @ EQUIP_TAKE_ON_3                       
INFO     22:08:15.778 │ Equipping_filter set to off                                
INFO     22:08:15.781 │ [Equipping_filter] on                                      
INFO     22:08:15.783 │ Click (  36,  534) @ EQUIPPING_ON                          
INFO     22:08:16.083 │ [Equipping_filter] off                                     
**INFO     22:08:17.438 │ Drag (1002,  477) -> (1011,  288)                          
INFO     22:08:18.882 │ Drag ( 846,  486) -> ( 859,  294)                          
INFO     22:08:20.344 │ Drag ( 835,  587) -> ( 835,  397)                          
INFO     22:08:21.779 │ Drag (1008,  544) -> (1002,  354)                          
INFO     22:08:23.187 │ Drag ( 821,  436) -> ( 823,  244)                          
WARNING  22:08:24.632 │ No recorded equipment was found.**                           
INFO     22:08:24.634 │ <<< UI CLICK >>>                                           
INFO     22:08:24.769 │ Click (  57,   56) @ BACK_ARROW                            
INFO     22:08:25.364 │ Take on 4                                                  
INFO     22:08:25.366 │ <<< UI CLICK >>>                                           
INFO     22:08:25.370 │ Click ( 177,  459) @ EQUIP_TAKE_ON_4                       
INFO     22:08:25.973 │ Equipping_filter set to off                                
INFO     22:08:25.975 │ [Equipping_filter] on                                      
INFO     22:08:25.978 │ Click (  33,  544) @ EQUIPPING_ON                          
INFO     22:08:26.266 │ [Equipping_filter] off                                     
INFO     22:08:27.622 │ Equip equipment                                            
INFO     22:08:27.625 │ <<< UI CLICK >>>                                           
INFO     22:08:27.776 │ Click ( 648,  148) @ EQUIPMENT                             
INFO     22:08:28.080 │ Equip confirm                                              
INFO     22:08:28.082 │ <<< UI CLICK >>>                                           
INFO     22:08:28.377 │ Click ( 907,  664) @ EQUIP_CONFIRM                         
INFO     22:08:28.973 │ <<< UI CLICK >>>                                           
INFO     22:08:29.275 │ Click (  63,   41) @ BACK_ARROW                            
INFO     22:08:30.192 │ <<< UI CLICK >>>                                           
INFO     22:08:30.492 │ Click (  56,   56) @ BACK_ARROW                            
INFO     22:08:30.810 │ Pending tasks: ['GemsFarming']                             
INFO     22:08:30.813 │ [Task] GemsFarming (Enable, 2024-12-19 08:14:15)           
INFO     22:08:30.815 │ Continue task `GemsFarming (Enable, 2024-12-19 08:14:15)`  
INFO     22:08:30.817 │ Stage name b3 is from event event_20241219_cn
