### ISSUE TITLE
目录下产生大量core.xxx文件，导致磁盘空间被占满

### ISSUE THREAD

**Issue by DarkGhast** [LmeSzinc/AzurLaneAutoScript#4460]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

目录下产生大量core.xxx文件，导致磁盘空间被占满
![image](https://github.com/user-attachments/assets/f8f14849-38ce-4393-a33e-6fc4a914c53c)
![image](https://github.com/user-attachments/assets/2006c577-2cd8-46ce-83c8-b4ed8d37510b)

### 如何复现

不太确定。但是由于Alas经常卡在Loading OCR model: ./bin/cnocr_models/azur_lane   ，这两天进行了多次强制重启（首页——工具——force restart）

### 预期行为

提供解决方案或减少该文件的产生

**Comment by LmeSzinc** [comment]
你的系统打开了 core dump，所以在你强制关闭 alas 的时候会产生 dump file，关掉
Loading OCR model: 慢是你的 cpu 拉跨

**Comment by DarkGhast** [comment]
不是慢，是到Loading OCR model: ./bin/cnocr_models/azur_lane显示发生错误，但是没有发邮件
