### ISSUE TITLE
出问题后无法重新安装

### ISSUE THREAD

**Issue by jiangzihan123** [LmeSzinc/AzurLaneAutoScript#455]
之前模拟器出问题删除重装后脚本就打不开了 全部删除后在打开也不行 会在设置模拟器哪里输入后跳出 求大佬解惑

**Comment by DebuAqua** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/482

目前可以用 QQ 群内的大佬给出的临时解决方案。当然还是希望作者能尽快更新安装教程或初始化脚本。
