### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by Edward1949** [LmeSzinc/AzurLaneAutoScript#463]
![捕获2](https://user-images.githubusercontent.com/70761981/120914348-4d75e000-c6d0-11eb-973c-c5664207bfa6.PNG)

**Comment by lxy506414792** [comment]
+1

**Comment by Ragecks** [comment]
同问

**Comment by DebuAqua** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/482

目前可以用 QQ 群内的大佬给出的临时解决方案。当然还是希望作者能尽快更新安装教程或初始化脚本。

**Comment by Ragecks** [comment]
感谢，如果作者可以尽快改进就再好不过了

**Comment by LmeSzinc** [comment]
#482
