### ISSUE TITLE
因傻瓜式安装包不再维护，现已无法参考傻瓜式安装教程完成初始化，希望修改目前的教程文档

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#482]
我参照的安装教程为 [傻瓜式安装教程](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn)
<img width="744" alt="微信图片_20210612223123" src="https://user-images.githubusercontent.com/70339606/121779381-ec697300-cbcd-11eb-9d31-6762be5432b9.png">
根据教程描述，当我选择 [1] Manual Setup ，随后选择 Y ，并输入模拟器 SERIAL 后，脚本就会尝试连接模拟器。
但我输入 SERIAL 后，alas.bat 自动关闭，没有任何尝试连接模拟器的迹象。而且再次运行 alas.bat 时，依然提示首次运行，需要设置模拟器连接。

目前 QQ 群中有临时解决方案：
在 Alas-Deploy-Tool-V4.bat 执行完成后，执行 console.bat ，并在出现的命令行窗口中输入 pip install -r requirements.txt ，执行完成后再运行 alas.bat ，完成首次运行的设置

**Comment by Kurisu3071** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/413#issuecomment-825541885
閃退問題這個應該能解決

**Comment by DebuAqua** [comment]
目前作者已在QQ群中声明傻瓜式安装包无人维护
希望对目前的教程做出修改，例如把手动安装教程放在傻瓜式安装教程之前

**Comment by DebuAqua** [comment]
安装教程已更新：[https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn_manual](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn_manual)
同时建议关闭所有与 alas.bat 相关的 issue
