### ISSUE TITLE
运行alas.bat闪退

### ISSUE THREAD

**Issue by 450177215** [LmeSzinc/AzurLaneAutoScript#485]
如图，啥也没干，不知道为什么突然进不去了。删除.git文件夹可以进去但是不能再热更新。运行Alas-Deploy-Tool-V4.bat后重新下载.git，但问题还是没有得到解决，每次运行alas.bat都会运行图中几行代码然后迅速闪退，这是好不容易截的图。求助T T。
-
![问题](https://user-images.githubusercontent.com/85773117/121799844-e8fdd800-cc1d-11eb-9d72-552043409559.png)

**Comment by LmeSzinc** [comment]
#482
