### ISSUE TITLE
更新错误

### ISSUE THREAD

**Issue by JeanRent** [LmeSzinc/AzurLaneAutoScript#500]
使用alas.bat更新不成功

== | GIT Found in D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\Git\mingw64\bin\git.exe Proceeding
== | Updating from "origin" repository..
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (95/95), done.
Receiving objects:  55% (117/212)
Receiving objects: 100% (212/212), 102.31 KiB | 776.00 KiB/s, done.
Resolving deltas: 100% (163/163), completed with 51 local objects.
error: unknown object type 5 at offset 9530756 in .git/objects/pack/pack-1b608c381e107e462354dc42d5294468dbdb83ee.pack
fatal: packed object df214b5617abcaee899f505283002a48190c5b25 (stored in .git/objects/pack/pack-1b608c381e107e462354dc42d5294468dbdb83ee.pack) is corrupt
error: https://github.com/LmeSzinc/AzurLaneAutoScript.git did not send all necessary objects

error: unknown object type 5 at offset 9530756 in .git/objects/pack/pack-1b608c381e107e462354dc42d5294468dbdb83ee.pack
fatal: packed object df214b5617abcaee899f505283002a48190c5b25 (stored in .git/objects/pack/pack-1b608c381e107e462354dc42d5294468dbdb83ee.pack) is corrupt
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (95/95), done.
Receiving objects:  65% (138/212)
Receiving objects: 100% (212/212), 102.31 KiB | 851.00 KiB/s, done.
Resolving deltas: 100% (163/163), completed with 51 local objects.
error: unable to write file .git/objects/pack/pack-425fb21f126f718693aa8361f6616b56b2306ffa.pack: Permission denied
fatal: cannot store pack file
fatal: index-pack failed
== | Updating requirements.txt
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the 'D:\AzurLaneAutoScript\AzurLaneAutoScript\toolkit\python.exe -m pip install --upgrade pip' command.
== | requirements.txt updated
== | DONE

== | Please re-run this batch to make the settings take effect.
== | Please re-run the "alas.bat" to make the settings take effect.
=======================================================================================================================
== Press any key to exit...

**Comment by AkenoSyuRi** [comment]
以管理员身份运行

**Comment by LmeSzinc** [comment]
网络传输错误，重试就行
