### ISSUE TITLE
大世界遇到明石的位置，可能会造成明石无法被正确侦测

### ISSUE THREAD

**Issue by yhtojy** [LmeSzinc/AzurLaneAutoScript#502]
**Describe the bug**
使用"大世界全自动"的短猫相接时，如果自动攻略最后停止位置，是在明石的上方或左方，会被判定为没有明石

**To Reproduce**
1. 有明石的大世界地图
2. 移动舰队到明石的上方或左方
3. 启动"大世界全自动"功能，仅选择只有"短猫相接"功能开启
只要舰队是在明石的上方或左方时，都不会成功判定地图中有明石存在

**Expected behavior**
不管自动攻略停止位置都要能够侦测到明石

**Screenshots**
![Screenshot_2021-06-26-18-52-34](https://user-images.githubusercontent.com/3877705/123513743-5a7b6300-d6c1-11eb-965b-b6eca24d5b3c.png)
![Screenshot_2021-06-26-18-52-55](https://user-images.githubusercontent.com/3877705/123513745-5c452680-d6c1-11eb-85c0-6409f78e3f5a.png)
![Screenshot_2021-06-26-19-16-05](https://user-images.githubusercontent.com/3877705/123513746-5c452680-d6c1-11eb-963a-82b22595f909.png)
![Screenshot_2021-06-26-19-16-08](https://user-images.githubusercontent.com/3877705/123513747-5cddbd00-d6c1-11eb-8092-b6057d4e4097.png)

**Log**

> 2021-06-26 18:31:44.127 | INFO | Get OS auto search reward
> 2021-06-26 18:31:44.555 | INFO | OS auto search finished
> 2021-06-26 18:31:44.606 | INFO | No akashi on this map

**Comment by yhtojy** [comment]
![Screenshot_2021-06-30-20-00-57](https://user-images.githubusercontent.com/3877705/123973047-fcff5300-d9ed-11eb-864e-0e12cd9c9056.png)
![Screenshot_2021-06-30-21-46-56](https://user-images.githubusercontent.com/3877705/123973054-fec91680-d9ed-11eb-8388-ab9296cbdbad.png)
根据测试，左侧的没问题了，但是上方的还是会侦测不到

**Comment by LmeSzinc** [comment]
提供的图片无法复现问题
```python
from module.os.map import OSMap
self = OSMap('alas')
self.image_file = '123973054-fec91680-d9ed-11eb-8388-ab9296cbdbad.png'
print(self.radar.predict_akashi(self.device.image))
self.image_file = '123973047-fcff5300-d9ed-11eb-864e-0e12cd9c9056.png'
print(self.radar.predict_akashi(self.device.image))
```
```
(0, 1)
(0, 1)
```

另外，所有情况我这边都有测试，是没有问题的。
```python
from module.os.map import OSMap
from module.base.utils import *
import os
from PIL import Image
folder = 'xxxxx'  # A folder contains 16 screenshots
self = OSMap('alas')
out = Image.new('RGB', tuple(np.array((3, 6)) * 50))
for n, file in enumerate(os.listdir(folder)):
    file = os.path.join(folder, file)
    self.image_file = file
    print(self.radar.predict_akashi(self.device.image))
    area = area_offset((-25, -25, 25, 25), offset=self.radar.center)
    out.paste(self.image_area(area), np.multiply((n % 3, n // 3, n % 3 + 1, n // 3 + 1), 50))
out.show()
```
```
(0, 1)
(0, 1)
(0, 1)
(1, 0)
(1, 0)
(1, 0)
(0, -1)
(0, -1)
(0, -1)
(-1, 0)
(-1, 0)
(-1, 0)
None
None
None
None
```
![image](https://user-images.githubusercontent.com/37934724/124122873-292bda00-daa9-11eb-83da-3dda9fa460fa.png)
