### ISSUE TITLE
大世界遇到明石时，对话选项判断到的数量不正确

### ISSUE THREAD

**Issue by yhtojy** [LmeSzinc/AzurLaneAutoScript#503]
**Describe the bug**
"大世界全自動"運行短貓相接時，遇到明石，選擇了離開，而不是進入商店

**To Reproduce**
1. 在大世界有明石的地圖，艦隊移動到明石身邊
2. 運行"大世界全自動"，僅開啟短貓相接功能。
3. 會看到跳出對話選項，並且選擇了第二個的離開
根據LOG，應該是判斷少一個選項
 @ STORY_OPTION_1_OF_1
 正常應該是 @ STORY_OPTION_1_OF_2

**Expected behavior**
應該點擊進入商店

**Screenshots**
![Screenshot_2021-06-26-19-08-35](https://user-images.githubusercontent.com/3877705/123514105-a3341b80-d6c3-11eb-9ef1-344453c12e42.png)

**Log**
不正常的
> 2021-06-26 18:45:06.731 | INFO | Click (1249,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
> 2021-06-26 18:45:07.680 | INFO | Get OS auto search reward
> 2021-06-26 18:45:08.083 | INFO | OS auto search finished
> 2021-06-26 18:45:08.120 | INFO | Found Akashi on (-1, 0)
> 2021-06-26 18:45:08.120 | INFO | [homo_storage] ((10, 7), [(110.307, 103.657), (1012.311, 103.657), (-32.959, 600.567), (1113.057, 600.567)])
> 2021-06-26 18:45:08.148 | INFO |            center_loca: (5, 4)
> 2021-06-26 18:45:08.148 | INFO | <<< UI CLICK >>>
> 2021-06-26 18:45:08.160 | INFO | Click ( 528,  367) @ E5
> 2021-06-26 18:45:09.001 | INFO | Click (1189,   41) @ STORY_SKIP
> 2021-06-26 18:45:09.428 | INFO | Click ( 898,  365) @ STORY_OPTION_1_OF_1

正常的情況

> 2021-06-26 18:44:26.153 | INFO | Click ( 664,  541) @ AUTO_SEARCH_REWARD
> 2021-06-26 18:44:27.960 | INFO | Get OS auto search reward
> 2021-06-26 18:44:28.352 | INFO | OS auto search finished
> 2021-06-26 18:44:28.390 | INFO | Found Akashi on (-1, 0)
> 2021-06-26 18:44:28.390 | INFO | [homo_storage] ((10, 7), [(110.307, 103.657), (1012.311, 103.657), (-32.959, 600.567), (1113.057, 600.567)])
> 2021-06-26 18:44:28.419 | INFO |            center_loca: (5, 4)
> 2021-06-26 18:44:28.419 | INFO | <<< UI CLICK >>>
> 2021-06-26 18:44:28.430 | INFO | Click ( 531,  359) @ E5
> 2021-06-26 18:44:29.310 | INFO | Click (1184,   42) @ STORY_SKIP
> 2021-06-26 18:44:29.740 | INFO | Click ( 874,  288) @ STORY_OPTION_1_OF_2

**Comment by LmeSzinc** [comment]
确认是自律寻敌后的消息框遮挡了选项，已增加处理。
