### ISSUE TITLE
共斗次数识别失败

### ISSUE THREAD

**Issue by foxwhite25** [LmeSzinc/AzurLaneAutoScript#522]
**Describe the bug**
共斗次数识别失败，15次识别为0

**To Reproduce**
打开每日共斗打15次选项

**Expected behavior**
应该识别出15/15，而不是0

**Screenshots**
![image](https://user-images.githubusercontent.com/39846845/125147124-04e09500-e15c-11eb-885a-f74e1cdc6a18.png)

**Log**
![image](https://user-images.githubusercontent.com/39846845/125147133-12961a80-e15c-11eb-8c90-952973abc97e.png)

**Comment by golden2077** [comment]
我也遇到了同样的问题

**Comment by foxwhite25** [comment]
fixed
