### ISSUE TITLE
当前SOS救援任务UI变动了，无法进行

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#577]
![image](https://user-images.githubusercontent.com/49509508/129543344-149c87a4-e6dc-4172-9f6c-d3a5e5d9e9ea.png)

现在的SOS可以玩家自行选择在几图出现了，和旧版不同
所以估计这块儿 更新后没有再维护了吧。。。

当前甚至可以只打某一张图的SOS，，打完后又继续搜寻该图的信号，感觉比之前更有规律一些

期望开发大大可以考虑整一下这块儿，多谢~

**Comment by LmeSzinc** [comment]
#578
