### ISSUE TITLE
出击时红脸无法自动更换前后排

### ISSUE THREAD

**Issue by chjptc** [LmeSzinc/AzurLaneAutoScript#628]
**Describe the bug**
自动刷钻石时如果在出击选择编队界面有红脸，将不会自动更换前后排，会直接报错。

**To Reproduce**
1. 自动刷钻石委托的队伍中存在红脸
2. 启动脚本
3. See error

**Expected behavior**
应当自动更换前、后排，并再次进行出击

**Screenshots**
![image](https://user-images.githubusercontent.com/91282011/134571178-cc4ad17b-74ac-4dfc-91bc-c2e0150cdf29.png)
![2021-09-23_13-16-30-604171](https://user-images.githubusercontent.com/91282011/134571290-294ac92b-f795-4da2-96c7-338af63d5768.png)

**Log**
Post the entire log snippet that caused you to receive the error
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7220384/log.txt)

**Comment by chjptc** [comment]
Attached is the error log file.
[1632424596683.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7220988/1632424596683.zip)

**Comment by Cyumxi** [comment]
😭
