### ISSUE TITLE
[Help] I need help setting the automatic mode

### ISSUE THREAD

**Issue by MakuSensei** [LmeSzinc/AzurLaneAutoScript#629]
Hi, I have set the "fleet1_all_fleet2_standby" setting to clean the entire node, but it doesn't. the moment the boss appears, he will directly eliminate him.
I am trying to get the application to help me complete the current event as I am struggling with time.
I have managed to help me with the daily missions and other functions and I appreciate that.
I just come to mention that fleet1_all_fleet2_standby does not serve its purpose of cleaning everything before fighting the boss
Or maybe I don't know what else to configure to do it
![image](https://user-images.githubusercontent.com/16900914/134603948-98500c2e-ab5c-4d92-b4e3-8b57fe79bf7f.png)
![image](https://user-images.githubusercontent.com/16900914/134603987-d828e6a2-f97a-4482-a7ea-1497f619ad88.png)
![image](https://user-images.githubusercontent.com/16900914/134604061-e454be1f-a154-43b5-9cfc-87817558c41e.png)
Excuse me if you don't understand what I mean, I speak Spanish, and I'm using the google translator

**Comment by LmeSzinc** [comment]
Auto search setting is for auto search only. Set `enable_auto_search` to `yes` if you want to use `fleet1_all_fleet2_standby`.

**Comment by MakuSensei** [comment]
Thanks
