### ISSUE TITLE
[TW] 蝶海梦花活动图无法进入

### ISSUE THREAD

**Issue by yhtojy** [LmeSzinc/AzurLaneAutoScript#630]
**Describe the bug**
使用活动图功能，到达地图后，侦测完文字之后，不会点击区域进入

**To Reproduce**
启动活动图功能，选择任一关，例如HT2，不馆该区域是否CLEARED都无法。
跳到该地图页面之后就会跳出错误

**Screenshots**
![2021-09-24_21-36-17-569203](https://user-images.githubusercontent.com/3877705/134690945-8bf82159-d35d-4eaa-b5aa-914307a4bf76.png)

**Log**

> 2021-09-24 21:36:11.946 | INFO | +---------------------------------------------+
> 2021-09-24 21:36:11.946 | INFO | |                    START                    |
> 2021-09-24 21:36:11.946 | INFO | +---------------------------------------------+
> 2021-09-24 21:36:11.948 | INFO | [Server] tw
> 2021-09-24 21:36:14.492 | INFO | [Command] Event
> 2021-09-24 21:36:14.492 | INFO | <<< DEVICE >>>
> 2021-09-24 21:36:14.493 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
> 2021-09-24 21:36:14.761 | INFO | already connected to 127.0.0.1:62025
> 2021-09-24 21:36:17.104 | INFO | [Emotion fleet_1] 150
> 2021-09-24 21:36:17.104 | INFO | [Emotion fleet_2] 150
> 2021-09-24 21:36:17.105 | INFO | [Emotion_bug] 0/65
> 2021-09-24 21:36:17.106 | INFO | ==================== HT2 ====================
> 2021-09-24 21:36:17.106 | INFO | Count: [0]
> 2021-09-24 21:36:17.570 | INFO | [Screen_size] 1280x720
> 2021-09-24 21:36:17.582 | INFO | <<< UI ENSURE >>>
> 2021-09-24 21:36:18.042 | INFO | [UI] page_event
> 2021-09-24 21:36:18.043 | INFO | Already at page_event
> 2021-09-24 21:36:18.726 | INFO | [Campaign_ball] red
> 2021-09-24 21:36:18.748 | INFO | [Mode_switch_2] ex
> 2021-09-24 21:36:18.758 | INFO | [Mode_switch_1] normal
> 2021-09-24 21:36:18.758 | INFO | <<< UI ENSURE INDEX >>>
> 2021-09-24 21:36:18.874 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
> 2021-09-24 21:36:18.930 | INFO | [campaign 0.070s] HT2
> 2021-09-24 21:36:18.930 | INFO | [Chapter] ht
> 2021-09-24 21:36:18.930 | INFO | [Stage] ht2
> 2021-09-24 21:36:18.930 | INFO | [Index] 1
> 2021-09-24 21:36:18.935 | INFO | -------------------- HT2 --------------------
> 2021-09-24 21:36:18.935 | INFO | <<< ENTER MAP >>>
> 2021-09-24 21:36:19.397 | ERROR | operands could not be broadcast together with shapes (3,) (0,) 
> Traceback (most recent call last):
>   File "C:\fakepath\AzurLaneAutoScriptTW\alas.py", line 28, in run
>     self.__getattribute__(command.lower())()
>   File "C:\fakepath\AzurLaneAutoScriptTW\alas.py", line 159, in event
>     az.run(self.config.EVENT_STAGE, folder=self.config.EVENT_NAME)
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\campaign\run.py", line 226, in run
>     self.campaign.run()
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\campaign\campaign_base.py", line 129, in run
>     self.enter_map(self.ENTRANCE, mode=self.config.CAMPAIGN_MODE)
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\map\map_operation.py", line 116, in enter_map
>     if campaign_timer.reached() and self.appear_then_click(button):
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\base\base.py", line 70, in appear_then_click
>     appear = self.appear(button, offset=offset, interval=interval)
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\base\base.py", line 62, in appear
>     threshold=self.config.COLOR_SIMILAR_THRESHOLD if threshold is None else threshold)
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\base\button.py", line 80, in appear_on
>     threshold=threshold
>   File "C:\fakepath\AzurLaneAutoScriptTW\module\base\utils.py", line 344, in color_similar
>     diff = np.array(color1).astype(int) - np.array(color2).astype(int)
> ValueError: operands could not be broadcast together with shapes (3,) (0,) 
> 2021-09-24 21:36:19.399 | INFO | Saving error: ./log/error/1632490579399

这个是需要修正assets吗?

**Comment by LmeSzinc** [comment]
已修复
