### ISSUE TITLE
关于新版的几个建议

### ISSUE THREAD

**Issue by dspjm** [LmeSzinc/AzurLaneAutoScript#643]
总体来说新的界面比旧的要好，但是似乎旧的暂时功能更完善一些。
1. 建议保留之前的一键选择每日的选项，否则每次手动收菜都会进每日耗时较长，一个一个点又太麻烦了。
2. 建议保留之前的收菜间隔可调功能。
3. 建议保留之前的收菜间隔期间app关闭的功能。
~~4. 开始任务以后似乎无法停止。而且如果app没有打开的话如果打开失败，重新开始后不会自动打开app。~~
5. 商店购买的过滤器中的内容完全删除后无法保存。
6. 建议保留作战档案密钥领取功能。虽然旧版这个功能似乎也有bug。
7. 强烈建议增加1200油委托自动选择常用角色的功能。
8. 通用设置中的重启功能暂时没有搞清楚是什么意思。

~~关于问题4：~~
07:51:16.286 | INFO | [SERVER] cn
07:51:16.288 | WARNING | Starting from current page is not supported
07:51:16.290 | WARNING | Supported page: ['page_unknown', 'page_main', 'page_fleet', 'page_guild', 'page_mission', 'page_event_list', 'page_campaign_menu', 'page_campaign', 'page_exercise', 'page_daily', 'page_event', 'page_sp', 'page_raid', 'page_archives', 'page_reward', 'page_commission', 'page_tactical', 'page_reshmenu', 'page_research', 'page_shipyard', 'page_dormmenu', 'page_dorm', 'page_meowfficer', 'page_academy', 'page_shop', 'page_munitions', 'page_build', 'page_os']
07:51:16.292 | WARNING | Supported page: Any page with a "HOME" button on the upper-right
07:51:16.389 | INFO | [Package_name] com.bilibili.azurlane
07:51:16.390 | CRITICAL | Please switch to a supported page before starting Alas
07:51:16.390 | CRITICAL | Request human takeover
08:02:54.850 | INFO | Bind task Research
08:02:54.850 | INFO | [Task] Research
08:02:54.854 | INFO | Scheduler: Start task `Research`
08:02:54.848 | INFO | Pending tasks: ['Research', 'Commission', 'Tactical', 'Dorm', 'Meowfficer', 'Guild', 'Reward', 'Gacha']
08:02:57.796 | INFO | <<< DEVICE >>>
08:02:57.797 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
08:02:57.961 | INFO | already connected to 127.0.0.1:5555
08:02:59.690 | INFO | [Screen_size] 1280x720
08:02:59.697 | INFO | +------------------------------------------------+
08:02:59.697 | INFO | |                    RESEARCH                    |
08:02:59.698 | INFO | +------------------------------------------------+
08:03:02.201 | INFO | <<< UI ENSURE >>>
08:03:02.558 | INFO | Unknown ui page

这个过程当中app启动失败，然后点了多次停止，开始后依然会接着上一次的执行进度。我的理解可能是都是单独的pending tasks，只是继续执行pending tasks。这样的设置是否会保存呢？

**Comment by LmeSzinc** [comment]
> 是不是可以增加一个唤醒最小间隔的选项，每次收菜之后都会有一个唤醒时间计算嘛，这个时候可以设定一个最小时间，比如多少分钟，这样代码改动应该也很小。在加上关闭app就好了。我觉得这个功能对不少的人都是比较有用的。

这个可以
套娃套得有点多了（
