### ISSUE TITLE
3-4 战船选择

### ISSUE THREAD

**Issue by Qinolion** [LmeSzinc/AzurLaneAutoScript#664]
夜神 蓝蝶都出问题
一直点击第一舰队

19:59:09.986 | INFO | Start scheduler loop: alas
19:59:10.000 | INFO | Pending tasks: ['Main']
19:59:10.001 | INFO | [Task] Main
19:59:10.002 | INFO | Bind task Main
19:59:10.002 | INFO | Scheduler: Start task `Main`
19:59:10.898 | INFO | <<< DEVICE >>>
19:59:10.899 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
19:59:11.978 | INFO | cannot connect to 127.0.0.1:5555: 由于目标计算机积极拒绝，无法连接。 (10061)
19:59:11.980 | WARNING | Failed to connect 127.0.0.1:5555 after 3 trial.
19:59:57.230 | INFO | Start scheduler loop: alas
19:59:57.244 | INFO | Pending tasks: ['Main']
19:59:57.244 | INFO | [Task] Main
19:59:57.245 | INFO | Bind task Main
19:59:57.245 | INFO | Scheduler: Start task `Main`
19:59:57.851 | INFO | <<< DEVICE >>>
19:59:57.851 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
19:59:57.941 | INFO | already connected to 127.0.0.1:62001
19:59:58.562 | INFO | [Screen_size] 1280x720
19:59:58.567 | INFO | +--------------------------------------------+
19:59:58.568 | INFO | |                    MAIN                    |
19:59:58.568 | INFO | +--------------------------------------------+
20:00:00.095 | INFO | ==================== CAMPAIGN_3_4 ====================
20:00:00.095 | INFO | Count: 0
20:00:00.565 | INFO | [UI] page_main
20:00:00.566 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
20:00:00.780 | INFO | Click (1086,  394) @ MAIN_GOTO_CAMPAIGN
20:00:00.780 | INFO | <<< MINITOUCH INIT >>>
20:00:01.794 | INFO | Minitouch bind to port 20685
20:00:01.887 | INFO | Minitouch forward port 20685
20:00:01.889 | INFO | minitouch running on port: 20685, pid: 8298
20:00:01.890 | INFO | max_contact: 2; max_x: 1280; max_y: 720; max_pressure: 0
20:00:03.259 | INFO | Click ( 287,  393) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
20:00:04.427 | INFO | [Mode_switch_1] hard
20:00:04.427 | INFO | <<< UI ENSURE INDEX >>>
20:00:04.610 | INFO | No stage found.
20:00:05.050 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
20:00:05.052 | INFO | [Mode_switch_1] hard
20:00:05.052 | INFO | <<< UI ENSURE INDEX >>>
20:00:05.266 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
20:00:05.408 | INFO | [campaign 0.174s] ['4--1', '4--2', '4--3', '4--4']
20:00:05.408 | INFO | [Chapter] 4
20:00:05.409 | INFO | [Stage] 4-1, 4-2, 4-3, 4-4
20:00:05.409 | INFO | [Index] 4
20:00:05.410 | INFO | Click (  53,  374) @ CHAPTER_PREV
20:00:07.176 | INFO | [campaign 0.051s] ['3--3', '3--1', '3--4', '3--2']
20:00:07.177 | INFO | [Chapter] 3
20:00:07.177 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
20:00:07.177 | INFO | [Index] 3
20:00:07.226 | INFO | [OCR_OIL 0.038s] 7502
20:00:07.226 | INFO | -------------------- 3-4 --------------------
20:00:07.226 | INFO | Expect emotion reduce: (8, 0)
20:00:07.239 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=119, Main.Emotion.Fleet1Record=datetime.datetime(2021, 10, 18, 20, 0, 7), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 10, 18, 20, 0, 7)
20:00:07.244 | INFO | [Emotion fleet_1] 119
20:00:07.245 | INFO | [Emotion fleet_2] 119
20:00:07.250 | INFO | <<< ENTER MAP >>>
20:00:07.276 | INFO | Click ( 618,  398) @ 3-4
20:00:08.974 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
20:00:08.974 | INFO | [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 3_stars, threat_safe, clear_mode
20:00:08.975 | INFO | [StopCondition_MapAchievement] non_stop
20:00:08.975 | INFO | [Fast_Forward] on
20:00:08.987 | INFO | [Auto_Search] on
20:00:08.988 | INFO | Click ( 854,  595) @ AUTO_SEARCH_ON
20:00:10.382 | INFO | [Auto_Search] off
20:00:10.382 | INFO | Click ( 887,  510) @ MAP_PREPARATION
20:00:11.190 | INFO | Handling 2x book setting, mode=prep.
20:00:11.206 | INFO | Using fleet: [1, 2, 0]
20:00:11.206 | INFO | [Light_orange_line] 0
20:00:11.207 | INFO | Click (1131,  334) @ FLEET_2_CLEAR
20:00:11.902 | INFO | Click (1030,  211) @ FLEET_1_CHOOSE
20:00:12.623 | INFO | Click (1046,  198) @ FLEET_1_CHOOSE
20:00:13.287 | INFO | Click (1024,  187) @ FLEET_1_CHOOSE
20:00:14.011 | INFO | Click (1025,  195) @ FLEET_1_CHOOSE
20:00:14.701 | INFO | Click (1036,  204) @ FLEET_1_CHOOSE
20:00:15.387 | INFO | Click (1042,  191) @ FLEET_1_CHOOSE
20:00:16.066 | INFO | Click (1023,  183) @ FLEET_1_CHOOSE
20:00:16.682 | INFO | Click (1035,  205) @ FLEET_1_CHOOSE
20:00:17.406 | INFO | Click (1042,  193) @ FLEET_1_CHOOSE
20:00:18.077 | INFO | Click (1029,  197) @ FLEET_1_CHOOSE
20:00:18.752 | INFO | Click (1043,  202) @ FLEET_1_CHOOSE
20:00:19.464 | INFO | Click (1046,  203) @ FLEET_1_CHOOSE
20:00:20.107 | INFO | Click (1038,  201) @ FLEET_1_CHOOSE
20:00:20.783 | INFO | Click (1034,  195) @ FLEET_1_CHOOSE
20:00:21.499 | WARNING | Too many click for a button: FLEET_1_CHOOSE
20:00:21.499 | WARNING | History click: ['FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE']
20:00:21.499 | WARNING | Too many click for a button: FLEET_1_CHOOSE
20:00:21.501 | WARNING | Saving error: ./log/error/1634558421501
20:00:21.600 | WARNING | Game stuck, com.YoStarJP.AzurLane will be restarted in 10 seconds
20:00:21.600 | WARNING | If you are playing by hand, please stop Alas
20:00:21.609 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=119, Main.Emotion.Fleet1Record=datetime.datetime(2021, 10, 18, 20, 0, 7), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 10, 18, 20, 0, 7), Restart.Scheduler.NextRun=datetime.datetime(2021, 10, 18, 20, 0, 21), Restart.Scheduler.Enable=True
Scheduler stopped.
20:00:28.315 | INFO | Start scheduler loop: alas
20:00:28.329 | INFO | Pending tasks: ['Restart', 'Main']
20:00:28.330 | INFO | [Task] Restart
20:00:28.330 | INFO | Bind task Restart
20:00:28.330 | INFO | Skip task `Restart` at scheduler start
20:00:28.331 | INFO | Delay task `Restart` to 2021-10-18 23:00:00 (server_update='00:00')
20:00:28.343 | INFO | Save config ./config\alas.json, Restart.Scheduler.NextRun=datetime.datetime(2021, 10, 18, 23, 0)
20:00:28.360 | INFO | Pending tasks: ['Main']
20:00:28.360 | INFO | [Task] Main
20:00:28.361 | INFO | Bind task Main
20:00:28.361 | INFO | Scheduler: Start task `Main`
20:00:28.934 | INFO | <<< DEVICE >>>
20:00:28.934 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
20:00:29.041 | INFO | already connected to 127.0.0.1:62001
20:00:29.489 | INFO | [Screen_size] 1280x720
20:00:29.495 | INFO | +--------------------------------------------+
20:00:29.495 | INFO | |                    MAIN                    |
20:00:29.496 | INFO | +--------------------------------------------+
20:00:30.460 | INFO | ==================== CAMPAIGN_3_4 ====================
20:00:30.460 | INFO | Count: 0
20:00:31.022 | INFO | Unknown ui page
20:00:31.160 | INFO | Click ( 262,   27) @ MAP_PREPARATION_CANCEL
20:00:31.161 | INFO | <<< MINITOUCH INIT >>>
20:00:32.173 | INFO | Minitouch bind to port 20432
20:00:32.252 | INFO | Minitouch forward port 20432
20:00:32.255 | INFO | minitouch running on port: 20432, pid: 8298
20:00:32.255 | INFO | max_contact: 2; max_x: 1280; max_y: 720; max_pressure: 0
20:00:32.306 | INFO | Goto page_main
20:00:32.306 | INFO | <<< UI GOTO PAGE_MAIN >>>
20:00:34.502 | INFO | Click ( 252,   33) @ MAP_PREPARATION_CANCEL
20:00:34.951 | INFO | Click (1238,   32) @ GOTO_MAIN
20:00:36.431 | WARNING | Unrecognized ui_current, using previous: page_unknown
20:00:36.431 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
20:00:36.435 | INFO | Click (1081,  379) @ MAIN_GOTO_CAMPAIGN
20:00:38.007 | INFO | Click ( 365,  367) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
20:00:38.977 | INFO | [Mode_switch_1] hard
20:00:38.978 | INFO | <<< UI ENSURE INDEX >>>
20:00:39.152 | INFO | No stage found.
20:00:39.544 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
20:00:39.999 | INFO | [Mode_switch_1] hard
20:00:40.000 | INFO | <<< UI ENSURE INDEX >>>
20:00:40.186 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
20:00:40.274 | INFO | [campaign 0.104s] ['3--3', '3--1', '3--4', '3--2']
20:00:40.274 | INFO | [Chapter] 3
20:00:40.275 | INFO | [Stage] 3-3, 3-1, 3-4, 3-2
20:00:40.275 | INFO | [Index] 3
20:00:40.324 | INFO | [OCR_OIL 0.041s] 7502
20:00:40.325 | INFO | -------------------- 3-4 --------------------
20:00:40.325 | INFO | Expect emotion reduce: (8, 0)
20:00:40.345 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=119, Main.Emotion.Fleet1Record=datetime.datetime(2021, 10, 18, 20, 0, 40), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 10, 18, 20, 0, 40)
20:00:40.349 | INFO | [Emotion fleet_1] 119
20:00:40.350 | INFO | [Emotion fleet_2] 119
20:00:40.350 | INFO | <<< ENTER MAP >>>
20:00:40.371 | INFO | Click ( 604,  395) @ 3-4
20:00:42.201 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
20:00:42.201 | INFO | [Map_info] 99%, star_1, star_2, star_3, 100_percent_clear, 3_stars, threat_safe, clear_mode
20:00:42.201 | INFO | [StopCondition_MapAchievement] non_stop
20:00:42.202 | INFO | [Fast_Forward] on
20:00:42.216 | INFO | [Auto_Search] off
20:00:42.216 | INFO | Click ( 930,  506) @ MAP_PREPARATION
20:00:42.928 | INFO | Handling 2x book setting, mode=prep.
20:00:42.938 | INFO | Using fleet: [1, 2, 0]
20:00:42.939 | INFO | [Light_orange_line] 0
20:00:42.940 | INFO | Click (1141,  309) @ FLEET_2_CLEAR
20:00:43.623 | INFO | Click (1045,  204) @ FLEET_1_CHOOSE
20:00:44.276 | INFO | Click (1044,  216) @ FLEET_1_CHOOSE
20:00:44.968 | INFO | Click (1047,  217) @ FLEET_1_CHOOSE
20:00:45.675 | INFO | Click (1036,  206) @ FLEET_1_CHOOSE
20:00:46.402 | INFO | Click (1025,  206) @ FLEET_1_CHOOSE
20:00:47.084 | INFO | Click (1030,  197) @ FLEET_1_CHOOSE
20:00:47.794 | INFO | Click (1046,  200) @ FLEET_1_CHOOSE
20:00:48.511 | INFO | Click (1029,  201) @ FLEET_1_CHOOSE
20:00:49.177 | INFO | Click (1058,  181) @ FLEET_1_CHOOSE
20:00:49.870 | INFO | Click (1015,  184) @ FLEET_1_CHOOSE
20:00:50.540 | INFO | Click (1029,  215) @ FLEET_1_CHOOSE
20:00:51.232 | INFO | Click (1021,  202) @ FLEET_1_CHOOSE
20:00:51.936 | INFO | Click (1036,  207) @ FLEET_1_CHOOSE
20:00:52.664 | INFO | Click (1033,  209) @ FLEET_1_CHOOSE
20:00:53.358 | WARNING | Too many click for a button: FLEET_1_CHOOSE
20:00:53.358 | WARNING | History click: ['FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE', 'FLEET_1_CHOOSE']
20:00:53.358 | WARNING | Too many click for a button: FLEET_1_CHOOSE
20:00:53.359 | WARNING | Saving error: ./log/error/1634558453359
20:00:53.465 | WARNING | Game stuck, com.YoStarJP.AzurLane will be restarted in 10 seconds
20:00:53.465 | WARNING | If you are playing by hand, please stop Alas
20:00:53.476 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=119, Main.Emotion.Fleet1Record=datetime.datetime(2021, 10, 18, 20, 0, 40), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 10, 18, 20, 0, 40), Restart.Scheduler.NextRun=datetime.datetime(2021, 10, 18, 20, 0, 53), Restart.Scheduler.Enable=True
20:01:03.480 | INFO | Scheduler: End task `Main`
20:01:03.493 | INFO | Pending tasks: ['Restart', 'Main']
20:01:03.494 | INFO | [Task] Restart
20:01:03.494 | INFO | Bind task Restart
20:01:03.494 | INFO | Scheduler: Start task `Restart`

**Comment by Qinolion** [comment]
[1634566697274.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7365720/1634566697274.zip)

**Comment by railzy** [comment]
确实UI位置发生了变化，已更新，可以试试现在能不能正常运行
