### ISSUE TITLE
收获点击过快

### ISSUE THREAD

**Issue by ShiroRan** [LmeSzinc/AzurLaneAutoScript#689]
新版的alas在执行收获任务的时候点太快了，现在每次任务执行只成功收获到了石油
可不可以改回原来的收获判断方式

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/12cc90536a8536ef0bf08507cca59afcc2330108/module/reward/reward.py#L13-L55

**Comment by LmeSzinc** [comment]
> 调收获间隔也没了

#643 ，第二点
