### ISSUE TITLE
Ctrl+R快捷键冲突

### ISSUE THREAD

**Issue by scythk** [LmeSzinc/AzurLaneAutoScript#698]
运行程序后 windows中其它应用的Ctrl+R快捷键无法使用, 不管程序是不是在前台都会重新加载.
在控制台中没有找到取消全局快捷键的设置, 也无法修改快捷键.
目前只发现Ctrl+R这一个快捷键存在问题.

**Comment by LmeSzinc** [comment]
e9e7e338fbcbf28fd91af6e027d732f1ab6dac3e

**Comment by scythk** [comment]
> [e9e7e33](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/e9e7e338fbcbf28fd91af6e027d732f1ab6dac3e)

测试后发现该bug依然存在, 在窗口失焦的情况下依然会响应ctrl+r和ctrl+shift+I快捷键.
已检查过index.ts确认是更新过的文件

**Comment by LmeSzinc** [comment]
打包的客户端还不能自动更新，你需要在 [Releases](https://github.com/LmeSzinc/AzurLaneAutoScript/releases) 处获取更新后的客户端
