### ISSUE TITLE
活动图每日重复出击

### ISSUE THREAD

**Issue by zekyou** [LmeSzinc/AzurLaneAutoScript#702]
**Describe the bug**
本来程序应按照d1-d2-d3顺序打下去，如果在打完d1后队列中插入其他时间（比如，插入收获等）。收获结束后应该继续打d2,脚本却没有记录到已经打过d1，选择继续重复出击d1，造成一直重复。推测是更新出击记录的时间与调度、刷新的顺序出错。
**To Reproduce**

**Expected behavior**

**Screenshots**
出击d1
![image](https://user-images.githubusercontent.com/45705837/139517904-b5b10dcc-d329-48f8-a2db-22a8cd4accb7.png)
完成d1
![image](https://user-images.githubusercontent.com/45705837/139517914-0714c73b-28ef-472b-ad9a-88761f764af2.png)
插入其他事件（宿舍）
![image](https://user-images.githubusercontent.com/45705837/139517929-5b0bcb57-edb2-463c-859d-c01c0b46ea87.png)
结束后却继续出击d1而非d2
![image](https://user-images.githubusercontent.com/45705837/139517951-27fb1c4c-97b6-4be9-b8bc-6e5aae40e9eb.png)

**Log**
Post the entire log snippet that caused you to receive the error

**Comment by LmeSzinc** [comment]
更新你的 Alas
c5bbbbe3ffea319791dd12fae66ed81df0d29445
