### ISSUE TITLE
[战术学院] 请求添加等级识别，避免浪费高级技能书

### ISSUE THREAD

**Issue by SF-monkey** [LmeSzinc/AzurLaneAutoScript#703]
**Is your feature request related to a problem? Please describe.**
如题。目前的逻辑是默认用最高级的技能书，然后是低级和其他的。但是技能快升满时用高级技能书相当浪费。
手动解决的话，目前可以在filter设置不用T4T3的书，只用T2T1，但是影响会效率。

**Describe the solution you'd like**
添加一个等级/经验值识别，快满级就用T2T1的书，减少浪费。

**Comment by LmeSzinc** [comment]
调用现有方法，对经验值做 OCR 即可实现，不会太难。

![Screenshot](https://user-images.githubusercontent.com/37934724/140533719-66560174-9aa3-4f1f-bd95-3d65c663661e.png)

对经验值的位置创建 Button，使用 `DigitCounter` 类进行 OCR。DigitCounter 类可以识别 `14/15` 格式的内容，获取当前值、剩余值、总值。总值为 5800 的即为 10 级技能。
由于默认的 OCR 预处理是针对特定颜色文字的，而此处的文字有两种颜色。可覆写 `pre_process()` 方法，输出 MAX(RGB)。

最后，在 `_tactical_books_choose` 中删除特定等级的书即可：`books = self.books.delete(self.books.select(tier=4))`

**Comment by julystone** [comment]
#742 #
