### ISSUE TITLE
图片识别，运行一段时间后无法工作

### ISSUE THREAD

**Issue by cyx3212** [LmeSzinc/AzurLaneAutoScript#706]
log：
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7446363/log.txt)

shot:
![2021-10-30_19-09-40-492145](https://user-images.githubusercontent.com/41174411/139530758-71355911-5631-4d8d-9c22-7dea0ce97f34.png)

**Comment by cyx3212** [comment]
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7446371/log.txt
![2021-10-30_08-02-16-858200](https://user-images.githubusercontent.com/41174411/139530808-63d2354c-ed05-4c4e-b717-36fe39b567b2.png)
)

**Comment by cyx3212** [comment]
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7446372/log.txt
![2021-10-30_07-56-33-708931](https://user-images.githubusercontent.com/41174411/139530835-fc909043-8021-4f7d-acdc-18b1932920e5.png)
)

**Comment by LmeSzinc** [comment]
模拟器问题。模拟器连接不稳定导致图片损坏，建议换模拟器。

**Comment by LmeSzinc** [comment]
有张图片露名字了，我删掉了
