### ISSUE TITLE
主线图心情值初始化错误

### ISSUE THREAD

**Issue by clarkgap** [LmeSzinc/AzurLaneAutoScript#708]
**Describe the bug**
我将主线BOSS舰队初始心情值设为150，BOSS队心情控制设为保持经验加成。但启动后alas自动将BOSS队心情值更新为119：“Main.Emotion.Fleet2Value=119”。

**Screenshots**
![屏幕截图(373)](https://user-images.githubusercontent.com/78226031/139555749-3f092abf-fcba-4272-ad61-2f03981d1dfd.png)

**Log**
12:10:58.953 | INFO | Start scheduler loop: alas
12:10:58.954 | INFO | [Server] cn
12:10:58.964 | INFO | Pending tasks: ['Main']
12:10:58.964 | INFO | [Task] Main
12:10:58.964 | INFO | Bind task Main
12:10:58.965 | INFO | Scheduler: Start task `Main`
12:10:59.259 | INFO | <<< DEVICE >>>
12:10:59.259 | INFO | [Adb_binary] .\toolkit\Lib\site-packages\adbutils\binaries\adb.exe
12:10:59.286 | INFO | already connected to 127.0.0.1:5555
12:10:59.723 | INFO | [Screen_size] 1280x720
12:10:59.726 | INFO | +--------------------------------------------+
12:10:59.727 | INFO | |                    MAIN                    |
12:10:59.727 | INFO | +--------------------------------------------+
12:11:00.484 | INFO | ==================== CAMPAIGN_13_4 ====================
12:11:00.485 | INFO | Count remain: 15
12:11:00.822 | INFO | [UI] page_main
12:11:00.822 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
12:11:00.840 | INFO | Click (1091,  325) @ MAIN_GOTO_CAMPAIGN
12:11:00.841 | INFO | <<< MINITOUCH INIT >>>
12:11:02.842 | INFO | Minitouch bind to port 20608
12:11:02.882 | INFO | Minitouch forward port 20608
12:11:02.885 | INFO | minitouch running on port: 20608, pid: 23116
12:11:02.885 | INFO | max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
12:11:03.839 | INFO | Click ( 281,  303) @ CAMPAIGN_MENU_GOTO_CAMPAIGN
12:11:04.562 | INFO | [Mode_switch_1] hard
12:11:04.562 | INFO | <<< UI ENSURE INDEX >>>
12:11:04.683 | INFO | No stage found.
12:11:04.909 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
12:11:04.911 | INFO | [Mode_switch_1] hard
12:11:04.912 | INFO | <<< UI ENSURE INDEX >>>
12:11:05.034 | INFO | No stage found.
12:11:05.279 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
12:11:05.560 | INFO | [Mode_switch_1] hard
12:11:05.561 | INFO | <<< UI ENSURE INDEX >>>
12:11:05.694 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
12:11:05.751 | INFO | [campaign 0.068s] ['13--1', '13--3', '13--2', '13--4']
12:11:05.751 | INFO | [Chapter] 13
12:11:05.752 | INFO | [Stage] 13-1, 13-3, 13-2, 13-4
12:11:05.752 | INFO | [Index] 13
12:11:05.775 | INFO | [OCR_OIL 0.020s] 14350
12:11:05.775 | INFO | -------------------- 13-4 --------------------
12:11:05.776 | INFO | Expect emotion reduce: (14, 2)
12:11:05.783 | INFO | Save config ./config\alas.json, Main.Emotion.Fleet1Value=150, Main.Emotion.Fleet1Record=datetime.datetime(2021, 10, 30, 12, 11, 5), Main.Emotion.Fleet2Value=119, Main.Emotion.Fleet2Record=datetime.datetime(2021, 10, 30, 12, 11, 5)
12:11:05.785 | INFO | [Emotion fleet_1] 150
12:11:05.786 | INFO | [Emotion fleet_2] 119
12:11:05.786 | INFO | Delay current task to prevent emotion control in the future
12:11:05.786 | INFO | Delay task `Main` to 2021-10-30 12:18:00 (target=datetime.datetime(2021, 10, 30, 12, 18))
12:11:05.793 | INFO | Save config ./config\alas.json, Main.Scheduler.NextRun=datetime.datetime(2021, 10, 30, 12, 18)
12:11:05.796 | INFO | <<< SCRIPT END >>>
12:11:05.796 | INFO | Emotion control
12:11:05.798 | INFO | Scheduler: End task `Main`
12:11:05.799 | INFO | [Server] cn
12:11:05.808 | INFO | No task pending
12:11:05.809 | INFO | Wait until 2021-10-30 12:19:00 for task `Main`

**Comment by LmeSzinc** [comment]
不认为这是有问题的。

未放置于后宅的时候，心情最多回复到 119。
虽然心情值的确可以高于 119，但是正常人都是把要出击的船放置到后宅，不会在出击前养到 150，出击时又故意移出后宅。因此认为心情值最大为 119。
