### ISSUE TITLE
Support for BlueStacks5 hyper-v version?

### ISSUE THREAD

**Issue by gItSpLasHeR** [LmeSzinc/AzurLaneAutoScript#718]
As BlueStacks 5.3.100 released, they added support for hyper-v in N64 version,
check the link
https://support.bluestacks.com/hc/en-us/articles/4407823168525

> BlueStacks 5.3.100
>1. You will now be able to play your favorite Android games on BlueStacks 5.3.100 Nougat 64-bit even when Hyper-V is enabled on your PC

since this is BlueStacks5,  the real time adb host  _bluestacks4-hyperv_  never worked again,
Is there any notes for Bluestacks5 hyper-v?

**Comment by junbluedd** [comment]
My Bluestacks5 Hyper-V has to manually enter the port on the settings page to get it to work, and the port changes every time I reboot

**Comment by LmeSzinc** [comment]
The serial of BS4 is read from `SOFTWARE\BlueStacks_bgp64_hyperv\Guests\Android\Config`.
Try to find the serial of BS5, then make a PR.
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/212e4d0193bf59b6f1b35ef590131d2785703c9d/module/device/connection.py#L37-L68

**Comment by gItSpLasHeR** [comment]
Current path in registry supposed to be "HKEY_LOCAL_MACHINE\SOFTWARE\BlueStacks_nxt".
However there is no port item any more.

Manually check port in settings is a workaround.

**Comment by LmeSzinc** [comment]
#725 , but code quality is not up to the requirements.

**Comment by LmeSzinc** [comment]
#733
