### ISSUE TITLE
作战档案，凛冬王冠概率找不到

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#727]
复现了两次，alas一直在下滑寻找凛冬王冠，但是其实是在最上方

22:08:11.799 | INFO | Research detail quit
22:08:11.823 | INFO | Click ( 753,  671) @ RESEARCH_DETAIL_QUIT
22:08:15.557 | INFO | Delay task `Research` to 2021-11-04 00:38:15 (minute=150.0)
22:08:15.571 | INFO | Save config ./config\alas.json, Research.Scheduler.NextRun=datetime.datetime(2021, 11, 4, 0, 38, 15)
22:08:15.577 | INFO | Scheduler: End task `Research`
22:08:15.578 | INFO | [Server] cn
22:08:15.597 | INFO | Pending tasks: ['WarArchives']
22:08:15.597 | INFO | [Task] WarArchives
22:08:15.598 | INFO | Bind task WarArchives
22:08:15.598 | INFO | Scheduler: Start task `WarArchives`
22:08:16.544 | INFO | +---------------------------------------------------+
22:08:16.544 | INFO | |                    WARARCHIVES                    |
22:08:16.544 | INFO | +---------------------------------------------------+
22:08:16.546 | INFO | ==================== B1 ====================
22:08:16.546 | INFO | Count: 0
22:08:17.471 | INFO | [UI] page_research
22:08:17.471 | INFO | <<< UI ENSURE >>>
22:08:17.483 | INFO | [UI] page_research
22:08:17.483 | INFO | Goto page_archives
22:08:17.484 | INFO | <<< UI GOTO PAGE_ARCHIVES >>>
22:08:17.491 | INFO | Click (1233,   34) @ GOTO_MAIN
22:08:19.661 | INFO | Click (1118,  396) @ MAIN_GOTO_CAMPAIGN
22:08:22.234 | INFO | Click ( 279,  622) @ CAMPAIGN_MENU_GOTO_WAR_ARCHIVES
22:08:22.731 | INFO | [War_Archives_switch] ex
22:08:22.827 | INFO | Drag ( 667,  578) -> ( 631,  305)
22:08:24.513 | INFO | Drag ( 611,  505) -> ( 643,  218)
22:08:26.132 | INFO | Drag ( 656,  489) -> ( 667,  233)
22:08:27.768 | INFO | Drag ( 636,  483) -> ( 629,  211)
22:08:29.463 | INFO | Drag ( 629,  580) -> ( 654,  261)
22:08:31.103 | INFO | Drag ( 651,  484) -> ( 641,  200)
22:08:32.748 | INFO | Drag ( 666,  510) -> ( 671,  259)
22:08:34.374 | INFO | Drag ( 621,  555) -> ( 621,  313)
22:08:36.036 | INFO | Drag ( 627,  517) -> ( 629,  225)
22:08:37.682 | INFO | Drag ( 656,  529) -> ( 632,  245)
22:08:38.606 | WARNING | Failed to find archives entrance
22:08:38.606 | CRITICAL | Respective server may not yet support the chosen War Archives campaign, check back in the next app update
22:08:38.606 | CRITICAL | Request human takeover
![MuMu20211103223437](https://user-images.githubusercontent.com/49509508/140080695-2842a212-57c6-4454-9fe6-e7d597a155b9.png)

**Comment by LmeSzinc** [comment]
经私下讨论，认为是作战档案界面的活动卡片未加载完全导致的。
可以在 _search_archives_entrance() 开头部分加上 等待任意活动卡片出现 的逻辑。

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/8d63d534c852d5c417b36a8619048152aa9e674d/campaign/campaign_war_archives/campaign_base.py#L37-L69

**Comment by LmeSzinc** [comment]
#739
