### ISSUE TITLE
期望区分开领取任务奖励的，weekly奖励与daily奖励

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#728]
weekly奖励存在大量石油，而每周一领取的话，不太方便使用。（一般刷油都在周末）
而daily奖励却期望当日就领掉。

但是当前两个奖励用的是一个UI勾选栏
![image](https://user-images.githubusercontent.com/49509508/140081155-6ab2c004-b019-4269-8300-c226c26078af.png)

群主接受优化的话，我明天增加个选项？

**Comment by LmeSzinc** [comment]
你想加可以加。

我是觉得无所谓，反正都是挂脚本，周中周末都一样。

**Comment by LmeSzinc** [comment]
#740
