### ISSUE TITLE
[重启] 新版游戏客户端UI改动，重启时用户协议无法跳过

### ISSUE THREAD

**Issue by SF-monkey** [LmeSzinc/AzurLaneAutoScript#730]
**Describe the bug**
如题。问题应该是脚本无法正确识别新版UI。因为我试过旧版客户端可以正常识别。

**Expected behavior**
游戏现在支持热更，不是最新客户端也能玩，可能要兼容下新版UI？

**Screenshots**
![](https://imgur.com/FqmTJWi.png)

**Log**
22:56:11.191 | INFO | Scheduler: Start task `Restart`
22:56:11.407 | INFO | +-----------------------------------------------+
22:56:11.407 | INFO | |                    RESTART                    |
22:56:11.407 | INFO | +-----------------------------------------------+
22:56:11.430 | INFO | <<< APP RESTART >>>
22:56:11.430 | INFO | App stop: com.bilibili.azurlane
22:56:11.564 | INFO | App start: com.bilibili.azurlane
22:56:11.891 | INFO | <<< APP LOGIN >>>
22:56:14.445 | INFO | Click (1023,  656) @ GET_SHIP
22:56:14.445 | INFO | <<< MINITOUCH INIT >>>
22:56:16.447 | INFO | Minitouch bind to port 20283
22:56:16.471 | INFO | Minitouch forward port 20283
22:56:16.473 | INFO | minitouch running on port: 20283, pid: 20449
22:56:16.473 | INFO | max_contact: 2; max_x: 32767; max_y: 32767; max_pressure: 0
22:56:16.644 | INFO | Click (1022,  663) @ GET_SHIP
22:56:16.812 | INFO | Click (1039,  655) @ GET_SHIP
22:56:16.982 | INFO | Click (1018,  678) @ GET_SHIP
22:56:17.154 | INFO | Click (1028,  659) @ GET_SHIP
22:56:17.322 | INFO | Click (1026,  650) @ GET_SHIP
22:56:17.489 | INFO | Click (1023,  679) @ GET_SHIP
22:56:17.677 | INFO | Click (1022,  646) @ GET_SHIP
22:56:17.860 | INFO | Click (1042,  660) @ GET_SHIP
22:56:18.031 | INFO | Click (1028,  657) @ GET_SHIP
22:56:18.208 | INFO | Click (1028,  667) @ GET_SHIP
22:56:18.378 | WARNING | Too many click for a button: GET_SHIP
22:56:18.378 | WARNING | History click: ['GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP']
22:56:18.379 | WARNING | Too many click for a button: GET_SHIP
22:56:18.379 | INFO | App stop: com.bilibili.azurlane
22:56:18.652 | INFO | App start: com.bilibili.azurlane
22:56:18.975 | INFO | <<< APP LOGIN >>>
22:56:21.441 | INFO | Click (1034,  652) @ GET_SHIP
22:56:21.600 | INFO | Click (1018,  646) @ GET_SHIP
22:56:21.761 | INFO | Click (1028,  653) @ GET_SHIP
22:56:21.924 | INFO | Click (1034,  650) @ GET_SHIP
22:56:22.083 | INFO | Click (1024,  662) @ GET_SHIP
22:56:22.244 | INFO | Click (1037,  660) @ GET_SHIP
22:56:22.402 | INFO | Click (1028,  656) @ GET_SHIP
22:56:22.590 | INFO | Click (1022,  655) @ GET_SHIP
22:56:22.756 | INFO | Click (1022,  646) @ GET_SHIP
22:56:22.919 | INFO | Click (1033,  665) @ GET_SHIP
22:56:23.083 | INFO | Click (1012,  676) @ GET_SHIP
22:56:23.248 | WARNING | Too many click for a button: GET_SHIP
22:56:23.248 | WARNING | History click: ['GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP']
22:56:23.248 | WARNING | Too many click for a button: GET_SHIP
22:56:23.249 | INFO | App stop: com.bilibili.azurlane
22:56:23.519 | INFO | App start: com.bilibili.azurlane
22:56:23.830 | INFO | <<< APP LOGIN >>>
22:56:26.232 | INFO | Click (1017,  677) @ GET_SHIP
22:56:26.405 | INFO | Click (1010,  651) @ GET_SHIP
22:56:26.570 | INFO | Click (1029,  663) @ GET_SHIP
22:56:26.745 | INFO | Click (1018,  661) @ GET_SHIP
22:56:26.913 | INFO | Click (1028,  643) @ GET_SHIP
22:56:27.087 | INFO | Click (1009,  667) @ GET_SHIP
22:56:27.257 | INFO | Click (1016,  665) @ GET_SHIP
22:56:27.436 | INFO | Click (1022,  659) @ GET_SHIP
22:56:27.610 | INFO | Click (1016,  668) @ GET_SHIP
22:56:27.785 | INFO | Click (1024,  658) @ GET_SHIP
22:56:27.960 | INFO | Click (1049,  644) @ GET_SHIP
22:56:28.143 | WARNING | Too many click for a button: GET_SHIP
22:56:28.144 | WARNING | History click: ['GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP', 'GET_SHIP']
22:56:28.144 | WARNING | Too many click for a button: GET_SHIP
22:56:28.144 | INFO | App stop: com.bilibili.azurlane
22:56:28.402 | INFO | App start: com.bilibili.azurlane
22:56:28.723 | CRITICAL | Login failed more than 3
22:56:28.723 | CRITICAL | Azur Lane server may be under maintenance, or you may lost network connection
22:56:28.723 | CRITICAL | Request human takeover

**Comment by LmeSzinc** [comment]
B站的用户协议界面改动过多次，样式不一。建议是学习 ~~照抄~~ 隔壁 PCR 脚本，使用 uiautomator2 获取 UI 控件，而不是使用图像识别。

https://github.com/SimonShi1994/Princess-connection-farm/blob/8bd58f9768f7eac3612ca800ccefb9f071a7d7a3/automator_mixins/_login.py#L121-L138

滚动条的位置不能使用硬编码坐标，要使用 `color_similarity_2d()` 寻找浅灰色块，往下拉。
这是B服的专属问题，所以不需要考虑多服务器适配的事情。

**Comment by MrGuoRanDuo** [comment]
这周内PR修复。
