### ISSUE TITLE
在已完成自律寻敌的情况下使用大世界每日会一直点击自律寻敌

### ISSUE THREAD

**Issue by Horizon101011** [LmeSzinc/AzurLaneAutoScript#731]
**Describe the bug**
如题，进入大世界时如果舰队处于一个无自律事件的海域，会出现一直点击自律寻敌不动的情况

**Expected behavior**
旧版时，点击自律在无事件时会自动打开情报处确认每日任务或退出到地图接新任务

**Log**
02:03:40.017 | INFO | +-------------------------------------------------+
02:03:40.018 | INFO | |                    OPSIDAILY                    |
02:03:40.018 | INFO | +-------------------------------------------------+
02:03:41.221 | INFO | ==================== OS INIT ====================
02:03:41.397 | INFO | Already in os map
02:03:41.415 | INFO | Loading OCR model: ./bin/cnocr_models/cnocr
02:03:41.533 | INFO | [MAP_NAME 0.133s] 东南洋脊C
02:03:41.534 | INFO | Map name processed: 东南洋脊C
02:03:41.537 | INFO | [Zone] [53|东南洋脊C|Southeast Ocean Ridge C|南東海嶺C]
02:03:41.743 | INFO | [HP]  90%  90%  90%  95%  87%  90%
02:03:41.748 | INFO | [Repair icon] [False, False, False, False, False, False]
02:03:41.748 | INFO | [HP]  90%  90%  90%  95%  87%  90%
02:03:41.749 | INFO | No ship found to be below threshold 40%, continue OS exploration
02:03:41.763 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
02:03:41.854 | INFO | [ASH_COLLECT_STATUS 0.104s] 70/100
02:03:41.855 | INFO | -------------------- OS AUTO SEARCH --------------------
02:03:42.072 | INFO | Click (1226,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:03:50.971 | INFO | Click (1242,  578) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:03:54.047 | INFO | Click (1245,  580) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:03:57.104 | INFO | Click (1259,  581) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:04:00.143 | INFO | Click (1235,  581) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:04:03.227 | INFO | Click (1235,  580) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:04:06.395 | INFO | Click (1237,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
02:04:09.561 | INFO | Click (1223,  582) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
Scheduler stopped.

**Comment by LmeSzinc** [comment]
需要截图
