### ISSUE TITLE
偶然的情况下梯队在大世界陷入死循环

### ISSUE THREAD

**Issue by Horizon101011** [LmeSzinc/AzurLaneAutoScript#732]
**Describe the bug**
使用大世界每日时，在直布罗特港口，梯队试图前往港口接每日任务时出现绕圈死循环
被选中的梯队初始位于E2，但根据日志似乎被显示为了E1
在到达E3后，被选中的队伍应移动到C5，但根据日志被显示为位于E2，并移动到了D5
随后就开始观测到梯队在 E3，F1，E3，D5 这几个位置依次循环移动
简单查阅日志能发现梯队实际位置和识别位置并不一致（如移动C5实际点击了D5等

**Screenshots**
![MuMu20211105022521](https://user-images.githubusercontent.com/43370844/140397999-96d50365-1a24-4acc-957e-ad8afb14bb63.png)

**Log**
02:09:02.205 | INFO | [Globe_pinned] [2|直布罗特|Gibraltar|ジブラルタル]
02:09:02.206 | INFO | Zone has no type to select, skip
02:09:02.210 | INFO | Click ( 480,  298) @ ZONE_ENTRANCE
02:09:04.576 | INFO | [MAP_NAME 0.065s] 直布罗特
02:09:04.577 | INFO | Map name processed: 直布罗特
02:09:04.577 | INFO | [Zone] [2|直布罗特|Gibraltar|ジブラルタル]
02:09:04.584 | INFO | [HP]  92%  92%  90%  95%  87%  89%
02:09:04.591 | INFO | [Repair icon] [False, False, False, False, False, False]
02:09:04.592 | INFO | [HP]  92%  92%  90%  95%  87%  89%
02:09:04.592 | INFO | No ship found to be below threshold 40%, continue OS exploration
02:09:04.698 | INFO | Port route at [0 2]
02:09:04.803 | INFO |            tile_center: 0.864 (9 matches)
02:09:04.822 | INFO | 0.117s  _   edge_lines: 5 hori, 1 vert
02:09:04.822 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:04.825 | INFO |           grids_offset: (1, 0)
02:09:04.826 | INFO |            center_loca: (4, 0)
02:09:04.982 | INFO | 0.155s         predict: 35
02:09:04.983 | INFO | -- -- -- -- FL -- -- -- --
02:09:04.983 | INFO | -- -- -- -- -- -- -- -- --
02:09:04.984 | INFO | -- -- -- -- -- -- -- -- --
02:09:04.984 | INFO | .. -- -- -- -- -- -- -- --
02:09:04.984 | INFO | Radar (0, 2) -> Local E3 (fleet=E1)
02:09:04.985 | INFO | Click ( 649,  513) @ E3
02:09:07.363 | INFO | Port route at [-2  2]
02:09:07.462 | INFO |            tile_center: 0.887 (14 matches)
02:09:07.477 | INFO | 0.109s  _   edge_lines: 5 hori, 1 vert
02:09:07.478 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:07.483 | INFO |           grids_offset: (1, 0)
02:09:07.484 | INFO |            center_loca: (4, 1)
02:09:07.672 | INFO | 0.187s         predict: 44
02:09:07.672 | INFO | -- -- -- -- -- -- -- -- --
02:09:07.673 | INFO | -- -- -- -- -- -- -- -- --
02:09:07.673 | INFO | -- -- -- -- FL -- -- -- --
02:09:07.673 | INFO | -- -- -- -- -- -- -- -- --
02:09:07.673 | INFO | .. -- -- -- -- -- -- -- --
02:09:07.674 | INFO | Radar (-2, 2) -> Local C5 (fleet=E2)
02:09:07.674 | INFO | Click ( 409,  597) @ C5
02:09:10.812 | INFO | Port route at [ 1 -2]
02:09:10.895 | INFO |            tile_center: 0.912 (good match)
02:09:10.912 | INFO | 0.094s  _   edge_lines: 7 hori, 1 vert
02:09:10.913 | INFO | Edges: /     homo_loca: ( 53,  59)
02:09:10.920 | INFO |            center_loca: (3, 4)
02:09:11.240 | INFO | 0.320s         predict: 75
02:09:11.240 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:11.241 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:11.242 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:11.242 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:11.242 | INFO | -- -- -- FL -- -- -- -- -- ..
02:09:11.243 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:11.243 | INFO | -- -- -- -- -- FL -- -- -- ..
02:09:11.243 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:11.244 | WARNING | Convert radar to local, but found multiple current fleets: [D5, F7]
02:09:11.244 | WARNING | Assuming the nearest fleet to camera canter is current fleet: D5
02:09:11.244 | INFO | Radar (1, -2) -> Local E3 (fleet=D5)
02:09:11.244 | INFO | Click ( 743,  222) @ E3
02:09:13.927 | INFO | Port route at [ 1 -2]
02:09:14.023 | INFO |            tile_center: 0.899 (19 matches)
02:09:14.040 | INFO | 0.108s  _   edge_lines: 5 hori, 1 vert
02:09:14.040 | INFO | Edges: /     homo_loca: ( 53,  58)
02:09:14.047 | INFO |            center_loca: (4, 2)
02:09:14.307 | INFO | 0.259s         predict: 60
02:09:14.307 | INFO | -- -- -- -- -- -- -- -- -- -- --
02:09:14.308 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:14.308 | INFO | -- -- -- -- FL -- -- -- -- -- ..
02:09:14.309 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:14.309 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:14.309 | INFO | .. -- -- -- -- -- -- -- -- -- ..
02:09:14.310 | INFO | Radar (1, -2) -> Local F1 (fleet=E3)
02:09:14.310 | INFO | Click ( 728,  220) @ F1
02:09:16.873 | INFO | Port route at [0 2]
02:09:16.972 | INFO |            tile_center: 0.864 (9 matches)
02:09:16.989 | INFO | 0.111s  _   edge_lines: 5 hori, 1 vert
02:09:16.989 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:16.993 | INFO |           grids_offset: (1, 0)
02:09:16.994 | INFO |            center_loca: (4, 0)
02:09:17.142 | INFO | 0.148s         predict: 35
02:09:17.143 | INFO | -- -- -- -- FL -- -- -- --
02:09:17.143 | INFO | -- -- -- -- -- -- -- -- --
02:09:17.143 | INFO | -- -- -- -- -- -- -- -- --
02:09:17.144 | INFO | .. -- -- -- -- -- -- -- --
02:09:17.144 | INFO | Radar (0, 2) -> Local E3 (fleet=E1)
02:09:17.145 | INFO | Click ( 633,  508) @ E3
02:09:19.561 | INFO | Port route at [-2  2]
02:09:19.658 | INFO |            tile_center: 0.887 (14 matches)
02:09:19.674 | INFO | 0.108s  _   edge_lines: 5 hori, 1 vert
02:09:19.674 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:19.679 | INFO |           grids_offset: (1, 0)
02:09:19.680 | INFO |            center_loca: (4, 1)
02:09:19.866 | INFO | 0.185s         predict: 44
02:09:19.867 | INFO | -- -- -- -- -- -- -- -- --
02:09:19.867 | INFO | -- -- -- -- -- -- -- -- --
02:09:19.867 | INFO | -- -- -- -- FL -- -- -- --
02:09:19.867 | INFO | -- -- -- -- -- -- -- -- --
02:09:19.868 | INFO | .. -- -- -- -- -- -- -- --
02:09:19.868 | INFO | Radar (-2, 2) -> Local C5 (fleet=E2)
02:09:19.868 | INFO | Click ( 408,  607) @ C5
02:09:23.178 | INFO | Port route at [ 1 -2]
02:09:23.263 | INFO |            tile_center: 0.912 (good match)
02:09:23.280 | INFO | 0.096s  _   edge_lines: 7 hori, 1 vert
02:09:23.280 | INFO | Edges: /     homo_loca: ( 53,  59)
02:09:23.289 | INFO |            center_loca: (3, 4)
02:09:23.604 | INFO | 0.316s         predict: 75
02:09:23.605 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:23.605 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:23.606 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:23.606 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:23.607 | INFO | -- -- -- FL -- -- -- -- -- ..
02:09:23.607 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:23.607 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:23.607 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:23.608 | INFO | Radar (1, -2) -> Local E3 (fleet=D5)
02:09:23.608 | INFO | Click ( 728,  224) @ E3
02:09:26.435 | INFO | Port route at [ 1 -2]
02:09:26.535 | INFO |            tile_center: 0.899 (20 matches)
02:09:26.551 | INFO | 0.111s  _   edge_lines: 5 hori, 1 vert
02:09:26.552 | INFO | Edges: /     homo_loca: ( 53,  58)
02:09:26.559 | INFO |            center_loca: (4, 2)
02:09:26.811 | INFO | 0.250s         predict: 60
02:09:26.812 | INFO | -- -- -- -- -- -- -- -- -- -- --
02:09:26.812 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:26.812 | INFO | -- -- -- -- FL -- -- -- -- -- ..
02:09:26.813 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:26.813 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:26.813 | INFO | .. -- -- -- -- -- -- -- -- -- ..
02:09:26.813 | INFO | Radar (1, -2) -> Local F1 (fleet=E3)
02:09:26.814 | INFO | Click ( 731,  221) @ F1
02:09:29.296 | INFO | Port route at [0 2]
02:09:29.393 | INFO |            tile_center: 0.864 (9 matches)
02:09:29.409 | INFO | 0.109s  _   edge_lines: 5 hori, 1 vert
02:09:29.410 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:29.414 | INFO |           grids_offset: (1, 0)
02:09:29.415 | INFO |            center_loca: (4, 0)
02:09:29.568 | INFO | 0.153s         predict: 35
02:09:29.568 | INFO | -- -- -- -- FL -- -- -- --
02:09:29.569 | INFO | -- -- -- -- -- -- -- -- --
02:09:29.569 | INFO | -- -- -- -- -- -- -- -- --
02:09:29.570 | INFO | .. -- -- -- -- -- -- -- --
02:09:29.570 | INFO | Radar (0, 2) -> Local E3 (fleet=E1)
02:09:29.570 | INFO | Click ( 643,  518) @ E3
02:09:32.151 | INFO | Port route at [-2  2]
02:09:32.247 | INFO |            tile_center: 0.887 (14 matches)
02:09:32.262 | INFO | 0.106s  _   edge_lines: 5 hori, 1 vert
02:09:32.263 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:32.267 | INFO |           grids_offset: (1, 0)
02:09:32.268 | INFO |            center_loca: (4, 1)
02:09:32.453 | INFO | 0.184s         predict: 44
02:09:32.453 | INFO | -- -- -- -- -- -- -- -- --
02:09:32.454 | INFO | -- -- -- -- -- -- -- -- --
02:09:32.454 | INFO | -- -- -- -- FL -- -- -- --
02:09:32.454 | INFO | -- -- -- -- -- -- -- -- --
02:09:32.455 | INFO | .. -- -- -- -- -- -- -- --
02:09:32.455 | INFO | Radar (-2, 2) -> Local C5 (fleet=E2)
02:09:32.455 | INFO | Click ( 390,  599) @ C5
02:09:35.574 | INFO | Port route at [ 1 -2]
02:09:35.654 | INFO |            tile_center: 0.912 (good match)
02:09:35.671 | INFO | 0.093s  _   edge_lines: 6 hori, 1 vert
02:09:35.671 | INFO | Edges: /     homo_loca: ( 53,  59)
02:09:35.677 | INFO |            center_loca: (3, 4)
02:09:36.008 | INFO | 0.329s         predict: 75
02:09:36.008 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:36.008 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:36.008 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:36.009 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:36.009 | INFO | -- -- -- FL -- -- -- -- -- ..
02:09:36.009 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:36.010 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:36.010 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:36.010 | INFO | Radar (1, -2) -> Local E3 (fleet=D5)
02:09:36.011 | INFO | Click ( 737,  224) @ E3
02:09:38.906 | INFO | Port route at [ 1 -2]
02:09:39.003 | INFO |            tile_center: 0.899 (19 matches)
02:09:39.020 | INFO | 0.110s  _   edge_lines: 5 hori, 1 vert
02:09:39.020 | INFO | Edges: /     homo_loca: ( 53,  58)
02:09:39.026 | INFO |            center_loca: (4, 2)
02:09:39.286 | INFO | 0.260s         predict: 60
02:09:39.286 | INFO | -- -- -- -- -- -- -- -- -- -- --
02:09:39.288 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:39.288 | INFO | -- -- -- -- FL -- -- -- -- -- ..
02:09:39.288 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:39.288 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:39.288 | INFO | .. -- -- -- -- -- -- -- -- -- ..
02:09:39.289 | INFO | Radar (1, -2) -> Local F1 (fleet=E3)
02:09:39.289 | INFO | Click ( 744,  226) @ F1
02:09:41.879 | INFO | Port route at [0 2]
02:09:41.978 | INFO |            tile_center: 0.864 (9 matches)
02:09:41.996 | INFO | 0.112s  _   edge_lines: 5 hori, 1 vert
02:09:41.996 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:42.000 | INFO |           grids_offset: (1, 0)
02:09:42.002 | INFO |            center_loca: (4, 0)
02:09:42.149 | INFO | 0.146s         predict: 35
02:09:42.150 | INFO | -- -- -- -- FL -- -- -- --
02:09:42.150 | INFO | -- -- -- -- -- -- -- -- --
02:09:42.151 | INFO | -- -- -- -- -- -- -- -- --
02:09:42.151 | INFO | .. -- -- -- -- -- -- -- --
02:09:42.151 | INFO | Radar (0, 2) -> Local E3 (fleet=E1)
02:09:42.152 | INFO | Click ( 647,  517) @ E3
02:09:44.757 | INFO | Port route at [-2  2]
02:09:44.857 | INFO |            tile_center: 0.887 (14 matches)
02:09:44.872 | INFO | 0.111s  _   edge_lines: 5 hori, 1 vert
02:09:44.873 | INFO | Edges:   \   homo_loca: ( 53,  58)
02:09:44.877 | INFO |           grids_offset: (1, 0)
02:09:44.878 | INFO |            center_loca: (4, 1)
02:09:45.073 | INFO | 0.195s         predict: 44
02:09:45.074 | INFO | -- -- -- -- -- -- -- -- --
02:09:45.074 | INFO | -- -- -- -- -- -- -- -- --
02:09:45.074 | INFO | -- -- -- -- FL -- -- -- --
02:09:45.075 | INFO | -- -- -- -- -- -- -- -- --
02:09:45.075 | INFO | .. -- -- -- -- -- -- -- --
02:09:45.075 | INFO | Radar (-2, 2) -> Local C5 (fleet=E2)
02:09:45.076 | INFO | Click ( 414,  592) @ C5
02:09:48.448 | INFO | Port route at [ 1 -2]
02:09:48.532 | INFO |            tile_center: 0.912 (good match)
02:09:48.546 | INFO | 0.093s  _   edge_lines: 6 hori, 1 vert
02:09:48.547 | INFO | Edges: /     homo_loca: ( 53,  59)
02:09:48.555 | INFO |            center_loca: (3, 4)
02:09:48.876 | INFO | 0.321s         predict: 75
02:09:48.877 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:48.877 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:48.877 | INFO | -- -- -- -- -- -- -- -- -- --
02:09:48.878 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:48.878 | INFO | -- -- -- FL -- -- -- -- -- ..
02:09:48.879 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:48.879 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:48.879 | INFO | -- -- -- -- -- -- -- -- -- ..
02:09:48.879 | INFO | Radar (1, -2) -> Local E3 (fleet=D5)
02:09:48.880 | INFO | Click ( 744,  228) @ E3
02:09:51.713 | INFO | Port route at [ 1 -2]
02:09:51.813 | INFO |            tile_center: 0.899 (19 matches)
02:09:51.829 | INFO | 0.111s  _   edge_lines: 5 hori, 1 vert
02:09:51.829 | INFO | Edges: /     homo_loca: ( 53,  58)
02:09:51.837 | INFO |            center_loca: (4, 2)
02:09:52.093 | INFO | 0.255s         predict: 60
02:09:52.094 | INFO | -- -- -- -- -- -- -- -- -- -- --
02:09:52.094 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:52.094 | INFO | -- -- -- -- FL -- -- -- -- -- ..
02:09:52.095 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:52.095 | INFO | -- -- -- -- -- -- -- -- -- -- ..
02:09:52.095 | INFO | .. -- -- -- -- -- -- -- -- -- ..
02:09:52.096 | INFO | Radar (1, -2) -> Local F1 (fleet=E3)
02:09:52.096 | INFO | Click ( 740,  223) @ F1
02:09:54.650 | INFO | Port route at [0 2]
Scheduler stopped.

**Comment by LmeSzinc** [comment]
过程比较复杂，需要提供视频

**Comment by LmeSzinc** [comment]
无法复现的问题。

另外，大世界的坐标都是局部地图坐标，在不同镜头之间对比是没有意义的。至于为什么大世界里的都是局部坐标，而正常地图都是全局坐标，可以看 #723 。
```
02:09:11.244 | INFO | Radar (1, -2) -> Local E3 (fleet=D5)
02:09:11.244 | INFO | Click ( 743, 222) @ E3
```
