### ISSUE TITLE
Failed to find a free tile

### ISSUE THREAD

**Issue by Arcelibs** [LmeSzinc/AzurLaneAutoScript#743]
**Describe the bug**
運行一段時間後 Failed to find a free tile 自動停止
持續的刷某張圖，連續使用1小時以上

附上log檔案，該如何設置模擬器以減少這樣的情況發生?
(how to set my Android Emulator to reduce the occurrence of such situations?)

我的電腦配置(My Computer hardware)
CPU : 3300X 4C8T
RAM : 32G
SSD 1TB
VGA : RX460 2G

模擬器配置 
4Core 8G RAM 有設定顯卡加速 雷電模擬器(LDPlayer)

** my log ↓ **
[2021-11-10_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7512670/2021-11-10_alas.txt)

**Comment by LmeSzinc** [comment]
501467ed4c1d50f5872c21bd6b285cd211344a8f ， 7a0c566a9e9f1add9236835386611a0d17a8c001 ，这两个 commit 下来应该解决了 #736 里描述的问题，~~又给瓜游cxy擦屁股了~~。

> 原因是，模拟器卡顿或者游戏卡顿时，把滑动当成点击，又刚好点到了一个敌人进入战斗，导致海图识别报错


这是一个非常复杂又充满魔法的实现，我顺便记录一下整个过程。

1. 在 13-4 的右下角无限滑动，等待复现。滑动3格来探究点击发生在什么位置。

![134_swipe](https://user-images.githubusercontent.com/37934724/142884981-c8c5cb3d-7c58-4089-ac25-e0232708a02f.png)
```python
from campaign.campaign_main.campaign_13_4 import Campaign
az = Campaign('alas')
self.device.disable_stuck_detection()
while 1:
    self.device.swipe((-300, -10), box=(230, 240, 570, 310), padding=5)
```

2. 创造卡顿的游戏客户端。多开模拟器，几天不重启游戏，使用科技（感谢现在基于 Game Guardian 的垃圾科技，cpu占用增加了两倍），~~摸鱼玩原神~~。
大概 5 分钟左右会出现一次舰队移动的情况，也就是出现了滑动变点击，点击的位置都是在滑动轨迹的末端。

3. 优化随机滑动的生成 （[random_rectangle_vector_opted](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/790515c800dd657cd30e35e9e6d50454d3e60bc7/module/base/utils.py#L62-L118)）。建立白名单和黑名单区域，滑动轨迹结束在陆地上是安全的，是白名单区域，落在敌人上会引起报错，是黑名单区域。

4. 计算黑白名单区域（[get_swipe_area_opt](https://github.com/LmeSzinc/AzurLaneAutoScript/blob/790515c800dd657cd30e35e9e6d50454d3e60bc7/module/map/camera.py#L394-L438)）。查找全局地图中的岛屿，转换为局部地图的格子，作为白名单格子；查找局部地图中的敌人，作为黑名单格子。接下来是将格子转换为区域，这里又涉及到透视计算了，因为海图识别得到的是当前的局部地图，滑动过后地图会移动，需要预测移动后落在哪个格子上。`screen2grid` 和 `grid2screen` 封装了 带透视的海域坐标 与 平面坐标 之间的相互转换，直接调用就行。这张图里的绿框是白名单区域，红框是黑名单区域，这是一个 `(0, 0)` 的短滑动，将镜头对准网格中心，所以区域和原来物品很接近。

![swipe_show](https://user-images.githubusercontent.com/37934724/142890822-f018a943-7291-46a6-b7f3-2333fa70eae7.png)

5. 最后是修改 Alas 的识别逻辑，每次滑动过后增加海域物品的识别，给下一次滑动前计算黑白名单区域使用。在两个很卡的客户端上挂了两天，未出现一次 MapDetectionError，修改前大概 3-6 小时会出现一次。
