### ISSUE TITLE
config --local --unset http.proxy

### ISSUE THREAD

**Issue by genmone** [LmeSzinc/AzurLaneAutoScript#748]
**Describe the bug**
不能使用反和谐功能
**To Reproduce**
点击启用自动运行
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54836819/141649220-a905fe50-32ec-4f72-83c7-ff1f5f9fcb02.png)

**Log**
Post the entire log snippet that caused you to receive the error
![image](https://user-images.githubusercontent.com/54836819/141649223-4e5bf3cc-0f7f-4261-9f8b-6abcc982ff47.png)

**Comment by LmeSzinc** [comment]
运行没有问题。

Alas 仍然在执行 `git fetch`，下载需要一些时间，请等待。

**Comment by genmone** [comment]
> 运行没有问题。
> 
> Alas 仍然在执行 `git fetch`，下载需要一些时间，请等待。

![image](https://user-images.githubusercontent.com/54836819/141664170-d29e03c1-52d2-4589-b648-4b4917395e02.png)
左上角的运行错误,我尝试过打开或关闭碧蓝航线客户端,都是如图情况,应该是替换文件时出错

**Comment by genmone** [comment]
以和谐打扰了
