### ISSUE TITLE
科研项目优先级识别有误

### ISSUE THREAD

**Issue by stevenghost** [LmeSzinc/AzurLaneAutoScript#753]
S4-Q0.5 > Q-0.5 > S4-DR0.5 > S4-H0.5 > S4-PRY0.5 > DR-0.5 > PRY-0.5
> S4-Q4 > S4-Q2 > S4-Q1
> S4-DR2.5 > S4-PRY2.5
> S4-G1.5 > S4-G2.5
> S4-DR5 > S4-PRY5
> S4-G4 > S4-DR8
> S4-1 > S4-2 > S4-4 > reset > shortest

我使用默认优先级字串

14:28:39.115 | INFO | ==================== RESEARCH REWARD ====================
14:28:39.117 | INFO | No research has finished
14:28:39.117 | INFO | ==================== RESEARCH SELECT ====================
14:28:39.128 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
14:28:39.281 | INFO | [RESEARCH 0.164s] ['G-531-MI', 'C-153-MI', 'D-305-MI', 'D-363-MI', 'E-031-MI']
14:28:39.286 | INFO | [Project] S4 G-531-MI
14:28:39.286 | INFO | [Project] S4 C-153-MI
14:28:39.286 | INFO | [Project] S2 D-305-MI
14:28:39.286 | INFO | [Project] S4 D-363-MI
14:28:39.286 | INFO | [Project] S4 E-031-MI
14:28:39.286 | INFO | [Filter_sort] S4 G-531-MI > reset > shortest
14:28:39.286 | INFO | Research project: S4 G-531-MI
14:28:39.286 | INFO | Research project: 0
14:28:39.287 | INFO | Project offset: 0, project 0 is at 0
14:28:39.287 | INFO | Click ( 119,  248) @ ENTRANCE_1
14:28:41.579 | INFO | Click ( 463,  581) @ RESEARCH_START
14:28:41.812 | INFO | Click ( 791,  510) @ POPUP_CONFIRM_RESEARCH_START
14:28:42.411 | INFO | Research detail quit
14:28:42.419 | INFO | Click ( 734,  701) @ RESEARCH_DETAIL_QUIT

应该是G-531-MI = G4 D-363-MI = DR5 把 似乎没有正确的执行优先级顺序

**Comment by LmeSzinc** [comment]
请阅读 “自定义科研过滤器” 下方的帮助文本

> 使用自定义过滤器需**将 "科研过滤器" 设置为 "自定义"**，并阅读 https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/filter_string_cn
