### ISSUE TITLE
台服科研自動化無法使用

### ISSUE THREAD

**Issue by leo706966** [LmeSzinc/AzurLaneAutoScript#756]
台服改了UI會按不到科研室
![Snipaste_2021-11-18_19-37-33](https://user-images.githubusercontent.com/15162112/142408418-1f105190-fc54-4d9d-81bd-732fabcd0bd1.png)

**Comment by julystone** [comment]
![image](https://user-images.githubusercontent.com/49509508/142588850-c70e5ed3-9684-4689-9179-34daef7efc17.png)

可以提供下，1280*720的截图文件呗

**Comment by leo706966** [comment]
![Screenshot_2021 11 19_16 18 07 117](https://user-images.githubusercontent.com/15162112/142589230-6ebd7c29-cf2a-4080-8f12-da12b61d48db.png)
![Screenshot_2021 11 19_16 18 18 283](https://user-images.githubusercontent.com/15162112/142589239-c13d75aa-d9a8-4f28-b5c0-5bd20cdf2e9a.png)
目前的UI

**Comment by leo706966** [comment]
![Screenshot_2021 11 19_16 18 18 283](https://user-images.githubusercontent.com/15162112/142589536-b80c9716-9fc8-401d-bfa0-6355311585ed.png)
![Screenshot_2021 11 19_16 18 07 117](https://user-images.githubusercontent.com/15162112/142589539-702e1895-f793-4d36-97fd-dcb272e9533b.png)

**Comment by leo706966** [comment]
![Screenshot_2021 11 19_16 22 03 900](https://user-images.githubusercontent.com/15162112/142589613-5464d298-fc4d-4272-aee6-d70f30d7c29f.png)
![Screenshot_2021 11 19_16 18 07 117](https://user-images.githubusercontent.com/15162112/142589619-ed450638-525a-400c-9dc4-a21589f11b65.png)

**Comment by julystone** [comment]
![image](https://user-images.githubusercontent.com/49509508/142590114-911b4738-af48-4017-adc3-a7f0125dae92.png)
与cn服的似乎没区别，我直接用cn的asset了？ @LmeSzinc
