### ISSUE TITLE
希望能支持繁體服大世界的部分

### ISSUE THREAD

**Issue by leo706966** [LmeSzinc/AzurLaneAutoScript#762]
有需要什麼我可以提供。

**Comment by LmeSzinc** [comment]
#761

**Comment by leo706966** [comment]
![image](https://user-images.githubusercontent.com/15162112/142732415-1b925090-09e4-493c-a061-04a0d877fba1.png)
剛剛測試 能辨識地圖名了

**Comment by Zorachristine** [comment]
> 有需要什麼我可以提供。

感謝你願意抽空支援，因為我不是很懂程式語言，所以我更新的部分就僅有`./assets/tw`及活動`campaign`。
所以具體需要幫忙的地方，我無法指明，就請你看哪邊有問題，直接做修正即可。
