### ISSUE TITLE
关于保留自定义修改

### ISSUE THREAD

**Issue by Elypha** [LmeSzinc/AzurLaneAutoScript#771]
源于这个需求 #291
alas 运行的时候貌似会和远程仓库同步并覆盖冲突，请问有保留这些更改的比较优雅的方法吗……（git 苦手，考虑到要兼容后续更新暂时想不到什么方法……除了 fork 一个做自定义 x

**Comment by LmeSzinc** [comment]
config/deploy.yaml 里有 KeepLocalChanges 设置，本质是自动 git slash

**Comment by Elypha** [comment]
哦哦哦原来如此！
解决了，十分感谢！
