### ISSUE TITLE
JP MAP NAME BUG

### ISSUE THREAD

**Issue by xvatan** [LmeSzinc/AzurLaneAutoScript#774]
**Describe the bug**
For some reason, the software doesn't recognize 4-2 as a map name

**To Reproduce**
1. Set Alas to JP server
2. click on the main
3. set level to 4-2

**Expected behavior**
I expected it to start grinding 4-2

**Screenshots**
![image](https://user-images.githubusercontent.com/59143278/143541793-9906e985-2a13-422f-90d3-ed414302aae3.png)

**Log**
11:55:08.165 | INFO | +--------------------------------------------+
11:55:08.165 | INFO | |                    MAIN                    |
11:55:08.166 | INFO | +--------------------------------------------+
11:55:08.173 | INFO | ==================== CAMPAIGN_4_2 ====================
11:55:08.174 | INFO | Count: 0
11:55:08.431 | INFO | [UI] page_campaign
11:55:08.431 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:08.716 | INFO | [Mode_switch_1] normal
11:55:08.716 | INFO | Click (  92,  667) @ SWITCH_1_NORMAL
11:55:10.139 | INFO | [Mode_switch_1] hard
11:55:10.140 | INFO | <<< UI ENSURE INDEX >>>
11:55:10.261 | INFO | [campaign 0.025s] ['1-4', '1-', '1-1', '1-3']
11:55:10.262 | INFO | [Chapter] 1
11:55:10.262 | INFO | [Stage] 1-4, 1--, 1-1, 1-3
11:55:10.262 | INFO | [Index] 1
11:55:10.262 | INFO | Click (1221,  372) @ CHAPTER_NEXT
11:55:10.487 | INFO | Click (1222,  372) @ CHAPTER_NEXT
11:55:10.750 | INFO | Click (1222,  376) @ CHAPTER_NEXT
11:55:12.229 | INFO | [campaign 0.025s] ['4-4', '4-1', '4-', '4-']
11:55:12.229 | INFO | [Chapter] 4
11:55:12.230 | INFO | [Stage] 4-4, 4-1, 4--
11:55:12.230 | INFO | [Index] 4
11:55:12.230 | WARNING | Stage not found: 4-2
11:55:12.518 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:12.520 | INFO | [Mode_switch_1] hard
11:55:12.521 | INFO | <<< UI ENSURE INDEX >>>
11:55:12.641 | INFO | [campaign 0.022s] ['4-4', '4-1', '4-', '4-']
11:55:12.641 | INFO | [Chapter] 4
11:55:12.641 | INFO | [Stage] 4-4, 4-1, 4--
11:55:12.641 | INFO | [Index] 4
11:55:12.642 | WARNING | Stage not found: 4-2
11:55:12.917 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:12.919 | INFO | [Mode_switch_1] hard
11:55:12.919 | INFO | <<< UI ENSURE INDEX >>>
11:55:13.035 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:13.035 | INFO | [Chapter] 4
11:55:13.036 | INFO | [Stage] 4-4, 4-1, 4--
11:55:13.036 | INFO | [Index] 4
11:55:13.036 | WARNING | Stage not found: 4-2
11:55:13.306 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:13.579 | INFO | [Mode_switch_1] hard
11:55:13.579 | INFO | <<< UI ENSURE INDEX >>>
11:55:13.697 | INFO | [campaign 0.022s] ['4-4', '4-1', '4-', '4-']
11:55:13.697 | INFO | [Chapter] 4
11:55:13.697 | INFO | [Stage] 4-4, 4-1, 4--
11:55:13.697 | INFO | [Index] 4
11:55:13.698 | WARNING | Stage not found: 4-2
11:55:13.962 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:14.257 | INFO | [Mode_switch_1] hard
11:55:14.257 | INFO | <<< UI ENSURE INDEX >>>
11:55:14.372 | INFO | [campaign 0.022s] ['4-4', '4-1', '4-', '4-']
11:55:14.372 | INFO | [Chapter] 4
11:55:14.372 | INFO | [Stage] 4-4, 4-1, 4--
11:55:14.372 | INFO | [Index] 4
11:55:14.373 | WARNING | Stage not found: 4-2
11:55:14.638 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:14.930 | INFO | [Mode_switch_1] hard
11:55:14.930 | INFO | <<< UI ENSURE INDEX >>>
11:55:15.045 | INFO | [campaign 0.022s] ['4-4', '4-1', '4-', '4-']
11:55:15.045 | INFO | [Chapter] 4
11:55:15.045 | INFO | [Stage] 4-4, 4-1, 4--
11:55:15.045 | INFO | [Index] 4
11:55:15.046 | WARNING | Stage not found: 4-2
11:55:15.311 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:15.588 | INFO | [Mode_switch_1] hard
11:55:15.588 | INFO | <<< UI ENSURE INDEX >>>
11:55:15.720 | INFO | [campaign 0.035s] ['4-4', '4-1', '4-', '4-']
11:55:15.721 | INFO | [Chapter] 4
11:55:15.721 | INFO | [Stage] 4-4, 4-1, 4--
11:55:15.721 | INFO | [Index] 4
11:55:15.721 | WARNING | Stage not found: 4-2
11:55:15.986 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:16.262 | INFO | [Mode_switch_1] hard
11:55:16.262 | INFO | <<< UI ENSURE INDEX >>>
11:55:16.376 | INFO | [campaign 0.021s] ['4-4', '4-1', '4-', '4-']
11:55:16.376 | INFO | [Chapter] 4
11:55:16.377 | INFO | [Stage] 4-4, 4-1, 4--
11:55:16.377 | INFO | [Index] 4
11:55:16.377 | WARNING | Stage not found: 4-2
11:55:16.631 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:16.931 | INFO | [Mode_switch_1] hard
11:55:16.931 | INFO | <<< UI ENSURE INDEX >>>
11:55:17.047 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:17.047 | INFO | [Chapter] 4
11:55:17.047 | INFO | [Stage] 4-4, 4-1, 4--
11:55:17.047 | INFO | [Index] 4
11:55:17.048 | WARNING | Stage not found: 4-2
11:55:17.313 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:17.315 | INFO | [Mode_switch_1] hard
11:55:17.315 | INFO | <<< UI ENSURE INDEX >>>
11:55:17.432 | INFO | [campaign 0.021s] ['4-4', '4-1', '4-', '4-']
11:55:17.433 | INFO | [Chapter] 4
11:55:17.433 | INFO | [Stage] 4-4, 4-1, 4--
11:55:17.433 | INFO | [Index] 4
11:55:17.433 | WARNING | Stage not found: 4-2
11:55:17.718 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:18.020 | INFO | [Mode_switch_1] hard
11:55:18.020 | INFO | <<< UI ENSURE INDEX >>>
11:55:18.134 | INFO | [campaign 0.021s] ['4-4', '4-1', '4-', '4-']
11:55:18.134 | INFO | [Chapter] 4
11:55:18.134 | INFO | [Stage] 4-4, 4-1, 4--
11:55:18.134 | INFO | [Index] 4
11:55:18.134 | WARNING | Stage not found: 4-2
11:55:18.393 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:18.686 | INFO | [Mode_switch_1] hard
11:55:18.686 | INFO | <<< UI ENSURE INDEX >>>
11:55:18.809 | INFO | [campaign 0.025s] ['4-4', '4-1', '4-', '4-']
11:55:18.809 | INFO | [Chapter] 4
11:55:18.809 | INFO | [Stage] 4-4, 4-1, 4--
11:55:18.809 | INFO | [Index] 4
11:55:18.809 | WARNING | Stage not found: 4-2
11:55:19.086 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:19.088 | INFO | [Mode_switch_1] hard
11:55:19.089 | INFO | <<< UI ENSURE INDEX >>>
11:55:19.202 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:19.202 | INFO | [Chapter] 4
11:55:19.202 | INFO | [Stage] 4-4, 4-1, 4--
11:55:19.203 | INFO | [Index] 4
11:55:19.203 | WARNING | Stage not found: 4-2
11:55:19.463 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:19.741 | INFO | [Mode_switch_1] hard
11:55:19.742 | INFO | <<< UI ENSURE INDEX >>>
11:55:19.869 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:19.869 | INFO | [Chapter] 4
11:55:19.869 | INFO | [Stage] 4-4, 4-1, 4--
11:55:19.869 | INFO | [Index] 4
11:55:19.870 | WARNING | Stage not found: 4-2
11:55:20.144 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:20.146 | INFO | [Mode_switch_1] hard
11:55:20.147 | INFO | <<< UI ENSURE INDEX >>>
11:55:20.268 | INFO | [campaign 0.021s] ['4-4', '4-1', '4-', '4-']
11:55:20.268 | INFO | [Chapter] 4
11:55:20.269 | INFO | [Stage] 4-4, 4-1, 4--
11:55:20.269 | INFO | [Index] 4
11:55:20.269 | WARNING | Stage not found: 4-2
11:55:20.540 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:20.833 | INFO | [Mode_switch_1] hard
11:55:20.833 | INFO | <<< UI ENSURE INDEX >>>
11:55:20.944 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:20.944 | INFO | [Chapter] 4
11:55:20.944 | INFO | [Stage] 4-4, 4-1, 4--
11:55:20.945 | INFO | [Index] 4
11:55:20.945 | WARNING | Stage not found: 4-2
11:55:21.216 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:21.507 | INFO | [Mode_switch_1] hard
11:55:21.508 | INFO | <<< UI ENSURE INDEX >>>
11:55:21.640 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:21.640 | INFO | [Chapter] 4
11:55:21.641 | INFO | [Stage] 4-4, 4-1, 4--
11:55:21.641 | INFO | [Index] 4
11:55:21.641 | WARNING | Stage not found: 4-2
11:55:21.922 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:22.213 | INFO | [Mode_switch_1] hard
11:55:22.214 | INFO | <<< UI ENSURE INDEX >>>
11:55:22.331 | INFO | [campaign 0.022s] ['4-4', '4-1', '4-', '4-']
11:55:22.331 | INFO | [Chapter] 4
11:55:22.331 | INFO | [Stage] 4-4, 4-1, 4--
11:55:22.331 | INFO | [Index] 4
11:55:22.332 | WARNING | Stage not found: 4-2
11:55:22.599 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:22.898 | INFO | [Mode_switch_1] hard
11:55:22.899 | INFO | <<< UI ENSURE INDEX >>>
11:55:23.013 | INFO | [campaign 0.020s] ['4-4', '4-1', '4-', '4-']
11:55:23.013 | INFO | [Chapter] 4
11:55:23.013 | INFO | [Stage] 4-4, 4-1, 4--
11:55:23.014 | INFO | [Index] 4
11:55:23.014 | WARNING | Stage not found: 4-2
11:55:23.291 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
11:55:23.574 | INFO | [Mode_switch_1] hard
11:55:23.574 | INFO | <<< UI ENSURE INDEX >>>
11:55:23.693 | INFO | [campaign 0.025s] ['4-4', '4-1', '4-', '4-']
11:55:23.693 | INFO | [Chapter] 4
11:55:23.694 | INFO | [Stage] 4-4, 4-1, 4--
11:55:23.694 | INFO | [Index] 4
11:55:23.694 | WARNING | Stage not found: 4-2
11:55:23.970 | WARNING | Campaign name error
11:55:23.971 | ERROR | Campaign name error
Traceback (most recent call last):
  File "D:\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "D:\AzurLaneAutoScript\alas.py", line 225, in main
    name=self.config.Campaign_Name, folder=self.config.Campaign_Event, mode=self.config.Campaign_Mode)
  File "D:\AzurLaneAutoScript\module\campaign\run.py", line 200, in run
    mode=mode
  File "D:\AzurLaneAutoScript\module\campaign\campaign_ui.py", line 124, in ensure_campaign_ui
    raise ScriptEnd('Campaign name error')
module.exception.ScriptEnd: Campaign name error
11:55:23.973 | WARNING | Saving error: ./log/error/1637898923973

**Comment by LmeSzinc** [comment]
需要 1280x720 的截图，./log/error/1637898923973 里面有

**Comment by xvatan** [comment]
![2021-11-26_22-14-24-652636](https://user-images.githubusercontent.com/59143278/143594074-584245df-b13d-46d3-84a7-f5ce8d2a1fbe.png)


> 需要 1280x720 的截图，./log/error/1637898923973 里面有
