### ISSUE TITLE
日服困難11-2的數據消失了?

### ISSUE THREAD

**Issue by h29800020** [LmeSzinc/AzurLaneAutoScript#776]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:03:57:51.337 | INFO | <<< UI ENSURE INDEX >>>
03:57:51.529 | INFO | [campaign 0.030s] ['11-3', '11-1', '11-4', '11-']
03:57:51.530 | INFO | [Chapter] 11
03:57:51.530 | INFO | [Stage] 11-3, 11-1, 11-4, 11-
03:57:51.530 | INFO | [Index] 11
03:57:51.530 | WARNING | Stage not found: 11-2
03:57:51.905 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
03:57:52.444 | INFO | [Mode_switch_1] normal
03:57:52.445 | INFO | Click (  62,  658) @ SWITCH_1_NORMAL
03:57:54.012 | INFO | [Mode_switch_1] hard
03:57:54.012 | INFO | <<< UI ENSURE INDEX >>>
03:57:54.389 | INFO | [campaign 0.112s] ['11-', '11-1', '11-4', '11-']
03:57:54.389 | INFO | [Chapter] 11
03:57:54.389 | INFO | [Stage] 11-, 11-1, 11-4
03:57:54.389 | INFO | [Index] 11
03:57:54.392 | INFO | [Mode_switch_1] hard
03:57:54.392 | INFO | Click ( 119,  645) @ SWITCH_1_HARD
03:57:56.287 | INFO | [Mode_switch_1] normal
03:57:56.287 | INFO | <<< UI ENSURE INDEX >>>
03:57:56.477 | INFO | [campaign 0.037s] ['11-3', '11-1', '11-4', '11-']
03:57:56.478 | INFO | [Chapter] 11
03:57:56.478 | INFO | [Stage] 11-3, 11-1, 11-4, 11-
03:57:56.478 | INFO | [Index] 11
03:57:56.479 | WARNING | Stage not found: 11-2
03:57:57.108 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
03:57:57.517 | INFO | [Mode_switch_1] normal
03:57:57.517 | INFO | Click ( 102,  666) @ SWITCH_1_NORMAL
03:57:59.028 | INFO | [Mode_switch_1] hard
03:57:59.029 | INFO | <<< UI ENSURE INDEX >>>
03:57:59.220 | INFO | [campaign 0.032s] ['11-', '11-1', '11-4', '11-']
03:57:59.220 | INFO | [Chapter] 11
03:57:59.220 | INFO | [Stage] 11-, 11-1, 11-4
03:57:59.221 | INFO | [Index] 11
03:57:59.223 | INFO | [Mode_switch_1] hard
03:57:59.223 | INFO | Click (  93,  670) @ SWITCH_1_HARD
03:58:00.769 | INFO | [Mode_switch_1] normal
03:58:00.769 | INFO | <<< UI ENSURE INDEX >>>
03:58:01.245 | INFO | [campaign 0.045s] ['11-3', '11-1', '11-4', '11-']
03:58:01.245 | INFO | [Chapter] 11
03:58:01.246 | INFO | [Stage] 11-3, 11-1, 11-4, 11-
03:58:01.247 | INFO | [Index] 11
03:58:01.247 | WARNING | Stage not found: 11-2
03:58:01.617 | INFO | <<< UI GOTO PAGE_CAMPAIGN >>>
03:58:01.619 | INFO | [Mode_switch_1] normal
03:58:01.620 | WARNING | Too many click between 2 buttons: SWITCH_1_HARD, SWITCH_1_NORMAL
03:58:01.620 | WARNING | History click: ['SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL', 'SWITCH_1_HARD', 'SWITCH_1_NORMAL']
03:58:01.621 | WARNING | Too many click between 2 buttons: SWITCH_1_HARD, SWITCH_1_NORMAL
03:58:01.621 | WARNING | Game stuck, com.YoStarJP.AzurLane will be restarted in 10 seconds
03:58:01.621 | WARNING | If you are playing by hand, please stop Alas
03:58:01.632 | INFO | Bind task {'Alas', 'Hard', 'General'}
03:58:01.632 | INFO | Save config ./config\alas.json, Restart.Scheduler.NextRun=datetime.datetime(2021, 1, 1, 0, 0), Restart.Scheduler.Enable=True
03:58:11.636 | INFO | Scheduler: End task `Hard`

找不到11-2

**Comment by LmeSzinc** [comment]
#773
