### ISSUE TITLE
大世界开荒没有等待30分钟

### ISSUE THREAD

**Issue by wxnsznbd** [LmeSzinc/AzurLaneAutoScript#785]
![444](https://user-images.githubusercontent.com/58931297/144090979-9d9dbaab-9cb9-4d01-850d-21311bb12d62.jpg)

电脑时间为00:41 等待到2021-12-01 01:11:13  但并没有等待,直接进下图,然后直接点空域搜索了

**Comment by LmeSzinc** [comment]
需要完整log

**Comment by LmeSzinc** [comment]
运行没有问题。

等待 30 分钟是，将下一次运行的时间推迟 30 分钟，并不是原地干等。这张地图的开荒才刚开始，结束后会切换至其他任务。从这张地图执行空域搜索，至下一张地图开始的时间间隔是 30 分钟。

**Comment by wxnsznbd** [comment]
一个海域是指一张地图还是几张地图是一个海域的.它依旧会使用9点体力值的空域侦查

**Comment by LmeSzinc** [comment]
![群主酱的掉 SAN 日常](https://user-images.githubusercontent.com/37934724/144097800-639e1a73-7357-43fc-b2d5-b3db2eb5606a.jpg)

**Comment by wxnsznbd** [comment]
01:25:48.866 | INFO | ==================== OS EXPLORE 43 ====================
01:25:48.866 | INFO | <<< ORDER_SCAN >>>
01:25:48.866 | INFO | <<< UI CLICK >>>
01:25:48.868 | INFO | Click (1030,  184) @ ORDER_ENTER
01:25:49.611 | INFO | Click (1132,  428) @ ORDER_SCAN
01:25:49.867 | INFO | Click ( 828,  549) @ POPUP_CONFIRM_ORDER_SCAN
01:25:51.811 | INFO | Delay task `OpsiExplore` to 2021-12-01 01:55:51 (minute=30)
01:25:51.819 | INFO | Bind task {'OpsiGeneral', 'OpsiExplore', 'Alas', 'General'}
01:25:51.819 | INFO | Save config ./config\alas.json, OpsiExplore.Scheduler.NextRun=datetime.datetime(2021, 12, 1, 1, 55, 51)
01:25:51.823 | INFO | -------------------- OS AUTO SEARCH --------------------
01:25:51.829 | INFO | Click (1233,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
01:25:55.192 | INFO | Click (1240,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
01:25:59.692 | INFO | [Loading] 31%
01:25:59.693 | INFO | [battle_count] 1
01:25:59.693 | INFO | Auto search combat loading
01:25:59.694 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:26:04.551 | INFO | Auto Search combat execute
01:26:19.581 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:26:19.582 | INFO | Combat end.
01:26:21.603 | INFO | [Loading] 28%
01:26:21.603 | INFO | [battle_count] 2
01:26:21.604 | INFO | Auto search combat loading
01:26:21.604 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:26:26.494 | INFO | Auto Search combat execute
01:26:40.556 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:26:40.556 | INFO | Combat end.
01:26:41.414 | INFO | [Loading] 30%
01:26:41.414 | INFO | [battle_count] 3
01:26:41.415 | INFO | Auto search combat loading
01:26:41.415 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:26:46.330 | INFO | Auto Search combat execute
01:27:02.391 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:27:02.391 | INFO | Combat end.
01:27:04.243 | INFO | [Loading] 31%
01:27:04.244 | INFO | [battle_count] 4
01:27:04.244 | INFO | Auto search combat loading
01:27:04.245 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:27:08.988 | INFO | Auto Search combat execute
01:27:21.007 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:27:21.007 | INFO | Combat end.
01:27:22.699 | INFO | [Loading] 10%
01:27:22.700 | INFO | [battle_count] 5
01:27:22.700 | INFO | Auto search combat loading
01:27:22.700 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:27:27.545 | INFO | Auto Search combat execute
01:28:01.655 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:28:01.655 | INFO | Combat end.
01:28:02.786 | INFO | Click (1185,   44) @ STORY_SKIP
01:28:05.026 | INFO | Click (1186,   46) @ STORY_SKIP
01:28:14.560 | INFO | Click (1186,   42) @ STORY_SKIP
01:28:17.675 | INFO | Click (1191,   33) @ STORY_SKIP
01:28:18.105 | INFO | Click (1221,  577) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
01:28:18.663 | INFO | Click ( 646,  630) @ AUTO_SEARCH_REWARD
01:28:20.107 | INFO | Get OS auto search reward
01:28:20.462 | INFO | OS auto search finished
01:28:20.525 | INFO | No akashi on this map
01:28:20.534 | INFO | Bind task {'OpsiGeneral', 'OpsiExplore', 'Alas', 'General'}
01:28:20.535 | INFO | Save config ./config\alas.json, OpsiExplore.OpsiExplore.LastZone=43
01:28:20.538 | INFO | Zone cleared: [43|西大陆架C|West Continental Shelf C|西大陸棚C|西大陸棚C]
01:28:20.542 | INFO | [HP]  98%  98%  98%  98%  98%  98%
01:28:20.545 | INFO | [Repair icon] [False, False, False, False, False, False]
01:28:20.545 | INFO | [HP]  98%  98%  98%  98%  98%  98%
01:28:20.545 | INFO | No ship found to be below threshold 50%, continue OS exploration
01:28:20.558 | INFO | No task pending
01:28:20.558 | INFO | [Task] OpsiExplore (Enable, 2021-12-01 01:55:51)
01:28:20.560 | INFO | <<< GLOBE GOTO: [81|NA海域西A|NA OCEAN W SECTOR A|NA海域西A|NA海域西A] >>>
01:28:20.563 | INFO | <<< UI CLICK >>>
01:28:20.566 | INFO | Click (1104,  678) @ MAP_GOTO_GLOBE
01:28:23.016 | INFO | Swipe ( 451,  448) -> ( 499,  401), 0.132
01:28:24.993 | INFO |           globe_center: (993.0, 670.0)
01:28:24.994 | INFO | 0.128s      similarity: 0.517
01:28:24.995 | INFO | [Globe_center] [81|NA海域西A|NA Ocean W Sector A|NA海域西A|NA海域西A]
01:28:24.995 | INFO | Globe focus_to: [81|NA海域西A|NA Ocean W Sector A|NA海域西A|NA海域西A]
01:28:24.998 | INFO | Click ( 605,  336) @ ZONE_81
01:28:25.889 | INFO |           globe_center: (1091.0, 562.0)
01:28:25.890 | INFO | 0.133s      similarity: 0.493
01:28:25.891 | INFO | [Globe_center] [91|NA海域西北A|NA Ocean NW Sector A|NA海域北西A|NA海域西北A]
01:28:26.431 | INFO |           globe_center: (1091.0, 562.0)
01:28:26.431 | INFO | 0.133s      similarity: 0.427
01:28:26.432 | INFO | [Globe_center] [91|NA海域西北A|NA Ocean NW Sector A|NA海域北西A|NA海域西北A]
01:28:26.433 | INFO | [Globe_pinned] [81|NA海域西A|NA Ocean W Sector A|NA海域西A|NA海域西A]
01:28:26.435 | INFO | Zone has no type to select, skip
01:28:26.438 | INFO | Click ( 514,  297) @ ZONE_ENTRANCE
01:28:27.256 | INFO | Loading OCR model: ./bin/cnocr_models/azur_lane
01:28:27.350 | INFO | [Amount_ocr 0.107s] [1049, 9, 2, 0]
01:28:27.372 | INFO | [ACTION_POINT_REMAIN 0.021s] 17
01:28:27.372 | INFO | Action points: 17(297), oil: 1049
01:28:27.373 | INFO | Click ( 703,  344) @ ACTION_POINT_GRID_2_0
01:28:27.935 | INFO | Click ( 811,  534) @ ACTION_POINT_USE
01:28:28.558 | INFO | [Amount_ocr 0.059s] [1049, 9, 1, 0]
01:28:28.580 | INFO | [ACTION_POINT_REMAIN 0.021s] 67
01:28:28.580 | INFO | Action points: 67(297), oil: 1049
01:28:28.580 | INFO | Having enough action points
01:28:28.580 | INFO | <<< UI CLICK >>>
01:28:28.602 | INFO | Click ( 461,  548) @ ACTION_POINT_CANCEL
01:28:29.457 | INFO | Click ( 467,  286) @ ZONE_ENTRANCE
01:28:31.437 | INFO | [MAP_NAME 0.049s] NA海域西A
01:28:31.438 | INFO | Map name processed: NA海域西A
01:28:31.438 | INFO | [Zone] [81|NA海域西A|NA Ocean W Sector A|NA海域西A|NA海域西A]
01:28:31.442 | INFO | [HP]  98%  98%  98%  98%  98%  98%
01:28:31.446 | INFO | [Repair icon] [False, False, False, False, False, False]
01:28:31.446 | INFO | [HP]  98%  98%  98%  98%  98%  98%
01:28:31.446 | INFO | No ship found to be below threshold 50%, continue OS exploration
01:28:31.447 | INFO | ==================== OS EXPLORE 81 ====================
01:28:31.447 | INFO | <<< ORDER_SCAN >>>
01:28:31.447 | INFO | <<< UI CLICK >>>
01:28:31.449 | INFO | Click (1023,  174) @ ORDER_ENTER
01:28:32.172 | INFO | Click ( 943,  447) @ ORDER_SCAN
01:28:32.419 | INFO | Click ( 762,  545) @ POPUP_CONFIRM_ORDER_SCAN
01:28:34.506 | INFO | Delay task `OpsiExplore` to 2021-12-01 01:58:34 (minute=30)
01:28:34.517 | INFO | Bind task {'OpsiGeneral', 'OpsiExplore', 'Alas', 'General'}
01:28:34.518 | INFO | Save config ./config\alas.json, OpsiExplore.Scheduler.NextRun=datetime.datetime(2021, 12, 1, 1, 58, 34)
01:28:34.522 | INFO | -------------------- OS AUTO SEARCH --------------------
01:28:34.527 | INFO | Click (1237,  584) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
01:28:36.248 | INFO | [Loading] 10%
01:28:36.249 | INFO | [battle_count] 1
01:28:36.249 | INFO | Auto search combat loading
01:28:36.249 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:28:41.184 | INFO | Auto Search combat execute
01:28:58.217 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:28:58.218 | INFO | Combat end.
01:28:59.696 | INFO | [Loading] 26%
01:28:59.696 | INFO | [battle_count] 2
01:28:59.697 | INFO | Auto search combat loading
01:28:59.697 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:29:04.460 | INFO | Auto Search combat execute
01:29:17.494 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:29:17.494 | INFO | Combat end.
01:29:21.479 | INFO | [Loading] 10%
01:29:21.480 | INFO | [battle_count] 3
01:29:21.480 | INFO | Auto search combat loading
01:29:21.480 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:29:26.284 | INFO | Auto Search combat execute
01:29:42.381 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:29:42.382 | INFO | Combat end.
01:29:43.628 | INFO | [Loading] 27%
01:29:43.629 | INFO | [battle_count] 4
01:29:43.629 | INFO | Auto search combat loading
01:29:43.629 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:29:48.521 | INFO | Auto Search combat execute
01:30:08.559 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:30:08.559 | INFO | Combat end.
01:30:10.976 | INFO | [Loading] 26%
01:30:10.977 | INFO | [battle_count] 5
01:30:10.977 | INFO | Auto search combat loading
01:30:10.977 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:30:15.795 | INFO | Auto Search combat execute
01:30:51.895 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:30:51.895 | INFO | Combat end.
01:30:52.230 | INFO | Click (1187,   37) @ STORY_SKIP
01:30:55.658 | INFO | Click (1182,   42) @ STORY_SKIP
01:30:58.688 | INFO | Click (1189,   41) @ STORY_SKIP
01:31:01.844 | INFO | Click (1189,   33) @ STORY_SKIP
01:31:02.801 | INFO | Click ( 645,  624) @ AUTO_SEARCH_REWARD
01:31:03.996 | INFO | Get OS auto search reward
01:31:04.375 | INFO | OS auto search finished
01:31:04.436 | INFO | No akashi on this map
01:31:04.445 | INFO | Bind task {'OpsiGeneral', 'OpsiExplore', 'Alas', 'General'}
01:31:04.445 | INFO | Save config ./config\alas.json, OpsiExplore.OpsiExplore.LastZone=81
01:31:04.448 | INFO | Zone cleared: [81|NA海域西A|NA Ocean W Sector A|NA海域西A|NA海域西A]
01:31:04.452 | INFO | [HP]  89%  92%  93%  93%  93%  98%
01:31:04.455 | INFO | [Repair icon] [False, False, False, False, False, False]
01:31:04.455 | INFO | [HP]  89%  92%  93%  93%  93%  98%
01:31:04.455 | INFO | No ship found to be below threshold 50%, continue OS exploration
01:31:04.465 | INFO | No task pending
01:31:04.465 | INFO | [Task] OpsiExplore (Enable, 2021-12-01 01:58:34)
01:31:04.466 | INFO | <<< GLOBE GOTO: [84|NA海域西D|NA OCEAN W SECTOR D|NA海域西D|NA海域西D] >>>
01:31:04.468 | INFO | <<< UI CLICK >>>
01:31:04.471 | INFO | Click (1146,  666) @ MAP_GOTO_GLOBE
01:31:07.329 | INFO | Swipe ( 444,  473) -> ( 491,  428), 0.134
01:31:09.321 | INFO |           globe_center: (1065.0, 592.0)
01:31:09.321 | INFO | 0.130s      similarity: 0.541
01:31:09.322 | INFO | [Globe_center] [82|NA海域西B|NA Ocean W Sector B|NA海域西B|NA海域西B]
01:31:09.323 | INFO | Globe focus_to: [84|NA海域西D|NA Ocean W Sector D|NA海域西D|NA海域西D]
01:31:09.326 | INFO | Click ( 570,  245) @ ZONE_84
01:31:10.211 | INFO |           globe_center: (1111.0, 356.0)
01:31:10.211 | INFO | 0.138s      similarity: 0.390
01:31:10.212 | INFO | [Globe_center] [92|NA海域西北B|NA Ocean NW Sector B|NA海域北西B|NA海域西北B]
01:31:10.762 | INFO |           globe_center: (1111.0, 356.0)
01:31:10.762 | INFO | 0.142s      similarity: 0.346
01:31:10.763 | INFO | [Globe_center] [92|NA海域西北B|NA Ocean NW Sector B|NA海域北西B|NA海域西北B]
01:31:10.764 | INFO | [Globe_pinned] [84|NA海域西D|NA Ocean W Sector D|NA海域西D|NA海域西D]
01:31:10.766 | INFO | Zone has no type to select, skip
01:31:10.769 | INFO | Click ( 497,  281) @ ZONE_ENTRANCE
01:31:12.955 | INFO | [MAP_NAME 0.121s] NA海域西D
01:31:12.956 | INFO | Map name processed: NA海域西D
01:31:12.956 | INFO | [Zone] [84|NA海域西D|NA Ocean W Sector D|NA海域西D|NA海域西D]
01:31:12.961 | INFO | [HP]  89%  92%  93%  93%  93%  98%
01:31:12.966 | INFO | [Repair icon] [False, False, False, False, False, False]
01:31:12.966 | INFO | [HP]  89%  92%  93%  93%  93%  98%
01:31:12.966 | INFO | No ship found to be below threshold 50%, continue OS exploration
01:31:12.967 | INFO | ==================== OS EXPLORE 84 ====================
01:31:12.967 | INFO | <<< ORDER_SCAN >>>
01:31:12.967 | INFO | <<< UI CLICK >>>
01:31:12.971 | INFO | Click (1027,  177) @ ORDER_ENTER
01:31:13.771 | INFO | Click (1051,  407) @ ORDER_SCAN
01:31:14.022 | INFO | Click ( 845,  531) @ POPUP_CONFIRM_ORDER_SCAN
01:31:16.016 | INFO | Delay task `OpsiExplore` to 2021-12-01 02:01:16 (minute=30)
01:31:16.025 | INFO | Bind task {'OpsiGeneral', 'OpsiExplore', 'Alas', 'General'}
01:31:16.026 | INFO | Save config ./config\alas.json, OpsiExplore.Scheduler.NextRun=datetime.datetime(2021, 12, 1, 2, 1, 16)
01:31:16.029 | INFO | -------------------- OS AUTO SEARCH --------------------
01:31:16.035 | INFO | Click (1251,  582) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
01:31:18.959 | INFO | [Loading] 21%
01:31:18.960 | INFO | [battle_count] 1
01:31:18.960 | INFO | Auto search combat loading
01:31:18.960 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:31:23.727 | INFO | Auto Search combat execute
01:31:38.839 | INFO | Screenshot interval set to 0.1s, limited to 1.0s in auto search
01:31:38.840 | INFO | Combat end.
01:31:41.324 | INFO | [Loading] 9%
01:31:41.325 | INFO | [battle_count] 2
01:31:41.325 | INFO | Auto search combat loading
01:31:41.325 | INFO | Screenshot interval set to 1.0s, limited to 1.0s in auto search
01:31:46.069 | INFO | Auto Search combat execute

**Comment by LmeSzinc** [comment]
你确认有问题，可以重开这个 issue。最好附上完整log。

**Comment by wxnsznbd** [comment]
直接复制log行不?

**Comment by LmeSzinc** [comment]
今日的完整 log，你可以在 ./log 目录下找到。

**Comment by wxnsznbd** [comment]
好的

**Comment by wxnsznbd** [comment]
[2021-12-01_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7627651/2021-12-01_alas.txt)

**Comment by wxnsznbd** [comment]
[2021-12-01_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7627696/2021-12-01_alas.txt)
[2021-12-01_gui.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7627703/2021-12-01_gui.txt)
这是我删除log文件后,重新跑了一遍的文件

**Comment by wxnsznbd** [comment]
![789](https://user-images.githubusercontent.com/58931297/144100104-603f6f91-5611-4f9d-a459-6ca4105075e4.jpg)
