### ISSUE TITLE
周回中舰队任务弹窗识别失败

### ISSUE THREAD

**Issue by Elypha** [LmeSzinc/AzurLaneAutoScript#789]
**Describe the bug**
本次活动图T4周回时，战斗结束后如果恰好有大舰队任务弹窗，则 alas 似乎无法进行下一步操作

======

**Screenshots**
![2021-12-01_05-28-19-888786](https://user-images.githubusercontent.com/30290883/144237637-3b01e196-e7d0-42a3-9e0d-bf709847cb89.png)

**Log**
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7633954/log.txt)

======

**Screenshots**
![2021-11-30_14-46-30-952375](https://user-images.githubusercontent.com/30290883/144237733-8ed95aba-82a8-4607-8f7f-76e826ffdb04.png)

**Log**
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7633959/log.txt)

**Comment by LmeSzinc** [comment]
这个弹窗通常战斗结算的时候就会弹出来，但是你的模拟器比较慢，alas已经捕捉到战斗结束，弹窗才出来。
我给走路的时候加了弹窗处理，应该能解决问题，不过我无法复现这个问题，因此需要你确认是否已经修复。

**Comment by Elypha** [comment]
哦哦哦！原来如此
十分感谢！测试了一段时间现在应该没有问题了！

---
另外虽然有点离题但想咨询一下模拟器的性能（第一次遇到性能问题2333
请问是否有什么方法可以自己排查一下瓶颈，或者现成的能代表碧蓝航线运行需求的 benchmark 可以参考（
因为感觉目前硬件也不算很过时 x
具体是 win10, amd 5800x/16gb/gtx 2060，开启虚拟化。模拟器是 Nox，4核+3GB

**Comment by LmeSzinc** [comment]
侧边栏的 `工具` 里有个 `性能测试`，不过也有可能是网络的问题。

**Comment by Elypha** [comment]
> 侧边栏的 `工具` 里有个 `性能测试`，不过也有可能是网络的问题。

啊我明白了，应该是网络问题。谢谢！
