### ISSUE TITLE
No Stage found

### ISSUE THREAD

**Issue by juelsong** [LmeSzinc/AzurLaneAutoScript#791]
**Describe the bug**
A clear and concise de
![1638455779(1)](https://user-images.githubusercontent.com/46945564/144442627-7807e030-1625-498d-91db-b2f58bb95f9f.jpg)
scription of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log**
Post the entire log snippet that caused you to receive the error

**Comment by juelsong** [comment]
脚本运行时经常会产生这个问题，但是一段时间就好了

**Comment by LmeSzinc** [comment]
这个不是 bug，是预期的行为。

进入出击界面后，要过一个小动画，关卡才会出现。按照 Alas 的设计原则，是不能写固定时长的等待去等这个动画的，否则会变慢，所以办法是：不管这个动画，直接去获取关卡入口，找不到就重试，直到成功。一般重试一次就成功了，第二次和以后没有重试，是因为已经在出击界面了，没有动画了。
