### ISSUE TITLE
雷电模拟器：adb已开启，日志没有报错但是启动发生错误

### ISSUE THREAD

**Issue by hyber1998** [LmeSzinc/AzurLaneAutoScript#792]
日志如下：
03:10:13.874 | INFO | [Server] cn
03:10:13.888 | INFO | Bind task {'General', 'Alas'}
03:10:13.905 | INFO | Start scheduler loop: alas
03:10:13.906 | INFO | [Server] cn
03:10:13.917 | INFO | Bind task {'General', 'Alas'}
03:10:13.919 | INFO | Pending tasks: ['Event']
03:10:13.919 | INFO | [Task] Event (Enable, 2020-01-01 00:00:00)
03:10:13.920 | INFO | Bind task {'General', 'Event', 'Alas'}
03:10:13.920 | INFO | Scheduler: Start task `Event`
03:10:14.391 | INFO | <<< DEVICE >>>
03:10:17.406 | INFO | [Adb_binary] D:/blhx/AzurLaneAutoScript/toolkit/Lib/site-packages/adbutils/binaries/adb.exe

无其他报错信息

**Comment by LmeSzinc** [comment]
重新打开你的模拟器和 Alas。
