### ISSUE TITLE
False OS Akashi detection

### ISSUE THREAD

**Issue by nEEtdo0d** [LmeSzinc/AzurLaneAutoScript#795]
**Describe the bug**
False OS Akashi detection.

Doesn't happen too often since depends on the zone and if your fleet ends up nearby the white question mark as it won't always.

Detected Akashi but no Akashi actually there. Actually detected are the 1-2 tiles which uses the same white question mark as Akashi. As a result, keeps moving until end of map and gets into a too many click state or stuck state depending on whether it remains in world view.

**To Reproduce**
1. Enter OS zone with 1-2 tile available
2. Move a fleet nearby any tile
3. Run any OS task
4. Should detect the white question mark on radar, presumes is Akashi and attempts to click on that tile but just moves and continuously keeps trying

**Expected behavior**
May fall into just needing to re-visit how Akashi is detected since white question mark is a shared icon indicator at least with Akashi and 1-2 tile it is.

I'm not familiar with how this all works but I was thinking may need to do an extra processing step and I noticed there is Akashi template.

Also might not be resolvable but after auto search, doesn't always end up near Akashi especially in obscure with walls dynamically created so can skip but not much we can do about that, I would think.

Just submitting this for awareness doesn't need to be handled anytime soon or we can leave it since again doesn't happen that often all RNG.

**Screenshots**
https://www.dropbox.com/sh/dnhbgmtgean2oz9/AACUBz6JWbaXjUimyyPig9jra?dl=0

**Log**
Logs can be found in dropbox link

**Comment by nEEtdo0d** [comment]
dropbox link updated with another error folder, 1-2 tile aren't the only question mark icons OS strongholds may have some as well it seems.  Been a while since this happened so low percentage of happening and even if it does ALAS gracefully restarts which is fine as a resolution.

**Comment by LmeSzinc** [comment]
Closed this issue as Akashi shop detection changed in #1130 .
