### ISSUE TITLE
Research Stuck Error

### ISSUE THREAD

**Issue by nEEtdo0d** [LmeSzinc/AzurLaneAutoScript#799]
**Describe the bug**
Not very clear as to why this happens but enters page_research and has trouble detecting something? I think its trying to do the receive but expected to be in the center however is not?  But there are some error folders with no collection needed but get stuck anyway.

**To Reproduce**
No steps to reproduce but looking from the date modified each error folder happen within minutes of one another all with similar circumstances.

**Expected behavior**
Current research collected and new research initiated without error.  I recall research rewards use to be collected on the sidebar in page_reward however but it doesn't look to be the case anymore.  I think there was an issue a while back that when collecting the page_research wasn't always consistent so was opted to collect at that time instead of page directly.

**Screenshots**
https://www.dropbox.com/s/bt2zhlll30jyalw/research_warning_stuck_error.zip?dl=0

**Log**
In drop box link in several error folders

**Comment by LmeSzinc** [comment]
This is a game bug, refer to #553 . Try to apply the same handler to EN.

The completed research wasn't shown in the middle. Detect and click the one that is actually completed can fix the issue of receiving, but the bug also freezes the research list. The list is not scrollable anymore resulting in a wrong research selection.

**Comment by nEEtdo0d** [comment]
I see, thanks for your analysis!

Hasn't happened again in over a week so will close the issue as it really does seem to be a random issue.  If comes again I'll try out this JP handler for EN variant.
```
if self.config.SERVER == 'en':
    if self._research_finished_index == 2:
        self.ui_goto_main()
        self.ui_ensure_research()
```
