### ISSUE TITLE
潛艇圖任務報錯

### ISSUE THREAD

**Issue by lam4562311** [LmeSzinc/AzurLaneAutoScript#802]
1. 在海域救援的頁面中，不斷向下滑動。
開啟任務調度之後，一旦去往海域救援的頁面後，就只會往下滑。
![image](https://user-images.githubusercontent.com/76723974/144831018-6750ef9a-c022-42ff-84b5-0a11e3779122.png)
2. 
![image](https://user-images.githubusercontent.com/76723974/144831128-51999ba9-24c2-4d0e-825c-986c718169ab.png)
當我手動搜尋一章任務之後，出現報錯。
即使設定其他潛艇圖出擊章節，也會報同樣錯誤。

18:13:35.275 | INFO | SOS_SCROLL_AREA set to 0.0
18:13:35.276 | INFO | [SOS_SCROLL_AREA] 0.00
18:13:35.435 | INFO | [OCR_SOS_CHAPTER 0.009s] 3
18:13:35.435 | ERROR | argument of type 'int' is not iterable
Traceback (most recent call last):
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\alas.py", line 48, in run
    self.__getattribute__(command)()
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\alas.py", line 191, in sos
    CampaignSos(config=self.config, device=self.device).run()
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\module\sos\sos.py", line 187, in run
    if self._sos_signal_select(self.config.Sos_Chapter):
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\module\base\decorator.py", line 69, in wrapper
    return record['func'](self, *args, **kwargs)
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\module\sos\sos.py", line 128, in _sos_signal_select
    target_button = self._find_target_chapter(chapter)
  File "D:\a\AlasApp_0.3.3\AzurLaneAutoScript\module\sos\sos.py", line 56, in _find_target_chapter
    if chapter in chapter_list:
TypeError: argument of type 'int' is not iterable
18:13:35.437 | WARNING | Saving error: ./log/error/1638785615437

python 版本
Python 3.7.6

**Comment by LmeSzinc** [comment]
TW还未适配潜艇图。

你可以关闭这个功能等待适配，或者参照 [这里](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/4.1.-Detection-objects#%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA-button) 替换相关 assets。

**Comment by Zorachristine** [comment]
#804 已有更新，
若仍有錯誤請回報。

**Comment by lam4562311** [comment]
更新後，設定打第六章潛艇圖，還是出現，在海域救援的頁面中，不斷向下滑動的情況。
試過打第三、五章，暫無出現問題。
我的賬號目前只開放到第六章的海域救援。

**Comment by yhtojy** [comment]
这个主要是因为TW服的滚轮颜色跟其他人不一样
这是写死在sos.py的
SOS_SCROLL = Scroll(SOS_SCROLL_AREA, color=**(247, 210, 66)**, name='SOS_SCROLL')
上面这是已经换成TW的颜色了
不过这个更改会改动全部伺服器的滚轮颜色判断

**Comment by LmeSzinc** [comment]
> 这个主要是因为TW服的滚轮颜色跟其他人不一样 这是写死在sos.py的 SOS_SCROLL = Scroll(SOS_SCROLL_AREA, color=**(247, 210, 66)**, name='SOS_SCROLL') 上面这是已经换成TW的颜色了 不过这个更改会改动全部伺服器的滚轮颜色判断

可以使用 `@Config.when()` 装饰器，参考 `_sos_chapter_crop`

**Comment by Zorachristine** [comment]
```
    @cached_property
    @Config.when(SERVER='tw')
    def _sos_chapter_crop(self):
        SOS_SCROLL = Scroll(SOS_SCROLL_AREA, color=(247, 210, 66), name='SOS_SCROLL')
        return [-403, 8, -381, 35]
```
抱歉，我沒有python基礎，google裝飾器的教學也都是用`print`來解釋，腦袋轉不過來。
上面的code我這樣輸入，可以跑但沒有反應，請問應該怎麼修改？

**Comment by LmeSzinc** [comment]
@Zorachristine 
```python
    @cached_property
    @Config.when(SERVER='tw')
    def _sos_scroll(self):
        return Scroll(SOS_SCROLL_AREA, color=(247, 210, 66), name='SOS_SCROLL')

    @cached_property
    @Config.when(SERVER=None)
    def _sos_scroll(self):
        return Scroll(SOS_SCROLL_AREA, color=(164, 173, 189), name='SOS_SCROLL')
```
然后把原来的 SOS_SCROLL 删了，SOS_SCROLL 的调用改成 `self._sos_scroll`

**Comment by LmeSzinc** [comment]
#834
