### ISSUE TITLE
OpSi Daily Module will stuck on the new Monthly Boss Task if we can't clear it

### ISSUE THREAD

**Issue by altissia86** [LmeSzinc/AzurLaneAutoScript#811]
**Describe the bug**
OpSi Daily use the Information button to cycle through the Daily taks, unfortunately I cant clear the Monthly Boss at Hard difficutly, that one task will always remain in my Information menu. OpSi will always treat that task as unfinished task, that way it will stuck there and won't check the port for new daily task

**To Reproduce**
1. Enable OpSi Daily
2. Make sure the new monthly boss is not finished yet
3. ALAS will stuck at the new boss task indefinitely

**Expected behavior**
ALAS should ignore the new monthly boss task, as if that task is not exist and proceed to check port for new dailies, and item restock

**Screenshots**
![Screenshot_2021 12 11_15 12 11 350](https://user-images.githubusercontent.com/83286751/145669656-79f4eea7-006b-4b5d-89d1-e4626d2ff18c.png)
![Screenshot_2021 12 11_15 12 16 600](https://user-images.githubusercontent.com/83286751/145669660-dab3fc2a-53aa-448c-8648-168d5d6e6886.png)
After clicking the View button, ALAS will stuck indefinitely

**Log**
[2021-12-11_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7696662/2021-12-11_alas.txt)

**Comment by nEEtdo0d** [comment]
commit b99a29e has been added to detect the required asset now however might be run into a different problem as shown in #814
