### ISSUE TITLE
台服大舰队作战派遣时间应是现实时间6/12/18/21

### ISSUE THREAD

**Issue by hephooey** [LmeSzinc/AzurLaneAutoScript#822]
默认配置文件似乎设置成了 "00:00, 12:00, 18:00, 21:00"
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/master/config/template.json#L655
其他版本没有实测，不过中英文 wiki 都是同样的时间:
https://wiki.biligame.com/blhx/%E5%A4%A7%E8%88%B0%E9%98%9F#.E4.BD.9C.E6.88.98
https://azurlane.koumakan.jp/wiki/Guild#Events

![Screenshot_20211213-042152](https://user-images.githubusercontent.com/5430834/145729103-ce416678-df40-45c4-a40f-91b77858dde8.png)

**Comment by LmeSzinc** [comment]
#818
