### ISSUE TITLE
记录错误log后将任务移除调度器并重启而不是卡住

### ISSUE THREAD

**Issue by yanyihui** [LmeSzinc/AzurLaneAutoScript#830]
**Is your feature request related to a problem? Please describe.**
出现bug调度器就自动停止了

**Describe the solution you'd like**
能否先保存错误日志和截图，然后将出错的任务移出调度器，然后尝试重启模拟器和调度器。
然后在某个地方显示被移出的任务。

或许能防止晚上出错导致卡死，然后其他功能白挂一晚上。

**Describe alternatives you've considered**

**Additional context**

**Comment by LmeSzinc** [comment]
#838
