### ISSUE TITLE
作战档案：努力希望和计划，无法自动点击推荐，一直点击清空，反复重启游戏

### ISSUE THREAD

**Issue by BronyaSeele** [LmeSzinc/AzurLaneAutoScript#831]
00:06:46.609 | INFO | +-----------------------------------------------+
00:06:46.609 | INFO | |                    RESTART                    |
00:06:46.609 | INFO | +-----------------------------------------------+
00:06:46.611 | INFO | <<< APP RESTART >>>
00:06:46.611 | INFO | App stop: com.bilibili.azurlane
00:06:47.314 | INFO | App start: com.bilibili.azurlane
00:06:47.938 | INFO | <<< APP LOGIN >>>
00:07:06.082 | INFO | Click ( 456,  370) @ LOGIN_CHECK
00:07:06.134 | INFO | Login success
00:07:11.512 | INFO | Click ( 470,  330) @ LOGIN_CHECK
00:07:19.340 | INFO | Login to main confirm
00:07:19.340 | INFO | Delay task `Restart` to 2021-12-16 00:00:00 (server_update='00:00')
00:07:19.352 | INFO | Bind task {'Restart', 'General', 'Alas'}
00:07:19.352 | INFO | Save config ./config\alas.json, Restart.Scheduler.NextRun=datetime.datetime(2021, 12, 16, 0, 0)
00:07:19.355 | INFO | Scheduler: End task `Restart`
00:07:19.355 | INFO | [Server] cn
00:07:19.372 | INFO | Bind task {'General', 'Alas'}
00:07:19.372 | INFO | Pending tasks: ['WarArchives']
00:07:19.372 | INFO | [Task] WarArchives (Enable, 2020-01-01 00:00:00)
00:07:19.372 | INFO | Bind task {'WarArchives', 'General', 'Alas'}
00:07:19.373 | INFO | Scheduler: Start task `WarArchives`
00:07:20.013 | INFO | +---------------------------------------------------+
00:07:20.013 | INFO | |                    WARARCHIVES                    |
00:07:20.014 | INFO | +---------------------------------------------------+
00:07:20.021 | INFO | ==================== SP1 ====================
00:07:20.021 | INFO | Count: 0
00:07:20.704 | INFO | [UI] page_main
00:07:20.705 | INFO | <<< UI ENSURE >>>
00:07:20.706 | INFO | [UI] page_main
00:07:20.707 | INFO | Goto page_archives
00:07:20.707 | INFO | <<< UI GOTO PAGE_ARCHIVES >>>
00:07:20.722 | INFO | Click (1112,  376) @ MAIN_GOTO_CAMPAIGN
00:07:22.022 | INFO | Click ( 274,  598) @ CAMPAIGN_MENU_GOTO_WAR_ARCHIVES
00:07:23.167 | INFO | [War_Archives_switch] ex
00:07:23.167 | INFO | Click (1065,   55) @ WAR_ARCHIVES_SP_ON
00:07:24.810 | INFO | [War_Archives_switch] sp
00:07:25.278 | INFO | <<< UI CLICK >>>
00:07:25.279 | INFO | Click ( 165,  164) @ war_archives_20181020_en
00:07:26.309 | INFO | <<< UI ENSURE INDEX >>>
00:07:26.451 | INFO | No stage found.
00:07:26.970 | INFO | <<< UI ENSURE INDEX >>>
00:07:27.140 | INFO | [campaign 0.023s] ['SP1', 'SP2']
00:07:27.141 | INFO | [Chapter] sp
00:07:27.141 | INFO | [Stage] sp1, sp2
00:07:27.141 | INFO | [Index] 1
00:07:27.183 | INFO | [OCR_DATA_KEY_CAMPAIGN 0.035s] 55/60
00:07:27.183 | INFO | Inventory: 55 / 60, Remain: 55
00:07:27.211 | INFO | [OCR_OIL 0.027s] 10949
00:07:27.211 | INFO | -------------------- SP1 --------------------
00:07:27.212 | INFO | Expect emotion reduce: (2, 4)
00:07:27.237 | INFO | Bind task {'WarArchives', 'General', 'Alas'}
00:07:27.238 | INFO | Save config ./config\alas.json, WarArchives.Emotion.Fleet1Value=119, WarArchives.Emotion.Fleet1Record=datetime.datetime(2021, 12, 15, 0, 7, 27), WarArchives.Emotion.Fleet2Value=119, WarArchives.Emotion.Fleet2Record=datetime.datetime(2021, 12, 15, 0, 7, 27)
00:07:27.244 | INFO | [Emotion fleet_1] 119
00:07:27.244 | INFO | [Emotion fleet_2] 119
00:07:27.245 | INFO | <<< ENTER MAP >>>
00:07:27.257 | INFO | Click ( 463,  237) @ sp1
00:07:29.317 | INFO | [MAP_CLEAR_ALL_THIS_TIME] False
00:07:29.317 | INFO | [Map_info] 99%, star_1, star_3, 100_percent_clear, clear_mode
00:07:29.317 | INFO | [StopCondition_MapAchievement] threat_safe
00:07:29.318 | INFO | [Fast_Forward] on
00:07:29.320 | INFO | [Auto_Search] off
00:07:29.320 | INFO | Click (1035,  510) @ MAP_PREPARATION
00:07:30.370 | INFO | Handling 2x book setting, mode=prep.
00:07:30.373 | INFO | Using fleet: [1, 2, 0]
00:07:30.374 | INFO | [Light_orange_line] 0
00:07:30.375 | INFO | Click (1142,  329) @ FLEET_2_CLEAR
00:07:33.443 | INFO | Click (1140,  319) @ FLEET_2_CLEAR
00:07:36.801 | INFO | Click (1134,  318) @ FLEET_2_CLEAR
00:07:40.171 | INFO | Click (1116,  311) @ FLEET_2_CLEAR
00:07:43.532 | INFO | Click (1145,  324) @ FLEET_2_CLEAR
00:07:46.602 | INFO | Click (1128,  321) @ FLEET_2_CLEAR
00:07:49.817 | INFO | Click (1134,  330) @ FLEET_2_CLEAR
00:07:52.945 | INFO | Click (1144,  319) @ FLEET_2_CLEAR
00:07:56.032 | INFO | Click (1127,  338) @ FLEET_2_CLEAR
00:07:59.225 | INFO | Click (1147,  329) @ FLEET_2_CLEAR
00:08:02.393 | INFO | Click (1154,  339) @ FLEET_2_CLEAR
00:08:05.471 | INFO | Click (1139,  313) @ FLEET_2_CLEAR
00:08:08.584 | INFO | Click (1139,  315) @ FLEET_2_CLEAR
00:08:11.709 | INFO | Click (1135,  333) @ FLEET_2_CLEAR
00:08:14.803 | WARNING | Too many click for a button: FLEET_2_CLEAR
00:08:14.803 | WARNING | History click: ['FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR', 'FLEET_2_CLEAR']
00:08:14.803 | WARNING | Too many click for a button: FLEET_2_CLEAR
00:08:14.804 | WARNING | Saving error: ./log/error/1639498094804
00:08:14.896 | WARNING | Game stuck, com.bilibili.azurlane will be restarted in 10 seconds
00:08:14.897 | WARNING | If you are playing by hand, please stop Alas
00:08:14.907 | INFO | Bind task {'WarArchives', 'General', 'Alas'}
00:08:14.907 | INFO | Save config ./config\alas.json, Restart.Scheduler.NextRun=datetime.datetime(2021, 1, 1, 0, 0), Restart.Scheduler.Enable=True
00:08:24.910 | INFO | Scheduler: End task `WarArchives`
00:08:24.910 | INFO | [Server] cn
00:08:24.925 | INFO | Bind task {'General', 'Alas'}
00:08:24.925 | INFO | Pending tasks: ['Restart', 'WarArchives']
00:08:24.926 | INFO | [Task] Restart (Enable, 2021-01-01 00:00:00)
00:08:24.926 | INFO | Bind task {'Restart', 'General', 'Alas'}
00:08:24.926 | INFO | Scheduler: Start task `Restart`
![image](https://user-images.githubusercontent.com/45201662/146035601-eb673088-e335-4fce-8a80-eb232fb218ca.png)

**Comment by LmeSzinc** [comment]
这是困难图，你需要自己配队
推荐功能基本是没人用的

**Comment by BronyaSeele** [comment]
> 这是困难图，你需要自己配队推荐功能基本是没人用的

感谢大佬解疑，大佬不睡觉么，秒回。
