### ISSUE TITLE
余烬信标无法取消

### ISSUE THREAD

**Issue by clarkgap** [LmeSzinc/AzurLaneAutoScript#842]
**Describe the bug**
尽管我没有启用余烬信标功能，alas还是在运行大世界每日时自动打了。

**Log**
10:16:40.302 | INFO | Scheduler: Start task `OpsiDaily`
10:16:40.558 | INFO | +-------------------------------------------------+
10:16:40.558 | INFO | |                    OPSIDAILY                    |
10:16:40.558 | INFO | +-------------------------------------------------+
10:16:40.823 | INFO | ==================== OS INIT ====================
10:16:40.853 | INFO | <<< UI ENSURE >>>
10:16:40.861 | INFO | [UI] page_commission
10:16:40.861 | INFO | Goto page_os
10:16:40.862 | INFO | <<< UI GOTO PAGE_OS >>>
10:16:40.869 | INFO | Click (1241,   29) @ GOTO_MAIN
10:16:42.179 | INFO | Click (1076,  354) @ MAIN_GOTO_CAMPAIGN
10:16:43.285 | INFO | Click ( 728,  422) @ CAMPAIGN_MENU_GOTO_OS
10:16:45.584 | INFO | [MAP_NAME 0.044s] 圣彼得伯格
10:16:45.584 | INFO | Map name processed: 圣彼得伯格
10:16:45.585 | INFO | [Zone] [3|圣彼得伯格|St. Petersburg|ペテルブルク|聖彼得堡]
10:16:45.627 | INFO | [HP]  98%  98%  98%  98%  98%  98%
10:16:45.640 | INFO | [Repair icon] [False, False, False, False, False, False]
10:16:45.640 | INFO | No ship found to be below threshold 40%, continue OS exploration
10:16:45.640 | INFO | In port, skip running first auto search
10:16:45.661 | INFO | [ASH_COLLECT_STATUS 0.020s] 90/100
10:16:45.662 | INFO | ==================== OS FINISH DAILY MISSION ====================
10:16:45.662 | INFO | OS mission enter
10:16:45.670 | INFO | Click ( 964,  675) @ MISSION_ENTER
10:16:46.981 | INFO | Found at least one OS missions.
10:16:47.009 | INFO | Checkout os mission
10:16:47.010 | INFO | Click (1078,  221) @ MISSION_CHECKOUT
10:16:50.985 | INFO | Pinned at mission zone
10:16:50.989 | INFO | Click ( 494,  308) @ ZONE_ENTRANCE
10:16:54.267 | INFO | [MAP_NAME 0.041s] 东南洋脊A-安全海域
10:16:54.268 | INFO | Map name processed: 东南洋脊A
10:16:54.289 | INFO | [Zone] [51|东南洋脊A|Southeast Ocean Ridge A|南東海嶺A|東南洋脊A]
10:16:54.289 | INFO | <<< FLEET SET TO 4 >>>
10:16:54.359 | INFO | It is fleet 4 already
10:16:54.374 | INFO | [ASH_COLLECT_STATUS 0.015s] 90/100
10:16:54.375 | INFO | -------------------- OS AUTO SEARCH --------------------
10:16:54.393 | INFO | Click (1243,  542) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
10:16:57.553 | INFO | Click (1235,  540) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
10:17:00.604 | INFO | Click (1249,  536) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
10:17:03.705 | INFO | Click (1241,  543) @ AUTO_SEARCH_OS_MAP_OPTION_OFF
10:17:13.175 | INFO | [Loading] 11%
10:17:13.175 | INFO | [battle_count] 1
10:17:13.175 | INFO | Auto search combat loading
10:17:13.176 | INFO | Screenshot interval set to 1.0s
10:17:21.093 | INFO | Auto Search combat execute
10:17:27.014 | INFO | Submarine call timer reached
10:17:34.105 | INFO | Screenshot interval set to 0.1s
10:17:34.105 | INFO | Combat end.
10:17:41.555 | INFO | [Loading] 11%
10:17:41.555 | INFO | [battle_count] 2
10:17:41.556 | INFO | Auto search combat loading
10:17:41.556 | INFO | Screenshot interval set to 1.0s
10:17:49.560 | INFO | Auto Search combat execute
10:17:55.450 | INFO | Submarine call timer reached
10:18:02.557 | INFO | Screenshot interval set to 0.1s
10:18:02.557 | INFO | Combat end.
10:18:11.494 | INFO | [Loading] 10%
10:18:11.495 | INFO | [battle_count] 3
10:18:11.495 | INFO | Auto search combat loading
10:18:11.495 | INFO | Screenshot interval set to 1.0s
10:18:19.508 | INFO | Auto Search combat execute
10:18:25.389 | INFO | Submarine call timer reached
10:18:51.495 | INFO | Screenshot interval set to 0.1s
10:18:51.495 | INFO | Combat end.
10:18:56.867 | INFO | [Loading] 5%
10:18:56.868 | INFO | [battle_count] 4
10:18:56.868 | INFO | Auto search combat loading
10:18:56.868 | INFO | Screenshot interval set to 1.0s
10:19:05.908 | INFO | Auto Search combat execute
10:19:11.785 | INFO | Submarine call timer reached
10:19:33.883 | INFO | Screenshot interval set to 0.1s
10:19:33.883 | INFO | Combat end.
10:19:37.396 | INFO | [Loading] 10%
10:19:37.397 | INFO | [battle_count] 5
10:19:37.397 | INFO | Auto search combat loading
10:19:37.397 | INFO | Screenshot interval set to 1.0s
10:19:45.383 | INFO | Auto Search combat execute
10:19:51.315 | INFO | Submarine call timer reached
10:20:18.414 | INFO | Screenshot interval set to 0.1s
10:20:18.414 | INFO | Combat end.
10:20:45.540 | INFO | Click ( 653,  611) @ AUTO_SEARCH_REWARD
10:20:47.054 | INFO | Get OS auto search reward
10:20:47.355 | INFO | OS auto search finished
10:20:47.372 | INFO | [ASH_COLLECT_STATUS 0.017s] 160/100
10:20:47.374 | INFO | Click ( 670,   41) @ ASH_COLLECT_STATUS
10:20:47.910 | INFO | Click ( 570,  515) @ ASH_ENTER_CONFIRM
10:20:49.695 | INFO | <<< UI CLICK >>>
10:20:50.060 | INFO | Click ( 969,  682) @ HELP_ENTER
10:20:50.666 | INFO | Click ( 468,  379) @ HELP_1
10:20:50.846 | INFO | Click ( 664,  364) @ HELP_2
10:20:51.110 | INFO | Click ( 813,  366) @ HELP_3
10:20:51.161 | INFO | <<< UI CLICK >>>
10:20:51.343 | INFO | Click ( 845,  515) @ HELP_CONFIRM
10:20:51.933 | INFO | Ash beacon attack
10:20:52.287 | INFO | [Ash_beacon_hp] 19%
10:20:52.304 | INFO | Combat preparation.
10:20:52.307 | INFO | Click (1103,  682) @ ASH_START
10:20:52.732 | INFO | Click (1135,  675) @ ASH_START
10:20:53.127 | INFO | Click (1136,  670) @ ASH_START
10:20:53.747 | INFO | [Automation] ON
10:20:53.755 | INFO | Click (1107,  677) @ BATTLE_PREPARATION
10:20:54.401 | INFO | [Automation] ON
10:20:54.696 | INFO | [Automation] ON
10:20:54.999 | INFO | [Automation] ON
10:20:55.291 | INFO | [Automation] ON
10:20:55.708 | INFO | [Loading] 12%
10:20:55.709 | INFO | Screenshot interval set to 1.0s
10:21:02.570 | INFO | Combat execute
10:21:08.564 | INFO | Combat auto check timer reached
10:21:08.564 | INFO | Submarine call timer reached
10:22:22.913 | INFO | Click (1098,  661) @ BATTLE_STATUS
10:22:22.964 | INFO | Screenshot interval set to 0.1s
10:22:22.964 | INFO | Combat status
10:22:22.964 | INFO | [expected_end] is_in_ash
10:22:23.507 | INFO | Click (1103,  670) @ BATTLE_STATUS
10:22:24.370 | INFO | Click (1092,  659) @ BATTLE_STATUS
10:22:24.806 | INFO | Combat end.
10:22:25.179 | INFO | [Ash_beacon_hp] 11%
10:22:25.183 | INFO | Combat preparation.
10:22:25.186 | INFO | Click (1142,  680) @ ASH_START
10:22:25.600 | INFO | Click (1139,  663) @ ASH_START
10:22:25.982 | INFO | Click (1127,  653) @ ASH_START
10:22:26.389 | INFO | Click (1142,  682) @ ASH_START
10:22:27.038 | INFO | [Automation] ON
10:22:27.040 | INFO | Click (1137,  662) @ BATTLE_PREPARATION
10:22:27.669 | INFO | [Automation] ON
10:22:28.018 | INFO | [Automation] ON
10:22:28.345 | INFO | [Loading] 13%
10:22:28.346 | INFO | Screenshot interval set to 1.0s
10:22:35.290 | INFO | Combat execute
10:22:40.302 | INFO | Combat auto check timer reached
10:22:40.302 | INFO | Submarine call timer reached
Scheduler stopped.

**Comment by lonelyzerg** [comment]
大世界通用设置里面有自己的余烬信标设置，单独的余烬设置指的应该是支援的三次。
