### ISSUE TITLE
希望增加一个捡弹药的功能

### ISSUE THREAD

**Issue by yankayn** [LmeSzinc/AzurLaneAutoScript#849]
当进入海域仅有一队清理时，若该队伍的弹药量≤3（也可以设置调成无弹药时再捡），则控制去捡弹药。
当有两队时，自己设置是哪一队去捡弹药，或一队捡多少，另一队捡多少。
虽然说起来简单，但因为是纯小白，不太清楚实现的难度，就当提个建议，能优化就最好了。
Thank you for your time

**Comment by LmeSzinc** [comment]
关自律寻敌，就会捡弹药了
