### ISSUE TITLE
如何给Easy_Install-V2.bat设置代理?

### ISSUE THREAD

**Issue by railannad** [LmeSzinc/AzurLaneAutoScript#85]
人在大陆，刚开电脑。
按照[这里](https://github.com/railannad/AzurLaneAutoScript/blob/master/doc/Installation_cn.md)的傻瓜式教程输入"start"之后下载速度只有3K/s，很难受。  而给cmd挂代理的方式是
 `set http_proxy=http://127.0.0.1:PORT
set https_proxy=http://127.0.0.1:PORT
`
请问要怎么把这个功能揉进bat脚本里？ 改如何加代码?

**Comment by LmeSzinc** [comment]
可以将以下代码插入至 Easy_Install-V2.bat 第99行
```
%GIT% config --global http.proxy 'socks5://127.0.0.1:1080'
%GIT% config --global https.proxy 'socks5://127.0.0.1:1080'
```

还有有一个不用代理的骚方法是把 Easy_Install-V2.bat 的第9行
`SET LMESZINC=https://github.com/LmeSzinc/AzurLaneAutoScript.git`
改成
`SET LMESZINC=https://gitee.com/LmeSzinc/AzurLaneAutoScript.git`
我在码云 (gitee) , 上建了个镜像, gitee在国内的速度还是挺快的

**Comment by whoamikyo** [comment]
I will add gitee to Easy install.

**Comment by railannad** [comment]
> 可以将以下代码插入至 Easy_Install-V2.bat 第99行
> 
> ```
> %GIT% config --global http.proxy 'socks5://127.0.0.1:1080'
> %GIT% config --global https.proxy 'socks5://127.0.0.1:1080'
> ```
> 
> 还有有一个不用代理的骚方法是把 Easy_Install-V2.bat 的第9行
> `SET LMESZINC=https://github.com/LmeSzinc/AzurLaneAutoScript.git`
> 改成
> `SET LMESZINC=https://gitee.com/LmeSzinc/AzurLaneAutoScript.git`
> 我在码云 (gitee) , 上建了个镜像, gitee在国内的速度还是挺快的
请问是要这样改吗？
![image](https://user-images.githubusercontent.com/36919867/86680644-5cbc5b80-c031-11ea-84ed-fd9919487210.png)
socks端口是7891应该没错了
![image](https://user-images.githubusercontent.com/36919867/86680699-68a81d80-c031-11ea-8c88-037999ee2f84.png)
然而
![image](https://user-images.githubusercontent.com/36919867/86680762-7bbaed80-c031-11ea-9cf6-52f998afba3a.png)

**Comment by railannad** [comment]
![image](https://user-images.githubusercontent.com/36919867/86683327-056bba80-c034-11ea-9658-562288294a69.png)
我把设置代理的代码删掉，改用方法2


另外我发现我搜了几篇[教程](https://blog.csdn.net/li_magic/article/details/83140986?utm_medium=distribute.pc_relevant.none-task-blog-baidujs-7)  ，照着改了一些内容之后，报错还是和上次一模一样，除非我把整个文件夹删掉重新解压。  
这个bat是会修改并读取某个的配置文件吗？ 是不是必须要修改那个文件才行

**Comment by LmeSzinc** [comment]
问题已通过私聊解决.
解决方法: 在Easy_Install-V2.bat中使用gitee镜像下载

在最后一张截图中, 有两个问题
1. `OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 127.0.0.1:7890` 是本地代理的问题, 与Easy_Install-V2.bat无关
2. uiautomator2 推送 minitouch 至模拟器失败, 手动初始化 uiautomator2, 即可解决, 注意要使用tookit目录下的python
`python -m uiautomator2 init`
