### ISSUE TITLE
UI control中的Scroll类在指挥喵页面效果不理想

### ISSUE THREAD

**Issue by yanyihui** [LmeSzinc/AzurLaneAutoScript#852]
**Describe the bug**
在我写喂猫的时候，使用了Scroll类，由于指挥喵和委托等不一样，他的滑块是一直存在的。
当我想使用将页面托到低的方法（此时滑块是在顶部）会在第一页一直下滑

我使用的是set_top和set_bottm方法
**Screenshots**
![A2_@ Q~FY5HPD{Z%`H2H@ 3](https://user-images.githubusercontent.com/57699016/147391474-13daf64e-4741-4d72-9696-f067f8d7a522.png)
我尝试在终端输出position，current，drag_threshold
此时日志中输出 MEOFFICER_SCROLL_AREA的值是0.17
可以看到两次拖动的区域相差几乎没有

下面给出我测试时的指挥喵页面
![Screenshot_20211226-024624](https://user-images.githubusercontent.com/57699016/147391615-e4e92ca5-8b99-43dc-9976-e4c4de3380ba.png)

下面给出我截取的scroll的asset
![MEOWFFICER_SCROLL_AREA](https://user-images.githubusercontent.com/57699016/147391561-168922c0-071a-4e05-a3b1-0bb801ee59a6.png)

最后，如果有人要开发能读取整个指挥喵列表的功能，需要解决这个问题

**Comment by LmeSzinc** [comment]
Scroll 类对滚动条的识别，实际是 `当前位置 = 滚动条顶部到槽顶部的距离 / (槽长度 - 滚动条长度)`，你给出的图片滚动条长度和槽长度相当，误差就很大，这个解决不了。判断一下当 `滚动条长度 (self.length) / 槽长度 (self.total) > 一定比值` 的时候，不拖拽就可以了
