### ISSUE TITLE
喂养指挥喵的简单实现

### ISSUE THREAD

**Issue by yanyihui** [LmeSzinc/AzurLaneAutoScript#853]
如果你是使用者，我写好的喂养指挥喵功能已经上传到我fork本项目的个人仓库。下面有使用我仓库的教程，纯自用。
如果你是开发者，我将讲一些我开发此功能时遇到的问题，说不定对你有帮助，坐等新dalao自己撸一个喂养指挥喵。请跳过下面的教程看结论。

### 写给使用者
本功能必须配合筛选器将你要喂的猫放到第一页，筛选后范围内的猫数量不能大于12
使用我的仓库的方法：
**注意，将仓库改成我的，更新必须等到我合并群主的新提交之后**
大家要使用的画应该有改过源，项目路径下config文件中的deploy.yaml
其实很简单，将源改成我的github仓库，分支改成meowfficer

仓库：Repository: https://github.com/yanyihui/AzurLaneAutoScript.git
分支：Branch: meowfficer
阿里镜像
仓库：Repository: https://gitee.com/yanyihui2/AzurLaneAutoScript.git
分支：Branch: meowfficer
下面给出功能页的截图，如果出现说明你安装成功。
![O7JNVS2M } CF()@E}}SN}2](https://user-images.githubusercontent.com/57699016/147391837-2ecfbe24-d2a9-4c46-8262-7e48f5b84592.png)
![FSBR%9DACWT5LPU3`BA`T56](https://user-images.githubusercontent.com/57699016/147391838-d0059c50-416a-4b46-8670-1c78739bc32a.png)

### 写给开发者
由于群主的需求是要能读取所有猫，根据序号找猫。下面遇到的几个问题需要解决。

#### 去重问题
我写的时候模仿项目作者的commission.py中的方法。流程差不多如下

1. 找到所有猫的列表存入list
2. 获取用户想要的序号，目标猫，算出它在list中的位置
3. 从头翻一遍列表，找到list位置对应的猫选中并喂养

我通过不断翻页，来找到每一行的指挥喵，把每一行的指挥喵当作一组添加到列表。
这样的读取是没法去重的，因为可能很多行的指挥喵ui是一样的，等级都是1，名字也一样。原因如下：

- scroll每次翻页并不是完全精准，导致我两次翻页可能读取到的猫数量都不一样，可能有一行猫被我算了两次
- 最后一行距离底部的背景色像素宽度是6个像素，因此找平峰的时候必须设置峰值宽度在6以内。设置的太小会导致重复读取概率很大。如果能解决去重问题，那么重复读取也没关系，相当于问题解决了。
- 两行猫的背景色像素宽度在17以上，是因为一行猫的宽度是在117像素到124像素之间，就是说猫不一样高。虽然设置较高波峰宽度可以降低重复读取的概率，但是这样不可能读取到最后一行猫。这样肯定是不行的

#### 第一页翻页问题
如果要写读取所有猫，必须解决翻页问题。
如果用户的猫在3行以上，那么可以愉快的使用scroll方法。
可是如果猫在3行以内，第一页是没法翻页的，具体问题可以看我提交的bug
#852 

但是我是有解决思路的。可以Ocr右下角的猫窝库存：
![GTDWN_T3H1 D{Q(4OQL4K X](https://user-images.githubusercontent.com/57699016/147392181-04fe9f3c-9d1c-43b1-8a64-cdecdb6fafae.png)

如果发现已经有的猫数量在12以内，则采用直接在第一页定点搜索的方法，就是我已经写好的select函数。
如果数量在12以上就采用翻页读取的办法。

由于本人技术能力太差，导致我不能解决这两个开发中遇到的问题，我的开发到此为止。
本身我的目标就是解决我个人的喂猫问题，也算是我自己够用了，顺便给你们用来看看。
如果有大佬能写出符合群主的需求，并pr成功，我也会很高兴用回群主的仓库，毕竟更新方便很多。

**Comment by yanyihui** [comment]
如果在我写的功能里面发现bug就不要去烦群主了，在这里留言我尽量解决

**Comment by LmeSzinc** [comment]
另一个实现已合并 #923
