### ISSUE TITLE
Receive META rewards | 收取META奖励

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#863]
Yes! I am a lazy guy who thinks collecting META rewards is a waste of my life, even though it only requires several clicks every few days. I would like Alas to do that. This feature is easy to implement which can refer the battle pass module, so I tagged this LOW-priority. Feel free to participate in Alas development, you can consider this as a quick start.

---

对，我就是一条懒狗，哪怕收取META奖励只需要每几天点几次，我都觉得是在浪费人生。希望 Alas 可以帮我做这件事。
这个功能比较简单，可以参考大月卡模块，所以我把它标记为低优先级。欢迎参与 Alas 的开发，你可以把这个当成是快速入门。

**Comment by julystone** [comment]
加个help wanted标签呗~
