### ISSUE TITLE
Move submarines and call submarines at BOSS only | 移动潜艇和仅在BOSS点召唤潜艇

### ISSUE THREAD

**Issue by LmeSzinc** [LmeSzinc/AzurLaneAutoScript#864]
Hopping to move submarines and call submarines at boss only, because it's hard to clear 14-4 boss without them. A difficult feature it is and you must be familar with the map module of Alas, so probably can only be done by me. The main hope of this PR is to collect some ideas.
The hunting range of submarine is diverse, geme devs are fanatical about drawing patterns and adding poor memes on hunting ranges. It's hard to ensure boss is in the hunting range, so the current plan is to add such options:
- **Submarine Mode**: do_not_use / hunt_only / boss_only / every_combat
- **Move subs to within X range of the boss**: 0 / 1 / 2
  Effective only for boss_only. Move subs to X grid next to the boss, before boss battle. Need to confirm manully that the submarine hunting range includes up, down, left, and right X grids.
```
    X
  X X X
X X X X X
  X X X
    X
```

---

14-4 BOSS不叫潜艇的话会很难打，希望能增加移动潜艇的功能。很难的功能，你需要熟悉 Alas 的地图模块，可能只能由我来做。这个PR主要希望是收集一些想法。
潜艇狩猎范围五花八门，策划特喜欢在狩猎范围上画图案玩烂梗，很难保证潜艇能覆盖到boss，目前的打算是增加这样的选项：
- **潜艇出击方案**：不使用 / 仅狩猎 / 仅BOSS战 / 每战出击
- **移动潜艇至 BOSS 的 X 格范围内**：0 / 1 / 2
  仅BOSS战出击时生效，BOSS战前将潜艇移动至BOSS的X格范围以内，需要自行确认潜艇狩猎范围包含上下左右X格
```
    X
  X X X
X X X X X
  X X X
    X
```

**Comment by SF-monkey** [comment]
能否添加个：仅在打3星舰队或Boss出击

**Comment by yanyihui** [comment]
如果实在很难兼容所有的潜艇，或者一定需要用户来确认，希望能独立一个U522模式，只打boss一战。
