### ISSUE TITLE
使用uu加速器后出现以下提示“远程主机强迫关闭了一个现有的连接”

### ISSUE THREAD

**Issue by leohyh** [LmeSzinc/AzurLaneAutoScript#866]
**Describe the bug**
未使用加速器时alas可以正常运行。使用uu加速器打开雷电模拟器后，再打开alas就会停在这个提示“远程主机强迫关闭了一个现有的连接”

**Log**
"E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript
+----------------------------------------------------------+
|                    Show deploy config                    |
+----------------------------------------------------------+
Repository: https://github.com/LmeSzinc/AzurLaneAutoScript
Branch: master
GitExecutable: ./toolkit/Git/mingw64/bin/git.exe
GitProxy:
AutoUpdate: true
KeepLocalChanges: false
PythonExecutable: ./toolkit/python.exe
PypiMirror:
InstallDependencies: true
AdbExecutable: ./toolkit/Lib/site-packages/adbutils/binaries/adb.exe
ReplaceAdb: true
AutoConnect: true
InstallUiautomator2: true
WebuiPort: 22267
Language: zh-CN
Theme: default
CDN: false
+---------------------------------------------------+
|                    Update Alas                    |
+---------------------------------------------------+
==================== Git Init ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/.git/
[ success ]
==================== Set Git Proxy ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ failed ], error_code: 5
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ failed ], error_code: 5
==================== Set Git Repository ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://github.com/LmeSzinc/AzurLaneAutoScript
[ success ]
==================== Fetch Repository Branch ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" fetch origin master
From https://github.com/LmeSzinc/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
[ success ]
==================== Pull Repository Branch ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at 342bed62 Opt: Show minitouch init messages
[ success ]
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
From https://github.com/LmeSzinc/AzurLaneAutoScript
 * branch              master     -> FETCH_HEAD
Already up to date.
[ success ]
==================== Show Version ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/Git/mingw64/bin/git.exe" log --no-merges -1
error: cannot spawn less: No such file or directory
commit 342bed6255fbd8b2061ae3c8787ed65488b64a5c (HEAD -> master, origin/master)
Author: LmeSzinc <37934724+LmeSzinc@users.noreply.github.com>
Date:   Tue Jan 4 01:21:16 2022 +0800

    Opt: Show minitouch init messages
[ success ]
+-----------------------------------------------------------+
|                    Update Dependencies                    |
+-----------------------------------------------------------+
==================== Check Python ====================
"E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/python.exe" --version
Python 3.7.6
[ success ]
==================== Update Dependencies ====================
""E:/ALAS/AlasApp_0.3.3/AzurLaneAutoScript/toolkit/python.exe" -m pip" install -r requirements.txt --disable-pip-version-check
Requirement already satisfied: adbutils==0.11.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 7)) (0.11.0)
Requirement already satisfied: aiofiles==0.7.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: anyio==1.3.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: apkutils2==1.0.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (1.0.0)
Requirement already satisfied: asgiref==3.4.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (3.4.1)
Requirement already satisfied: async-generator==1.10 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (1.10)
Requirement already satisfied: cached-property==1.5.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.5.2)
Requirement already satisfied: certifi==2021.5.30 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (2021.5.30)
Requirement already satisfied: chardet==3.0.4 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (3.0.4)
Requirement already satisfied: cigam==0.0.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (0.0.3)
Requirement already satisfied: click==8.0.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (8.0.1)
Requirement already satisfied: cnocr==1.2.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (1.2.2)
Requirement already satisfied: colorama==0.4.4 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.4.4)
Requirement already satisfied: cycler==0.10.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (0.10.0)
Requirement already satisfied: decorator==5.1.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (5.1.0)
Requirement already satisfied: deprecated==1.2.13 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (1.2.13)
Requirement already satisfied: deprecation==2.1.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (2.1.0)
Requirement already satisfied: filelock==3.3.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (3.3.0)
Requirement already satisfied: gluoncv==0.6.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (0.6.0)
Requirement already satisfied: graphviz==0.8.4 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (0.8.4)
Requirement already satisfied: h11==0.12.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (0.12.0)
Requirement already satisfied: httptools==0.2.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (0.2.0)
Requirement already satisfied: idna==2.6 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (2.6)
Requirement already satisfied: imageio==2.9.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (2.9.0)
Requirement already satisfied: importlib-metadata==4.8.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (4.8.1)
Requirement already satisfied: inflection==0.5.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (0.5.1)
Requirement already satisfied: jellyfish==0.8.8 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (0.8.8)
Requirement already satisfied: kiwisolver==1.3.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (1.3.2)
Requirement already satisfied: logzero==1.7.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (1.7.0)
Requirement already satisfied: lxml==4.6.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (4.6.3)
Requirement already satisfied: lz4==3.1.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (3.1.3)
Requirement already satisfied: matplotlib==3.4.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (3.4.3)
Requirement already satisfied: mxnet==1.6.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (1.6.0)
Requirement already satisfied: networkx==2.6.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (2.6.3)
Requirement already satisfied: numpy==1.16.6 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.16.6)
Requirement already satisfied: opencv-python==4.5.3.56 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (4.5.3.56)
Requirement already satisfied: packaging==20.9 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (20.9)
Requirement already satisfied: pillow==8.3.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (8.3.2)
Requirement already satisfied: portalocker==2.3.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (2.3.2)
Requirement already satisfied: prettytable==2.2.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (2.2.1)
Requirement already satisfied: progress==1.6 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (1.6)
Requirement already satisfied: py==1.10.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (1.10.0)
Requirement already satisfied: pyelftools==0.27 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (0.27)
Requirement already satisfied: pyparsing==2.4.7 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (2.4.7)
Requirement already satisfied: python-dateutil==2.8.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (2.8.2)
Requirement already satisfied: python-dotenv==0.19.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (0.19.0)
Requirement already satisfied: pywavelets==1.1.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (1.1.1)
Requirement already satisfied: pywebio==1.5.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (1.5.0)
Requirement already satisfied: pywin32==301 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (301)
Requirement already satisfied: pyyaml==5.4.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (5.4.1)
Requirement already satisfied: requests==2.18.4 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (2.18.4)
Requirement already satisfied: retry==0.9.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (0.9.2)
Requirement already satisfied: retrying==1.3.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (1.3.3)
Requirement already satisfied: scikit-image==0.16.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (0.16.2)
Requirement already satisfied: scipy==1.4.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (1.4.1)
Requirement already satisfied: six==1.16.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (1.16.0)
Requirement already satisfied: sniffio==1.2.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (1.2.0)
Requirement already satisfied: starlette==0.14.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (0.14.2)
Requirement already satisfied: tornado==6.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (6.1)
Requirement already satisfied: tqdm==4.62.3 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (4.62.3)
Requirement already satisfied: typing-extensions==3.10.0.2 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (3.10.0.2)
Requirement already satisfied: ua-parser==0.10.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (0.10.0)
Requirement already satisfied: uiautomator2==2.16.7 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (2.16.7)
Requirement already satisfied: urllib3==1.22 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (1.22)
Requirement already satisfied: user-agents==2.2.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (2.2.0)
Requirement already satisfied: uvicorn[standard]==0.15.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (0.15.0)
Requirement already satisfied: watchgod==0.7 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (0.7)
Requirement already satisfied: wcwidth==0.2.5 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (0.2.5)
Requirement already satisfied: websockets==10.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (10.0)
Requirement already satisfied: whichcraft==0.6.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (0.6.1)
Requirement already satisfied: wrapt==1.13.1 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (1.13.1)
Requirement already satisfied: xmltodict==0.12.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (0.12.0)
Requirement already satisfied: zipp==3.6.0 in e:\alas\alasapp_0.3.3\azurlaneautoscript\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (3.6.0)
[ success ]
+---------------------------------------------------------+
|                    Start ADB service                    |
+---------------------------------------------------------+
==================== Replace ADB ====================
adb.exe: failed to check server version: protocol fault (couldn't read status): connection reset
Emulator Nemu found, instances: ['127.0.0.1:7555']
Replacing E:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe
E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\Lib\site-packages\adbutils\binaries\adb.exe is same as E:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe, skip
adb.exe: failed to check server version: protocol fault (couldn't read status): connection reset
Devices: []
error: protocol fault (couldn't read status): connection reset
adb.exe: failed to check server version: protocol fault (couldn't read status): connection reset
Devices: []
==================== Uiautomator2 Init ====================
Traceback (most recent call last):
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\deploy\installer.py", line 226, in <module>
    Installer().install()
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\deploy\installer.py", line 222, in install
    self.adb_install()
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\deploy\installer.py", line 210, in adb_install
    for device in adbutils.adb.iter_device():
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 445, in iter_device
    c.check_okay()
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 166, in check_okay
    data = self.read_string(4)
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 142, in read_string
    data = self.read(n).decode()
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 123, in read
    return self._read_fully(n)
  File "E:\ALAS\AlasApp_0.3.3\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py", line 131, in _read_fully
    chunk = self.conn.recv(t)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by LmeSzinc** [comment]
在你的模拟器里的设置中，打开ADB

**Comment by Kur0u0** [comment]
我也出现了这个问题，关闭掉外置的uu加速器就可以解决了，似乎只能这样

**Comment by dwtaiden** [comment]
有一个解决方法，UU加速器进设置-专项优化关闭TUN网卡兼容模式，在加速游戏时，选择路由模式节点，之后重启alas和模拟器
