### ISSUE TITLE
隐秘海域太多 STORY_SKIP 导致游戏重启

### ISSUE THREAD

**Issue by hephooey** [LmeSzinc/AzurLaneAutoScript#869]
隐秘海域处理能源矩阵会连续 skip 8 次以上，在侵蚀度 5-6 的海域加上伏击和增援的提示几乎必定触发GameTooManyClickError，然后就重启游戏了。

**Comment by LmeSzinc** [comment]
需要log和游戏截图

单看描述，我猜你没有在游戏设置里打开减少TB引导

**Comment by hephooey** [comment]
a, 抱歉不知道有这个选项，选上之后好多了。
