### ISSUE TITLE
mumu模拟器9截图无法正常工作

### ISSUE THREAD

**Issue by 31415926loli** [LmeSzinc/AzurLaneAutoScript#871]
01:24:45.177 | INFO | connected to 127.0.0.1:7555
01:24:46.048 | INFO | [Screen_size] 1280x720
01:24:46.052 | CRITICAL | Received pure black screenshots from emulator, color: [0.00013889 0.00038086 0.00065972]
01:24:46.052 | CRITICAL | Screenshot method `ADB` may not work on emulator `127.0.0.1:7555`
01:24:46.052 | CRITICAL | Please use other screenshot methods

另外两个截图方案均无法工作，都是黑屏

**Comment by LmeSzinc** [comment]
那就不用 mumu，建议使用夜神国际版或蓝叠国际版

**Comment by LmeSzinc** [comment]
稍微去了解了一下，这是mumu9的专属问题，所以只能通过换模拟器解决
