### ISSUE TITLE
自动使用大世界效能样本

### ISSUE THREAD

**Issue by HarutoEip** [LmeSzinc/AzurLaneAutoScript#877]
反正也不是什么很重要的功能，就是经常打到月底才发现仓库里10+的这个没开
![image](https://patchwiki.biligame.com/images/blhx/0/0b/eo2t76n4bo4ux96h8hjjf247uygh5s8.jpg)
略显强迫症Orz

**Comment by julystone** [comment]
应该不难吧，大世界本来就有自动打开海域坐标的功能，识别这个适应性也有了。
