### ISSUE TITLE
是否考虑做个商船护航的功能呢

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#879]
观察了下，几次的护航好像地图内容是固定的
但是我只提取过活动地图，商船的地图怎么弄不太会呀

**Comment by LmeSzinc** [comment]
897d179bbd9495d4471a3051994df28f4357b08b

加了简单的进入后就撤退，拿70%奖励。
搞骚走位0战拿全奖励，可以做但是我懒得做，如果这个玩法常驻，就考虑做
