### ISSUE TITLE
日服无法使用高效作战书

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#880]
尝试在12-4出击时使用高效作战书，发现出现高效作战书对话框时不会点击确定

![2022-01-14_15-04-30-775007](https://user-images.githubusercontent.com/70339606/149468044-dcbc9824-1258-4f08-a6fc-58e4a06d628a.png)
[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7868577/log.txt)

**Comment by railzy** [comment]
可能是本地第一次使用时会弹出提示 ~可以暂时先手动确认一次~
