### ISSUE TITLE
更新后报错 Invalid argument

### ISSUE THREAD

**Issue by AJCheng726** [LmeSzinc/AzurLaneAutoScript#881]
更新后没有修改配置，点击启动出现了下面的报错：

![image](https://user-images.githubusercontent.com/31361978/149474185-54162ecc-37be-4455-8385-508e32bcf76d.png)

**Comment by 18870** [comment]
尝试步骤 3,5,6
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/876#issuecomment-1011963386

**Comment by AJCheng726** [comment]
> 尝试步骤 3,5,6 [#876 (comment)](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/876#issuecomment-1011963386)

3很有效，谢谢
