### ISSUE TITLE
停止调度器导致alas崩溃

### ISSUE THREAD

**Issue by freesrz93** [LmeSzinc/AzurLaneAutoScript#883]
**Describe the bug**
我在服务器（CentOS 7.9.2009）上部署了alas并可以正常运行，但是当点击控制页面“停止”按钮后网页即失去连接，使用top发现alas相关进程都已终止，bash输出如下

[nohup.log](https://github.com/LmeSzinc/AzurLaneAutoScript/files/7874682/nohup.log)

PC未见此问题，不知是什么原因所致

**Comment by 18870** [comment]
> 2022-01-15 17:18:10.402 | ERROR | Invalid isoformat string: ''

已修复


> 2022-01-15 17:18:19.133 | INFO | Alas [alas] stopped
> INFO:     Shutting down

https://github.com/LmeSzinc/AzurLaneAutoScript/blob/96dbc2c52631925843fdd2d0dbddf87f9393fa77/module/webui/process_manager.py#L40-L45

似乎 `Process.terminate()` 并没有成功杀死进程
我没有服务器环境可以进行测试，这里写了一段测试代码
```py
import multiprocessing
import time

def main():
    print(1)
    time.sleep(2)
    print(3)

if __name__ == '__main__':
    process = multiprocessing.Process(target=main)
    process.start()
    time.sleep(1)
    print(2)
    process.terminate()
    time.sleep(2)
    print(4)
```

正确运行结果应该是输出124，如果进程没有被杀死会输出1234
