### ISSUE TITLE
寄了，账号异常

### ISSUE THREAD

**Issue by qbs233** [LmeSzinc/AzurLaneAutoScript#887]
在模拟器上一直挂着，然后账号异常了。。然后恰好号的绑定邮箱被注销了。😥😥

**Comment by LmeSzinc** [comment]
需要提供详细的信息

经过简单的搜索，帐号异常是因为没绑定手机号+异地登录
https://bbs.nga.cn/read.php?tid=30281023
~~连小编也说是真的~~
![2022-01-19_12-25-22_GoU9l43mfB_803_159](https://user-images.githubusercontent.com/37934724/150063916-3d813185-8870-4000-9392-b4ba63231f05.png)
