### ISSUE TITLE
科研统计的数据异常？

### ISSUE THREAD

**Issue by bananaheaven** [LmeSzinc/AzurLaneAutoScript#888]
大大你好，今天我想用[azur-stats.lyoko.io](https://azur-stats.lyoko.io/)掉落数据来做科研规划的时候发现的问题。
首先我希望我的认知没有出错就是金船和彩船定向一定会出蓝图，那么定向掉落的概率就应该全是1，但是我发现彩船定向的掉落概率全都小于1
![QQ截图20220118132632](https://user-images.githubusercontent.com/61352935/149876094-15179a64-ad4a-4877-857a-23d9f585e701.png)
一开始我以为是我认知出错了，但是我去查看金船的定向概率确实全都等于1
![QQ截图20220118132755](https://user-images.githubusercontent.com/61352935/149876229-e7989d60-7353-49f6-b2e4-3fc627d215e1.png)

**Comment by LmeSzinc** [comment]
翻了一下数据库，是有的埃吉尔蓝图没识别出来，给了一个自增ID：242

![2022-01-20_18-15-27_fqqw0YcJZp_1603_925](https://user-images.githubusercontent.com/37934724/150319459-5bc81289-60c3-4f73-995c-4f9ae7898a29.png)

生成的242号物品是一个带闪光的埃吉尔蓝图

![242](https://user-images.githubusercontent.com/37934724/150319788-bc9013eb-1e25-4768-9de6-f902bf9d88c2.png)

统计的后端 [azur-stats-server](https://github.com/LmeSzinc/azur-stats-server) 已经很久没维护过了，我过几天把这些新的物品标记一下就好了

![2022-01-20_18-21-37_Z9rbj8dQcy_2301_1121](https://user-images.githubusercontent.com/37934724/150320473-1795d082-c115-4edb-bd59-2f436af5df45.png)

**Comment by bananaheaven** [comment]
好的，知道了，辛苦大佬了

**Comment by LmeSzinc** [comment]
已修复，现在五期的统计也有了
