### ISSUE TITLE
Alas发生错误是为啥

### ISSUE THREAD

**Issue by Healerpaper** [LmeSzinc/AzurLaneAutoScript#892]
![image](https://user-images.githubusercontent.com/98081701/150294281-14db2031-ef93-48b3-bfd0-225d716aed3c.png)

**Comment by LmeSzinc** [comment]
> bad port number '75555" in '127.0. 0.1:75555'

端口号的范围是 0~65535，75555 不是一个正确的端口号，我猜你想使用的是 7555
