### ISSUE TITLE
其他商店的核心商店功能

### ISSUE THREAD

**Issue by Rexistflight** [LmeSzinc/AzurLaneAutoScript#909]
### 你的功能请求是否与问题有关？

其他商店功能现在会在核心商店里买些不想买的物品，不知是不是版本问题。

### 解决方案

整一个可以选择是否使用核心商店功能？

**Comment by LmeSzinc** [comment]
> 其他商店功能现在会在核心商店里买些不想买的物品，不知是不是版本问题。

详细描述你的问题，在核心商店里买了什么，你又不想买什么，以及为什么会觉得是版本问题

**Comment by Rexistflight** [comment]
![IMG_20220129_105429](https://user-images.githubusercontent.com/98587261/151644572-a088bef5-c88a-4afb-b21a-76ac3af62d62.jpg)
像这样子，然后就会在核心商店默认买了心智2

**Comment by HugeFaker** [comment]
①出Dào作，②女教Shī，③搜查Guān，④女医Shēng，⑤家政Fù，⑥禁Duàn介护，⑦夫目前Fàn，⑧不Lún，⑨人Qī，(10)风Sú，11)浓厚接Wěn，12)上司QīnFàn，13)痉Luān，14)中Chū，15)野外Lù出，16)温Quán，17)痴Hàn，18)一泊二Rī，19)Jǘ花，20)童贞，21)女子校生，22)凌Rǔ，23)女同，24)美TǔiWM：Bù兵

**Comment by Rexistflight** [comment]
我在这里看了一段时间感觉大家都没有遇到这个问题所以会不会是版本问题😂

**Comment by LmeSzinc** [comment]
你核心商店过滤器填的是 `Array`，对应心智2，Alas买了心智2，没有问题
对于大部分人来说，核心商店的心智1和心智2都是必买的，如果你不想买可以填一个空格
