### ISSUE TITLE
adb问题

### ISSUE THREAD

**Issue by pengchao520** [LmeSzinc/AzurLaneAutoScript#911]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

启动alas管理器会启动adb.exe，但我需要进入管理器主动关闭adb.exe才能正常运行alas。
所使用的模拟器为雷电
模拟器内adb设置为本地链接
AdbError: unknown host service

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by LmeSzinc** [comment]
需要提供 log，不能只有一行

**Comment by pengchao520** [comment]
INFO     13:34:05.886 │ [Server] cn                                                
INFO     13:34:05.903 │ Bind task {'Alas', 'General'}                              
═══════════════════════════════════════════════════════════════════════════════════
                                       START                                       
═══════════════════════════════════════════════════════════════════════════════════
INFO     13:34:05.925 │ Start scheduler loop: alas                                 
INFO     13:34:05.927 │ [Server] cn                                                
INFO     13:34:05.949 │ Bind task {'Alas', 'General'}                              
INFO     13:34:05.952 │ Pending tasks: ['Restart', 'Exercise', 'Dorm', 'Guild',    
         'Shipyard', 'Hard', 'OpsiAshAssist', 'RaidDaily', 'WarArchives', 'Main']  
INFO     13:34:05.954 │ [Task] Restart (Enable, 2022-01-31 00:00:00)               
INFO     13:34:05.958 │ Bind task {'Alas', 'Restart', 'General'}                   
INFO     13:34:05.959 │ Skip task `Restart` at scheduler start                     
INFO     13:34:05.961 │ Delay task `Restart` to 2022-02-01 00:00:00                
         (server_update='00:00')                                                   
INFO     13:34:05.971 │ Bind task {'Alas', 'Restart', 'General'}                   
INFO     13:34:05.975 │ Save config ./config\alas.json,                            
         Restart.Scheduler.NextRun=datetime.datetime(2022, 2, 1, 0, 0)             
INFO     13:34:05.981 │ [Server] cn                                                
INFO     13:34:05.998 │ Bind task {'Alas', 'General'}                              
INFO     13:34:06.001 │ Pending tasks: ['Exercise', 'Dorm', 'Guild', 'Shipyard',   
         'Hard', 'OpsiAshAssist', 'RaidDaily', 'WarArchives', 'Main']              
INFO     13:34:06.004 │ [Task] Exercise (Enable, 2022-01-30 12:00:00)              
INFO     13:34:06.007 │ Bind task {'Exercise', 'General', 'Alas'}                  
INFO     13:34:06.009 │ Scheduler: Start task `Exercise`                           
INFO     13:34:07.883 │ <<< DEVICE >>>                                             
ERROR    13:34:10.147 │ unknown host service                                       
         ╭────────────────── Traceback (most recent call last) ───────────────────╮
         │                                                                        │
         │ D:\AzurLaneAutoScript\alas.py:45 in device                             │
         │                                                                        │
         │    43 │   │   try:                                                     │
         │    44 │   │   │   from module.device.device import Device              │
         │ ❱  45 │   │   │   device = Device(config=self.config)                  │
         │    46 │   │   │   return device                                        │
         │    47 │   │   except RequestHumanTakeover:                             │
         │                                                                        │
         │ ╭──────────────────────────── locals ─────────────────────────────╮    │
         │ │ Device = <class 'module.device.device.Device'>                  │    │
         │ │      e = AdbError('unknown host service')                       │    │
         │ │   self = <alas.AzurLaneAutoScript object at 0x000001C31F4091C8> │    │
         │ ╰─────────────────────────────────────────────────────────────────╯    │
         │ D:\AzurLaneAutoScript\module\device\connection.py:33 in __init__       │
         │                                                                        │
         │    31 │   │   │   self.serial = self.find_bluestacks5_hyperv(self.seri │
         │    32 │   │                                                            │
         │ ❱  33 │   │   self.device = self.connect(self.serial)                  │
         │    34 │   │   # Set from 3min to 7days                                 │
         │    35 │   │   self.device.set_new_command_timeout(604800)              │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ config = <module.config.config.AzurLaneConfig object at            │ │
         │ │          0x000001C310055D48>                                       │ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x000001C31F48AB08>                                       │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\module\device\connection.py:187 in connect       │
         │                                                                        │
         │   185 │   │   self._adb_connect(serial)                                │
         │   186 │   │   try:                                                     │
         │ ❱ 187 │   │   │   device = u2.connect(serial)                          │
         │   188 │   │   │   return device                                        │
         │   189 │   │   except AssertionError:                                   │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │   self = <module.device.device.Device object at                    │ │
         │ │          0x000001C31F48AB08>                                       │ │
         │ │ serial = 'emulator-5554'                                           │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:1880 in connect                                                     │
         │                                                                        │
         │   1878 │   if wifi_addr:                                               │
         │   1879 │   │   return connect_wifi(addr)                               │
         │ ❱ 1880 │   return connect_usb(addr)                                    │
         │   1881                                                                 │
         │   1882                                                                 │
         │                                                                        │
         │ ╭────────── locals ───────────╮                                        │
         │ │      addr = 'emulator-5554' │                                        │
         │ │ wifi_addr = None            │                                        │
         │ ╰─────────────────────────────╯                                        │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:1921 in connect_usb                                                 │
         │                                                                        │
         │   1919 │   │   device = adbutils.adb.device()                          │
         │   1920 │   │   serial = device.serial                                  │
         │ ❱ 1921 │   return Device(serial)                                       │
         │   1922                                                                 │
         │   1923                                                                 │
         │                                                                        │
         │ ╭───────── locals ─────────╮                                           │
         │ │   init = False           │                                           │
         │ │ serial = 'emulator-5554' │                                           │
         │ ╰──────────────────────────╯                                           │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:248 in __init__                                                     │
         │                                                                        │
         │    246 │   │                                                           │
         │    247 │   │   # fallback to wifi if USB disconnected                  │
         │ ❱  248 │   │   wlan_ip = self.wlan_ip                                  │
         │    249 │   │   if wlan_ip:                                             │
         │    250 │   │   │   self._atx_agent_url = f"http://{wlan_ip}:7912"      │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │          self = <uiautomator2.Device object at 0x000001C32F3BAF88> │ │
         │ │ serial_or_url = 'emulator-5554'                                    │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:431 in wlan_ip                                                      │
         │                                                                        │
         │    429 │   @property                                                   │
         │    430 │   def wlan_ip(self):                                          │
         │ ❱  431 │   │   ip = self.http.get("/wlan/ip").text.strip()             │
         │    432 │   │   if not re.match(r"\d+\.\d+\.\d+\.\d+", ip):             │
         │    433 │   │   │   return None                                         │
         │                                                                        │
         │ ╭───────────────────────── locals ──────────────────────────╮          │
         │ │ self = <uiautomator2.Device object at 0x000001C32F3BAF88> │          │
         │ ╰───────────────────────────────────────────────────────────╯          │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\requests\sessions.py:5 │
         │ 21 in get                                                              │
         │                                                                        │
         │   519 │   │                                                            │
         │   520 │   │   kwargs.setdefault('allow_redirects', True)               │
         │ ❱ 521 │   │   return self.request('GET', url, **kwargs)                │
         │   522 │                                                                │
         │   523 │   def options(self, url, **kwargs):                            │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ kwargs = {'allow_redirects': True}                                 │ │
         │ │   self = <uiautomator2._AgentRequestSession object at              │ │
         │ │          0x000001C32F799BC8>                                       │ │
         │ │    url = '/wlan/ip'                                                │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:214 in request                                                      │
         │                                                                        │
         │    212 │   │                                                           │
         │    213 │   │   # fix atx-agent and request again                       │
         │ ❱  214 │   │   self.__client._prepare_atx_agent()                      │
         │    215 │   │   url = self.__client.path2url(url)                       │
         │    216 │   │   return super().request(method, url, **kwargs)           │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ __class__ = <class 'uiautomator2._AgentRequestSession'>            │ │
         │ │    kwargs = {'allow_redirects': True}                              │ │
         │ │    method = 'GET'                                                  │ │
         │ │     retry = True                                                   │ │
         │ │      self = <uiautomator2._AgentRequestSession object at           │ │
         │ │             0x000001C32F799BC8>                                    │ │
         │ │       url = '/wlan/ip'                                             │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:298 in _prepare_atx_agent                                           │
         │                                                                        │
         │    296 │   │   │   raise RuntimeError("USB device %s is offline" % sel │
         │    297 │   │   logger.debug("device %s is online", self._serial)       │
         │ ❱  298 │   │   version_url = self.path2url("/version")                 │
         │    299 │   │   try:                                                    │
         │    300 │   │   │   version = requests.get(version_url, timeout=3).text │
         │                                                                        │
         │ ╭───────────────────────── locals ──────────────────────────╮          │
         │ │   _d = AdbDevice(serial=emulator-5554)                    │          │
         │ │ self = <uiautomator2.Device object at 0x000001C32F3BAF88> │          │
         │ ╰───────────────────────────────────────────────────────────╯          │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:281 in path2url                                                     │
         │                                                                        │
         │    279 │   │   if re.match(r"^(ws|http)s?://", path):                  │
         │    280 │   │   │   return path                                         │
         │ ❱  281 │   │   return urlparse.urljoin(self._get_atx_agent_url(), path │
         │    282 │                                                               │
         │    283 │   @property                                                   │
         │                                                                        │
         │ ╭───────────────────────── locals ──────────────────────────╮          │
         │ │ path = '/version'                                         │          │
         │ │ self = <uiautomator2.Device object at 0x000001C32F3BAF88> │          │
         │ ╰───────────────────────────────────────────────────────────╯          │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\uiautomator2\__init__. │
         │ py:263 in _get_atx_agent_url                                           │
         │                                                                        │
         │    261 │   │   try:                                                    │
         │    262 │   │   │   lport = self._adb_device.forward_port(              │
         │ ❱  263 │   │   │   │   7912)  # this method is so fast, only take 0.2m │
         │    264 │   │   │   return f"http://127.0.0.1:{lport}"                  │
         │    265 │   │   except adbutils.AdbError as e:                          │
         │                                                                        │
         │ ╭───────────────────────── locals ──────────────────────────╮          │
         │ │ self = <uiautomator2.Device object at 0x000001C32F3BAF88> │          │
         │ ╰───────────────────────────────────────────────────────────╯          │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py:5 │
         │ 97 in forward_port                                                     │
         │                                                                        │
         │   595 │   │   if isinstance(remote, int):                              │
         │   596 │   │   │   remote = "tcp:" + str(remote)                        │
         │ ❱ 597 │   │   for f in self.forward_list():                            │
         │   598 │   │   │   if f.serial == self._serial and f.remote == remote a │
         │   599 │   │   │   │   │   "tcp:"):                                     │
         │                                                                        │
         │ ╭───────────────── locals ─────────────────╮                           │
         │ │ remote = 'tcp:7912'                      │                           │
         │ │   self = AdbDevice(serial=emulator-5554) │                           │
         │ ╰──────────────────────────────────────────╯                           │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py:3 │
         │ 80 in forward_list                                                     │
         │                                                                        │
         │   378 │   │   │   │   list_cmd = "host-serial:{}:list-forward".format( │
         │   379 │   │   │   c.send_command(list_cmd)                             │
         │ ❱ 380 │   │   │   c.check_okay()                                       │
         │   381 │   │   │   content = c.read_string_block()                      │
         │   382 │   │   │   for line in content.splitlines():                    │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │        c = <adbutils._AdbStreamConnection object at                │ │
         │ │            0x000001C32F8A5088>                                     │ │
         │ │ list_cmd = 'host-serial:emulator-5554:list-forward'                │ │
         │ │     self = <adbutils.AdbClient object at 0x000001C31FBECFC8>       │ │
         │ │   serial = 'emulator-5554'                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         │                                                                        │
         │ D:\AzurLaneAutoScript\toolkit\lib\site-packages\adbutils\__init__.py:1 │
         │ 68 in check_okay                                                       │
         │                                                                        │
         │   166 │   │   data = self.read_string(4)                               │
         │   167 │   │   if data == _FAIL:                                        │
         │ ❱ 168 │   │   │   raise AdbError(self.read_string_block())             │
         │   169 │   │   elif data == _OKAY:                                      │
         │   170 │   │   │   return                                               │
         │                                                                        │
         │ ╭────────────────────────────── locals ──────────────────────────────╮ │
         │ │ data = 'FAIL'                                                      │ │
         │ │ self = <adbutils._AdbStreamConnection object at                    │ │
         │ │        0x000001C32F8A5088>                                         │ │
         │ ╰────────────────────────────────────────────────────────────────────╯ │
         ╰────────────────────────────────────────────────────────────────────────╯
         AdbError: unknown host service

**Comment by LmeSzinc** [comment]
雷电模拟器的 serial 会在 `emulator-5554` 和 `127.0.0.1:5555` 之间横跳，两个都试试
再确认是否已经在模拟器的设置中打开 ADB
雷电模拟器爱搞事情，直接换模拟器也是可以的
