### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by qpzm-oss** [LmeSzinc/AzurLaneAutoScript#913]
![T5SCKHHTZVB`7S2~T9T8LO0](https://user-images.githubusercontent.com/63945266/151690562-6a1af996-2759-44d0-ac4e-39bc09935007.png)

**Comment by LmeSzinc** [comment]
> 在提问题之前至少花费 5 分钟来思考和准备，才会有人花费他的 5 分钟来帮助你

描述你遇到的问题

**Comment by qpzm-oss** [comment]
最下面不是报错说缺少东西吗，运行到这里卡住了

**Comment by 18870** [comment]
#919
