### ISSUE TITLE
特别作战每日15次

### ISSUE THREAD

**Issue by ShiroRan** [LmeSzinc/AzurLaneAutoScript#914]
### 解决方案

活动特别作战每日15次和ex

### 其他内容

![image](https://user-images.githubusercontent.com/63772901/151695789-14985aa5-5da4-421b-90d9-16aeb5216250.png)

**Comment by LmeSzinc** [comment]
已经有了，在 `每日任务` - `共斗活动每日`
EX一般都不打的，PT/油耗比还不如低耗困难

**Comment by AnaheimEX** [comment]
请问困难无限刷的话，该如何设置，我在难度过滤器里把normal 和 easy都去了。但是共斗就跑到等待中了

**Comment by LmeSzinc** [comment]
@AnaheimEX 出击 - 共斗活动
