### ISSUE TITLE
alas可以适配win11自带的安卓虚拟机吗

### ISSUE THREAD

**Issue by NightRain7** [LmeSzinc/AzurLaneAutoScript#915]
### 你的功能请求是否与问题有关？

如题，我自己对win11的wsa和alas进行了尝试
通过教程，我找到了win11虚拟机的adb，并与alas进行连接
但是会在分辨率要求上面错误，请问可以增加win11的适配功能吗

**Comment by LmeSzinc** [comment]
#669  #884
