### ISSUE TITLE
大世界可能会错过明石商店

### ISSUE THREAD

**Issue by hephooey** [LmeSzinc/AzurLaneAutoScript#916]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

开荒的时候自律寻敌好像不会最后移动到明石旁边，而是会在捡到最后的宝箱，显示海域压制完成的时候停止，如果明石不是刚好在旁边就会变成 “No akashi on this map” 因为 predict_akashi 只搜索相邻的格子。手动再点自律寻敌也不会移动。感觉除了遍历整个地图没有什么好的解决方案。我没有 5000 油买记录仪，也许买了自律行为会不一样。

### 如何复现

1. 开荒时遇到明石商店
2. 点击 自律寻敌
3. 自律寻敌在海域压制完成时结束
4. 没有停在明石旁边

**Comment by 18870** [comment]
明石旁边的四个格子是一个最低优先级的隐藏事件，舰队走过任意一个时**游戏**就认为这个商店已经买过了，清除隐藏事件避免自律重新走到明石旁边
自律过程中经过了这四个格子之一就会导致隐藏事件清除，最后就不会去明石旁边

**Comment by hephooey** [comment]
这个解释真内行！走过明石没有停下也会清除事件吗？还是必须是战斗或者捡物资的时候停在明石旁边？
如果只有途中经过明石才会导致最后不访问明石，或许可以在走路的时候拼命截图找明石，发现就走过去，如果没有发现就最后搜索周围。大概对机器要求会比较高。

**Comment by LmeSzinc** [comment]
在 #1130 中已解决
