### ISSUE TITLE
安装时出现问题

### ISSUE THREAD

**Issue by aic-o** [LmeSzinc/AzurLaneAutoScript#917]
![屏幕截图 2022-02-01 183738](https://user-images.githubusercontent.com/98812543/151953634-85499133-df0a-4a14-9f06-e8c6c321e33a.png)
deploy两条已修改安装到这里停了。

**Comment by LmeSzinc** [comment]
> **[设置模拟器](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_cn#%E8%AE%BE%E7%BD%AE%E6%A8%A1%E6%8B%9F%E5%99%A8)**
> 
> 如果你使用的是蓝叠模拟器或雷电模拟器，你还需要在模拟器设置中打开 ADB。

**Comment by aic-o** [comment]
解决了，多谢。
