### ISSUE TITLE
安装后启动白屏

### ISSUE THREAD

**Issue by Guanchang3** [LmeSzinc/AzurLaneAutoScript#918]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

通过alas.exe安装正常，启动后白屏，尝试使用了ctrl+R，无反应

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

也有可能是权限问题，安全中心内并没有将alas.exe列入黑名单

### 截图

![network截屏8](https://user-images.githubusercontent.com/48749711/152327696-9b10cd09-a863-4826-9e12-52e88fb58030.png)
![console截屏2](https://user-images.githubusercontent.com/48749711/152327708-512b3802-dabe-43a5-907e-56172e377b63.png)
![whole7](https://user-images.githubusercontent.com/48749711/152327833-64611ac9-6f78-4201-a823-7f9d1975b253.png)

**Comment by 18870** [comment]
> 我已经搜索了现有的 issues

[#876 ](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/876#issuecomment-1011963386)

**Comment by Guanchang3** [comment]
> > 我已经搜索了现有的 issues
> 
> [#876 ](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/876#issuecomment-1011963386)

多谢老哥提醒，之前搜白屏关键字没看到是我瞎了><
