### ISSUE TITLE
7-2寻路寻不动

### ISSUE THREAD

**Issue by MrGuoRanDuo** [LmeSzinc/AzurLaneAutoScript#92]
![image](https://user-images.githubusercontent.com/57265425/87329575-be1c8700-c569-11ea-9ec9-1b4a662bade8.png)
![image](https://user-images.githubusercontent.com/57265425/87329799-1bb0d380-c56a-11ea-94f0-6fb566178732.png)

**Comment by LmeSzinc** [comment]
先打完这一场或者撤退, 再启动.
我忘记在README里说这件事了

**Comment by MrGuoRanDuo** [comment]
好的
