### ISSUE TITLE
道中和boss战不会换队，一队打到底

### ISSUE THREAD

**Issue by he110W0r1d-shell** [LmeSzinc/AzurLaneAutoScript#927]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

没出error，也不算bug，就很怪。已经选择了一队道中二队boss，实际在打的时候总是一队打到底。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

应该换队的，结果没换。

### 截图

下面是我的选项，不知道哪里有问题。

![tmpE2CB](https://user-images.githubusercontent.com/60465638/152972645-3b596d8a-2635-4bfd-a967-6523c255be3f.png)
![tmp9CC8](https://user-images.githubusercontent.com/60465638/152972643-2a18631e-855f-4d63-94b1-833f67e4b9ce.png)

**Comment by LmeSzinc** [comment]
低级图不分队，低级图包括6章及以下、所有5战及以下的地图。

**Comment by he110W0r1d-shell** [comment]
好哒，谢谢解答呀😘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月8日(周二) 晚上9:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LmeSzinc/AzurLaneAutoScript] 道中和boss战不会换队，一队打到底 (Issue #927)




 
低级图不分队，低级图包括6章及以下、所有5战及以下的地图。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ares238** [comment]
原来如此，我还以为卡bug了呢
