### ISSUE TITLE
游戏会因为心情原因重启

### ISSUE THREAD

**Issue by kj326646302** [LmeSzinc/AzurLaneAutoScript#934]
### 你的功能请求是否与问题有关？

1.在我选过活动每日，还有主线后，每天早上一看都会重启过游戏，脚本会因为角色死亡或者运行过每日过后，心情计算错误，导致卡在进入战斗界面，显示是否要无视心情进入战斗那里，然后重启。
2.这是我个人请求，我在用手机脚本时，经常有那种低心情备用队伍使用，但是电脑这个低心情不能使用备用队伍。这个肝科研的时候用得着

**Comment by 18870** [comment]
1. 避免在每日中使用刷图的船，或者刷图队设置一定量的心情控制(>30)容错。角色死亡属于User mistake，你需要自己解决。
2. #576
