### ISSUE TITLE
期望新增个通知渠道，对于alas异常状态及时通知使用人

### ISSUE THREAD

**Issue by julystone** [LmeSzinc/AzurLaneAutoScript#936]
### 你的功能请求是否与问题有关？

会经常存在alas突然遇上异常了，于是卡停而用户不自知的情况，期望新增通知效果

### 解决方案

当前设想是用发送邮件方式，先做简单的，不贴报错日志，发生错误状态就往配置好了的email发送邮件。

可以往  【Alas设置 - 调试设置】 里头新增

**Comment by TwilightKHQ** [comment]
+1 也想要可以新增一个通知渠道
给到另外一个建议就是通过Push Plus推送到微信
给到一个参考实现[掘金签到](https://github.com/xiaojia21190/public_actions)，不会JS，希望大佬看看能不能加一下

**Comment by Coder-Sakura** [comment]
推荐下Server酱推送：https://sct.ftqq.com/

**Comment by LmeSzinc** [comment]
现有推送服务最大的问题是，它们的场景都是一对一的，并且这个 “一” 是自己，在 alas 里使用的话就需要用户去注册并申请某个平台的 apikey，这是比较麻烦的，只能是少部分爱折腾的人用。

现在理想的推送服务是：
一对多的，并且这个 “多” 是不确定的 Alas 用户。
Alas EN 用户也有一定占比，还需要在中国大陆内和中国大陆外都能推送，或者是两边选取各自的推送平台。

**Comment by Xm798** [comment]
如果希望进行一对多推送，且不需要用户申请其他平台的 API 的话，可以借助微信公众平台实现，但这要求 Alas 开发组拥有认证的微信服务号，成本较高；或者自行开发推送 APP，但显然，该方式开发成本更高，且用户使用的成本也会更高。

目前成熟且好用的推送服务非常非常多，自建推送平台的意义不大，例如：
- iOS 平台可以选择 Bark（开源）；
- iOS/安卓平台可以选择 Pushdeer（开源）；
- 微信用户可以使用自建企业微信应用，或者使用 Pushplus（仅需扫码获取一个 Token）。不再推荐 Server 酱，因为免费用户每天只能推送 5 条；
- Telegram 用户可以选择 Telegram Bot（国内国外均可用，全平台可用，仅需创建一个自己的 bot）；
- Discord 用户可以选择 Discord Webhook（海外用户使用的多一点）推送到 Discord 服务器内；
- 钉钉用户可以选择钉钉群机器人；
- QQ 用户可以选择借助 CQHTTP 推送到 QQ 群或者 QQ 个人号或者频道；
- IGOT；
- 邮件推送；
- 推送到任意 Webhook。

我的一个 [repo](https://github.com/Xm798/Genshin-Dailynote-Helper/blob/master/docs/README_ZH.md#%E6%8E%A8%E9%80%81%E6%96%B9%E5%BC%8F%E9%85%8D%E7%BD%AE) 用到了其中大部分的推送方式，或许可以当作一点参考。

**Comment by JeanbartBiubiu** [comment]
我认为可以使用邮箱自带的SMTP服务，相比其他方式，SMTP只需要去邮箱设置里申请个授权码，门槛并不高。

**Comment by BronyaSeele** [comment]
邮件推送适用面最广。

**Comment by Xm798** [comment]
> 我认为可以使用邮箱自带的SMTP服务，相比其他方式，SMTP只需要去邮箱设置里申请个授权码，门槛并不高。

为了方便的话，还可以直接接入 mailgun, sendgrid, sendcloud, submail 等服务商的服务，是个很合适的选择。

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/c71838b0918ba6930dcf71857f9f757c51b558d7
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Onepush-configuration-%5BCN%5D

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/cece2e67d35149037febaa3ee95aa03efa34f834
改了一下，现在用 yaml 格式的配置比较方便用户写
