### ISSUE TITLE
因误判 Items loading timeout ，无法在日服退役兑换商店购买任何物品

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#938]
https://user-images.githubusercontent.com/70339606/154488786-6511e6fa-4103-4800-822a-12e3ba527181.mp4

[2022-02-17_alas.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/8088867/2022-02-17_alas.txt)

视频中，商店过滤器已加入 BookRedT2 ，商店中也有T2红书，但 ALAS 不会购买商店中的红书。

推测问题出在商品识别上，在日志中可以见到大量 INFO | [Item detected] 0 ，这可能说明 ALAS 没有成功识别到任何商品。

**Comment by LmeSzinc** [comment]
需要游戏界面的截图

**Comment by DebuAqua** [comment]
> 需要游戏界面的截图来复现问题

只能提供今天已手动购买红书后的截图：

![com YoStarJP AzurLane_Screenshot_2022 02 17_21 20 00](https://user-images.githubusercontent.com/70339606/154490180-4e24c858-0c37-4fbc-9e3f-a562295ae10e.png)

**Comment by LmeSzinc** [comment]
日服的功勋图标比正常的大一圈，导致无法识别。

单独增加了一个功勋图标，在图片上测试通过。
