### ISSUE TITLE
没有找到Alas对 配置 的删除途径

### ISSUE THREAD

**Issue by LeviathanSE** [LmeSzinc/AzurLaneAutoScript#941]
### 你的功能请求是否与问题有关？

创建了多个配置,但实际只需要两个,想要删除掉多余的配置.

另外,使用VPN是否会影响脚本的正常运行?

### 解决方案

RT,添加对 配置 的删除途径

### 其他内容

![1](https://user-images.githubusercontent.com/65220720/154852586-51a576be-7eef-47a1-bdb2-82624fa544de.png)

**Comment by 18870** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/issues/687#issuecomment-953849913

**Comment by LeviathanSE** [comment]
谢谢.没有看到被关闭的issue.
