### ISSUE TITLE
大世界每月开荒遇到档案海域时就会导致出错停止

### ISSUE THREAD

**Issue by DebuAqua** [LmeSzinc/AzurLaneAutoScript#946]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

当每月开荒的目标海域也是档案海域时，脚本出错且停止

![2022-03-02_14-11-31-090788](https://user-images.githubusercontent.com/70339606/156331841-453d2451-4fe1-428d-bb0e-c4abb51a6394.png)

### 如何复现

月初重置大型作战后，在物资兑换商店购买档案坐标记录仪
使用每月开荒功能

### 预期行为

因无法进入大世界海域导致出错时，退出大世界，关闭每月开荒，执行调度器中的其他任务；或

无视档案海域，切换到探索海域；或

进入档案海域，档案海域压制后，恢复开荒流程

### 相关 Logs

[log.txt](https://github.com/LmeSzinc/AzurLaneAutoScript/files/8168278/log.txt)

**Comment by LmeSzinc** [comment]
日服需要更新 ZONE_ARCHIVE 和 SELECT_ARCHIVE

**Comment by LmeSzinc** [comment]
523f0fe8ca8d5db86e22c2e384d1c492e332e4ef
