### ISSUE TITLE
alas清理船坞后点击自律寻敌后没有进入战斗而卡住退出

### ISSUE THREAD

**Issue by chorblack** [LmeSzinc/AzurLaneAutoScript#947]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

清理船坞后点击自律寻敌，会卡在如下界面（这种应该是游戏bug），这时候由于长时间在这个界面脚本直接报错退出了，希望在这个地方加个判断，卡住了就重新点击

### 如何复现

有时候（一天遇到个十几次吧）
 清理船坞退出然后点击自律寻敌

### 预期行为

希望在这个地方加个判断，卡住了就重新点击

### 截图

![屏幕截图 2022-03-02 163619](https://user-images.githubusercontent.com/67499253/156360666-32339196-6da1-4363-97ac-fe7a4607468a.png)

https://user-images.githubusercontent.com/67499253/156360684-169395d7-f982-490c-830a-eb6b650c1839.mp4

能看清就行（）

**Comment by LmeSzinc** [comment]
这是碧蓝航线客户端的 bug，自律寻敌会罢工不运行，建议向官方反馈，在修复之前可以不使用自律寻敌。

**Comment by yhtojy** [comment]
其实在auto_search_combat.py 裡面原本就有_wait_until_in_map() 为了处理这个BUG
但是最近APP这BUG更严重
并不太好使
我直接弃疗让他多等4秒
            if self.handle_retirement():
                self.device.sleep(4)
                self._wait_until_in_map()
                continue

**Comment by LmeSzinc** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/blob/fbac07c710292b9ddd194ec750f426394fa83103/module/combat/auto_search_combat.py#L123-L125

可以尝试将这里改成：
```python
if self.handle_retirement():
    self.map_offensive()
    self._auto_search_confirm_low_emotion = True
    continue
```

我这边无法复现这个问题，需要有人测试一下

**Comment by yhtojy** [comment]
这几天使用没再遇到了
我这边修正前的发生率蛮高的
这个修正应该是有效的
感谢
