### ISSUE TITLE
希望加入演习时间自定义

### ISSUE THREAD

**Issue by MiraclesinWang** [LmeSzinc/AzurLaneAutoScript#949]
### 你的功能请求是否与问题有关？

感谢巨佬对碧蓝航线玩家作出的巨大贡献。
在使用AzurLaneAutoScript的过程中，对于“演习”模块我又一点小小的改进意见。
由于演习存在打得越晚，越容易拉开前面的人和自己的点数差距，胜利后获得的点数也就越高的情况（详见[演习-碧蓝航线WIKI](https://wiki.biligame.com/blhx/%E6%BC%94%E4%B9%A0#.E6.BC.94.E4.B9.A0.E7.A7.AF.E5.88.86)**演习积分**介绍模块），推迟进行演习更有利于获取海军元帅等高级军衔。
所以有部分玩家为了军衔会故意推迟演习，比如存10次演习机会，先等前面的玩家都把演习次数用掉，到11:50用掉5次，然后12:00再次获得5次，准备上海军元帅的时候连续使用15次。由于前面每次都跟比分差距更大的玩家对战，所以获得的积分也更高，最后上元帅也更容易。

### 解决方案

该功能的实现并不是很难，我自己也简单尝试了下。但是由于本人还在读研，代码规范化能力还很差，担心我的代码不符合您的代码管理规范，于是没有pull request。
希望大佬加入一行设置，比如允许自定义在每次刷新前/后多久进行演习。例如，设置为刷新前15分钟，则将“演习”模块的运行时间由本来的0:00-12:00-18:00更改为23:45-11:45-17:45。
如果大佬最近诸事缠身，也可以简单和我描述一下您的开发规范，由我来狗尾续貂，减轻一些您的工作量。

### 其他内容

演习积分计算公式（截自[演习-碧蓝航线WIKI](https://wiki.biligame.com/blhx/%E6%BC%94%E4%B9%A0#.E6.BC.94.E4.B9.A0.E7.A7.AF.E5.88.86)）：
![}U`YDXPKQYXZBNR{B~N2)ZC](https://user-images.githubusercontent.com/61409495/156883935-2bd3be78-1f77-4d7f-831d-7728fd52a464.png)

演习高分技巧（截自[演习-碧蓝航线WIKI](https://wiki.biligame.com/blhx/%E6%BC%94%E4%B9%A0#.E6.BC.94.E4.B9.A0.E7.A7.AF.E5.88.86)）：
![P)Q`_ I{C9YA$}PM$8_7 U5](https://user-images.githubusercontent.com/61409495/156883929-5fbe042f-470a-41bd-9a57-af89536f8350.png)

**Comment by LmeSzinc** [comment]
我觉得没有必要

1. 不少用户反馈，alas挂满基本能混到五星上将，偶尔能摸海军元帅，能得到绝大部分奖励，功勋后期完全溢出，没必要贪。
2. 平时改成 23:45-11:45-17:45，结算的时候又改回 0:00-12:00-18:00，反而消耗了你的更多时间，违背脚本节约生命的目标。

**Comment by MiraclesinWang** [comment]
感谢您的回答，我在[#951](https://github.com/LmeSzinc/AzurLaneAutoScript/pull/951)中上传了自己实现该功能的代码，由于开发能力欠佳且缺乏沟通，该代码存在诸多不美观，仅供参考。
