### ISSUE TITLE
希望加入退役排除布里

### ISSUE THREAD

**Issue by EasyRain** [LmeSzinc/AzurLaneAutoScript#950]
### 你的功能请求是否与问题有关？

勾选了退役sr之后，满船退役会将布里一起退役了，希望能加一个选择是否退役布里的功能

### 解决方案

最简单就是在分类里面不选择其他，就可以防止选择布里退役全部

**Comment by LmeSzinc** [comment]
使用 “一键退役” 而不是 “传统退役” 就不会退役布里了
