### ISSUE TITLE
使用主线图推图时，满足条件却没有开始打

### ISSUE THREAD

**Issue by C1C1D11974** [LmeSzinc/AzurLaneAutoScript#954]
### 你的功能请求是否与问题有关？

如题

### 解决方案

如题

**Comment by LmeSzinc** [comment]
> **在提问之前...**
>  我已经搜索了现有的 issues *
>  我在提问题之前至少花费了 5 分钟来思考和准备 *
>  我已经阅读了 Wiki 中的 常见问题(FAQ) *
>  我正在使用最新版的 Alas
> **描述你的问题**
> 简要描述你的问题
> 
> **如何复现**
> 重现该行为的步骤
> 
> 1. 前往 '...'
> 2. 点击 '....'
> 3. 滑动到 '....'
> 4. 出现问题
> 
> **预期行为**
> 简要描述你期望发生的事情
> 
> **相关 Logs**
> 请复制并粘贴任何相关的日志输出。
