### ISSUE TITLE
根据FAQ里设置ALAS控制手机不起作用

### ISSUE THREAD

**Issue by qbs233** [LmeSzinc/AzurLaneAutoScript#980]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

根据这个连接的方法设置的，但是还是不行
[https://mjjeduhk-my.sharepoint.com/:w:/g/personal/945444204_mjj_edu_hk/EUSaQz8IxBxClREgUrPl59sBvs2NYYaLqy1Ej4ci0xwJgw?rtime=drYqjrMP2kg](url)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
═══════════════════════════════════════════════════════════════════════════════════
                                      RESTART                                      
═══════════════════════════════════════════════════════════════════════════════════
INFO     13:52:14.748 │ [Screen_size] 1080x2340                                    
INFO     13:52:14.836 │ [Package_name] com.miui.home                               
WARNING  13:52:14.838 │ Received orientated screenshot, game not running           
INFO     13:52:14.853 │ <<< APP RESTART >>>                                        
INFO     13:52:14.856 │ App stop: com.bilibili.azurlane                            
INFO     13:52:14.932 │ App start: com.bilibili.azurlane                           
INFO     13:52:15.335 │ <<< APP LOGIN >>>                                          
INFO     13:52:17.166 │ [Screen_size] 2340x1080                                    
INFO     13:52:18.125 │ [Package_name] com.bilibili.azurlane                       
CRITICAL 13:52:18.128 │ Resolution not supported: 2340x1080                        
CRITICAL 13:52:18.130 │ Please set emulator resolution to 1280x720                 
CRITICAL 13:52:18.132 │ Request human takeover
```

### 截图

![image](https://user-images.githubusercontent.com/18738087/160268865-301455ba-ab0c-4599-99ed-a9dfb2c223b6.png)

![image](https://user-images.githubusercontent.com/18738087/160268870-75525b7a-17f5-4bee-9dff-3e6f547d2dcd.png)

**Comment by qbs233** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/FAQ_en_cn#how-to-use-alas-to-control-your-phone-%E5%A6%82%E4%BD%95%E7%94%A8alas%E6%8E%A7%E5%88%B6%E6%89%8B%E6%9C%BA

**Comment by LmeSzinc** [comment]
这部分是社区贡献的，不保证能用，~~还指向站外我都想打人了~~
在手机上运行就默认你有相关的知识了，否则不建议这么做

**Comment by thouger** [comment]
我遇到同样的问题,用了这个命令:adb shell wm size 720x1280,并且在一台手机上可以一台手机上不行,怀疑是系统原因,明天进行刷一次机

**Comment by thouger** [comment]
我又拿了一台手机做了测试,一共做了三台测试:
1. mate20x,鸿蒙2,没root,用的是adb有线,可以
2. nexus5,lineage不记得什么版本,adb devices找不到设备,怀疑没有驱动,分别用了linux系统和mac m1系统做了adb devices测试,最后借了别人Windows才找到,fastboot也是,但是借别人的有点麻烦,就不刷机了,因此用的是无线,不行
4. piexl 1,lineage不记得什么版本,用的是adb有线,可以,

所以重点怀疑是因为用了无线adb连接的原因,其次是因为手机问题

**Comment by LmeSzinc** [comment]
@thouger https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1316#issuecomment-1179560976
