### ISSUE TITLE
石油上限

### ISSUE THREAD

**Issue by JackyXu866** [LmeSzinc/AzurLaneAutoScript#987]
### 你的功能请求是否与问题有关？

执行委托任务时，如果石油达到上限不能接取委托，将会一直重复接取委托的动作。

### 解决方案

重复数次未奏效后，识别油量，若达到/接近上限，则推迟委托任务。

**Comment by LmeSzinc** [comment]
建议是打开几个出击任务把油消耗掉，或者是买咖喱

**Comment by yzanhua** [comment]
> 打开几个出击任务把油消耗掉

委托的优先级比出击任务高，会先卡在委托上
