### ISSUE TITLE
請問考慮抓句柄的方式操作嗎?

### ISSUE THREAD

**Issue by JohnAILove** [LmeSzinc/AzurLaneAutoScript#988]
### 你的功能请求是否与问题有关？

我之前也使用過ADB開發，但是感覺效率太慢了，有考慮改使用句柄的方式當作IO的工具嗎?

### 解决方案

使用句柄的方式當作IO的工具

**Comment by LmeSzinc** [comment]
不考虑

1. 现在 ADB 的速度已经很快了，这是在 8700k 夜神模拟器64位 7.0.0.8 上的性能测试结果，0.3s 的截图耗时已经足够让 Alas 像真人一样快了，0.1s 的截图耗时可以让 Alas 运行地比游戏加载还快

![benchmark](https://user-images.githubusercontent.com/37934724/161688612-8da4feb0-1ce1-4ad0-9caa-820ba5a8321f.png)

https://user-images.githubusercontent.com/37934724/161688918-9f17420f-e893-4ed3-987d-4a494e97830a.mp4

2. 调用 win32api 截图会给电脑使用带来极大不便，比如不能窗口不能最小化，不能缩放，是我坚决反对的。现在 Alas 和模拟器都可以最小化到托盘区，完全不用管，体验是不错的

**Comment by JohnAILove** [comment]
感謝回應，謝謝你跟我說你的考慮!
