### ISSUE TITLE
作战档案活动选择

### ISSUE THREAD

**Issue by MengNianxiaoyao** [LmeSzinc/AzurLaneAutoScript#995]
### 你的功能请求是否与问题有关？

作战档案无法自己选择想要的档案去挂机，会被强制选择最新的档案去挂机

### 解决方案

移除作战档案的自动选择功能，变为可以手动选择作战档案

### 其他内容

![QQ截图20220408200350](https://user-images.githubusercontent.com/103258286/162432023-e99f31bc-7486-4356-99fe-a5d8b661f94a.png)

**Comment by mka457** [comment]
请问q群多少
